### ISSUE TITLE
不错的工具，能否支持直接打开目录？

### ISSUE THREAD

**Issue by yeasy** [suziwen/markdownxiaoshujiang#10]
例如像gitbook默认每本书是一个目录，其中summary.md提供纲要。

直接打开该目录即打开这个工程，然后进行编辑？

**Comment by suziwen** [comment]
## 1.1.01 新功能
1. 客户端实现文件关联打开。window系统自动关联.md，.markdown两种扩展名。其他系统用户自己可进行修改文件关联，命令行执行内容：`./{app} {文件（夹）路径}`
