### ISSUE TITLE
linux版本建议添加图标与守护进程

### ISSUE THREAD

**Issue by Kashin-J** [suziwen/markdownxiaoshujiang#100]
如题,linux客户端建议添加图标和守护进程!

**Comment by suziwen** [comment]
编辑器一般退出就直接退出了，不需要添加守护进程。添加守护进程想做什么用的。

**Comment by Kashin-J** [comment]
应该是我没有表达清楚吧。
我把linux包下载下来之后，直接给权限运行了里面的Story-writer，但是它是在前台运行的，终端停止该命令或者关掉终端，程序就会停止。
我就是希望能解决一下这个问题。

**Comment by suziwen** [comment]
linux 因为发行版比较多，每个版本又不太一样，再加上自己觉得用linux的用户一般的操作应该是会的，也就没有处理太多。我自己用的fedora, 一般就是给它可以执行的权限后，然后直接文件夹里就可以双击运行了，不用打开命令行，可以自己在桌面添加快捷方式，指向这个可执行文件，双击后也是可以非命令行启动的。其他linux版本的操作估计也一样。

**Comment by Kashin-J** [comment]
按照你所说的，我在桌面添加了图标，双击打开后的确可以后台运行，但也确实希望能在终端不依靠其它工具可以在后他打开。
PS.我也使用的是Fedora
