### ISSUE TITLE
码云同步问题

### ISSUE THREAD

**Issue by qynx** [suziwen/markdownxiaoshujiang#1001]
同步到码云时 
保存失败: {"code":1009,"error":"服务器出错","orign":"Not Found"}
重新绑定也无效

**Comment by suziwen** [comment]
我这边正常，无法重现你说的情况

**Comment by qynx** [comment]
![Snipaste_2018-12-08_22-45-08.png](https://i.loli.net/2018/12/08/5c0bd92c1fa93.png)
