### ISSUE TITLE
图床转移问题

### ISSUE THREAD

**Issue by WuShaogui** [suziwen/markdownxiaoshujiang#1002]
最近七牛云经常出问题，想把图片转移到阿里云存储，每张图片都转移成功了，意思是通过转移后的链接可以成功访问到该图片，但是原文的链接没有被替换：

![image](https://user-images.githubusercontent.com/24794718/49135318-4f050700-f321-11e8-8d16-78155a9afc21.png)

**Comment by suziwen** [comment]
转换后，点击确定按钮，才替换原文章里相对应的链接。

**Comment by WuShaogui** [comment]
> 转换后，点击确定按钮，才替换原文章里相对应的链接。

不行，**图床转移感觉有大问题啊**，现在七牛云出了很大问题，博客上的图片全部访问不了，我想用小书匠如下法子解决，一点用都没有：
1.直接迁移到阿里云，如问题图示，先后点击全选->转换->确定，退出来后什么都没有变
2.将图片迁移到本地，再上传到阿里云，结果点击确定后，图片连接还是七牛云的

**Comment by suziwen** [comment]
看一下文章里的 `图片地址`是否和弹出层里 `转换前地址` 是否一样。系统在用户执行完`转换`后， 用户点击`确定`按钮时，就是通过对文章里的 `图片地址` 和 `转换前地址` 比较，如果字符完全一样，就替换成`转换后的地址`

**Comment by suziwen** [comment]
web 版已修复，客户端下个版本修复。

**Comment by WuShaogui** [comment]
好的，谢谢你的工作！-------- 原始邮件 --------主题：Re: [suziwen/markdownxiaoshujiang] 图床转移问题 (#1002)发件人：苏滋文 收件人：suziwen/markdownxiaoshujiang 抄送：WuShaogui ,Author web 版已修复，客户端下个版本修复。
