### ISSUE TITLE
重新打开md文件图片全部失效

### ISSUE THREAD

**Issue by wurenny** [suziwen/markdownxiaoshujiang#1004]
当前版本：1.10.0
不小心在小书匠中关闭了一个md文件，重新打开md里面图片全部失效，有啥办法恢复？
全部图片都报这个错，但我看软件的安装目录里根本没有images这个目录：
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/soft/Story/images/1543483129114.jpg

**Comment by suziwen** [comment]
图片是保存在内置数据库里的。

看看历史记录里还有没有

![image](https://user-images.githubusercontent.com/57370/49454901-1da8a180-f821-11e8-9976-6a714aa07fef.png)

**Comment by wurenny** [comment]
当时急用重装了新版本，把图片重复制了一遍。。
