### ISSUE TITLE
有序列表中含有无序列表，同步到Evernote中序号错误

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#101]
MarkDown举例如下：
```markdown
1. a
2. b
- d
- e
- f
3. c
```
小书匠预览中显示正常：
![image](https://cloud.githubusercontent.com/assets/7668825/10780444/73f67200-7d78-11e5-85c5-21937639ffc7.png)

但同步到Evernote中编号错误，无序列表后重新编号：
![image](https://cloud.githubusercontent.com/assets/7668825/10780456/8854bd38-7d78-11e5-969c-d1c7e2a78f0d.png)

**Comment by suziwen** [comment]
客户端1.7.1已经更新解决,可以到 http://soft.xiaoshujiang.com 下载

**Comment by youxunlong** [comment]
我目前的版本就是最新的
![c](https://cloud.githubusercontent.com/assets/12827520/12032095/5f81044a-ae4f-11e5-88cf-7abbf97044eb.png)

**Comment by suziwen** [comment]
我的还是不能重现，

这是我随便建的一篇，你试试有没有正常编号
[filename.txt](https://github.com/suziwen/markdownxiaoshujiang/files/73829/filename.txt)
