### ISSUE TITLE
那个象思维导图的树状图如何显示？

### ISSUE THREAD

**Issue by qdxyz** [suziwen/markdownxiaoshujiang#1010]
那个象思维导图的树状图如何显示？新建的文档里按说明文档里写不能出现，就是把说明复制到新文档里也出现不了，这是个很好的功能，请问这个软件用户文档能做这个图吗？如能语法是什么？谢谢！

**Comment by suziwen** [comment]
思维导图功能只有付费用户才能使用，免费用户只能在系统创建的手册文章内使用。
