### ISSUE TITLE
github 图床问题

### ISSUE THREAD

**Issue by ykgarfield** [suziwen/markdownxiaoshujiang#1012]
使用了 github 的图床功能，可以正常的操作，但是在文档预览中没有办法正常预览图片，只能显示为附件。但是用其他的 markdown 软件可以正常预览图片。

**Comment by suziwen** [comment]
可以在`设置>预览`里，把 `是否自动转换非图片扩展名为附件（自动识别jpg,jpeg,png,gif及无扩展名的文件为图片文件，其他的扩展名文件为附件）   ` 功能关闭。

**Comment by chenbofeng123** [comment]
没用呀。。还是识别为附件了
