### ISSUE TITLE
无法连接github

### ISSUE THREAD

**Issue by only-wjt** [suziwen/markdownxiaoshujiang#1015]
6.8.1无法绑定github，报错信息也看不到
![bug](https://user-images.githubusercontent.com/26518780/50258929-eb13c100-043c-11e9-91a7-4f935e3f27a3.png)

**Comment by suziwen** [comment]
这个应该是网络连接不到 github 服务器上引起的

**Comment by only-wjt** [comment]
> 这个应该是网络连接不到 github 服务器上引起的

对，我过了一会在登录就可以了
