### ISSUE TITLE
html属性配置attrs无法正常用

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#1016]
![image](https://user-images.githubusercontent.com/36830571/50369616-79ba4680-05d3-11e9-988b-807f54533243.png)
按照提供的Github上的编写样例写的几条，但是没有按照自动添加class实现。刚刚用，也不是很懂，是自己哪地方出问题了吗？
语法扩展中的`html属性配置(attrs)`与`html`都已经开了。

**Comment by suziwen** [comment]
把 `grammar_decorate` 也禁用掉， `decorate` 与 `attrs` 冲突， `decorate` 也是属性修改，需要用 `<!---->` 包裹. 
```
---
grammar_attrs: true
grammar_classy: false
grammar_decorate: false
---


# 测试{.aaa style="color:red;"}
```

**Comment by ghost** [comment]
> 把 `grammar_decorate` 也禁用掉， `decorate` 与 `attrs` 冲突， `decorate` 也是属性修改，需要用 `<!---->` 包裹.
> 
> ```
> ---
> grammar_attrs: true
> grammar_classy: false
> grammar_decorate: false
> ---
> 
> 
> # 测试{.aaa style="color:red;"}
> ```

好的，解决了，谢谢。再补充个问题，想给代码部分添加个不换行的属性，但是不知道怎么给`<code>`外的`<pre>`添加属性。直接在`java`后添加{class=“dd”}，小书匠会直接卡掉，动不了。加{id="dd"}的话，查看源代码是给code加，所以现在不知道怎么给code外的pre添加属性。

**Comment by suziwen** [comment]
代码块这个做了特殊处理，暂时没办法修改外层的 `<pre>` 标签，只能先通过文章自定义 css 或者全局 css 来设置。

或者直接对 `code` 进行  css 属性设置，  css 规则会自动覆盖掉上层 `<pre>` 的规则的

```
{#dd style="white-space: pre;"}
```

````
```{#dd style="white-space: pre;"}

world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow world hellow 
```
````

**Comment by suziwen** [comment]
现在还有个需要注意的是，如果开启行号显示功能，这些属性暂时就会失效。
后继版本我再调整一下规则

**Comment by ghost** [comment]
好的，谢谢，弄好了
