### ISSUE TITLE
本地图片保存在什么位置，导出Markdown笔记无法显示插入图片

### ISSUE THREAD

**Issue by MuseSmile** [suziwen/markdownxiaoshujiang#1017]
![](./images/1545635314892.png)  ./images图片是保存在哪里了？我导出Markdown文件时，所有图片都无法显示。

**Comment by suziwen** [comment]
这些图片保存在内置数据库里的。

导出 markdown 文本只能导出纯文本，没办法把图片带上去的。

可以选择导出 zip . zip 解压后里面就会有相应的图片了。

**Comment by MuseSmile** [comment]
漂亮，明白了。谢谢。
