### ISSUE TITLE
markdown渲染后的代码部分希望能加行号显示

### ISSUE THREAD

**Issue by Comdex** [suziwen/markdownxiaoshujiang#102]
如题，不是编辑器的行号显示而是文本内的代码在渲染是显示行号

**Comment by suziwen** [comment]
这个已经实现了,可以在`设置`里的`语法扩展`标签里选中`段代码显示行号`,也可以在元数据里添加语法`grammar_codeLinenums`,或者直接在 ` java?linenums`
