### ISSUE TITLE
预览字体和编辑的字体不统一

### ISSUE THREAD

**Issue by wangwei135** [suziwen/markdownxiaoshujiang#1020]
预览字体和编辑的字体不统一,预览的字体太小了.
而且导航栏的字体设置为微软雅黑,却一点用都没有,原来的字体看起来好丑
这个编辑器真的太烂了

**Comment by MuseSmile** [comment]
做开发的，有一点共性就是软件都是不断完善的。我觉着这个软件挺好的，功能挺强大，20元一年，也很太便宜，当然免费版也挺好的。我纯粹是为了赞助这么优秀的软件。
