### ISSUE TITLE
建议：建议为给github的 markdown 文件生成目录(toc)

### ISSUE THREAD

**Issue by Ryanjiena** [suziwen/markdownxiaoshujiang#1026]
在编写 github 项目时，有时候会编写各种 README.md 等 markdown 文件，但是 github 默认是没有目录的。github的渲染方式与一些常用博客渲染方式不相同，导致在使用时有些麻烦。

**Comment by suziwen** [comment]
可以使用[静态目录功能](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-3-1%20%E9%9D%99%E6%80%81%E7%9B%AE%E5%BD%95%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D.md)。

![image](https://user-images.githubusercontent.com/57370/50747230-cf4a5080-126d-11e9-9290-730c2b1f962a.png)
