### ISSUE TITLE
Gitlab多处同步出现问题

### ISSUE THREAD

**Issue by yinglovezhuzhu** [suziwen/markdownxiaoshujiang#1027]
首先非常感谢小书匠，一款非常不错的Markdown编辑器。在使用过程中发现一个问题，就是绑定了Gitlab，同步过程中会出现问题，一部电脑上同步到gitlab的内容，在另一部电脑怎么也无法同步下来，点了强制刷新也不行，仍然是旧的内容。

**Comment by suziwen** [comment]
现在发现有个 bug, 就是根目录下的文件，强制更新会创建一个新的文件到文件列表上，不是在原有的文件基础上更新。

----------

然后我这边试了下，没办法重现你说的情况，即使是根目录下的文件，虽然新创建了一条记录，但新的记录是会同步最新的。你看一下是不是只有特定的文件才会出错，还是 gitlab 上的所有文件都无法同步下来?或者给出能重现的步骤。

**Comment by yinglovezhuzhu** [comment]
> 现在发现有个 bug, 就是根目录下的文件，强制更新会创建一个新的文件到文件列表上，不是在原有的文件基础上更新。
> 
> 然后我这边试了下，没办法重现你说的情况，即使是根目录下的文件，虽然新创建了一条记录，但新的记录是会同步最新的。你看一下是不是只有特定的文件才会出错，还是 gitlab 上的所有文件都无法同步下来?或者给出能重现的步骤。

我是在电脑A上编辑了文档，同步到Gitlab上面，Gitlab上面的文档是最新的了，当我在电脑B上进行更新的时候，发现更新不下来，所以的文档都会这样。但是在单台电脑进行提交和更新，都没有问题。

**Comment by suziwen** [comment]
电脑A上编辑保存到 gitlab, 然后用电脑 a 上新开一个会话的浏览器，访问小书匠 web 版本，重新绑定 gitlab，这时能从 gitlab 拿下来最新的文件吗？
电脑B 网络有没有被阻止访问 gitlab ？

**Comment by yinglovezhuzhu** [comment]
> 电脑A上编辑保存到 gitlab, 然后用电脑 a 上新开一个会话的浏览器，访问小书匠 web 版本，重新绑定 gitlab，这时能从 gitlab 拿下来最新的文件吗？
> 电脑B 网络有没有被阻止访问 gitlab ？

我各种尝试，发现要先关闭打开的文档列表里面的对应文件（点删除按钮），然后同步，再在同步文件列表中打开文件，可以同步到，这个会不会是缓存的问题？更新了文件没有同步到 缓存中？

**Comment by suziwen** [comment]
我估计明白了。

你的强制刷新是刷新浏览器？

这个要自己手动右键更新本地缓存，不是点浏览器的刷新按钮。

![image](https://user-images.githubusercontent.com/57370/51290065-a419eb00-1a3d-11e9-9107-c738a8624acc.png)

-----------

或者

把文件列表里的文档归档或者删除，再点击对应的 gitlab 文件，才会自动抓取 GITLAB 最新的文件。
