### ISSUE TITLE
腾讯云的地域能多加几个吗？

### ISSUE THREAD

**Issue by oysz2016** [suziwen/markdownxiaoshujiang#1031]
之前配置腾讯云图床，很久都没成功。才发现可以选的地域不属于任何一个选项，可以选的地域能多加几个吗？

**Comment by suziwen** [comment]
嗯，应该是腾讯后面增加了很多新的服务器，这边没及时更新这些服务器列表。

考虑后面版本增加一个可以自己输入 上传服务器地址的功能。

**Comment by suziwen** [comment]
新版7.3.0 版本提供了自定义输入地域功能
