### ISSUE TITLE
段代码预览区字符对齐的问题

### ISSUE THREAD

**Issue by zmcui** [suziwen/markdownxiaoshujiang#1033]
在对代码插入字母和符号组成的图标， 如下
希望能够在预览区对齐， 但是字母和字符不等宽，所以格式就错乱了
请问有什么办法使段代码的预览字符对齐
谢谢
		            :                :
		            :                :
		            :                :
		+-------+   :   +--------+   :   +-------+
		|       |   :   |        |   :   |       |
		|       |   :   |        |   :   |       |
		| CPU 1 |<----->| Memory |<----->| CPU 2 |
		|       |   :   |        |   :   |       |
		|       |   :   |        |   :   |       |
		+-------+   :   +--------+   :   +-------+
		    ^       :       ^        :       ^
		    |       :       |        :       |
		    |       :       |        :       |
		    |       :       v        :       |
		    |       :   +--------+   :       |
		    |       :   |        |   :       |
		    |       :   |        |   :       |
		    +---------->| Device |<----------+
		            :   |        |   :
		            :   |        |   :
		            :   +--------+   :
		            :                :

**Comment by suziwen** [comment]
自定义 css 样式

```
.hljs{
   word-spacing: initial;
}
```

**Comment by zmcui** [comment]
解决了，谢谢
