### ISSUE TITLE
有道云能否修复下

### ISSUE THREAD

**Issue by Angolar** [suziwen/markdownxiaoshujiang#1035]
现在有道云无法使用了，能否尽快修复下。
![image](https://user-images.githubusercontent.com/9522956/51242264-7f306400-19ba-11e9-833d-3b07db6f27f9.png)

**Comment by suziwen** [comment]
这个是有道云那边自己的 api 没有跟进他们自己的产品引起的。暂时没办法修复，现在只能提供保存功能，无法提供读取功能。

**Comment by Angolar** [comment]
> 这个是有道云那边自己的 api 没有跟进他们自己的产品引起的。暂时没办法修复，现在只能提供保存功能，无法提供读取功能。

有道云没有公布新的产品的api是吗？有道云公布了之后就会修复么

**Comment by suziwen** [comment]
是的
