### ISSUE TITLE
加粗预览存在问题，实际效果无影响

### ISSUE THREAD

**Issue by SakuraYuki** [suziwen/markdownxiaoshujiang#1040]
![image](https://user-images.githubusercontent.com/15727209/51587571-26ae1900-1f1c-11e9-8514-fee4a989aa82.png)

【版本】v6.7
【系统】Windows 10 家庭版 1803

如图，加粗后的内容在编辑处渲染不对，实际上效果没有问题，下面是部分原文

```markdown
### 循环的威力

循环（for、while）是编程最常用到的功能，我学 Java 时接触的第一个循环的内容就是双循环打印九九乘法表，对初学者来说一次性搞定不大可能，我重试了几十次才打印出来争取的效果。

像求和函数，就是把数组中的数循环累加；求最大值，也是循环数组依次对比，找出最大的数。

因为不确定数组的长度，所以像带有循环的方法，时间复杂度并不是 **O(1)**，未知规模我们一般认为是 n，所以
```

**Comment by SakuraYuki** [comment]
找到问题了，如果在加粗代码后面跟随中文逗号【，】的话，就会出现这个问题，如果输入一个空格隔开，就可以解决这个问题，但目前来看这个应该是软件的问题

**Comment by typist-coder** [comment]
@SakuraYuki 我这里没有这个BUG（本机v6.7.0，网页都是）

**Comment by SakuraYuki** [comment]
> @SakuraYuki我这里没有这个BUG（本机v6.7.0，网页都是）

是否是编辑器主题的问题呢？我是用的主题是 `Solarized Light`。

**Comment by suziwen** [comment]
这个 web 版本在 6.8.2 升级了 codemirror 里的 markdown 规则，所以半角的逗号是可以区分出来的。

http://soft.xiaoshujiang.com/logs/version/v_6_8_2
```
3. codemirror 编辑器斜体显示问题 #1013
```

客户端版本还没有提供下载。

**Comment by SakuraYuki** [comment]
好的，那我关闭这个 issue 了
