### ISSUE TITLE
绑定印象笔记时，能不能设置印象笔记为只读，仅能通过小书匠来编辑

### ISSUE THREAD

**Issue by starsky9527** [suziwen/markdownxiaoshujiang#1042]
绑定印象笔记时，能不能设置印象笔记为只读，仅能通过小书匠来编辑。

因为搜索过慢，经常去印象笔记上搜索并阅读，但经常触发印象的编辑功能，然后就悲催了，笔记经常同步不了。

**Comment by suziwen** [comment]
在绑定界面里，有对印象笔记设置选项，可以控制只读保护。
![image](https://user-images.githubusercontent.com/57370/51719469-90e1cd80-2084-11e9-9f1e-45df48426832.png)

**Comment by starsky9527** [comment]
现在笔记是本地存储的，图片可以随意复制。绑定印象后，图片不能跨笔记复制了，这个很难受，迁移成本高多了，有什么好的方法吗

**Comment by suziwen** [comment]
可以使用 `另存为` 功能
![image](https://user-images.githubusercontent.com/57370/51783237-0d9ea580-2172-11e9-9b82-f7c16502ccf0.png)

**Comment by suziwen** [comment]
新版7.3.0 版本提供了复制 markdown 文章内容时，如果内容里有图片资源，自动复制到新文章时，也一起复制过来的功能
