### ISSUE TITLE
小书匠加载印象笔记文件列表出现错误

### ISSUE THREAD

**Issue by linut** [suziwen/markdownxiaoshujiang#1044]
提示如下：
![image](https://user-images.githubusercontent.com/15168038/52148191-eb41e600-26a3-11e9-98a2-fc9c1f9ac447.png)
1. 网络测试没问题
2. 印象笔记（6.17.8.540）和小书匠（6.8.8）都更新到最新版本
3. 本地和Chrome上都测试了，都有这个问题

**Comment by linut** [comment]
搜索了下，跟问题
#774 
很像，猜测应该也是印象笔记服务器拒绝了小书匠的访问请求。
尝试解决办法，重新获得印象笔记授权，获取token。
解决办法：
#532 
很遗憾，网络端和本地都获取失败，软件提示“验证用户失败，请确认token是否有效”
![image](https://user-images.githubusercontent.com/15168038/52150223-41198c80-26aa-11e9-8f3c-61785c63bacd.png)

**Comment by linut** [comment]
最新，上了个厕所，然后获取成功。这么玄学的吗？
啥原因？数据库重启了？我也不知道。不知道之后会不会还出现这个问题。

**Comment by linut** [comment]
时隔一个小时又出现了这个问题
猜测原因：因为今天通过小书匠整理文件，所以需要不断的访问印象笔记，上传下载MD文件，是服务器出于自我保护短暂停止了授权吗？这才多点访问量。

**Comment by linut** [comment]
去洗了个澡，回来果然可以绑定上了。 那么这个问题很可能的原因就是印象笔记的服务器限制了第三方软件在单位时间内单台设备的访问量，超过访问量就会短时间内断开授权。猜测大概是这样吧。
那整理文件等需要多次访问数据库的话，还是直接在印象笔记上操作比较好。小书匠就用来平时写东西之类的。
不过对比小书匠和印象笔记的界面来说，印象笔记好像更适合分类整理文件，但不利于写MD格式的文本，多屏除外。另外说一句，小书匠的模板非常好用。
因为印象笔记也支持了MD格式笔记，但是并不能和小书匠里MD格式笔记融合，保存在印象笔记里还是只能预览界面，不好直接修改，这点很遗憾。

**Comment by suziwen** [comment]
以前 evernote 有提供 develop token 的时候，可以自己创建一个不受访问限制的 token。现在没有办法，生成的 token 在一定时间内访问太多次 evernote 服务器, 就会自动被限制，需要等待 `rateLimitDuration` 秒后才能再次访问。

https://dev.yinxiang.com/doc/articles/rate_limits.php
