### ISSUE TITLE
每次登陆都需要重新绑定一次码云

### ISSUE THREAD

**Issue by jilaohome** [suziwen/markdownxiaoshujiang#1047]
以前只需要登录码云的账号授权,现在每次都需要我再生成一个token

总之,每次登录都需要我绑定一次码云

{
    "appCodeName": "Mozilla",
    "appName": "Netscape",
    "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "cookieEnabled": true,
    "language": "zh-CN",
    "platform": "Win32",
    "product": "Gecko",
    "productSub": "20030107",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
    "vendor": "Google Inc.",
    "vendorSub": ""
}
{
    "apm": {
        "storePlugin": "",
        "font": ""
    },
    "epm": {
        "editorType": "codemirror",
        "theme": "ace/theme/solarized_light",
        "cm_spellChecker": false
    },
    "ppm": {
        "previewLayoutPosition": "east"
    }
}

**Comment by suziwen** [comment]
刷新一下，然后重新绑定码云， `7.0.0` 版本开始使用用户自己创建 access token 的来访问 gitee 仓库。

***************

这个主要是码云官方限制了 token 的有效时间，不过如果是用户自己创建的token ,就不会有过期时间的限制。

https://gitee.com/oschina/git-osc/issues/IOLRW
