### ISSUE TITLE
本地保存

### ISSUE THREAD

**Issue by lywschxd** [suziwen/markdownxiaoshujiang#105]
绑定的是本地文件系统，编辑完成之后，点击保存和另存为均无效，点击新建会快速弹出两次选择保存的弹框，然后快速消失，黑屏。左边看是新建成功了的，但是无法打开或者删除。使用的是mac客户端

**Comment by lywschxd** [comment]
无法正常退出，只能强制退出。重新打开后绑定的文件夹恢复到默认，只有重新选择。这次保存又可以正常操作。

**Comment by suziwen** [comment]
#81

**Comment by lywschxd** [comment]
我遇到的问题不一样，本来我设定的文件夹下面是有其他文档的，但是每次打开之后发现里面什么都没有，刷新也没有用。然后只有在绑定里面取消绑定，然后重新绑定，才发现设定的文件夹下有其他文件了。
这个是大开小书匠的时候
![1](https://cloud.githubusercontent.com/assets/3980884/10861317/03def1be-7fb6-11e5-857a-090392bb7836.png)
这个是重新绑定的时候（发现目录是默认的了）
![2](https://cloud.githubusercontent.com/assets/3980884/10861323/262e5372-7fb6-11e5-8659-2be0293f140c.png)
这个是重新绑定之后
![3](https://cloud.githubusercontent.com/assets/3980884/10861324/32cb4b08-7fb6-11e5-800c-635257398f93.png)

重新打开之后又变成第一张图片那样了。

**Comment by suziwen** [comment]
客户端1.7.1已经更新,可以到 http://soft.xiaoshujiang.com 下载
