### ISSUE TITLE
能否同时绑定多个第三方数据操作界面

### ISSUE THREAD

**Issue by starsky9527** [suziwen/markdownxiaoshujiang#1050]
由于绑定印象后，有些笔记无法正常显示，这就有点尴尬了，所以能否同步到多个第三方数据库，比如说同时同步到印象、同步到本地，这样有个备份，安全点。

**Comment by suziwen** [comment]
同时保存在多个第三方数据，这个暂时不会考虑。主要是保存这个操作需要消耗比较多的资源，特别是把 markdown 文章转换成富文本格式。还有就是不同的第三方数据存储格式又不一致，有些只需要 markdown 原文，有需要富文本，有些又需要特殊过虑处理的富文本，纯文本的 markdown 还需要对图片等资源文件进行特殊处理，多个不同第三方数据同时保存时反而消耗大量系统资源，增加保存时间。

-------------

更重要的是用户在小书匠上编辑的文章，都是先直接保存在小书匠的内置数据库里，属于离线优先的数据。也就是当你发现同步到第三方数据失败后，只要不对小书匠客户端内置数据库重置，都可以到当时使用的小书匠客户端上找到。
