### ISSUE TITLE
解析为知笔记markdown数据有问题

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#1051]
以前用的是为知笔记的md来写的笔记，现在如果用小书匠来看以前的笔记，总是出现问题，主要是自身的图片纹理。
我做了个简单的测试，这是在为知笔记客户端里自动down下来的笔记文件。
解压后，里面的ziw后缀的文件就是为知的笔记文件，其实它也是个zip文件，需要再解压一次得到笔记源文件。

xiaoshuj小书匠的结果：
![image](https://user-images.githubusercontent.com/6416516/53295076-fd8beb80-382d-11e9-9553-34c0965be721.png)

实际为知笔记里的结果：
![image](https://user-images.githubusercontent.com/6416516/53295079-0bda0780-382e-11e9-8789-ec33af17cc6c.png)

简单的理解是小书匠对于为知笔记本身的图片转换不正确导致的问题
![image](https://user-images.githubusercontent.com/6416516/53295086-2b713000-382e-11e9-9bac-fb9455381d39.png)

最后那个img图片是display:none属性的，但是在小书匠里却显示出来了。前面的markdown语法的图片
![](index_files/8c8a466c-deb6-42f6-85f9-5ab89fdeccc5.jpg)却xian显示找不到资源
![image](https://user-images.githubusercontent.com/6416516/53295098-7db25100-382e-11e9-8dd0-389188a785f7.png)

用的是为知V2版本的同步，不过觉得应该跟这个也没关。
希望得到修复，谢谢~

[插件测试.md.zip](https://github.com/suziwen/markdownxiaoshujiang/files/2897571/md.zip)

**Comment by suziwen** [comment]
可以下载 7.1.0 版本了，这个版本对为知文章里，使用 editor.md 插件 生成的 md 文档做了适配。
