### ISSUE TITLE
每次打开提示登录

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#1053]
![image](https://user-images.githubusercontent.com/20160766/53339666-f35b1180-3941-11e9-9d52-1e6e2974f801.png)
每次打开都提示这个界面的登录，用自己的账号密码登录失败。

**Comment by suziwen** [comment]
这个是代理的认证过期弹出来的提示。

可以将小书匠客户端升级到 7.0.0 版本，该版本解决了代理认证过期的情形。如果代理过期，就自动禁用代理功能。

老版本可以参考这里解决 #1028

**Comment by jeferwang** [comment]
> 这个是代理的认证过期弹出来的提示。
> 
> 可以将小书匠客户端升级到 7.0.0 版本，该版本解决了代理认证过期的情形。如果代理过期，就自动禁用代理功能。
> 
> 老版本可以参考这里解决 #1028

升级了最新版，还是会出现登录框

**Comment by suziwen** [comment]
嗯，我再看看，现在暂时先禁用代理，或者使用代理时不要改变认证。

**Comment by suziwen** [comment]
刚发了个7.1.0 版本，重新修复了下代理认证失败弹窗的问题。

**Comment by dsclub** [comment]
版本：7.3.0
系统：Win10 x64

同样的问题

是不是会员都有这个问题！不升级会员时没问题，升级了之后就出现问题了。这个真让人头疼，每次提示，而且无法消除，输入正确的用户名和密码还是如此。

这个问题基本快让我破功了。

**Comment by suziwen** [comment]
@dsclub 

你先把数据目录 移到其他地方，然后启动小书匠呢？

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```

**Comment by dsclub** [comment]
> 
> 
> @dsclub
> 
> 你先把数据目录 移到其他地方，然后启动小书匠呢？
> 
> ```
> Windows: %LOCALAPPDATA%/storywriter/
> Mac: ~/Library/Application Support/storywriter/
> Linux: ~/.config/storywriter
> ```

@suziwen 

是的，我已经把`AppData/Local/storywriter/`下的内容**清空**了。登录确实就没有问题了，但是此时我就不是会员身份了对吧？
然后我再进行登录，就在登录完成后，立刻会弹出该对话框**两次**！

![图像 008](https://user-images.githubusercontent.com/428316/57963747-bf4d2680-795b-11e9-849b-bd67d78c916d.png)

所以，这个问题还是无法解决！解决条件岂不是变成了*不登录小书匠，就没有弹出对话框提示！*

这个来自`https://data.xiaoshujiang.com`的提示，确实厉害！不过这个网址说是被维护？

**Comment by suziwen** [comment]
你的网络连接要走代理？这个是代理服务器要的认证，不是小书匠帐户系统的用户。

https://data.xiaoshujiang.com 是你开启了数据同步服务功能。

**Comment by suziwen** [comment]
@dsclub 你再试一下。我刚才排查了下 数据同步服务器，有个错误，可能是引起你那边出现这个情况的原因

**Comment by dsclub** [comment]
@suziwen 

OK，解决了~~~



> 
> 
> @dsclub 你再试一下。我刚才排查了下 数据同步服务器，有个错误，可能是引起你那边出现这个情况的原因


我这个时间赶得也太巧了~~~
