### ISSUE TITLE
导出PDF，有水印？

### ISSUE THREAD

**Issue by bboqq** [suziwen/markdownxiaoshujiang#1054]
已付费用户

**Comment by suziwen** [comment]
展开面板，里面有一个水印选项，

![image](https://user-images.githubusercontent.com/57370/53487408-7c02ba80-3ac6-11e9-8fdc-8ffa1d3ed2a9.png)


![image](https://user-images.githubusercontent.com/57370/53487424-8329c880-3ac6-11e9-80ac-dba59c471954.png)
