### ISSUE TITLE
直接拖入图片到文章中无法修改description

### ISSUE THREAD

**Issue by MandyCh** [suziwen/markdownxiaoshujiang#1055]
点击插入图片按钮插入图片可以修改enter  description here那里，但是今天试了一下直接拖入图片到文章中可以显示图片，但是无法修改description

![snipaste_2019-02-28_09-44-14](https://user-images.githubusercontent.com/26193879/53536294-c45ebe80-3b40-11e9-8a6f-78028655c584.png)

![snipaste_2019-02-28_09-40-28](https://user-images.githubusercontent.com/26193879/53536301-d2144400-3b40-11e9-87bc-0a22424da133.png)

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/53540664-65557580-3b51-11e9-8a07-40f667ad9d5c.png)

**Comment by suziwen** [comment]
7.1.0 版本调整了下拖拽图片生成的 markdown 格式，直接把图片名称做为 alt 值，而不是以前的 title 值。避免引起使用的混乱。
