### ISSUE TITLE
网页版同步失败，客户端最新版打开弹出登录框

### ISSUE THREAD

**Issue by jeferwang** [suziwen/markdownxiaoshujiang#1056]
![image](https://user-images.githubusercontent.com/19504907/53566151-5f35b800-3b96-11e9-9682-48ddb2975aa0.png)
如图，网页版直接失败
客户端每次打开都弹窗登录
![image](https://user-images.githubusercontent.com/19504907/53566252-9d32dc00-3b96-11e9-8a11-01fe12ce2cc4.png)

**Comment by jeferwang** [comment]
已经开了会员的

**Comment by suziwen** [comment]
这个是代理的认证过期弹出来的提示。
#1028

**Comment by suziwen** [comment]
刚发了个7.1.0 版本，修复了下代理认证失败弹窗的问题。
