### ISSUE TITLE
版本 7.0.0,经常编辑过程中自动关闭客户端

### ISSUE THREAD

**Issue by RonnyW0ng** [suziwen/markdownxiaoshujiang#1057]
无论是Linux 还是 Windows都一样, 绑定的是为知笔记的账号. 
文件字数一万六千个左右,图片不超过10张

**Comment by RonnyW0ng** [comment]
Windows 8.1 Pro && Ubuntu 18.04 
内存12G

**Comment by suziwen** [comment]
升级到 7.1.0 版本呢？

--------------

我在 7.0.0 和 7.1.0 版本里试着编辑一篇超过二万字，20多张的图片，都没有意外崩溃的情况，感觉应该是其他操作细节引起的崩溃。

----------

7.1.0 版本升级了底层 nwjs 到 0.36.2 版本，其中修改了一个容易引起崩溃的问题 

> Fix: File input crashes when click it second time. (nwjs/nw.js/issues/6968)

https://github.com/nwjs/nw.js/blob/nw36/CHANGELOG.md

不过感觉好像跟你这边引起的崩溃无关。

**Comment by RonnyW0ng** [comment]
先升级了7.1版本 再看看

**Comment by yinglovezhuzhu** [comment]
@suziwen 我电脑安装的是7.0.0，总提示有新版本7.1.0，可是到github和百度网盘下载，都没发现有7.1.0的文件

**Comment by suziwen** [comment]
刷新一下下载页面，浏览器有缓存。


-------------


https://github.com/suziwen/markdownxiaoshujiang/releases

**Comment by suziwen** [comment]
@yinglovezhuzhu

**Comment by yinglovezhuzhu** [comment]
@suziwen 从官网进去的只能是7.0.0，我在github上重新返回项目首页，然后点release就好了，你们看看是不是官网的链接没有更新
