### ISSUE TITLE
希望能支持修改mathjax配置文件的支持。

### ISSUE THREAD

**Issue by ericma15** [suziwen/markdownxiaoshujiang#1060]
现有的mathjax文件使用的默认配置项TeX-AMS-MML_HTMLorMML.js。我需要使用mathjax的扩展箭头功能，能有允许用户去编辑这个文件呢？

**Comment by suziwen** [comment]
这个现在暂时没有自定义配置的功能。

可以把你自己想要的配置先贴出来，使用了什么扩展 js 等，我看是否可以直接集成进去。

**Comment by ericma15** [comment]
extpfeil.js 这个是mathjax的一个箭头扩展包。之前有的md文件中有用到。
谢谢了

**Comment by suziwen** [comment]
新版7.3.0 版本提供了该扩展功能。
