### ISSUE TITLE
全屏之后不能够显示左右对比的图标

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1066]
全屏之后不能够显示左右对比的图标，我是windows10 系统，下载的是最新的版本

这是全屏的显示
![image](https://user-images.githubusercontent.com/37186266/55136555-ae591380-5169-11e9-834d-9807751a314b.png)

这是缩小之后出现了这个图标
![image](https://user-images.githubusercontent.com/37186266/55136621-e3656600-5169-11e9-8484-1d8c3803e433.png)

请问这是什么问题，是因为我的版本太新了吗，我是第一次用这个工具，刚刚冲了两年的会员

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/55139357-8d47f100-5170-11e9-9dcc-feaa65205c42.png)
