### ISSUE TITLE
Heading 字体大小

### ISSUE THREAD

**Issue by farlandliu** [suziwen/markdownxiaoshujiang#1068]
这个算是小问题，可能有点强迫症。
就是标题字体大小，一级，二级标题整体字体偏大，看着不太协调。
比如印象原生markdown一级标题字体41px，小书匠的渲染后的字体大小是3.4em。

希望能调整或者提供调整字体的方法。

### 小书匠标题
![小书匠](https://user-images.githubusercontent.com/6795956/55369522-7b2bd100-5529-11e9-9db0-d50047d83505.png)
### 印象原生标题
![印象笔记](https://user-images.githubusercontent.com/6795956/55369526-80891b80-5529-11e9-97ac-f7187d7d70dc.png)

**Comment by suziwen** [comment]
`设置>预览>预览区自定义样式`

```
h1{
    font-size: 41px;
}
h2 {
    font-size: 34px;
}
```
