### ISSUE TITLE
编辑器主题问题

### ISSUE THREAD

**Issue by farlandliu** [suziwen/markdownxiaoshujiang#1069]
@suziwen 

一直再用solarized light主题，小书匠的这个主题颜色有点不太对。
请问怎么调整？mac 客户端。
[solarized light](https://ethanschoonover.com/solarized/#features)

![屏幕快照](https://user-images.githubusercontent.com/6795956/55463959-b19e4480-562c-11e9-90fe-031ea4441643.png)

强调色建议改成 base1
![light](https://github.com/altercation/solarized/raw/master/img/solarized-values-light.png)

**Comment by suziwen** [comment]
这个当初是直接拿的 ace https://ace.c9.io/build/kitchen-sink.html 编辑器的主题设置里提供的 `solarized light` ， 应该没有完整参考 `solarized light` 官方的建议。

因为不同用户有不同颜色需求，不好完全满足，所以除非特别影响使用效果，否则就不进行个别调整了。

-------------

7.2.0 版本增加了一个调整编辑器全局样式的入口 `设置>基本>全局自定义样式`, 可以自己自定义 css 样式，来微调编辑器，达到自己想要的样式。

比如：

```
.ace-solarized-light .ace_string{
    color: #586e75 !important;
}
```

**Comment by farlandliu** [comment]
简单改了一下，预览区直接拷贝的typora的github css。

![效果](https://user-images.githubusercontent.com/6795956/55523797-4c466400-56bd-11e9-8e06-b7445f9b702c.png)

> 建议有空整体改版一下默认ui，以朴素简洁为主，小书匠立马能提升一个档次。

**Comment by farlandliu** [comment]
solarized 没调好，最后微调了default。

![image](https://user-images.githubusercontent.com/6795956/55543311-630bab80-56fb-11e9-8dde-53732c37ec5e.png)

**Comment by suziwen** [comment]
调主题是个细心活，还要对 css 有一定理解，可以先在 chrome 浏览器下的 web 版本进行具体元素细调，然后再把最终的 css 保存。

---------

我自己不是专职设计，对一些颜色如何更优雅的组合没有太多研究，加上经费有限，请不起专业设计，目前只能放开权限让用户自己调了。
