### ISSUE TITLE
建议明确支持的图床，同时支持语法自定义（主要是感叹号）

### ISSUE THREAD

**Issue by aszzp** [suziwen/markdownxiaoshujiang#1071]
看起来支持的图床蛮多，试了下微博的，失败了，说是接口改动。试了腾讯的，失败了，查了半天，估摸是因为不支持v5。建议开发者在设置页面可以做个说明，可以节省用户很多精力。

**Comment by aszzp** [comment]
* 关于图床
看起来支持的图床蛮多，试了下微博的，失败了，说是接口改动。试了腾讯的，失败了，查了半天，估摸是因为不支持v5。建议开发者在设置页面可以做个说明，可以节省用户很多精力。
* 关于语法
小书匠的语法很完善，但是有一点感觉难以适应。mermaid和mathjax（这个可以通过扩展修改，nice）中添加的感叹号感觉有些多余，如果去掉的话，就可以和主流平台实现兼容。不然每次发布到其他平台还要一个个进行修改。也许确实会出现极小概率混淆的情况，但相对来说，增加个感叹号所增加的编辑成本要高得多得多。希望能予以调整或者想mathjax一样给出自定义的设置项。

**Comment by suziwen** [comment]
嗯，抱歉。这两个图床以前是支持的，后来官方改了接口，或者升级了新版本接口，这边没有及时跟进，引起使用误解。下个版本会考虑先把微博图床接口去掉，腾讯云接口注明版本。


-----------

这个加感叹号是为了区分代码高亮和代码执行。比如，在同一篇文章里，既想要展示 mathjax 的源代码，又想要展示 mathjax 对应的生成公式。

而且 mathjax, mermaid 这些扩展的语法，很多第三方编辑器支持的写法都不太一样，比如有些是写 mathjax, 有些却写 math, 有些直接用 `$` 符号来区分。所以还是比较难统一。

目前想到的一个解决方案是，自定义代码块语言别名，比如可以把 `mathjax!` 添加一个别名 `mathjax` 或者 `math`, 这样代码块内遇到这个别名就会直接执行 `mathjax!` 的功能。

---------

注： 小书匠语法设置里可以打开兼容通用公式语法，将 mathjax 写成 `$$`格式。

**Comment by aszzp** [comment]
辛苦了，期待更新~
