### ISSUE TITLE
右侧预览中的图片，能恢复之前版本可以点击查看大图的功能吗？

### ISSUE THREAD

**Issue by ieeloleei** [suziwen/markdownxiaoshujiang#1072]
你好，之前的版本中，右侧预览的图片是可以点击弹窗看大图的。这样在插入大图时查看十分方便，请问能继续支持这个功能吗？谢谢。

**Comment by suziwen** [comment]
这个可能是你的图片不是块级图片。

系统只对块级图片提供图片查看器功能，行内图片一般使用场景是一些小图片，不需要放大来查看，就禁用了图片查看器。

所谓块级图片就是图片的上下各空一行，不在任何其他标签内（比如列表，引用，表格，还有就是给图片添加超链接功能等）。

http://soft.xiaoshujiang.com/docs/grammar/common/image/

![image](https://user-images.githubusercontent.com/57370/56004539-85568800-5cfe-11e9-92d5-01252f6fb269.png)
