### ISSUE TITLE
在列表中的图片描述显示异常。

### ISSUE THREAD

**Issue by ieeloleei** [suziwen/markdownxiaoshujiang#1073]
![image](https://user-images.githubusercontent.com/22229263/55966038-47c80f80-5caa-11e9-8031-b729f402930f.png)
1.列表中插入的图片描述都没了。
2.如果连续插入多个图片（不在列表中），图片描述也很容易消失。
请问能恢复图片描述显示吗？
谢谢。

**Comment by suziwen** [comment]
这个现在改成只有在块级图片里才会显示下面的图片描述。

在列表，引用，表格中的图片，都会当成行内图片，不会显示下面的图片描述。

连继多个图片，如果图片之间没有空行，第二张图片开始也会显示成行内图片，不会显示图片描述。

所谓块级图片就是图片的上下各空一行，不在任何其他标签内（比如上面的列表，引用，表格，还有就是给图片添加超链接功能）。

http://soft.xiaoshujiang.com/docs/grammar/common/image/

![image](https://user-images.githubusercontent.com/57370/56004539-85568800-5cfe-11e9-92d5-01252f6fb269.png)

**Comment by ieeloleei** [comment]
谢谢！
