### ISSUE TITLE
实时同步功能能不能回退？？？

### ISSUE THREAD

**Issue by WystanW** [suziwen/markdownxiaoshujiang#1074]
写了一天的东西。。。因为没网所以没同步，等联网以后把我写的全覆盖了。。。能不能返回去啊，现在极其郁闷

**Comment by WystanW** [comment]
我现在只想关闭同步这个功能。。。怎么都关不了

**Comment by suziwen** [comment]
有历史记录功能
![image](https://user-images.githubusercontent.com/57370/56035738-87036880-5d5d-11e9-99f9-89090c10d8c1.png)

也可以到 `小书匠主按钮>数据>同步`，把同步功能关掉。
