### ISSUE TITLE
图片在印象笔记上能正常显示,但在小书匠里面就显示不了

### ISSUE THREAD

**Issue by WystanW** [suziwen/markdownxiaoshujiang#1076]
显示找不到地址对应的资源,为什么呢?好几次这样了, 每次都要重新把图弄上去

**Comment by WystanW** [comment]
我在印象笔记调整过笔记对应的目录,难道是这个原因?现在调整过目录的笔记的图片在小书匠里面都看不了了

**Comment by WystanW** [comment]
然后有时候打开旧的笔记总出现 
<a name="e6938de4bd9ce7b3bbe7bb9fe6a682e5bfb5e5928ce7bb84e68890e983a8e58886_2"></a><a name="操作系统概念和组成部分"></a>

这种标签,到底为啥啊?

**Comment by WystanW** [comment]
![image](https://user-images.githubusercontent.com/18168353/56074759-5c132600-5dea-11e9-8e31-582ce4b52dc9.png)
第二次打开,有时候总出现这种标签, 这是为什么??

**Comment by WystanW** [comment]
![image](https://user-images.githubusercontent.com/18168353/56074971-7c90af80-5ded-11e9-9eb7-db0e1686ec8d.png)

好不容易编辑的以后..再打开就出现这种,

**Comment by suziwen** [comment]
通过小书匠保存到印象笔记的文件，如果你进行了操作，修改，下次通过小书匠读取时，只会尝试进行印象笔记文件格式转换成 markdown 格式，而不是原 markdown 文件直接展示。如果想避免进行修改误操作，可以在 `绑定` 界面的设置里，打开文档保护功能，这样保存到印象笔记的文件就会进入只读状态。

![image](https://user-images.githubusercontent.com/57370/56075277-8c5ec280-5df2-11e9-84bd-3c17b6fb8e8a.png)

**Comment by WystanW** [comment]
@suziwen 那我想问下, 转换网络图片是什么意思呢?

**Comment by WystanW** [comment]
@suziwen 第一个问题没有解决, 我现在已经改成保护文档的方式了, 我保存完一个文件以后, 在印象笔记把这个笔记移动大另一个笔记本了(在安卓手机客户端上),再打开,图片在预览区无法显示!!!

**Comment by WystanW** [comment]
@suziwen 还有一个问题,我在一个文档里面有图片,比如
![image](https://user-images.githubusercontent.com/18168353/56076297-fcc11000-5e01-11e9-9c1f-2421964855c7.png)
,我复制这个到另一个文档里面,预览区就无法显示了...这是为什么

**Comment by WystanW** [comment]
@suziwen 上面两个问题能都回答一下吗?折磨疯了,一直搞不定!!!!!!!

**Comment by suziwen** [comment]
转换网络图片指的是把图片地址是 http:// 开头的图片转换成保存到印象笔记里。

----------------

这个保护机制是印象自己提供的，我不知道他们的客户端是否有允许修改保护的文档，我刚才在 web 版本测试了一下移动一篇文章到其他目录，图片，正文格式都是正确的。也能在小书匠里正常从印象笔记里读取。

-------

> 还有一个问题,我在一个文档里面有图片,比如
image
,我复制这个到另一个文档里面,预览区就无法显示了...这是为什么

你复制的是纯文本，肯定不会把图片带过来的。如果想复制一篇文章，可以考虑导出 zip 格式,  再导入 . 或者使用另存为，把当前这篇文章保存到印象笔记的其他目录里。

**Comment by WystanW** [comment]
@suziwen 我只是想复制一个文章的几个图片,有方法吗?我记得以前是可以的,复制一段,这里面包含图片,直接复制过去,现在每每遇到图片都要重新截图

**Comment by suziwen** [comment]
如果想复制 markdown 文件带上图片，就需要使用图床，把图片把存到网络中。

再一个我刚才再试着关闭保护文档，然后在印象上修改一篇 文章，重新从小书匠那抓取，一样可以看到图片，只是 markdown 正文会跟以前的不一样。

**Comment by WystanW** [comment]
@suziwen 修改目录那个我知道了,安卓手机上修改和web修改不一样的, 图床这个需要怎么设置呢?我现在就是小书匠默认的图床服务,

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/56079022-1887de80-5e21-11e9-8a45-a943c6fec6ba.png)
![image](https://user-images.githubusercontent.com/57370/56079037-44a35f80-5e21-11e9-9955-adfd401e76c8.png)

复制一篇 文章可以使用另存为，或者导出 zip, 再导入。

**Comment by WystanW** [comment]
@suziwen 我知道整篇文章,我是说你刚才说的图床服务, 那个怎么设置呢?我只想复制一部分也可以复制图片

**Comment by suziwen** [comment]
比如你绑定了一个 smms 图床，添加新的图片后， 生成的图片地址为 `![enter description here](https://i.loli.net/2019/04/13/xxxxxx.jpg)`, 不会再像以前的  `![enter description here](./images/1555154633294.png)`

然后文章直接复制时，图片就会跟着显示了。

使用图床的前提最好是你有自己的图床服务器，如果使用第三方图床服务器，对方关闭了服务，图片就会消失。

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/56079162-2cccdb00-5e23-11e9-9376-6823b4f9c941.png)

**Comment by suziwen** [comment]
新版7.3.0 版本提供了直接复制部份文字，带有图片资源时，也自动解析到新的文章的功能。
