### ISSUE TITLE
全屏后，任务栏消失，鼠标放最底下也不显示，必须再缩小

### ISSUE THREAD

**Issue by LonlyPan** [suziwen/markdownxiaoshujiang#1077]
全屏后，任务栏消失，鼠标放最底下也不显示我想要再编写的同时能够再多个应用中跳转，可是全屏后无法打开任务栏 以选择其他应用，必须再缩小

**Comment by suziwen** [comment]
你可能混乱了`最大化`和`全屏`的概念。

按你的需求，应该点最大化那个按钮，不是全屏按钮。


![image](https://user-images.githubusercontent.com/57370/56075247-f88cf680-5df1-11e9-88f5-988e9c187d16.png)

**Comment by LonlyPan** [comment]
感谢，没注意那个按钮，今天才看到: )
