### ISSUE TITLE
表格行显示ABC，列显示123

### ISSUE THREAD

**Issue by xulingfeng** [suziwen/markdownxiaoshujiang#1081]
![table](https://user-images.githubusercontent.com/1643355/56255207-946e7900-60f6-11e9-84b6-aa7894c79662.png)

如图

**Comment by suziwen** [comment]
这些只在小书匠内置的预览器里显示的，方便用户在表格里快速定位，不会影响到你导出 html 后的显示效果（比如保存到印象笔记，是不会有这些多余的行列信息的）。

**Comment by xulingfeng** [comment]
本地客户端导出PDF也会有这些东西。

**Comment by suziwen** [comment]
更新到 7.2.2 可以了。
