### ISSUE TITLE
能不能在导出PDF时单独选择主题样式？

### ISSUE THREAD

**Issue by gyzhangqi** [suziwen/markdownxiaoshujiang#1083]
RT
在编辑的时候，预览主题样式选择的是黑色系（和编辑器主题搭配），但是导出PDF的时候希望用default来确保导出成功（部分主题样式无法正常导出，如tomorrow_night_eighties）。
目前只能按照先修改预览主题样式，再导出，太麻烦……

**Comment by suziwen** [comment]
嗯，后面会考虑这个功能。

**Comment by suziwen** [comment]
新版7.3.0 版本提供了导出界面下的设置样式选择功能。
