### ISSUE TITLE
图床服务

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1085]
很喜欢小书匠的图片上传功能，而且他能一键发布到wordpress这个是超级喜欢的，因为可能我自己的服务器带宽够用。所以没有像其他人一样把图片放到七牛云之类的地方，有些人可能会使用自己的图床，或者跟我一样把图片放到wordpress文件目录，如果这个小书匠能上传到这个地方（应该类似FTP的）也是可以的，但是这样好像不太满足大部分人群（哈哈）最近看到很多人使用https://doc.xiaoz.me/#/imgurl2/    来创建自己的私有图床，这样思路一转换下，这可以解决上面的了，希望作者能增加一个对接imgurl图床的图床服务

**Comment by suziwen** [comment]
后继会考虑添加一个自定义上传图片的入口。

**Comment by 52Lau** [comment]
感谢采纳

**Comment by suziwen** [comment]
web（7.4.0） 版本添加了个自定义图床，可以先试下

http://soft.xiaoshujiang.com/blog/images/custom_images_manager
