### ISSUE TITLE
关于图床问题，更新最新版不能正常上传

### ISSUE THREAD

**Issue by xufeifan1992** [suziwen/markdownxiaoshujiang#1087]
从昨天开始，我绑定的七牛云图床或者github图床都不能正常上传图片，复制图片进去没反应，

**Comment by suziwen** [comment]
绑定  smms 图床呢，也不能正常上传？

直接绑定小书匠内置数据库的图片呢？

**Comment by xufeifan1992** [comment]
> 绑定 smms 图床呢，也不能正常上传？
> 
> 直接绑定小书匠内置数据库的图片呢？
内置数据库好使，绑定码云图床，github，七牛云都不行，smms好使

**Comment by suziwen** [comment]
我刚试了下 码云图床，没有问题的。

你那边能提供下你绑定的参数设置吗

![image](https://user-images.githubusercontent.com/57370/57665896-66fee780-7630-11e9-9fc3-01ffe79553f0.png)

**Comment by xufeifan1992** [comment]
> 我刚试了下 码云图床，没有问题的。
> 
> 你那边能提供下你绑定的参数设置吗
> 
> ![image](https://user-images.githubusercontent.com/57370/57665896-66fee780-7630-11e9-9fc3-01ffe79553f0.png)
可以的，码云图床
![image](https://user-images.githubusercontent.com/23428194/57668065-a6313680-7638-11e9-9281-506fd7690a27.png)

token:045e182cdefea9c1bd2ee8ed93ebce70
仓库： imgGiteeRepo
分支：master

**Comment by xufeifan1992** [comment]
> 我刚试了下 码云图床，没有问题的。
> 
> 你那边能提供下你绑定的参数设置吗
> 
> ![image](https://user-images.githubusercontent.com/57370/57665896-66fee780-7630-11e9-9fc3-01ffe79553f0.png)

![image](https://user-images.githubusercontent.com/23428194/57668219-2bb4e680-7639-11e9-9040-226e276cba60.png)

github图床

token：21daf232451c04c4a8945e53cbed692049c5b0e1
仓库名称：note
分支：master
生成规则：https://github.com/xufeifan1992/note/tree/master/images/{{year}{month}{date}}/{{filename}}

麻烦您了

**Comment by xufeifan1992** [comment]
> 我刚试了下 码云图床，没有问题的。
> 
> 你那边能提供下你绑定的参数设置吗
> 
> ![image](https://user-images.githubusercontent.com/57370/57665896-66fee780-7630-11e9-9fc3-01ffe79553f0.png)

**Comment by suziwen** [comment]
文件名生成规则

1. 不要带上域名这些信息, 比如  `https://github.com/xufeifan1992/note/tree/master`, 这个如果实现了自己绑定域名的话，可以在 `url 前缀` 里设置， 如果没有的话，系统自动帮你生成。
2. 变量的使用是两个 `{{` `}}` 成对的，你里面的 `year`, `month` 和 `date` 写法不对， 应该写成这样
```
{{year}}{{month}}{{date}}
```

最终的生成规则应该这样写 `/images/{{year}}{{month}}{{date}}/{{filename}}`

**Comment by suziwen** [comment]
还有一个就是使用了图床的话，那该图床必须是可以公开访问，我看你的 gitee 图床好像是不公开的，这样的话图片也会失效。

如果自己的文章不想公开 ，可以不使用图床，直接使用小书匠内置的数据库图片管理，当文章保存到 gitee 或者 github 时，系统会尝试把图片保存到该 gitee或者  github 相关的目录下面的。

**Comment by xufeifan1992** [comment]
> 还有一个就是使用了图床的话，那该图床必须是可以公开访问，我看你的 gitee 图床好像是不公开的，这样的话图片也会失效。
> 
> 如果自己的文章不想公开 ，可以不使用图床，直接使用小书匠内置的数据库图片管理，当文章保存到 gitee 或者 github 时，系统会尝试把图片保存到该 gitee或者 github 相关的目录下面的。

感谢感谢！！！！ 我也发现了生成规则得问题，再次感谢您
