### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1089]
![enter description here](http://qiniu.ymxlass.com/blog/1558072010752.png)
左边有时候会偏移过去，看不到内容

**Comment by suziwen** [comment]
有重现的操作方法吗，我这边没有遇见过。

**Comment by 52Lau** [comment]
就那天出现过两次，重启软件之后，后面没了，如果再出现会注意下什么情况下触发的

**Comment by 52Lau** [comment]
这几天好像有出现了，我记得应该是复制文本到右上角上面粘贴标题的时候，会出现这样的情况

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/61104425-ed0ca280-a4a8-11e9-90a7-bd309216657a.png)

**Comment by 52Lau** [comment]
这个问题应该是右边的标题点击的时候，会往左边挤过去

**Comment by suziwen** [comment]
最新版本已经修复。
