### ISSUE TITLE
图标太黑

### ISSUE THREAD

**Issue by flySword** [suziwen/markdownxiaoshujiang#109]
我在windows下使用黑色背景桌面时，图标直接看不到了。。

**Comment by suziwen** [comment]
有截图吗?

**Comment by flySword** [comment]
![qq 20151116123126](https://cloud.githubusercontent.com/assets/7957122/11174407/0a76bc8c-8c5e-11e5-8aec-c23e41523910.jpg)
![qq 20151116123146](https://cloud.githubusercontent.com/assets/7957122/11174408/0a78c004-8c5e-11e5-956e-f2579a7629f6.jpg)

**Comment by suziwen** [comment]
1.8.0新版本已换用新的图标，欢迎下载使用。
