### ISSUE TITLE
2k屏win10系统，只能在屏幕一块区域显示，分辨率设置问题

### ISSUE THREAD

**Issue by tryerrorman** [suziwen/markdownxiaoshujiang#1090]
如图所示，下面和右边没有显示全，请问这种除了修改系统分辨率外，可以通过软件设置调整吗
<img width="1034" alt="2019-05-20 01_54_46-小书匠编辑器使用手册 小书匠" src="https://user-images.githubusercontent.com/10434436/57986060-8a97b700-7aa2-11e9-9b87-d9f663dece6d.png">

**Comment by suziwen** [comment]
你的截图上怎么没有看到最大化按钮?

![image](https://user-images.githubusercontent.com/57370/57990273-9b165480-7ad7-11e9-9ad5-13a380d2bfc3.png)

我测试了下自己的 win 10 系统，
正常是有这些按钮的，同时也可以把鼠标移动到软件的边框，然后拖动调整大小。

**Comment by tryerrorman** [comment]
今天我又尝试了一下，现在已经可以自己调整到最佳桌面大小了，谢谢。

昨天的时候，是有这个最大化按钮。
实在不好意思，耽误你宝贵的开发时间了。
遇到这种情况，可以先尝试按照下列优先级尝试修复，1. 重新打开软件；2.关机重启，开软件；3.搜一下别人是否遇到这种问题；4. 向作者提问。
