### ISSUE TITLE
急切需要自定义图床的

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1092]
我是使用ImgURL搭建自己的图床的，其实用搭建什么都可以，就希望图片放在自己服务器上，毕竟七牛云之类的，每个月也是一笔开支

**Comment by suziwen** [comment]
web （7.4.0） 版本添加了个自定义图床，可以先试下

http://soft.xiaoshujiang.com/blog/images/custom_images_manager

**Comment by suziwen** [comment]
#1085

**Comment by 52Lau** [comment]
感谢作者，666，我是做优秀软件分享的，看过很多MarkDown工具，没有一款能达到小书匠这么完美的，特别是这次的自定义图床，真的很秀，再次感谢！
另外再提一个小小的建议，对于文章的管理，这一块，能改造下，改善下体验基本上是超级完美了

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/58242154-e4d59800-7d80-11e9-975e-2f260612b5c8.png)发现会有这个问题，在ImgURL的接口也没看到怎么增加参数，使自己不受限制

**Comment by 52Lau** [comment]
哦，看到了，有一个游客限制，改一下就行
