### ISSUE TITLE
文章目录结构 

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1093]
建议小书匠可以引入目录结构，就是在每一篇的文章的开头就可以看到不同文章的目录层级结构，而且可以通过点击目录上不同的标题实现页面内跳转，非常的方便，简单来说这样做有两个优点：
* 目录清晰，一目了然
* 可以实现内容的定位跳转

在CSDN的博客中Markdown这个语法的定义是这样的`@[toc](标题)`，之后会自动把`# 、##、### `等不同层级的目录结构自动排列好，下面是我用CSDN的Markdown写的一篇博客，样式如下：
![markdown 定义目录结构](https://user-images.githubusercontent.com/37186266/58447746-04c9da80-8138-11e9-8881-6c45d79ca32d.png)

**`希望小书匠可以不断改进，越做越好！！！`**

**Comment by suziwen** [comment]
这个在小书匠的语法是 `[toc]` 单独一行。

**Comment by shliang0603** [comment]
好的，谢谢你的回复
