### ISSUE TITLE
图片存放位置

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1094]
我再网页上复制的图片可以正常添加到小书匠中，显示为：`![未选择的路](./images/1559033429315.png)` 但是我不知道这个图片是被保存在本地是什么地方，我再保存文章的地方并不能找到括号里面的那个路径，如果我想把这篇文章放到CSDN博客上，图片就不能正确显示，请问请问应该在哪里可以找到自己添加的图片。还有入托把复制图片换成链接之后，图片就不会居中啦，希望有人可以给解答一下，谢谢

**Comment by suziwen** [comment]
这个保存在小书匠内置的数据库里，如果想拿到文章下的所有图片，可以导出为 zip , 该 zip 文件展开后，里面就有相应的图片了。

也可以自己绑定图床，这样添加的图片就保存到自己的图床服务器上了。

**Comment by shliang0603** [comment]
@suziwen  你好，图片是不是必须要绑定图床服务器，有没有一种方式，可以直接把图片直接存储本地

**Comment by suziwen** [comment]
选择绑定本地做为默认的第三方存储 ，这样每次上传的图片都会在 markdown 文件对应的目录下创建相关的资源了。
