### ISSUE TITLE
有办法调换编辑窗口与预览窗口的位置吗

### ISSUE THREAD

**Issue by DemoJameson** [suziwen/markdownxiaoshujiang#110]
即编辑窗口在右边，预览窗口的左边。因为显示器放在偏左的位置，这样比较习惯。

**Comment by suziwen** [comment]
预览区边上按钮

![image](https://cloud.githubusercontent.com/assets/57370/21964073/ee9f146c-db0a-11e6-9145-33fa22bda6f6.png)
