### ISSUE TITLE
这两天绑定的图床突然不好用了,用的是github,有没有办法找到原因

### ISSUE THREAD

**Issue by treeyh** [suziwen/markdownxiaoshujiang#1100]
前两天复制图片进去可以自动上传, 这两天突然就不行了 ,版本  7.4.0.

**Comment by suziwen** [comment]
我在 7.4.0 版本上测试了下，是没有问题的。

**Comment by treeyh** [comment]
我这边有的时候可以，有的时候不行，有没有办法看到错误日志

**Comment by suziwen** [comment]
我记得只要图片上传出错，就会在右上角弹出错误提示的。

**Comment by liao20081228** [comment]
github图床无法预览，一直转圈圈是什么意思？

**Comment by suziwen** [comment]
@liao20081228 

编辑区里有生成正确的 url 地址了吗？

新建一篇文章，再粘贴图片呢？

**Comment by liao20081228** [comment]
> @liao20081228
> 
> 编辑区里有生成正确的 url 地址了吗？
> 
> 新建一篇文章，再粘贴图片呢？

生成路径：https://www.github.com/username/rep_name/raw/master/subdir/filename

还是转圈圈，我完全卸载后重装  还是再转圈圈。v7.7.1

我这里的路径是指的格式是这样的，但是不是真实的路径。

我试了百度图片的地址和微博图片的地址，同样转圈圈，也就是预览区无法预览。

========================

另外升级后发现mathjax公式无法正常显示,卸载重装后恢复。

**Comment by suziwen** [comment]
你看下，这个文件里的图片能正常显示吗？

[2019-7-2 测试图片.md.zip](https://github.com/suziwen/markdownxiaoshujiang/files/3347544/2019-7-2.md.zip)


------------

或者你提供一个不能正常显示图片的 markdown 测试文件

**Comment by suziwen** [comment]
@liao20081228

**Comment by liao20081228** [comment]
> 你看下，这个文件里的图片能正常显示吗？
> 
> [2019-7-2 测试图片.md.zip](https://github.com/suziwen/markdownxiaoshujiang/files/3347544/2019-7-2.md.zip)
> 
> 或者你提供一个不能正常显示图片的 markdown 测试文件

不能一直在转圈圈。你那边测试时能显示吗？我时在win10平台。
但是 把这个链接插入 网页版的 小书匠可以显示

同时 在 7.5 版本是可以的

**Comment by suziwen** [comment]
@liao20081228 

我这边 7.7.1 客户端版本能正常显示的，是不是系统其他软件限制了网络请求？

或者你先把数据目录移到其他位置，重新登录更新到 7.7.1 版本，再打开这个文件呢？

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```

**Comment by suziwen** [comment]
@liao20081228 

刚发现了个 bug , 如果开启了图片大小语法功能，图片描述文字里，如果只有数字的话，可能会造成图片无法正确加载。不知道你的情况是不是这个原因，可以在`设置>扩展语法 > 图片大小` 里，禁用一下试试。

**Comment by liao20081228** [comment]
> @liao20081228
> 
> 刚发现了个 bug , 如果开启了图片大小语法功能，图片描述文字里，如果只有数字的话，可能会造成图片无法正确加载。不知道你的情况是不是这个原因，可以在`设置>扩展语法 > 图片大小` 里，禁用一下试试。

ok 已经正常了，thanks 。主要是我用的是7. 7.0. 没有看到升级提示7.7.1. 升级后正常了
