### ISSUE TITLE
有没有快速自定义图片大小的方法？

### ISSUE THREAD

**Issue by zhaocai** [suziwen/markdownxiaoshujiang#1101]
参考 [小书匠语法说明之图片 | 小书匠](http://soft.xiaoshujiang.com/docs/grammar/common/image/)， 没有发现可以快速自定义图片的方法，是这个功能还没实现吗？还是必须自己写`<img style=... />` 这样的格式呢？

**Comment by suziwen** [comment]
没有提供自定义图片大小的方法，需要自己写 `<img style=... />`

**Comment by zhaocai** [comment]
可不可以提供类似 [markdown-it-imsize](https://github.com/tatsy/markdown-it-imsize) 这样的支持呢？

`![test](image.png =100x200)`

**Comment by zhaocai** [comment]
> 没有提供自定义图片大小的方法，需要自己写 `<img style=... />`

使用 `<img src='xxx.png' width='512'>`
同步到 Evernote 之后没有效果, 最后在 Evernote 中得到的是
```html
<img class="en-media" style="vertical-align: middle; height: auto; max-width: 100%; border: 0;" src="https://www.evernote.com/shard/xxxxxxxxxxxxxxx?resizeSmall&amp;width=800" name="b398abc9-1f47-45b1-9cfa-3f4ff1c1075f" />
```

**Comment by suziwen** [comment]
嗯，会考虑支持。

----------


这样写

```
<img src="./images/1559473993862.png" style="width:200px;height:100px;"/>
```
