### ISSUE TITLE
图床转移问题，所有数据一键转移

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1103]
图床转移问题，所有数据一键转移，能不能把所有文章的图片都转移呢，难道只能 一个一个转移么

**Comment by suziwen** [comment]
暂时不能，只能自己一个一个转移的。

**Comment by 52Lau** [comment]
能否考虑下一键转移呢

**Comment by suziwen** [comment]
这个估计不会去实现的。只能自己写些小脚本，做批量的操作。

**Comment by 52Lau** [comment]
这个小脚本的是怎么样的思路呢，或者开放那个图床转移的，自己写批量脚本

**Comment by suziwen** [comment]
这个得最好有编程基础的，写起来比较快。没法简单说明。
