### ISSUE TITLE
图床样式支持问题

### ISSUE THREAD

**Issue by liliang2840** [suziwen/markdownxiaoshujiang#1105]
图床用的七牛云和阿里云，如果需要对图片进行样式处理，处理完后的图片不能显示。

如 图片为   http://xxxx.com/123.jpg  ,  图片样式为 http://xxxx.com/123.jpg-resize

问题1：怎么才能正确使用样式
问题2：是否支持自动添加样式后缀功能

**Comment by suziwen** [comment]
`小书匠主按钮>设置>预览` 界面下，把 `是否自动转换非图片扩展名为附件（自动识别jpg,jpeg,png,gif及无扩展名的文件为图片文件，其他的扩展名文件为附件）` 选项关掉。

----------
或者把图片样式配置成带参数的形式，比如

```
 http://xxxx.com/123.jpg?resize
```

**Comment by liliang2840** [comment]
搞定，或者直接上传的时候不要让文件带.jpg后缀，这样加样式就没问题。

自动添加样式这个功能是否有计划加入到图床中。

**Comment by suziwen** [comment]
会考虑添加一个指定图片大小的设置，其他图片修改还是看第三方图床的支持。
