### ISSUE TITLE
Evernote 内部链接问题

### ISSUE THREAD

**Issue by zhaocai** [suziwen/markdownxiaoshujiang#1106]
如下的 Evernote 内部链接，`[Note](evernote:///view/xxx/syyy/a26eda2d-c308-4a19-ab1b-01e3f5994203/a26eda2d-c308-4a19-ab1b-01e3f5994203/)`，保存到 Evernote 以后会变成：
`http://evernote///view/xxx/syyy/a26eda2d-c308-4a19-ab1b-01e3f5994203/a26eda2d-c308-4a19-ab1b-01e3f5994203/`。

也就是 `evernote:///` → `http://evernote///` , 能不能检查一下代码，这是不需要转换的！

**Comment by zhaocai** [comment]
@suziwen 

any update on this issue? I tried to use `<a href="evernote:///view/149127684/s111/a26eda2d-c308-4a19-ab1b-01e3f5994203/a26eda2d-c308-4a19-ab1b-01e3f5994203/"
  style="background-color: transparent;text-decoration:none;color:#8CD790;">Note</a>` as a temporary solution. But, the result is the same 😞

**Comment by suziwen** [comment]
这周未会发布一个修正后的客户端版本。

**Comment by zhaocai** [comment]
@suziwen 多谢7.7版本的更新，解决了最近的几个问题。这里提一个小要求：能不能给 `Evernote` 内部链接用不同的颜色以示区别，比如像 `Evernote` 本身那样用绿色，或者可以自定义颜色。

**Comment by suziwen** [comment]
这个可以自定义 css 样式实现

```css
a[href^="evernote:///"] {
  color: red;
}
```

**Comment by zhaocai** [comment]
@suziwen 谢谢

**Comment by zhaocai** [comment]
> 这个可以自定义 css 样式实现
> 
> ```css
> a[href^="evernote:///"] {
>   color: red;
> }
> ```

自定义样式在小书匠可以，但是保存到 Evernote 之后就没用啦。

**Comment by suziwen** [comment]
web 版已修复。
