### ISSUE TITLE
文件夹层级结构

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1108]
强烈建议小书匠可以像有道云笔记一样在客户端的侧边引入文件夹层级结构，如下：
![image](https://user-images.githubusercontent.com/37186266/59319691-31681f80-8cfe-11e9-9408-d88922d930ee.png)
**这样就可以方便文档的查询和管理**

**Comment by zhengmingliang** [comment]
麻烦问一下，现在有这个目录结构了吗，我还没发现，你就关闭这个issue了

> 强烈建议小书匠可以像有道云笔记一样在客户端的侧边引入文件夹层级结构，如下：
> ![image](https://user-images.githubusercontent.com/37186266/59319691-31681f80-8cfe-11e9-9408-d88922d930ee.png)
> **这样就可以方便文档的查询和管理**
