### ISSUE TITLE
是否能支持Mactype渲染支持

### ISSUE THREAD

**Issue by Bronts** [suziwen/markdownxiaoshujiang#111]
开发者您好，最近用了类似的几个产品，觉得小书匠还是做得很不错的，尤其支持印象笔记和本地存储，非常赞。
但是有点问题想咨询或者建议下，我在window上使用，本地还安装了mactype对系统的字体进行渲染，会使得字体显示更加好一些。不过小书匠上就失效了。之前用chrome也出现过这种情况，后来关了directdraw就好了，不知道小书匠是不是有同样的问题，不知道未来能不能支持mactype渲染？

**Comment by suziwen** [comment]
支持的,不过得自己配置下.

在安装目录下,修改 'package.json' 文件,比如 `c:\\Proggram Files\Story\package.json`

在根节点上添加 `"chromium-args": "--disable-direct-write",` 就可以了.

比如由原来的 

``` json
"main": "index.html",
  "name": "小书匠(编)",
  "description": "小书匠(编)，markdown编辑器, evernote",
  .
  .
  .
}
```
修改成

``` json

{"main": "index.html",
  "name": "小书匠(编)",
  "description": "小书匠(编)，markdown编辑器, evernote",
  "chromium-args": "--disable-direct-write",
.
.
.
}

```

**Comment by Bronts** [comment]
@suziwen 谢谢回复，加入这个配置可以渲染了^_^
