### ISSUE TITLE
win10下使用sublime作为外部编辑器打开失败

### ISSUE THREAD

**Issue by tryerrorman** [suziwen/markdownxiaoshujiang#1110]
软件提示，外部编辑器打开失败：Error: EPERM: operation not permitted, open 'C:\Program Files\Story\xsj_1560359140370.md'

设置如图
<img width="295" alt="image" src="https://user-images.githubusercontent.com/10434436/59371606-1639f600-8d78-11e9-8903-b269d4801bc9.png">

**Comment by suziwen** [comment]
window 下执行的程序，如果没有配置 path 环境变量，需要指定完整的路径。还有一个就是路径里如果有空格，最好把整个命令用双引号包裹下。

比如 `"c:\Program files\xxxx\xxx.exe" {{file}}`

**Comment by tryerrorman** [comment]
我环境变量配置好的，但我还是按照你说的修改了软件配置，如下图
<img width="635" alt="image" src="https://user-images.githubusercontent.com/10434436/59548080-02f77800-8f7c-11e9-939e-92052cd8cce1.png">
结果还是如图片右上角所示的这样。感觉应该是权限问题，但不知道是什么权限

**Comment by suziwen** [comment]
在 **小书匠主按钮>设置>基本** 里，有一项 **资源绝对路径起始地址** , 选择一个非系统盘的位置。

win10 系统，对系统盘目录下的文件好像有文件保护设置，造成创建临时文件失败，导致无法打开的问题。

![image](https://user-images.githubusercontent.com/57370/59558350-0c87eb00-9023-11e9-873b-98178727e829.png)

**Comment by tryerrorman** [comment]
是这样的，路径改到d盘就可以了，谢谢
