### ISSUE TITLE
win10 中小书匠导出word2007版本文件，无法打开还是试图删除，资源管理器都崩溃

### ISSUE THREAD

**Issue by tryerrorman** [suziwen/markdownxiaoshujiang#1114]
小书匠是最新版的7.7.1，导出的docx是纯文本文件，每次一选中，直接资源管理器就崩溃，像病毒一样。

**Comment by suziwen** [comment]
每篇文章导出成 docx 都这样吗？

我这篇导出的 docx 能够正常打开的。

**Comment by tryerrorman** [comment]
是的，我测试好几次了，都是这样。只要选中导出的文件，资源管理器就会崩溃。

**Comment by suziwen** [comment]
能正常导出 pdf 吗？
感觉这个跟你的系统环境关系比较大了，我这边没法重现你说的情形。

还有就是导出  docx, pdf 这几个需要联网才能使用，可能你系统其他软件限制了网络请求原因。

**Comment by tryerrorman** [comment]
我这边导出doc是可以打开的

**Comment by suziwen** [comment]
doc 是本地导出 ， 目前只有 epub, mobi, docx ,pdf 是需要联网才能导出的。

![image](https://user-images.githubusercontent.com/57370/60310469-94f07f00-9985-11e9-914e-6f2763e4f5dc.png)

**Comment by tryerrorman** [comment]
了解了，我今天重新测试自己建的docx并找到了原因。之前安装了clover，由于添加书签会导致资源管理器直接关掉，遂卸载。可能是卸载不完全导致的一选中docx就崩溃。我今天重新安装了clover，从小书匠导出的docx就可以打开了。非常感谢你的耐心回复。这个是我个人原因导致的，实在不好意思。
