### ISSUE TITLE
保存失败: 服务器出错....{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"58.87.82.241","port":443}

### ISSUE THREAD

**Issue by MandyCh** [suziwen/markdownxiaoshujiang#1118]
今天保存文件的时候出现了错误，看了半天没看懂。
![Snipaste_2019-07-02_14-58-07](https://user-images.githubusercontent.com/26193879/60491670-df526280-9cdb-11e9-8ecb-2493e1a0b1cb.png)
后来看了一下issues觉得可能我文章哪里写了不符合的字符，然后就发现我把表头和表格分割那行多打了几个空格
![Snipaste_2019-07-02_15-12-27](https://user-images.githubusercontent.com/26193879/60491984-92bb5700-9cdc-11e9-9387-e7a54366478f.png)
把空格删掉之后就保存成功了。
嗯，这种不小心的操作造成的错误，不注意还挺难发现的，希望以后能有个提示之类的

**Comment by suziwen** [comment]
这个错误提示是连接超时，可能是连接的第三方存储服务不稳定超时引起的。


----

也有可能是一些无法显示的非法字符引起的，把空格删掉后，重新再添加空格估计就能保存。表格语法里，这些空格数是不受影响的。

------

或者你把能重现的测试文档发一个过来，我这边调试下看看。
