### ISSUE TITLE
0.2.2版下载地址? 和win64位版本的安装问题

### ISSUE THREAD

**Issue by fjxhkj** [suziwen/markdownxiaoshujiang#112]
RT
- 您给出的官网下载地址是0.1.7的;
- 0.1.7 x64 版本安装时仍然默认安装到 %Program% (x86) 目录中,是不是搞错了?

**Comment by suziwen** [comment]
打包的时候忘记修改安装地址,不过安装的是64位版本,你可以手动选择安装位置
程序运行时是按64位来走的.可以通过任务管理器看出该程序是64位还是32位的.

**Comment by suziwen** [comment]
现在0.2.2版本是老版本,可以到http://soft.xiaoshujiang.com下载最新的版本.
