### ISSUE TITLE
拍照截图又用不了了

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1120]
[object Event]

**Comment by suziwen** [comment]
网页版还是客户端版？

网页版的话刚才更新功能，重启了下后台，再截图一下试试。

客户端版的话，我这边能正常截图。把你截图失败的文章做成个能重现问题的版本，发过来测试下。

**Comment by CharMingF** [comment]
网页客户端，仍然不可以
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading Snipaste_2019-07-03_07-07-47.png…]()

![网页客户端]（https://imgchr.com/i/ZYaJNF）

**Comment by suziwen** [comment]
那比较奇怪了，我这边可以正常截图的。

![image](https://user-images.githubusercontent.com/57370/60556038-fba0de80-9d71-11e9-97b9-4d1d96085ee1.png)


![image](https://user-images.githubusercontent.com/57370/60556068-29862300-9d72-11e9-9944-b131fd1395ff.png)

------------


你试下网页版在 chrome 浏览器的隐藏模式下截图呢？

**Comment by CharMingF** [comment]
隐藏模式下可以

**Comment by suziwen** [comment]
那感觉是装了其他插件引起的

**Comment by CharMingF** [comment]
啥也没修改，在#1126 说好了之后就好了
