### ISSUE TITLE
在gitee上加个备份下载链接吧

### ISSUE THREAD

**Issue by fontomas** [suziwen/markdownxiaoshujiang#1122]
github的下载速度实在是太赶人了！
真·200M宽带，用迅雷下只有80K上下，需要下15分左右。如果用Firefox自带的下载，就要1h38m+了，太赶人了！

**Comment by fontomas** [comment]
你造吗，我换用百度网盘下载，免费体验了一下会员下载——只用了10秒~！我提了这个issue之后，迅雷被限速了，下载速度只有10K+，逼得我只能换百度网盘下载！

**Comment by suziwen** [comment]
https://gitee.com/suziwen/markdownxiaoshujiang/releases/v7.7.0
