### ISSUE TITLE
能不能记住对照模式的状态

### ISSUE THREAD

**Issue by sfegsetsfe** [suziwen/markdownxiaoshujiang#1124]
对一个文件预览关闭对照模式后，重新打开这个文件后对照模式又会自动开启。
能不能记住这个文件对照模式的状态？这样就不用每次切换文件都要去点击对照模式。

**Comment by suziwen** [comment]
你应该是在系统的帮助文件上进行了修改，才会自动打开对照功能。如果是新建文件，然后再修改，就不会有这个情况。
