### ISSUE TITLE
drawio里面的文本可以支持latex吗？

### ISSUE THREAD

**Issue by zfhxi** [suziwen/markdownxiaoshujiang#1125]
虽然drawio有格式控制上标下标，但对其他公式就无法满足要求了。
尽管我找到draw.io的[FAQ-How to use mathematical typesetting?](https://desk.draw.io/support/solutions/articles/16000067792-how-do-i-use-the-format-panel-)给出提示：
```
Mathematical typesetting

This option enables mathematical typesetting in the document properties, allowing users to create mathematical formulae and equations using either AsciiMath or LaTeX. MathJax is used for rendering.

By default, mathematical typesetting is disabled, and should only be enabled if the diagram contains mathematical typesetting, as it affects rendering performance and the image quality for exports.  All export formats (except SVG) are supported.
```
另外
[FAQ-How to use mathematical typesetting?](https://desk.draw.io/support/solutions/articles/16000032875-how-to-use-mathematical-typesetting-)给出提示：
```
Enable mathematical typesetting via Extras->Mathematical Typesetting. The following syntax is supported
```
但是我并未在小书匠内置的drawio找到mathematical typesetting。

**Comment by suziwen** [comment]
恩，目前小书匠这边在drawio上禁用这功能了。

**Comment by zfhxi** [comment]
> 恩，目前小书匠这边在drawio上禁用这功能了。

在以后的版本中会开启这个功能吗？

**Comment by suziwen** [comment]
会的
