### ISSUE TITLE
发布到Wordpress 该博客无法提供metaweblog接口

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1128]
该博客无法提供metaweblog接口,网站的RPC-XML已经打开的，用其他的类似的工具发布是正常的，比如MWEB发布是正常的，所以排除是网站的问题

**Comment by suziwen** [comment]
你的url地址等信息怎么填的？

**Comment by 52Lau** [comment]
https://www.ifuntools.cn
![image](https://user-images.githubusercontent.com/37538641/61292287-671f8d00-a803-11e9-8ecd-b03771a61f75.png)

**Comment by suziwen** [comment]
看不到你网站的源码提供metaweblog 入口

**Comment by suziwen** [comment]
Rsd+xml

**Comment by 52Lau** [comment]
是打开的，因为我手机上可以通过MWEB发布

**Comment by suziwen** [comment]
或者直接提供rpc入口，类似这样https://www.cnblogs.com/suziwen/rsd.xml

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/61293551-8966da00-a806-11e9-9c4c-4ca54aab75d1.png)
我的这个一直是保持打开的，这个开关，我做过实现，关闭后，我手机上MWEB也无法使用，开启后，MWEB能使用，但是小书匠使用不了

**Comment by suziwen** [comment]
我再研究一下。

主要是我通过查看源文件，找不到你主页里有“EditURI”相关链接信息。

**Comment by 52Lau** [comment]
嗯嗯，谢谢

**Comment by suziwen** [comment]
可以暂时直接输入这个地址

```
https://www.ifuntools.cn/xmlrpc.php?rsd
```

------------------------

下个版本我再自动匹配这个类型的地址。

**Comment by e0qkgr** [comment]
嗯，谢谢，我这边试了，可以发送
