### ISSUE TITLE
导出出错

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1129]
错误信息如下：
导出失败：TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'

**Comment by suziwen** [comment]
客户端版本信息？
重现的文章？

**Comment by shliang0603** [comment]
这是我的版本信息：
![image](https://user-images.githubusercontent.com/37186266/61292625-53c0f180-a804-11e9-94ab-95d03bbd2c03.png)

![image](https://user-images.githubusercontent.com/37186266/61292865-ef526200-a804-11e9-8dcb-df75cad8a33d.png)
这个是我的文章，不知道是不是文章太长导不出，因为我尝试导出pdf格式是可以的，但是导出png格式失败，就会报`导出失败：TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob` 错误

**Comment by suziwen** [comment]
这个是文章生成的图片太长了，超出小书匠系统支持的最长图片。

**Comment by suziwen** [comment]
#850 

具体原因是超出了底层canvas 的最大高度限制

**Comment by shliang0603** [comment]
这个有没有可能后期改进，可以生成更长的png图片，让小书匠越来越强（嘿嘿）

**Comment by suziwen** [comment]
这个得看用户的电脑了，生成越长的图片，消耗越多的内存。将来最多就是把图片切割成很多小块。

**Comment by shliang0603** [comment]
嗯，好的，谢谢
