### ISSUE TITLE
关于定价策略

### ISSUE THREAD

**Issue by aeagean** [suziwen/markdownxiaoshujiang#1130]
定价策略建议改为19.9与38.8

**Comment by suziwen** [comment]
理由？

**Comment by lanyuanxiaoyao** [comment]
> 理由？

就跟小米手机1999一样, 虽然只差一元, 但是不到2000让人感觉便宜了很多...

**Comment by aeagean** [comment]
> 多

同感

**Comment by aeagean** [comment]
> > 理由？
> 
> 就跟小米手机1999一样, 虽然只差一元, 但是不到2000让人感觉便宜了很多...

同感
