### ISSUE TITLE
CSS里的mathjax公式无法渲染，但为知笔记可以

### ISSUE THREAD

**Issue by JingofXin** [suziwen/markdownxiaoshujiang#1132]
在为知笔记中，嵌套在css里的mathjax公式是可以渲染出来的，但是在小书匠里就不行了。例如下面这段在为知笔记里就可以渲染出来公式，但是小书匠就无法渲染出来：

`<p style="background-color: #d9edf7;border:3px solid #bce8f1;padding: 0.6cm 0.4cm;line-height: 150%;color: #31708f"><font face="微软雅黑" color=#31708f size=5  style="font-weight:bold;"> Note </font><br /> &emsp; 根据万有引力公式：<br />$$\vec{F}=G\times\dfrac{M\times m}{r^2}\cdot\vec{e}$$</p>`

为知笔记渲染结果：
![image](https://user-images.githubusercontent.com/31361630/61341023-5577cd00-a877-11e9-8b22-14acf6e96767.png)
小书匠的渲染结果：
![image](https://user-images.githubusercontent.com/31361630/61341066-7cce9a00-a877-11e9-85ed-68b6a899f9ee.png)

**Comment by suziwen** [comment]
要在 `p` 标签里加上  `class` 为 `mathjax`

即

```
<p class="mathjax" style="background-color: #d9edf7;border:3px solid #bce8f1;padding: 0.6cm 0.4cm;line-height: 150%;color: #31708f"><font face="微软雅黑" color=#31708f size=5 style="font-weight:bold;"> Note </font><br /> &emsp; 根据万有引力公式：<br />$$\vec{F}=G\times\dfrac{M\times m}{r^2}\cdot\vec{e}$$</p>
```

------------


同时要在语法设置里，打开 mathjax 语法开关，并在 mathjax 里打开`兼容通用写法` 选项

![image](https://user-images.githubusercontent.com/57370/61610598-29e84e80-ac8c-11e9-9608-5af703ed520b.png)

**Comment by JingofXin** [comment]
@suziwen 真的解决了，太感谢了！
