### ISSUE TITLE
关于预览界面

### ISSUE THREAD

**Issue by WhiteUmaru** [suziwen/markdownxiaoshujiang#1133]
我感觉预览页的字体过于大了，感觉就是巨大！ 
可不可以稍微调小点字体
还有就是 我感觉预览页 有点丑。。。
![image](https://user-images.githubusercontent.com/29397850/61353042-650c0b80-a8a1-11e9-8e5c-01e27975876d.png)

**Comment by lanyuanxiaoyao** [comment]
> 我感觉预览页的字体过于大了，感觉就是巨大！
> 可不可以稍微调小点字体
> 还有就是 我感觉预览页 有点丑。。。
> ![image](https://user-images.githubusercontent.com/29397850/61353042-650c0b80-a8a1-11e9-8e5c-01e27975876d.png)

可以自定义预览的样式, 你上网找个好看的样式就行了...

**Comment by suziwen** [comment]
这个需要自定义 css 样式， 
比如

```
h1{
    font-size: 41px;
}
h2 {
    font-size: 34px;
}
```

**Comment by WhiteUmaru** [comment]
可以使用第三方的主题css吗 比如 typora 之类的

**Comment by suziwen** [comment]
可能不兼容，因为生成的 html 结构可能不一样，需要自己微调。

**Comment by lihua45678910** [comment]
那我冒昧的问一句 官方可能出现自定义主题的工具吗

**Comment by WhiteUmaru** [comment]
谢谢 明白了 请问后续会有”第三方自制主题支持“之类的方向吗

**Comment by suziwen** [comment]
暂时不会，自定义 css 功能，需要用户自己对 html , css 有一些基础的了解。 或者网上看有没有人分享，直接粘贴过来。

**Comment by WhiteUmaru** [comment]
好的
