### ISSUE TITLE
列表项渲染后行距的相关问题

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [suziwen/markdownxiaoshujiang#1134]
![示例](https://i.loli.net/2019/07/19/5d316a61bb71c64868.png)

如图所示, 列表项应该是标题与正文行距较宽, 正文与正文之间行距较窄才对, 但是同一组列表项若第一项和第二项之间没有空行, 那么所有列表项的所有行距都像标题与正文的行距一样宽, 不太美观, 这应该是个bug, 因为不管有多少列表项, 只要第一项和第二项如上图所示加了空行, 那么第二项往下的所有列表项都正常, 如果不加就大家都不正常, 如下图所示

![示例](https://i.loli.net/2019/07/19/5d316b61d263642853.png)

另外, 这和我的自定义样式应该无关, 因为我切换了其他预览样式均出现同样的结果

**Comment by suziwen** [comment]
我这边看着好像是正常的， 你是不是自定义 css 样式了？

````
# 演示

## 空行前
- 列表1
列表内容
列表内容
- 列表2
列表内容
列表内容

## 空行后
- 列表1
列表内容
列表内容

- 列表2
列表内容
列表内容



````

![image](https://user-images.githubusercontent.com/57370/61611031-4c2e9c00-ac8d-11e9-9be2-319ffd0ebbf9.png)

**Comment by lanyuanxiaoyao** [comment]
> 我这边看着好像是正常的， 你是不是自定义 css 样式了？
> 
> ```
> # 演示
> 
> ## 空行前
> - 列表1
> 列表内容
> 列表内容
> - 列表2
> 列表内容
> 列表内容
> 
> ## 空行后
> - 列表1
> 列表内容
> 列表内容
> 
> - 列表2
> 列表内容
> 列表内容
> ```
> 
> ![image](https://user-images.githubusercontent.com/57370/61611031-4c2e9c00-ac8d-11e9-9be2-319ffd0ebbf9.png)

结案了...确实是自定义样式的问题, 因为空一行比不空一行会把<li>的内容包裹在一个<p>标签里, 导致引用了<p>标签的样式, 导致上述问题. 我调整一下我的样式就好.
![](https://i.loli.net/2019/07/22/5d358c441df7e93533.png)
