### ISSUE TITLE
支持类图的语法吗？

### ISSUE THREAD

**Issue by aeagean** [suziwen/markdownxiaoshujiang#1135]
如果有支持就好了。

**Comment by suziwen** [comment]
可以使用 plantuml 语法 

http://soft.xiaoshujiang.com/docs/grammar/feature/plantuml


````
``` plantuml! 
class User { 
  username 
  password 
  +sign_in() 
} 
 
class Group { 
  name 
} 
 
class Member { 
  roles 
} 
 
User .. Member 
Group .. Member 
``` 
````

![image](https://user-images.githubusercontent.com/57370/61610261-37510900-ac8b-11e9-8257-db9779297c81.png)

**Comment by aeagean** [comment]
> 可以使用 plantuml 语法
> 
> http://soft.xiaoshujiang.com/docs/grammar/feature/plantuml
> 
> ```
> ``` plantuml! 
> class User { 
>   username 
>   password 
>   +sign_in() 
> } 
>  
> class Group { 
>   name 
> } 
>  
> class Member { 
>   roles 
> } 
>  
> User .. Member 
> Group .. Member 
> ``` 
> ```
> 
> ![image](https://user-images.githubusercontent.com/57370/61610261-37510900-ac8b-11e9-8257-db9779297c81.png)
太好了
