### ISSUE TITLE
无法加载为知笔记V2

### ISSUE THREAD

**Issue by JingofXin** [suziwen/markdownxiaoshujiang#1136]
为知笔记今天忽然就无法加载，也无法保存了。
加载出错：
`
加载出现错误{"code":1009,"error":"服务器错误","orign":{"returnCode":301,"returnMessage":"Invalid token","externCode":"","code":301,"return_code":301,"return_message":"Invalid token"}}
`
保存出错：
`
保存失败: {"code":1009,"error":"服务器错误","orign":{"returnCode":301,"returnMessage":"Invalid token","externCode":"","code":301,"return_code":301,"return_message":"Invalid token"}}
`

**Comment by suziwen** [comment]
好像是为知升级了 api , 这边要跟进调整。

**Comment by suziwen** [comment]
7.8.0 版本已经跟进 api 修改

http://soft.xiaoshujiang.com
