### ISSUE TITLE
CodeMirror 编辑器编辑区中如何设置代码块字体

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [suziwen/markdownxiaoshujiang#1137]
如下图代码块的字体并没有使用指定的字体
![](https://i.loli.net/2019/07/23/5d365b576bded93558.png)
![](https://i.loli.net/2019/07/23/5d365baca5d2412455.png)

**Comment by suziwen** [comment]
我的可以， 你是不是自己电脑没有安装   Consolas 字体？

![image](https://user-images.githubusercontent.com/57370/61675447-f6a8cc80-ad2a-11e9-951a-b3980e142555.png)


![image](https://user-images.githubusercontent.com/57370/61675467-088a6f80-ad2b-11e9-8c01-bda0ba208325.png)

**Comment by lanyuanxiaoyao** [comment]
> 我的可以， 你是不是自己电脑没有安装 Consolas 字体？
> 
> ![image](https://user-images.githubusercontent.com/57370/61675447-f6a8cc80-ad2a-11e9-951a-b3980e142555.png)
> 
> ![image](https://user-images.githubusercontent.com/57370/61675467-088a6f80-ad2b-11e9-8c01-bda0ba208325.png)

似乎只对`java`打头的管用 ? 😂
![](https://i.loli.net/2019/08/01/5d4238db2740521058.png)

**Comment by suziwen** [comment]
在`设置>基本` 里，有一个全局样式自定义，可以在那里添加下面的内容

``` css
.cm-xsj_code {
    font-family: 'Consolas', '微软雅黑', monospace;
}
```

![image](https://user-images.githubusercontent.com/57370/62258375-bb9a4d80-b43c-11e9-9a31-822f05523c25.png)

**Comment by lanyuanxiaoyao** [comment]
> 在`设置>基本` 里，有一个全局样式自定义，可以在那里添加下面的内容
> 
> ```css
> .cm-xsj_code {
>     font-family: 'Consolas', '微软雅黑', monospace;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/57370/62258375-bb9a4d80-b43c-11e9-9a31-822f05523c25.png)

嗯嗯, 是的, 这就管用了, 话说这个全局自定义样式我一直以为是调界面的? 没想到编辑器也归它管.

**Comment by suziwen** [comment]
是的，不过这个需要对 html 和 css 比较熟悉的用户才好操作。
