### ISSUE TITLE
处理文件样式关联失败

### ISSUE THREAD

**Issue by tuke0919** [suziwen/markdownxiaoshujiang#1139]
![image](https://user-images.githubusercontent.com/13417140/61799649-142a8300-ae5e-11e9-897a-2b20e23cab3c.png)

预览区的css样式：
h1{
font-size:30px
}
h2{
font-size:25px
}
h3{
font-size:20px
}
strong{
 color:blue;
}
code{
background: #FF3E96;
color:#FFFFFF
}

文章信息：
文章中使用md表格，表格中插入了16张图片，图床是github，已经升级了最新版7.7.0，之前因为保存这篇文章，好几次闪退软件。使用的是Mac版本，印象笔记里也是只保存了md文件，没有内容

给点意见哈。

**Comment by suziwen** [comment]
是只有这篇文章会出现失败？

我测试了下你给的样式，我这边是可以正常保存的。

可以试着使用 32 位版本的小书匠看看。 https://github.com/suziwen/markdownxiaoshujiang/issues/1052#issuecomment-475642940

**Comment by tuke0919** [comment]
> 是只有这篇文章会出现失败？
> 
> 我测试了下你给的样式，我这边是可以正常保存的。
> 
> 可以试着使用 32 位版本的小书匠看看。 [#1052 (comment)](https://github.com/suziwen/markdownxiaoshujiang/issues/1052#issuecomment-475642940)

是的，只有这一篇文章是的，新建空文件和保存其他文件是正常的。好像mac版本没有32位的。今早新打开mac，只开了浏览器2个网页，然后打开小书匠，再次保存这篇文章还是同样的错误。

**Comment by suziwen** [comment]
能把这个文件导出成 zip 格式，发到我邮箱 suziwen1@gmail.com 上吗。

或者提供一篇能重现的测试文章发到我邮箱上。我这边看下。

**Comment by tuke0919** [comment]
> 能把这个文件导出成 zip 格式，发到我邮箱 [suziwen1@gmail.com](mailto:suziwen1@gmail.com) 上吗。
> 
> 或者提供一篇能重现的测试文章发到我邮箱上。我这边看下。

已发送哈

**Comment by suziwen** [comment]
还是没法重现你说的情况，

你试着新建一篇文章，把该文章的内容复制到新文章后，再保存呢？

如果还是失败，那就先把两个包含比较多图片的表格删除掉，再保存这个新的文件呢？

**Comment by tuke0919** [comment]
> 还是没法重现你说的情况，
> 
> 你试着新建一篇文章，把该文章的内容复制到新文章后，再保存呢？
> 
> 如果还是失败，那就先把两个包含比较多图片的表格删除掉，再保存这个新的文件呢？

发现新建一篇文章，只要有那两个表格+图片，都不行。

**Comment by suziwen** [comment]
试一下导出 html ，然后选项选择下面几个，看能不能导出成功。

![image](https://user-images.githubusercontent.com/57370/61924091-e85fe800-af98-11e9-98b9-3ce126272bd5.png)
