### ISSUE TITLE
方向键还是时不时无效

### ISSUE THREAD

**Issue by unlackingc** [suziwen/markdownxiaoshujiang#114]
联想G400-win8-x64系统
版本7.1
32位和64位都实验了。但还是方向键不好用
这么好的软件，**楼主加油～**
## 调试信息
1. 使用google中文拼音是
2. 使用ctrl+c复制粘贴后

**Comment by suziwen** [comment]
ace编辑器,还是轻量编辑器.
方向键不好具体点是什么情况下发生?文字很多?预览窗口是打开还是关闭状态?
我这边自己在用一直都没有这种情况,最好能提供详细些.

**Comment by unlackingc** [comment]
难道是因为我调的vim模式。
是不是我蠢了。。

**Comment by unlackingc** [comment]
我将键盘模式从vim调回默认就好了
我对vim懂得不多，所以可能是自己的问题
**楼主好勤劳，加油~**

**Comment by unlackingc** [comment]
![a](https://cloud.githubusercontent.com/assets/11269996/11960809/76f6940e-a90f-11e5-9a44-ac8f8e846c38.png)


然后是 这样
![b](https://cloud.githubusercontent.com/assets/11269996/11960851/aaf04d7c-a90f-11e5-8c3c-757480b461da.png)

**Comment by suziwen** [comment]
vim模式方向键好像也是正常的,不过我平时都是默认模式写东西.vim下测试得少.

**Comment by unlackingc** [comment]
## 楼主好，我已经发现bug的真正面目了：
是这样，我用的是win8系统前面已经说过。

每次当我**切换输入法（winkey+space）**以后，ace编辑器的上下左右键就不能用！！

但**轻量级编辑器不存在这样的问题。
所有的**ace键盘模式**都试过了
**请务必关注**
给出我的输入法配置附图：

![image](https://cloud.githubusercontent.com/assets/11269996/11971417/629d4b6a-a978-11e5-88d7-49f2f5535260.png)


## 其他
当我切换中文（简体，中国）和英语（美国）是会出现问题，
但如果我按ctrl+space切换输入法内选项时，则不会出错。

**Comment by suziwen** [comment]
收到,会尽快修复,这个好像只有win8才会出现.

**Comment by suziwen** [comment]
https://github.com/ajaxorg/ace/issues/2258

https://github.com/ajaxorg/ace/pull/2617

**Comment by suziwen** [comment]
1.8.0已解决，欢迎下载使用

**Comment by unlackingc** [comment]
谢谢楼主，祝小书匠越做越好
