### ISSUE TITLE
打字时没有隐藏指针

### ISSUE THREAD

**Issue by Lanple-LPW** [suziwen/markdownxiaoshujiang#1140]
打字时没有隐藏指针，特别是写作模式下，很需要指针隐藏。
我用的win10系统，控制面板-鼠标属性-指针选项下面有一个“在打字时隐藏指针”的选项，这项功能可以在编辑word文档时正常使用。

**Comment by Lanple-LPW** [comment]
还有就是写作模式下按Enter，希望能够连换两行（或一行，在设置里设置）并在第二行开头加上两个全角空格（加不加同样可以设置）。现在在一行开头有两个全角空格时按Enter键会到下一行并在开头自动添加两个英文空格，这是写英文文章的习惯啊，我还得去掉这两个空格再输入两个全角空格，很麻烦。

**Comment by suziwen** [comment]
7.8.0 版本提供了自动指针隐藏功能
