### ISSUE TITLE
思维脑图grammar_mindmap的显示字体有点小，怎么能调大点？

### ISSUE THREAD

**Issue by bcaso** [suziwen/markdownxiaoshujiang#1141]

**Comment by suziwen** [comment]
这个现在还没有。

**Comment by suziwen** [comment]
7.8.0 版本提供了字体大小参数，可以参考这里  http://soft.xiaoshujiang.com/docs/grammar/feature/mindmap/

http://soft.xiaoshujiang.com/download/
