### ISSUE TITLE
如何开启时不显示预览？

### ISSUE THREAD

**Issue by zhpencil** [suziwen/markdownxiaoshujiang#1143]
在使用CodeMirror编辑器的情况下，已经能实现预览了。
然而小书匠启动时会自动开启预览，显得很多余，每次都需要手动关闭。
请问如何默认关闭预览或者有什么关闭预览的快捷键吗？

**Comment by zhpencil** [comment]
CTRL+SHIFT+P 关闭预览的快捷键
如何默认关闭预览?

**Comment by suziwen** [comment]
这个确认是个 bug， 正常会记住上次关闭时的状态。

**Comment by zhpencil** [comment]
> 这个确认是个 bug， 正常会记住上次关闭时的状态。

哇，意外地发现了一个BUG吗？好开心。
谢谢大大，小书匠超好用，现在我们整个宿舍都在用。😂

**Comment by suziwen** [comment]
感谢支持:heart:
