### ISSUE TITLE
7.7.4 更新后 打不开

### ISSUE THREAD

**Issue by THIISPAN** [suziwen/markdownxiaoshujiang#1146]
一直停留在logo无限加载，进入不到 编辑页面。

**Comment by THIISPAN** [comment]
卸载重装也不管用

**Comment by suziwen** [comment]
通过其他编辑器新建一个扩展名为 md 的空白文件，然后用小书匠关联打开该文件呢？

类似命令行 `Stroy-writer.exe d:\temp.md`

**Comment by THIISPAN** [comment]
> 通过其他编辑器新建一个扩展名为 md 的空白文件，然后用小书匠关联打开该文件呢？
> 
> 类似命令行 `Stroy-writer.exe d:\temp.md`

试过了，这也不管用啊

**Comment by THIISPAN** [comment]
不好使啊，这也不管用。

**Comment by suziwen** [comment]
那就先把数据目录移到其他地方备份下，重新启动，再登录，升级到 7.7.4 呢？

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```
