### ISSUE TITLE
公式的竖线“|”与表格的竖线“|”冲突

### ISSUE THREAD

**Issue by JingofXin** [suziwen/markdownxiaoshujiang#1147]
表格中插入数学公式，当数学公式包含竖线“|”时候，该竖线被判为了表格的分隔竖线“|”。
例如：
```
a |b
--|--
$P(A|B)$ | 0
```
![image](https://user-images.githubusercontent.com/31361630/62208959-cf0cd080-b3ca-11e9-8c8b-8dd3dd541205.png)
类似该问题的具体描述与示例：
[https://github.com/atom-community/markdown-preview-plus/issues/185](https://github.com/atom-community/markdown-preview-plus/issues/185)

**Comment by suziwen** [comment]
可以用小书匠默认支持的公式语法来处理，
比如这样写

```
a |b
--|--
`!$P(A|B)$` | 0
```
