### ISSUE TITLE
小书匠发布到博客园不显示内容

### ISSUE THREAD

**Issue by ittimeline** [suziwen/markdownxiaoshujiang#1149]

**Comment by ittimeline** [comment]
小书匠将文章发布到博客园，提示发送成功，但是登陆博客园账号，并没有更新文章内容。
小书匠版本:7.7.0
windows,macOS版本均有此现象

**Comment by ittimeline** [comment]
macOS版小书匠7.3.0能够正常发布博客到博客园

**Comment by suziwen** [comment]
我这边测试了下，好像没有问题， 这是我刚刚发的测试文章

https://www.cnblogs.com/suziwen/p/11296449.html

https://www.cnblogs.com/suziwen/p/11296458.html

**Comment by suziwen** [comment]
你的操作系统版本是 window 7 ,8,10?

**Comment by ittimeline** [comment]
win10 1903，macOS10.14.6

**Comment by suziwen** [comment]
我刚 win 10 下测试了，也可以正常发布。

你可以试着把  数据目录 删除（或者临时移动备份），再启动小书匠，看能不能正常发布

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```


--------------

如果还是不行的话，感觉跟你的系统其他应用设置干扰有关，或者你的博客园选项设置有关。

**Comment by ittimeline** [comment]
我觉得跟博客园设置以及系统其它应用没关系啊，回退到7.5.0版或者是7.3.0版后发布到博客园的功能能用了。windows和macOS我都试过

**Comment by suziwen** [comment]
主要是我这边没法重现，

暂时只能看看还有没有其他用户反馈类似的问题，及提供的一些更详细的参考信息了。

**Comment by ittimeline** [comment]
没法重现确实挺那个啥的，我就用7.5.0版的了

**Comment by ittimeline** [comment]
刚刚又装了7.7.0版，又能发布到博客园了
