### ISSUE TITLE
关于同步到印象笔记出错，无法刷新目录

### ISSUE THREAD

**Issue by youxunlong** [suziwen/markdownxiaoshujiang#115]
![1](https://cloud.githubusercontent.com/assets/12827520/11995271/c201f0d6-aa88-11e5-9301-1523000970a9.png)
![2](https://cloud.githubusercontent.com/assets/12827520/11995273/c2058a02-aa88-11e5-8a6c-f12a1c6bce5c.png)
![3](https://cloud.githubusercontent.com/assets/12827520/11995272/c205418c-aa88-11e5-8dcc-f8812d0c65a1.png)

没法刷新目录，导致没法同步到印象笔记中

**Comment by suziwen** [comment]
连接超时,检查下你的网络是否可以直接访问印象笔记

**Comment by youxunlong** [comment]
在公司的网络可以同步到印象笔记(电信+有线)，但是回家就会出现这种现象(移动+无线)
印象笔记都是能直接访问的

**Comment by suziwen** [comment]
检查一下是不是防火墙等应用限制了网络访问.

**Comment by youxunlong** [comment]
在家里把腾讯管家关了就没事了，无语
