### ISSUE TITLE
win7-x64客户端最新版，github图床上传图片后远程仓库中有图片，客户端一直显示加载中

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1152]
win7-x64客户端最新版，github图床上传图片后远程仓库中有图片，客户端一直显示加载中。

![image](https://user-images.githubusercontent.com/12257223/62834839-53413c80-bc84-11e9-83c4-0a8ef9273f8c.png)

但是在浏览器中输入图片地址可以访问啊，访问速度也快.

github图床设置如下：
![image](https://user-images.githubusercontent.com/12257223/62835011-1413eb00-bc86-11e9-9919-f8a5aae04d2d.png)

图片上传后地址: `![x](https://www.github.com/juejian/mblog_imgs/raw/master/imgs2/2019/08/11/f5392a6fe24752648314d9f12e6064ea.jpg)`

用sublime3 markdown编辑器 和 Haroopad markdown编辑器预览图片也可以正常显示啊。

在这个评论框输入以上图片地址也可以显示：如下
![图片](https://www.github.com/juejian/mblog_imgs/raw/master/小书匠测试/2019/08/11/f5392a6fe24752648314d9f12e6064ea.jpg)

**是不是小书匠对图片url解析存在限制???**

**Comment by suziwen** [comment]
你这个是每次粘贴都会出现这种情况吗？

----------


我这里有时也会出现加载图片提示一直转的情况，然后等了很久图片才显示出来。

暂时分析好像是 github 网络的原因，有时访问请求要很长的时间，甚至超时。有时可以很快就显示出来。可以通过切换文章，重新进行加载这些图片资源。


或者自己设置一个翻墙代理试试。

**Comment by juejian** [comment]
今早上突然好了，可能是网络的问题。
