### ISSUE TITLE
发布博客到博客园时如何设置分类和标签，如何批量发布？

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1153]
按照以下格式设置的参数均未生效。

```
---
title: css基本语法、选择器、继承、层叠、优先级
dateCreated: 2018-10-21 20:00:00
categories: web前端,css
tags: web前端,css
mt_keywords: web前端,css,选择器,继承,层叠,优先级,CSS5的误解
---
```

**Comment by suziwen** [comment]
这样写

```
weblog_categories: ["小书匠", "语法", "新建", "模板"]
weblog_mt_keywords: "测试,添加新的标签,成功,abc"
```

-----------

所有 metaweblog 的 api 提交的 post 字段，可以通过元数据添加前缀 `weblog_`  来实现。

https://codex.wordpress.org/XML-RPC_MetaWeblog_API


----

需要注意的是， categories 对应的名称需要先在博客园先创建好。

**Comment by suziwen** [comment]
暂时没有提供批量发布的功能。

**Comment by juejian** [comment]
谢谢解答，不过：

你提供的是wordpress中元数据的写法，不是博客园中的，我测试过发现无效。

最后经过测试发现将以下代码放到发布文章时的自定义ymal框中，**发布文章才会生效**（放在文章中不会生效，前面加weblog_ 和使用元数据发送地址https://rpc.cnblogs.com/metaweblog/jsword也不行）

目前文章的标题、目录、标签发布后都正常，但是自定义的dateCreated(创建时间)无论采用哪种时间格式都不会生效。显示的都是当前时间。

![image](https://user-images.githubusercontent.com/12257223/62879754-6fb1a780-bd5e-11e9-87c2-35896de4e6dd.png)

**Comment by suziwen** [comment]
在文章里的话，为了防止和小书匠的一些元数据冲突，需要添加前缀 `weblog_` , 再提交给博客服务器时，会自动把该前缀去除。

在自定义  yaml 数据里的话，可以不添加前缀。（但是建议添加前缀）


-------------


创建时间的话，刚才测试了下，不知道是 wordpress 的 xmlrpc 解析 bug ,还是我这边的问题，规范里说是提交 iso8601 格式的数据， 我查了下[规范](https://en.wikipedia.org/wiki/ISO_8601)，应该是 `YYYY-MM-DDTHH:MM:SSZ` 这种格式 ，所以我这边提交时，是类似这种格式 `2014-02-11T11:02:57Z` 的时间, 而 wordpress    [源代码](https://github.com/WordPress/WordPress/blob/06fa4161aa74619239cf27017d124081c825684a/wp-includes/IXR/class-IXR-date.php#L49)里却需要我提交这种格式的数据 `YYYYMMDDTHH:MM:SSZ`

在我本地修改掉这个bug 后，把时间提交改成 `YYYYMMDDTHH:MM:SSZ` 格式，是可以正常修改 wordpress 的发布时间的，**但是测试了下博客园，好像还是不能修改，不知道是不是博客园对这个时间进行了限制。**

**Comment by juejian** [comment]
除了发布时间，其他问题解决了,以下的**设置必须放在文件开头**，从第二行开始放，就无效了。

发布时间可能是博客园为了防止抄袭而不能自定义吧，否则别人抄袭你的文章，修改发布时间，其他人看来还是你抄了别人的。。

```
---
weblog_post_type: post
weblog_title: css基本语法、选择器、继承、层叠、优先级
weblog_description:  主要讲述css基本语法、选择器、继承、层叠、优先级
weblog_categories: ["html","css"]
weblog_mt_keywords: "css,web"
weblog_dateCreated: 2014-02-11 11:00:02
---
```
