### ISSUE TITLE
gmail无法收到验证邮件

### ISSUE THREAD

**Issue by bmh27088** [suziwen/markdownxiaoshujiang#1154]
已查看垃圾箱里无邮件 邮箱地址: bmh27088@email.vccs.edu
和其他邮箱都可以往来邮件，就是收不到github的验证邮件

**Comment by suziwen** [comment]
我在小书匠后台没看到有这个邮箱（bmh27088@email.vccs.edu）的注册用户 ，你是不是用其他邮箱地址注册的小书匠用户？

**Comment by bmh27088** [comment]
小书匠是什么？我是注册github的时候绑定了一个edu邮箱，验证的时候收不到验证邮件，后面又添加了一个126邮箱验证了，但是这个edu邮箱还是验证不了
