### ISSUE TITLE
图床无法正常替换

### ISSUE THREAD

**Issue by suxuemi** [suziwen/markdownxiaoshujiang#1157]
![image](https://user-images.githubusercontent.com/42887808/63252884-44214680-c2a3-11e9-9cea-7acf92270334.png)

**Comment by suziwen** [comment]
感觉像是图片原地址里可能有特殊符号，造成替换失败。

能把 markdown 文件发到我邮箱 suziwen1@gmail.com 里吗， 我测试下。

**Comment by suxuemi** [comment]
@suziwen  发了   请查收下

**Comment by suziwen** [comment]
测试了下，可以正常转换你发的文章里的图片。

你那转换到小书匠内置数据库里也不可以？还是你自己的 图床  `tu-201908` 也不行？

客户端版本是多少？
