### ISSUE TITLE
文件无法保存到本地 win10 版本7.7.0

### ISSUE THREAD

**Issue by ggunlics** [suziwen/markdownxiaoshujiang#1158]
将写好的md文件另存为本地时, 显示保存成, 但是本地却没有该文件

**Comment by suziwen** [comment]
这个可以暂时先用导出 markdown 功能。或者先通过操作系统创建 md 文件，然后另存为时，选择这个新的文件。

后面版本会修复这个 bug。

**Comment by suziwen** [comment]
7.8.0 版本已修复

http://soft.xiaoshujiang.com/download/
