### ISSUE TITLE
7.4.0 版本写文档时光标位置随机跳动

### ISSUE THREAD

**Issue by starsky9527** [suziwen/markdownxiaoshujiang#1159]
这个问题文字不好描述，就是在记录笔记时，光标直接跳到了笔记的其它位置，不在编写的位置，这个真的很影响笔记的体验。

录了个 gif，一看就明白了，

**Comment by suziwen** [comment]
gif ?

**Comment by starsky9527** [comment]
这块不清楚怎么上传 gif，发你 苏滋文 <notifications@github.com> 这个邮箱了，麻烦看下

**Comment by suziwen** [comment]
发这个邮箱地址 

suziwen1@gmail.com

**Comment by starsky9527** [comment]
已发送

**Comment by suziwen** [comment]
`小书匠主按钮>设置>编辑器>codemirror` 里，把 `打印机滚动效果` 关掉

![image](https://user-images.githubusercontent.com/57370/63336600-ffb0ac00-c371-11e9-883f-3cc48d7f7a13.png)

**Comment by starsky9527** [comment]
谢谢大佬，问题解决了
