### ISSUE TITLE
数学公式，流程图等扩展无法使用；

### ISSUE THREAD

**Issue by ShomyLiu** [suziwen/markdownxiaoshujiang#116]
版本： Linux版最新客户端，　数学公式和流程图块，无法渲染，，求解啊！！！

**Comment by suziwen** [comment]
公式,流程图默认没有打开,可以到 `设置-->语法扩展` 里打开,也可以在每篇文章的元数据部分单独打开
`grammar_mathjax: true`, `grammar_flow: true`, `grammar_sequence: true`,
公式语法跟其他编辑器(像stackedit)有些区别,都是代码块里包裹起来,并且前面有个感叹号
~~~~
`!$a$`
~~~~
~~~~
``` mathjax!
$$
a
$$
` ``
~~~~
