### ISSUE TITLE
本地客户端PDF导出或者打印时，图片不显示

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#1161]
如题，使用本地客户端PDF导出选项或者打印选项时，图片不显示，使用PDF导出功能可以显示。导出HTML也正常。

**Comment by suziwen** [comment]
需要提供一篇能重现的文章

可以把该文章用小书匠的导出  zip 功能 , 然后发到我邮箱里 suziwen1@gmail.com

**Comment by jianzs** [comment]
已经发给你了。应该是我这边的问题，我应该怎么Debug？

**Comment by suziwen** [comment]
确认是 bug。原因是我程序这边网络图片没下载完，就直接执行 pdf 导出了。

暂时只能使用网页版本的小书匠打印，或者客户端上将里面的网络图片转移成小书匠默认的本地存储 (类似 `./images/xxxxxx.jpg`)，然后客户端 pdf 打印。

**Comment by suziwen** [comment]
7.8.0 版本已修复

http://soft.xiaoshujiang.com/download/
