### ISSUE TITLE
ppt模式下图片无法显示

### ISSUE THREAD

**Issue by ieeloleei** [suziwen/markdownxiaoshujiang#1162]
进入ppt模式预览总是看不到图片，显示异常，左上角有个破碎图片的标志，而普通预览模式则毫无问题。
在编辑的过程中保存或刷新预览，ppt模式预览图片就能看到，但闪一下接着就异常了。

ppt模式总是看不到图片：
![image](https://user-images.githubusercontent.com/22229263/63582611-f9b60780-c5cb-11e9-8c89-0858398816cb.png)
普通预览都没有问题：
![image](https://user-images.githubusercontent.com/22229263/63582814-5a454480-c5cc-11e9-9bd4-2ad3e9e3134e.png)

谢谢!

**Comment by suziwen** [comment]
能把重现的文章用小书匠的导出功能，导出成 zip 格式，发我邮箱下吗， 邮箱地址: suziwen1@gmail.com

**Comment by ieeloleei** [comment]
> 能把重现的文章用小书匠的导出功能，导出成 zip 格式，发我邮箱下吗， 邮箱地址: [suziwen1@gmail.com](mailto:suziwen1@gmail.com)

已经发送了，请看看。

**Comment by suziwen** [comment]
确认 bug。下个版本会修复。

**Comment by ieeloleei** [comment]
谢谢，辛苦了。

**Comment by suziwen** [comment]
7.8.0 版本已修复

http://soft.xiaoshujiang.com/download/
