### ISSUE TITLE
文章内容格式错乱

### ISSUE THREAD

**Issue by ittimeline** [suziwen/markdownxiaoshujiang#1163]
![xiaoshujiang](https://user-images.githubusercontent.com/45027871/63630394-c1a2d900-c64c-11e9-87da-09ab680cb708.png)
为什么打开之前写的文章内容格式错乱了，图片、文本、代码都显示错乱

![image](https://user-images.githubusercontent.com/45027871/63630414-ea2ad300-c64c-11e9-973d-4f3849d5b6e3.png)

**Comment by suziwen** [comment]
你的打开是指打开保存到第三方存储的文章？还是没有使用第三方存储，直接点击右侧文件列表的打开？

**Comment by ittimeline** [comment]
我的文章是保存在印象笔记的。

**Comment by ittimeline** [comment]
所有的文章全错乱了

**Comment by suziwen** [comment]
这个应该是你在印象笔记里做了修改。然后再通过小书匠打开 。格式就没办法保存住，小书匠只能尝试通过  html 转换成 markdown 的方法进行转换。

**Comment by ittimeline** [comment]
那这就是以后使用小书匠保存在印象笔记的文章，只能在小书匠修改，不能在印象笔记修改是吧

**Comment by suziwen** [comment]
如果不想误修改保存到印象笔记的文章，可以尝试在绑定界面里打开保护文档选项。这样保存到印象笔记的文章就会成为只读状态。

![image](https://user-images.githubusercontent.com/57370/63630533-47735400-c64e-11e9-8ba1-54cf38226ee7.png)

**Comment by suziwen** [comment]
嗯，只要在印象笔记修改的话，因为要再一次将 html 转换成 markdown 格式，这种转换必然会造成样式的丢失。

**Comment by ittimeline** [comment]
好的，谢谢了
