### ISSUE TITLE
写好的文章发布到csdn上面的bug

### ISSUE THREAD

**Issue by cqhclys830** [suziwen/markdownxiaoshujiang#1164]
写好的文章发布到csdn上面的bug，显示 “ 发送失败  NOT FOUND”
博客地址为： https://blog.csdn.net/cqhclys830/
用户名，密码能正常登陆

**Comment by cqhclys830** [comment]
也显示，发送失败 error

**Comment by suziwen** [comment]
这个我记得 csdn 目前不支持 metaweblog api 的发布功能。

**Comment by ittimeline** [comment]
可以用csdn的同步功能，先把博客发布到博客园，再同步到CSDN就行了
