### ISSUE TITLE
建议:图床从本地转移到七牛后，图片链接建议加上http://

### ISSUE THREAD

**Issue by cqhclys830** [suziwen/markdownxiaoshujiang#1167]
j建议:图床从本地转移到七牛后，图片链接建议加上http://
目前是这样 `![enter description here](pwu9ixbaz.bkt.clouddn.com/xiaoshujiang/134627.jpg)`

建议改为
目前是这样 `![enter description here](http://pwu9ixbaz.bkt.clouddn.com/xiaoshujiang/134627.jpg)`
这样直接复制md内容到其他md编辑器才不会出错

**Comment by suziwen** [comment]
在绑定配置里，有提供自定义前缀的字段的。

![image](https://user-images.githubusercontent.com/57370/63769222-dc06dc00-c904-11e9-9362-74517e80b31b.png)

**Comment by frank1901s** [comment]
<img width="673" alt="为什么图片是以附件的形式显示的呢" src="https://user-images.githubusercontent.com/44490792/63831893-39049f80-c9a2-11e9-9ce5-142884106d8a.png">


可以帮我看看嘛，我不知道哪里出错了，为什么图片是以附件的形式显示的呢？
点击附件那里会跳转到图片页面

**Comment by suziwen** [comment]
@frank1901s 

`设置>预览` 里，把这个选项去掉，或者保证图片扩展名为 `jpg, png, gif, svg`

![image](https://user-images.githubusercontent.com/57370/63833817-7d923a00-c9a6-11e9-98f9-5ec853ae12b9.png)
