### ISSUE TITLE
代码块保存到印象笔记显示问题

### ISSUE THREAD

**Issue by pinsily** [suziwen/markdownxiaoshujiang#1168]
### 问题描述
在小书匠中编写的代码块背景色为黑色，如图所示：

![image](https://user-images.githubusercontent.com/19889043/63988436-e1d00d80-cb0e-11e9-8ca7-3b32540c4940.png)

但是保存到印象笔记之后背景色被改变了，导致颜色冲突看不清代码，如下图：

![image](https://user-images.githubusercontent.com/19889043/63988537-4723fe80-cb0f-11e9-8e2f-c405083251ff.png)

### 版本信息

![image](https://user-images.githubusercontent.com/19889043/63988551-5d31bf00-cb0f-11e9-88d7-de6744314dae.png)

**Comment by suziwen** [comment]
代码主题，预览主题选择了什么？

还有是不是自定义了 css 样式？

**Comment by pinsily** [comment]
@suziwen 

找到原因了，我自定义了行代码的 <code></code> 的样式，结果影响到了代码块 pre 里的code标签了

**Comment by suziwen** [comment]
行内代码的样式如果不想影响块代码样式，可以参考这样的写法

https://github.com/suziwen/markdownxiaoshujiang/issues/711#issuecomment-516250166
