### ISSUE TITLE
[BUG]自定义模板导出

### ISSUE THREAD

**Issue by dsclub** [suziwen/markdownxiaoshujiang#1169]
建立多个自定义模板，导出时提示是否导出所有模板数据，但是导出文件中只有最后一个模板的数据内容。

另外，在导出时，是不是可以选择只导出指定的模板内容。毕竟，自定义模板非常好用，但是会员也无法同步这个数据。

**Comment by suziwen** [comment]
1. 我这边导出时，导出的是所有的模板，没有重现你说的情况。
2. 导出时可以选择导出的模板这个可以后面考虑实现
3. 会员是可以自动同步自定义的模板内容

**Comment by dsclub** [comment]
好的，我把它卸载后再试试。

**Comment by dsclub** [comment]
重新安装后确实问题都解决了，是我自己机器的问题。谢了，小书匠非常好用！
