### ISSUE TITLE
同步到印象笔记序列号出现问题

### ISSUE THREAD

**Issue by youxunlong** [suziwen/markdownxiaoshujiang#117]
小书匠界面
![a](https://cloud.githubusercontent.com/assets/12827520/12030629/b1bd9088-ae3c-11e5-9254-f4b9c5e7f18e.png)
印象笔记界面
![b](https://cloud.githubusercontent.com/assets/12827520/12030630/b1bf5152-ae3c-11e5-8bef-e38c8d62b9b5.png)
序列号不对

**Comment by suziwen** [comment]
修复有序列表中含有无序列表，同步到Evernote中序号错误 #101

**Comment by suziwen** [comment]
我的还是不能重现，

这是我随便建的一篇，你试试有没有正常编号  
[filename.txt][0]

我这边是正常的

[0]: https://github.com/suziwen/markdownxiaoshujiang/files/73829/filename.txt

**Comment by suziwen** [comment]
先关了
