### ISSUE TITLE
每次需要清除缓存还能登录进去，不然一直在加载状态

### ISSUE THREAD

**Issue by zaza24kb** [suziwen/markdownxiaoshujiang#1172]

**Comment by suziwen** [comment]
客户端版本还是 web 版本？

客户端版本号是多少？

**Comment by zaza24kb** [comment]
Web 版本 浏览器 Chrome 75.03770.100

苏滋文 <notifications@github.com>于2019年9月2日 周一上午9:52写道：

**Comment by suziwen** [comment]
是不是你的浏览器插件引起的

试着创建浏览器自己的一个新用户，不要在这个浏览器里装插件 ，然后使用小书匠呢？

**Comment by zaza24kb** [comment]
目测不是，隐私模式下关闭扩展也有这情况，我升级下浏览器看看吧

苏滋文 <notifications@github.com>于2019年9月2日 周一上午10:08写道：

**Comment by suziwen** [comment]
那比较奇怪，我这边 Version 76.0.3809.132 (Official Build) (64-bit) 是没有问题的。

-----

你试着访问这几个网址呢

http://markdown.xiaoshujiang.com/

http://md.xiaoshujiang.com/

https://markdown.xiaoshujiang.com/

**Comment by zaza24kb** [comment]
http://md.xiaoshujiang.com/  这个地址可以了，不过发生了一件尴尬的事情，之前的文档基本没了；归档里也没找到

苏滋文 <notifications@github.com> 于2019年9月2日周一 上午10:28写道：

**Comment by suziwen** [comment]
这个不同的 url 地址，浏览器是当成不同的存储空间的，如果想要查看以前的文章，只能访问之前的 url 地址 。然后使用导出功能（或者数据库导出），再重新打开新的 url 地址，进行导入。

---------

不建议在浏览器里做为自己数据存储的，及时导出，或者保存到第三方存储平台。

**Comment by zaza24kb** [comment]
好的，感谢支持

苏滋文 <notifications@github.com> 于2019年9月2日周一 上午11:23写道：
