### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by aubreyzheng** [suziwen/markdownxiaoshujiang#1173]
为什么图片突然全都不能加载出来了？？？

**Comment by suziwen** [comment]
你的图片是存在哪的？

小书匠内置数据库？还是图床？

**Comment by aubreyzheng** [comment]
图床，在github，下面是其中一个

![enter description here](https://www.github.com/aubreyzheng/python_learn/raw/master/小书匠/1566956702247.png)

**Comment by aubreyzheng** [comment]
图床，在github，下面是其中一个

```![enter description here](https://www.github.com/aubreyzheng/python_learn/raw/master/小书匠/1566956702247.png)```

**Comment by suziwen** [comment]
我这没问题

![image](https://user-images.githubusercontent.com/57370/64086988-9e270f00-cd6d-11e9-8fcb-d54a58e4071c.png)

------------

你是用网页版小书匠，还是客户端？

**Comment by aubreyzheng** [comment]
用的是客户端，刚跟新的，不知道是否和更新有关系，全都无法正常显示

**Comment by suziwen** [comment]
什么错误提示，截图我看一下

**Comment by aubreyzheng** [comment]
之前右上角报了错，没在意，我刚把程序退出，重新打开就好了

**Comment by suziwen** [comment]
哦，下次再有这个错误，可以先截下图。

不过一般使用了图床，图片都是放在 github 上了，除非是 github 服务器或者网络问题，不然不会丢失的。
