### ISSUE TITLE
7.8 自定义模板中模板内容的标题和标签无法应用到正文中

### ISSUE THREAD

**Issue by ggunlics** [suziwen/markdownxiaoshujiang#1175]
新建的模板在填写标题和标签, 不改正文后, 用这个模板新建的文件标题和标签没有与模板标题、标签一致。
修改模板新建时的正文, 新建文件就会正常显示标题和标签。
这样的话模板新建时标题和标签没有意义

**Comment by suziwen** [comment]
系统对文章的标题和标签有一个优先级的规则，如果正文的元数据里定义了标题或者标签，文章的标题和标签属性就会被自动替换成元数据里对应的值。

如果正文里没有这些元数据标题和标签，文章属性里的标题和标签才会是模板创建的标题，标签。


-----------

注意区分这两个概念，`元数据标题`，`元数据标签`, `属性标题`, `属性标签`

只要有`元数据标题,标签`, 每次修改正文时，都会尝试覆盖`属性标题,标签`。
