### ISSUE TITLE
小书匠导出html目录修正

### ISSUE THREAD

**Issue by xiaoyilee** [suziwen/markdownxiaoshujiang#1176]
[https://www.cnblogs.com/xiaoyihappy/p/11456687.html](https://www.cnblogs.com/xiaoyihappy/p/11456687.html)

**Comment by suziwen** [comment]
不错 :+1: 

感谢反馈这个 bug, 还帮忙找出一种解决方案。



其实今天我也正在改这个问题，主要原因是我这边生成的 html 结构和该目录组件有些不兼容引起的。

系统为了处理一些定位兼容的问题(pdf, docx 定位等)，生成的 html 代码做了特殊处理，下面是一个一级标题生成的 html 片段。

``` html
<div class="xiaoshujiang_element xsj_anchor">
  <a name="e5b08fe4b9a6e58ca0_1" class="blank_anchor_name"></a>
  <a id="e5b08fe4b9a6e58ca0_1" class="blank_anchor_id"></a>
  <a name="小书匠" class="blank_anchor_name"></a>
  <a id="小书匠" class="blank_anchor_id"></a>
</div>
<h1 class="xsj_heading_hash xsj_heading xsj_heading_h1" id="e5b08fe4b9a6e58ca0_1">
<span class="xsj_heading_content">小书匠</span>
</h1>
```

正因为上面的代码，造成点击定位时，自动定位到 `xiaoshujiang_element xsj_anchor` 上，而目录组件判断还没有到 `h1` 这个标签位置，所以目录高亮就显示为前面一层的结构了。

打算下个版本改成这样的结构

``` html
<h1 class="xsj_heading_hash xsj_heading xsj_heading_h1" id="e5b08fe4b9a6e58ca0_1">
<div class="xiaoshujiang_element xsj_anchor">
  <a name="e5b08fe4b9a6e58ca0_1" class="blank_anchor_name"></a>
  <a id="e5b08fe4b9a6e58ca0_1" class="blank_anchor_id"></a>
  <a name="小书匠" class="blank_anchor_name"></a>
  <a id="小书匠" class="blank_anchor_id"></a>
</div>
<span class="xsj_heading_content">小书匠</span>
</h1>
```

**Comment by suziwen** [comment]
https://github.com/tscanlin/tocbot

这个链接是小书匠使用的目录脚本，

导出带脚本的 html 模板可以在客户端(window)安装目录下 `app/templates/toctemplate.html`  下找到。

然后就可以直接在 toctemplate.html 下修改，或者在`导出>自定位模板导出` 里修改了。

**Comment by xiaoyilee** [comment]
> https://github.com/tscanlin/tocbot
> 
> 这个链接是小书匠使用的目录脚本，
> 
> 导出带脚本的 html 模板可以在客户端(window)安装目录下 `app/templates/toctemplate.html` 下找到。
> 
> 然后就可以直接在 toctemplate.html 下修改，或者在`导出>自定位模板导出` 里修改了。

谢谢您的提示，已按照说明修改，目前功能良好，小书匠是我用过的最好的md编辑工具，功能强大。愿我们一起让小书匠越来越好。

**Comment by xiaoyilee** [comment]
> https://github.com/tscanlin/tocbot
> 
> 这个链接是小书匠使用的目录脚本，
> 
> 导出带脚本的 html 模板可以在客户端(window)安装目录下 `app/templates/toctemplate.html` 下找到。
> 
> 然后就可以直接在 toctemplate.html 下修改，或者在`导出>自定位模板导出` 里修改了。

感谢您的回复，已经根据说明修改配置，目前功能良好，小书匠是我见过的最好用的md编辑器，功能强大，愿小书匠越来越好。
