### ISSUE TITLE
bug: win7 v7.8.2 预览快捷键ctrl + shift + p 无效

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1177]
问题如上。

目前是否支持**快捷键修改**，小书匠预览的快捷键`ctrl + shift + p ` 可能与windows系统自带的快捷键冲突。

**Comment by suziwen** [comment]
这个现在还不能改快捷键。

------


我测试了下，可以正常使用 `ctrl + shift + p`, 应该是跟你系统上其他应用快捷键冲突了

**Comment by suziwen** [comment]
最新版本可以自定义快捷键，可以自己重新定义一下按键，这里有[说明](http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/)
