### ISSUE TITLE
小书匠绑定本地存储，放置附件出现超出30M大小的限制

### ISSUE THREAD

**Issue by HiHotzenplotz** [suziwen/markdownxiaoshujiang#1179]
如题，本地存储不需要上传文件，只涉及到拷贝的操作，应该不需要设置30M大小的限制吧？

**Comment by suziwen** [comment]
这个主要是不想让文章管理系统变成资源管理系统，而且图片太大的话，显示加载都需要比较大的内存，也是有性能的影响。

**Comment by HiHotzenplotz** [comment]
放置的是一个pdf文件,显示在md中也只是一个链接, 应该不涉及到内存吧.

**Comment by suziwen** [comment]
像导出 html, 保存到第三方存储时，对这些比较大的文件就需要更多的内存资源来处理。

**Comment by HiHotzenplotz** [comment]
了解
