### ISSUE TITLE
复制gif图片会变成静态图片

### ISSUE THREAD

**Issue by 52Lau** [suziwen/markdownxiaoshujiang#1181]
从网页上复制gif动图之后，到编辑器粘贴，上传七牛云之后会变成静态图片，复制gif的链接，图床转换之后也会变成静态图片

**Comment by suziwen** [comment]
1. 目前从剪切板无法复制 gif 动图。

2. web 版 `7.8.4` 应该修复了这个问题，你可以测试下。

**Comment by 52Lau** [comment]
好的
