### ISSUE TITLE
同步功能抽风了

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1182]
服务器抽风了，目前有两个小问题：
1. 对于历史的绑定我删除后，其仍然会显示回来，不知道是不是我多机登陆的问题，我每次删掉这些绑定，再打开其又回来了。怎么也删除不干净。
![image](https://user-images.githubusercontent.com/7530342/64935147-0bfd2b80-d882-11e9-92ea-aecf50284a0d.png)
2. 另存，在页面选择其他绑定，存入其他绑定之后，理论上应该是存在两份同名文件，但是好像目前会覆盖原来的，且选择之后下方的文档列表区，不会自动跳转。
![image](https://user-images.githubusercontent.com/7530342/64935257-cd1ba580-d882-11e9-929b-9250204a16cb.png)

**Comment by suziwen** [comment]
所有客户端更新到 `7.8.4 ` ，绑定的存储信息就可以正常删除了。

----------

另存为有一个规则，就是如果当前有选择一个默认存储的话，并且另存为的目标存储跟当前存储不是同一类型绑定存储，另存为就不会改变当前的关联信息。

还有就是另存为只是把文件保存到新的第三方存储，并不在本地创建一个新的副本。

**Comment by CharMingF** [comment]
> 所有客户端更新到 `7.8.4 ` ，绑定的存储信息就可以正常删除了。

绑定的还是无法删除，删除之后又回来了，有点崩溃 ，不过好像是我删除的太快了？还是没有保存？因为取消绑定，那个页面的确定是不能点击的，取消绑定的操作需要保存吗？ 

> 另存为有一个规则，就是如果当前有选择一个默认存储的话，并且另存为的目标存储跟当前存储不是同一类型绑定存储，另存为就不会改变当前的关联信息。
> 还有就是另存为只是把文件保存到新的第三方存储，并不在本地创建一个新的副本。

虽然跟word等的逻辑不同，更像是导出的功能，不过这样也没有问题，可以加到说明书里

**Comment by suziwen** [comment]
如果还没有删除的话，可以一台修改完后，另外一台先注销小书匠用户，再重新登录。这样应该能拿到最新的，这次登录后，以后应该就会正常同步绑定信息了。

**Comment by CharMingF** [comment]
> 如果还没有删除的话，可以一台修改完后，另外一台先注销小书匠用户，再重新登录。这样应该能拿到最新的，这次登录后，以后应该就会正常同步绑定信息了。

#1095 我去试试，不过登陆了好多设备，需要鸡贼的提下自己上次的需求了，😂

**Comment by suziwen** [comment]
这个原本想改的，后来发现有点复杂，内部逻辑也比较多，就只能延后了 😂

**Comment by suziwen** [comment]
刚想起来，如果重设置密码的话，系统就会自动强制所有已经登录的 token 失效。
