### ISSUE TITLE
LaTex公式不能够正常显示

### ISSUE THREAD

**Issue by shliang0603** [suziwen/markdownxiaoshujiang#1184]
@suziwen  LaTex公式不能够正常显示，如下图：
![image](https://user-images.githubusercontent.com/37186266/65119624-05f08180-da1f-11e9-9cf1-3b9696eb3f1c.png)

尝试了版本跟新到最新也不可以
![image](https://user-images.githubusercontent.com/37186266/65119705-1f91c900-da1f-11e9-8021-3ca7a4dece2a.png)

看了一些提交的issues，进行了` mathjax公式`设置，但是都没有能够解决我的问题
![image](https://user-images.githubusercontent.com/37186266/65119839-4bad4a00-da1f-11e9-8c24-29e19240d70c.png)

**Comment by shliang0603** [comment]
已经解决：
发现是由于最右边的勾没有打开（捂脸）
![image](https://user-images.githubusercontent.com/37186266/65120422-2ff67380-da20-11e9-986f-ca4946f8d793.png)

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/65120469-469cca80-da20-11e9-9368-1aa92b368311.png)

**Comment by shliang0603** [comment]
@suziwen  嗯，才发现，非常感谢您。
