### ISSUE TITLE
[建议]从印象笔记回去内容到小书匠时，能否按md附件输出？

### ISSUE THREAD

**Issue by dsclub** [suziwen/markdownxiaoshujiang#1185]
从小书匠保存到印象笔记的内容，一般都会同时保存了Markdown附件。然而再从印象笔记回去内容到小书匠时，内容就乱了，不是按照Markdown内容来渲染的。作者应该是考虑到，如果在印象笔记中又对内容修改后，按Markdown渲染可能无法保持内容一致。
但是，能否提供一个这样的选项，让用户自己做判断用附件渲染还是用内容渲染。

谢谢作者！

**Comment by suziwen** [comment]
这个也可以把文件保护起来，防止在印象笔记里误修改。这样下次从印象服务器拉取数据时，就会原样显示 markdown 文件了。

在绑定界面上，有设置选项。
