### ISSUE TITLE
MacOS 快捷键保存问题

### ISSUE THREAD

**Issue by zaza24kb** [suziwen/markdownxiaoshujiang#1189]
command + S 保存会提示下载网页，而不是保存

**Comment by suziwen** [comment]
应该是快捷键冲突了。

**Comment by suziwen** [comment]
最新版本可以自定义快捷键，重新定义一下保存操作的按键，这里有[说明](http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/)
