### ISSUE TITLE
小书匠会考虑出一个笔记间关联的网状视图查看功能吗？

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1196]
现在笔记功能已经非常牛了，但总觉得笔记间的关联少了点（当然这应该是我自己的问题）……

用过几个能把笔记间的联系可视化出来的软件，比如The Brain（偏向于思维发展等，笔记功能太弱。11.0之前都不支持MarkDown，11.0看Alpha版支持得也很有限）、ConnectedText（好像很久没有更新了，而且因为年代久远某些插件中文支持很烂）、TiddlyWiki（整体放一个文件里，东西多了很难保证效率。图片啥的全靠外链）、Zim（不支持PlantUML，且中文支持也不太好。而且它的网状结构图也太丑）
小书匠会考虑出一个网状视图的功能吗？

**Comment by suziwen** [comment]
笔记之间的关联现在还没有仔细想过，基本都是通过第三方存储的目录树来管理，或者使用标签。至于像你说的这些网状视图查看，我要先试一下这些软件，看看具体的使用场景是否合适。

**Comment by hexawing** [comment]
今天又逛到一个可以有笔记间链接的笔记软件，您可以参考一下：

https://github.com/zadam/trilium/wiki/Screenshot-tour

不过确实，像小书匠这样借助第三方软件的方式确实不好处理。要不干脆考虑出一个独立的软件算了XD

**Comment by suziwen** [comment]
最新版本的小书匠添加了一个 `category` 元数据属性，配合新提供的 [过滤器](http://soft.xiaoshujiang.com/docs/tutorial/filter/#e58886e7b1bbe8bf87e6bba4e599a8_5) 功能，可以实现树形展示的效果。

![image](https://user-images.githubusercontent.com/57370/68906678-13f12300-0780-11ea-873a-f1017261e142.png)


后继我会再考虑实现图形化显示效果，并且丰富笔记间的关联展示，比如一篇笔记引用另外的笔记，他们之间的关联展示等。

**Comment by hexawing** [comment]
@suziwen 您这截图是安装版的对吧？web版似乎没有看到呢。

**Comment by suziwen** [comment]
web 版本已经有了

![image](https://user-images.githubusercontent.com/57370/69243601-6302e200-0bde-11ea-9d99-edb22b0e0e2e.png)


教程可以看[这个](http://soft.xiaoshujiang.com/docs/tutorial/filter/)

**Comment by suziwen** [comment]
7.9.4 版本提供了[链接关系图](http://soft.xiaoshujiang.com/docs/tutorial/internal_link/#e993bee68ea5e585b3e7b3bbe59bbe_7)功能

![image](https://user-images.githubusercontent.com/57370/69894831-3aa68080-1360-11ea-8335-7457af9f0e71.png)

**Comment by hexawing** [comment]
太厉害了！突然觉得记笔记的热情高涨起来了！！
