### ISSUE TITLE
建议增强发布功能(metaweblog,样式)

### ISSUE THREAD

**Issue by corminlu** [suziwen/markdownxiaoshujiang#120]
1. 现在需要从页面中找到RSD引用才能发布文章，有些自定义模板没有RSD引用标记，就没办法发布了，能否直接填metaweblog接口地址（比如wordpress的xmlrpc.php）
2. 发布是否可以增加选项，把css样式放在内容中一起发布出去（类似导出html的inlineStylesheet选项）。比如代码高亮的样式，有些博客模板没有自带代码高亮样式，发布后还需要自行在后台嵌入样式操作起来很麻烦。
3. 发现一个问题，在当前文件嵌入自定义css样式之后，发布并未把嵌入的样式一起发布出去。（导出才有这个样式）

**Comment by suziwen** [comment]
确认了下，当前文件的css也是有生效的。
现在系统发布时也是用的inlineStylesheet功能进行处理的。只是有些博客系统自己定义了全局css，影响了效果，这个得用户自己调整。
