### ISSUE TITLE
窗口最大话之后会改变页面布局

### ISSUE THREAD

**Issue by xiao7462** [suziwen/markdownxiaoshujiang#1200]
![image](https://user-images.githubusercontent.com/32445059/66883582-015cc000-f001-11e9-8ae8-fa882f78db0b.png)
最大话窗口本来是3个布局

但是一缩小，再放大， 就编程markdown的书写界面了， 每次都要重新弄 ，很麻烦

**Comment by suziwen** [comment]
感谢反馈，后面我再改进一下。

**Comment by suziwen** [comment]
最新版本已经进行了改进 。
