### ISSUE TITLE
win7 今天升级到v7.8.7 ctrl+s保存快捷键失效，自定义快捷键恢复正常

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1204]
v7.8.7  应该未定义默认的“保存”快捷键为ctrl+s吧。

需要用户自定义快捷键：
![image](https://user-images.githubusercontent.com/12257223/67214087-b8b66400-f451-11e9-9d70-b237e4f553a2.png)

**Comment by suziwen** [comment]
应该是ace 编辑器和竖排编辑器出的问题。

漏掉给这两个做兼容处理了。

下个版本补上，感谢反馈。
