### ISSUE TITLE
打开时桌面位置不正常。

### ISSUE THREAD

**Issue by theblack6688** [suziwen/markdownxiaoshujiang#1207]
打开后，总是在右下角位置，且显示 不全！！！
很难受啊！
原本以为是因为显示为125%造成的，
恢复默认100%，依旧如此！
望解决该问题！
![截图](pyl3y9obp.bkt.clouddn.com/xiaoshujiang/Snipaste_2019-10-22_22-18-45.png)

**Comment by theblack6688** [comment]
![截图](https://ae01.alicdn.com/kf/Hf03c94b028bf490ca6a41ef6f404a75b6.png)

**Comment by suziwen** [comment]
这个是多块屏幕引起的。

我这也有这情况，只是觉得并没有太多影响 ，也就一直没怎么在意。

不过我自己都是让它自动最大化，也就是显示加载 logo 时会在右下角，显示完后，就自动最大化到当前屏幕了。

后面再找个时间研究下如何解决。

**Comment by suziwen** [comment]
最新版本已经修复
