### ISSUE TITLE
7.8.8版本导出有图片的markdown不是压缩包，只有一个md文件

### ISSUE THREAD

**Issue by ygqygq2** [suziwen/markdownxiaoshujiang#1211]
7.8.8版本导出有图片的markdown不是压缩包，只有一个md文件。
以前的版本是有图片就是导出压缩包，里面有图片文件。

**Comment by suziwen** [comment]
导出 zip 就可以了。

导出 markdown， 不管有没有图片， 一直都是纯文本的。

**Comment by ygqygq2** [comment]
@suziwen 好的。
