### ISSUE TITLE
希望支持导出到HTML时，可以选择无样式导出。以及删除多余xsj_anchor

### ISSUE THREAD

**Issue by Felix-V587** [suziwen/markdownxiaoshujiang#1212]
导出到HTML时，有时候需要使用自定义的样式，这时就不需要在导出的HTML中带上小书匠自定义的“xsj_xxx”等class。
此外，xsj_anchor这个class下的内容我认为是没有必要的，可否选择导出时删除？

**Comment by suziwen** [comment]
这个感觉可以在导出后，对于有个性化需求的，比如自定义博客等，可以自己写个脚本专门处理 html 结构。小书匠目前只提供了是否对样式进行内联处理的选项。

小书匠这里的 html 导出，一般是满足普通需求，比如在预览区什么效果，导出的 html 就是什么效果。

而且由于  markdown 并没有严格要求生成的 html 是什么格式，不同的编辑器生成的 html 也不会是完全一致的。

---------


这个 anchor 主要是处理像 toc 定位用的。像有些标题名称是相同的，如果只是用这相同的名称来定位，永远只能定位到第一个标题名称。
