### ISSUE TITLE
希望支持导出到有道云笔记时以markdown格式保存

### ISSUE THREAD

**Issue by Felix-V587** [suziwen/markdownxiaoshujiang#1213]
目前保存到有道云笔记时，是以有道默认的笔记格式存储，希望能支持markdown格式

**Comment by suziwen** [comment]
这个是有道没提供api 支持，就算是保存成 markdown 内容，也只能是富文本格式的 markdown 文件，无法使用有道自己的 markdown 编辑器打开。
