### ISSUE TITLE
双向保存

### ISSUE THREAD

**Issue by aubreyzheng** [suziwen/markdownxiaoshujiang#1214]
可以在同步网站保存的同时，在本地也保存一份数据吗？
不然在不能联网的情况下，都无法查看文章。
在离线的情况下可以编辑，等联网后，自动同步。

**Comment by suziwen** [comment]
这个感觉不需要，小书匠客户端是一个离线优先的编辑器。完全可以在离线状态下编辑文件，等联网的时候，再保存到相应的第三方存储上。
