### ISSUE TITLE
chrome 78 暗黑模式下, 无法看到输入指针

### ISSUE THREAD

**Issue by Captain-Alan** [suziwen/markdownxiaoshujiang#1216]
如图, chrome 78 版的暗黑模式下, 输入时, 未见输入指示符, 也就是在输入框中输入的时候往往会出现的那个竖线「 | 」

![quicker_e7097c83-a413-429f-904d-8b75065bbd0d.png](https://i.loli.net/2019/10/26/3gP4fl1oFtYGCnI.png)

**Comment by suziwen** [comment]
这个后面再跟进调整。

**Comment by suziwen** [comment]
我这边今天升级了 chrome 到 78, 在 window 10 下切换成暗色模式，光标能正常显示的。
你小书匠内置编辑器的主题选择的是哪一个?

**Comment by Captain-Alan** [comment]
TextMate

**Comment by suziwen** [comment]
奇怪了，我 window 10 下 dark 模式里，看到的小书匠页面背景是白色的，你的怎么会是黑色的？你的 chrome 装了主题类的插件？

![image](https://user-images.githubusercontent.com/57370/68025251-4d894f00-fce7-11e9-917f-de3a42943e9d.png)


![image](https://user-images.githubusercontent.com/57370/68025428-a6f17e00-fce7-11e9-8a99-67c682051396.png)

**Comment by suziwen** [comment]
或者自己直接进行编辑器自定义样式 **小书匠主按钮>设置>基本>全局自定义样式**

```
.CodeMirror-cursor.ace_cursor{
border-left-color: red;!important
}
```

![image](https://user-images.githubusercontent.com/57370/68026862-da360c00-fceb-11e9-8b1e-163dd18f6b27.png)

**Comment by Captain-Alan** [comment]
通过 chrome://flags 将 Force Dark Mode for Web Contents 设为 Enable

**Comment by suziwen** [comment]
> 或者自己直接进行编辑器自定义样式 **小书匠主按钮>设置>基本>全局自定义样式**
> 
> ```
> .CodeMirror-cursor.ace_cursor{
> border-left-color: red;!important
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/57370/68026862-da360c00-fceb-11e9-8b1e-163dd18f6b27.png)

这个感觉是 chrome 没有把 border-left-color 做颜色反转处理的问题，跟小书匠这边关系不大了。

因为 chrome 没有任何通知提供是否进入这种类型的 dark mode , 对于小书匠是完全无法感知的，所以小书匠这边就暂时不做更改了。你可以通过上面提供的自定义全局方法，单独对光标样式进行处理。
