### ISSUE TITLE
小书匠已开启vim, 在chrome中, 使用Esc建, 无法进入命令模式

### ISSUE THREAD

**Issue by Captain-Alan** [suziwen/markdownxiaoshujiang#1217]
如题, 小书匠已开启vim, 在chrome中, 使用Esc建, 无法进入命令模式

**Comment by suziwen** [comment]
我这可以正常在 "命令模式"， "输入模式" 和“底线命令模式” 里正常切换， <kbd>Esc</kbd> 键也可以正常工作。

是不是你浏览器其他插件的按键冲突了？

**Comment by Captain-Alan** [comment]
的确, 检查发现是Vimium插件导致案件冲突了, 将http://markdown.xiaoshujiang.com/ 添加到exlude list就正常了

**Comment by andi2233i** [comment]
> 的确, 检查发现是Vimium插件导致案件冲突了, 将http://markdown.xiaoshujiang.com/ 添加到exlude list就正常了

感谢
