### ISSUE TITLE
不是有效的单个文件网页

### ISSUE THREAD

**Issue by PterX** [suziwen/markdownxiaoshujiang#122]
### 系统环境
* linux x64
* 小书匠最新版1.8

我使用导出功能导出的word文档打不开。
提示不是有效的单个文件网页。
![20160119174228](https://cloud.githubusercontent.com/assets/1871048/12414982/0aaa3636-bed4-11e5-8914-de90045f66d6.png)

**Comment by suziwen** [comment]
导出的word功能有限，最好是window下的word打开，wine 打开的word没测试过。
