### ISSUE TITLE
win7 v7.8.8 导出1.33M的md文件为pdf失败,但导出<100k的正常。

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1220]
导出几十k的文件为pdf正常，但导出1.33M的文件为pdf时，出现以下错误(未说明详细原因)：

![image](https://user-images.githubusercontent.com/12257223/67926700-a4acf800-fbf1-11e9-8704-66446fd9f7ee.png)

导出pdf时的选项（我是付费用户，也联网了）：
![image](https://user-images.githubusercontent.com/12257223/67926890-2f8df280-fbf2-11e9-9387-95d7355ab743.png)

但将1.33M的md文件导出为html时，确是正常的。

**请问是否对导出为pdf的markdown文件的大小有限制。**

**Comment by suziwen** [comment]
这个大小目前最大可以 50M ，你那边出错应该是导出的 markdown 文件里可能有未考虑到的 bug。 如果可以的话，把那个文章导出成 小书匠 zip 格式，发到我的邮箱  suziwen1@gmail.com 上， 我这边排查一下。或者你自己也可以使用二等分法，把 markdonw 文字删除一部份，再导出，直到导出成功为止，找出导出失败的原因。

**Comment by juejian** [comment]
导出本地pdf成功，只不过样式有点丑。在线导出pdf失败，可能是我合并后文章中引用的图片太多。我再试下.

**Comment by juejian** [comment]
确认原因：文章中引用的图片太多（约600）。 文章分割为2个文件，导出成功。
