### ISSUE TITLE
小书匠(v7.9.0) 同步 markdown 到印象笔记(v6.20) 内容是 null

### ISSUE THREAD

**Issue by ghy-git** [suziwen/markdownxiaoshujiang#1221]
![image](https://user-images.githubusercontent.com/25817063/67970737-71e11f00-fc46-11e9-891b-acf8b37de3f2.png)

**Comment by suziwen** [comment]
刚测试了下，我这边能正常保存的。

你看一下印象笔记 web 版本是否也没有内容了？再一个是不是自定义了样式，或者试一下比较简单的 markdown 文章保存到印象笔记，看能不能成功？

![image](https://user-images.githubusercontent.com/57370/67993166-9b1ba280-fc7a-11e9-9edf-79831aef6a83.png)

**Comment by ghy-git** [comment]
刚才试了下，新建然后另存为 还是不行

小书匠
![image](https://user-images.githubusercontent.com/25817063/68004644-3cbbe780-fcad-11e9-95f1-7d4250dd2993.png)


印象笔记 web
![image](https://user-images.githubusercontent.com/25817063/68004613-20b84600-fcad-11e9-85ba-0fd906c82f21.png)

印象笔记客户端
![image](https://user-images.githubusercontent.com/25817063/68004628-2e6dcb80-fcad-11e9-9f1f-57a8de5408c2.png)

**Comment by ghy-git** [comment]
没有自定义样式，卸载了重装还是不行
对了 麻烦问下 你们 v6.20 版本的印象笔记有 markdown 功能吗？

**Comment by suziwen** [comment]
可以参考下这几个，看能不能解决。

#1187

#883

小书匠的安装路径里有中文？或者换成小书匠 32 位版本呢？

**Comment by suziwen** [comment]
> 没有自定义样式，卸载了重装还是不行
> 对了 麻烦问下 你们 v6.20 版本的印象笔记有 markdown 功能吗？

小书匠保存到印象笔记都是转换成 富文本格式的。

**Comment by ghy-git** [comment]
路径中有中文，修改成英文之后就解决了
但是因为之前卸载小书匠和印象笔记，搞得文章插图丢失了T_T
不过问题解决了 还是不错的 阿里嘎多
