### ISSUE TITLE
不经意发现收费翻倍了？

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1222]
那么以前交的两年的折算成一年了吗？还是以后交的才折算？

另外前端的更新日志没有日期的吗？想翻翻是哪天更新的死活没找到，到github上才看到。

**Comment by suziwen** [comment]
http://soft.xiaoshujiang.com/blog/price_change_plan

以前交的不变。比如 以前交40 的，不会折算成一年，还是两年。

新付费的调整了。

**Comment by suziwen** [comment]
点击页面右侧的修改文件, 里面有更新日期的元数据。后面我在修改下，把这个显示到升级日志页面上

![image](https://user-images.githubusercontent.com/57370/67999394-1b500100-fc97-11e9-9152-f07650a72f3f.png)

![image](https://user-images.githubusercontent.com/57370/67999436-4c303600-fc97-11e9-8770-e457aaef04a9.png)
