### ISSUE TITLE
win7 x64 升级到v7.9.0, ACE编辑器部分快捷键命令失效：selecttolineend、selecttolinestart,selecttoend,selecttostart

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1223]
如上。无论定义那个快捷键，这4个命令都不生效。但在v7.8.8中是可用的.

**Comment by suziwen** [comment]
我这边 7.9.0 版本下，测试了 `selecttolineend` 没有问题，能贴一下你是怎么设置快捷键的吗？

![image](https://user-images.githubusercontent.com/57370/68024430-1023c200-fce5-11e9-8159-bc3af1aab16c.png)

**Comment by juejian** [comment]
将本地 `AppData\Local\storywriter` 中所有文件删除，重启客户端正常了，问题无法重现了。

可能是v7.8.8残留的配置文件和v7.9.0有所冲突吧。
