### ISSUE TITLE
请问github图床的默认连接怎么改变了？

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1227]
**前缀变化有什么影响吗*？

**Comment by suziwen** [comment]
是的，将原来的 `https://www.github.com/{username}/{reponame}/{branch}/` 改成了 `https://raw.githubusercontent.com/{username}/{reponame}/{branch}/`

`https://www.github.com` 有跨域访问的限制，而 `https://raw.githubusercontent.com` 没有， 所以小书匠默认就改成后者了。你也可以自己自定义前缀，重新改成前者。

对于访问的话，只要 github 不改域名，基本是没有影响的。两个地址都是 github 官方的，而且访问资源情形下，使用前者的地址，最后还是会被 github 重定向到后者的地址上来。
