### ISSUE TITLE
配置文件导出（换浏览器）导入，并未能完整复制配置

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1230]
比如上次您教的修改plantuml服务的路径，就未能导入。
当然我知道，这个可能是要存的东西实在太多了，我也就是随便一说，改不改得了都随您。

**Comment by suziwen** [comment]
这个我测试了一下，没有出现你说的情况，  plantuml 里的设置也是能正常导入的。你看一下你导出的配置文件里是否包含 这个 `"grammar_plantuml_options_url":"http://www.plantuml.com/plantuml/svg/{{uml}}"`

![image](https://user-images.githubusercontent.com/57370/68476486-be8bb200-0265-11ea-84de-5137288ed0d1.png)


----------

同步范围要把`预览` 选项选中，这个是控制渲染效果的，包括扩展语法设置的选项。

![image](https://user-images.githubusercontent.com/57370/68476589-0ca0b580-0266-11ea-9894-e8e78366906f.png)

**Comment by hexawing** [comment]
又换了个浏览器，不仅这个成功了，连云存储那些也成功了，太棒！
