### ISSUE TITLE
关于全局自定义样式和预览区自定义样式

### ISSUE THREAD

**Issue by lvhaoyu** [suziwen/markdownxiaoshujiang#1232]
请问全局自定义样式的作用在哪呢？我想修改导出到印象笔记的标题和字体样式，在全局自定义写了样式但是没有作用，只有在预览区写样式才有效果，那么全局自定义样式的意义在哪呢？

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/68590982-b1233180-04ca-11ea-928a-7b75eb535107.png)
**设置>基本>全局自定义样式 **里是控制整个小书匠应用的样式，但不包括预览生成的样式。


![image](https://user-images.githubusercontent.com/57370/68591114-f182af80-04ca-11ea-8640-96691f8d7f5e.png)

**设置>预览>预览区自定义样式**里控制的是所有预览区共用的样式（每篇文章都会应用该样式），不会影响小书匠系统本身。


![image](https://user-images.githubusercontent.com/57370/68591220-2858c580-04cb-11ea-8938-9b1b68290878.png)


每篇文章预览区右边里的 **自定义样式** ， 控制的是当前文章想要生成的样式，不会影响到其他文章预览生成的样式。



----------------------


全局样式是留给想要修改小书匠系统的样式，像有些用户在选择了一个小书匠主题后，觉得某个颜色不喜欢，自己可以在这里改掉，比如这样的需求 https://github.com/suziwen/markdownxiaoshujiang/issues/1228#issuecomment-551036620 或者这样的需求 https://github.com/suziwen/markdownxiaoshujiang/issues/1216#issuecomment-548782080

**Comment by lvhaoyu** [comment]
好的 明白了 感谢回复。
