### ISSUE TITLE
中文引号被当做半角符号

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#1233]
中文引号 “” 被当做半角符号，导致光标显示异常，并在第二行造成文字重叠。

![image](https://user-images.githubusercontent.com/20160766/68745671-104f8600-0632-11ea-825a-f26844c705f4.png)

如图所示，光标应在 “ 之后，显示却在 “ 中间，第二行首字重叠。

**Comment by suziwen** [comment]
内置编辑器是 `CodeMirror`?

![image](https://user-images.githubusercontent.com/57370/68818524-36bc0280-06c0-11ea-8e22-34b179be1e05.png)

**Comment by jianzs** [comment]
Ace 编辑器

**Comment by suziwen** [comment]
Ace 编辑器的话，要设置成等宽字体， `设置>编辑器>编辑器字体`  [等宽字体](https://zh.wikipedia.org/wiki/%E7%AD%89%E5%AE%BD%E5%AD%97%E4%BD%93)

**Comment by jianzs** [comment]
了解，谢谢。
