### ISSUE TITLE
启动一直转圈, 所以卸载,卸载后之前写的文档默认存储在哪里,没有另存为,没有使用第三方存储

### ISSUE THREAD

**Issue by fIappy** [suziwen/markdownxiaoshujiang#1235]
如题

**Comment by fIappy** [comment]
最新版的还出打不开转圈的bug,重装软件,重启系统都没用,关键是之前写的文档也找不到了,不解决这些问题请不要在坑用户了谢谢

**Comment by suziwen** [comment]
可以用其他编辑器创建一个新的扩展名为 md 的空白文本文件，然后右键用小书匠打开。

如果还是打不开的话，可以把数据库文件夹压缩一下，发到我的邮箱 suziwen1@gmail.com ，我看一下什么原因造成的。

--------------


数据库文件路径
```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```
------------

小书匠是一个离线优先的软件，意味着所有的数据都是保存在本地的数据库里。

如果想把小书匠当成一个笔记管理的软件，建议对小书匠的[数据库](http://soft.xiaoshujiang.com/docs/tutorial/database/)有一些了解，因为所有存在本地的文件都会有被其他应用(像垃圾文件清理 ，或者病毒等)干扰破坏掉的风险。

如果只是想把小书匠当成编辑器来使用，建议及时保存文件到自己信任的位置，比如本地的指定文件夹或者其他第三方存储。
