### ISSUE TITLE
sm.ms v2无法绑定token

### ISSUE THREAD

**Issue by kabeor** [suziwen/markdownxiaoshujiang#1236]
![image](https://user-images.githubusercontent.com/34511237/69144880-4fd11300-0b07-11ea-8367-f138395ac784.png)

点击绑定按钮，验证图片成功上传，但应用返回上传失败报错

![image](https://user-images.githubusercontent.com/34511237/69144956-7db65780-0b07-11ea-95f3-d7feda8c6fbe.png)

**Comment by suziwen** [comment]
嗯，我今天也看到了，应该是 smms 的 api 返回的数据信息修改了，以前可以直接返回 json 的，现在是一串字符串 ，需要自己转换成 json 对像。

可以暂时使用 #1219  提供的自定义图床版本。

在 [14 行里](https://gist.github.com/jackytsu/70b00dbc300eca0c67fedd47646ce18e#file-sm-ms_v2-js-L14) 添加自己生成的 token.

**Comment by kabeor** [comment]
提供的方法测试成功，感谢
