### ISSUE TITLE
为什么很对语法在新建的页面渲染不出来呢？

### ISSUE THREAD

**Issue by lhjmemory** [suziwen/markdownxiaoshujiang#1237]
为什么很多语法在新建的页面渲染不出来呢，比如甘特图、流程图，比如高级表格等。在语法说明里面可以渲染，在新建的页面却不行。

**Comment by suziwen** [comment]
这个有语法开关的，有些语法是默认关闭的，可以在 `设置>扩展语法` 里进行全局控制，也可以通过每篇文章的元数据进行打开或者关闭。

语法说明里就是通过元数据把想要使用的语法打开的。

比如 [mermaid](http://soft.xiaoshujiang.com/docs/grammar/feature/mermaid/) 的元数据就是 `grammar_mermaid`
