### ISSUE TITLE
小书匠功能栏全部消失

### ISSUE THREAD

**Issue by highgetup** [suziwen/markdownxiaoshujiang#1239]
mac 版本 10.14.6，小书匠版本 7.8.0，升级到 7.9.1 也出现同样问题，目前版本 7.9.2（使用中，暂未出现问题）
问题描述如下：
1.使用一段时间后，打开小书匠，发现功能栏全部丢失，随着不管的拉伸小书匠边框的大小，部分功能栏才随之出现，怀疑可能是接了外接屏的问题，不使用外接屏幕时恢复导致未兼容？以下是异常图片。
![image](https://user-images.githubusercontent.com/16283113/69495712-f9981180-0f04-11ea-81be-69f2a999ce50.png)
![image](https://user-images.githubusercontent.com/16283113/69495717-ff8df280-0f04-11ea-9410-1b39b76d5d8c.png)
![image](https://user-images.githubusercontent.com/16283113/69495718-0288e300-0f05-11ea-9286-c3217d8467e8.png)

**Comment by suziwen** [comment]
用鼠标点击一下标题栏，然后按快捷键 <kbd>ctrl+⇧</kbd> 呢

**Comment by highgetup** [comment]
等我这个版本使用一段时间后看能不能复现，复现我操作下试试。

**Comment by highgetup** [comment]
等我这个版本使用一段时间后看能不能复现，复现后我操作下试试。
