### ISSUE TITLE
英文"."无法被转义

### ISSUE THREAD

**Issue by corminlu** [suziwen/markdownxiaoshujiang#124]
ABC测试\\.NET
ABC测试\\.COM

在启用grammar_linkify情况下，以上两种格式均无法转义，"\"+"."还是会出现链接

**Comment by suziwen** [comment]
linkify 功能是在转义之后对文本操作，所以 ` ABC测试\.COM` 这些文字会在转义成 `ABC测试.COM` 然后进行文字是否需要链接的判断。
