### ISSUE TITLE
小书匠无法登陆

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#1240]
主题：小书匠客户端突然无法登陆
window版本：Windows 10专业工作站版 ，版本号1909
相关措施：1、重启客户端 2、重新安装 
当前结果：经过相关措施后仍无法登陆进去。

![image](https://user-images.githubusercontent.com/15724559/69507456-8f678700-0f6d-11ea-95a0-c1ca1190c384.png)

**Comment by ghost** [comment]
一直在登陆转圈圈

**Comment by ghost** [comment]
采用作者以往提供给其他用户的建议仍无效。
------------------------------------作者以往的建议如下--------------------------------------
用其他编辑器创建一个扩展名为 md 的文件，然后右键，打开方式选择小书匠编辑器打开
或者
清空数据目录（重要数据建议备份下），再启动。

Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter

**Comment by ghost** [comment]
Windows: %LOCALAPPDATA%/storywriter/
--找不到以上目录

**Comment by suziwen** [comment]
清空数据目录也启动不了？

**Comment by ghost** [comment]
启动不了  我都重装了 还是不行

**Comment by ghost** [comment]
> 清空数据目录也启动不了？

不行  还在转圈 进不去

**Comment by suziwen** [comment]
`%LOCALAPPDATA%` 这个是系统变量，根据你系统的设置指定的数据位置

**Comment by ghost** [comment]
> `%LOCALAPPDATA%` 这个是系统变量，根据你系统的设置指定的数据位置

重装后 我在我的安装位置找不到这个数据位置，是下面哪个目录 麻烦看一下 
![image](https://user-images.githubusercontent.com/15724559/69508147-d0609b00-0f6f-11ea-936c-7e19b955f97c.png)

**Comment by fanstoyou** [comment]
> `%LOCALAPPDATA%` 这个是系统变量，根据你系统的设置指定的数据位置

重装后 我在我的安装位置找不到这个数据位置，是下面哪个目录 麻烦看一下 
  @@![image](https://user-images.githubusercontent.com/15724559/69508147-d0609b00-0f6f-11ea-936c-7e19b955f97c.png)

**Comment by suziwen** [comment]
不是安装位置
是系统数据目录位置 

类似这个

```
C:\Users\Administrator.WIN7-1607010007\AppData\Local\storywriter
```

**Comment by suziwen** [comment]
数据保存位置和安装位置不一样的。

**Comment by suziwen** [comment]
也可以自己在启动时，加参数，把数据目录指定到其他位置 ，比如

```
Story-writer.exe --user-data-dir=d:/xxx
```

**Comment by suziwen** [comment]
如果可以的话，把数据目录压缩一下，发到我邮箱 suziwen1@gmail.com , 我看一下具体是什么原因造成的。

**Comment by ghost** [comment]
@suziwen 变更数据目录已解决，多谢作者大大。
--初次使用，请多多关照！

**Comment by ghost** [comment]
> 如果可以的话，把数据目录压缩一下，发到我邮箱 [suziwen1@gmail.com](mailto:suziwen1@gmail.com) , 我看一下具体是什么原因造成的。

数据文件已发邮箱

**Comment by suziwen** [comment]
邮件收到了，但里面好像找不到任何附件，换个邮件客户端发送，或者其他邮箱发呢？

**Comment by ghost** [comment]
> 邮件收到了，但里面好像找不到任何附件，换个邮件客户端发送，或者其他邮箱发呢？
整个是我重装后，还是无法登录的数据目录，也就是默认生成的。因此这个问题可能无法复现。假如下次还有这种情况的时候，我先备份数据目录下来发你邮箱。

**Comment by suziwen** [comment]
好的
