### ISSUE TITLE
分类器逻辑

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1241]
新出的分类器对于工作和生活都用的我来说非常好用，目前遇到一个问题，说明中说的分类是等于关系，但是对于分类的，既然支持子分类，那么是不是父分类是包含关系呢？

举例：
我有两个分类：
工作\周报
工作\项目

我搜索：
工作

应该上面两者都出现的才对吧，目前好像是都搜索不到。

另外，网页版的好像不支持 博客发布？
对于自己而言，由于我喜欢放大操作，桌面版无法缩放，网页版无法发布博客，有点两难。
多平台发布，有考虑吗？
比如operwrite、最近新出的：ArtiPub (Article Publisher https://blog.csdn.net/tikazyq/article/details/101099940），开源的能融合下就好了 。

**Comment by suziwen** [comment]
分类过滤器有打算做成 起始于关系，也就是类似 javascript 里的 startswith 。现在还是等于关系，所有搜索不到。

网页版不提供发布博客功能，客户端版专有。

多平台发布的话，还需要再研究下。要做的话，优先级也会很低。

**Comment by suziwen** [comment]
分类过滤器加了个**起始于关系**， 可以这里查看[说明](http://soft.xiaoshujiang.com/docs/tutorial/filter/#e58886e7b1bbe8bf87e6bba4e599a8e4b88e20category20e580bce585b3e7b3bb_6)

**Comment by CharMingF** [comment]
> 分类过滤器加了个**起始于关系**， 可以这里查看[说明](http://soft.xiaoshujiang.com/docs/tutorial/filter/#e58886e7b1bbe8bf87e6bba4e599a8e4b88e20category20e580bce585b3e7b3bb_6)
谢谢提醒，我是死忠粉，早就看到更新了
