### ISSUE TITLE
同样的配置，在Chrome里可以以粘贴的形式上传图片到七牛云，在Firefox里就报错

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1242]
配置文件是从Chrome导出然后导入到Firefox里的，电脑是同一台电脑。

![报错](https://user-images.githubusercontent.com/230037/69612035-e9e60d80-1069-11ea-9863-88dea60f03d1.png)

而且，也无法通过“修改”的方式来查看我的token到底是否正确。

**Comment by suziwen** [comment]
如果同一个配置文件的话，在 chrome 下可以，在 firefox 下失败，那应该是 firefox 下的 bug.

你也可以试试在 firefox 下重新绑定七牛。

暂时不打算提供绑定的修改界面了，一般绑定完，很少需要再修改，真万一要修改，删除以前的，直接重新创建一个就可以了。


我这边现在 firefox 很少测试了，一般都是测试最新的两个 chrome 版本，和小书匠客户端对应的 chrome 版本。有时间再慢慢跟进这块。

**Comment by hexawing** [comment]
好的。我下载一个客户端试试。

**Comment by hexawing** [comment]
客户端倒是可以正常使用七牛了，但绑定为知笔记又失败。
客户端版本7.9.2
操作系统Win7 64位
绑定时一直提示：
`{"code":1009,"error":"服务器错误","orign":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}}`
哪怕我故意输入错用户名，也提示这个。

web端绑定的时候，输入错误的用户名会提示用户名不存在。
`{"code":1009,"error":"服务器错误","orign":{"returnCode":31001,"returnMessage":"user is not exist: userId = hexawing","externCode":"","code":31001,"return_code":31001,"return_message":"user is not exist: userId = hexawing"}}`
web端输入正确的用户名密码后可以正常绑定。

**Comment by suziwen** [comment]
我新注册了一个 wiz 帐号 

```
username:  test99@test99.com
password: test99
```

在客户端上绑定是可以正常使用的，没有出现你说的错误。

![image](https://user-images.githubusercontent.com/57370/69689750-b86e5000-1104-11ea-884e-06e3c9f89216.png)


----------------

感觉跟你的网络环境或者系统限制有关。

web 版本绑定为知的话，需要走小书匠服务器中转，而客户端版本绑定为知的话是直接连接。

**Comment by suziwen** [comment]
网上搜索了下这个关键词 `UNABLE_TO_VERIFY_LEAF_SIGNATURE`，好像还是网络问题比较大。使用了代理 ？

**Comment by hexawing** [comment]
@suziwen 感谢回复。
我个人并没有使用代理，但是是在公司使用，不清楚公司是否额外限定了什么。
我自己试了一下科学上网，也还是不行。
用你的那个账号密码也不行。
然后我又开了手机的热点，还是不行……
你用的是“为知笔记”还是“为知笔记V2”啊？（反正我都试了，都不行，哭）

**Comment by suziwen** [comment]
为知笔记V2

**Comment by hexawing** [comment]
用奇怪的方式解决了Firefox的问题：
用http没有s访问
客户端还是先不用了。逃避可耻但有效。
