### ISSUE TITLE
新建文件怎么改名？右键修改属性存在严重BUG

### ISSUE THREAD

**Issue by shadowfish07** [suziwen/markdownxiaoshujiang#1243]
我右键一个新建的文件，修改属性，改变了标题栏的值，保存，取消后可以看到文件名变了，但是此时其他文件都点不开，也无法保存文件，退出程序后重新打开，发现文件名字仍然没变！最要命的是修改属性后文件无法保存，让我失去了半小时的进度!

**Comment by suziwen** [comment]
非常抱歉，确认 bug。

一会会再发布个新版本修复这个问题。

**Comment by suziwen** [comment]
好了，更新到 `7.9.4`

**Comment by shadowfish07** [comment]
反应很快啊~蟹蟹作者啦
