### ISSUE TITLE
请问这个slug能有多个吗？

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1245]
A笔记的元数据里写
`slug: word1, word2`
B笔记里写
`[link](word1)`，引用不到的样子。
请问是不支持这种多slug，还是我的用法不对啊？

**Comment by suziwen** [comment]
不支持多个的

**Comment by hexawing** [comment]
好吧，我再摸索一下这个的应用场景。顺便说一下，这个箭头真是太漂亮了。
