### ISSUE TITLE
既然已经有关联图了，那接下来会不会考虑「按标签关联」的特性呢？

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1246]
比如一种是按slug的连线，一种是按tag的连线？
如果担心网铺得太大了可以设置只显示两三层。
我是不是太贪心了……:flushed:

**Comment by suziwen** [comment]
tag 应该只是过滤出相关的文件，没有关联这个使用场景，估计不会考虑。

**Comment by hexawing** [comment]
有相同tag的文章，也说明思维上有一定的延续性啊。
好吧，没有就算了 :crying_cat_face:

**Comment by suziwen** [comment]
主要是有些时候，同一个标签下会有很多文件，如果展示出来的话，整个图就会感觉很乱。我这边尝试实现一下，看看具体效果如何。

**Comment by hexawing** [comment]
@suziwen 您真是开发者的典范！:+1: :+1: :+1:

**Comment by suziwen** [comment]
7.9.5 添加了标签关系显示，双击标签结点时，会自动在文章列表里使用标签过滤器过滤出相应的标签文章。

**Comment by hexawing** [comment]
太赞了！:+1::+1::+1:
