### ISSUE TITLE
win10 系统更新7.9.5版本后打不开

### ISSUE THREAD

**Issue by gaoyp27** [suziwen/markdownxiaoshujiang#1250]
win10 系统更新7.9.5版本后打不开，已卸载重装了一样打不开！

**Comment by suziwen** [comment]
可以用其他编辑器创建一个新的扩展名为 md 的空白文本文件，然后右键关联用小书匠打开， 或者用命令行 `Story-writer.exe --file=d:/xxx.md`。

如果还是打不开的话，可以把数据库文件夹暂时先移走，再启动小书匠


数据库文件路径
```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```

也可以自己在启动时，加参数，把数据目录指定到其他位置 ，比如


```
Story-writer.exe --user-data-dir=d:/xxx
```

--------------

如果想恢复旧的数据目录，需要把数据目录压缩一下，发到我的邮箱 suziwen1@gmail.com ，我看一下什么原因造成的。

**Comment by gaoyp27** [comment]
移走数据文件已解决，文件在git上有备份！谢谢！
