### ISSUE TITLE
写latex代码的时候，高亮出现问题

### ISSUE THREAD

**Issue by xfdywy** [suziwen/markdownxiaoshujiang#1251]
latex代码中的某些符号会导致高亮不正确。不过只影响markdown编辑区的高亮，不影响最后的显示效果。
比如下面三个图，前两个是编辑器，可以看到上标符号 ^ 和下标符号 _ 都会影响高亮。最后一个是显示图，可以看到是正常的 

![image](https://user-images.githubusercontent.com/6959554/70432169-90460000-1ab9-11ea-9af2-575a9568f1b3.png)
![image](https://user-images.githubusercontent.com/6959554/70432176-976d0e00-1ab9-11ea-9bc3-e29aceeb1065.png)

![image](https://user-images.githubusercontent.com/6959554/70432232-be2b4480-1ab9-11ea-8d91-9a24aed6fc4b.png)

**Comment by suziwen** [comment]
感谢反馈，后面会改进高亮显示这一块。
