### ISSUE TITLE
请问最近怎么不能预览github图床的图片了？

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1255]
不论是www.github.com 还是新的那个域名？只是右边的窗口没法预览，编辑框鼠标点击“编辑图片”指针可以编辑。

**Comment by suziwen** [comment]
我这里没有问题，是不是你那边的网络问题？

```
![enter description here](https://raw.githubusercontent.com/suziwen/tt/master/小书匠/1576637480908.png)
```

![image](https://user-images.githubusercontent.com/57370/71051882-98223600-2184-11ea-8e05-df1a493fa2bc.png)

**Comment by liao20081228** [comment]
> 我这里没有问题，是不是你那边的网络问题？
> 
> ```
> ![enter description here](https://raw.githubusercontent.com/suziwen/tt/master/小书匠/1576637480908.png)
> ```
> 
> ![image](https://user-images.githubusercontent.com/57370/71051882-98223600-2184-11ea-8e05-df1a493fa2bc.png)

是的网络问题，我路由器开了梯子。但是有梯子为什么会出现这种情况

**Comment by suziwen** [comment]
这个不太清楚了，可能跟你网络访问策略的具体设置有关，比如限制了某些应用，某些端口的访问。
