### ISSUE TITLE
七牛云图床上的图片只有在小书匠客户端才能看

### ISSUE THREAD

**Issue by G233** [suziwen/markdownxiaoshujiang#1256]
复制链接到浏览器里面都看不到，显示如下：
```
{
error: "no such domain"
}
```

**Comment by suziwen** [comment]
这个好像是七牛不再提供测试域名显示引起的问题，解决方法就是需要自己添加使用自己的域名，然后在小书匠绑定图床时，定义一下图片 url 前缀到自己的域名上。

https://developer.qiniu.com/kodo/kb/5443/no-to-domain-related-issues

![image](https://user-images.githubusercontent.com/57370/71361960-8ea72c80-25cf-11ea-966b-52ca9c393765.png)

**Comment by G233** [comment]
好的，我试试，谢谢了
