### ISSUE TITLE
希望提供可以随时关闭预览窗口功能

### ISSUE THREAD

**Issue by smilelandchr** [suziwen/markdownxiaoshujiang#1257]
目前研究可以用悬浮预览窗口代替，但不是完整的解决方案，因为有时候编辑latex公式后，怕错误就想看一眼，但写文字时右侧总是渲染却非常的讨人厌，尤其是插入的图片的刷新，很晃眼睛。

**Comment by suziwen** [comment]
可以使用 `ctrl+shift+p` 快捷键快速关闭或者打开预览。

也可以通过`preview` [命令](http://soft.xiaoshujiang.com/docs/tutorial/commands/#preview_6)自定义快捷键 来实现这个功能

![image](https://user-images.githubusercontent.com/57370/71439779-d647c880-2735-11ea-8c96-337de1991105.png)

**Comment by smilelandchr** [comment]
> 可以使用 `ctrl+shift+p` 快捷键快速关闭或者打开预览。
> 
> 也可以通过`preview` [命令](http://soft.xiaoshujiang.com/docs/tutorial/commands/#preview_6)自定义快捷键 来实现这个功能
> 
> ![image](https://user-images.githubusercontent.com/57370/71439779-d647c880-2735-11ea-8c96-337de1991105.png)

非常感谢！
