### ISSUE TITLE
希望文章可以分类，侧边栏可以拖动文章到不同的分类目录

### ISSUE THREAD

**Issue by Yuki-J1** [suziwen/markdownxiaoshujiang#1258]
如题

**Comment by suziwen** [comment]
web 版本提供[过滤器](http://soft.xiaoshujiang.com/docs/tutorial/filter/)功能，然后可以通过按 <kbd>ctrl</kbd> 键,选择多个文件，批量修改属性，来达到类似 **拖动文章到不同分类目录** 的效果

**Comment by Yuki-J1** [comment]
请问电脑客户端会出，类似功能吗？

**Comment by suziwen** [comment]
这个功能将来打算做为会员功能，免费用户的话，只能在 web 版本使用。

**Comment by Yuki-J1** [comment]
![2020-01-05_202507](https://user-images.githubusercontent.com/41263770/71780110-74bb1000-2ff9-11ea-82c1-bbba8e6058fc.png)
这个过滤器功能免费用户没有吧

**Comment by suziwen** [comment]
web 版，免费和付费用户都可以用，客户端版，将来只对付费用户开放。

**Comment by Yuki-J1** [comment]
明白了，谢谢解答。
