### ISSUE TITLE
有方法设置一个回车就是一个段落吗

### ISSUE THREAD

**Issue by leon0625** [suziwen/markdownxiaoshujiang#1259]
在小书匠里面，两个回车（有一个空行隔开）才算一个段落结束。

我主要是想使用这个css功能：段落开始前空两个字符。我想出来如下这样的效果

输入如下内容
```
今天是开心的一天。
天气非常好。
```
如果设置xsj_paragraph_level_0段落前空两个字符
预览出来这个效果
```
　　今天是开心的一天。
天气非常好。
```
**我希望是这个效果**
```
　　今天是开心的一天。
　　天气非常好。
```
有办法实现吗？

**Comment by suziwen** [comment]
这个是 markdown 语法要求这样，两个段落之间需要空一行。

没有空行分开的文字，都当成一个段落来处理的。
