### ISSUE TITLE
v7.8 osx版本提示已损坏

### ISSUE THREAD

**Issue by ygqygq2** [suziwen/markdownxiaoshujiang#1261]
v7.9.0 osx版本提示已损坏

![image](https://user-images.githubusercontent.com/17672440/71762572-b8cfe700-2f0b-11ea-83b7-02b22d0ee6c1.png)

![image](https://user-images.githubusercontent.com/17672440/71762575-c2594f00-2f0b-11ea-95e7-afe613e0868f.png)

**Comment by suziwen** [comment]
对比下 MD5 值，如果不一致的话，说明你下载的文件不完整，需要重新下载。

**Comment by ygqygq2** [comment]
对比了，就是那个md5，不行。是7.8，就是你最新那个。

**Comment by suziwen** [comment]
如果是从 gitee 下载的话，需要把三个 压缩文件都下载下来，然后合并成一个压缩文件(下载说明.txt 文件里有说明如何合并压缩文件)

```
 Story-writer-osx64.zip
 Story-writer-osx64.z02
 Story-writer-osx64.z01
```

如果是从 github 下载的话，如果文件和 md5 值都一致的话，应该都能打开的，至少我这边没有问题，也没有其他用户反馈你说的类似情形。

**Comment by ygqygq2** [comment]
我2个都试了，都是一样的。就这里github下的。可以的话，给另外方式发个给我吗？
ygqygq2@qq.com

**Comment by suziwen** [comment]
如果  md5 值一致的话，就不是打包文件的问题，再发一个估计也是一样的效果。可能跟操作系统或者其他外部因素关系比较大了。或者看看有没有其他用户也反映这种情况，然后提供一种问题重现的方法 。

**Comment by ygqygq2** [comment]
![image](https://user-images.githubusercontent.com/17672440/71768712-d5900d00-2f53-11ea-83a4-60ccada825fd.png)
我系统版本比较新，10.15.2

**Comment by suziwen** [comment]
你试着下载 nwjs 这两个文件，看能不能打开

https://dl.nwjs.io/v0.36.2/nwjs-v0.36.2-osx-x64.zip

https://dl.nwjs.io/v0.43.3/nwjs-v0.43.3-osx-x64.zip
