### ISSUE TITLE
Bug反馈：创建新的绘图 

### ISSUE THREAD

**Issue by dsclub** [suziwen/markdownxiaoshujiang#1262]
在绘图窗口中，存在以下小问题：

1. **帮助**菜单下的各项命令打开的窗口页面都**无法关闭**，目前只能<kbd>Alt+F4</kbd>
2. **鼠标**悬停在已绘制好的图形连接箭头提示内容最后括号内应该是Ctrl而不是xtrl。
3. **快速视频入门**连接的是*YouTube*，这个有点儿尴尬。

感谢苏大的作品，这个功能实在太棒了，不用上*ProcessOn*了。

**Comment by suziwen** [comment]
感谢反馈

帮助菜单下面的内容都是直接拿到 drawio 官方的，没怎么修改过，相关的视频也是 drawio 官方自己的 youtube,所以也就没有改了。

错别字和打开新窗口这个后面版本会改过来。

**Comment by dsclub** [comment]
太喜欢苏大的更新速度了！要是能够fork项目，以后这种修修补补的小活儿我直接给你pull request了。
