### ISSUE TITLE
绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况

### ISSUE THREAD

**Issue by liang-liang1** [suziwen/markdownxiaoshujiang#1267]
https://i.loli.net/2020/01/17/WiQ2RNV3plGZgju.png

**Comment by suziwen** [comment]
刚测试了下，我这边没有问题的

https://gitee.com/booksmith/testaa/raw/master/小书匠/1579228157755.png

--------------

直接在编辑器用剪切版 粘贴图片呢，或者将图片拖拽到编辑器内呢？

图片名称比较特别？

**Comment by liang-liang1** [comment]
我昨天正用着插入图片的功能呢，今天打开电脑不知道什么情况不能正常使用，昨天我还添加图片啦（![政策查询界面](https://gitee.com/wwb225241/img/raw/master/小书匠/微信截图_20200116174735.png) ），这是什么情况，给你发了个录屏，你看下什么情况，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 上午10:32
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"心如薄荷天然凉"<813938294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况 (#1267)




刚测试了下，我这边没有问题的
 
https://gitee.com/booksmith/testaa/raw/master/小书匠/1579228157755.png
 
 
直接在编辑器用剪切版 粘贴图片呢，或者将图片拖拽到编辑器内呢？
 
图片名称比较特别？

**Comment by suziwen** [comment]
看不到你发的录屏内容。直接发到这个邮件 suziwen1@gmail.com

**Comment by suziwen** [comment]
试一下在 web 版上绑定 gitee 图床，然后用 chrome 按 `f12` 看下上传图片时有什么信息提示。

-------

或者在客户端重新绑定一个新的 gitee 图床呢？

------

客户端版本是多少

**Comment by liang-liang1** [comment]
我又重新添加了个仓库，然后又弄了个令牌，也绑定成功了，但就是上传图片一直加载中，版本号是7.9.0


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 中午11:43
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"心如薄荷天然凉"<813938294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况 (#1267)




试一下在 web 版上绑定 gitee 图床，然后用 chrome 按 f12 看下上传图片时有什么信息提示。
 
 
或者在客户端重新绑定一个新的 gitee 图床呢？
 
 
客户端版本是多少

**Comment by suziwen** [comment]
新的仓库地址是什么？绑定成功时，会上传一个验证图片，验证图片有没有在新的仓库里？

或者你先把数据目录暂时移走，再启动小书匠，重新绑定，看能不能上传成功。

数据目录位置可以到 `小书匠按钮>关于` 界面上看到。

**Comment by liang-liang1** [comment]
验证图片有，文件移除后可以使用，这是什么情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 中午12:12
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"心如薄荷天然凉"<813938294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况 (#1267)




新的仓库地址是什么？绑定成功时，会上传一个验证图片，验证图片有没有在新的仓库里？
 
或者你先把数据目录暂时移走，再启动小书匠，重新绑定，看能不能上传成功。
 
—数据目录位置可以到&nbsp;小书匠按钮&gt;关于&nbsp;界面上看到。

**Comment by suziwen** [comment]
能把你那数据目录压缩一下，发我邮箱吗？我需要调试下才能知道具体原因。

**Comment by liang-liang1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 下午2:06
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"心如薄荷天然凉"<813938294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况 (#1267)




能把你那数据目录压缩一下，发我邮箱吗？我需要调试下才能知道具体原因。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Default.zip (380.74M, 2020年02月16日 14:08 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=23633836751e0c8d15d5bb0643310a4a5052015703090a064e53080f061c0c515605150f54020d4857520a000350595c54060a05653a3821060559430945161f0a13380b&t=exs_ftn_download&code=cc86e18e

**Comment by suziwen** [comment]
感觉像是数据目录上的数据库有错误数据(或者可能满了)，

你可以先 `小书匠按钮>数据>导出数据` 来导出最近 30 天的数据，然后把数据目录下的 `storywriter/Default/IndexedDB` 目录删除，启动小书匠，导入刚才导出的数据。(看文章数量，导入导出过程可能要比较长时间)

**Comment by liang-liang1** [comment]
我的图床转化大概有700张图片吧，转化了快四个小时了，还没转化完，什么情况？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月17日(星期五) 下午3:15
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"心如薄荷天然凉"<813938294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 绑定过码云的图床，点击插入图片一直显示加载中，昨天还可以正常使用，这时什么情况 (#1267)




感觉像是数据目录上的数据库有错误数据(或者可能满了)，
 
你可以先 小书匠按钮&gt;数据&gt;导出数据 来导出最近 30 天的数据，然后把数据目录下的 storywriter/Default/IndexedDB 目录删除，启动小书匠，导入刚才导出的数据。(看文章数量，导入导出过程可能要比较长时间)

**Comment by suziwen** [comment]
图片太多了，还没测试过这吗多图片的文章，估计性能已经到了瓶颈吧。还是建议把文章分成多篇，不要试图在一篇文章里包含一整本书的内容。

-------

还有一个就是你那个数据目录估计老文件很多了，还是建议像上面[提到的](https://github.com/suziwen/markdownxiaoshujiang/issues/1267#issuecomment-575504963)，导出最近 30 天的数据文件 ，然后删除数据目录，再重新导入 。
