### ISSUE TITLE
咨询: 作者以后会考虑以小书匠为基础，做云笔记软件吗?

### ISSUE THREAD

**Issue by juejian** [suziwen/markdownxiaoshujiang#1268]
如题，目前流行的有道云笔记、为知笔记、印象笔记对markdown的支持及其它功能都存在一些缺陷，不如小书匠支持的好。

**Comment by suziwen** [comment]
云笔记概念应该是把笔记内容存储到云端，这个受很多因素影响，比如各种资源（硬件，软件），当前政策等，而且很多大公司都在做，竞争激烈，不是个人或者一个小团队就能够支撑起来的。

所以做自己的存储这块估计不会考虑，目前还是专注在工具功能上的开发。

而且感觉小书匠提供的第三方存储就可以满足大部分用户的需求了。用户也更喜欢把自己的数据放在自己信任的地方，比如本地或者其他第三服务(像 github)


如果想把小书匠当成笔记来用，也可以了解小书匠的内部数据存储, 小书匠内部的数据结构都是透明的

http://soft.xiaoshujiang.com/docs/tutorial/files_manager/

http://soft.xiaoshujiang.com/docs/tutorial/database/

http://soft.xiaoshujiang.com/blog/setup_custom_couchdb_server/

**Comment by juejian** [comment]
ok, 明白了
