### ISSUE TITLE
进不去

### ISSUE THREAD

**Issue by 2515299122** [suziwen/markdownxiaoshujiang#1273]
昨天用还是好好的，今天怎么等都加载不进去，重装也是一样

**Comment by suziwen** [comment]
http://soft.xiaoshujiang.com/blog/question/can_not_start

**Comment by 2515299122** [comment]
确实可以了，不过两天时间出现四次这怎么搞，hold不住这么折腾

**Comment by suziwen** [comment]
看看你的文章里，是否有使用了不规范的元数据 ，

比如

标题前后带有 `[` `]` 符号，这个会触发成标题变成数组，造成系统无法启动。

```
---
title: [小书匠错误的标题]
---
```

可以在标题前后用引号包裹，强制生成字符串格式，比如下面的写法。

```
---
title: "[小书匠带有 [] 符号的正确标题]"
---
```



--------------



或者你也可以把数据目录压缩一下（不能启动时的数据目录），发到我的邮箱 suziwen1@gmail.com , 我看一下具体什么原因造成的。

**Comment by 2515299122** [comment]
确实有一个是这样的，我改下看看下次还有没有吧
