### ISSUE TITLE
导出封面太难设置了

### ISSUE THREAD

**Issue by wltj920** [suziwen/markdownxiaoshujiang#1275]
封面有标题、副标题和作者，但是3个值间距的调整是双向margin，想调成合适的样子实在太难了。能否改成单向margin？

**Comment by suziwen** [comment]
这个需要了解些 CSS 基础。可以通过 `主标题/副标题/作者CSS字体`  进行行高的设置。格式为`字体大小/行高大小 字体`
比如 `2em/1em serif` ，表示的是字体大小 2em, 行高 1em ，使用服务器默认的 serif 字体。

如果想把某一项的行高调大，只要把行高项加大一些就可以了。

同时字体大小和行高大小的单位也可以是 px, pt, mm, rem 等，并不一定要 em 这个单位。比如我可以把行高设置成 200px, `2em/200px serif`

设置的值，
![image](https://user-images.githubusercontent.com/57370/73664452-66384500-46da-11ea-89f9-0325898cade3.png)

导出后的效果

![image](https://user-images.githubusercontent.com/57370/73664481-751ef780-46da-11ea-9256-b92d4d80d076.png)


``` html
<div style="text-align: center; vertical-align: middle;">
           <h1 style="font: bold 2em/200px serif;color:#000000;">小书匠a</h1> 
              <h3 style="font: 1.5em/80px sans-serif;color:#000000;">小书匠b</h3>
              <p style="font: 0.8em/80px serif;color:#bbbbbb;">小书匠c</p>
         </div>
```

**Comment by suziwen** [comment]
如果上面的设置不符合要求，也可用 另一种不太正式的方法，暂时魔改下。

就是系统这边最终都是通过拼接 css 的方式实现的。

你可以在 `css 字体` 项里，额外添加一些 css 样式，间接控制 html 元素的其他样式。

比如想把作者项下移些，可以设置成  `0.8em/80px serif;margin-top: 300px`。


最终效果

![image](https://user-images.githubusercontent.com/57370/73666694-25dac600-46de-11ea-83e0-0ef5d0685019.png)

**Comment by wltj920** [comment]
谢谢楼主，解决了我的问题
