### ISSUE TITLE
请求加入coding平台的数据储存接口

### ISSUE THREAD

**Issue by hacker-jerry** [suziwen/markdownxiaoshujiang#1276]
作者您好！
感谢您做出的卓越工作，您的在线markdown编辑器令我赞叹不已。

只是希望能添加一个小小功能，就是加入coding平台的第三方数据存储功能，不知道是否能实现呢？
谢谢！

-----
新年快乐！
最近疫情严重，也希望您能保重身体。祝好！

**Comment by suziwen** [comment]
嗯，也祝你新年快乐

----------

coding 以前有想添加的，后来发现他们提供的 api 没有保存文件的存储接口，就放弃了。

**Comment by hacker-jerry** [comment]
> 嗯，也祝你新年快乐
> 
> coding 以前有想添加的，后来发现他们提供的 api 没有保存文件的存储接口，就放弃了。

啊这样呀，那谢谢啦！
