### ISSUE TITLE
表格解析问题

### ISSUE THREAD

**Issue by medfav** [suziwen/markdownxiaoshujiang#1277]
表格内容带有ed2k链接（ed2k链接包含|），应将“[空格]|[空格]”这种格式作为表格分割符，解析出现问题（导致问题的markdown代码如下）：
| title1 | title2  | title3  | title4  |
| --- | --- | --- | --- |
| [Windows 10, Version 1909 简体中文消费者版64位](ed2k://|file|cn_windows_10_consumer_editions_version_1909_x64_dvd_76365bf8.iso|5381154816|6A56DE112B164EC054D1104C53F8F10B|/) | 5.01GB | 是 | 5F3C8E743C9E87BDEFDAABB49BBD0D7AA9221E7A |

**Comment by suziwen** [comment]
表格内如果有 `|` 符号， 可以用转义的写法 `\|`.
