### ISSUE TITLE
建议：将大纲转换为思维导图

### ISSUE THREAD

**Issue by Duola-li** [suziwen/markdownxiaoshujiang#1282]
建议：在转化思维导图时提供选项，生成图片格式保存到图床。

在用小书匠写github博客文章时，想插入思维导图。但是默认生成html，在博客中使用时因为内容为文本，并不是图片，所以返回为空，无法正常访问图片。
![image](https://user-images.githubusercontent.com/16505929/74896987-9ec16980-53d0-11ea-8ccc-fa441eb7b1cd.png)
就像下面这样
![image](https://www.liyue.site/assets/images/attachments/1582163098919.drawio.html)

**Comment by suziwen** [comment]
这样设计主要是考虑用户下次还可以继续编辑修改这个思维导图。
