### ISSUE TITLE
印象笔记中的大纲目录不能跳转

### ISSUE THREAD

**Issue by starsky9527** [suziwen/markdownxiaoshujiang#1283]
小书匠版本：7.9.0
印象笔记版本：6.10.3

在升级小书匠至最新版本后，编辑关联的印象笔记后，印象笔记中的大纲便无法跳转了，未升级前是正常的。

![image](https://user-images.githubusercontent.com/30900883/75000648-ebbd4280-5499-11ea-9c8f-02041ca554e5.png)

![image](https://user-images.githubusercontent.com/30900883/75000837-8453c280-549a-11ea-969f-7a5c87e16f2b.png)

**Comment by suziwen** [comment]
在升级小书匠到 `7.9.0` 版本之前，保存的文章大纲在 `6.10.3` 版本的印象客户端里还能跳转？


我这边测试了下，`6.3.3` 的 evernote 客户端还是可以点击跳转的(以前的和现在新保存的文章都可以跳转)，然后在 `6.20.0`的最新印象客户端(今天刚下载的)里，就不能跳转了（不管是以前的文章还是现在的），所以感觉好像是印象笔记自己升级的客户端不支持点击跳转了。

![image](https://user-images.githubusercontent.com/57370/75009413-97c05700-54b5-11ea-97b6-339d83b9df43.png)

![image](https://user-images.githubusercontent.com/57370/75009431-9f7ffb80-54b5-11ea-82a4-845a0f96303f.png)

**Comment by starsky9527** [comment]
你好：


升级小书匠之前，在&nbsp;6.10.3&nbsp;版本的印象中是可以跳转的。在升级后，如果小书匠中不修改笔记，印象笔记还是可以跳转的，一旦修改了，印象笔记就不能跳转了。即当时的印象笔记中，有部分笔记支持跳转，部分笔记不支持（升级后新增笔记、修改笔记）。


其它版本的印象跳转功能应该是有问题的，所以我一直用 6.10.3 版本的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 下午2:24
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"窗外"<907665061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 印象笔记中的大纲目录不能跳转 (#1283)




在升级小书匠到 7.9.0 版本之前，保存的文章大纲在 6.10.3 版本的印象客户端里还能跳转？
 
我这边测试了下，6.3.3 的 evernote 客户端还是可以点击跳转的(以前的和现在新保存的文章都可以跳转)，然后在 6.20.0的最新印象客户端(今天刚下载的)里，就不能跳转了（不管是以前的文章还是现在的），所以感觉好像是印象笔记自己升级的客户端不支持点击跳转了。

**Comment by suziwen** [comment]
你是从什么版本的小书匠升级到 `7.9.0` 的？

重新装回上一个客户端版本的小书匠，然后把数据目录临时移走，重新绑定印象笔记，保存后，在 `6.10.3` 的印象笔记客户端里还能点击吗？

小书匠数据目录可以先在 `小书匠主按钮>关于` 里查看到。
