### ISSUE TITLE
mac版本 点击全屏按钮直接crash

### ISSUE THREAD

**Issue by bjxiaxueliang** [suziwen/markdownxiaoshujiang#1284]
mac版本 点击全屏按钮直接crash

**Comment by bjxiaxueliang** [comment]
最新版本8.0

**Comment by suziwen** [comment]
我这边试了下，没有问题。可能跟操作系统的具体版本有关系，或者外部的其他软件有影响。

只能过段时间，看看还有没有其他用户比较多的反馈类似问题了。

**Comment by suziwen** [comment]
这个应该是 nwjs 底层的一个问题. https://github.com/nwjs/nw.js/issues/7254

你可以试试通过命令行启动小书匠,并带上参数  `--disable-features=nw2`


`open {小书匠程序} --disable-features=nw2`

比如你下载后的小书匠位置 `/home/username/download/stroy-wirter`

可以切换到目录 `cd /home/username/download` ,然后执行 `open story-writer --disable-features=nw2`
