### ISSUE TITLE
更新8.0之后找不到预览和文件栏在哪里了

### ISSUE THREAD

**Issue by G233** [suziwen/markdownxiaoshujiang#1285]
如题，不要为了美观把功能性降低吧

**Comment by G233** [comment]
原来是要输入文字后才能打开，着实有些不方便

**Comment by suziwen** [comment]
![1582425742682](https://user-images.githubusercontent.com/57370/75102634-cfe8a680-5629-11ea-837c-c35f25e63184.png)

**Comment by suziwen** [comment]
可以通过快捷键

打开或者关闭预览

默认快捷键 <kbd>ctrl+shift+p</kbd>

打开文件列表

默认快捷键 <kbd>ctrl+shift+f</kbd>


http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/

http://soft.xiaoshujiang.com/docs/tutorial/commands/

**Comment by G233** [comment]
经过测试发现 刚打开的时候是大窗口，没有显示预览和文件窗口点击区域，再放大窗口也不会显示，需要缩小窗口再次拉大才会显示。很不方便，一定会复现。打开文件列表快捷键也没有用
![image](https://user-images.githubusercontent.com/39009225/75134911-ba9f7500-571a-11ea-9390-d3801046e136.png)

**Comment by suziwen** [comment]
我这边测试了下，每次打开最大化时，左右两侧都能正常显示那两个按钮。
不知道有没有重现的操作步骤，让打开小书匠最大化时那两按钮消失。


---------


窗口要调到指定大小才会触发不同的布局，比如左右两侧的按钮显示。

目前的设定是 `x<768`, `768<= x <=992`, `x>992` 这三个临界点，窗口小于 768 时，两侧的按钮都会消失， 在 768, 992 之间时，左边的会消失，右边的保存不变，只有当窗口大于 992 时， 左边和右边的才会同时显示。

**Comment by shigw** [comment]
1、左边按钮显示不出来。
2、ctrl-shift-f好像和印象笔记有冲突。
3、反复调整大小后，出来了左边按键，
4、左边按键出来了以后，展开左侧列表后，又找不到左边按键了。
5、这俩按键建议放别的地方，一是bug多，二是太费眼睛找不到，三是鼠标点起来费力。

**Comment by G233** [comment]
非常同意

**Comment by suziwen** [comment]
[8.0.1](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.0.1) 已经修复了

**Comment by shliang0603** [comment]
建议改掉这个侧边栏预览效果：
1、由于选用不同的主题效果，这个侧边栏的经常显示看不到
2、位置也不固定，会随滚动条移动，难以锁定
3、还会出现找不到的情况，我今天打开小书匠，找不到了，无法进行预览

因此，强烈建议改变其位置，和显示的形式！！！

**Comment by suziwen** [comment]
@shliang0603 
1. 没明白, 切换不同的主题, 侧边栏会消失?我这边一直都存在的,并没有你说的情况
2. 还是不明白你的描述,能给个 gif 看看你说的情形吗
3. 侧边栏的预览需要在比较大的窗口下才能看到,在太小的的窗口下会被隐藏,然后在工具栏里就会出现一个预览按钮.
