### ISSUE TITLE
升级成8.0版本后，左侧列表栏以及视图栏都不见了

### ISSUE THREAD

**Issue by linut** [suziwen/markdownxiaoshujiang#1286]
![微信截图_20200224093016](https://user-images.githubusercontent.com/15168038/75124171-667b9d00-56e8-11ea-9a9c-c80c0631d674.png)
![eee20200224091735](https://user-images.githubusercontent.com/15168038/75124198-9034c400-56e8-11ea-900f-942ddd8bcbc3.png)

**Comment by linut** [comment]
GitHub上面图上传不上去，我就描述下。在8.0版本前，我的工作界面是分为3栏，最左侧是文章列表栏，中间编辑栏，右侧视图栏。
在本次更新完8.0版本后，我工作界面就只剩下编辑栏了，以前还可以通过编辑栏最左侧或者最右侧中间的小按钮拉成三栏，但现在小按钮也没有了，我只能先恢复到7.9版本。

**Comment by linut** [comment]
刚才通过外网把图上传了，可以看下目前我的7.9版本和8.0版本的界面。

**Comment by suziwen** [comment]
把窗体手动调整一下大小，两侧边上的按钮就应该会自动出来。

或者用 `ctrl+shift+f` 和 `ctrl+shift+p` 打开/关闭 文件列表和预览，然后那些按钮就应该会出现了。

如果还是没有出现的话，可以再在这里发一下。

**Comment by linut** [comment]
用快捷键可以打开了

**Comment by suziwen** [comment]
#1285

**Comment by suziwen** [comment]
[8.0.1](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.0.1) 已经修复了
