### ISSUE TITLE
8.0版本最小化按钮无法将软件缩到任务栏

### ISSUE THREAD

**Issue by linut** [suziwen/markdownxiaoshujiang#1288]
升级到8.0版本后，我点击右上角的最小化按钮，软件不再是缩到任务栏而是缩到手动调整的界面大小，只有再点击一下最小化才可以收到任务栏。

按win+D也是一样效果。

系统win10，小书匠版本8.0。另外说一下，这个8.0版本我使用感觉小问题有点多，看了升级日志，不知道是不是升级底层的原因，暂时我回退到了7.9，到时候一起升8.1吧。

**Comment by suziwen** [comment]
[8.0.1](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.0.1) 已经修复了

感谢反馈，确实是底层 nwjs 升级引起的， nwjs 修改了最大化/最小化等事件触发的顺序。
