### ISSUE TITLE
GitHub一直加载出错 Load Error

### ISSUE THREAD

**Issue by Loren-Wang** [suziwen/markdownxiaoshujiang#1290]
![image](https://user-images.githubusercontent.com/26294416/75407857-0175b080-594f-11ea-87a4-a23ff7493d62.png)

Load error!({"path":"","request":{"dataType":"json"},"error":0})

**Comment by Loren-Wang** [comment]
有时候正常，有时候会出现

**Comment by suziwen** [comment]
不定时出现的话，估计跟网络环境有关，建议使用一个稳定的网络环境，同时保证连接 github 正常。

**Comment by liao20081228** [comment]
> 不定时出现的话，估计跟网络环境有关，建议使用一个稳定的网络环境，同时保证连接 github 正常。

我也是同样的问题，求解决
