### ISSUE TITLE
markdown 能够取消 *做斜体的功能吗。

### ISSUE THREAD

**Issue by ligoudanblabla** [suziwen/markdownxiaoshujiang#1291]
要使用大量的*，如果每个都添加反斜杠的话太麻烦了

**Comment by suziwen** [comment]
现在还不能，因为这个是最基础的 markdown 语法，所以当时没考虑提供取消这个功能的控制。

后继版本会考虑在语法设置里添加一个取消该语法的选项。

**Comment by liao20081228** [comment]
> 现在还不能，因为这个是最基础的 markdown 语法，所以当时没考虑提供取消这个功能的控制。
> 
> 后继版本会考虑在语法设置里添加一个取消该语法的选项。

不建议，基本语法应该遵循基本的规范。

**Comment by vio1etus** [comment]
> 要使用大量的*，如果每个都添加反斜杠的话太麻烦了

可以使用键盘 esc 下面那个波浪线包裹，做成行内代码，那样就不用加反斜杠了

示例：
```
`***`
```

`***`
