### ISSUE TITLE
建议：增加侧边标题导航功能

### ISSUE THREAD

**Issue by yinglovezhuzhu** [suziwen/markdownxiaoshujiang#1293]
首先，感谢小书匠编辑器给与的极大方便，针对编写技术文档的需求，我建议编辑器能有一个跟word那样的侧边标题导航的功能，这样导出来的文档，更方便阅读

**Comment by suziwen** [comment]
你是指导出的 html 左边有个大纲功能?

![image](https://user-images.githubusercontent.com/57370/75841623-2b284f00-5e09-11ea-967c-d2e276afb68c.png)

**Comment by yinglovezhuzhu** [comment]
> 你是指导出的 html 左边有个大纲功能?
> 
> ![image](https://user-images.githubusercontent.com/57370/75841623-2b284f00-5e09-11ea-967c-d2e276afb68c.png)

没错，但是你的图片看不到，就是类似word那样的导航窗格

**Comment by suziwen** [comment]
我的图片看不到是什么情况?

就是在`导出界面>html` 的左边有个三角形的图标,点击展开, 然后选择 `生成带脚本的目录` 选项就可以了.

**Comment by yinglovezhuzhu** [comment]
> 我的图片看不到是什么情况?
> 
> 就是在`导出界面>html` 的左边有个三角形的图标,点击展开, 然后选择 `生成带脚本的目录` 选项就可以了.

原来已经有这个功能了，一直不知道，感谢提醒。
PS：不知道咋地今天github上面的图片全部不显示，包括头像，都是裂图

**Comment by yinglovezhuzhu** [comment]
> 我的图片看不到是什么情况?
> 
> 就是在`导出界面>html` 的左边有个三角形的图标,点击展开, 然后选择 `生成带脚本的目录` 选项就可以了.

另外想问一下，自动编号的格式是否可以自定义？现在默认都是1-1-1这样的，能否自定义成1.1.1这样的？

**Comment by suziwen** [comment]
可以看看这个[文档](http://soft.xiaoshujiang.com/blog/numbered_heading)

`设置>预览`
比如三号标题 renderNumberedHeadingH3 值,改成 `counter('h2', '%s.');counter('h3', '%s ');`

四号标题 renderNumberedHeadingH4 值改成`counter('h2', '%s.');counter('h3', '%s.');counter('h4', '%s  ');`

**Comment by yinglovezhuzhu** [comment]
> 可以看看这个[文档](http://soft.xiaoshujiang.com/blog/numbered_heading)
> 
> `设置>预览`
> 比如三号标题 renderNumberedHeadingH3 值,改成 `counter('h2', '%s.');counter('h3', '%s ');`
> 
> 四号标题 renderNumberedHeadingH4 值改成`counter('h2', '%s.');counter('h3', '%s.');counter('h4', '%s ');`

好的，感谢
