### ISSUE TITLE
打字机滚动效果无法记忆上次位置，每次打开都是默认上方，需要手动调整

### ISSUE THREAD

**Issue by linut** [suziwen/markdownxiaoshujiang#1294]
![image](https://user-images.githubusercontent.com/15168038/75936772-15289600-5ebe-11ea-8079-1da1054b3fb4.png)
这个图钉标记功能叫什么我不知道，但是我能明白它的作用。就是每次打开文档进行编辑的位置。我记得8.0.1版本前是可以调整位置和记忆位置的，但是现在只能调整，无法记忆位置，每次打开都是默认上方，需要手动拉一下才可以。

另外标题我会根据这个功能名字更改，麻烦告知下，以便后来人可以看到。

**Comment by suziwen** [comment]
确认 bug, 感谢反馈.

主要原因是这个图钉没有监听窗口大小的变化,如果你的窗口不是最大化状态,关闭后再打开,还是会记忆你上次的位置.

以前版本的问题是当调整窗口大小后,图钉位置和光标实际停留位置会错位,对不上的问题,特别是在调整窗口高度的时候,高度变化越大,错位越严重,需要手动重新拖拽图钉才能解决.

---------

这个是 `打字机滚动效果` , 可以在 `设置>编辑器>codemirror>打字机滚动效果` 里控制打开或者关闭.
