### ISSUE TITLE
升级到8.0后好像公式显示不了了？

### ISSUE THREAD

**Issue by hexawing** [suziwen/markdownxiaoshujiang#1295]
![如图所示](https://user-images.githubusercontent.com/230037/75967050-301ef880-5f06-11ea-89d9-32d270232acc.png)
看了下语法也没有改呀？

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/75967523-ed115500-5f06-11ea-9fb6-f0c4e65cfbac.png)
