### ISSUE TITLE
Bug：小书匠Windows版8.0.1无法使用导图样式的标题

### ISSUE THREAD

**Issue by yinglovezhuzhu** [suziwen/markdownxiaoshujiang#1297]
在Windows下离线版无法识别成导图样式的标题，如下图：
![image](https://user-images.githubusercontent.com/3961801/76043933-dfee7780-5f93-11ea-962e-b9802e874263.png)

一样的MarkDown文本，在线的小书匠编辑器却是可以的，如下图：
![image](https://user-images.githubusercontent.com/3961801/76043997-03b1bd80-5f94-11ea-9de1-c94b68b70279.png)

PS：我看到编辑器自带的使用手册，在Windows离线版上是可以显示导图样式标题，但是我将文本copy到新建的一个文件的时候，也是无法显示导图样式的标题，我直接在编辑器里编写mindmap脚本也是无效，甚是奇怪。另外，我的配置里都是启用了所有扩展脚本的

**Comment by suziwen** [comment]
这个是会员功能,非会员只能在系统内置帮助文章里使用.

[思维导图](http://soft.xiaoshujiang.com/docs/grammar/feature/mindmap/#e6b3a8_31)

----------

后继版本会做一个提示,避免以为是个 bug.
