### ISSUE TITLE
建议-分类文件夹📂

### ISSUE THREAD

**Issue by qingchuwudi** [suziwen/markdownxiaoshujiang#1299]
## 情景

- 文档写的比较多，找的时候是 **一个大列表** 从头拖到尾，比较麻烦。

- 现在里面的文档展示顺序不是按照创建时间排列，这种情况下查找文档的时候和自己的记忆不一致，反倒增加了不少麻烦。

## 建议

建议增加 文件夹📂（目录、或者空间）的功能，就像浏览器的收藏夹一样，可以自己整理归类。

如果直接增加文件夹功能比较麻烦，可以考虑把文档里面的tag当做文件夹展示，这样也可以接受。

找到两个有类似需求的issue ： #1067 #1205 

这款软件用了一段时间，很好用很有帮助，希望越做越好。

以上，谢谢！

**Comment by suziwen** [comment]
可以看一下小书匠的[过滤器](http://soft.xiaoshujiang.com/docs/tutorial/filter/)功能.

不过该功能目前在客户端只对会员用户开放,非会员用户只能在 web 版本上使用.

**Comment by qingchuwudi** [comment]
> 可以看一下小书匠的[过滤器](http://soft.xiaoshujiang.com/docs/tutorial/filter/)功能.
> 
> 不过该功能目前在客户端只对会员用户开放,非会员用户只能在 web 版本上使用.

以前还真没发现有这个功能，用了一下挺好的基本能满足需求。不过还是不如直接建目录方便。
