### ISSUE TITLE
升级8.0后腾讯图床的图片打不开了

### ISSUE THREAD

**Issue by marsggbo** [suziwen/markdownxiaoshujiang#1300]
![](https://ask.qcloudimg.com/draft/1215004/tr8agw7zz0.png?imageView2/2/w/1620)

![](https://ask.qcloudimg.com/draft/1215004/21ra82axnz.jpg)

**Comment by marsggbo** [comment]
比如如下两个图片链接

https://ask.qcloudimg.com/draft/1215004/tr8agw7zz0.png?imageView2/2/w/1620

https://ask.qcloudimg.com/draft/1215004/21ra82axnz.jpg

**Comment by suziwen** [comment]
你这两个图片我这里浏览器就不能直接打开,图床里的图片必须要有开放给外部访问的权限,小书匠才可以访问到的.

![image](https://user-images.githubusercontent.com/57370/76097324-78bbdc00-6002-11ea-89ec-4efe5e081067.png)

**Comment by marsggbo** [comment]
但是很奇怪我用阿里的云栖社区和这个[在线工具](https://mdnice.com/)都能正常显示。

![image](https://user-images.githubusercontent.com/13477956/76098901-3d6edc80-6005-11ea-804b-519af09c8aaf.png)
![image](https://user-images.githubusercontent.com/13477956/76098912-4495ea80-6005-11ea-9466-d9d4816c98d5.png)
![image](https://user-images.githubusercontent.com/13477956/76098942-511a4300-6005-11ea-8aa1-e863829bd659.png)

**Comment by suziwen** [comment]
你在 github 的评论里这样输入,然后看能不能出图片

```
![](https://ask.qcloudimg.com/draft/1215004/21ra82axnz.jpg)
```

![](https://ask.qcloudimg.com/draft/1215004/21ra82axnz.jpg)

**Comment by suziwen** [comment]
或者你自己浏览器用隐身模式,打开这个链接 https://ask.qcloudimg.com/draft/1215004/21ra82axnz.jpg    看能不能访问到图片 .

**Comment by marsggbo** [comment]
隐私模式打不开了。。。这是为啥

**Comment by suziwen** [comment]
这个得你自己到腾讯服务器上看下配置了.

想用图床的话,图片存放的空间必须对外开放可以访问的.
