### ISSUE TITLE
有关代码块的一个巨大bug

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1301]
1. **当我使用TAB，将代码对齐后，把代码格式从C变为C++，代码对齐立即乱了**
2. **当我使用TAB，将代码对齐后，如果更改代码预览样式，同样发生代码变乱**

**Comment by suziwen** [comment]
最好能给出重现的代码例子,及相关错误结果的截图效果,注上你期望的效果.

**Comment by liao20081228** [comment]
一开始我是用的tomorrow-night对整齐后，换为monokai，就不对齐了，然后在同一主题下，选择c/cpp/text 都会导致不对齐。

**Comment by suziwen** [comment]
我这边没法重现你说的情形,对齐跟很多因素有关,比如你自己机器上的字体, tab键是否自动切换了 space 键等.
或者给个录屏 gif 最好

**Comment by liao20081228** [comment]
@suziwen 可以看到左边的markdown原文字没有变化，但是右边的预览对齐却在变化

![QQ截图20200307233356](https://user-images.githubusercontent.com/25471051/76155068-da269c80-6121-11ea-88e9-2127a4008d33.png)

![QQ截图20200307233433](https://user-images.githubusercontent.com/25471051/76155070-e01c7d80-6121-11ea-8f75-6fea8d758905.png)

![QQ截图20200307233521](https://user-images.githubusercontent.com/25471051/76155071-e3b00480-6121-11ea-9899-04a1bd7756ac.png)

**Comment by liao20081228** [comment]
![bug](https://user-images.githubusercontent.com/25471051/76155351-0217ff00-6126-11ea-9706-0f3ed6d994d1.gif)

**Comment by suziwen** [comment]
这个就是跟机器上安装的字体和使用的 tab 字符宽度设定有影响的.

你把你的那些代码复制到不同的编辑器,或者不同的网页输入框,比如 github 的评论框里,对齐都是有可能跟预想的不一样.

------------

如果使用的字体不是等宽字体,不同的字符,宽度是不一样的,比如字母 `i` 和字母 `m` , 宽度差别就会很大,造成行与行之间想对齐是不可能的.

再有就是 tab 字符的使用, 不同的编辑器对 tab 的宽度设定也不一样,有些把 tab 设置成 2 个字符的宽度,有些设置成 4 个字符的宽度.


----------

如果想将代码块内的文字对齐起来的话, 建议使用等 宽字体,而且是中文的一个字等于英文的两个字的这种等宽效果.

还有就是把所有的 tab 字符转换成 空格 字符.

同时,如果想让编辑器效果和预览区效果都是对齐的, 两边的自定义样式都要保证使用等宽字体.

如果  codemirror 编辑器自己不太会设置样式的话, 可以将小书匠的内置编辑器切换成 ace 编辑器,把`显示隐藏字符` 效果打开 .


![image](https://user-images.githubusercontent.com/57370/76155717-d0556700-612a-11ea-90b7-012cbd60f51c.png)

**Comment by liao20081228** [comment]
@suziwen  我的设置如下？有什么问题吗？我用ace和mirror都是这样的。

1. monokai主题中：当把代码类型从text切换到cpp，或者从cpp切换到text对齐就乱了
2. 当主题从monokai切换到tomorrow-night，或者切换回来，对齐也会乱。

我查看了隐藏元素，TAB键的数量是没有发生改变的。

因此感觉是不同主题对tab键的处理不同。

你说的等宽字体是什么意思？

最新发现：在tomorrow-night 切换代码类型，不会导致对其变化

![QQ截图20200308110030](https://user-images.githubusercontent.com/25471051/76155801-6b027580-612c-11ea-97b6-60a9ff216668.jpg)
![QQ截图20200308110113](https://user-images.githubusercontent.com/25471051/76155802-6ccc3900-612c-11ea-9d4d-7f39c0bed440.jpg)
![QQ截图20200308110254](https://user-images.githubusercontent.com/25471051/76155803-6d64cf80-612c-11ea-8a8e-2ccb33849e63.jpg)

**Comment by suziwen** [comment]
预览区自定义 css 

```
body {
    tab-size: 4;
    letter-spacing: 0;
    word-spacing: 0;
}
```

**Comment by liao20081228** [comment]
> 预览区自定义 css
> 
> ```
> body {
>     tab-size: 4;
>     letter-spacing: 0;
>     word-spacing: 0;
> }
> ```

没用啊。我换tomorrow-night使用吧。

**Comment by suziwen** [comment]
你的预览区主题选的是什么?(不是代码块的主题,整个预览页面的主题)

**Comment by suziwen** [comment]
知道了,还是你的字体问题

两套不同的主题里,使用了不同的字重 , monokai 主题对变量名使用了 bold (700), 而 tomorrow-night 主题使用了 normal (400). 因为你的系统里字体里,可能没有同一种字体的不同字重,造成系统选择了其他字体,因为不同的字体宽度设计不一样,就会造成对齐效果不理想.

再自定义一下下面的预览区样式,应该 就可以了.
```css
.hljs-keyword, .hljs-selector-tag, .hljs-literal, .hljs-doctag, .hljs-title, .hljs-section, .hljs-type, .hljs-selector-id {
    font-weight: normal;
}
```
