### ISSUE TITLE
MacOS版全屏闪退

### ISSUE THREAD

**Issue by cjsoft** [suziwen/markdownxiaoshujiang#1305]
osx版本 10.15.3 (19D76)
小书匠版本 v8.0.1
无论是点击全屏模式按钮还是通过control center进行最大化，都会导致小书匠桌面应用闪退。

**Comment by suziwen** [comment]
#1284 

这个应该是 nwjs 底层的一个问题. https://github.com/nwjs/nw.js/issues/7254

你可以试试通过命令行启动小书匠,并带上参数  `--disable-features=nw2`


`open {小书匠程序} --disable-features=nw2`

比如你下载后的小书匠位置 `/home/username/download/stroy-wirter`

可以切换到目录 `cd /home/username/download` ,然后执行 `open story-writer --disable-features=nw2`

**Comment by cjsoft** [comment]
全屏问题解决，补充一下，catalina中应当是如下命令
```
open /Applications/Story-writer.app --args --disable-features=nw2
```
顺便问一下，停用feature nw2之后，对小书匠的功能会有什么影响吗？
非常感谢！

**Comment by cjsoft** [comment]
![image](https://user-images.githubusercontent.com/3616632/76501356-17ba5b00-647d-11ea-89b5-054b783ad35f.png)
可进行下列操作作为一个workaround

**Comment by suziwen** [comment]
应该不会有影响, nw2 的相关代码现在还没有用到
