### ISSUE TITLE
8.0.3版本的表格组件与印象笔记同步问题

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1307]
如果在印象笔记关联的文件里插入一个表格组件，并且什么都不写，也就是右侧也不会渲染出来，则会保存不了，就是一直在“正在保存”，不会保存成功，如果插入表格组件但是表格内有内容，则可以正常保存。发现这个bug是因为无意间在笔记里插入了个表格组件，没写内容，就保存不了了。

**Comment by suziwen** [comment]
感谢反馈,确认为 bug.

**Comment by AtaraxiaZ** [comment]
作者的效率也太高了，今天已经把更新了bug的版本发出来了👍
