### ISSUE TITLE
建议添加和Typora一样的自定义图片本地地址

### ISSUE THREAD

**Issue by Eggplant4363** [suziwen/markdownxiaoshujiang#1309]
![image](https://user-images.githubusercontent.com/44885380/76677789-52eb9400-660d-11ea-90d0-9cc6950da6c5.png)

**Comment by suziwen** [comment]
`设置>基本>资源绝对路径起始地址`

![image](https://user-images.githubusercontent.com/57370/76680861-8c30fd80-6627-11ea-96c5-c2ccfe70c434.png)
