### ISSUE TITLE
Sql语法高亮问题

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#131]
sql语句在代码块中如果手动换行(按enter键后)，高亮就失效（关键字和其他非关键字都会进行高亮）。
顺便说一下，xiaoshujiang.com 写文章的编辑器使用[toc]生成的目录，target='_blank'不应该要了。

**Comment by suziwen** [comment]
高亮失效的问题能贴个图看下吗。

**Comment by leongfeng** [comment]
![meitu_0](https://cloud.githubusercontent.com/assets/11471256/13098868/8ac6081e-d567-11e5-87ef-c32cc1e5d85c.jpg)

**Comment by suziwen** [comment]
web版修复完成，客户端下次更新。


window话可以自己替换下这个文件
`安装目录/js/app.js`

注:
1. 仅适用1.8.0版本
2. 替换前备份下app.js原文件
[app.js.zip](https://github.com/suziwen/markdownxiaoshujiang/files/134538/app.js.zip)

**Comment by leongfeng** [comment]
您好：
有些关键字不能高亮，我如果想手动添加一些关键字来进行判断应该修改哪个js?

**Comment by suziwen** [comment]
目前使用的是 https://highlightjs.org 进行高亮，
好像该库还没有提供自定义关键字，不过你可以修改他的源文件 https://github.com/isagalaev/highlight.js/blob/master/src/languages/sql.js ，把 building后的压缩文件追加到 `安装目录/js/vendor.js` 未尾应该就可以。
