### ISSUE TITLE
无法同步印象笔记

### ISSUE THREAD

**Issue by shendeguize** [suziwen/markdownxiaoshujiang#1312]
版本8.0.4 升级前的8.0.3也有这个问题
[截图](https://shendeguize-picbed.oss-cn-beijing.aliyuncs.com/images/Snipaste_2020-03-16_10-39-02.png)

**Comment by ittimeline** [comment]
+1

**Comment by suziwen** [comment]
错误显示是网络请求超时,感觉像是印象服务器挂了,或者你的网络有问题. (客户端版本小书匠印象笔记请求是没有经过小书匠中转,直接链接印象服务器的.)


现在呢? 
我现在小书匠客户端测试是正常的.

**Comment by ittimeline** [comment]
![image](https://user-images.githubusercontent.com/45027871/76730034-5dd13080-6795-11ea-8ec6-546ff0a4b760.png)

印象笔记的目录都加载不出来

**Comment by ittimeline** [comment]
![读取目录失败](https://user-images.githubusercontent.com/45027871/76731475-7ee75080-6798-11ea-87a9-47d9a74fffca.png)

**Comment by ittimeline** [comment]
加载出错服务器出错....{"errno":-4077,"code":"ECONNRESET","syscall":"read"}

**Comment by ittimeline** [comment]
![image](https://user-images.githubusercontent.com/45027871/76733125-282f4600-679b-11ea-8daa-13b024c38405.png)

**Comment by ittimeline** [comment]
![image](https://user-images.githubusercontent.com/45027871/76733410-bb687b80-679b-11ea-8ed7-5d3bac45c5c6.png)

**Comment by linut** [comment]
![image](https://user-images.githubusercontent.com/15168038/76737689-36ce2b00-67a4-11ea-81c3-9accb22ae794.png)
一样的问题。

**Comment by ittimeline** [comment]
我已经退到6.x版本，能够正常使用

**Comment by linut** [comment]
7.9版本也不行

**Comment by ittimeline** [comment]
7.8也不行

**Comment by suziwen** [comment]
回退到 7.9, 7.8 都有问题的话, 那我感觉还是印象笔记服务器有问题, 7.9 或者 7.8 都是去年发布的版本,要是那几个版本印象笔记不能连接, 当时早就有人反馈这个问题了.

回退到 6.x 就可以,那感觉就是碰巧印象服务器刚好恢复了.


-----------

还有一个就是我现在再测试了一下,还是可以正常连接印象笔记服务器.

**Comment by suziwen** [comment]
@ittimeline  有道笔记那个提示是小书匠现在不支持从有道读取数据,这个没办法,他们家的api 不支持.

**Comment by WindFreedomP** [comment]
保存失败: 服务器出错....{"errorCode":9,"parameter":"authenticationToken"}
保存失败: {"code":1006,"error":"服务器出错....{\"errorCode\":9,\"parameter\":\"authenticationToken\"}","orign":{"errorCode":9,"parameter":"authenticationToken"}}
