### ISSUE TITLE
linux 绑定印象笔记后，不出现选择

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1313]
![image](https://user-images.githubusercontent.com/33022132/76729691-b2c07700-6794-11ea-946a-29e7810f8b99.png)

先绑定了 github， 又绑定印象笔记，显示授权成功，但是选项里面没有印象笔记。

manjaro linux 最新版19， 小书匠当前版本: 8.0.1

**Comment by suziwen** [comment]
#1312 

感觉是印象服务器有问题.

现在测试呢?

**Comment by vio1etus** [comment]
瞬间好了，emm。

**Comment by vio1etus** [comment]
大概率是印象笔记问题，多谢大佬！
