### ISSUE TITLE
更新版本8.0.1后原先主题的样式都被改变了

### ISSUE THREAD

**Issue by Serenity1994** [suziwen/markdownxiaoshujiang#1314]
我macbook使用的story-sticker主题,更新之后样式和以前的有很大差别,而且我尝试卸载后重装原先版本还是无法变回去

**Comment by Serenity1994** [comment]
![Uploading image.png…]()
还有一点小的问题,代码块设置语言的提示排序能不能按照最匹配的排在前面,比如说我现在设置想设置```java,它总是会第一个提示javascript

**Comment by suziwen** [comment]
嗯,新版本对预览主题做了比较多的调整.如果想要用回原先的样式,只能回退到早期版本(你的原先版本是多少?), 比如 7.x 的版本.  或者是自己自定义 css 样式调整.

------------
一些以 story_ 开头的主题, 样式上的修改都比较激进些,会使用到很多 html5 css3 的特性,改动也会比较大, 兼容性比较差.  default 主题适用性比较广,会考虑很多兼容问题.

**Comment by suziwen** [comment]
排序这个问题,后面再改进一下.

**Comment by Serenity1994** [comment]
> 嗯,新版本对预览主题做了比较多的调整.如果想要用回原先的样式,只能回退到早期版本(你的原先版本是多少?), 比如 7.x 的版本. 或者是自己自定义 css 样式调整.
> 
> 一些以 story_ 开头的主题, 样式上的修改都比较激进些,会使用到很多 html5 css3 的特性,改动也会比较大, 兼容性比较差. default 主题适用性比较广,会考虑很多兼容问题.

有没有之前版本的链接呀,我现在的都是8以上的版本,,,

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases
