### ISSUE TITLE
建议将历史版本备份在百度网盘

### ISSUE THREAD

**Issue by ittimeline** [suziwen/markdownxiaoshujiang#1316]
建议将历史版本备份在百度网盘，这样如果新版本有Bug，用户可以快速下载。相对于GitHub和Gitee快很多

**Comment by suziwen** [comment]
这个想了想,还是不整理了,主要是更希望大家用最新版本的小书匠. 

其他历史版本要吗用户自己保存,要吗就是集中到 github 来下载.
