### ISSUE TITLE
PDF导出，封面作者名显示不全

### ISSUE THREAD

**Issue by LonlyPan** [suziwen/markdownxiaoshujiang#1317]
如图，”LonlyPan“ 作者名的 ‘y’ 字母显示有问题。

![image](https://user-images.githubusercontent.com/48073168/76938704-1338eb00-6932-11ea-98c2-72d0b6d0055a.png)

**Comment by suziwen** [comment]
试试把这个封面设置里的行高改一下(改成无单位的 1)

```
bold 2em/1.2 serif
1.5em/1.1 sans-serif
0.8em/1 serif
```

![image](https://user-images.githubusercontent.com/57370/76939635-ae7e9000-6933-11ea-99c4-784fe60dc16a.png)

**Comment by LonlyPan** [comment]
已按照上述设置，问题依旧，未解决
软件版本：8.0.4（最新版）
环境：Win10 家庭版

![image](https://user-images.githubusercontent.com/48073168/77049480-1f40ad80-6a03-11ea-8a5a-97a7223d3657.png)

**Comment by suziwen** [comment]
那把这个值调大点,改成 `1.5`

```
0.8em/1.5 serif
```

**Comment by LonlyPan** [comment]
改成1.5问题解决，谢谢！
