### ISSUE TITLE
隐私安全问题

### ISSUE THREAD

**Issue by LonlyPan** [suziwen/markdownxiaoshujiang#1318]
连接服务器导出PDF，
1、服务器是小书匠自有的还是别人的？
2、服务器会不会备份该文件或留有其他数据，有没有数据泄露风险？
3、一般本地文档编辑，不联网导出，软件会不会后台上传有关文档内容的数据？

**Comment by suziwen** [comment]
连网导出的肯定要经过小书匠服务器. 下载后使用的下载链接第二次会直接失效.

如果涉及到重要隐私数据,不建议使用联网导出.可以使用客户端本地 pdf 导出或者  打印,这些都是在本地完成的.小书匠服务器不会参与.

一般客户端版本用户文章数据都不会上传到小书匠服务器,但是如果你是会员的话,自己开启了配置参数同步功能,就会把用户的配置数据同步到小书匠服务器上.

**如果还配置使用了小书匠的临时数据中心,那吗用户的文章数据也是会经过小书匠服务器**, 对数据比较敏感的建议自己搭建数据中心或者关闭这个功能.


---------

其实如果对数据比较敏感的话,完全可以在私有网络下使用小书匠.

**Comment by suziwen** [comment]
小书匠服务器是放在阿里云上面的.生成的文件是会下载后清理.

**Comment by LonlyPan** [comment]
感谢解答
