### ISSUE TITLE
windows10 一打字光标焦点就跳到下面

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1319]
windows10
小书匠当前版本: 8.0.4(8.0.1)
为什么一打字光标焦点就跳到下面去，这个是 markdown 编辑器的啥标准吗？我发现别的 markdown 编辑器（typora，vnote）也有这问题。
我就想焦点在上面编辑不行吗？
![bug_gif](https://raw.githubusercontent.com/violetu/blogimages/master/bug.gif)

希望大佬可以给解答一下

**Comment by suziwen** [comment]
`设置>编辑器>打字机滚动效果` , 看你当前是使用 ace 编辑器还是 codemirror 编辑器,然后把 `打字机滚动效果` 选项去掉就可以了.

![image](https://user-images.githubusercontent.com/57370/77165811-019c4280-6aee-11ea-95d1-25ecffdf3fe4.png)

![image](https://user-images.githubusercontent.com/57370/77166101-9606a500-6aee-11ea-9ede-f13592d35a0b.png)

**Comment by vio1etus** [comment]
哇，好快，谢谢，谢谢大佬，搞定！
