### ISSUE TITLE
Feature request: 细节优化

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1320]
1. 绑定的第三方存储（本地文件系统）可否重命名，因为有时候会多个文件夹或者linux 和 windows 上切换，分不清那个是那个。

2. 插入 URL 链接： 选中文字，快捷键 ctrl +l， 可以直接获取剪切板链接，然后生成 markdown 格式
可以参考 Typora，记得它好像就是这样。这样快捷键才是真正快捷方便呀。

3. 待办列表，事项，可否给一个 panel， 可以看出当前文件系统（或者至少当前的文件）的待办有哪些（或者至少提示一下，因为有时候不知道有啥待办了emm），并且点击一下，可以定位到对应文章的对应位置，这样便于完成待办事项。

4. 文件重命名，希望支持 F2 快捷键重命名，或者至少可以支持根据原来的文件名重命名。
很多时候，重命名并不想完全修改原名字，只想改一点点而已。
比如: "01.Python_collections" 改成  "02.Python_collections" ， 这时，还需要重新输入有些累。
而且当前的小书匠重命名弹窗不透明，看不见原来文件名字，不好。
总结， 还是像操作系统那样，F2 直接修改好

上面都是一些小细节，希望大佬有时间能否可以优化一下，也不着急。

最后，祝小书匠越来越好！

**Comment by suziwen** [comment]
1.  ![image](https://user-images.githubusercontent.com/57370/77226481-acc2ff80-6bb3-11ea-801c-66b10fae7eb7.png)

----------



`2.  3.   4. ` 项后面再改进

**Comment by vio1etus** [comment]
收到，谢谢大佬！

**Comment by vio1etus** [comment]
> 1. ![image](https://user-images.githubusercontent.com/57370/77226481-acc2ff80-6bb3-11ea-801c-66b10fae7eb7.png)
> 
> `2. 3. 4. ` 项后面再改进

5. 创建 insertSnipaste 的快捷键时，能不能选了 insertSnipaste 命令后，下面的命令参数可以出个下拉框，可以下拉选择 snipaste 的 片段 id（比如: snippet_1578537460214）。这样，就不用回去复制了emm。

当然，有了这功能，体验会更好，没有的话，稍微麻烦点，但也不影响大局。

**Comment by suziwen** [comment]
5. 这个要做的话,估计优先级也会比较低,因为这个并不是高频需求,一般配置一次以后,就基本不会再过来这个页面了.而且我想后面添加一个类似 sublime / vscode 的 `ctrl+shift+p` Command Palette (command prompt) 功能.

**Comment by vio1etus** [comment]
可以可以，加油！

**Comment by vio1etus** [comment]
@suziwen 老哥，
1. 新版本对文件好像还是不能 F2 重命名，F2 在小书匠里面貌似是个啥快捷键。
2. 当本地存储时，能不能在文件的右键菜单中加一个打开文件所在位置的选项呀？
3. 坐等老哥，实现待办事项面板，嘿嘿

**Comment by suziwen** [comment]
点击文件夹是可以 F2, 点击文件的话,因为触发了切换文章,自动把焦点切换到编辑器上面,造成 F2 事件发生在编辑器上,而不是目录树.

**Comment by vio1etus** [comment]
> 点击文件夹是可以 F2, 点击文件的话,因为触发了切换文章,自动把焦点切换到编辑器上面,造成 F2 事件发生在编辑器上,而不是目录树.

那对文件 f2 是不是就不得行了呀？

另外，待办事项我帮老哥找到个 vscode 的插件 https://github.com/TomasHubelbauer/vscode-markdown-todo。没准对老哥实现有帮助？
