### ISSUE TITLE
导出“pdf”时，自动添加了印章式样的水印？

### ISSUE THREAD

**Issue by oukohou** [suziwen/markdownxiaoshujiang#1325]
所添加的水印如图：  
![image](https://user-images.githubusercontent.com/16237619/77716092-38ce9000-6fd5-11ea-9045-0e2fd37204b8.png)

但我是完全没选的：  
![image](https://user-images.githubusercontent.com/16237619/77716160-6582a780-6fd5-11ea-9b05-d36cc55c4ec4.png)

当前版本: 6.7.0，系统win 10 64-bit

**Comment by suziwen** [comment]
联网版 pdf 打印,非会员会被强制添加水印.

**Comment by oukohou** [comment]
> 联网版 pdf 打印,非会员会被强制添加水印.

。。。什么时候加的feature。。。2020-03-03时使用还没有，所以就是这样是吧，不能白嫖了的意思🐼

**Comment by suziwen** [comment]
可以使用客户端本地 pdf / 打印 ,都可以导出 pdf . 或者自己导出成 html ,再使用其他工具转换成 pdf. 

联网版的 pdf 现在会被加水印/印章.

**Comment by oukohou** [comment]
客户端本地 pdf / 打印 得到的pdf感觉对比与联网打印的，观感较差，字体之类都比较丑，能在哪里调整不？

**Comment by suziwen** [comment]
这个需要根据自己本地操作系统安装的字体,然后通过自定义 css 样式来调整.
