### ISSUE TITLE
一个关于“最小化”标签的小bug

### ISSUE THREAD

**Issue by smilelandchr** [suziwen/markdownxiaoshujiang#1327]
[](https://i.loli.net/2020/03/29/MpVDkwYrufzjN7h.png)
[](https://i.loli.net/2020/03/29/neSfaoIPVrR3J7k.png)
[](https://i.loli.net/2020/03/29/fXdzK7F3cIDjV9m.png)

在win7系统下，8.0.4版本，总会在屏幕上留下最小化这个标记，而什么时候能没，目前没有找到规律，bug出现过很多次，但如何复现故障并不清楚，为什么判定是小书匠的bug呢，因为开别的程序，比如网页时候，最小化变迁还依然存在，而在打开小书匠时候，这个标签就消失了，标签出现在小书匠最小化的时候。

**Comment by smilelandchr** [comment]
[https://i.loli.net/2020/03/29/fXdzK7F3cIDjV9m.png](url)
[https://i.loli.net/2020/03/29/F3cZyXU5aueBDY7.png](url)
[https://i.loli.net/2020/03/29/qLoSrZsxhaXYpWA.png](url)

**Comment by suziwen** [comment]
我这边测试了下,没办法重现.

不过下个版本我可以把这个最小化的提示取消掉.
