### ISSUE TITLE
标签问题

### ISSUE THREAD

**Issue by WindFreedomP** [suziwen/markdownxiaoshujiang#1328]
在小书匠中没设置tags，保存印象笔记后自动添加了 小书匠、模板、新建 这三个标签。怎么设置才能在保存时不自动添加这三个标签？

![image](https://user-images.githubusercontent.com/30370449/77877532-98a09180-7288-11ea-8250-aca153a69a33.png)

**Comment by suziwen** [comment]
点击右上角的标题,然后修改标签

![image](https://user-images.githubusercontent.com/57370/77880190-a35e2500-728e-11ea-8876-c52939d1a9c2.png)
