### ISSUE TITLE
有关插入片段会自动换行的问题

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1329]
为什么我写的片段，在插入后会自动换行呢？

**Comment by suziwen** [comment]
贴一下你写的片段,或者能重现的示例片段代码.

**Comment by liao20081228** [comment]
> 贴一下你写的片段,或者能重现的示例片段代码.
`<u>${index}</u>`

**Comment by suziwen** [comment]
还是没法重现, 

你是不是自己定义片段的结尾就是换行的?

![image](https://user-images.githubusercontent.com/57370/78266995-1094e300-7539-11ea-9cb2-97f37af23795.png)


![image](https://user-images.githubusercontent.com/57370/78266909-f6f39b80-7538-11ea-8e4c-542abfa8e850.png)

**Comment by liao20081228** [comment]
> 还是没法重现,
> 
> 你是不是自己定义片段的结尾就是换行的?
> 
> ![image](https://user-images.githubusercontent.com/57370/78266995-1094e300-7539-11ea-9cb2-97f37af23795.png)
> 
> ![image](https://user-images.githubusercontent.com/57370/78266909-f6f39b80-7538-11ea-8e4c-542abfa8e850.png)

还真是多了一个回车。。。。
