### ISSUE TITLE
关于粘贴为markdwon 问题

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1330]
常常在复制网页上一些文章后出现，图中的情况。
总是带着一堆高亮点，能去掉吗？虽说简单正则替换一下即可，但是每次都替换有点麻烦。

![image](https://user-images.githubusercontent.com/33022132/78226733-c131c100-74fe-11ea-9053-a795ed6a4b33.png)

**Comment by suziwen** [comment]
哪个网站上的文字?

我测试 github 上的英文句子, 复制粘贴到小书匠编辑器上,并不会出现你说的情形,感觉这些特殊字符是网站自己本身就有的,跟小书匠无关.

**Comment by vio1etus** [comment]
听老哥一说，感觉好有道理，哈哈。应该不是小书匠问题。

这个，嗷嗷，我以为是常见问题呢，因为我老是遇到，可能是因为我访问的网站啥的都比较乱。 emm

这次是百度文库 https://wenku.baidu.com/view/941008ad33687e21ae45a94f.html 我使用网页复制插件强制复制的。
之前也出现过好几次这种情况（但是我忘了是啥站点或者复制源了）。估计是网站排版的问题。

等我遇到其他出问题的正常站点（百度文库复制毕竟不正常也正常emm），再附上来告诉老哥。
万一小书匠能顺便解决呢，哈哈。

**Comment by vio1etus** [comment]
最近没遇到了，我先关了它。嘻嘻。多谢老哥
