### ISSUE TITLE
能不能增加一个定时自动保存的功能？

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1331]
有时在A写了东西忘了保存，在B上下载同一个文件继续写了，然后再保存。然后再回到A编写，保存。。于是B上保存的不见了。

**Comment by suziwen** [comment]
第三方存储的自动保存功能暂时不考虑,需要用户自己明确触发保存机制(ctrl+s/ 或者点击保存按钮).

因为有些第三方存储并不是纯文本存储,每次保存时需要做大量的计算进行格式转换,附件资源的处理等. 再有就是有些第三方存储还会限制单位时间内的访问次数, 自动存储会加快达到限制次数.

---------------

正常情况下不同的第三方存储,打开的文件即使是相同文件名称,在小书匠内置数据里也是会创建两篇不同的文章.
