### ISSUE TITLE
请教：在hexo的博客上支持小书匠的所有语法

### ISSUE THREAD

**Issue by theblack6688** [suziwen/markdownxiaoshujiang#1332]
请教：自己想在hexo的博客上也支持小书匠的所有语法，是可以实现的吗？如果可以，请问该如何做呢？

hexo 网站：https://hexo.io/
自己使用的是3-hexo主题：https://github.com/yelog/hexo-theme-3-hexo

**Comment by suziwen** [comment]
标准语法两边都可以通用,但一些特殊语法就没办法了.比如有些 hexo 的语法是无法在小书匠上使用,像 `include` 另一个文件. 有些小书匠的语法也无法在 hexo 上使用, 像思维导图语法等.
