### ISSUE TITLE
1.80版本不能绑定到github

### ISSUE THREAD

**Issue by xdsnet** [suziwen/markdownxiaoshujiang#134]
不能绑定到github，设置完全按照要求，但提示“检测失败，使用的token没有找到相应的仓库”

**Comment by suziwen** [comment]
我这边测试没有问题的
![screenshot_2016-02-17_20-47-26](https://cloud.githubusercontent.com/assets/57370/13110701/8b96d4d0-d5bc-11e5-9b08-6a37de8d78dd.png)
![screenshot_2016-02-17_20-45-55](https://cloud.githubusercontent.com/assets/57370/13110702/8b9a667c-d5bc-11e5-8bd8-5c8514b8799e.png)

**Comment by xdsnet** [comment]
我知道原因了，语法问题，我直接输入的https地址，而不是仓库名。
