### ISSUE TITLE
图片存储到sm.ms，不保证那一天图片会丢失，我想的情况是在上传的时候能不能本地同时保存一份勒！

### ISSUE THREAD

**Issue by hyq965672903** [suziwen/markdownxiaoshujiang#1340]
也就是同时开启图床存储和小书匠本地存储  这样的话 图片万一丢失  我自己 这还有一份勒

**Comment by hyq965672903** [comment]
![image](https://user-images.githubusercontent.com/28795893/78954026-60f9db00-7b0d-11ea-9214-a4b853442671.png)

**Comment by hyq965672903** [comment]
![image](https://user-images.githubusercontent.com/28795893/78954377-90f5ae00-7b0e-11ea-8308-82c5164191ed.png)
这个想法  是来源于  shareX这个截图上传软件。保证我们在使用 第三方图床的时候 图片留存一份。

**Comment by suziwen** [comment]
小书匠默认会在关联的文章里保存一份图片的备份,如果图床失效取不到图片,小书匠会尝试从本地关联的图片里找的.可以通过导出 zip 功能,查看备份的图片文件 .

通过这个自动备份的关联图片,当对应的图床失效后,就可以使用小书匠的图片迁移, 快速的进行图床迁移.

-------

自己也可以通过[自定义图床](http://soft.xiaoshujiang.com/blog/images/custom_images_manager)功能,将图片备份到其他位置上

**Comment by hyq965672903** [comment]
点赞  明白了。。  功能强大
