### ISSUE TITLE
小书匠有序无序列表编辑体验差，尤其是多层有序或无序列表时

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1341]
用小书匠希望有序无序列表，以及多层有序无序列表是个极其痛苦的事情。
希望老哥能复刻  vscode 等众多 md 编辑器正常的体验就好。

缺点一: 小书匠序号无高亮
缺点二: 小书匠在序号换行后，不能通过一个 backspace 就删除序号，还需要 3 个 backspace 才行
缺点三: 小书匠在同一个序号块中换行时，不能够自动对齐缩进
总之，希望小书匠按照vscode对有序，无序列表的体验搞过来。

下面是我录制的 gif：
![gif](https://raw.githubusercontent.com/violetu/blogimages/master/xiaoshujiang.gif)

**Comment by suziwen** [comment]
我全新安装的 `1.44.0` 版本,除了高亮和自动缩进,其他的自动编号,快速删除编号应该是装了一些增强的插件,

--------------

目前这些功能都是直接拿 [ace 编辑器](https://ace.c9.io/build/kitchen-sink.html) 默认有的,没有在这基础上进行太多改进.

**Comment by vio1etus** [comment]
> 我全新安装的 `1.44.0` 版本,除了高亮和自动缩进,其他的自动编号,快速删除编号应该是装了一些增强的插件,
> 
> 目前这些功能都是直接拿 [ace 编辑器](https://ace.c9.io/build/kitchen-sink.html) 默认有的,没有在这基础上进行太多改进.

奥奥。可能是我安装的一些插件。不过，希望高亮和自动缩进可以支持哦，尤其是**自动缩进**。自己有时候在进行有/无序列表块换行或者写多层列表时，没自动缩进着实难受
谢谢老哥，老哥加油！

**Comment by vio1etus** [comment]
新版体验很好，多谢老哥
