### ISSUE TITLE
疑问：多标签，同时挂在多个文件系统

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1342]
1. 小书匠是否有计划支持多标签页（多TAB）
2. 小书匠是否有计划支持同时挂载两个文件系统
比如：同时挂载着本地文件系统与印象笔记，方便将印象笔记的内容整理到本地 md 文件中。

**Comment by suziwen** [comment]
1. 多标签目前是做到右上角很多小点的位置上, (可能跟我们一般理解的标签不太一样了)

![image](https://user-images.githubusercontent.com/57370/79035244-2e281380-7bef-11ea-8101-1324652397ef.png)

2. 这个暂时不会考虑,目前只能选择一个默认第三方存储,想存储到其他位置,只能使用 `另存为` 按钮,选择其他第三方存储保存.

**Comment by vio1etus** [comment]
> 1. 多标签目前是做到右上角很多小点的位置上, (可能跟我们一般理解的标签不太一样了)
> 
> ![image](https://user-images.githubusercontent.com/57370/79035244-2e281380-7bef-11ea-8101-1324652397ef.png)
> 
> 1. 这个暂时不会考虑,目前只能选择一个默认第三方存储,想存储到其他位置,只能使用 `另存为` 按钮,选择其他第三方存储保存.

奥奥，原来这些点点是多标签呀，失误失误，看见过它，竟然没发觉emm

其实除了多标签，还想要是有个分屏就好了，就像这样。
![image](https://user-images.githubusercontent.com/33022132/79044448-c6e28180-7c37-11ea-8f45-9a9d5421a324.png)
在修改一些零散文章，整合时，对照着比较舒服。
