### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1343]
![q](https://user-images.githubusercontent.com/25471051/79037765-88809e80-7c06-11ea-93e9-a2eddeeeeaf1.gif)

**Comment by suziwen** [comment]
没看明白这个动画想说什么情况?

**Comment by liao20081228** [comment]
> 没看明白这个动画想说什么情况?

没有看到那个横线吗？那是怎么产生的？？

**Comment by suziwen** [comment]
能把重现的文章发过来吗

**Comment by liao20081228** [comment]
> 能把重现的文章发过来吗

不知道什么问题，我卸载后重装了一次，问题消失了，太奇怪了。文章内容也没变。

**Comment by liao20081228** [comment]
> 能把重现的文章发过来吗

我继续使用看看该问题会不会重现
