### ISSUE TITLE
无法复制markdown或渲染中的图片

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1345]
对于粘贴到markdown中的图片，以链接的形式保存，如果想要复制粘贴到其他地方，只会有链接。我尝试从markdown渲染后的阅读模式中右键复制，也没有这个选项，作者可以考虑添加下这个功能。

**Comment by suziwen** [comment]
你是想把图片复制到剪切板里?

**Comment by AtaraxiaZ** [comment]
是的，因为现在的图片操作相当于是单向的，只能入，不能出。
