### ISSUE TITLE
内容太多时的渲染速度

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1346]
在编辑器中内容（文本和图片等）过多时，渲染会花一定的时间，这样会导致编辑器中的输入字符产生些卡顿，按照我猜测的逻辑，是因为每在编辑器中添加一个东西，预览部分就会全部重新渲染一遍，然后编辑器才能做新的更改。是否可以只渲染部分内容，因为大部分的内容是没有更改的（只是更改了几个字符而已）。如果这样不行的话，或许可以让编辑器的部分和预览部分异步执行，不需要等待预览结束后才能在编辑器敲击下一个字符。这个问题现阶段也可以解决，比如进入只编辑状态，就不会出现卡顿问题了

**Comment by suziwen** [comment]
局部渲染和独立进程进行渲染都有想过,不过一直在研究中,因为要对整个代码逻辑进行重新设计,就没有比较明确的实现安排.

目前建议是不要把太多内容放在一篇文章里,或者文章内容太多时,关闭预览功能.

**Comment by AtaraxiaZ** [comment]
已解决
