### ISSUE TITLE
现在进入阅读模式和进入写作模式都闪退

### ISSUE THREAD

**Issue by cyberbug-yang** [suziwen/markdownxiaoshujiang#1347]
点击就闪退，自从升级到8.01版本后，就这样。其后每次升级都一样，还是闪退。操作系统版本 mac os Catalina 10.15。小书匠7.X版本无此问题。

**Comment by cyberbug-yang** [comment]
用这个命令走命令行打开解决了问题。
open /Applications/Story-writer.app --args --disable-features=nw2

**Comment by qingchuwudi** [comment]
Got the same problem.

**Comment by suziwen** [comment]
@qingchuwudi @cyberbug-yang 

也可以下载这个版本试试

https://github.com/suziwen/markdownxiaoshujiang/releases/download/v8.0.1/Story-writer-osx64-fix-fullscreen.zip

**Comment by cyberbug-yang** [comment]
> @qingchuwudi @cyberbug-yang
> 
> 也可以下载这个版本试试
> 
> https://github.com/suziwen/markdownxiaoshujiang/releases/download/v8.0.1/Story-writer-osx64-fix-fullscreen.zip

这个版本没有全屏闪退问题了。但它也能正常升级吗？现在最新的正常版本已经是8.0.7了

**Comment by suziwen** [comment]
@cyberbug-yang  可以正常升级的
