### ISSUE TITLE
webdav方式远程存储支持

### ISSUE THREAD

**Issue by zhengmingliang** [suziwen/markdownxiaoshujiang#1354]
话说能不能支持一下webdav协议啊，现在很多笔记软件都支持通过webdav备份和恢复，然后如果小书匠可以也支持webdav的话那就更完美了

**Comment by suziwen** [comment]
大体看了下这个协议, 应该没问题,后面会考虑添加进来.

**Comment by zhengmingliang** [comment]
> 大体看了下这个协议, 应该没问题,后面会考虑添加进来.

好嘞

**Comment by CharMingF** [comment]
> 大体看了下这个协议, 应该没问题,后面会考虑添加进来.

安排上了，但是不会用呢？没有说明嘛？在哪里添加的功能？导出？绑定?

**Comment by suziwen** [comment]
@CharMingF 
就是可以自己搭建一个 webdav 服务器,或者使用第三方提供的 webdav 服务, 比如 

*   [ownCloud](https://owncloud.org/) 
*   [Nextcloud](https://nextcloud.com/) 

然后在`绑定`页面上选择 `webdav 服务`, 输入服务器地址,用户名,密码等相关信息.后面的操作跟绑定 github ,gitee 等相同了


----------

注: 如果想在 web 版本小书匠上使用 webdav 第三方存储,记得正确配置跨域问题.


--------


自己搭建 webdav 的话,可以自己拿 docker 的一些镜像,比如 https://hub.docker.com/r/bytemark/webdav

下面的链接,记录的是我这几天研究 webdav 的笔记,也可以看看,可能不全.

https://suziwen.github.io/acorns/daily-notes/2020-04-28
https://suziwen.github.io/acorns/daily-notes/2020-04-29

**Comment by vio1etus** [comment]
@CharMingF 如果是小白的话，可以用坚果云，坚果云官网有类似配置教程。
