### ISSUE TITLE
8.0.8新出的待办总表能否导出？

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1355]
新出的待办列表十分方便，能一目了然看到目前自己的任务状态，自己目前用来做周报非常的方便，现有筛选功能了，能够一键导出或者选择就好了，目前好像不是独立的，全选会选择到全部文档内容。

另外，一个小bug，不影响，但是有点强迫症，如下，不小心把待办列表框移动上面去了，就无法关闭了，还好缩放了浏览器通过按钮关闭了，不是什么问题。

![image](https://user-images.githubusercontent.com/7530342/80306964-d1387a00-87f8-11ea-85b1-11d4078f1934.png)

**Comment by suziwen** [comment]
1. 现在还不能导出,后面会考虑添加进去.
2. 这个现在没有做边界范围控制,不过可以通过点击 `待办列表视图` 按钮,关闭这个界面,再点击,显示时就会重新定位位置.

**Comment by CharMingF** [comment]
作者太给力了，响应太迅速，不愧是我第一爱编辑器。
