### ISSUE TITLE
导出至印象笔记，公式太小

### ISSUE THREAD

**Issue by anony-ghost** [suziwen/markdownxiaoshujiang#1356]
![image](https://user-images.githubusercontent.com/59722503/80774665-3640f680-8b90-11ea-93f4-fd342ac5309c.png)
如图， 这是同一个文档中的公式，大小不一致，太小了。。。。请问该如何解决呢？
看到之前的评论，说设置.MathJax_SVG ，请问具体该怎么操作呢？
感谢！

**Comment by anony-ghost** [comment]
我发现原因了，公式后面用\tag{*}加编号，就会出现这种情况。。。

**Comment by suziwen** [comment]
这是因为有编号的公式,生成的图片比较宽,当在宽度不够的屏幕里,文章图片会自动缩小,造成图片整体变小.这个暂时没有比较好的解决方案,只能像你提到的,取消编号.

**Comment by suziwen** [comment]
最新的 [web](http://markdown.xiaoshujiang.com) 版本对带编号的公式做了调整，现在保存到印象笔记后，这些公式应该也能正常显示了。
