### ISSUE TITLE
mathjax公式显示异常

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1357]
有一条公式很奇怪，在mathjax!的那种格式下渲染不出来公式。而我试过其他公式，是没问题的，就这一条有问题，我用在线latex网站测试又可以正常显示，公式为：$$H(\mathscr{S}) \leqslant \frac{\bar{L}_{n}}{n}<H(\mathscr{S})+\frac{1}{n}$$，是mathjax本身的问题吗？

**Comment by suziwen** [comment]
确认 bug, 感谢反馈.
