### ISSUE TITLE
哪个编辑器好用呀？好难呀

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1359]
CodeMirror 编辑器没有高亮。

![image](https://user-images.githubusercontent.com/33022132/81364708-e8d90200-9118-11ea-9f52-e4cb01266447.png)

Ace 编辑器没有自动预览图片和 checkbox

![image](https://user-images.githubusercontent.com/33022132/81365842-d57b6600-911b-11ea-818d-70d705fedc6e.png)

**Comment by suziwen** [comment]
Codemirror 有高亮的,你可以在 Codemirror 编辑器下切换不同的主题试试.

有些主题高亮设置得比较简洁,有些设置得比较具体化.


![image](https://user-images.githubusercontent.com/57370/81367656-6f451200-9120-11ea-8654-b9fa7c5ef472.png)

**Comment by vio1etus** [comment]
ACE 的 Halflife Contract 主题
![image](https://user-images.githubusercontent.com/33022132/81370367-8dfad700-9127-11ea-974d-e300ec0c0f0e.png)

Codemirror 的 Halflife Contract 主题

![image](https://user-images.githubusercontent.com/33022132/81370414-abc83c00-9127-11ea-973d-ee96f054f1ad.png)

再来一张Codemirror 的 Halflife Contract 主题

![image](https://user-images.githubusercontent.com/33022132/81370604-24c79380-9128-11ea-9d62-bbc310cd6abd.png)

而且 Codemirror 有的标题会高亮有的不会，就很奇怪。

感觉 Codemirror 高亮和 ace 差很多，Codemirror  的高亮有点想高亮哪儿，高亮哪儿的随机感（/苦笑）。 Codemirror 瞎高亮，该亮的不亮，不该亮的都是亮了 

希望 ace 编辑器支持预览图片和 checkbox，然后我就放弃 Codemirror 了

**Comment by suziwen** [comment]
ace 的后继开发会越来越少的.现在主要还是 Codemirror , ace 只是备用, 像纯文字表格的对齐等,在等宽字体下显示效果就比较好.

目前主推 codemirror 是因为这个不受等宽字体的限制.扩展比较方便.


高亮这块两边的内部解析不一样, 有些样式在 ace 下适配得比较好,有些在 codemirror 下表现更好.

而且我看你的截图很奇怪,为什么你的 Codemirror 下 的 Halflife Contract 主题里标题没有高亮,而我的有高亮,感觉也跟你的正文内容也有些关系.

![image](https://user-images.githubusercontent.com/57370/81371183-bbe11b00-9129-11ea-9aba-a3d52922daae.png)

**Comment by vio1etus** [comment]
![image](https://user-images.githubusercontent.com/33022132/81375119-6578da00-9133-11ea-9d30-639ae7a63ec1.png)

![image](https://user-images.githubusercontent.com/33022132/81375143-745f8c80-9133-11ea-94e2-55d0b5ab1adc.png)


“高亮这块两边的内部解析不一样, 有些样式在 ace 下适配得比较好,有些在 codemirror 下表现更好.”

我感觉不都是这样啊，不只是内部解析不一样。而且在 ace 编辑器下绝大部分主题都高亮的很好，而CodeMirror 下，我试了好多，没有找到正常高亮的。
 
比如: ace 下 一个主题的高亮
![image](https://user-images.githubusercontent.com/33022132/81375840-f0a69f80-9134-11ea-80f0-1b8a1b7ca547.png)


CodeMirror 连**基本正常**和自己**上下文一致**的高亮都做不到。

我也很奇怪，这两个是同一个文件，有的标题就高亮，有的就不高亮

如果需要我可以把 md 文件发给你？

**Comment by suziwen** [comment]
可以发一份到 suziwen1@gmail.com

标题不高亮, 我估计原因是 你使用了 `<pathspec>` 这种带 `<` 符号的文字,  codemirror 把他识别为 html 的一部份进行了高亮, ace 编辑器只是把他做为普通的文字来处理.

建议将 `<pathspec>` 这种文字用 `` ` `` 符号包裹起来, 比如这样 `` `<pathspec>` `` , 因为像你那样的写法是有些不规范的, 有些第三方的编辑器或者网站,会把 `<pathspec>` 当成非法的字符串,不进行显示, 比如 github , 你输入下面的文字

```
<pathspec> sdfdf
```
github 的预览是不会有 `pathspec` 内容的

**Comment by vio1etus** [comment]
ok，已发送

**Comment by suziwen** [comment]
就是我上面提到的原因https://github.com/suziwen/markdownxiaoshujiang/issues/1359#issuecomment-625650467 , 你的 `<pathspec>` 被当成 html 片段识别了

替换前

![image](https://user-images.githubusercontent.com/57370/81377688-9b6c8d00-9138-11ea-81f0-d30dd7199409.png)

替换后

![image](https://user-images.githubusercontent.com/57370/81378012-1cc41f80-9139-11ea-9320-471bd63548dd.png)

**Comment by vio1etus** [comment]
这就尴尬了emm 
![image](https://user-images.githubusercontent.com/33022132/81378545-0ec2ce80-913a-11ea-8c2d-cfe8289478b3.png)
