### ISSUE TITLE
右键,在文件夹中打开这个功能失效？

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1360]
右键,在文件夹中打开这个功能,点击后没有反应。
![image](https://user-images.githubusercontent.com/33022132/81366420-30618d00-911d-11ea-8d84-c9fe3e6c0711.png)

小书匠版本: 8.0.10
windows 版本
![image](https://user-images.githubusercontent.com/33022132/81366475-5850f080-911d-11ea-8037-6a42d3af370f.png)

**Comment by suziwen** [comment]
我这边正常,没有出现你说的情形.

**Comment by suziwen** [comment]
知道原因了,window 下只测试了根目录,其他子目录没有测试到.

**Comment by vio1etus** [comment]
果然，根目录可以。OK，谢谢大佬

**Comment by vio1etus** [comment]
赞，不愧是你，太强了，这么快就更新了。
