### ISSUE TITLE
超链接问题

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1361]
1. 关于对文字添加超链接的快捷键可否做得再快捷一些？就像一般的 md 编辑器，如: typora，vscode，cmd等，只需要一个快捷键，便**直接**生成了 markdown 格式的超链接。
目前小书匠 ctrl+l，之后，虽然会自己获取剪切板了，但是还是会弹出超链接窗口，需要多点击一下确认才行。

2. 超链接是否在 codemirror 的编辑器下就能点击，从而浏览器打开呢？
           这个可能不是体验的刚需，不实现也罢。

**Comment by suziwen** [comment]
1. feature
2. 这个鼠标移到链接上有个 chrome 的图标,这个就可以直接在浏览器上打开的


![image](https://user-images.githubusercontent.com/57370/81489158-1783e380-92a5-11ea-899a-ade31ad62d65.png)

**Comment by vio1etus** [comment]
ok，谢谢老哥

![image](https://user-images.githubusercontent.com/33022132/81489575-911dd080-92a9-11ea-8615-a90ce596da1a.png)

**Comment by suziwen** [comment]
1. `8.0.12` 版本后, 可以看下这个[功能](http://soft.xiaoshujiang.com/docs/tutorial/snippet_script_context/#e887aae58aa8e588a4e696ade589aae58887e69dbfe58685e5aeb9e5b9b6e689a7e8a18ce4b88de5908ce8be93e587ba_16)

**Comment by vio1etus** [comment]
好的，我通过该功能实现了 ctrl +l 快捷输入剪切板超链接的功能，配置如图:
![image](https://user-images.githubusercontent.com/33022132/81493423-c985d480-92d2-11ea-9213-3fbf9b2ddd2b.png)

而且通过此功能的 `<%=clipboardText%>` 参数也实现了从 ppt 中复制过来，粘贴纯文本的功能

(虽然会首尾有时候会多一些空格，如果老哥能告诉我一下，如何实现类似 python 中 strip 函数去除首尾 whitespaces 的效果就更好了。)

**Comment by suziwen** [comment]
可以使用 $.trim 或者 trimStart, trimEnd等方法

```
<% if ( /^http[s]?:\/\//i.test($.trim(clipboardText))) { 
print("["  + editorSelectionText + "${cursor}](" + $.trim(clipboardText) + ")");
} else {%><%=$.trim(clipboardText)%>${cursor}<%}%>
```

**Comment by vio1etus** [comment]
好的好的，Thank you！

**Comment by vio1etus** [comment]
> 1. feature
> 2. 这个鼠标移到链接上有个 chrome 的图标,这个就可以直接在浏览器上打开的
> 
> ![image](https://user-images.githubusercontent.com/57370/81489158-1783e380-92a5-11ea-899a-ade31ad62d65.png)

emm，还有些小的问题，

1. windows 下 CodeMirror 编辑器，貌似鼠标移到链接上没有 chrome 的图标？（我装着 chrome 呢）
是有设置这个的开关吗？

![1](https://user-images.githubusercontent.com/33022132/81499644-96a60580-92ff-11ea-847f-e777ab3ea967.gif)

2. 还有 md 文件之间的内部链接跳转，在 Windows 的 codeMirror 也没有 图标。（预览的时候可以跳转）
![image](https://user-images.githubusercontent.com/33022132/81500140-a83cdc80-9302-11ea-98d3-fe29b6009fe1.png)

3. md 文件之间的内部引用链接跳转到被引用文件之后，再回去原文件(引用文件)，可以让光标回到原文件(引用文件)设置的该引用的位置吗？

这两天找论文，看论文，做笔记，作报告，用小书匠用的比较深度，所以问题有点多，希望老哥多担待。 Thank you！

**Comment by suziwen** [comment]
1,2. 你给我的那个测试高亮的文件里的链接也不能点击吗? 把`设置>编辑器>codemirror编辑区` 里的配置截个图看下.

![image](https://user-images.githubusercontent.com/57370/81517983-2f279e80-936f-11ea-9e99-3776dece398a.png)

3. 你是通过什么方式,从被引用文件跳回原文件的.通过文件列表的文件切换,我记得是会记住上次鼠标位置的.如果是通过链接关系图切换回原文件, 也是会跳到原引用位置的.

![image](https://user-images.githubusercontent.com/57370/81518426-98f47800-9370-11ea-9b23-897992fbc79c.png)

**Comment by vio1etus** [comment]
1. 不能，那个测试高亮的文件里的链接也不能点击
![image](https://user-images.githubusercontent.com/33022132/81520648-7a45af80-9377-11ea-9c07-594296739b6c.png)

![image](https://user-images.githubusercontent.com/33022132/81520525-2a66e880-9377-11ea-85e0-e762e97e29ee.png)

2. 你是通过什么方式,从被引用文件跳回原文件的：
奥奥，原来是我的姿势不对，我是通过 
![image](https://user-images.githubusercontent.com/33022132/81520794-d577a200-9377-11ea-9fd1-c316e2c5ad6c.png)返回的。

通过文件列表的文件切换或者通过链接关系图切换回原文件, 确实都会跳到原引用位置，OK

不过，我发现引用点击跳转在 CodeMirror 里也不行，得去链接关系图或者预览点击跳转

**Comment by suziwen** [comment]
确认bug,  可以先把那个英文语法检测关掉,链接就能正确出现点击图标.

**Comment by vio1etus** [comment]
果然，关掉它，就可以了。好耶！
![image](https://user-images.githubusercontent.com/33022132/81522202-3f924600-937c-11ea-8661-415c7349390b.png)
