### ISSUE TITLE
文件大纲问题

### ISSUE THREAD

**Issue by WindFreedomP** [suziwen/markdownxiaoshujiang#1362]
8.0.1版本
预览界面的文件大纲点击后不能跳转

**Comment by WindFreedomP** [comment]
还有一个问题不知道能不能解决，就是设置为只读保存到印象笔记后，在印象笔记中阅读的过程中还是会被修改。

![image](https://user-images.githubusercontent.com/30370449/81772563-cb40d980-9518-11ea-9a0c-85af9104fe28.png)

**Comment by suziwen** [comment]
1. 这个确认 bug, web 版本已经修复,客户端版本要在下一个版本再发布.

2. 这个只读功能是印象自己设定的,如果印象自己想强制修改那是没办法的.
