### ISSUE TITLE
已经确保token正确，仓库名称正确，仓库里有描述文件Readme.md，但是还是不能正确添加配置并报错

### ISSUE THREAD

**Issue by Lucacaa** [suziwen/markdownxiaoshujiang#1363]
![2](https://user-images.githubusercontent.com/56707250/81904812-5fcd3980-95f6-11ea-97c6-fab82249b5dd.png)
如图，已经确保token正确，仓库名称正确，仓库里有描述文件Readme.md，但是还是不能正确添加配置并报错。小书匠版本1.12（学校里电脑是xp），不知道是不是版本老的原因。

**Comment by Lucacaa** [comment]
![3](https://user-images.githubusercontent.com/56707250/81905346-2b0db200-95f7-11ea-97a5-ee118e232d40.png)
看了下日志文件，貌似是系统浏览器太垃圾，解析不了github的ssl证书的版本。。xp不行了啊。。。

**Comment by suziwen** [comment]
这个看起来,感觉是你的机子访问不到 github 服务器.

也有可能就是你说的情形, github 的 ssl 证书解析不了.
