### ISSUE TITLE
图片闪烁问题

### ISSUE THREAD

**Issue by yangxinyi-bigdata** [suziwen/markdownxiaoshujiang#1364]
在内容中添加了图片之后,每在内容中增加几个字,右侧预览栏就会重新渲染一次,添加的图片就会跳动一次.
这个问题导致添加了图片之后,右侧非常干扰注意力,而且很晃眼睛,不知道是否都存在这个问题呢?

希望能够解决一下

**Comment by yangxinyi-bigdata** [comment]
这个软件用的逻辑是不是编辑内容的时候应该把右侧预览栏关掉?
但是我想要参照图片上面的内容,编写内容啊,关掉预览就看不到图片了

**Comment by suziwen** [comment]
这个现在是全部重新渲染，所以会抖动闪烁。

后续会考虑改进这一块。

**Comment by suziwen** [comment]
#1346
