### ISSUE TITLE
SMMS图床无法使用，望排查

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#1365]
SMMS图床绑定成功后，实际转换图床或插入图片时显示“上传失败”，链接不变。SMMS v2绑定时显示“测试图片上传失败”，无法绑定使用。望排查，谢谢。

另外刚开始用，请问下绑定的印象笔记导出为md文件时只有文本，没有图片附件，这是正常的吗？或者如何解决呢？非常感谢。

**Comment by suziwen** [comment]
2. 小书匠不要安装在有中文的文件夹下，最好是英文的

**Comment by ghost** [comment]
本地安装是纯英文路径，出现此问题。在网页端试了依旧如此…才来问的。

**Comment by suziwen** [comment]
1. smms v1 版本官方 api 已经禁止使用. 
2. smms v2 的问题, 因为 smms 官方禁止了跨域调用 api, web 版本无法使用. 现在只能在小书匠客户端使用
3. 如果连网页版本的小书匠保存到印象笔记也只有一个 md 文件的话, 可能跟你的文章内容有关系,或者自定义了 css 样式? 你试着在隐身模式下,新建一篇简单点的文章,然后保存到印象笔记呢?

**Comment by ghost** [comment]
图床的情况了解啦，谢谢。
网页版新建使用小书匠自带的图床，保存至印象笔记能显示图片，但对应的md文件、在网页直接导出为md都是没有附件的，不知道是我这里的问题还是方法不对……我再研究一下。
感谢答疑！这个应用连接如此多真的是太好用了，非常感谢~

**Comment by suziwen** [comment]
我好像明白你的意思了,你是想导出小书匠的 md 文件里,包含那些上传的图片?

这个可以使用小书匠的导出 zip 功能, 里面包含了所有相关的图片,绘图组件(drawio)和其他附件.

**Comment by ghost** [comment]
对的，原来如此。成功了，非常感谢！~
