### ISSUE TITLE
搜索优化

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1366]
1. 一个都搜不到， 为啥还 17/17

![image](https://user-images.githubusercontent.com/33022132/82142770-526fb380-9871-11ea-89f0-564bfce672d8.png)

2. 如果有，为啥搜搜出来的老在最后一行，不能在中间或者当前页面的首行吗？让人很是恼火
最后一行，不方便看
![image](https://user-images.githubusercontent.com/33022132/82142871-36204680-9872-11ea-8676-b50790915e5d.png)

**Comment by suziwen** [comment]
1.  把能够重现的文章发到我邮箱，suziwen1@gmail.com

2. 这个是按照如果查找的词，不在可视区域，就按照搜索的方向滚动，如果是下一项，就出现在最后，如果是向上搜索，就出现在页面首部位置。

**Comment by vio1etus** [comment]
## 1. 搞懂了为啥这样？
不用特定文章，任意文章即可复现。
复现步骤:
1. 首先，搜一个文章中有的关键字，然后可以看个数等，比如: 7 个，然后你点下一个，比如：变成了 2/7， 很正常吧
2. 然后搜索一下，再再该文章中搜索一个没有的关键字，并回车。奇怪的事情发生了，还是 2/7

## 2. 这个方式能改改吗？
老在最后一行显示emm，有时候把小书匠窗口调整的时候，最后一行比较靠下，看不见。
我使用 vscode ，就不是那样子。

复现 gif 有点大，github 上传不了，已发邮箱

**Comment by suziwen** [comment]
感谢反馈
1. 确认 bug
2. 后面会优化下.

**Comment by vio1etus** [comment]
ok，谢谢
