### ISSUE TITLE
Github图床无法访问

### ISSUE THREAD

**Issue by i-mine** [suziwen/markdownxiaoshujiang#1367]
之前可以正常使用，突然所有的图片都不能显示了
![image](https://user-images.githubusercontent.com/24563047/82205385-1c960200-9939-11ea-8110-5763ae244dd1.png)

**Comment by i-mine** [comment]
换了新的Token也不行

**Comment by suziwen** [comment]
你这个 MyNote 不是公开可以访问的?

图床服务需要公开可以访问的仓库.

**Comment by i-mine** [comment]
好吧，之前private也是可以的，也就最近突然不行了，我改成public了

**Comment by suziwen** [comment]
private 可以,是因为小书匠提供了一套缓存, 当清空, 或者换一台电脑,或者把文章复制到其他编辑器时,这些图片都会看不到的.

如果想使用 private 仓库的话,不建议使用图床, 而是直接绑定 private 仓库,并选择做为默认的第三方存储, 这样保存文章时, 上传的图片都会在这个 private 仓库里, 图片是以相对链接的形式保存到 private 仓库里.
