### ISSUE TITLE
bug: Win10 v2004 ，重启后，恢复小书匠关机前的任务后，无法关闭小书匠，必须任务管理器结束

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1369]
bug: Win10 v2004， 设置重启后恢复之前任务后。

重启后，恢复小书匠关机前的任务后，都正常。然后想要关闭/退出小书匠，
![image](https://user-images.githubusercontent.com/33022132/82274077-c44f1680-99b1-11ea-8b42-d2b22f725cfa.png)

但是 "退出" 失效，无法关闭小书匠，必须任务管理器结束

已遇到 3 次

**Comment by suziwen** [comment]
`恢复小书匠关机前的任务后` 这个是什么操作?

**Comment by vio1etus** [comment]
就重启后，小书匠自动就启动/恢复了，然后显示出窗口，窗口里是关机前的那个文章吧？ 我没仔细看

**Comment by suziwen** [comment]
你是指电脑体眠后,重启自动打开系统重启前的应用了?

**Comment by vio1etus** [comment]
> 你是指电脑体眠后,重启自动打开系统重启前的应用了?

![image](https://user-images.githubusercontent.com/33022132/82278369-9cb17b80-99bc-11ea-9929-75285ee3a053.png)
是关机之后，再启动，自动打开系统重启前的应用了。嗯，不过这不是 bug。可以在 windows 里设置
bug是 小书匠退出不了了，
![image](https://user-images.githubusercontent.com/33022132/82278450-cff40a80-99bc-11ea-8420-6870e05d22bc.png)
这个 退出不管用了。
