### ISSUE TITLE
Firefox中编辑器打字的乱码问题

### ISSUE THREAD

**Issue by waldens** [suziwen/markdownxiaoshujiang#137]
首先感谢小书匠作者。

Chrome完全正常。Firefox即使恢复到安全模式下（扩展全禁），也会有乱码
选项- 字体 中已设置和勾选 允许页面选择字体
不知哪儿还有问题呢？

![截图](http://ww2.sinaimg.cn/large/d80a8e60gw1f19pjyopy4j20bs08b0u2.jpg)

**Comment by suziwen** [comment]
这个是使用了 ace 编辑器 引起的，不过测试了下，按下空格键后能够正常选字，应该没有影响。或者可以选用轻量编辑器。目前正在考虑实现切换到 codemirror 编辑器中，所以暂时就先放着了。

**Comment by waldens** [comment]
@suziwen 明白了，谢谢：）
