### ISSUE TITLE
链接功能简化

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1372]
最近新出了一款新型的笔记软件:Roam Research。其具有bi-directional linking（双向链）的功能。
简单说就是笔记的双向引用，你在一篇链接中引用了另外一篇笔记，那么另外一篇自动的会和这篇关联起来，并且打开另外一篇也能够看到这篇中的内容。

同时也具有可视化网状图功能，就是链接关系的可视化。

给早已略显饱和沉静的大纲类笔记软件圈子带来了新鲜的玩意。

实际上上述两者，小书匠已经有了部分功能，在前些时间的更新中增加了笔记引用的功能。不知道是作者也知道了，还是偶尔为之。

但是目前使用中觉得可以做的更好的地方，就是语法稍显繁琐，另外则是没有双向引用的功能。

对于小书匠编辑器不一定说要什么都要做，但是我觉得可以把现有的稍微提高一点，比如这个语法可以借鉴目前前面提到的软件，直接采用[[笔记]]来链接整个笔记，用((笔记段落))来链接笔记段落。

这样配合快捷键及片段功能，也可以基本实现了链接的快捷使用。

至于，双向链接，是希望作者考虑下，就是在引用的笔记中也回引用笔记，显示在一个窗口中（类似大纲的窗口）。

具体，这个下面软件可以参考，也是markdown编辑器。

http://einverne.github.io/post/2020/05/obsidian-note-taking.html

**Comment by suziwen** [comment]
其实大部份功能, 应该就是 小书匠的 [链接关系图](http://soft.xiaoshujiang.com/docs/tutorial/internal_link/#e993bee68ea5e585b3e7b3bbe59bbe_7)功能 , 在很早就有用户提这个需求的 #1196


![image](https://user-images.githubusercontent.com/57370/82724655-36a15d00-9d0a-11ea-8560-ad27d29e6cd7.png)

双击关系图的文章,就会将当前编辑的文章切换到对应的文章上, 双击关系图上的标签,就会在左侧的文章列表里过滤出该标签下的所有文章.



后继版本会添加一个反向链接过滤器, 将当前文章被哪些文章引用过的,把这些文章在左侧的列表里显示出来.


--------------

小书匠不打算使用 `[[]]` 或者  `(())` 这种语法,主要是想尽量兼容标准的 markdown 语法, 这样用户在使用其他编辑器时,也能很方便的兼容显示, 不丢失链接跳转的含义.

**Comment by CharMingF** [comment]
嗯,好的,明白,兼容确实也是一个考虑的问题.但是这个可能是一个笔记的趋势吧,实际我想说的是,小书匠也有自己不兼容的语法啦,比如公式就独立的语法,还有脚注,多一个不兼容的也可以的,哈哈,我自己的感觉哈.

**Comment by suziwen** [comment]
可能没讲清楚,就是普通的 markdown 语法里 ,`[]()`就可以实现 文章之间的跳转,就不想再增加一个 `[[]]`  或者 `(())`这种格式了.

不过你也说得对,小书匠已经有很多独立的语法了,再加一个也是不差这一种的. 只是现在小书匠语法太多 :smile:  , 有点爆炸了, 先尽量克制,如果将来这种 wiki 式的引用语法 `[[]]` 在 markdown 里普遍被接受的话,也是会考虑添加进来.

**Comment by suziwen** [comment]
`8.4.12` 版本添加了 wiki 链接语法

**Comment by CharMingF** [comment]
> `8.4.12` 版本添加了 wiki 链接语法

太牛了！
