### ISSUE TITLE
想法: 美观优化？功能简化？

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1375]
这里面有个人审美/追求简洁、美观的偏见，勿喷。
只说一下，自己用了一段时间的想法，有些方面如果觉得可以，老哥可以改进小书匠一波。

老哥回复一下，我就关 issue 了

1. 整体界面
说起整体界面与美观， 老哥可以去看 Mweb bootnote notable Simplenote 之类的，一眼看上去，供嗯强大但是很整洁美观。
我也和同伴们推荐小书匠，但是好几个一看界面，再看功能之繁复，便劝退不再使用了。
我慢慢也感觉一个好的 UI 和主题可确实以让人心情娱乐，写作舒畅。

2. 主题
虽然小书匠主题之多，但是很杂乱。其实我没有找到一款类似 vscode 或者和上面提到的几款 markdown 编辑器主题的一款看上去整洁典雅的主题。
个人偏爱深色系主题，而小书匠的深色系主题，白色字体貌似都很显眼（难受）,还有别的高亮之类的

3. 启动相对慢
4. 强化高度书写体验的功能快捷键还欠缺
比如: 自己写的 markdown 表格格式化
批量增加序号
有无序列表书写体验等
一些细节的地方。
5. 预览
现在展示预览 markdown 一般用 typora，原因有 2:
1. 直接就是预览页面
2. 美观
3. 预览的时候，还有标题大纲

很遗憾截至今日，我发现小书匠已经不是我的主要编辑器/知识管理工具了，目前主要是用小书匠的导出功能。
当然， 小书匠的优点是多的说的说不清的。

**Comment by suziwen** [comment]
优化肯定会优化, 只是要一个过程.

其实如果能提供一些细节上的改进建议,而不是比较概括笼统的说法,那就更好了.比如说界面上的改进吧,要是能贴个截图, 描述说明对比下,就更好了. 还有可能不同的电脑,显示器,显卡不一样,显示出来的效果也会差别很大.

再一个就是启动速度了.虽然我在自己电脑上使用时,感觉启动速度还是可以接受, 但用户环境多样, 不代表他们启动速度也跟我一样. 因为能测试的环境比较有限, 目前也只能慢慢推进,还有就是改代码内部的启动逻辑,涉及的细节比较多, 进度也不会很快.

最后, 就是非常非常感谢,帮忙推荐那么多用户,虽然很遗憾, 可能最终想使用的用户很少. 不过也不必纠结于小书匠这个软件, 如果觉得其他软件确实更适合你的知识管理的话,断舍离还是需要的.
