### ISSUE TITLE
表格内的公式渲染后会出现自动换行的问题

### ISSUE THREAD

**Issue by JingofXin** [suziwen/markdownxiaoshujiang#1376]
当预览窗口较小，表格内的公式渲染会自动换行。
目前只能把预览窗口拖大，表格内的公式重新渲染后才会在同一行。

有没有办法使得表格内的公式不会自动换行？
如下图所示：
![2020-05-29_17-32-33](https://user-images.githubusercontent.com/31361630/83244890-939d8700-a1d2-11ea-9d83-3efe786842ac.jpg)

**Comment by suziwen** [comment]
通过自定义 css 样式,指定表格的宽度

**Comment by JingofXin** [comment]
> 通过自定义 css 样式,指定表格的宽度

我设置了这个还是不管用：
  table {
    table-layout: fixed;
    width: 100%;
  }

**Comment by suziwen** [comment]
因为主题使用了 `.table` , 需要用  `.table` 名称代替 `table` 来覆盖主题的样式定义.

再一个就是 width 设置成 `100%` ,就变成了跟随窗口大小变化, 也就是跟默认的一样了. 可以设置一个固定值, 比如`800px;`

类似这样


```
.table {
    table-layout: fixed;
    width: 800px;
}
```

**Comment by JingofXin** [comment]
谢谢。已按建议方法设置CSS。但表格所有列的宽度一致了。而且如果宽度固定值设置不合理，该问题还是会出现。
![2020-06-01_14-52-05](https://user-images.githubusercontent.com/31361630/83383740-50ccf080-a418-11ea-825c-4b62c3f8d41b.jpg)
有个疑惑是：在渲染输出最后结果的前一秒，有一个渲染结果。该结果是不会让公式自动换行的，**无论是否设置了CSS**，但这个结果转瞬即逝，立马被覆盖。如下图所示：
![2020-06-01_15-03-29](https://user-images.githubusercontent.com/31361630/83384323-a229af80-a419-11ea-82a1-628f29b0a65b.jpg)

可尝试以下Markdown文本（在实时预览窗口较小下会出现该问题，笔记本二分屏后就较小了。）
```
|名称|代码|效果|注意与说明|
|:-:|:-:|:-:|:-:|
|小括号|(a)|$(a)$|无转义|
|小括号|\left(\dfrac{x^3}{y^7}\right)|$\left(\dfrac{x^3}{y^7}\right)$|自适应大小的括号，使用\left,\right|
|小括号|P\left(A=2\middle\|\dfrac{A^2}{B}>4\right)|`!$P\left(A=2\middle|\dfrac{A^2}{B}>4\right)$`|自适应大小的括号，使用\left,\right,中间可用\middle\||
|中括号|[a]|$[a]$|无转义|
```

**Comment by suziwen** [comment]
这个是 mathjax 做自动换行处理, 当发现空间不够,就自动换行.


------------

不想所有的表格都变化的话, 
也可以在单元格内的前面添加个 `<!-- {.custom_width} -->`  [属性配置](https://github.com/rstacruz/markdown-it-decorate), 然后通过自定义 css 样式, 给单元格指定一个宽度.

```
.custom_width{
min-width: 200px;
}
```
完整的 markdown 文本 

```
|名称|代码|效果|注意与说明|
|:-:|:-:|:-:|:-:|
|小括号|(a)|$(a)$|无转义|
|小括号|\left(\dfrac{x^3}{y^7}\right)|$\left(\dfrac{x^3}{y^7}\right)$|自适应大小的括号，使用\left,\right|
|小括号|P\left(A=2\middle\|\dfrac{A^2}{B}>4\right)|<!-- {.custom_width} -->`!$P\left(A=2\middle|\dfrac{A^2}{B}>4\right)$`|自适应大小的括号，使用\left,\right,中间可用\middle\||
|中括号|[a]|$[a]$|无转义|
```


![image](https://user-images.githubusercontent.com/57370/83391029-6dbbf080-a425-11ea-8caf-b61bd4d1f276.png)
