### ISSUE TITLE
公式编号问题

### ISSUE THREAD

**Issue by SHANGHL29** [suziwen/markdownxiaoshujiang#1378]
系统win10，版本8.1.4，公式编号实现不了，小书匠语法使用手册的公式无法编译

![公式显示问题](https://user-images.githubusercontent.com/65458388/84118073-0fb28d00-aa65-11ea-9117-d3c280dab941.png)

**Comment by suziwen** [comment]
更新一下, 8.1.5.

**Comment by SHANGHL29** [comment]
你好，我在8.1.4的版本更新到8.1.5，但它重新启动的按钮点不动，关闭也点不动，然后我强制退出了，退出了之后再打开发现还是8.1.4，打算卸载重装了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"苏滋文"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 晚上6:57
收件人:&nbsp;"suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;;
抄送:&nbsp;"梦想着有一天"<2481732488@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 公式编号问题 (#1378)





 
更新一下, 8.1.5.

**Comment by suziwen** [comment]
如果还是 8.1.4 , 下次启动应该有提示你升级更新的,或者也可以到 关于界面,再升级一次.

**Comment by SHANGHL29** [comment]
都试了的，就动不了，重装就好了，公式编号也好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏滋文"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 晚上8:08
收件人: "suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;; 
抄送: "梦想着有一天"<2481732488@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [suziwen/markdownxiaoshujiang] 公式编号问题 (#1378)





 
如果还是 8.1.4 , 下次启动应该有提示你升级更新的,或者也可以到 关于界面,再升级一次.

**Comment by suziwen** [comment]
重装后, 8.1.5 也能正常升级成功吧?

**Comment by SHANGHL29** [comment]
嗯嗯，是升到8.1.5了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏滋文"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 晚上8:12
收件人: "suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;; 
抄送: "梦想着有一天"<2481732488@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [suziwen/markdownxiaoshujiang] 公式编号问题 (#1378)





 
重装后, 8.1.5 也能正常升级成功吧?

**Comment by suziwen** [comment]
:ok_hand:
