### ISSUE TITLE
pdf水印问题，直接把内容遮挡住了

### ISSUE THREAD

**Issue by ChuKuang** [suziwen/markdownxiaoshujiang#1380]
![微信截图_20200616153817](https://user-images.githubusercontent.com/20549836/84745628-6da41f00-afe7-11ea-99fe-2dabaf821643.png)

水印颜色太深了，把内容遮住了

**Comment by suziwen** [comment]
这个联网打印 pdf 功能只对会员提供去水印功能, 非会员都会强制加水印的.非会员的话可以考虑使用客户端本地 pdf 打印功能 .
