### ISSUE TITLE
经常会出现连续输入多行文字后,全部操作被撤销

### ISSUE THREAD

**Issue by OliverRen** [suziwen/markdownxiaoshujiang#1381]
普通模式下
未保存前,连续输入多行文字,有时会出现整段文本被删除掉.但是按 ctrl+z 可以撤销

另外程序在没有任何操作的情况下,也需要占用 30%的CPU 不知是为什么,
CPU i3 6100+16g ddr4内存

**Comment by suziwen** [comment]
小书匠客户端版本是多少? 还是使用了 web 版本?

有可以重现的操作流程吗? 我这边自己如果没有任何操作的话, cpu 基本都是 0

**Comment by suziwen** [comment]
还有一个,你打开的文件是本地关联打开的文件,然后编辑操作一会,就会出现所说的操作被撤消吗? 还是通过新建按钮生成的文章会出现撤消

**Comment by OliverRen** [comment]
我使用的是客户端版本 .版本是7.9.0.

基本上没有什么流程.
1.新建一个文档.
我使用的默认模板是这样的

![2](https://user-images.githubusercontent.com/3365039/84968697-b5db5280-b149-11ea-942b-07aa7291bb37.png)


文档大多是有道笔记,复制后使用将富文本转换为markdown粘贴方式导入然后编辑的.然后文档一般比较长,500行-1000行吧

占用CPU一直是这么多
![微信图片_20200618095255](https://user-images.githubusercontent.com/3365039/84968618-888ea480-b149-11ea-8a82-ef2376977c55.png)

**Comment by suziwen** [comment]
可以试试下面几个操作

1. 升级到 8.1.1 版本
2. 需要用到的语法,再使用语法开关打开, 不需要的先关闭, 不要一下子全部语法都打开,这样好排查是哪个语法造成 cpu 消耗比较大
3. 文章内容比较多的话,可以试着关闭预览,看是不是还会有这吗多 cpu 消耗.

**Comment by OliverRen** [comment]
:) 升级到了最新版本,问题都没有了 谢谢解答
