### ISSUE TITLE
全局自定义样式，有对应设置的文档木有？

### ISSUE THREAD

**Issue by gnibgnib** [suziwen/markdownxiaoshujiang#1382]
我看能全局自定义样式，
但是不晓得有哪些类名或ID对应哪，
选择器都不知道怎么写，不知如何下手，有文档莫得？🐶

**Comment by suziwen** [comment]
这个现在还没有,如果是 window 版本的话,可以到安装目录里找想应的 css 文件 .  把想要修改的内容通过 `设置` 进行修改就可以了(不建议直接改安装目录里的文件,因为升级后,这些文件都会被重新覆盖掉)

`app/css/preview` 这个文件夹里的是 预览区里对应的 css .

`app/css/themes` 这个是编辑器全局区域的 css.

--------------

**建议:**

可以使用 chrome 浏览器访问小书匠 web 版本,  按 `ctrl+shift+I` 进入审查元素窗口, 调整改哪个属性,把这些修改记录下来,然后在小书匠客户端的 `设置` 里添加上去.
