### ISSUE TITLE
代码执行错误

### ISSUE THREAD

**Issue by LVXUEYANGTiger** [suziwen/markdownxiaoshujiang#1386]
```{javascript cmd:"node",fancy:'1,3,4',linenums:true}
var x = 1;
var y = 2;
var z = 3;
var u = 4;
var v = 5;
console.log(x + y + z + u + v);
```
提交出错: {"code":1009,"error":"服务器错误","orign":{"returnCode":301,"returnMessage":"Invalid token","externCode":"","code":301,"return_code":301,"return_message":"Invalid token"}}

**Comment by suziwen** [comment]
你的token 不对，你是执行什么操作的，保存第三方储存？

**Comment by LVXUEYANGTiger** [comment]
可能错误不匹配吧，我发的那个错误应该是那个第三方存储(用的为知笔记)现在可以了，我其实想问 那个代码执行结果如何出来呢？就像Jupyter Notebook那样&nbsp; 点了那个按钮不出来结果，有没有具体的参数说明。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏滋文"<notifications@github.com&gt;; 
发送时间: 2020年7月4日(星期六) 下午3:40
收件人: "suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;; 
抄送: "吕雪阳"<1191432275@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [suziwen/markdownxiaoshujiang] 代码执行错误 (#1386)





 
你的token 不对，你是执行什么操作的，保存第三方储存？
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by suziwen** [comment]
你是指这个？
http://soft.xiaoshujiang.com/docs/grammar/feature/code_chunk/

**Comment by LVXUEYANGTiger** [comment]
是的,我在客户端使用的小书匠,而且开了非安全模式,代码我是按照您的文档输入的,而且我的系统上也有node的，就是不执行，点上去也没有任何变化。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏滋文"<notifications@github.com&gt;; 
发送时间: 2020年7月4日(星期六) 下午3:56
收件人: "suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;; 
抄送: "吕雪阳"<1191432275@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [suziwen/markdownxiaoshujiang] 代码执行错误 (#1386)





 
你是指这个？
 http://soft.xiaoshujiang.com/docs/grammar/feature/code_chunk/

**Comment by suziwen** [comment]
代码执行这个确认是个 bug.

应该是升级了底层的 nwjs, 没有测试到. 感谢反馈.

**Comment by LVXUEYANGTiger** [comment]
作者大大你是想实现这样的功能吧！







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏滋文"<notifications@github.com&gt;; 
发送时间: 2020年7月4日(星期六) 下午4:17
收件人: "suziwen/markdownxiaoshujiang"<markdownxiaoshujiang@noreply.github.com&gt;; 
抄送: "吕雪阳"<1191432275@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [suziwen/markdownxiaoshujiang] 代码执行错误 (#1386)





 
确认是个 bug.

**Comment by suziwen** [comment]
嗯,是的,就是在代码通过外部程序执行,然后把结果返回过来.

**Comment by suziwen** [comment]
8.2.2 已修复,可以到[这里](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.2.2)下载
