### ISSUE TITLE
关于又拍云图床formApiSecret的问题

### ISSUE THREAD

**Issue by hucstar** [suziwen/markdownxiaoshujiang#1387]
![20200705122106.png](https://i.loli.net/2020/07/05/2LaluKnypIhEZo4.png)

文章是不是有点老，管理界面值的是控制面板吧，怎么找了好久没有找到高级功能>表单 API呢？希望得到大大指点，也希望路过的各位大佬能给点提示，感谢大家了。

![](https://raw.githubusercontent.com/hucstar/img/img/xiaoshujiang/20200705122106.png)

**Comment by suziwen** [comment]
嗯,确实比较旧了,后继我再更新一下操作说明

**Comment by suziwen** [comment]
formApiSecret 就是现在的 `文件密钥`

![image](https://user-images.githubusercontent.com/57370/86708212-4a4f1b80-c04b-11ea-9173-c59c7d54d8f4.png)

**Comment by hucstar** [comment]
感谢大大，完美解决问题，真的是非常好的开源项目。还有个问题，就是默认情况一级标题和二级标题等前都是有序列编码的，如1，1-1，1-1-1，可以自由设置编码或者不编码吗？因为写好的md文件导入到知乎专栏是不编的，自己想编前面有自动就会显示1.1.，1-1.1-1……

**Comment by suziwen** [comment]
参考[这里](https://github.com/suziwen/markdownxiaoshujiang/issues/1388#issuecomment-654834494)

还有这个 http://soft.xiaoshujiang.com/blog/numbered_heading/
