### ISSUE TITLE
频繁提示提交出错 {\"errorCode\":2,\"parameter\":\"Note.guid\"}

### ISSUE THREAD

**Issue by majiaxin110** [suziwen/markdownxiaoshujiang#1389]
v 8.2.0 macOS 10.15.3
![出错提示](https://gitee.com/majiaxin110/my_images/raw/master/小书匠/1594092757049.png)
似乎只有我[这一篇笔记](https://file.mtage.top/#/s/5GfM)会出现这个问题，其他笔记编辑时正常，但是这篇笔记之前也没有这种现象，最近才出现的

**Comment by majiaxin110** [comment]
我想是不是和 #1386 类似的问题，但我设置里面并没有打开codeChunk，在文档元数据指定grammar_codeChunk: false也没有效果。另外我保存到印象笔记是没有问题的

**Comment by suziwen** [comment]
用另存为试一下, 提示的错误是印象笔记里的 Note.guid 不对引起的.

--------

原因: 

这个像是你使用了两个不同的印象笔记账号, 把另一个帐号的笔记内部保存到当前帐号引起的.

也有可能是这篇文章在印象笔记服务器里已经被删除,或者内部的 guid 变了产生的.

**Comment by majiaxin110** [comment]
> 用另存为试一下, 提示的错误是印象笔记里的 Note.guid 不对引起的.
> 
> 原因:
> 
> 这个像是你使用了两个不同的印象笔记账号, 把另一个帐号的笔记内部保存到当前帐号引起的.
> 
> 也有可能是这篇文章在印象笔记服务器里已经被删除,或者内部的 guid 变了产生的.

我试了下另存为不行，我期间并没有切换账号什么的。我删除文档数据库之类的折腾了几轮，后来发现保存到某一个特定的笔记本就会出这个问题，于是我新建了一个笔记本来保存，现在没有这个问题了。我估计可能还是印象笔记的问题

**Comment by majiaxin110** [comment]
我今天又出现这个问题了，而且不止一篇笔记，另存为没有用，我删除数据文件等重新安装小书匠都不行。明明直接保存内容是正常的，有没有办法先把这个报错干掉？orz

**Comment by majiaxin110** [comment]
8.1.1版本没有这个问题 我先倒回去了orz

**Comment by majiaxin110** [comment]
我这里又出现绑定印象笔记就会出错的问题了，我是不是应该重新开个issue...
![here](https://gitee.com/majiaxin110/my_images/raw/master/小书匠/1594194755991.png)

**Comment by majiaxin110** [comment]
现在又绑定上了（好迷啊...）8.1版本不会报这个错 我就先退回去了

**Comment by suziwen** [comment]
rateLimit 这个错是印象笔记那边返回来的

意思是说 单位时间内请求 印象笔记服务器的次数太多,被印象服务器限制了访问, 需要等待 567 秒(也就是 10 分钟左右)后,才能再次请求印象笔记服务器.
