### ISSUE TITLE
离线版代理

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#139]
下载了离线版，应该是一个软件把网页等封装起来的吧。没有代理功能，公司限制直接连接外网的功能，需要代理才能上网，没有代理，一直连接不了网络，绑定的印象笔记一直都刷新不了目录，啥回事能提供个设置代理功能呢？

**Comment by chinaShawn** [comment]
强烈需求，代理

**Comment by xiexianbin** [comment]
+1

**Comment by zrainx** [comment]
+1

**Comment by suziwen** [comment]
6.7.0 版本已经提供代理设置功能

http://soft.xiaoshujiang.com/download.html
