### ISSUE TITLE
在小书匠编辑的文章呈现在github pages上集中在一个自然段里

### ISSUE THREAD

**Issue by zllafgafg** [suziwen/markdownxiaoshujiang#1390]
你好，我在小书匠里编辑的文章是按回车键进行换段落的，而且在小书匠编辑页面的最右侧，呈现出来也是一段一段的，但是在github pages博客上浏览文章，都是集中在一个段落的，没有分段了。因为不是太会配置github，所以想问一下是不是在编辑时要按两次空格，然后再回车呢？谢谢。

**Comment by suziwen** [comment]
段与段之间 ,建议两个换行, 进行分段, 这个是大部份 markdown 语法的要求.

一个换行仅仅表示在一个段落里换行,不同的 markdown 解析后显示效果可能会不同.

**Comment by zllafgafg** [comment]
嗯，谢谢
