### ISSUE TITLE
为知接口出问题了吗？

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1391]
![image](https://user-images.githubusercontent.com/7530342/87839580-fd323b80-c8cd-11ea-801d-848f042a68af.png)

打开为知的文件特别的慢，甚至有的文件夹内会失败，有的可以正常打开，保存是正常的。

**Comment by CharMingF** [comment]
补充测试，发现对于1个月内保存的文件会很快打开，但是1个月左右之前的文件就会出现这个错误，可能是不是wiz对1个月之前的文件进行了什么处理

**Comment by suziwen** [comment]
感谢反馈,确认是个 bug.

**Comment by CharMingF** [comment]
> 感谢反馈,确认是个 bug.

感谢快速的修复，太棒了
