### ISSUE TITLE
pdf导出附件资源顺序和内容紊乱

### ISSUE THREAD

**Issue by LonlyPan** [suziwen/markdownxiaoshujiang#1392]
在使用PDF导出时，有附件的地方，显示的是其它地方的附件，总之就是内容都对，但附件全都错了。
下图中右侧导出后的两张图片都显示的是别的地方的图表，不是左侧源文件对应的图片，其它地方亦是。
![image](https://user-images.githubusercontent.com/48073168/87905129-6d89ba00-ca92-11ea-96e8-5658da2fd87f.png)

**Comment by suziwen** [comment]
确认 bug, 感谢反馈.

**Comment by suziwen** [comment]
可以试下 `8.2.4` web 版本.
