### ISSUE TITLE
Win10 1909 黑屏

### ISSUE THREAD

**Issue by fadedFantastic** [suziwen/markdownxiaoshujiang#1393]
Win10 1909 黑屏

**Comment by suziwen** [comment]
我这边没有这个版本操作系统,不好排查 . 不过在较老版本的 win 10 下是可以正常启动的.

你可以试试改一下启动配置文件 , `package.json` , 添加参数 `"chromium-args": "--disable-gpu"` 看能不能启动.

package.json 文件在小书匠的安装目录下面

```
  "chromium-args": "--enable-node-worker",
```

改成

```
  "chromium-args": "--enable-node-worker --disable-gpu",
```

![image](https://user-images.githubusercontent.com/57370/88173226-ce60f000-cc54-11ea-8551-5778770cbad9.png)


然后启动小书匠.

**Comment by fadedFantastic** [comment]
感谢，终于可以用了
