### ISSUE TITLE
plantuml 一致 500 Internal Server Error

### ISSUE THREAD

**Issue by kkHAIKE** [suziwen/markdownxiaoshujiang#1394]
是只有我这样么？

**Comment by suziwen** [comment]
可以了, 

小书匠的 plantuml 服务可能有些不稳定, 我重启了下, 现在应该没问题了.

------------

可以在 `设置>语法扩展>plantuml` 里自己指定一个比较稳定的 plantuml 服务器,比如官方的 plantuml 服务器, 或者自己搭建一个 plantuml 服务器.

![image](https://user-images.githubusercontent.com/57370/88669895-0a91c600-d117-11ea-83b4-13412526e32f.png)
