### ISSUE TITLE
edge浏览器中不显示第三方存储选项

### ISSUE THREAD

**Issue by ruozhixian** [suziwen/markdownxiaoshujiang#1397]
如图：

<img width="854" alt="批注 2020-08-05 110221" src="https://user-images.githubusercontent.com/25141494/89367314-44605f00-d70b-11ea-9cfd-ddfa72dc0b08.png">

**Comment by suziwen** [comment]
我这边用最新的 edge 浏览器, 测试了下,没有出现你说的情形

**Comment by ruozhixian** [comment]
> 我这边用最新的 edge 浏览器, 测试了下,没有出现你说的情形

那应该是因为edge版本，我用的win10本身自带的edge浏览器，换了三台电脑都不行。更新了最新的版本，可以
