### ISSUE TITLE
生成的Html里<a>为什么自动给我加了target="_blank"？

### ISSUE THREAD

**Issue by welkinbai** [suziwen/markdownxiaoshujiang#140]
如题，我不想要target="_blank"，因为这样的话，我就不能使用这个工具来生成一套相互跳转的页面了，每次点连接都会弹出新窗口，这样没一会儿，就开了一堆窗口…………

可不可以在导出Html的地方设置个开关，让用户自己选择？

**Comment by suziwen** [comment]
目前系统会对链接打开目标进行出理，规则是同路经的链接保持不变，比如`<a href="#id">链接</a>`,
其他的链接都加上了在新窗口打开的属性。主要是为了防止在预览窗口里点击链接后跳转到其他页面。

这个后面会改进处理方式。
