### ISSUE TITLE
编辑器主题列表改进

### ISSUE THREAD

**Issue by vio1etus** [suziwen/markdownxiaoshujiang#1401]
希望添加显示当前主题的功能。像下图这样，都不知道自己目前使用的是哪一个主题

![image](https://user-images.githubusercontent.com/33022132/89859253-2c894f00-dbd3-11ea-827b-94e412ff3f78.png)

**Comment by suziwen** [comment]
被选中使用的主题,字体有加粗效果的,可能在暗系主题下不是比较明显.

8.3.3 版本我加了个边框效果,用来表示当前选择的主题.

**Comment by vio1etus** [comment]
加了边框，就还可了。
![image](https://user-images.githubusercontent.com/33022132/89890796-89522d00-dc06-11ea-8ccb-c25370a91ece.png)
谢谢！
