### ISSUE TITLE
使用小书匠图床服务时，无法使用图床路径 {{title}} 

### ISSUE THREAD

**Issue by apas008** [suziwen/markdownxiaoshujiang#1402]
小书匠图床默认将图片储存在images文件夹下，由于个人需要要将md上传至个人博客，需要文章title与图片文件夹相同，故希望使用小书匠图床时，也能够自定义文件夹名称。

**Comment by suziwen** [comment]
可以这样设置

![image](https://user-images.githubusercontent.com/57370/90012110-588cf900-dcd5-11ea-8bec-ee23623591c8.png)

**Comment by suziwen** [comment]
小书匠内置的图床服务现在还不支持 {{title}} 等这些变量.

想使用这种变量的话,需要使用像 github, alioss 等图床,或者通过[自定义图床](http://soft.xiaoshujiang.com/blog/images/custom_images_manager/), 编写 javascript 脚本,把图片保存到自己想要保存的位置上

**Comment by apas008** [comment]
谢谢 学习了
