### ISSUE TITLE
公式渲染问题

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1404]
用mathjax渲染公式$$\text { TCP throughput }=\frac{1.22 \cdot \mathrm{MSS}}{\mathrm{RTT} \sqrt{\mathrm{L}}}$$显示不出来正常公式，我用其他latex在线网站渲染是正常的

**Comment by suziwen** [comment]
在 `小书匠>设置>语法扩展>mathjax公式` 里,把 兼容通用写法选中
![image](https://user-images.githubusercontent.com/57370/90012231-9853e080-dcd5-11ea-8a20-7894232fb8f2.png)

**Comment by AtaraxiaZ** [comment]
啊是我搞错了，我忘了在```后面加mathjax!，打扰你了，不好意思
