### ISSUE TITLE
切换程序时有些卡顿

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1409]
您好，就是在我编辑文本时，因为经常要从其他途径获取文字资料，所以会经常用alt+tab切换程序，我发现切换的时候时常会有卡顿，有时候会比较流畅，大概十次里有两次，并且是在关闭了预览，是纯文本编辑下。我一开始怀疑是文字太多了，就把这个4万字的文档归档了，编辑了一个只有几千字的，发现还是有这个问题。我不太懂编程，但感觉是因为在切换程序之前，编辑器会先保存，再切换窗口，可能就是这个保存过程导致了延时。那是否可以在后台保存呢？这样切换程序就会很顺畅。就是先切换玩程序后再在后台保存

**Comment by suziwen** [comment]
你操作系统和小书匠是什么版本?我这边自己测试了下,切换时并没有卡顿的现像.

**Comment by AtaraxiaZ** [comment]
win10专业版，小书匠是8.3.5，这种情况出现比较偶然，每次切换前要先打些字。不过我刚刚尝试了下也没有试出来卡顿，我之前说的频率夸张了，但是是偶然有出现这种情况的。或许也是我电脑配置的问题

**Comment by AtaraxiaZ** [comment]
应该是我电脑性能不太行了，和小书匠应该没关系，打扰您了
