### ISSUE TITLE
在预览区不小心按了鼠标中键，出现bug

### ISSUE THREAD

**Issue by welkinbai** [suziwen/markdownxiaoshujiang#141]
如题，不小心按了鼠标中建，鼠标标志变成了滚动的点点那个标志，然后就卡住，按不了所有的按钮。只有强制重启软件。
我的环境是：win7专业版 客户端

我可以稳定重现这个bug

**Comment by leongfeng** [comment]
这个bug不一定是按中键才出现，偶尔点了其它东西也会出现

**Comment by suziwen** [comment]
“按不了所有按钮”,是卡死？cpu很高？我自己还没遇到这种情况，得再测试下。

**Comment by welkinbai** [comment]
就是连右上角的叉叉都点不了………………Cpu不高，cpu占用是00

**Comment by suziwen** [comment]
暂时只能禁用鼠标中间的按键了。



https://bugs.chromium.org/p/chromium/issues/detail?id=259225
https://bugs.chromium.org/p/chromium/issues/detail?id=336373
https://bugs.chromium.org/p/chromium/issues/detail?id=386176
https://bugs.chromium.org/p/chromium/issues/detail?id=392136
https://bugs.chromium.org/p/chromium/issues/detail?id=446984
