### ISSUE TITLE
过滤器中标签过滤能否增加直接多标签筛选功能

### ISSUE THREAD

**Issue by fedstryale** [suziwen/markdownxiaoshujiang#1416]
一个文章通常有很多标签，一个标签下也有很多文章，当需要寻找特定文章时，通常需要多个标签同时选择以缩小范围，这在有标签管理的软件中也通常是标配。
而在小书匠中标签过滤器默认条件一次只能选择一个标签，而想要选择多个标签则需要自定义，这就太不方便了，排列组合的选择太多，还不如在一个标签的文章列表里慢慢找。
如果能直接在过滤器中点击选中多个标签进行筛选就太方便了。

**Comment by suziwen** [comment]
https://www.bilibili.com/video/BV1uW4y1S7Td?t=207.5
