### ISSUE TITLE
无法正确显示webp格式图片，默认会识别成attachment

### ISSUE THREAD

**Issue by editcue** [suziwen/markdownxiaoshujiang#1419]
因为webp储存动图体积会小很多，所以希望支持webp格式图片

**Comment by suziwen** [comment]
可以在 `设置>预览>是否自动转换非图片扩展名为附件` 功能去掉.

![image](https://user-images.githubusercontent.com/57370/92423424-a94c2080-f1b3-11ea-92f0-8696f3840617.png)
