### ISSUE TITLE
离线版的文档是保存在本地电脑上的么？

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#142]
![qq](https://cloud.githubusercontent.com/assets/11471256/13373656/4f8a96e0-dda8-11e5-84f5-415dad575e8c.png)

我看复制图片后的超链接的路径是./images/xxx.jpg，我查找了本机没找到图片。
好像我曾经看到过有垃圾站的功能，现在想找又不找不到了，有这个功能么？因为可能记错了，谢谢

**Comment by suziwen** [comment]
图片是放在本机的，只是是保存到数据库里，`./`开头的文件链接，系统保留用来查找数据库里对应的文件。
有垃圾站的功能，在文档列表上方有个回收标识（就是搜索按钮边上。需要v1.8.0版本）。
每篇文章的附件都是单独的，可以在文档列表里（鼠标移到对应的文章项上有三个按钮，中间那个就是了）的附件管理弹出层上进行管理，你那里找找应该就能找到你想要的图片。
