### ISSUE TITLE
webdav文件系统 Network Error

### ISSUE THREAD

**Issue by editcue** [suziwen/markdownxiaoshujiang#1420]
浏览器网页版小书匠->绑定第三方数据操作界面->webdav文件系统->提示“检测失败:Error: Network Error”
这个问题在nwjs版小书匠测试，没有报错
是因为跨域问题吗？

**Comment by suziwen** [comment]
chrome 浏览器下, 可以 `ctrl+shift+j` / `F12`看一下 `console` 或者 `network` 标签有什么错误信息

**Comment by editcue** [comment]
console 报错
`Access to XMLHttpRequest at 'https://xxx.com/' from origin 'http://markdown.xiaoshujiang.com' has been blocked by CORS policy: Method PROPFIND is not allowed by Access-Control-Allow-Methods in preflight response.`
应该是服务器问题，我在response header加了`Access-Control-Allow-Methods:PROPFIND`后就没问题了。
谢谢。
