### ISSUE TITLE
左侧 MD 文件列表栏消失，快捷键也失效

### ISSUE THREAD

**Issue by soupedog** [suziwen/markdownxiaoshujiang#1423]
版本：8.3.0
系统环境：win 10 2004

症状：
①左侧 md 文件列表栏消失 ( ctrl + shift + f 也没用 )

另：很早前就开始了，本地未另存为的 md 文件已另存为的 md 文件图标没区分，这个用起来很不方便，希望能够区分是否已另存为

**Comment by soupedog** [comment]
尝试 ``小书匠→数据→重建数据库索引`` 后似乎文件栏恢复了

**Comment by suziwen** [comment]
1. 调大一点窗口, 然后左侧中间有个不是很明显的按钮,可以展开文件列表栏.
2. 确认 bug, 感谢反馈.

**Comment by soupedog** [comment]
> 1. 调大一点窗口, 然后左侧中间有个不是很明显的按钮,可以展开文件列表栏.
> 2. 确认 bug, 感谢反馈.

补充一下，bug 出现时，左侧的小按钮也是消失状态，快捷键、按钮都是无法使用的

**Comment by suziwen** [comment]
第一个问题能截个图看下吗? 

我刚才确认的 bug 是 `本地未另存为的 md 文件已另存为的 md 文件图标没区分`. 第一个问题我这边没法重现.

**Comment by soupedog** [comment]
> 第一个问题能截个图看下吗?
> 
> 我刚才确认的 bug 是 `本地未另存为的 md 文件已另存为的 md 文件图标没区分`. 第一个问题我这边没法重现.

这个我现在也复现不出来了，``小书匠→数据→重建数据库索引`` 之后恢复正常了。。。

bug 出现的时候，左侧小按钮 ``open``、``close`` 全都不存在，文件列表栏也消失，按快捷键 ``ctrl + shift + f `` 也是没反应的
