### ISSUE TITLE
建议`图床转移`功能，支持其他类型文件的链接转换

### ISSUE THREAD

**Issue by editcue** [suziwen/markdownxiaoshujiang#1424]
因为部分图床服务是支持非图片类型文件上传的(例如七牛云/腾讯云/阿里云之类的`云储存服务`)，现在`图床转移`只支持图片类型链接。虽说自己用正则批量替换链接也行但比较麻烦。希望能增加这个功能。

**Comment by suziwen** [comment]
这个估计不会添加.
