### ISSUE TITLE
编辑器正则替换不支持`后向引用文本替换`？

### ISSUE THREAD

**Issue by editcue** [suziwen/markdownxiaoshujiang#1425]
字符串：`as1234asd`
正则：`[\s\S]+?([0-9]+)[\s\S]+`
替换：`b$1a`
结果：`b$1a`
期望结果：`b1234a`

**Comment by editcue** [comment]
临时解决办法，用其他编辑器替换完，再复制回小书匠

**Comment by suziwen** [comment]
这个现在暂时没有.

**Comment by suziwen** [comment]
`8.5.0` 版本已经支持这个功能了，欢迎下载使用。
