### ISSUE TITLE
Linux 下 1.8.0 的问题

### ISSUE THREAD

**Issue by wenLiangcan** [suziwen/markdownxiaoshujiang#143]
我是从 1.7.1 升到 1.8.0 的，打开后找不到之前存在里面的离线文档了。

![selection_005](https://cloud.githubusercontent.com/assets/1244181/13386084/5c7c1b26-dee3-11e5-9bef-6fb00215dbb4.png)

另外就是没法最大化窗口。

**Comment by wenLiangcan** [comment]
发现用回 1.7.1 就两个问题都没有了

**Comment by suziwen** [comment]
没法最大化指的是什么？全屏写作模式？
调整下窗口大小，再按 `+` 号呢？

老数据可以在　`~/.config/小书匠(编)` 下找到，把这个文件夹重命名成 `~/.config/小书匠`，再启动就能找到以前的离线文件了。

升级后第一次启动要对数据重新索引，如果以前离线文章比较多的话，可能要索引比较久。

**Comment by wenLiangcan** [comment]
不是全屏，就是普通的窗口最大化，按那个 + 号窗口会闪一下然后变回原来的大小

**Comment by suziwen** [comment]
你那是什么LINUX操作系统，我这边无法重现。
1.8的最大化行为是和1.7有些差别，但功能还是可以使用的。

**Comment by wenLiangcan** [comment]
我用的 Arch Linux，桌面环境是 KDE Plasma 5。

**Comment by suziwen** [comment]
启动后，先调整大小，再点击`＋`号呢

**Comment by wenLiangcan** [comment]
调整过多种大小了都不行，我录了个屏，你看一下：

![new](https://cloud.githubusercontent.com/assets/1244181/13416185/c97cfa16-df9b-11e5-9972-7f4e3ab10614.gif)

**Comment by suziwen** [comment]
不是点 `+` 号的调整，是单独在边框上拉动调整，调整完后，再点击 `+` 号呢。

**Comment by wenLiangcan** [comment]
不好意思，没表达清楚。我说的调整就是拖动边框调整窗口大小。这个录屏只是想让你看一下我说的闪一下变回原样是什么情况。

**Comment by suziwen** [comment]
知道什么原因了，kde桌面的动画效果引起的。

**Comment by wenLiangcan** [comment]
太好了。

**Comment by wenLiangcan** [comment]
更新到 1.9.1 后已经没有问题了
