### ISSUE TITLE
同步预览区滚动逻辑是不是反了？

### ISSUE THREAD

**Issue by LonlyPan** [suziwen/markdownxiaoshujiang#1430]
当我选中  左 <- 右 箭头时，预览区跟随编辑区滚动
反之，编辑区跟随预览区滚动。

这个箭头方向和实际逻辑是不是反了？

![小书匠同步预览](https://user-images.githubusercontent.com/48073168/94507139-a89e2b80-0241-11eb-994a-3fc542c0a48e.gif)

**Comment by suziwen** [comment]
看 gif 应该是个 bug, 但不知道什么原因触发这种情况的.

 我这边测试了几次, 是正常的逻辑, 点上边的按钮时,编辑区滚动,预览区跟随滚动,点下边按钮时,预览区滚动,编辑区跟随滚动.

你可以在 web 版本上,用 chrome 等浏览器打开隐身模式,测试下这个滚动效果.

**Comment by LonlyPan** [comment]
今天新发现，两个箭头都不点，不论左右，都会同步滚动。
web 版本试用了，都正常。

电脑win10，软件版本8.3.15

![小书匠同步预览2](https://user-images.githubusercontent.com/48073168/94634368-730d4700-0302-11eb-921d-2015c1d7304d.gif)

**Comment by suziwen** [comment]
你客户端版本是多少?

**Comment by suziwen** [comment]
看一下 `设置>基本` 里选项

![image](https://user-images.githubusercontent.com/57370/94634796-9c7aa280-0303-11eb-8601-7e51d826e255.png)

**Comment by suziwen** [comment]
或者你试一下,把数据目录(可以在 `关于` 界面,找到数据目录位置)先移走,再启动小书匠,看还会出现这个情况吗?

**Comment by LonlyPan** [comment]
对比了设置里的选项，发现现在的逻辑是：黑色不选中，灰色选中。看下面的图，左边是界面的箭头，右边是设置里自动相继改动结果。
![image](https://user-images.githubusercontent.com/48073168/94663812-b2588980-033c-11eb-9357-1669692870ad.png)

**Comment by LonlyPan** [comment]
数据目录移走后，操作恢复正常。

**Comment by suziwen** [comment]
应该是跟选择的编辑主题有关，你选了暗色主题，就会这样，亮色主题应该就好了。

**Comment by LonlyPan** [comment]
最近更新了一次，问题修复了。
