### ISSUE TITLE
如何取消编辑器语法高亮？

### ISSUE THREAD

**Issue by drcege** [suziwen/markdownxiaoshujiang#1432]
请问编辑器里 (CodeMirror, Ace) 如何关闭颜色显示呢，就是各种 Markdown 的语法高亮？

现在编辑器里看起来花里胡哨的，很分散注意力，比右边预览里颜色还多。

写 Markdown 时只要黑白的纯文本显示就够了（更改主题似乎没有效果，改的是整个应用的全局主题）

**Comment by suziwen** [comment]
可以选择这几个纯色主题 ,

![image](https://user-images.githubusercontent.com/57370/96411644-5e461400-121b-11eb-9812-c5ba3a1936e0.png)

![image](https://user-images.githubusercontent.com/57370/96411795-a1a08280-121b-11eb-948f-ba9500ab189e.png)


--------------

如果了解 html 和 css 的话, 可以在 `设置>基本>全局自定义样式` 里,自己写 css 样式.

**Comment by drcege** [comment]
这个说实话有点丑，而且也不是纯黑白，变成灰度之后辨识度很低。。。而且还是与主题耦合在一起的，整个界面的 UI 也都跟着变。

感觉在设置里增加一个编辑器语法高亮的开关更合适点？

**Comment by suziwen** [comment]
那就只能自定义css 样式了,

其实小书匠现在的主题都是使用 css 的变量,简单配置几个颜色值,就能改变主题. 这些主题基本都遵循 base16 的配色,

像上面的 `grayscale-light` 主题 ,对应安装目录下的 `css/themes/base16-grayscale-light.css` 文件,里面的内容其实很简单

``` css
:root {
  --base00: #f7f7f7;
  --base01: #e3e3e3;
  --base02: #b9b9b9;
  --base03: #ababab;
  --base04: #525252;
  --base05: #464646;
  --base06: #252525;
  --base07: #101010;
  --base08: #7c7c7c;
  --base09: #999999;
  --base0A: #a0a0a0;
  --base0B: #8e8e8e;
  --base0C: #868686;
  --base0D: #686868;
  --base0E: #747474;
  --base0F: #5e5e5e;
}
```

如果想实现只在编辑区内改成黑白,而编辑区外使用系统主题配色,可以对这些变量进行范围限定

比如把下面的代码粘贴到  `设置>基本>全局自定义样式` ,这样,无论怎么切换主题,编辑区都是自定义的样式内容
```css
.editorPanel {
    --base00: #f7f7f7;
    --base01: #e3e3e3;
    --base02: #b9b9b9;
    --base03: #ababab;
    --base04: #525252;
    --base05: #464646;
    --base06: #252525;
    --base07: #101010;
    --base08: var(--base05);
    --base09: var(--base05);
    --base0A: var(--base05);
    --base0B: var(--base05);
    --base0C: var(--base05);
    --base0D: var(--base05);
    --base0E: var(--base05);
    --base0F: var(--base05);
    --defaultBackground: var(--base00);
    --lighterBackground: var(--base01);
    --selectionBackground: var(--base02);
    --highlightBackground: var(--base03);
    --darkForeground: var(--base04);
    --defaultForeground: var(--base05);
    --lightForeground: var(--base06);
    --lightBackground: var(--base07);
}
```

其中  `base08` 到 `base0F` 就是控制 markdown 语法里变量的颜色,把这些颜色全部设置成 `base05` 这个默认前景色 就可以了.
