### ISSUE TITLE
pdf导出能不能分页，全部章节连在一起太难看了

### ISSUE THREAD

**Issue by juneofive** [suziwen/markdownxiaoshujiang#1434]
能不能用 `----`做分页符啊，全部连在一起好难受

**Comment by suziwen** [comment]
使用 三个以上的下橫线就能分页 `___`

----------------

也可以自定义 css 样式来实现分页,

```
.xsj_hr{
   page-break-after: always;
}
```

**Comment by juneofive** [comment]
![image](https://user-images.githubusercontent.com/25833936/96705073-6642b700-13c7-11eb-93ac-e0f8c0f05d52.png)
实际上就是打印了一窜下换线 ，并没有分页

**Comment by suziwen** [comment]
那这样写呢?

``` css
@media print{
.xsj_hr{
   page-break-after: always;
   visibility: hidden;
}}
```

----------

我这边第一种写法也是可以的,不知道你自己有没有其他自定义 css 覆盖了这个规则 .

![image](https://user-images.githubusercontent.com/57370/96707831-f6363000-13ca-11eb-99ff-6f2270f808c4.png)

![image](https://user-images.githubusercontent.com/57370/96707886-04844c00-13cb-11eb-8b7e-95c5ef5ab410.png)


![image](https://user-images.githubusercontent.com/57370/96707923-14039500-13cb-11eb-8058-6d86aad8e06b.png)

**Comment by juneofive** [comment]
最开始是没有自定义样式的，我按照你给的CSS加上也是一样，这个自定义样式是在PDF那里加的吗

**Comment by juneofive** [comment]
可以了， 自定义样式是在预览里面加
