### ISSUE TITLE
表格显示异常

### ISSUE THREAD

**Issue by ygqygq2** [suziwen/markdownxiaoshujiang#1437]
![image](https://user-images.githubusercontent.com/17672440/97386285-764e1f80-190e-11eb-939b-25ee709c0ea5.png)
如图，编辑表格的时候，一行行往下写，预览区对齐异常。解决办法如下图：
![image](https://user-images.githubusercontent.com/17672440/97386488-e066c480-190e-11eb-861b-6375203e4061.png)

**Comment by suziwen** [comment]
没明白你的描述,我这边只要文字输入,光标上下行移动,右侧的预览区都会同步滚动的.
能否提供个录屏操作效果.

**Comment by ygqygq2** [comment]
当前版本: 8.4.4(8.3.0)

[录制_2020_10_28_14_45_31_950.zip](https://github.com/suziwen/markdownxiaoshujiang/files/5450129/_2020_10_28_14_45_31_950.zip)

注意预览区恢复正常时的操作。

**Comment by suziwen** [comment]
知道什么原因了,感谢反馈.下个版本修复.

**Comment by ygqygq2** [comment]
多谢，其实bug很久了，我一直没来提。
