### ISSUE TITLE
悬浮框中显示文章

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#1439]
有时候会在写文档的时候，参考另外一篇文档的内容，两篇之间来回切换比较麻烦，可不可以有一种功能 将另外一篇文档在悬浮窗中打开呢？

预览中我看已经有各种类型的显示方式，包括悬浮和窗口了，可以基于现有的预览添加另外一篇文章在这个窗口中即可。

具体操作的话，比如按住 ctrl键点击文档的时候会在 原先预览窗口中显示该文档，设置关闭按钮，关闭后恢复到 原先预览的内容。

现在的也可以进行更多的自由，比如将双栏的内容自由化，就是编辑随时可以变为预览，预览页可以变为编辑，比如自己和自己对比也是可以的，适用于在文尾编辑参考文首并复制文首内容的功能（现有状态是能够实现，但是有时候预览状态下样式是无法复制到编辑区的，比如列表会丢失列表符号。）

**Comment by suziwen** [comment]
8.4.8 版本加了[浮动编辑器](http://soft.xiaoshujiang.com/docs/tutorial/sub_codemirror_editor/)

**Comment by CharMingF** [comment]
感谢，强
