### ISSUE TITLE
Shift+Enter功能不对了

### ISSUE THREAD

**Issue by shendeguize** [suziwen/markdownxiaoshujiang#1442]
正常shift+enter应该是不继承列表直接换行,现在是退格若干(有时候退格有时候清空行有时候不退格)并输入"_"了
稳定复现(搜狗输入法/win自带输入都会出现)
win10 v8.4.10

**Comment by suziwen** [comment]
更新到 [8.4.11](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.4.11)
