### ISSUE TITLE
菜单栏消失不见

### ISSUE THREAD

**Issue by MandyCh** [suziwen/markdownxiaoshujiang#1443]
8.4.2 版本 
菜单栏消失不见了 ctrl+↑ 也不行没反应
![Snipaste_2020-12-02_09-28-54](https://user-images.githubusercontent.com/26193879/101432902-ac86b200-3944-11eb-8e49-4008cbf4b45f.png)

**Comment by suziwen** [comment]
是什么操作触发工具栏消失的?
重启下小书匠呢?

`8.4.2 ` 版本我记得在中间加了个按钮,如果自己不小心按了快捷键触发工具栏收起,是可以通过这个按钮,重新打开的,但看你的截图里并没有这个按钮

![image](https://user-images.githubusercontent.com/57370/101442301-08a60200-3956-11eb-96c1-c8e02beb5d8f.png)

**Comment by MandyCh** [comment]
具体什么操作也记不清了 无意中触发的 我卸载重装 删掉了user data里面的数据 就又可以了 也可以通过ctrl+↑控制工具栏打开和收起谢谢回复
