### ISSUE TITLE
PlantUML errors

### ISSUE THREAD

**Issue by GersonHuang** [suziwen/markdownxiaoshujiang#1448]
ISSUE: Plantuml cannot parse some file, because plantuml version not fresh
ERROR INFO:
An error has occured : java.lang.UnsupportedOperationException: member=matchStereoLines class net.sourceforge.plantuml.cucadiagram.MethodsOrFieldsArea$1
In an infinite Universe anything can happen.
Diagram size: 178 lines / 5178 characters.
PlantUML (1.2018.14) cannot parse result from dot/GraphViz.
This version of PlantUML is 730 days old, so you should
consider upgrading from http://plantuml.com/download
Please go to http://plantuml.com/graphviz-dot to check your GraphViz version.
This may be caused by :
- a bug in PlantUML
- a problem in GraphViz
You should send this diagram and this image to
plantuml@gmail.com
or
post to
http://plantuml.com/qa
to solve this issue.
You can try to turn arround this issue by simplifing your diagram.
java.lang.UnsupportedOperationException: member=matchStereoLines class net.sourceforge.plantuml.cucadiagram.MethodsOrFieldsArea$1
net.sourceforge.plantuml.graphic.AbstractTextBlock.getInnerPosition(AbstractTextBlock.java:45)
net.sourceforge.plantuml.ugraphic.ULayoutGroup.tryOne(ULayoutGroup.java:82)
net.sourceforge.plantuml.ugraphic.ULayoutGroup.getInnerPosition(ULayoutGroup.java:71)
net.sourceforge.plantuml.cucadiagram.MethodsOrFieldsArea.getInnerPosition(MethodsOrFieldsArea.java:244)
net.sourceforge.plantuml.graphic.TextBlockMarged.getInnerPosition(TextBlockMarged.java:75)
net.sourceforge.plantuml.graphic.TextBlockLineBefore.getInnerPosition(TextBlockLineBefore.java:91)
net.sourceforge.plantuml.graphic.TextBlockVertical2.getInnerPosition(TextBlockVertical2.java:128)
net.sourceforge.plantuml.svek.image.EntityImageClass.getInnerPosition(EntityImageClass.java:115)
net.sourceforge.plantuml.svek.image.EntityImageTips.drawU(EntityImageTips.java:133)
net.sourceforge.plantuml.svek.SvekResult.drawU(SvekResult.java:83)
net.sourceforge.plantuml.ugraphic.ImageBuilder.getFinalDimension(ImageBuilder.java:281)
net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:215)
net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:178)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:127)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:71)
net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:379)
net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:193)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:233)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:136)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:109)
net.sourceforge.plantuml.Run.managePipe(Run.java:357)
net.sourceforge.plantuml.Run.main(Run.java:166)
PlantumlNail.nailMain(PlantumlNail.java:24)
sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.martiansoftware.nailgun.NGSession.run(Unknown Source)
Diagram source: (Use http://zxing.org/w/decode.jspx to decode the qrcode)

**Comment by suziwen** [comment]
#1394

**Comment by suziwen** [comment]
`设置>语法扩展>plantuml` 

```
https://www.plantuml.com/plantuml/svg/{{uml}}
```

**Comment by GersonHuang** [comment]
> `设置>语法扩展>plantuml`
> 
> ```
> https://www.plantuml.com/plantuml/svg/{{uml}}
> ```

This issue has been solved, Thanks
