### ISSUE TITLE
为知笔记绑定失败

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#145]
今天为知笔记不能绑定了。
返回的错误：
{"code":1009,"error":"服务器错误","orign":{"code":1009,"error":"服务器错误","orign":{"code":3332,"message":"encrypted notes"}}}

**Comment by suziwen** [comment]
我这边绑定没问题的。
你那笔记单独加密了？

**Comment by leongfeng** [comment]
已经好了，这看来是为知那边的问题了。可以把这问题删了

**Comment by leongfeng** [comment]
你这么一说早上我有加密过日志，看来是这个原因了。谢谢
