### ISSUE TITLE
Multi-line equations will be crashed into one line

### ISSUE THREAD

**Issue by GersonHuang** [suziwen/markdownxiaoshujiang#1451]
My storage backend is evernote (china version). I have found the issue about mathjax extension:
   for any multi-lines equation, the output image will be compressed into an image patch that just occupies one line-height.
   Besides, if equations between  `aligned`,  `cases`  or some flags will help generate function number, the output will also be one-line image

![image](https://user-images.githubusercontent.com/18435383/103205195-feaf6780-4933-11eb-8a7e-fc727ecfe935.png)

This drawback may not be an `actually problem`, but it will be clear and interactive friendly if multi-lines generate multi-lines image

**Comment by suziwen** [comment]
The newest [web](http://markdown.xiaoshujiang.com) version has fixed this problem,  I hope this version will suffice your requirement

**Comment by suziwen** [comment]
#1356

**Comment by GersonHuang** [comment]
Thanks, this problem is solved.
