### ISSUE TITLE
预览 button 消失

### ISSUE THREAD

**Issue by xinatcg** [suziwen/markdownxiaoshujiang#1452]
我之前设置预览为 浮动窗口，但是下次再打开发现预览的 button 没有了，而且没有浮动窗口，我该怎么把预览找回来呢？
![image](https://user-images.githubusercontent.com/55399567/103532470-331aaa80-4e83-11eb-9385-d3cb25852b2e.png)

**Comment by suziwen** [comment]
试一下下面这些操作

1. 新建一篇文章
2. 关闭文件列表
3. 最大化窗口
4. 重启小书匠
5. 按 `ctrl+shift+p`
