### ISSUE TITLE
邮件发送功能似乎有问题

### ISSUE THREAD

**Issue by nemo95** [suziwen/markdownxiaoshujiang#1456]
我用来推送kindle的smtp邮箱配置一直使用正常，但小书匠用相同的配置后虽然提示发送成功，收件箱和垃圾箱里却都找不到

**Comment by suziwen** [comment]
感谢反馈， 这个确认是 bug. 

现在无论是发送成功还是失败，都提示 “发送成功”。

**Comment by suziwen** [comment]
`8.5.0` 已修复。
