### ISSUE TITLE
小书匠markdown在线版的 bug

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#146]
我用的是chrome 41.0.2272.118 m，在小书匠的在线版里面编辑markdown，选择一部分经常出现自动帮我全选的问题，很挠人。
另外一个问题，左侧编辑窗口，不能复制内容。没提示，只是粘贴的时候实际上应该是一个不可打印的字符，右侧的预览窗口可以复制

望修复

**Comment by suziwen** [comment]
这边没有出现你说的这种情况。
建议chrome版本最好升到最近的两个版本。
或者试着用另外两个编辑器
目前web版本提供的编辑器有 `ace`, `codemirror`, `轻量`
![screenshot_2016-03-02_15-07-50](https://cloud.githubusercontent.com/assets/57370/13453141/b92e9bb8-e088-11e5-9506-0d8922fdddd3.png)

**Comment by epluguo** [comment]
刚又试了一下，知道原因了，是因为我的chrome安装了 拖拽搜索 插件，禁用掉就可以了
