### ISSUE TITLE
[freature] 同时绑定多个仓库

### ISSUE THREAD

**Issue by Wang-Bo-xuan** [suziwen/markdownxiaoshujiang#1468]
不能同时同步多个仓库，我想同步多个仓库，现在关闭一个现有同步绑定，再开启新的同步绑定，文档更新完成后再绑定回最初的仓库；例如：一个是公司工作机文档目录，一个是家用nas上的个人文档目录，一个印象笔记

**Comment by suziwen** [comment]
可以`另存为`，先择另一个仓库.

**Comment by Wang-Bo-xuan** [comment]
看到了 在另存为对话框左下角可以选择其他仓库或本地 感谢
