### ISSUE TITLE
windows桌面版不能编辑同步到印象笔记的内容？

### ISSUE THREAD

**Issue by smashell** [suziwen/markdownxiaoshujiang#147]
版本1.8.0
双击印象笔记附件中的md文件，编辑后点保存，只是附件md文件变了，印象笔记的内容没有更新啊

**Comment by suziwen** [comment]
系统还没办法直接通过点击印象笔记中的md文件来修改笔记，需要绑定，导入再保存。

**Comment by smashell** [comment]
多谢@suziwen
