### ISSUE TITLE
代码高亮支持bash、shell、console吗？

### ISSUE THREAD

**Issue by editcue** [suziwen/markdownxiaoshujiang#1470]
写一些linux命令的代码块，试过bash、shell、console似乎都不行

**Comment by suziwen** [comment]
高亮使用的是 [highlight.js ](https://highlightjs.org/static/demo/)

bash, shell, console 都有的， 其中 shell == console

![image](https://user-images.githubusercontent.com/57370/106277476-2ae04000-6274-11eb-9e17-161b1568c1e3.png)
