### ISSUE TITLE
[bug] 浮动编辑器最大化后无法退出

### ISSUE THREAD

**Issue by Wang-Bo-xuan** [suziwen/markdownxiaoshujiang#1479]
如题
另外，浏览有窗口模式，为什么编辑器没有窗口模式。。。

也可能有，但我没看见，麻烦回复下。

3q

**Comment by suziwen** [comment]
不能退出是没有那个关闭图标吗，还是点击关闭图标关闭不了？能截个图看下浮动编辑器最大化的效果？

-----------

编辑器暂时不考虑单独的窗口模式。

**Comment by Wang-Bo-xuan** [comment]
是没有最大化的那个按钮了，标题栏是无色的一条，没有截图，暂时还未复现；
今天再测试就有最大化的开关了，可以正常放大、缩小；

不过更新最新版本后，发现一个问题，就是以前绑定的导出库全失效了
最大化bug出现后有登陆过web端，发现web端没有同步数据就下了，今天再更新就不见了绑定导出库，不确定是什么原因

**Comment by suziwen** [comment]
不明白你的绑定导出库全失效具体是什么效果。

如果想让自己的配置文件在不同的客户端同步的话，需要会员才有这个功能，然后还要自己在`用户管理 > 用户配置` 里把这些选项打开。

还有一种情况就是登录用户退出后，配置信息(包括绑定信息)会切换为退出前的状态。

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/109745503-ef3beb80-7c0e-11eb-9a91-6cd94b1215e3.png)

**Comment by Wang-Bo-xuan** [comment]
是会员，而且已经有过多台机器同步的经历。
但是昨天出现浮动编辑器最大化无法关闭后，我上了web端想看看是不是一样最大化了，
登录web端后发现，账户和设置（如上图）都是正确的，但是没有绑定，然后就关闭web tab没有管了（没有退出账号），
今天更新程序后，客户端的绑定就全都没有，不确定是更新造成的（以前更新不会）还是登录web造成的。

**Comment by suziwen** [comment]
登录其他端，同步配置信息估计要等待一会，网络传输也需要时间。

---------

更新程序后，客户端的绑定没有，这个应该跟更新程序和 web 登录都没有关系。

能说下你的 id 吗， 我看一下什么原因造成的。

**Comment by Wang-Bo-xuan** [comment]
@8905

**Comment by suziwen** [comment]
你现在又自己重新绑定好了？

**Comment by suziwen** [comment]
你是不是登录 web 端后， 看到没有绑定信息，就自己重新在 web 端执行绑定？

**Comment by Wang-Bo-xuan** [comment]
我今天在客户端重新绑定了，
昨天登录web后发现绑定失效，直接就关闭网页了，好像没操作什么，
今天发现后在客户端重新绑定的。

**Comment by suziwen** [comment]
感觉就是 web 的绑定信息覆盖了服务器保存的配置，后继这边再提供一个配置信息历史记录的功能，这样可以从历史记录里恢复配置。
