### ISSUE TITLE
linux客户端中文输入问题

### ISSUE THREAD

**Issue by Cppowboy** [suziwen/markdownxiaoshujiang#148]
在linux客户端中，输入中文时会出现无法输入的情况，多打几次也能输进去。
比如，想打出“国”字，可能“国”字第一次打不出来，多试几次也能打出来。
LinuxMint17.3
fctix

**Comment by suziwen** [comment]
客户端版本号？
使用什么编辑器,ace?轻量？
什么桌面环境，kde?,gnome3?gnome经典？

**Comment by Cppowboy** [comment]
客户端版本号：1.8.0
编辑器：ace
桌面环境：linuxmint cinnamon(百度百科：Cinnamon由Clement Lefebvre,Linux Mint创始的一个桌面交互环境，试图提供一个布局类似于GNOME 2，含有一个底部面板和启动器器，GNOME2-like系统托盘和通知等工具。)



--

﻿﻿潘寅旭
Pan Yinxu
清华大学计算机科学与技术系
Department of computer science and technology
tel:15652919913
email:panyx93@163.com
panyxkr@qq.com
panyx.cpp@gmail.com
address:清华大学紫荆二号楼109A

在 2016-03-09 00:04:24，"苏滋文" <notifications@github.com> 写道：


客户端版本号？
使用什么编辑器,ace?轻量？
什么桌面环境，kde?,gnome3?gnome经典？

**Comment by suziwen** [comment]
嗯，测试了下，感觉像是 ace 和 fcitx 在焦点处理上出现问题。不过奇怪的是我在web端就没有这种情况。
可以暂时考虑换种输入法或者用轻量编辑器，下个版本会再添加个 codemirror 编辑器。

**Comment by Cppowboy** [comment]
的确，在web端没有问题，在客户端上才会有这种问题。
