### ISSUE TITLE
bug 手动输入图片地址，预览区全部失效。

### ISSUE THREAD

**Issue by Abirdcfly** [suziwen/markdownxiaoshujiang#149]
我用来编辑HEXO的文章。上传Github io博客。
因为图片地址要这么写：
![冒泡排序](/resources/maopao.gif)
会在HEXO编译过程中导入图片。直接访问./resources/maopao.gif 是找不到图片的。
这时候，小书匠的预览界面就完全崩掉了。。

**Comment by suziwen** [comment]
如果是win版本的话，可以把resources的目录也放一份到安装目录下临时解决，下个版本修复。
