### ISSUE TITLE
为什么全屏阅读模式不是真正的全屏？页面四周留下很大的空白。设置->全屏->百分比 -调节这个百分比也不起作用

### ISSUE THREAD

**Issue by benzbj** [suziwen/markdownxiaoshujiang#1492]
如果笔记里有一张比较复杂的思维导图，不是真正的全屏的话看不清楚，页面四周留下那么大空白很浪费空间啊。

**Comment by suziwen** [comment]
截几个图，看看你说的效果
全屏设置页面的截图，全屏阅读后的页面效果截图

**Comment by benzbj** [comment]
就是这样
![小书匠截图](https://user-images.githubusercontent.com/81525536/113089661-b47fa000-921a-11eb-9270-37c6c4c6c628.png)

**Comment by suziwen** [comment]
你的设置是不是不对，我设置成  100%, 两边的空隙就几乎没有了


![image](https://user-images.githubusercontent.com/57370/113089884-2526bc80-921b-11eb-9607-ec61d9bc3e62.png)
![image](https://user-images.githubusercontent.com/57370/113089995-5a330f00-921b-11eb-9e3f-ea0b9a7d4359.png)

**Comment by suziwen** [comment]
其实像你这个需求，还可以通过打开独立窗口预览功能

![image](https://user-images.githubusercontent.com/57370/113090186-c9a8fe80-921b-11eb-8c64-8b47f6864b42.png)

**Comment by suziwen** [comment]
再有，就是在分屏预览的预览区，图片可以点击后使用鼠标放大，缩小，移动。

![image](https://user-images.githubusercontent.com/57370/113090776-1b9e5400-921d-11eb-80a3-b9713cf6275e.png)

**Comment by benzbj** [comment]
我已经在设置里设成100%了，好像不起作用。已经多次尝试了。全屏预览页面四周还会有很大的空白。
--------------------
独立窗口的方式确实基本上能全屏了。但是在这种界面按住ctrl+鼠标滚轮不能放大，显示出来多大就是多大，如果图很大的话还是会不太方便。
-------------------
分屏预览的预览区点击图片确实可以放大缩小，移动...这是一个变通的做法，就是阅读体验不太好。
------------------
理想的界面还是在点击全屏阅读按钮后能真正全屏，且在这个界面点图片可以再进一步放大缩小，移动等...请看下是不是能达到这个效果，非常感谢！

**Comment by suziwen** [comment]
`100%` 不生效，应该是你用的不是数字的 `100` 或者 `100` 前后有空格引起的，**确保数字是半角英文状态下的 `100` ,前后没有空格**

**Comment by benzbj** [comment]
又仔细检查了一下，我输入的是100%， 应该把“%”去掉，直接写数字100就行了：）

另外一个问题，就是在全屏阅读页面，点击页面里的图片能加上放大缩写移动功能吗？感谢！

**Comment by suziwen** [comment]
> 另外一个问题，就是在全屏阅读页面，点击页面里的图片能加上放大缩写移动功能吗？

这个后面会加上的。

**Comment by benzbj** [comment]
好的，谢谢
