### ISSUE TITLE
Evernote和小书匠标签冲突时无法使用服务器版本

### ISSUE THREAD

**Issue by catwang01** [suziwen/markdownxiaoshujiang#1495]
在印象笔记中修改完标签之后在小书匠中保存时会弹出，”服务器标题(标签) 被其他客户端修改过，是否覆盖？“。其中的 “使用服务器版本”选项点击没有效果。

**Comment by suziwen** [comment]
确认 bug,感谢反馈.

**Comment by catwang01** [comment]
看到已经修复啦，就关闭了，辛苦辛苦
