### ISSUE TITLE
印象笔记加载文件列表失败

### ISSUE THREAD

**Issue by wushuangcoder** [suziwen/markdownxiaoshujiang#1498]
加载文件列表出现错误{"code":1006,"error":"服务器出错....{\"errorCode\":9,\"parameter\":\"authenticationToken\"}","orign":{"errorCode":9,"parameter":"authenticationToken"}}

我试过退出重登，没有用。可能是我会员到期，导致的问题，但我已经续费了。

**Comment by suziwen** [comment]
印象笔记帐户会话过期， token 失效了，重新绑定一下印象笔记就可以了。
