### ISSUE TITLE
bug?字符显示

### ISSUE THREAD

**Issue by Abirdcfly** [suziwen/markdownxiaoshujiang#150]
某些情况会出现叠字与挤字？
![00c40350-e642-11e5-8c20-308b4971fe38](https://cloud.githubusercontent.com/assets/5100555/13637443/5697c76c-e642-11e5-8f1a-ea2ed6c62a80.png)

PS: 感觉我适合做测试了。。。
提bug提的我都不好意思了。。。

**Comment by suziwen** [comment]
这个倒没遇见过 。编辑器里的字体没用等宽字体？
主要是软件还有比较多地方需要改进，也感谢热心反馈。

**Comment by Abirdcfly** [comment]
默认字体。
感谢免费和开源。
THX。

**Comment by suziwen** [comment]
调整编辑区大小，或者上下拉滚动条，会重新出现这些错位吗？
下次打开时也一样错位？

**Comment by Abirdcfly** [comment]
调整编辑区大小，会在边缘出现错位，位置不规律。
上下拉滚动条，还是出现在原文的对应位置。
目前只发现会出现在有多个项的无序列表中间。

**Comment by suziwen** [comment]
要是能把这篇文章发过来测试下那是最好了，suziwen1#gmail.com
感觉最大的可能就是字体的问题，ace编辑器是只能用等宽字体来处理的，不然很容易就错位的。
先记下来。下个客户端版本会添加个默认的codemirror编辑器。

**Comment by Abirdcfly** [comment]
好的。不过得明天了，笔记本电池不行了。学校还断电。。

**Comment by suziwen** [comment]
这个看来是 ace 编辑器在计算布局时出错了， 你可以把文章贴这里 https://ace.c9.io/build/kitchen-sink.html 测试下，也是有这种情况。
暂时解决方案就是手动调整下编辑区的宽度直到不错位。
先记下来了，等第三方有更新再一起修复。
![screenshot_2016-03-10_21-33-46](https://cloud.githubusercontent.com/assets/57370/13671021/5a51d71e-e708-11e5-82af-ffcc8db91c59.png)
