### ISSUE TITLE
手机版《花田日记》闪退

### ISSUE THREAD

**Issue by qingchuwudi** [suziwen/markdownxiaoshujiang#1506]
华为 P20，安装《花田日记》以后前三次打开会闪退，第四次后不再有问题。

**Comment by suziwen** [comment]
卸载后，再安装，然后启动也是前几次会闪退？

-------

注：　卸载时，会清空重置本地数据。

**Comment by qingchuwudi** [comment]
没有卸载，反复启动了几次后面不再闪退就没再管

**Comment by suziwen** [comment]
嗯，好的。那等后继看看有没有其他用户有类似的情况。

**Comment by qingchuwudi** [comment]
又出现了，昨天反复闪退了10多次，今天闪退了2次

**Comment by suziwen** [comment]
更新到 [0.0.3](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/Android_Beta_0.0.3)

然后如果再出现闪退的话，可以到关于界面里看一下日志文件，看有什么错误信息

**Comment by qingchuwudi** [comment]
排查了下，发现没有给存储权限，给了存储权限以后到目前没出过问题。

话说，安装软件、启动软件的过程中没有弹出存储权限的提醒，也没有默认分配权限，这里可以优化下。

**Comment by suziwen** [comment]
嗯，后面会改进下。

**Comment by qingchuwudi** [comment]
已解决，是存储授权问题，多谢帮助 :)
