### ISSUE TITLE
版本8.5.0更新至8.5.16失败

### ISSUE THREAD

**Issue by wushuangcoder** [suziwen/markdownxiaoshujiang#1507]
![image](https://user-images.githubusercontent.com/26687424/120077294-5d902d00-c0dc-11eb-83c8-32a9e113a6eb.png)

**Comment by wushuangcoder** [comment]
系统版本：macOS 11.3.1 (20E241)
电脑：MacBook Pro (15-inch, 2019)

**Comment by suziwen** [comment]
可能是网络问题造成更新文件下载失败，
可以再重启下小书匠，或者到关于界面，重新更新升级。

**Comment by anony-ghost** [comment]
window端遇到同样的问题，退出重启都没有解决

**Comment by suziwen** [comment]
@anony-ghost 在关于界面里，有个数据文件目录的路径，把该文件夹临时移走，然后再启动小书匠，如果还不能升级的话，感觉应该跟你的网络有关。

**Comment by anony-ghost** [comment]
> @anony-ghost 在关于界面里，有个数据文件目录的路径，把该文件夹临时移走，然后再启动小书匠，如果还不能升级的话，感觉应该跟你的网络有关。

我把storywriter\User Data\Default这个文件夹临时移走了，再启动小书匠，在关于界面上显示当前版本和服务器端最新版本都是8.50，还是无法更新，我这边能正常上网，不知道啥原因

**Comment by suziwen** [comment]
@anony-ghost  这个在线更新只对会员提供，普通用户只能到网站指定地址下载客户端，普通用户在关于界面上看到的当前版本和服务器版本一致，就表明是最新版本了。


一般没有什么大的 bug, 或者只针对会员功能修改的，都不会单独发布客户端。

**Comment by wushuangcoder** [comment]
系统版本：5.4.0-74-generic #83~18.04.1-Ubuntu
同样的问题，尝试的方法：
- 移除数据文件
- 切换网络（联通，移动，WiFi，流量）
- 挂vpn（香港，美国，日本）
以上方法无用

**Comment by wushuangcoder** [comment]
在关于界面点击升级，出现同样的问题。

**Comment by suziwen** [comment]
@wushuangcoder 再升级下，升级 android 0.0.2 版本时，把地址放错了。
