### ISSUE TITLE
bug？Windows版本直角引号问题及高清支持

### ISSUE THREAD

**Issue by AshYao** [suziwen/markdownxiaoshujiang#151]
首先真的喜欢这个软件，感谢作者！
不过Windows版本使用时发现，在`文字**「文字」**文字``的情况下软件无法正确显示预览，不知道是否是个人操作问题？
另外，很希望新版能够支持高清屏幕，Surface上显示有点模糊。
<img width="754" alt="wxid_kc2x5qrsn98y12_1457887957072_66" src="https://cloud.githubusercontent.com/assets/17813752/13730055/3874562a-e97f-11e5-8c82-a5e3cd806103.png">

**Comment by suziwen** [comment]
前后加一个空格

`文字 **「文字」** 文字的情况`
就可以了。
