### ISSUE TITLE
尖角号导致表格显示异常

### ISSUE THREAD

**Issue by ygqygq2** [suziwen/markdownxiaoshujiang#1514]
如下图，不管加不加反引号，都显示异常。

![image](https://user-images.githubusercontent.com/17672440/125382282-f991a180-e3c7-11eb-8049-0f847e1b1195.png)

**Comment by suziwen** [comment]
可以把当前文章的增强型表格语法关掉

`grammar_tableExtra: false`


![image](https://user-images.githubusercontent.com/57370/125392426-bd1a7180-e3d8-11eb-931b-98961a09a1dc.png)
