### ISSUE TITLE
虚拟机win1064位，加载插件界面转圈半小时

### ISSUE THREAD

**Issue by lixiao123** [suziwen/markdownxiaoshujiang#152]
下载了最新的180无法打开，加载插件界面转圈半小时还进不去，但是171是可以使用的额

**Comment by lixiao123** [comment]
刚刚发现，在装win虚拟的linux(gentoo)上也无法打开1.8.0了，附上启动时抓的日志以及story-exception.log日志，希望能帮到忙
[Story-1.8.0_log.txt](https://github.com/suziwen/markdownxiaoshujiang/files/187365/Story-1.8.0_log.txt)

[story_exceptions.log.txt](https://github.com/suziwen/markdownxiaoshujiang/files/187368/story_exceptions.log.txt)

**Comment by suziwen** [comment]
这个错误可能是要预览的文件有问题。
linux上试着关联打开一个空白的markdown文件呢？， 比如

```
echo tt>new.md
./Story-writer {绝对路径}/new.md
```
如果还是不行的话，
试一下把 `~/.config/小书匠` 目录临时改一下其他名称，看能否正常起来

**Comment by suziwen** [comment]
你自定义字体了？填的什么值

**Comment by lixiao123** [comment]
搞定了，应该是自定义字体的问题。。删掉Local Storage目录就可以了，不过这块填的值不能用应该启用默认才合适吧，直接起不来用户会完全不知所措的
感谢帮忙～

**Comment by lixiao123** [comment]
Windows和Linux都应该是这个问题，我各自删掉Local Storage目录，都可以正常启动了
