### ISSUE TITLE
两年+的书匠老粉给小书匠的下载的一点建议（不知道提在哪里）

### ISSUE THREAD

**Issue by myhuibbaoqi** [suziwen/markdownxiaoshujiang#1521]
从第一次写博客大概两年多了，用了小书匠卸载了别的所有markdown编辑器。
图床绑定好评，绑定第三方存储博文好评，页面绚丽，主题丰富各种好评。今天只吐槽一点！

小书匠的下载，弊端明显，缺少直接下载链接，导致介绍给朋友被嫌弃。
![图片](https://user-images.githubusercontent.com/50536515/126856402-2615242d-7a92-4b17-bd04-0be5fa30f9d8.png)
1. github下载，github经常被墙，大家应该都遇见过，需要下载时正好被墙，各种转圈圈。失败
2. gitee下载，与github少了被墙烦恼，但下载链接在最下方，好一顿翻，第一次进来一脸懵逼。
3. 百度网盘，新机装了阿里云盘，文件已经从百度网盘迁移至阿里云盘。真心不想用那几kb的网速了。。。根本没下百度网盘

吐槽结束，给建议。
直接在官网给出下载按钮，一键直下。云存储费用并不贵吧，实在不行搭个文件服务器下载慢点也行，但让我简单点，我换个电脑首次安装的时候，真的只想一键下载。不想各种跳转！！！

**Comment by myhuibbaoqi** [comment]
另外建议第三方绑定如果能云存储一下就好了，我换机较多，每次重装要配置好久。可能是我姿势不对。。。 没找到

**Comment by suziwen** [comment]
非常感谢一直以来对小书匠的支持。

以前是有提供直接下载链接的，后来发现很多第三方下载平台就直接用这个下载链接，造成网络拥堵，就给去掉了。

推荐给朋友的话，可以先给出小书匠的 [web](http://markdown.xiaoshujiang.com) 版本直接使用，这样就不需要下载安装文件，也能第一时间体验小书匠的功能。

后续的话，会考虑添加一个阿里云盘的下载方式。

------

第三方存储绑定的配制同步需要会员功能的，而且需要会员自己在`主按钮/用户/配置/配置同步`里，打开相关选项的。因为配置参数的同步需要把配置数据保存到小书匠服务器上，考虑到数据隐私及安全问题，该选项默认是关闭的。

同样的，其实文章也是可以同步的，只要在`主按钮/数据/同步`里，配置好同步服务器，切换电脑后，文章就可以自动同步过来的，详细的介绍可以看[这里](http://soft.xiaoshujiang.com/docs/tutorial/database/)

**Comment by myhuibbaoqi** [comment]
OK，已经了解，后续来个阿里云盘的链接就好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "suziwen/markdownxiaoshujiang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月25日(星期天) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [suziwen/markdownxiaoshujiang] 两年+的书匠老粉给小书匠的下载的一点建议（不知道提在哪里） (#1521)





 
非常感谢一直以来对小书匠的支持。
 
以前是有提供直接下载链接的，后来发现很多第三方下载平台就直接用这个下载链接，造成网络拥堵，就给去掉了。
 
推荐给朋友的话，可以先给出小书匠的 web 版本直接使用，这样就不需要下载安装文件，也能第一时间体验小书匠的功能。
 
后续的话，会考虑添加一个阿里云盘的下载方式。
 
 
第三方存储绑定的配制同步需要会员功能的，而且需要会员自己在主按钮/用户/配置/配置同步里，打开相关选项的。因为配置参数的同步需要把配置数据保存到小书匠服务器上，考虑到数据隐私及安全问题，该选项默认是关闭的。
 
同样的，其实文章也是可以同步的，只要在主按钮/数据/同步里，配置好同步服务器，切换电脑后，文章就可以自动同步过来的，详细的介绍可以看这里

**Comment by myhuibbaoqi** [comment]
![图片](https://user-images.githubusercontent.com/50536515/127437535-5f84fd38-ef1c-4a87-8f10-060a312a43c4.png)
很棒，听得进建议。支持一年会员！
