### ISSUE TITLE
Ace编辑器输入的字符后面会多几个空格

### ISSUE THREAD

**Issue by rguo97** [suziwen/markdownxiaoshujiang#1522]
Ace编辑器输入的字符后面会多几个空格，字符越多，输入光标和文件的间隔越大。通过移动光标，我发现这些间距是空格，可是删掉这些空格的时候会发现会把已有的文本删掉。我不了解Ace编辑器，是它本来的特性吗，还是一个bug？在使用文档中也没有这样类似的说明。

**Comment by suziwen** [comment]
可能跟你系统的字体有关，Ace 编辑器需要使用等宽字体，如果操作系统里没有相关的等宽字体，就会造成光标错位。你可以试着切换成 Codemirror 编辑器，如果能恢复正常，但重新再切换成 Ace 编辑器后，又是错误的话，就可以肯定是字体问题了。

要自定义字体的话，可以到 `设置>基本` 里修改 css 样式，或者 `设置>编辑器` 里修改字体。

**Comment by rguo97** [comment]
> 可能跟你系统的字体有关，Ace 编辑器需要使用等宽字体，如果操作系统里没有相关的等宽字体，就会造成光标错位。你可以试着切换成 Codemirror 编辑器，如果能恢复正常，但重新再切换成 Ace 编辑器后，又是错误的话，就可以肯定是字体问题了。
> 
> 要自定义字体的话，可以到 `设置>基本` 里修改 css 样式，或者 `设置>编辑器` 里修改字体。


已经修改了，多谢
