### ISSUE TITLE
[同步]多客户端同步

### ISSUE THREAD

**Issue by yolo079** [suziwen/markdownxiaoshujiang#1530]
请问一下，不同客户端有没有一键同步的功能- - 

\----------------------------------------------------------------------------------------------------------------------------------
``` markdonw
当前版本: 8.6.2(8.3.0)
服务器最新版本: 8.6.1

有电脑A、B，账号绑定了印象笔记
A中有文章X，
某日备份数据，将A的数据库备份导入电脑B
```

当日在B中编辑了X（在A备份的基础上），并保存到印象笔记。

翌日，直接在A中继续编辑（忘记A还没同步B后续编辑内容），直接通过`ctrl + s`保存，自动同步到了印象笔记（**无**服务器、本地的版本选择**提示框弹出**）。
然后现在`A`、`印象`中都没了B编辑的内容，只有到B电脑重新保存同步，但是B直接上传又没有了A中后续保存同步的内容- - 
\----------------------------------------------------------------------------------------------------------------------------------
小书匠做得挺好的，就是偶尔的同步问题，搞得挺纠结的，手机也下了客户端，但是好像也得考虑同步问题，所以暂时懒得折腾- -。
请问有没有较为科学的同步方法推荐，谢谢！

**Comment by suziwen** [comment]
如果是会员的话，可以打开同步功能，大致原理可以查看这个[文档](http://soft.xiaoshujiang.com/docs/tutorial/database/)。
具体点操作就是 `主按钮>用户>配置>是否实时同步客户端配置` 等相关选项打开，然后再`主按钮>数据>同步>同步配置` 里选择一种同步方案，比如服务器选择`小书匠`.(记得选择完后，要点击`应用` 按钮).
![image](https://user-images.githubusercontent.com/57370/129286979-0a29582f-e115-44c0-974f-0c295109567f.png)

![image](https://user-images.githubusercontent.com/57370/129286997-ebb9db08-ed9e-4dee-9529-47e96e82394f.png)



有影笔记的操作就是 `主按钮>配置>同步`

会员才有这个同步功能，而且必须自己手动打开，同时如果想自己配置数据服务器的话，可以参考这篇[文章](http://soft.xiaoshujiang.com/blog/setup_custom_couchdb_server)

----------------

如果不是会员，或者不想使用同步功能的话，就需要自己记住自己保存到第三方存储的时间，在滞后的小书匠客户端里，右键第三方存储文件树列表项，选择`更新本地缓存`菜单项，这样小书匠就会把第三方存储的内容覆盖更新到本地。

![image](https://user-images.githubusercontent.com/57370/129286922-2ee04fea-7027-4994-a67f-ac576e5855f5.png)

**Comment by yolo079** [comment]
谢谢解答，非常详细！
会员从去年就开通了，只是看提示发现小书匠的服务器是临时性的，所以就没勾选。
有空了研究下自定义模式，
顺祝小书匠越搞越好！
