### ISSUE TITLE
[建议]我在编辑同步在github上的md的时候习惯写一点就ctrl+s以下,但是目前的版本触发了太多的commit

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1532]
我在编辑同步在github上的md的时候习惯写一点就ctrl+s以下,但是目前的版本触发了太多的commit.
希望有个`中间态`就是,`Ctrl+S`本身只是保存,有一个`sync`按钮或者是定时5min的时候`sync`一次可以减少commit
数量.
或者,如果我使用自定义的服务器可以解决这问题?

**Comment by suziwen** [comment]
可以通过 `主按钮>按键`界面，自己绑定快捷键，相关命令说明可以看这个[文档](http://soft.xiaoshujiang.com/docs/tutorial/commands/)，根据你的需求，涉及到的命令大概有 `save`, `saveInternal`, `saveAs`, `passtoDefault` 和 `preventToDefault`. 

绑定快捷键的文档可以看[这里](http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/)

比如 把 `ctrl+s` 操作禁用掉，自己添加连继按两次 `ctrl+s ctrl+s`  才真正触发保存等。
