### ISSUE TITLE
[BUG] 自定义类不生效，导出语法手册，html文件中没有发现green class

### ISSUE THREAD

**Issue by shadowfish07** [suziwen/markdownxiaoshujiang#1533]
版本：8.6.2 
操作环境：win10

**Comment by suziwen** [comment]
感谢反馈。

不过这个不算 bug, 只是内置语法使用手册没说明清楚，该语法和 `grammar_attrs` 和 `grammar_decorate` 语法会有冲突，需要禁用这两个语法才可以。下个版本会把这些提示添加上去。

`grammar_classy` 语法详细的说明可以查看官网的说明[文档](http://soft.xiaoshujiang.com/docs/grammar/advance/class/)，这里就有指出这个注意项。

**Comment by shadowfish07** [comment]
> 感谢反馈。
> 
> 不过这个不算 bug, 只是内置语法使用手册没说明清楚，该语法和 `grammar_attrs` 和 `grammar_decorate` 语法会有冲突，需要禁用这两个语法才可以。下个版本会把这些提示添加上去。
> 
> `grammar_classy` 语法详细的说明可以查看官网的说明[文档](http://soft.xiaoshujiang.com/docs/grammar/advance/class/)，这里就有指出这个注意项。

感谢，再指出个小错误，官网这边指向decorate和attrs的链接404啦
