### ISSUE TITLE
[咨询]使用图床转换功能后,出现大量拥有类似![./attachments/****.jpg](链接的图片

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1535]
类似这样:
![image](https://user-images.githubusercontent.com/30266323/129711166-a5840827-6b42-4976-89a5-bf719a55f90d.png)
大约有50%,其他的图片可以转移图床成功?
搞得我只能一个一个图片处理
求助

**Comment by suziwen** [comment]
图床迁移是把新生成的图床地址通过全局替换旧地址实现的，如果文章里有字符串是跟旧地址一样，也是会被替换的。

比如旧图片的地址是 `http://xxx.com/a.jpg`, 然后你的文章里是下面的内容

```
只是个链接 http://xxx.com/a.jpg

图片 ![](http://xxx.com/a.jpg)


图片说明里也带了链接 ![http://xxx.com/a.jpg](http://xxx.com/a.jpg)

```

迁移后的图片地址是 `http://yyy.com/b.jpg`

则对应的文章就会变成这样

```
只是个链接 http://yyy.com/b.jpg

图片 ![](http://yyy.com/b.jpg)


图片说明里也带了链接 ![http://yyy.com/b.jpg](http://yyy.com/b.jpg)
```

**Comment by lqdflying** [comment]
> 图床迁移是把新生成的图床地址通过全局替换旧地址实现的，如果文章里有字符串是跟旧地址一样，也是会被替换的。
> 
> 比如旧图片的地址是 `http://xxx.com/a.jpg`, 然后你的文章里是下面的内容
> 
> ```
> 只是个链接 http://xxx.com/a.jpg
> 
> 图片 ![](http://xxx.com/a.jpg)
> 
> 
> 图片说明里也带了链接 ![http://xxx.com/a.jpg](http://xxx.com/a.jpg)
> ```
> 
> 迁移后的图片地址是 `http://yyy.com/b.jpg`
> 
> 则对应的文章就会变成这样
> 
> ```
> 只是个链接 http://yyy.com/b.jpg
> 
> 图片 ![](http://yyy.com/b.jpg)
> 
> 
> 图片说明里也带了链接 ![http://yyy.com/b.jpg](http://yyy.com/b.jpg)
> ```

转换前地址:`https://pic1.zhimg.com/v2-7580b92db7de668a48e8839360417630_b.jpg`
转换后地址:`./attachments/1629251490131.jpg`

不懂,为什么转换出来一个`attachments`,这个`attachments`是个本地HTML引用,commit到`github`就无效了,我得挨个改

**Comment by suziwen** [comment]
这个 `attachments` 是根据文件类型判断的，如果是图片，就会变成 images, 如果是其他的，就会变成 `attachments` , 这个可以在 `设置>基本>资源路径>资源名称` 里调整。

注:
这里系统不是通过扩展名来判断是否图片，而是根据返回的 content-type 来判断的。

---------------

如果配置了默认第三方存储，比如 github, 通过图床迁移的图片，是不会把迁移成功后相对路径的图片资源自动提交到 github 上的，需要自己`另存为`，这样系统就会把这些资源都提交到 github 上了。

**Comment by lqdflying** [comment]
> 而是根据返回的 content-type 来判断的。

我大概理解了下:
- content-type不是图片的,但是url的结尾是类似`jgp`结尾的,依然会被转换成附件也就是`attachment`这种相对路径
- content-type是图片的,会自动上传图床

我特地做了以下这个例子:
```md
![https://pic2.zhimg.com/v2-f0c70714ddb87c75b9d67bce41187da5_b.jpg](https://pic2.zhimg.com/v2-f0c70714ddb87c75b9d67bce41187da5_b.jpg)

![https://pic2.zhimg.com/v2-4ce45e183980af622e93b8802ac814bd_b.jpg](https://pic2.zhimg.com/v2-4ce45e183980af622e93b8802ac814bd_b.jpg)
```
- 第一个的content-type是`content-type: application/octet-stream`,因此会被转换为附件`attachment`
- 第二个的content-type是`content-type: image/jpeg`,因此会被自动上传到图床

那么问题来了,
第一个明显是个图片哈,**可以根据扩展名匹配以下吗,或者加个开关,勾选后,会自动匹配`png/ipeg/...`等等后缀的文件名,然后上传图床**

**Comment by suziwen** [comment]
我看一下，应该可以。

------

设计成　content-type ，当时主要是考虑有些图片可能不会有扩展名，或者通过扩展名实现大小切割等，比如 `http://xxx.com/a.jpg/w200/h300`。就像有些浏览器，打开这些连接，通过　content-type 判断，如果是图片就直接显示，如果是其他的，就会变成下载。

**Comment by lqdflying** [comment]
嗯,但是就像B乎这种反人类的,他是反着来的,扩展是`jpeg`,居然不好好设定`content-type`,重点是,他还真的是个图片.

**Comment by suziwen** [comment]
web 版 8.6.4 调整了图床迁移判断方式。

**Comment by lqdflying** [comment]
tested the updated feature, it works well.
tks:)

**Comment by chenbofeng123** [comment]
请问怎么调整啊



这个 attachments 是根据文件类型判断的，如果是图片，就会变成 images, 如果是其他的，就会变成 attachments , 这个可以在 设置>基本>资源路径>资源名称 里调整。

注:
这里系统不是通过扩展名来判断是否图片，而是根据返回的 content-type 来判断的。

**Comment by suziwen** [comment]
@chenbofeng123  客户端要在下个版本发布才会修正这情况，web 版本已经修复，可以先用 [web](http://markdown.xiaoshujiang.com/) 版的图床迁移。
