### ISSUE TITLE
[需求]没有下划线

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1537]
没有下划线

**Comment by suziwen** [comment]
`设置>语法扩展>文字格式 插入` `grammar_ins`

```
++下划线++
```

**Comment by suziwen** [comment]
好像我的文档忘记添加了

**Comment by lqdflying** [comment]
> 好像我的文档忘记添加了

如何为下划线添加一个快捷键

**Comment by suziwen** [comment]
可以自己写个 CodeMirror 片段, 然后按键绑定到 insertSnippet 命令，指定片段的 id 为参数就可以了。具体的操作可以看这个[文档](http://soft.xiaoshujiang.com/docs/tutorial/snippet/#e9809ae8bf87e591bde4bba4e4bdbfe794a8e78987e6aeb5_15)

**Comment by suziwen** [comment]
类似这样

```
++${editorSelectionText}++${cursor}
```

![image](https://user-images.githubusercontent.com/57370/130378822-64d7f309-0070-4496-911c-999a026633a5.png)


![image](https://user-images.githubusercontent.com/57370/130378872-7d5210a2-add3-4735-a1a6-e5ca7ec0e8b1.png)

**Comment by lqdflying** [comment]
非常感谢

苏滋文 ***@***.***> 于2021年8月23日周一 上午9:44写道：
