### ISSUE TITLE
1.8.0 导出PDF格式问题

### ISSUE THREAD

**Issue by GuangY** [suziwen/markdownxiaoshujiang#154]
很感谢作者无私提供该软件,支持语法真心多.  
遇到问题:  
1. 导出PDF在文章头的[TOC]显示内容无链接.
2. 文章内链接只有颜色,无链接.
3. 图片没有显示,离线版预览中有显示,导出PDF无显示.导word同样图片不显示.

**Comment by GuangY** [comment]
> 图片没有显示,离线版预览中有显示,导出PDF无显示.导word同样图片不显示.  

这个经试验添加附件OK,原谅我操作上的无知 :laughing:

**Comment by suziwen** [comment]
可以试试web版的导出，
客户端的pdf导出功能有限，用的是这个工具 http://phantomjs.org/screen-capture.html
web版本pdf导出功能比较多，用的是 wkhtml2pdf, 由于 wkhtml2pdf license的限制，没有直接包含到客户端里，如果想客户端导出的pdf比较好些的话，暂时只能先导出 html,然后 自己下载 wkthml2pdf ，执行导出 pdf.

或者客户端的打印也是可以直接导出成pdf的。

**Comment by GuangY** [comment]
谢谢您的答复,web版解决我所有问题,希望做得越来越好！

**Comment by sjm111** [comment]
我也遇到文章内链接只有颜色,无链接的问题，用的web版本，请问您是怎么解决的？
