### ISSUE TITLE
关于账户安全问题

### ISSUE THREAD

**Issue by cworld1** [suziwen/markdownxiaoshujiang#1545]
建议提供更换电子邮箱、修改密码和注销（删除）账户功能。我在网页上没有看到类似的提供按钮。我的密码已经遭到泄露风险，同时我的邮箱号因为涉及qq账号，一直想要更改。希望能采纳建议。

**Comment by suziwen** [comment]
用户退出后，在登录页面，有一个找回密码的子页面，通过这个页面就能找回密码。

暂不提供修改邮件地址和注销功能。因为小书匠服务器并不提供用户数据存储服务，也不提供对外评论，发表文章等功能，注销按钮其实没太多意义。小书匠服务器也会为节省服务器开销，不定期清空非会员注册的用户。

小书匠的账户其实更像是 license 授权码功能，你完全可以用一个不存在的邮箱注册小书匠帐号，用支付宝等付完后，备注下 唯一 id 就可以等待确认升级会员了，以后到期了，完全可以不需要再管这个 id ,自己想重新注册一个新的也可以。不过用不存在的邮箱注册的话，就没办法找回密码，这时候就相当于你自己买的 license 要自己管理好密码。
