### ISSUE TITLE
提示 "is trusted true"

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1546]
不知道是什么原因导致大量出现这样的提示，持续好久了。
![image](https://user-images.githubusercontent.com/25471051/132094967-d1ecce88-840f-44cb-804c-37b0b4952da4.png)

**Comment by suziwen** [comment]
这个像是内置的数据库出问题了，可能是数据空间满了，或者硬盘有坏文件等原因。

可以先到`关于`界面里，查看数据文件夹位置，然后根据下面的情况操作。

1. 在操作前先自己备份一份数据文件
2. 然后如果平时没有保存其他第三方存储，而是把小书匠内置数据库做为存储方式的话，就要先执行`小书匠主按钮>数据>导出`　,进行数据导出
3. 导出完成后，就可以删除数据文件夹所在位置
4. 删除完数据文件夹后，启动小书匠，导入刚才导出的数据文件。
5. 如果自己使用第三方存储方案的话，可以直接删除数据文件夹，重启小书匠，再把第三方存储的数据导入就可以了。

**Comment by liao20081228** [comment]
不行仍然没有解决呢

**Comment by liao20081228** [comment]
目前绑定gittee的仓库和图床

**Comment by suziwen** [comment]
移走数据文件夹后，启动小书匠，新建文章编辑时，就有这个错误提示？还是说导入了特定的文章后，编辑时才会出现这个错误？

**Comment by liao20081228** [comment]
> 移走数据文件夹后，启动小书匠，新建文章编辑时，就有这个错误提示？还是说导入了特定的文章后，编辑时才会出现这个错误？

目前没有出现这个问题了，奇怪了

**Comment by liao20081228** [comment]
最近又出现这个问题？路由器开了双拨，是否有关？

**Comment by liao20081228** [comment]
看起来似乎是更新导致的。删除资源和文章数据库后好了
