### ISSUE TITLE
代码段不会自动补全结尾的```

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1551]
当我输入 ``` json后,敲个回车,希望可以自动添加一个空行,然后多一个结尾的三个`点点`,不然我每次都要手动打出来

**Comment by suziwen** [comment]
可以考虑用快捷键 <kbd>ctrl+k</kbd>,快速输入代码片段。这样操作的目的性比较强些，因为有时候用户可能只是想修改语法高亮的语言，并不是要创建一个新的代码块，像上面的操作感觉容易引起其他用户的困惑。
