### ISSUE TITLE
代码区一行内容过长时能不能有滚动条而不是自动换行

### ISSUE THREAD

**Issue by MandyCh** [suziwen/markdownxiaoshujiang#1554]
IOS系统
软件版本： 8.5.0
问题：代码区超出自动换行了
<img width="790" alt="1" src="https://user-images.githubusercontent.com/26193879/135816571-bd1b26e1-1a75-4726-9cbb-553ac045c648.png">
期望效果：不换行出现滚动条
<img width="681" alt="iShot2021-10-04 16 11 35" src="https://user-images.githubusercontent.com/26193879/135816728-79fc5884-77f2-4450-ba4e-55e386c64da2.png">
尝试改css但是没生效
<img width="678" alt="iShot2021-10-04 16 12 38" src="https://user-images.githubusercontent.com/26193879/135816855-396ceae7-47b6-4c28-ba1c-86bcdff1d69f.png">
不知道能否实现这样的效果

**Comment by suziwen** [comment]
```css
.hljs{
    white-space: pre;
    overflow-x: auto!important;
}
```

**Comment by MandyCh** [comment]
可以了，感谢
