### ISSUE TITLE
8.6.17版本新增的声音太吓人

### ISSUE THREAD

**Issue by 290760647** [suziwen/markdownxiaoshujiang#1555]
8.6.17版本新增的声音太吓人，刺耳又难听，是否有关闭设置或者修改声音？？？？？？？

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/137653617-847048ab-a1aa-47ff-9a25-e1b586978e93.png)

**Comment by suziwen** [comment]
或者

![image](https://user-images.githubusercontent.com/57370/137653771-9f02f55b-5532-4734-804a-8c7892abe79b.png)

**Comment by 290760647** [comment]
第一种方法可行，第二种方法我刚试了貌似不行，一会再看看，mac客户端，总之感谢了
