### ISSUE TITLE
Big Sur 11.6 频繁闪退

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#1556]
之前一直没有更新，用的Catalina，一切正常。最近更新至Big Sur11.6，已经发生过多次莫名闪退，不过都是发生在不输入的时候。在输入过程中没有发生闪退。

**Comment by suziwen** [comment]
有什么错误提示吗，错误日志或系统错误记录等。

看下 `关于` 界面里，指定的错误日志路径上的文件，有没有什么记录。

**Comment by jianzs** [comment]
没有，最近的报错是9月10日的，那时还没有更新操作系统。

**Comment by suziwen** [comment]
在崩溃闪退前，系统监控里，内存， cpu等指标 有什么异常？

**Comment by jianzs** [comment]
没有注意，看系统日志也没有发现相关崩溃的报告。

**Comment by suziwen** [comment]
试一下这个[版本](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/issue1556),看还会不会闪退。

**Comment by jianzs** [comment]
使用了几天，的确没有出现闪退的情况。
