### ISSUE TITLE
[建议]GitHub同步时希望可以修改comment的内容

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1562]
希望GitHub同步上传保存的时候,可以自己填写comment的内容,目前都是`修改文件:<file name>`这样

**Comment by suziwen** [comment]
升级到 `8.6.20`, 然后在绑定页面里，对应的 github 绑定项有一个设置。

![image](https://user-images.githubusercontent.com/57370/139681301-3637e1c4-37a4-42ec-98ad-582623a1010c.png)

**Comment by lqdflying** [comment]
web还没更新?
