### ISSUE TITLE
如何关闭打字特效?

### ISSUE THREAD

**Issue by GersonHuang** [suziwen/markdownxiaoshujiang#1563]

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/139835347-896f8977-0acc-4530-b9a2-771b800c17ac.png)


或者

![image](https://user-images.githubusercontent.com/57370/139835384-5f3112da-cf90-4c43-9b68-5f6d915045c8.png)

**Comment by GersonHuang** [comment]
> ![image](https://user-images.githubusercontent.com/57370/139835347-896f8977-0acc-4530-b9a2-771b800c17ac.png)
> 
> 或者
> 
> ![image](https://user-images.githubusercontent.com/57370/139835384-5f3112da-cf90-4c43-9b68-5f6d915045c8.png)

感谢
