### ISSUE TITLE
对锚点的定位 如何操作

### ISSUE THREAD

**Issue by Yuki-J1** [suziwen/markdownxiaoshujiang#1568]
![image](https://user-images.githubusercontent.com/41263770/140912185-30a328a7-684a-44ab-8838-1b9a015f8ff9.png)
您好管理员，关于这个教程我有几个问题想请教一下。
我开启了 grammar_decorate 语法功能，并且添加了一个锚点 `<!--{#小书匠锚位置}-->`

在尝试对锚点定位时，点击预览结果
[小书匠另外一篇文章的指定位置](小书匠/示例/测试锚#小书匠锚位置)  
会跳转到
![image](https://user-images.githubusercontent.com/41263770/140912763-ae75c32c-2d29-425f-95e2-3843a7e46ebd.png)

**Comment by suziwen** [comment]
要把鼠标移到那个链接，停一会，就会自动弹出下拉选项，列出系统里有相关的所有文章，点击对应的选项文章，就可切换到那个文件上了。

直接点击的话，就按照 markdown 默认的行为打开一个链接跳转到新页面上了。


注：一定要先建好对应的文章，不然是不会有下拉列表文章的.

 [如何使用内部链接](http://soft.xiaoshujiang.com/docs/tutorial/internal_link/#e5a682e4bd95e4bdbfe794a8e58685e983a8e993bee68ea5_2)
