### ISSUE TITLE
页面跟随当前行滚动的问题

### ISSUE THREAD

**Issue by qingchuwudi** [suziwen/markdownxiaoshujiang#1576]
作者你好，最近几个版本的小书匠软件，在编辑文档的时候，每次点击一个位置或者移动到某一行，页面都会跟着滚动，并且把当前行作为页面中心。

这个策略有点闹心：
- 一个是习惯于编辑的时候页面静止，现在自动滚动导致眼花缭乱；
- 再一个写当前行的时候需要参考前面（或者后面）的图片、条目等等，自动跟随导致每次都要手动翻几行才行。

一直没找到这个功能的开关，请问这个功能有开关在什么位置？

**Comment by suziwen** [comment]
1. `设置>编辑器>codemirror>打字机滚动效果`
或者
在这里设置也可以


![image](https://user-images.githubusercontent.com/57370/143873478-7b9cf2d3-c8cb-4b4f-83c1-0c36425a80f5.png)


-----------------
2. 鼠标移到预览区后，预览区左下角就会有控制编辑区与预览区同步滚动方式

![image](https://user-images.githubusercontent.com/57370/143872723-ee162be6-6166-45ce-aafb-05de7abcb730.png)


如果你是会员的话，还可以在编辑器里按  F4, 或者在文件列表里，右键打开浮动编辑器，修改同一篇文章，这样，文章比较长的话，就可以定位在不同的位置上了

![image](https://user-images.githubusercontent.com/57370/143873313-231e5ad6-d177-47ca-aed9-7c1478e6c3ac.png)

**Comment by qingchuwudi** [comment]
解决了，非常感谢
