### ISSUE TITLE
建议: 增强文件链接复制功能

### ISSUE THREAD

**Issue by niuyongjie** [suziwen/markdownxiaoshujiang#1579]
![image](https://user-images.githubusercontent.com/18510241/144959626-8773a6ef-f5d5-4478-98a2-67d63a318582.png)

现在的文件复制链接，复制的是小书匠自己的存储链接。
这个功能可以增强下，我在小书匠中随机复制了印象笔记的链接，保存到印象笔记中后，印象笔记客户端中的笔记可以正常跳转。

建议：
1. 在右键复制的列表中增加一个选项，复制绑定的第三方链接（印象笔记的 share 链接）。
2. 或者程序判断，根据文档来源（第三方，小书匠）复制对应的链接

这样可以使书写过程更加顺畅，不必再切换到印象笔记专门去复制一次笔记链接。

**Comment by suziwen** [comment]
在第三方存储的树形文件列表上右键，复制链接

![image](https://user-images.githubusercontent.com/57370/144968708-4353e587-8f7a-4217-b2bd-819f546e20f5.png)


http://soft.xiaoshujiang.com/blog/evernote/internal_link

**Comment by niuyongjie** [comment]
感谢回复，跟我想的效果一致！
