### ISSUE TITLE
ubuntu-gnome 15.10 打开后界面超级模糊，感觉上面盖了一层膜，修改字体也不行（除了左侧菜单，主页，绑定。。。这一列）。

### ISSUE THREAD

**Issue by zhanghaofei** [suziwen/markdownxiaoshujiang#158]
![default](https://cloud.githubusercontent.com/assets/14348610/14199560/0efba058-f818-11e5-8944-52d3865d4b8d.jpg)
不知道你能不能看的出来，可以对比下桌面上我文件的字

**Comment by q1042697116** [comment]
![default](https://cloud.githubusercontent.com/assets/14348610/14199585/45d63002-f818-11e5-8169-c381e2f14722.jpg)
这有这一列正常，很清晰

**Comment by suziwen** [comment]
不知道你是怎么设置字体，可能值不对就没有生效
`设置>基础` 和 `设置>编辑器`
多个字体用逗号隔开，字体名称中有空格的话，要用引号

![screenshot_2016-04-02_01-03-16](https://cloud.githubusercontent.com/assets/57370/14214366/50e6e42a-f802-11e5-920c-cf7e8506817e.png)
![screenshot_2016-04-02_01-03-33](https://cloud.githubusercontent.com/assets/57370/14214371/53a3d0d8-f802-11e5-8263-e1ef57f10b3f.png)
![screenshot_2016-04-02_01-05-58](https://cloud.githubusercontent.com/assets/57370/14214380/5e884a60-f802-11e5-9a31-494068771c57.png)
![screenshot_2016-04-02_01-09-18](https://cloud.githubusercontent.com/assets/57370/14214427/99d190ae-f802-11e5-8987-9ae5ae949975.png)

**Comment by q1042697116** [comment]
看来不是程序问题，不知道你的程序底层是不是根chrome有关系，我升级了系统，chrome字体变了，小书匠里面字体页变好了，之前就觉得是和chrome有关系
