### ISSUE TITLE
腾讯云cos v5版本绑定一直是失败状态

### ISSUE THREAD

**Issue by tohere** [suziwen/markdownxiaoshujiang#1581]
![image](https://user-images.githubusercontent.com/28532718/145505298-b741040f-93a1-4ade-877c-6edbfc975092.png)
![image](https://user-images.githubusercontent.com/28532718/145505468-5c98403a-d120-43a5-b022-ebb2098d35a3.png)
也在**picgo**中绑定试过，也成功了，但是小书匠一直是失败的，不知道什么原因

**Comment by suziwen** [comment]
如果是使用网页版本小书匠的话，要在腾讯云里添加跨域安全设置，把 `http://markdown.xiaoshujiang.com` 和 `https://markdown.xiaoshujiang.com` 添加进去。


比如

![image](https://user-images.githubusercontent.com/57370/145584345-d50388f2-c911-4592-899b-ce2461054ab3.png)

![image](https://user-images.githubusercontent.com/57370/145584370-568a9329-8b7a-4700-9410-a2db24eb15e1.png)


如果是用小书匠客户端版本的话，就可以不需要这个额外配置就可以绑定了。

**Comment by tohere** [comment]
> 

果然，感谢大佬~~
