### ISSUE TITLE
作者大大可以将内部链接功能优化一下吗？

### ISSUE THREAD

**Issue by VIOSnZ** [suziwen/markdownxiaoshujiang#1583]
作者大大可以将内部链接功能优化一下吗，我希望能在修改引用文件本身名称的同时，其他引用这个文件的文档都会作出调整，就像obsidian和logseq那种双向链接。

还有新版的链接图谱能多一些筛选功能吗？比如只显示特定tag下的。
（总之就是希望咱小书匠能像logseq和obsidian那样QAQ）

**Comment by suziwen** [comment]
1. 这个要研究下，主要是小书匠这边的同一个引用可以指向多篇文章，而其他双链笔记，一个引用只能指向一篇文章。就是说小书匠这里能同时创建多篇相同 slug 的文章，然后其他文章引用这个 slug 就成了多篇文章的效果。
2. 可以点击左侧的标签栏，就会高亮这些 tag 的文章。如果想只显示特定 tag 的文章，可以先用过滤器，把文章过滤出来，然后再点击文档列表下方的链接关系图，就会只生成这些 tag 的链接关系图了

![image](https://user-images.githubusercontent.com/57370/145670612-c871b82f-8a0a-49e2-b517-9e92f06ec511.png)

**Comment by VIOSnZ** [comment]
原来是这么操作的…收到！谢谢作者大大指点～(^///^)

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/145670834-d5697833-2df4-4037-ada6-8cd44950d5e9.png)

**Comment by suziwen** [comment]
通过过滤器，就可以实现不单单是过滤标签，还可以过滤特定时间范围内的链接关系图，或者全文搜索，组合搜索后的文章之间的链接关系图。
