### ISSUE TITLE
自定义远程数据库推送出错

### ISSUE THREAD

**Issue by aecra** [suziwen/markdownxiaoshujiang#1588]
Windows 客户端，版本8.7.1

报错场景：全部推送

报错内容

```json
{
	"stack": "SyntaxError: Unexpected token < in JSON at position 0",
	"message": "Unexpected token < in JSON at position 0",
	"result": {
		"ok": false,
		"start_time": "2021-12-22T03:28:20.278Z",
		"docs_read": 1,
		"docs_written": 0,
		"doc_write_failures": 1,
		"errors": [],
		"last_seq": 705,
		"status": "aborting",
		"end_time": "2021-12-22T03:28:22.778Z"
	}
}
```

chrome 96

报错场景：全部推送

报错内容

```json
{
	"stack": "TypeError: Failed to fetch\n at Function.Be.fetch (http://markdown.xiaoshujiang.com/js/vendor-base.js?v=8.7.1:1:156471)\n at t.fetch (http://markdown.xiaoshujiang.com/js/app.js?v=8.7.1:1:105436)\n at c (http://markdown.xiaoshujiang.com/js/vendor-base.js?v=8.7.1:1:192965)\n at f (http://markdown.xiaoshujiang.com/js/vendor-base.js?v=8.7.1:1:193323)\n at http://markdown.xiaoshujiang.com/js/vendor-base.js?v=8.7.1:1:198269",
	"message": "Failed to fetch",
	"result": {
		"ok": false,
		"start_time": "2021-12-22T04:14:42.938Z",
		"docs_read": 1,
		"docs_written": 0,
		"doc_write_failures": 1,
		"errors": [],
		"status": "aborting",
		"end_time": "2021-12-22T04:14:43.192Z",
		"last_seq": 0
	}
}
```

**Comment by suziwen** [comment]
试一下在浏览器里访问你配置的数据库地址，看能否正确返回 json 字符串

![image](https://user-images.githubusercontent.com/57370/147052287-1eaeeccb-c18b-4a58-ba46-fa2e9b6db980.png)

![image](https://user-images.githubusercontent.com/57370/147052359-8088711e-d17f-49a4-95a8-b078a2581d9c.png)

**Comment by suziwen** [comment]
如果是在网页版使用自定义服务器的话，还需要自己配置跨域请求权限。

#1534

**Comment by aecra** [comment]
我这些都没问题，如果使用推送最近十篇是正常的，只有全部推送报错

使用的数据库是 [bitnami/couchdb:latest](https://hub.docker.com/layers/bitnami/couchdb/latest/images/sha256-4818b6cc4536aa330949bd8eec0e2dbf9b8ae95cabf6d4a7e035b4319712e9a1?context=explore)

**Comment by suziwen** [comment]
可以按下 `ctrl` 键，然后再点击全部推送，看下推送到什么进度被停下来了。

**Comment by suziwen** [comment]
感觉是其中一个文件有错误，可能是比较大，造成 couchdb 直接拒绝，返回了一个 50x 错误等。也可以看看 couchdb 日志记录，看有什么相关的信息。

**Comment by suziwen** [comment]
日志命令

```
docker logs -f --tail 100 {docker 实例名称}

比如
docker logs -f --tail 100 couchdb
```

**Comment by aecra** [comment]
推送进度显示 0%。

多次测试，都没有 50x 的报错日志。

关于大文件问题，在 couchdb 里看了一下较大的文章都同步到数据库了。

我的笔记数量不足 50 篇，在推送最近修改的50篇文章时没有报错。

**Comment by suziwen** [comment]
可以试着做下下面操作

1. 在`关于`界面里，有本地数据库的文件路径，先备份一份
2. 到`数据`界面，选择导出数据库，时间范围尽量选择大一点，最好可以覆盖整个数据库
3. 导出数据库，确认下导出的文件大小。
4. 将本地数据库文件临时移走，然后再启动小书匠，登录自己的帐号
5. 到 `数据`界面，将刚才导入的数据库文件导入进去。
6. 按 `ctrl` 点击全库同步，看这时候还能不能同步成功？

---------

如果还是全库同步失败的话，就在 chrome 浏览器里，打开隐身模式，然后导入刚才导出的数据。再点击全库同步，同时按 f12 打开调试信息，切到网络标签项，看失败时，报什么　http 相关的错误信息。

**Comment by aecra** [comment]
在 `_revs_diff` 请求之后紧接着就是错误请求 `POST /xsj/_bulk_docs`，错误码：`413`

![content](https://user-images.githubusercontent.com/34883050/147578641-9ac83d49-e88e-4937-a413-003cada0c8ac.png)

**Comment by suziwen** [comment]
413 的错误应该是指上传的文件太大，被拒绝提交了。

你 couchdb 前面加了一层　nginx 或者 apache 做为反向代理了？ 

apache 或者 nginx 或者 couchdb 有单独设置了文件上传最大值？

**Comment by aecra** [comment]
使用了 `nginx`，没有设置过大小限制，查阅了一下 `nginx` 文档，发现默认配置是 `client_max_body_size 1m;`。

修改配置大小后，一切正常使用。
