### ISSUE TITLE
关于在线与本地的同步问题

### ISSUE THREAD

**Issue by wunshare** [suziwen/markdownxiaoshujiang#159]
- 现在下了一个更新的1.9.0版本，但是遇到新问题：

怎么在小书匠官方服务器上同步之前的数据？我现在只能**人工COPY**。
**但是怎么把官方服务器商的数据同步回来？？？**
- 之前下了一个1.6.1离线版本的编辑器，用起来各种问题（好像当了白老鼠）：
- 没有更新检测（这个只能泪奔）
- 数据同步有问题（官方跟第三方的数据同步貌似问题不小）
- 界面卡顿，字体各种难看（新版界面，字体还是不错的）
- **编辑的时候莫名出bug**，搞到整篇文章都没了（我为此**丢过3篇文档**）
- 没有回收站（新版终于有了）
- 导出的文档有问题（新版到处word格式还是有些不对，但是起码文件能打开了）

**Comment by suziwen** [comment]
编辑器的数据都是存在本地的，浏览器的话也是存在浏览器自带的数据库里。
如果是从1.6.0升级到最新版本，想找回以前客户端的数据，可以到用户目录里把文件名改一下就可以
`C:\Users\Administrator\AppData\Local\小书匠(编)` 改成 `C:\Users\Administrator\AppData\Local\小书匠`,
linux的话，`~/.config`目录

**Comment by SeaUncharted** [comment]
用的是最新版本 1.9.1，链接到Evernote会出现在同步时发生错误。在关掉小书匠重启之后，软件卡在 启动界面上：
![image](https://cloud.githubusercontent.com/assets/15714030/16580904/4f3bd88e-42d9-11e6-9813-d27014cb351d.png)
 
只能重启电脑才能解决。 这个问题最近才出现，怎么解决？
