### ISSUE TITLE
WebDAV无法绑定（坚果云或者其他网盘的）

### ISSUE THREAD

**Issue by VIOSnZ** [suziwen/markdownxiaoshujiang#1591]
试了好几个网盘的webdav，都无法绑定。

**Comment by suziwen** [comment]
我这里测试是正常的。

如果使用的是小书匠 web 版本，由于跨域安全的原因，坚果云是无法直接使用的，自己搭建的 webdav 服务器的话，就要把 cors 跨域访问限制取消掉才可以。



#1420
#1354

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/issues/1435#issuecomment-718294961
