### ISSUE TITLE
自动换行的文字重叠

### ISSUE THREAD

**Issue by newstart2014** [suziwen/markdownxiaoshujiang#160]
---
## tags: bug

版本1.8,1.9
环境:win7 32位 中文系统
设置:
键盘模式(ace):vim
Soft Wrap(ace):80 Chars
问题:
一行字符长度超过80时自动换行的字符会重叠显示

另外,在反馈时候怎么在标题加bug标签啊?

**Comment by suziwen** [comment]
有截图吗？
