### ISSUE TITLE
打开第三方存放的文章总是会打开两个

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1604]
打开第三方存放的文章总是会打开两个，这是为什么？
例如我打开一篇gitee的文章，左上角的最近编辑窗口就会打开两份一样的文章。这什么原因？

**Comment by suziwen** [comment]
是每次点击左下角第三方文件夹内的任何文本文件，然后左上角的文章列表都会出现两篇一样的文章？

**Comment by liao20081228** [comment]
> 是每次点击左下角第三方文件夹内的任何文本文件，然后左上角的文章列表都会出现两篇一样的文章？

对

**Comment by liao20081228** [comment]
> 是每次点击左下角第三方文件夹内的任何文本文件，然后左上角的文章列表都会出现两篇一样的文章？

一开始我以为是因为我使用了双拨网络造成的，后来发现单拨也一样的

**Comment by suziwen** [comment]
我这边测试好像没有问题，你试下在网页版里，用浏览器打开隐藏模式，然后试下操作，是否也会有你说的情况？

![image](https://user-images.githubusercontent.com/57370/154845070-fc15a930-030e-4500-b1c5-115a3f54f15b.png)

**Comment by liao20081228** [comment]
有的

> 我这边测试好像没有问题，你试下在网页版里，用浏览器打开隐藏模式，然后试下操作，是否也会有你说的情况？
> 
> ![image](https://user-images.githubusercontent.com/57370/154845070-fc15a930-030e-4500-b1c5-115a3f54f15b.png)
仍然有的

**Comment by suziwen** [comment]
我这边没法重现，能录个操作视频吗？

**Comment by liao20081228** [comment]
> 我这边没法重现，能录个操作视频吗？



第一步就是把左上角的文章列表的都删了，然后点击左下角第三方文件夹内的任何文本文件，然后左上角的文章列表都会出现两篇一样的文章。

**原因找到了**： 我重置了路由器为单拨就解决了，然后双拨后，就会这样。
