### ISSUE TITLE
关于新版本的一点疑问？

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#161]
1.预览区的“更新提示”只能点关闭，点击“不再提醒”没反应。
2.升级的时候是直接升级就会把旧版本覆盖么？还是需要直接卸载旧版本再安装
3.我觉得软件可以放到网盘上供下载，现在下载的速度太慢，我用chrome下载的时候才几十kb，迅雷还好一点。
![111](https://cloud.githubusercontent.com/assets/11471256/14342709/4541d816-fcce-11e5-90e4-bd7fe3145aba.png)
4.看下图
![1](https://cloud.githubusercontent.com/assets/11471256/14342090/b73e3400-fcc9-11e5-9637-ff96576993cc.png)

**Comment by suziwen** [comment]
1.  `不再提醒` 这个是1.8.0 的bug,后继版本有更正了，如果还想用1.8版本，可以在设置里关闭升级提示。
2. 直接升级，或者覆盖都可以。数据和应用是分离的，数据一般存放在这个目录下 `C:\Users\Administrator\AppData\Local\小书匠` 。
3.  嗯
4. 这两个功能的区别就是一个是当前文章的大纲，一个可以看其他文章的大纲，并且快速切换到其他文章指定的大纲位置上。删除是有点远了，不过感觉没地方放，放回原来的位置？

**Comment by leongfeng** [comment]
貌似又有一个新的版本了，我又升级了。
继续说下前面提到的问题4，这几个管理按钮实在太远，而且这个悬浮窗体验太差，悬浮窗很容易就消失。小书匠这个客户端应该大多数是JS代码吧？我觉得这个悬浮窗的触发事件可以是整个文件标题的焦点（hover?）事件来触发，而不应该只是那个**管理按钮**来触发，按钮的面积太小，很容易失去焦点。
![qq 20160408000305](https://cloud.githubusercontent.com/assets/11471256/14358053/ed49bc5a-fd1d-11e5-9464-6e87818ffd7d.png)
现在又有 点问题：
5.引用的图片为什么要自动引用它的文件名？显示文件名没什么意义呀，如果你说自己命名图1，图2....这样的还有点意义，显示自动生成的文件名真没什么用。
6.文章指定内部链接有个BUG，
![qq 20160408004220](https://cloud.githubusercontent.com/assets/11471256/14359199/f6155f92-fd22-11e5-9d8b-95511409c2a7.png)
我看了源码，竟然大写转成小写了，而后面的指定的还是大写，这个应该要修正一下。

**Comment by suziwen** [comment]
5. 新版的加强了图片生成的语法，这个就是自己命名的图片。

具体规则是：如果是单独一个段落里的图片，就自动把这个图片包裹成块格式，并居中，如果图片是在文字里面的，就依然是行内图片。块图片如果有描述，或者提供 title ，就自动在图片下方显示这个title或者alt.
如果不想让块图片显示title,可以自己定义css，把这个信息隐藏掉。
```
![](xxx.jpg)
![][1]

 [1]: xxx.jpg
```
这样的方式都不会带上标题

而
```
![标题1](xxx.jpg)
![标题1][1]

 [1]: xxx.jpg "标题2"
```
就会添加图片的名称

6. 后面那个 `<a href="#1CHAPTER1">指向chapter 1</a>` 是你自己使用 html 标签添加的？ 目前系统生成的id都会把它转换成小写的，因为有些浏览器对id属性是大小写不敏感，所以干脆都转成小写了。如果你想自己用html控制跳转，最好先看一下目标元素生成的id值，系统不是简单的把 h1里的文字当成 id来处理，会进行一定的过滤处理，比如汉字标题。

**Comment by leongfeng** [comment]
<a href="#1CHAPTER1">指向chapter 1</a>  这个是 [指向chapter 1](#1CHAPTER1) 的源码，不是我自己添加的。

**Comment by leongfeng** [comment]
da

**Comment by suziwen** [comment]
你的原文是这样的？

``` markdown

# 1CHAPTER1  ===》 这个地方系统会自动生成一个id ，这个id规则不是简单的拿文本内容的
aaaaaa

aaaa

aaa
.
.
.
[指向chapter 1](#1CHAPTER) ===》 这个链接不是系统管理的，属于用户自己输入的，系统是不会将其改成小写的。

```

这里面的  `#1CHAPTER` 是你自己写入的，系统是不会帮改的。系统自动生成的id规则不是简单的把标题内容当做 id 的
