### ISSUE TITLE
如何添加外部编辑器？

### ISSUE THREAD

**Issue by mind2sear** [suziwen/markdownxiaoshujiang#1614]
找不到反馈的地方。
作为一个小白，读不懂所说的添加外部编辑器的方法，望解答！多谢
![image](https://user-images.githubusercontent.com/24808059/159899954-3672ebe3-b486-4584-8303-077ae6f50be2.png)

**Comment by suziwen** [comment]
这个不太好解释，可能需要一些计算机命令行执行的知识，才好理解．

如果不会的话，可以忽略这个功能．这个功能其实是用你电脑里安装的其他文本编辑器打开当前修改的文章进行编辑，不用这个功能，　并不影响对笔记内容的编辑使用．

觉得小书匠内置的编辑器不好用的话，只能建议放弃使用这款软件．

**Comment by mind2sear** [comment]
> 这个不太好解释，可能需要一些计算机命令行执行的知识，才好理解．
> 
> 如果不会的话，可以忽略这个功能．这个功能其实是用你电脑里安装的其他文本编辑器打开当前修改的文章进行编辑，不用这个功能，　并不影响对笔记内容的编辑使用．
> 
> 觉得小书匠内置的编辑器不好用的话，只能建议放弃使用这款软件．

**Comment by mind2sear** [comment]
给个示例可否？
就比如在win10下安装了GVIM，怎么添加这个GVIM。

**Comment by suziwen** [comment]
类似这样

```
"C:\Program Files\Sublime Text 3\subl.exe" {{file}}
```
