### ISSUE TITLE
自定义数据中心拉取出错

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1617]
自定义数据中心，拉取出错，下面是报错信息：
拉取出错：{"status":500,"name":"unknown_error","message":"Database encountered an unknown error","error":true,"reason":"transaction was aborted",
"result":{"ok":false,"start_time":"2022-04-22T08:53:14.303Z","docs_read":2,"docs_written":0,"doc_write_failures":2,"errors":[],"last_seq":"174-g1AAAACbeJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVCJDUv3___-zMpgTJ-QCBdiTUgxM0pKNsGnAY0weC5BkaABS_6GmyYFNM7dMTUxNM8GmLwsAgTwpjg","status":"aborting","end_time":"2022-04-22T08:53:21.521Z"}}

我用两台电脑试了下，都有问题，但是用手机、ipad同步拉取都没问题，请问是什么原因呢？

**Comment by suziwen** [comment]
你是使用小书匠的临时数据服务器还是自己搭建的数据库服务器?

**Comment by lingxiaqidu** [comment]
自己搭建的数据库服务器，用的couchdb

**Comment by suziwen** [comment]
你试一下这样操作
1. 到小书匠客户端关于界面里，找到数据目录的位置
2. 把这个数据文件夹先临时移走
3. 然后启动小书匠，登录下
4. 再配置一下新的　couchdb 数据库地址,比如原来的是 `http://localhost:5984/aa`, 　现在配置成 `http://localhost:5984/bb`
5. 看下新的数据库是否能同步成功，或者也会报这个错误。

**Comment by suziwen** [comment]
还有看下是不是这个原因

https://github.com/suziwen/markdownxiaoshujiang/issues/1588#issuecomment-1002397593


如果不是的话，

也可以试下这个操作

https://github.com/suziwen/markdownxiaoshujiang/issues/1588#issuecomment-1000898107

**Comment by lingxiaqidu** [comment]
在浏览器里运行，报两个错
![image](https://user-images.githubusercontent.com/17762125/164752101-b345443d-68a4-4155-86e2-da1edee5e6a0.png)

**第一个**

Uncaught RangeError: Maximum call stack size exceeded
    at vendor-base.js?v=8.8.17:1:280397
    at vendor-base.js?v=8.8.17:1:280458
    at Array.forEach (<anonymous>)
    at vendor-base.js?v=8.8.17:1:278340
    at IDBRequest.a (vendor-base.js?v=8.8.17:1:280470)
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
a @ vendor-base.js?v=8.8.17:1
IndexedDB(异步)
(匿名) @ vendor-base.js?v=8.8.17:1
_ @ vendor-base.js?v=8.8.17:1
then.e._openTransactionSafely.a.objectStore.get.onsuccess @ vendor-base.js?v=8.8.17:1
IndexedDB(异步)
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
Promise.then(异步)
(匿名) @ vendor-base.js?v=8.8.17:1
Te.n._openTransactionSafely @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
Promise.then(异步)
_e @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
Promise.then(异步)
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
M @ vendor-base.js?v=8.8.17:1
Promise.then(异步)
D @ vendor-base.js?v=8.8.17:1
O @ vendor-base.js?v=8.8.17:1
(匿名) @ vendor-base.js?v=8.8.17:1
p.run @ vendor-base.js?v=8.8.17:1
f @ vendor-base.js?v=8.8.17:1


第二个：
Database has a global failure DOMException: Uncaught exception in event handler.
i.onabort @ vendor-base.js?v=8.8.17:1

**Comment by suziwen** [comment]
这两个错看不出什么原因造成的


-----

你试着在浏览器，用隐藏模式打开小书匠，登录帐号，然后同步也是这个错误？

**Comment by lingxiaqidu** [comment]
是的，这就是隐藏模式下报的错

**Comment by lingxiaqidu** [comment]
我明天再试试，谢谢啦

**Comment by suziwen** [comment]
好的。
你明天可以试一下，在隐藏模式下，同步到另一个新创建的数据库上看看。然后除了看 console 选项卡，也可以切换到 network 网络选项卡，看有什么异常。

**Comment by lingxiaqidu** [comment]
你好，我用邮箱把数据库导出后发你了，离线导出的数据库在另一台电脑上导入也是提示错误，麻烦帮忙看下什么原因，谢谢

**Comment by suziwen** [comment]
你发的数据，我这边测试导入和同步都没有问题。
我邮件回了个自己录屏的视频，你可以看下。

**Comment by lingxiaqidu** [comment]
我试了下chrome、edge都不行，用火狐没有问题。查了下好像是indexed db或者localdb的问题，不知道咋解决，暂时先用火狐了，谢谢

**Comment by lingxiaqidu** [comment]
问题和这个描述的很像，https://github.com/pouchdb/pouchdb/issues/7098

**Comment by suziwen** [comment]
知道原因了，

文章的历史版本太多， indexeddb 在保存对像时，无法对过多的嵌套层对像进行保存造成的

可以更新到 `8.8.18` 版本，我把历史版本保留数调低了点，现在应该就可以正常导入了。

------------


下面是重现的简易代码，只要把 `MAXDEEP` 从 `100` 改成 `10000`, 就会重现 `Uncaught RangeError: Maximum call stack size exceeded` 这个错误.

至于能嵌套多少层，可能跟不同的系统环境有关。

``` js
var MAXDEEP = 10000;
var open = indexedDB.open("MyDatabase", 1);
open.onupgradeneeded = function() {
    var db = open.result;
    var store = db.createObjectStore("MyObjectStore", {keyPath: "id"});
    var index = store.createIndex("NameIndex", ["name.last", "name.first"]);
};
open.onsuccess = function() {
    var db = open.result;
    var tx = db.transaction("MyObjectStore", "readwrite");
    var store = tx.objectStore("MyObjectStore");
    var index = store.index("NameIndex");

   
    var deepObj = { index: 0};
    var johnData = {id: 12345, name: {first: "John", last: "Doe"}, age: 42, deepObj: deepObj};
    for(var i=0; i < MAXDEEP; i++){
       var tempDeepObj = { index: i + 1 };
       deepObj.deepObj = tempDeepObj;
       deepObj = tempDeepObj;
    }
    store.put(johnData);
    store.put({id: 67890, name: {first: "Bob", last: "Smith"}, age: 35});
    var getJohn = store.get(12345);

    getJohn.onsuccess = function() {
        console.log(getJohn.result.name.first);  // => "John"
    };
    tx.oncomplete = function() {
        db.close();
    };
}
```


![image](https://user-images.githubusercontent.com/57370/165037545-d1f91c05-0d74-47b3-afe7-8e1552c6e038.png)

**Comment by lingxiaqidu** [comment]
谢谢谢谢，太强大了！我会推荐朋友都用这个软件的
