### ISSUE TITLE
[bug]最新版拉取后筛选异常

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1618]
最新版8.8.18，从服务器拉取后如下图所示，可以看到1-38文章都能正常显示
![image](https://user-images.githubusercontent.com/17762125/165062679-9ff17aaa-7684-4543-a41d-19129e49eda3.png)

点击筛选中的全部后，效果如下图所示，列表框里面少了很多文章
![image](https://user-images.githubusercontent.com/17762125/165062174-3fc89d04-4fbf-48c1-8f92-2596b88c2b57.png)
不显示的文章通过搜索框搜索还是能找到的，感觉是个小bug

**Comment by suziwen** [comment]
每页只显示 30 条数据，多的数据需要分页下。

![image](https://user-images.githubusercontent.com/57370/165067657-1c7deb51-5b0c-451a-892e-bad05c35452c.png)

**Comment by lingxiaqidu** [comment]
是的，没有留意这还有按钮
