### ISSUE TITLE
能提供在软件更新或自动更新选项吗？

### ISSUE THREAD

**Issue by MeowCold** [suziwen/markdownxiaoshujiang#162]
能提供在软件更新或自动更新选项吗？
1.8.0 最近才下的，但提示更新时 我选择 知道了，不再提醒 无效
而且点X 后 正在写文章 右部开始不断刷更新提示把右边一竖都是没法好好玩耍了
![qq 20160407223952](https://cloud.githubusercontent.com/assets/7279597/14354913/b030c888-fd11-11e5-962c-005394942ef7.png)

**Comment by suziwen** [comment]
一直刷更新提示，这个是个bug, 可以在 `设置>基本` 里设置取消更新检测。

**Comment by suziwen** [comment]
1.9.0以上的版本已经修复
