### ISSUE TITLE
更新出错:Error: Request for xxxxx returned a response with status 404

### ISSUE THREAD

**Issue by yolo079** [suziwen/markdownxiaoshujiang#1620]
当前版本：8.8.18
最新版本：8.9.0
问题描述：
> 上一个小版本就出现这个错误，但是没有管它。
```bash
更新出错:
Error: Request for http://localhost/app/js/app-client.js?_sw-precache=a76880e707a2fdabb55da868decb6d0c returned a response with status 404
```
![image](https://user-images.githubusercontent.com/31334545/167085703-2908470b-7504-400d-8749-0a30bdabf39d.png)

**Comment by suziwen** [comment]
抱歉，忘记给个提示了，这个版本要单独下载客户端，

现在提供 8.9.1 版本，可以到这里[下载](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.9.1)
