### ISSUE TITLE
左侧文件列表不显示

### ISSUE THREAD

**Issue by canghaiwuhen** [suziwen/markdownxiaoshujiang#1624]
![image](https://user-images.githubusercontent.com/4746188/168290115-0b719772-494c-4ab9-95cb-6713e6947620.png)

最新8.9.2版本
系统win10 ltsc

**Comment by suziwen** [comment]
按下 <kbd>ctrl+shift+f</kbd> 按钮能出来吗? 

![image](https://user-images.githubusercontent.com/57370/168297857-33c7ddfc-07fb-4042-ada2-6c59f75a5a42.png)

**Comment by canghaiwuhen** [comment]
> 

可以的 但左边是有一片空白

**Comment by canghaiwuhen** [comment]
![image](https://user-images.githubusercontent.com/4746188/168413235-2f393885-05d0-4976-8435-532f08adff98.png)
右边左侧也有一片空白。。。很久没用了 现在变得有点不认识了 尴尬

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/168413900-f97e6fc4-472e-4349-a57b-24e009128871.png)

**Comment by canghaiwuhen** [comment]
> ![image](https://user-images.githubusercontent.com/57370/168413900-f97e6fc4-472e-4349-a57b-24e009128871.png)

好的 明白了 谢谢

**Comment by jialori** [comment]
自从有一次缩进了左侧列表之后，时不时会在遇到同样的问题，这个问题有时自己出现有时又自己修好，出现的时候上述方法都无法解决。
环境：win10的Edge浏览器
