### ISSUE TITLE
markdown字体高亮

### ISSUE THREAD

**Issue by canghaiwuhen** [suziwen/markdownxiaoshujiang#1625]
我的Blog用的Hexo，内容用小书匠来写，但hexo对字体颜色的语法不太一样

小书匠加粗红色高亮是  ```**==test#F44336==**```

hexo加粗红色高亮是 ```**<font color=red>test </font>**```

可以调整这个语法么？

**Comment by suziwen** [comment]
小书匠也可以识别这种写法的

```
**<font color=red>test </font>**
```

只是没办法方便的选择颜色,需要自己手动输入,或者自己写个片段,通过片段快速输入.

**Comment by canghaiwuhen** [comment]
> 小书匠也可以识别这种写法的
> 
> ```
> **<font color=red>test </font>**
> ```
> 
> 只是没办法方便的选择颜色,需要自己手动输入,或者自己写个片段,通过片段快速输入.

好吧 可以识别 但就是没法快速选择颜色。。希望后面更新能加上这种语法
