### ISSUE TITLE
索引慢

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1626]
目前显示有三千多个文档，索引的时候要转好大一会儿才能完成索引，而且索引完成，再切换标签也要转圈几秒才能显示出来

**Comment by suziwen** [comment]
不同的搜索项,涉及到搜索的字段不同,就会使用不同的索引.
比如通过标签,分类或者全文搜索,就会涉及到三个不同的索引.

小书匠跟其他数据库索引时间点不同,一般数据库都是更新数据时,就直接索引,小书匠是在具体搜索时,再触发更新索引.

每次索引时,都是从上次索引的位置继续索引.如果你是新建的数据库,并一次导入以前备份的数据库的话,第一次搜索时,索引就会消耗比较多的时间.索引完成后,以后再搜索时,就会只索引你增量修改的文章内容了,这人时候就会快点了.

具体小书匠用到哪些索引,可以到 `小书匠主按钮>数据>索引` 下查看,

![Screen Shot 2022-05-15 at 18 29 47](https://user-images.githubusercontent.com/57370/168468293-11b075e6-72e8-457a-a4ef-65ac7f95e540.png)

**Comment by lingxiaqidu** [comment]
把软件关了再开，索引要大概一分钟才能显示文件列表，这块还挺影响体验的

**Comment by lingxiaqidu** [comment]
还有个问题是大文件加载的问题，我有个长度六万多的文件，动起来感觉卡卡的

**Comment by lingxiaqidu** [comment]
还有个就是图片的加载速度，文件稍大，按说图片都是离线的，但还是转圈二十秒以上

**Comment by suziwen** [comment]
1.  软件关掉之后，再打开。如果关掉之前修改的文章比较多，重新打开后，会使用`最近修改的时间字段`，进行索引，然后再显示出来。如果关掉之前没有修改文章，或者修改文章后，自己使用了最近修改的过滤器，那下次打开，文件列表显示出来的速度应该就会比较快。
2. 六万多字？字数多的话，可以考虑把立时预览功能关掉试试。
3. 大图片这块应该是有优化空间的，不知道你说的图片一块有多大，太大的文件，除了小书匠需要进行转换外，系统进行解码也是需要时间的。

**Comment by suziwen** [comment]
再有一个，索引快慢还跟硬盘类型和 cpu 有关。

数据文件如果放在机械硬盘里，索引就会比较慢些。如果是固态硬盘，就会快很多。

对于像全文搜索，由于要对文章内文字进行分词处理，需要大量的 cpu 计算，如果 cpu 偏弱的话，这块的索引也会慢些。

**Comment by lingxiaqidu** [comment]
> 1. 软件关掉之后，再打开。如果关掉之前修改的文章比较多，重新打开后，会使用`最近修改的时间字段`，进行索引，然后再显示出来。如果关掉之前没有修改文章，或者修改文章后，自己使用了最近修改的过滤器，那下次打开，文件列表显示出来的速度应该就会比较快。
> 2. 六万多字？字数多的话，可以考虑把立时预览功能关掉试试。
> 3. 大图片这块应该是有优化空间的，不知道你说的图片一块有多大，太大的文件，除了小书匠需要进行转换外，系统进行解码也是需要时间的。

第一个，修改不多，就算是不修改，重新打开也要加载至少半分钟；
第二个：关掉立刻预览，编辑区加载很快；但是预览区的图片还是要很久才能加载
第三个：不是大图片，是说一篇文章较长，万字以上，配图较多的时候，图片加载很慢；
第四个：索引的话，我是放在C盘的，512G的固态硬盘，CPU是i9-10980HK
同样一篇文章，我用思源测试了下，那个软件文章立刻预览图片加载非常快，几乎看不到加载过程

**Comment by suziwen** [comment]
1. 你到数据库文件夹位置,看下整个数据文件现在占用多少空间了?
2. 点击 `全部` 过滤器,然后鼠标移到分页区,看一下,文章总数有多少了?

![Screen Shot 2022-05-16 at 18 28 50](https://user-images.githubusercontent.com/57370/168574023-ba6f4c63-5803-46b2-a792-989b3fd1355b.png)

3. 把图片多的其中一篇文章,导出成 zip 格式,看下导出的文件大小是多少?

**Comment by lingxiaqidu** [comment]
文章数83，userdata文件夹578MB，最大的一篇文章21.78MB

**Comment by suziwen** [comment]
那不应该，我这边自己的都到了 2000+个文档，总大小 4G+, 查询速度也是在2-3秒范围内。启动的时候，可能还同时处理其他数据项，但也不至于要半分钟。我录了几个视频，回复了你的邮箱，你可以看下。

**Comment by suziwen** [comment]
是不是你那有什么监控软件，要检测文件的读写？

**Comment by suziwen** [comment]
你试一下把数据库路径移动到非系统盘上，然后用类似下面的命令启动小书匠看看

```
Story-writer.exe --user-data-dir=d:\tempdata
```

`d:\tempdata` 是你刚才移动的新数据库路径

![image](https://user-images.githubusercontent.com/57370/168600067-08469a49-f47f-4ad4-a670-a58eb4917230.png)

**Comment by lingxiaqidu** [comment]
新版本好用很多，赞！小书匠很给力
