### ISSUE TITLE
表格编辑异常

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1631]
立时预览模式下，8.9.5 插入表格后，双击单元格编辑添加文本，然后保存，提示保存成功了，但是关闭软件再打开后表格还是空的；如果点击表格左上角的修改源代码，直接在代码的对应单元格填入文字，保存再打开就有

**Comment by suziwen** [comment]
我这边测试了下，好像是正常的

https://user-images.githubusercontent.com/57370/170416840-83d823dd-707d-4b58-a843-90497430e064.mp4
