### ISSUE TITLE
外部回链打开

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1634]
我用bookxnote导出书籍笔记为html格式，这个文件用浏览器打开，可以跳转到bookxnote对应笔记具体位置，就算bookxnote关掉了也能打开；但是小书匠导入这个html，在预览区打开链接，只能打开软件，不能跳转到相应的笔记位置是什么原因呢？
![image](https://user-images.githubusercontent.com/17762125/172975239-42e632cd-3ce7-47b1-b664-6d7c3e3f69f7.png)
![image](https://user-images.githubusercontent.com/17762125/172975280-6fd64c52-86d4-48cc-bc2d-da990fadf0fa.png)
![image](https://user-images.githubusercontent.com/17762125/172975489-512bc1b0-bc58-4dbb-841e-3acb354f7bc4.png)

**Comment by suziwen** [comment]
编辑区生成的 markdown 文件对应的内容是什么？

**Comment by lingxiaqidu** [comment]
![image](https://user-images.githubusercontent.com/17762125/172997188-33c5a74a-bc4f-4b9f-9228-cd695b3ab46e.png)

**Comment by lingxiaqidu** [comment]
是这样的

**Comment by suziwen** [comment]
这个不行，这些链接是 bookxnote 自己专有的链接，只能在他家的应用里打开。小书匠这边没办法解析 `bookxnotepro://` 这种非标准协议地址的。

通过 bookxnote 导出的 html，链接应该是做了处理转换的。你可以看下导出的 html 源文件里，这些链接已经被替换掉了。所以普通的浏览器也能正常查看。

**Comment by lingxiaqidu** [comment]
![image](https://user-images.githubusercontent.com/17762125/173003083-ede169fe-62dd-404e-a219-ebd0001eeb40.png)
没有变的，这个是用的url protocol协议，就跟网页打开百度网盘一个原理，就是在小书匠里只能打开程序，后续的参数好像没起作用

**Comment by suziwen** [comment]
哦，我理解错了，我原以为你是想直接在小书匠里面定位这篇文章。

如果是想通过这样的链接打开其他应用，应该是可以的，我这边测试了下 telegram 的链接，是可以打开的。


参数没传过去的话，估计是生成的 url 里有特殊符号引起的，你通过小书匠导出 html 的方式，然后看下生成的 html 源代码里，这个链接最终是什么样的？

**Comment by lingxiaqidu** [comment]
![image](https://user-images.githubusercontent.com/17762125/173027033-b3338b87-e046-40b8-9274-4928b818e484.png)
![image](https://user-images.githubusercontent.com/17762125/173027067-ce3326a2-d95f-4d20-b6e5-8a12f8915ed5.png)
我用小书匠导出html，同样的这个链接，在浏览器中就能打开且定位到具体位置，小书匠中只能打开软件，好奇该

**Comment by suziwen** [comment]
能把这个链接的 markdown 内容发一下吗，我看一下。

**Comment by lingxiaqidu** [comment]
已通过邮箱发送

**Comment by suziwen** [comment]
知道原因了， 预览区 url 编码有些问题，更新到 `8.9.11` 应该就可以了。

**Comment by lingxiaqidu** [comment]
牛，更新了很不错，赞一个
