### ISSUE TITLE
同步选项

### ISSUE THREAD

**Issue by MeowCold** [suziwen/markdownxiaoshujiang#164]
能否新增wordpress和ghost同步  实在受够wp的写作页面，超喜欢小书匠。手动转换太麻烦了

**Comment by suziwen** [comment]
wordpress 可以通过发布功能实现。（支持metablog api 的博客），ghost没研究过，好像不支持metablog api。

**Comment by hjb2722404** [comment]
能否研究下csdn的发布呀
