### ISSUE TITLE
Mac客户端的界面bug

### ISSUE THREAD

**Issue by fedstryale** [suziwen/markdownxiaoshujiang#1645]
今天发现mac客户端的一个界面bug，上次关闭时是窗口模式的状态，这次再次打开后，窗口模式的最上面一条窗口控制栏跑到menu bar后面去了，导致现在没办法控制窗口。

<img width="743" alt="截屏2022-07-25 22 41 44" src="https://user-images.githubusercontent.com/6479758/180806056-4a2a843a-86ba-44d2-8f5d-997bd5f0a725.png">
<img width="974" alt="截屏2022-07-25 22 51 40" src="https://user-images.githubusercontent.com/6479758/180806427-9c3ef885-da7e-4a5f-b004-508eb02bada3.png">
。

**Comment by suziwen** [comment]
应该可以看到窗口下边的边框吧？

通过下边的边框，把小书匠窗口高度调整小些，整个高度控制在屏幕高度内，然后退出小书匠，再重启应该就能看到上边的边框了。

**Comment by fedstryale** [comment]
这么操作的确是可以找回边框，但每次都要这么操作一下的确非常不便，都要重新调整已经调整好的大小，不知道为什么不能打开后回到上次打开的位置和大小

**Comment by suziwen** [comment]
这个是因为窗口大小超过了显示器屏幕大小，为了让应用居中显示，高度太大就会把整个应用顶上去。不同的操作系统，或者有多个显示器时，顶到边界后，会有不同的处理逻辑，正常是顶到桌面的可活动区域时，系统就应该禁止再往上移了，但苹果这边可能逻辑不一样。还有一种情况是两个显示器，上下叠放，下面的是主显示器，这样，系统就可能会把应用顶出的部份放到上面的显示器上了。

后继版本我会在代码逻辑上做个调整，如果宽度或者高度超过了显示器的屏幕大小，就按显示器的屏幕的大小来显示。

**Comment by fedstryale** [comment]
其实窗口高度是小于显示器高的，另外我测试了，加不加外接显示器都是这个现象，现在的解决办法是人为把窗口高度缩小到一个值，每次打开边框就刚好顶到系统菜单栏下面，只是这样窗口下面会空出一截，不知道是不是因为初始化是从显示器中间某个坐标值开始渲染的，而这样一种渲染方式或坐标跟新的MacBookPro不太兼容，毕竟换了分辨率又刘海的

**Comment by suziwen** [comment]
刘海屏确实没考虑到。

可以更新到 8.9.25 看看，启动时，如果发现窗口要显示的位置不合理，就自动将窗口居中。

**Comment by fedstryale** [comment]
更新后软件行为正常了，重新打开后能原大小回到原来位置，高度也不影响了
