### ISSUE TITLE
行内公式输入繁琐

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1646]
行内公式输入需要输入`!$$`五个字符才能开始公式内容的录入，比较繁琐。有没有快捷键直接输入这几个字符

**Comment by suziwen** [comment]
可以到 `设置>语法扩展` 里，把兼容通用 mathjax 语法功能打开，这样就可以直接输入 `$` 进行行内公式了。

也可以通过创建一个[片段](http://soft.xiaoshujiang.com/docs/tutorial/snippet/#codemirror20e7bc96e8be91e599a8e78987e6aeb5e8afade6b395_22)，然后把这个片段绑定到 insertSnippet [命令](http://soft.xiaoshujiang.com/docs/tutorial/commands/#insertsnippet_23)里，这样就可以通过[快捷键](http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/)输入文字内容了

片段内容

```
`!$$${cursor}$$ `
```


https://user-images.githubusercontent.com/57370/181742843-51fdc4f4-7f69-4d21-aaf5-d8d2f6a6c8f4.mp4
