### ISSUE TITLE
更新版本后索引丢失

### ISSUE THREAD

**Issue by yoko-murasame** [suziwen/markdownxiaoshujiang#1652]
更新至  v8.10.0 文章索引（左侧目录）丢失，然后有的笔记未同步到本人（印象笔记），有办法补救吗？
试过导出数据库 但是没用 貌似都没了

**Comment by linut** [comment]
我也是，一篇重要的文章丢失了，找了一上午没找到，心态崩了。

**Comment by linut** [comment]
而且更新到8.10  连不上印象笔记，报错 is trusted  true

**Comment by linut** [comment]
回退8.9后，所有索引、模板都丢失了

**Comment by linut** [comment]
有什么办法能找回吗？

**Comment by yoko-murasame** [comment]
> 回退8.9后，所有索引、模板都丢失了

同情况

**Comment by suziwen** [comment]
@yoko-murasame @linut 

我这边测试，正常从 8.9.x 版本升级到 8.10 是没问题。不过还是建议每次客户端升级都自行进行备份数据的。

该版本升级了底层 nwjs，没办法直接回退。回退后数据就直接重置了。

**Comment by yoko-murasame** [comment]
建议更新公告中发提醒不要回退版本，这个丢失未保存的数据影响有点大 @suziwen

**Comment by linut** [comment]
看来真找不回来了，心痛到无法呼吸
