### ISSUE TITLE
图片和公式太多的时候预览会变得非常卡

### ISSUE THREAD

**Issue by RoggeOhta** [suziwen/markdownxiaoshujiang#1654]
在新的文档里往往速度很快，图片和公式可以秒渲染，但是对于比较长的文档，渲染速度就会变得非常慢，甚至有些卡顿，尤其是图片和公式。
几万字的文档，现在新插入一个图片可能需要好几秒才能完成（我的机器是2022年的主流配置，应该不存在性能问题）
#1346 和这个问题类似，不知道2年过去是否有相关进展了呢？

**Comment by suziwen** [comment]
能把重现的文章使用小书匠导出 zip 功能导出来，然后发到我的邮箱里吗？ suziwenjob@gmail.com 

小书匠的预览很早就已经是局部渲染了，速度应该很快。而且小书匠现在支持所见即所得，完全可以不用打开预览区，就能在编辑区里查看公式的显示效果。

**Comment by RoggeOhta** [comment]
[https://res-geo.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]笔记.zip<https://1drv.ms/u/s!ApP44hE4_IASgYtoZvigZgj3N55tNw>

________________________________
发件人: 苏滋文 ***@***.***>
发送时间: 2022年8月15日 1:57
收件人: suziwen/markdownxiaoshujiang ***@***.***>
抄送: RoggeOhta ***@***.***>; Author ***@***.***>
主题: Re: [suziwen/markdownxiaoshujiang] 图片和公式太多的时候预览会变得非常卡 (Issue #1654)


能把重现的文章使用小书匠导出 zip 功能导出来，然后发到我的邮箱里吗？ ***@***.******@***.***>

小书匠的预览很早就已经是局部渲染了，速度应该很快。而且小书匠现在支持所见即所得，完全可以不用打开预览区，就能在编辑区里查看公式的显示效果。

―

**Comment by RoggeOhta** [comment]
![test2](https://user-images.githubusercontent.com/19422794/184789062-9f80f24a-0a32-420c-be90-72176b708d59.gif)
![test3](https://user-images.githubusercontent.com/19422794/184789076-1652cfdd-4141-41e1-a787-1c31cb563efb.gif)
具体的表现如图所示，新建的文档几乎可以做到秒插入图片并显示，比较大的文档就需要好几秒，如果输入公式的话也是类似

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.10.1_fix


![未命名文件](https://user-images.githubusercontent.com/57370/185015793-67aab28b-2368-4aed-bca4-545b1a7c7e56.png)




1. 先到 `小书匠>关于` 界面上，备份下数据目录的文件
2. 安装我上传的这个 fix 版本[小书匠](https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v8.10.1_fix)
3. 到 `小书匠>数据>基本>文章数据库` 界面上
4. 选择全部，然后点击导出数据库
5. 导出完数据库后，点击重置数据库
6. 重启小书匠后，再次打开 `小书匠>数据` 界面，选择导入数据库，导入刚才导出的数据库。
7. 导入数据库完成后，再重启下小书匠，图片插入速度应该比以前的快了。

**Comment by RoggeOhta** [comment]
问题已解决！非常感谢！
