### ISSUE TITLE
求助！回退版本导致数据丢失，无法找回！

### ISSUE THREAD

**Issue by linut** [suziwen/markdownxiaoshujiang#1655]
### 事情起因
最近小书匠升级了8.10.0版本，升级后发现软件报错，报错问题同 #1653 问题一致，因为着急工作，所以回退了版本，到8.9.12版本。
### 发现问题
**回退后发现小书匠中文件列表都没了！！！**但我认为既然同步了印象笔记，那印象笔记中应该有，然后去找发现一个恐怖的事情，印象笔记中没有，小书匠没有把笔记同步到印象笔记中！！当时把这个问题也在Issues上反馈了，问题#1652，然后发现也有人有同样的问题，但确定丢失后没办法，只能重新写。
但今天在印象笔记中翻以前的文件发现一个更严重问题，有个文件我一直在记录流水，发现印象笔记中只同步到了2021年11月份的，说明**我有近9个月份的数据未能从小书匠同步到印象笔记！！！这些数据对我非常重要，这些数据我没办法回忆，也没办法重写，心态有点崩。**
### 问题处理

1. 丢失的文件能够回忆起来的，我都重新写了。好在我喜欢记完就归档，清空列表，所以丢失的不多，这一部分没有问题。
2. 但那个流水文件对我非常重要，丢失了近9个月的数据我无法找回，这个非常影响我的工作。我通过恢复数据库、重新升级版本、去网页版找缓存（虽然不大可能，病急乱投医了），我能想到的方式都做了，但依然没能恢复。

### 求助
希望有方式能找回以前的数据，如果有方式能够恢复数据，愿意给与一定报酬，可以先商量后再提供方案。万分感谢！！！
以下是我的邮箱：fenzang6255@sina.com，如有大佬麻烦能联系我下，再次感谢！！！
@syziwen，苏大佬，您那有还什么方案可以恢复的话麻烦也联系我一下，真的万分感谢！我以前是付费用户，后来没怎么用付费功能，这两年就白嫖了，可能这是我的报应吧，如果数据能恢复的话我就再也不白嫖了QAQ。

**Comment by suziwen** [comment]
首先，对于因回退版本后数据丢失的情况，我也表示很遗憾难过。


# 关于印象笔记同步问题

印象笔记的同步并不是自动的，需要自己主动触发 `ctrl+s`，而且需要把印象笔记做为默认的第三方存储，编辑的文章和印象笔记进行了关联(文章列表左侧的图标显示为印象笔记的图标)，这个在文档里有说明的。如果不把印象笔记做为默认的第三方存储，就需要点另存为保存。


# 关于恢复

## 硬件层面的恢复

感觉可能性不大，除非在你回退到 `8.9.12` ，发现数据不对时，立即停止对数据目录所在的盘进行任何操作，然后通过硬盘底层数据碎片恢复，可能会找出来文章来，但这个超出了我的能力范围，而且进行硬盘数据恢复价格是相当昂贵的。

## 软件层面的恢复

在回退到 `8.9.12` 后，发现数据不对时，不知道当时备份了数据目录没？如果备份了，可以将数据目录压缩后，发我邮箱 suziwenjob@gmail.com 

虽然这种方式的恢复，可能性也不是很大，不过可以看下。

## 其他

1. 如果你有配置了数据中心的同步，并使用了小书匠的临时服务器，或许我可以帮你看看这边还有没有。
2. 如果你在浏览器上编辑过那篇文章(比如你说的流水文章)，可以到对应浏览器上再次访问小书匠网页，一般没对浏览器清空数据操作的话，都是会保存一份的。

# 最后

我并不介意免费用我的软件，但不管免费还是付费，都应该有备份的意识，因为小书匠是一个本地软件，并且所有数据都是保存在本地的，小书匠并不提供云存储服务。

如果你把小书匠当成笔记系统来用，就要有一定的意识，备份数据，不管是自己通过外部软件定时备份数据目录的文件，还是通过小书匠的数据导出，再或者自己搭建一个数据服务器中心，进行自动同步。这些操作都是必须的，现在可能是因为版本回退问题引起的，并不能保证将来还有其他原因，比如硬盘自己坏了，或者操作系统升级失败把对应的分驱数据搞丢了，再或者病毒破坏了文件，再或者我技术太差，升级了个错误的版本（是人都有打盹的情况）。

如果只是把小书匠当成编辑器来使用，数据备份可能就不那吗重要，但自己肯定要在每次退出小书匠前，及时将所有文章保存到自己信任的位置上，不管是本地的其他文件夹位置或者印象笔记，github 等上。

**Comment by linut** [comment]
首先感谢大佬的回复，每一条我都认真看了，本次的确是我这边没有数据备份意识，这次给了我一个很大的教训。

我当时回退之后的确备份了数据库文件，但我打开后没看到有用的信息，这两个文件我也通过邮件发您了，麻烦大佬抽空帮看下能否通过这个恢复。

另外我有备份磁盘的习惯，2022年6月8日备份了一份磁盘文件在移动硬盘上，小书匠的安装、配置文件应该都还在这个磁盘上，不知道能不能通过这个恢复到6月8日的数据？麻烦大佬给指点下。

**Comment by linut** [comment]
经过尝试，上面方法是可行的！
我把备份磁盘上面数据库和安装文件都复制一份过来，打开后是可以看到之前的文件，虽然丢失了2个月数据，但我现在已经很满足了。

**Comment by suziwen** [comment]
不是这两个 json 文件，是数据目录的文件（关于界面上有数据存放目录的位置）。因为回退后，文件列表的文件已经看不到了，这个时候直接通过数据库的导入导出就没有意义了。而且这两个 json 文件才几 kb ，文件再怎么压缩，也不可能压缩得这吗小，直接用一般的文本编辑器就能看到里面的内容。

而这时候备份数据目录下的文件才是最好的选择。数据目录下有些文件因为缓存需要并不会直接删除，所以一开始是想通过这里查找最近被修改的文件是否可能恢复。可以把这个数据目录下的文件压缩发邮件过来看看。

**Comment by linut** [comment]
其他文件我这边当时没有备份，只是下载了这两个json文件。目前我已经通过备份磁盘文件恢复到了6月份的数据，已经把影响降低到最小了，感谢大佬的关注，我这就信仰充值去。
