### ISSUE TITLE
end 键移到行末

### ISSUE THREAD

**Issue by RainbowXie** [suziwen/markdownxiaoshujiang#1656]
当一行很长的时候，会被折成几行。end 键之前是移到被折的行的最后，后面逻辑被更改了，移到了行末。这个怎么改回去呢？

**Comment by RainbowXie** [comment]
这个逻辑对于开发来说很合理，但是对于其他文章，一个段落本来就会很长不敲回车键。

**Comment by suziwen** [comment]
可以自定义[快捷键](http://soft.xiaoshujiang.com/docs/tutorial/shortcuts/)，把 home/end 键的行为绑定到命令 `goLineLeft/goLineRight` 上



https://user-images.githubusercontent.com/57370/187036770-f4489d71-1bd0-4ca9-871a-87cd1f09b554.mp4

**Comment by RainbowXie** [comment]
改好了，谢谢！
