### ISSUE TITLE
旧版本升级问题

### ISSUE THREAD

**Issue by dadadaguyue** [suziwen/markdownxiaoshujiang#1659]
# 升级新版客户端
- 大半年没有升级客户端，看到旧版客户端可能数据库不支持，如何同步数据到新客户端
- 如何查看现在版本号和数据库版本

**Comment by suziwen** [comment]
1. 先备份数据目录里的文件。数据目录位置可以到 `关于`界面上查看到。(版本号也可以在关于界面上看到)

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```
2. 再直接升级，一般都会自动同步成功的。
 
3. 如果失败的话，可以用备份文件夹覆盖数据目录位置，然后启动旧版本的小书匠，到`小书匠>数据>本地`, 里选择导出数据库（选择时间范围要覆盖到）,然后启动新版本的小书匠，再到 `小书匠>数据>本地`，把数据导入。

**Comment by dadadaguyue** [comment]
作者大大，我的这个版本号是8.6.11
![image](https://user-images.githubusercontent.com/87740597/188569149-da179a42-d717-474e-a25f-5f2f367f1348.png)
## 直接升级的步骤这样是否可行
1. 解压安装包到旧版本目录
2. 安装位置选择旧版本安装位置，替换升级

**Comment by suziwen** [comment]
数据目录所在的文件夹只要备份了就可以。

备份完，直接将最新版本的小书匠覆盖安装，启动小书匠就可以了。

（备份数据目录的目的是防止升级失败，或者版本回退引起的数据问题时，有一个防范手段。）

**Comment by dadadaguyue** [comment]
升级成功了，谢谢作者大大了
