### ISSUE TITLE
每次保存成功后，鼠标光标都会回到首行，不方便

### ISSUE THREAD

**Issue by aisuhua** [suziwen/markdownxiaoshujiang#166]
因为习惯了没写完一句话就直接 Ctrl + S 保存一下。但是当保存成功后，此时右上角的会出现 “保存成功”，并随之消失。

但是为什么消息过后，鼠标的焦点会重新回到首行的第一个位置的？ 感觉这样设计真的不好，不知道是不是一个 bug？

最后，编辑器真的很好用！一直在寻找像这样的编辑器。

**Comment by suziwen** [comment]
web版还是客户端版本？客户端的话版本号，操作系统环境？

**Comment by aisuhua** [comment]
小书匠客户端版本: 1.9.1  Window 64 版（刚刚从官网下载的） 

操作系统：Window 7 64位

我试过，在书写和非书写模式下，都有这个问题。

我录了一个 gif ，你看看：

http://7xj8ix.com1.z0.glb.clouddn.com/ScreenGif.gif

**Comment by suziwen** [comment]
win7下我试了，也是正常的，你那换台电脑试下？
![aa](https://cloud.githubusercontent.com/assets/57370/14497633/07f92f6c-01ca-11e6-96ee-4f555e0315a1.gif)

**Comment by aisuhua** [comment]
可能是我电脑的问题了。我今天用公司电脑用的话，就没有这样的一回事。
我再看看是什么原因吧。不过说回来，如果可能自由设置是否弹出“保存成功”提示的话，可能会更好。其实我自己个人更偏爱不提示的方式，因为其他编辑器，都以一个 * 号来表示没保存这样，纯粹个人YY。

还是谢谢啦！
