### ISSUE TITLE
8.10.17版本修改预览主题

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1669]
修改预览主题按钮去哪里了呢？之前在编辑区和预览区都有快捷设置的按钮，现在怎么没有了

**Comment by suziwen** [comment]
改到下边区域了

**Comment by lingxiaqidu** [comment]
找到了，但是在下面跟那个萤火虫模式冲突啊，虽然萤火虫目前我也没用起来

**Comment by suziwen** [comment]
应该不会有太大冲突的，可能是操作鼠标的方式习惯引起的．

如果鼠标从文件列表区快速移动到编辑区（或者预览区）底部，才会显示这个萤火虫模式区域．如果鼠标只是在编辑区(预览区)里移动，是不会触发萤火虫区域的显示．

之所以把这些按钮放在下面，主要是这些按钮用得不是很频繁，所以就把它们放在更不容易被发现的区域，让整个页面看起来更简洁些．

-----

如果不用萤火虫模式，也可以主动把这个功能关闭掉的．
