### ISSUE TITLE
Win7 64位系统安装64位安装包从1.9.0覆盖升级到1.9.1无法进入编辑页面

### ISSUE THREAD

**Issue by soiff** [suziwen/markdownxiaoshujiang#167]
自动升级失败，于是我手动下载最新版本覆盖安装，然后启动就一直停留在启动动画，无法进入编辑页面；卸载1.9.1手动安装1.9.0版本问题依旧；

**Comment by soiff** [comment]
![Uploading 无标题.png…]()
![Uploading 无标题.png…]()

**Comment by suziwen** [comment]
把这个目录删除掉再启动1.9.1版本
`{Windows 7系统盘}/Users/{用户，比如Administrator}/AppData/Local/小书匠/Local Storage`

**Comment by soiff** [comment]
# @suziwen 确实是这个问题，多谢，问题解决！
