### ISSUE TITLE
全文搜索怎么用

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1670]
比方说我有一篇文档，里面有这么几个字
![image](https://user-images.githubusercontent.com/17762125/197770385-4cd88d85-7a38-471f-9824-6cbae2ab3299.png)
然后我在左上角的搜索框，搜索“同步原理”，什么结果也没有找到
![image](https://user-images.githubusercontent.com/17762125/197770543-dc094c73-8f1d-4614-957f-feaac367e488.png)

**Comment by suziwen** [comment]
我这边测试了下，是没有问题的

![image](https://user-images.githubusercontent.com/57370/197788088-ee880d5f-7dd2-4dd3-84eb-f720238ae569.png)


------------


是不是索引坏了？可以到 `小书匠主按钮>数据>索引`, 把 `全文搜索索引` 重新生成一下，再搜索呢？

![image](https://user-images.githubusercontent.com/57370/197788381-14915272-b4c0-4e15-9808-63844be9e32b.png)

**Comment by lingxiaqidu** [comment]
![image](https://user-images.githubusercontent.com/17762125/197912897-eb0a77b8-f4d1-486f-808d-2869b75f8cf9.png)
删除后重新索引，这个进度到169/5694就不动了咋回事呢

**Comment by suziwen** [comment]
那可能是出现 bug 了．估计是文章的具体内容引起的．

其他索引项能正常重新索引吗？比如 `query_index/by_plugin`

**Comment by lingxiaqidu** [comment]
其他正常，我把本地数据都删除了，重新下载数据就行了，不管了，谢谢
