### ISSUE TITLE
8.10.23 卡顿问题

### ISSUE THREAD

**Issue by RainbowXie** [suziwen/markdownxiaoshujiang#1671]
更新到 8.10.23 后如果打开预览视图就会变得非常卡顿，甚至打字都会有明显延迟，无法正常使用。

而且在代码块选语言的时候程序直接卡死 2-3 s。

**Comment by RainbowXie** [comment]
测试网页版并不会卡。

**Comment by suziwen** [comment]
1. 你的文章是不是很复杂或者很长，试着创建一篇简单的文章呢？
2. 或者试着把小地图 minimap 滚动条关了，看有没有改善?

![image](https://user-images.githubusercontent.com/57370/200129804-41dbaead-6b37-4eaf-b6d7-9d6fd12f058e.png)

**Comment by RainbowXie** [comment]
> * 你的文章是不是很复杂或者很长，试着创建一篇简单的文章呢？

确实是很长的文章。关了 minimap 之后就好了，谢谢额！
