### ISSUE TITLE
支持同时绑定多个第三方数据

### ISSUE THREAD

**Issue by RainbowXie** [suziwen/markdownxiaoshujiang#1672]
出于数据备份的考虑，有多个第三方存储点。
![image](https://user-images.githubusercontent.com/34147843/203901569-aaaced2c-5ac3-4f60-b9d2-c100cf358dac.png)
能不能支持同时绑定多个第三方数据接口在这显示？

**Comment by suziwen** [comment]
这个应该不会考虑，一般一个默认第三方存储就够了，如果确实有需要保存到其他第三方存储，这时候可以点击`另存为(ctrl+shift+s)>选择其他绑定`．


![image](https://user-images.githubusercontent.com/57370/204027248-17c9d41d-8532-41f8-8079-f9a9c53412ba.png)

**Comment by RainbowXie** [comment]
好吧，就是觉得这个很麻烦
