### ISSUE TITLE
如何在写作区，禁用图片预览？

### ISSUE THREAD

**Issue by ismart-yuxi** [suziwen/markdownxiaoshujiang#1675]
我的图片很多，但是在禁用区就开始预览图片，导致我看到满屏好乱啊，我找了设置也没看到禁用写作区预览图片的选项

**Comment by suziwen** [comment]
写作区下边一排按钮里有个设置按钮。

![te](https://user-images.githubusercontent.com/57370/206888258-e8d76b1e-c5ee-40d7-81f1-b7c31601f481.png)

**Comment by ismart-yuxi** [comment]
### 收到谢谢！
