### ISSUE TITLE
下载页面和Release页面  typo error 

### ISSUE THREAD

**Issue by SChen1024** [suziwen/markdownxiaoshujiang#1676]
再下载页面和release 页面 再写 mac 启动的指令的时候有问题， 可以下次修改一下

> Mac M1/M2 机器的用户，请下载 osxarm 版本 如果发现不能启动，可以尝试执行下面的命令
> cd /Users/suziwen/Downloads/Story-writer-osxarm
> xattr -cr ./Story-writter.app

后面这个 多打了一个t 导致出现问题 
应该是
`
xattr -cr ./Story-writer.app`
我看多个release 版本都都是这个， 就提醒一下，

**Comment by suziwen** [comment]
感谢提醒
