### ISSUE TITLE
关于升级小书匠DrawIO的需求

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1682]
小书匠中DrawIO用来画些图非常好用，但现在里面的版本不支持复制图片，绘制复杂图形的时候很受限 ，新的版本支持了，能不能升级下。或者能不能教一下怎么升级，我自己弄也行

**Comment by suziwen** [comment]
这个好像上次提到过了。

我先把你说的复制图片功能添加上。现在最新版本应该就可以直接从剪切板里粘贴图片了。

**Comment by lingxiaqidu** [comment]
给力，赞一个
