### ISSUE TITLE
编辑区不能正常预览

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1684]
![image](https://user-images.githubusercontent.com/17762125/226793282-5ae7333f-9ea7-443d-9acc-f4e67b9ff576.png)
如上图所示，表格中有美元符，表格可以正常显示，但是后续添加标题就失效了，不能显示预览的状态，但是右侧的阅读区是正常的

**Comment by suziwen** [comment]
我这边好像没办法重现

![image](https://user-images.githubusercontent.com/57370/226932698-3adb73a5-5052-46ab-b83e-ec17eab08e59.png)

能贴一下重现的内容片段,或者做为附件上传一下吗

**Comment by lingxiaqidu** [comment]
| Option | Description |
| --- | --- |
| `--help` or `-h` | $Show command line help. |
| `--version` | Display WiX Toolset version in use. |
| `--nologo` | Suppress displaying the logo information. |


上面这个就不行

**Comment by lingxiaqidu** [comment]
但是新建一个文件把内容复制进去又可以，原始文档我发到你的邮箱了

**Comment by suziwen** [comment]
可以在元数据里，把 mathjax 语法关了

```
grammar_mathjax: false
```

或者到 `设置>语法扩展>mathjax公式` 里，通过全局，把数据公式取消掉

![image](https://user-images.githubusercontent.com/57370/227947865-9edbf5e9-6ac5-4b3a-a9b6-b3c8001de52a.png)

**Comment by suziwen** [comment]
可以在元数据里，把 mathjax 语法关了

```
grammar_mathjax: false
```

或者到 `设置>语法扩展>mathjax公式` 里，通过全局，把数据公式取消掉

![image](https://user-images.githubusercontent.com/57370/227947865-9edbf5e9-6ac5-4b3a-a9b6-b3c8001de52a.png)

**Comment by suziwen** [comment]
可以在元数据里，把 mathjax 语法关了

```
grammar_mathjax: false
```

或者到 `设置>语法扩展>mathjax公式` 里，通过全局，把数据公式取消掉

![image](https://user-images.githubusercontent.com/57370/227947865-9edbf5e9-6ac5-4b3a-a9b6-b3c8001de52a.png)

**Comment by lingxiaqidu** [comment]
不行啊，公式也是经常用的

**Comment by suziwen** [comment]
可以全局设置里打开公式语法开关，然后在需要特殊处理的单篇文章里，通过元数据 `grammar_mathjax: false` 把这个语法关掉。

-------

也可以更新到 `8.12.4`, 我调整了行内公式在编辑器内的解析逻辑，如果出现空白行，就中断对公式的后继识别。

这样应该能解决大部份的情况。

不过由于美元符号太过常用，用来做为数学公式的分隔符，感觉很难做到统一。
