### ISSUE TITLE
本地导入的文件修改无法保存

### ISSUE THREAD

**Issue by zmcui** [suziwen/markdownxiaoshujiang#1686]
问题描述：
通过“导入->选择文件”打开了文件，修改部分内容后， 点击菜单“保存”，显示“保存成功”
通过文本程序打开该文件，没有修改的内容
版本：
Ubuntu2004
当前版本: 8.12.0
服务器最新版本: 8.12.0

**Comment by suziwen** [comment]
导入是无法自动同步本地文件的修改。

想要监听文件的变化，并自动保存到本地，有两种方式。

1.  通过命令 `/小书匠安装路径/story-writer  /markdown文件路径/markdown文件名.md` 方式打开，可以自己配置系统的应用程序默认打开方式，这样以后双击扩展名为 md 的文件，就自动使用小书匠打开了。
2. 也可以绑定本地文件夹，这样打开的文件就可以监听文件的改变，保存时，也会自动同步到本地的文件系统上。

**Comment by BianChengNan** [comment]
印象笔记中已经存在的文件，使用小书匠编辑后，保存也有类似的问题。按 ctrl+s 保存，没有同步到印象笔记。
为了验证，我单独在小书匠里新建了一个文件，然后保存，这样是没问题的。是不是最近改动了什么逻辑？判断不需要同步，所以就跳过了？

**Comment by suziwen** [comment]
@BianChengNan 最近的改动都不没有调整印象笔记的存储逻辑，应该不会有什么影响。能稳定复现吗？是不是这篇文章太大了？

**Comment by zmcui** [comment]
多谢
