### ISSUE TITLE
表格编辑区空白面积过大

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1687]
![image](https://user-images.githubusercontent.com/17762125/229732951-420db150-853f-47ad-9aaf-8b1cdbbb5481.png)
如上图所示，一个有两行的表格，下面一行文字紧跟表格，为什么预览模式下间距那么大，能减小一下吗

**Comment by suziwen** [comment]
嗯，后面再调整下。
