### ISSUE TITLE
小书匠官网https过期了

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1688]

**Comment by suziwen** [comment]
感觉提醒，差点忘记了😄

**Comment by lqdflying** [comment]
更新出错,大佬还没有部署海外更新节点吗?需要我赞助一台VPS吗

**Comment by suziwen** [comment]
更新出错是报什么错？

暂时没打算分开部署。

**Comment by lqdflying** [comment]
人在国外,下不下来,挂回国代理才算更新完

**Comment by suziwen** [comment]
我记得 GFW 应该没有限制国内的服务器被外网访问，只是限制了国内的用户不能访问特定国外的服务。

国外访问我这国内的服务器不应该会被限制吧。

**Comment by suziwen** [comment]
不过更新也不是很频繁，要更新时，只能自己临时切下代理了。现在国外用户也不是很多，小书匠的市场也主要以中文为主，也就不想花太多精力在这上面了，抱歉哈😅。

**Comment by lqdflying** [comment]
大佬客气了,没有关系,总是有办法的
