### ISSUE TITLE
停留在启动界面无法转圈

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#1690]
提示 同步服务启动失败

**Comment by suziwen** [comment]
能进入到编辑区的界面吗，还是一直停留在小书匠 logo 页面上？重启下小书匠呢？

**Comment by liao20081228** [comment]
> 能进入到编辑区的界面吗，还是一直停留在小书匠 logo 页面上？重启下小书匠呢？

一直在logo上，重启PC都不行

**Comment by liao20081228** [comment]
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/ccef4862-3115-4fcd-b9bf-6f9ef3bfa675)
一直在这转圈圈

**Comment by suziwen** [comment]
没出现过这种情况，你的操作系统是什么版本的，上次退出小书匠时，有什么异常吗？

------------


试着把数据目录的文件移走，再重新打开试下。

把下图第 5 个步骤指定的目录( User Data 这个文件夹)备份一下。然后试着移走 第 6 步的 Local Storage 文件，启动下小书匠看看。

如果还是不能启动，试着把第 6 步的 `Local Storage` 和 紧挨着的 `IndexedDB` 都移走，再启动看一下。

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/c7bed4f3-6c7d-4b10-ae28-c38ff1fb4070)

**Comment by liao20081228** [comment]
把下图第 5 个步骤指定的目录( User Data 这个文件夹)备份一下。然后试着移走 第 6 步的 Local Storage 文件，启动下小书匠看看。
如果还是不能启动，试着把第 6 步的 Local Storage 和 紧挨着的 IndexedDB 都移走，再启动看一下。


![image](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/97f9437b-7418-460f-88bb-e62f414c238b)

**Comment by liao20081228** [comment]
解决了

**Comment by liao20081228** [comment]
> 把下图第 5 个步骤指定的目录( User Data 这个文件夹)备份一下。然后试着移走 第 6 步的 Local Storage 文件，启动下小书匠看看。 如果还是不能启动，试着把第 6 步的 Local Storage 和 紧挨着的 IndexedDB 都移走，再启动看一下。
> 
> ![image](https://user-images.githubusercontent.com/25471051/246667256-97f9437b-7418-460f-88bb-e62f414c238b.png)

为什么我每次启动都没法启动，需要删除掉Local Storage 才能启动？另外为什么同步的时候绑定无法自动同步到配置中？我看了配置里面有数据，但是绑定没生效。另外按键也没有生效

**Comment by liao20081228** [comment]
需要什么日志？

**Comment by liao20081228** [comment]
2023-07-24T15:00:37.110Z - error: Error in .on("change", function):
2023-07-24T15:01:28.449Z - error: worker process mathjax fail , fallback to normal process
2023-07-24T15:01:30.818Z - error: worker process mathjax fail , fallback to normal process
2023-07-24T15:01:31.063Z - error: worker process mathjax fail , fallback to normal process
2023-07-24T15:02:08.252Z - error: worker process mathjax fail , fallback to normal process
2023-07-24T15:02:09.779Z - error: worker process mathjax fail , fallback to normal process
2023-07-24T15:30:40.191Z - error: Error in .on("change", function):

**Comment by suziwen** [comment]
1. 删除 `Local Storage`， 启动后，你看一下最近修改的几篇文章标题名称有没有什么特殊符号？

2. 能把日志文件发我邮箱吗? <suziwen1@gmail.com>

3. 你是不是没有在 `用户>用户管理>用户配置` 把实时同步打开

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/14b27127-2cff-4751-9641-71b3a4a23bb3)


------------------

如果上面操作比较乱，可以试着按[这个](https://github.com/suziwen/markdownxiaoshujiang/issues/1693#issuecomment-1575750664)
把数据文件路径修改到其他位置上，观察一段时间，看是不是每次启动小书匠都停在转圈页面。

**Comment by liao20081228** [comment]
> 1. 删除 `Local Storage`， 启动后，你看一下最近修改的几篇文章标题名称有没有什么特殊符号？
> 2. 能把日志文件发我邮箱吗? [suziwen1@gmail.com](mailto:suziwen1@gmail.com)
> 3. 你是不是没有在 `用户>用户管理>用户配置` 把实时同步打开
> 
> ![image](https://user-images.githubusercontent.com/57370/255651914-14b27127-2cff-4751-9641-71b3a4a23bb3.png)
> 
> 如果上面操作比较乱，可以试着按[这个](https://github.com/suziwen/markdownxiaoshujiang/issues/1693#issuecomment-1575750664) 把数据文件路径修改到其他位置上，观察一段时间，看是不是每次启动小书匠都停在转圈页面

我有勾选同步，点进去有很多冲突分支，这怎么产生的？一边在网页用，一边在本地用。是不是数据同步导致的？我在本地修改配置后网页不会刷新？

**Comment by liao20081228** [comment]
![local](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/2cc98192-9fd3-454d-b5d4-0d991821b968)
![web](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/ac54cbf4-7a29-46f7-8928-d8127d2d4d8b)

这个修改；了配置，web版本就是没法同步仓库。要不就是我web修改了仓库，本地登陆后没法自动配置。

**Comment by liao20081228** [comment]
![捕获](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/483aca97-a024-4c31-943c-c2b1599ddd37)

**Comment by liao20081228** [comment]
这个配置数据同步机制怎么回事呢？我在本地点击了重置配置。但是过了一会，显示变成这样了， 我看前面那个序号就是每一次配置的吧、怎么会有2和139冲突？我139不是刚刚已经重置了吗？

**Comment by liao20081228** [comment]
还有这个即时预览，我关闭了不生效呢？

![捕获](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/f3534d6d-ef97-4fc9-bbad-523d11dd1b07)

**Comment by suziwen** [comment]
这个是因为有三个以上同步的客户端，一个网页，一个桌面，一个小书匠临时服务器。一般在桌面上点击重置配置文件时，只重置桌面本机和小书匠临时服务器。想要完整重置的话，就要保证连网的客户端都被重置。

不过一般可以不管这些冲突，系统默认会使用最新的那个版本。

你试着切换主题，或者修改下第三方绑定的别名，这样，同步机制就会以你当前机器的版本为基础进行同步了。

**Comment by suziwen** [comment]
立时预览这个我好像没问题,你试着重启下小书匠呢？


https://github.com/suziwen/markdownxiaoshujiang/assets/57370/0023582d-a249-4096-9e1a-63d67d3fddcf

**Comment by suziwen** [comment]
这个视频是第三方绑定同步的效果



https://github.com/suziwen/markdownxiaoshujiang/assets/57370/955b4ac0-f70c-4a46-8223-b48cd860bf6b

**Comment by liao20081228** [comment]
![捕获](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/60a72add-ed63-4ba0-90b2-83a78b40d13b)
![捕获1](https://github.com/suziwen/markdownxiaoshujiang/assets/25471051/85943529-fe13-44a5-a507-e3d95f35555b)
这是我重置了本地和web端后，清空浏览器的东西。然后卸载本地端删除appdata数据之后重装，我在绑定重配置了库。然后打开用户配置。里面仍然没有变化呢？

**Comment by liao20081228** [comment]
定位一下这个问题，我已经持续大半年这样了。

**Comment by suziwen** [comment]
你可以试着这样操作，

1. 关闭网页端

2. 再在客户端里，把 `用户>用户配置>是否实时同步客户端配置` 选项关闭掉，点击`应用`后。 再点击`重置配置文件`,

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/6becd268-23e4-4228-8948-ffeae40c235e)


3. 再访问网页端，点击 `用户>用户配置`， 点击 `重置配置文件`
4. 再回到客户端，把 `是否实时同步客户端配置` 重新打开。
5. 刷新下网页
6. 这时候改客户端的第三方绑定，主题等，看网页是否正确同步。

**Comment by liao20081228** [comment]
我有两个浏览器edge和chrome。按照你这步骤我在edge的本地端做了。可以。ok。但是当我登陆到chrome时问题又出现了，配置文件的版本都是ok的，但是配置没有应用到编辑器。

**Comment by suziwen** [comment]
你用 chrome 新建一个全新的会话，或者用 chrome 的隐藏模式访问小书匠，登录后，也是没办法应用到编辑器里？

**Comment by liao20081228** [comment]
> 你用 chrome 新建一个全新的会话，或者用 chrome 的隐藏模式访问小书匠，登录后，也是没办法应用到编辑器里？

明晚我再复现一下，这个问题真奇怪

**Comment by liao20081228** [comment]
可以了。重置之后，完全重新配置就可以了。
