### ISSUE TITLE
数据文件路径 

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1693]
现在数据文件已经快5G了，C盘空间很有限，能把数据文件存储到其他盘吗

**Comment by suziwen** [comment]
可以的。

修改安装目录下的 `package.json`

把第 20 行改成 `"chromium-args": "--user-data-dir=d:/xsjdata --enable-node-worker --disable-devtools",`，启动后，就是在新数据目录下运行了 。 

可以把原始数据目录文件拷贝到新的数据目录下（需要保持目录结构一致），这样就可以继续以前的文章操作了。 

**注意新数据目录的路径最好不要有空格和中文。**

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/e68bde0a-7a84-428d-b7c6-901ee12f8978)

-------------


如果想避免每次系统升级小书匠客户端时，配置文件被重置的问题，可以通过命令行启动来修改数据目录的位置 `Story-writer.exe --user-data-dir=d:/xsjdata`, 把这个启动命令做成 bat 文件，以后点击这个 bat 文件就可以直接启动小书匠了。

**Comment by CodeEngieer** [comment]
作者，作者，我在清理C盘的时候，数据库文件全部丢失了，重新打开后，只有我最近写的几篇文章。之前的文章数据全部丢失了怎么办？

**Comment by suziwen** [comment]
@CodeEngieer 

这个没有比较好的办法，只能看操作系统有没有备份还原的功能了，没有任务备份措施的话，数据基本很难恢复。


------


建议以后完稿的文章及时保存到其他第三方存储上。

如果把小书匠做为笔记软件使用的话，最好了解下数据存放位置，做好定时备份处理，也可以使用小书匠的天马版，用 Docker 搭建自己的数据中心，将数据统一在一个位置上。
