### ISSUE TITLE
8.12.26修改编辑器主题

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1699]
最新版本修改编辑器主题在哪里呢，怎么找不到了，编辑下面只看到这几个选项
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/17762125/15c6c93a-fe0d-49f5-9247-837fc3475bfe)

**Comment by lingxiaqidu** [comment]
找到了

**Comment by kkHAIKE** [comment]
在左边panel 的下方，💧
