### ISSUE TITLE
Evernote绑定失败

### ISSUE THREAD

**Issue by zhangdoa** [suziwen/markdownxiaoshujiang#1704]
你好，

我在8.12.43版本上尝试绑定我的Evernote账户，弹出页面显示“certificate has expired”。我的小书匠账户中曾经有过一个Evernote绑定，但是已经不能连接，编辑器界面会弹出红色错误提示类似“CERTI_ERROR”的信息，所以我删除了旧绑定然后重新试着绑定一次。

**Comment by suziwen** [comment]
应该可以了，好像是 evernote 最近更新了 ssl 证书引起的。

**Comment by zhangdoa** [comment]
测试已经可以使用，谢谢！
