### ISSUE TITLE
新功能建议：增加一列子列表用于添加关联的文件

### ISSUE THREAD

**Issue by CodeEngieer** [suziwen/markdownxiaoshujiang#1705]
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/75971727/cd9bb5ad-f6f2-4a02-9305-aea46ec08907)
我希望新版本能添加一行，并且能自由放大缩小，而非横着的，用于封装较大或者是常用的较大的代码组以便于复习，一个一个链接查看有点复杂，但如果多一列就方便很多。例如我做这个任务系统，点击这个第二列就可以显示我关联的一系列的解决设计方案，点击设计方案就可以刷新第一列，第二列显示设计方案的具体内容。也就是子文件显示

**Comment by suziwen** [comment]
没太理解你的需求描述，不知道将过滤器界面固定是否能满足。

![2023-10-04_21-08](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/275da9cf-0f38-47c6-b8e3-876dd4af95c1)

**Comment by CodeEngieer** [comment]
我的意思是让左边列表再多一列，多一列的内容显示所关联的文件，这样的话我可以写一些系统设计的解决方案。点击这个第二列就显示不同的解决方案（不过这个要跟点击事件冲突做下处理），点击方案后第一列刷新为第一层级、第二列为具体的解决方案内容。不知道这个功能合理没？我想用这个存储我针对于某个模块的不同设计方案

**Comment by suziwen** [comment]
你是想拿到当前文章引用与被引用的关系？

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/946e1200-d839-440f-9c48-396ad9c8c956)

**Comment by CodeEngieer** [comment]
看来是这样的，实现了，两列的话会更直观。我做下改动

**Comment by CodeEngieer** [comment]
麻烦作者了，是我的问题。Close一下吧，这个功能还没有发现。
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/75971727/11b98add-20cb-4bad-a236-1cdca75d0aac)

**Comment by suziwen** [comment]
系统过滤器里，也有一个直接拿反链的过滤器的。

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/d47e5132-64b4-42d2-afac-4a44abb00621)
