### ISSUE TITLE
编辑区“C++”预览不正确

### ISSUE THREAD

**Issue by lingxiaqidu** [suziwen/markdownxiaoshujiang#1726]
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/17762125/7ba4e99a-82d2-4efd-8665-75173f4fa6c6)
![image](https://github.com/suziwen/markdownxiaoshujiang/assets/17762125/fcfcb8f5-e5ba-45bd-ae74-dd79abc99755)
如上面两图所示，我输入的是C++字样，但是预览的时候就变成了第一张图那样，只有在++后面输入一个空格显示才正常

**Comment by suziwen** [comment]
这个是因为默认打开了 `文字格式插入语法`，系统把 `++` 识别成了插入(下划线)语法。

可以在 `小书匠>设置>语法扩展` 把 `文字格式插入` 选项关掉。

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/1ba517a2-1c1e-4b83-a4d4-09088f29ec71)


上面的设置是全局的，如果只想对当前文章取消，可以在元数据区里加 `grammar_ins: false` 参数.

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/bfc2ac90-62b9-4024-bcb3-021871963951)

**Comment by lingxiaqidu** [comment]
好的，谢谢
