### ISSUE TITLE
Gitee码云图片载入问题

### ISSUE THREAD

**Issue by SiDaiJie** [suziwen/markdownxiaoshujiang#1727]
- 通过复制粘贴图片到一个新的markdown文件的时候，这个文件会转换成这样的标签

`![enter description here](./images/1709784012607.png)`

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/279aaa81-6d7a-4d3c-b788-1ddeb0330974)

上面的图片会在码云的`images`文件夹中保存着。到目前位置还没什么问题。

 - 通过手动上传图片素材到上面的`1709784012607.png`同个文件夹下

使用同样的语法，则图片不能正常显示。

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/93dbe763-ad00-4868-915c-8fa6dfac0dc9)

 - 在码云中则显示为这样的情况

很奇怪的是，在小书匠中能正常显示出来的图片在码云中也是可以直接看到的。
在小书匠中不能正常显示的图片在码云中是**能正常显示**的。
码云的结果：

![码云中的结果](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/e1ca2d03-feac-4b63-b885-87b3bd3c5842)

小书匠的结果：

![小书匠的结果](https://github.com/suziwen/markdownxiaoshujiang/assets/71361064/a5637abf-f687-4725-9feb-5810cab9913a)

**Comment by suziwen** [comment]
小书匠不会主动从码云上拉取数据，所以你单独在码云上添加的图片，小书匠这边是无法知道的。

通过小书匠粘贴的图片，保存到码云后，因为小书匠本地有一份图片版本，所以能够正常显示出来，但如果你自己使用其他工具，对码云上的图片进行修改，小书匠这边是不会检测到的，只会显示小书匠本地的版本。

想要更新本地缓存，需要自己右键对应的 markdown 文件，在弹出的菜单中，点击`更新本地缓存`，　这样系统才会从码云上拿取最新版本的 markdown 文件，**并对 markdown 引用的图片进行更新**。

![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/f24b1bcf-135d-4f09-8e2c-3aca63a56ec2)

**Comment by SiDaiJie** [comment]
噢，这太好了，Thanks
