### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by jiayihello** [suziwen/markdownxiaoshujiang#1728]
同时从网页复制文本和图片，粘贴到软件上时不显示图片，图片不会自动上传至绑定的图床

**Comment by suziwen** [comment]
纯图片可以直接复制粘贴，但图片和文字一起复制的话，目前步骤比较多些，需要右键，弹出的上下文菜单里，选择 `粘贴为>将富文本转换成 markdown 进行粘贴`。这时候粘贴的图片还是网页自己的图片地址，如果想转到图床上，需要点击 `图床转移按钮`.


![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/846afed2-8552-4bb4-a32e-e94cba0465db)



![image](https://github.com/suziwen/markdownxiaoshujiang/assets/57370/80ad59b0-a5b2-4392-9929-df7c3cade651)

**Comment by jiayihello** [comment]
谢谢
