### ISSUE TITLE
代码缩进导致的渲染错误

### ISSUE THREAD

**Issue by qingchuwudi** [suziwen/markdownxiaoshujiang#1733]
小书匠中书写markdown时，如果有代码缩进，那么这个缩进的代码后续的文字在小书匠的渲染中会被认为也是代码里面的内容。

例子：

```markdown
## 标题1
- 第一个
    ```bash
    ## 任意内容
    ```
- 第二个
```

正常来说要渲染成这种：

![图片](https://github.com/user-attachments/assets/f345885e-333c-457e-bb65-476f8fbb2c4b)

但是小书匠经常会渲染成这种：

![图片](https://github.com/user-attachments/assets/9637e0f6-5601-45e8-bba3-78d50e61bbac)

遇到这种情况以后关闭文档再打开，渲染也是错误的，必须要尝试在有问题的渲染前面（或者后面）再加一段代码，才会有几率恢复。而恢复以后如果不再编辑的话，渲染就会一直正常，如果再编辑还有概率会渲染出错。

**Comment by suziwen** [comment]
我这好像没有问题．

![image](https://github.com/user-attachments/assets/3a62c495-6c03-45ac-bcfa-e7e3c8adce79)

能否提供个可重现的文章，然后用小书匠的导出功能，导出 zip , 发过来．

还有就是你的小书匠版本是多少？

**Comment by qingchuwudi** [comment]
小书匠版本： 8.13.4 。

>下图是一个例子

![图片](https://github.com/user-attachments/assets/8cc47b23-1efd-414d-8d6d-107c22955440)


附件：[docker自建加速.zip](https://github.com/user-attachments/files/16451402/docker.zip)

**Comment by suziwen** [comment]
哦，我以为是说预览区预览效果不对，原来是指编辑区．
确实有问题，下个版本会修复，感谢反馈．

**Comment by suziwen** [comment]
更新到 `8.13.5` 后，应该就可以了．

**Comment by qingchuwudi** [comment]
试了几十个文章都是正常的
