### ISSUE TITLE
小书匠无法打开

### ISSUE THREAD

**Issue by qingchuwudi** [suziwen/markdownxiaoshujiang#1735]
### 问题：

1. 编辑一个文章时，连续插入了两个图片，文章突然变成空白，使用快捷键撤消编辑（CTRL+z）后恢复正常
2. 再次插入其他图片，又变为空白，再查看其他文章也全部是空白，并且小书匠卡死，无法做任何正常操作
3. 使用顶栏关闭按钮关闭小书匠，重新打开小书匠，小书匠卡在启动界面
4. 使用任务管理器结束进程，并重新打开，依然卡在启动界面

### 环境信息：

|        -           |  -
|--------------|----------------------
| 小书匠版本 | 8.13.5 
| 操作系统    | windows 11 23H2

### 其他

在文件夹 `C:\Users\{user}\AppData\Local\storywriter\User Data` 未找到错误日志，请问如何提供更详细的信息，以及如何排错？

> 另外，小书匠能够把couchdb中的所有文章一键导出为markdown吗？
> 如果可以导出为markdown，那就可以把历史文章保存为md文件，并用webdav做存储来管理，再遇到类似的情况也不会影响文章的阅读和编辑。

**Comment by suziwen** [comment]
1. 看一下, `User Data` 目录现在大小
2. 在桌面（或者其他位置），用其他编辑器创建一个空白的扩展名为 `.md` 的文件，然后用小书匠打开这个 md 文件（比如右键，使用小书匠应用打开）．看这种方式能启动吗？

**Comment by qingchuwudi** [comment]
1. `User Data` 471MB
2. 无法启动

![图片](https://github.com/user-attachments/assets/faf78be2-bbb1-4dfa-a39a-339c8a2f59a5)

**Comment by suziwen** [comment]
那试着把 `User Data` 目录下的 `Default/Local Storage` 目录删除掉（先备份下 User Data 目录），然后按刚才第二步骤启动小书匠呢？

![image](https://github.com/user-attachments/assets/24f3dd71-9bb6-42ed-8e72-d330fa86505c)

**Comment by qingchuwudi** [comment]
这样处理以后可以启动，但是文章仍然打不开：couchdb中的文章和markdown文件都打不开。

退出软件再重新打开以后，预览区正常，编辑区不可用。

在 `User Data` 中发现一个文件 `CrashpadMetrics-active.pma` ，这个对排查错误是否有帮助？

![图片](https://github.com/user-attachments/assets/65ba948e-40fb-4313-b095-e34cc7604950)

**Comment by suziwen** [comment]
估计文章内容触发了 bug, 可否把出现问题的文章，用小书匠的 zip 导出功能导出？如果无法切换到当前文章，可以用批量导出，再选择有问题的这篇文章．

**Comment by qingchuwudi** [comment]
[git工作流.zip](https://github.com/user-attachments/files/16538852/git.zip)

**Comment by suziwen** [comment]
知道原因了，图片语法解析错误引起的．

刚发布了 `8.13.6`, 更新下就好了．

**Comment by qingchuwudi** [comment]
恢复正常了 👍

**Comment by qingchuwudi** [comment]
导出文章为Markdown这里能加一个“全部选中”的功能吗？目前有几百个文章，逐个选想一想就头大。

![图片](https://github.com/user-attachments/assets/d339d6d8-180f-4786-931f-f490c8952b65)

**Comment by suziwen** [comment]
嗯，后面添加．
