### ISSUE TITLE
编写了文件保存完成后，光标会自动跳到文件首。。。

### ISSUE THREAD

**Issue by Neutree** [suziwen/markdownxiaoshujiang#174]
# 编写了文件保存完成后，光标会自动跳到文件首。。。

是这样设计的么？还是说在哪儿可以设置的？每次保存都会跑到开头去。。。很麻烦

**Comment by suziwen** [comment]
#166 
跟这个相似？

**Comment by Neutree** [comment]
嗯嗯，对的，一样的情况，

**Comment by suziwen** [comment]
网页版会有这种情况吗，chrome, firefox等浏览器，我自己这边客户端都是正常的，没法重现。

**Comment by Neutree** [comment]
网页版不会哦~~我用的chrome，桌面版才会这样，桌面使用的win10

**Comment by suziwen** [comment]
使用的是什么编辑器。 ace编辑器， codemirror编辑器, 轻量编辑器都会吗？
![image](https://cloud.githubusercontent.com/assets/57370/14823967/dd8a6aba-0c06-11e6-9a16-a6ebd83be885.png)

因为我win10下光标也是正常定位的，所以你那边最好提供一下操作系统的详细信息，当前运行了哪些软件，或者你那换一台电脑试一下呢？

**Comment by Neutree** [comment]
sorry，最近忘了看通知，我这里只是codemirror编辑器会出现这个问题，其它的编辑器没有问题的

**Comment by suziwen** [comment]
嗯，已经可以确认原因了，下个版本修复 

#183 
#174
#166
