### ISSUE TITLE
打开小书匠一直在加载中，重启也没用

### ISSUE THREAD

**Issue by RainyGrass** [suziwen/markdownxiaoshujiang#1741]
https://github.com/user-attachments/assets/b663ade9-163a-4cd6-8d0d-224077ac3850

现在加载十分钟了，还是没显示出来

**Comment by RainyGrass** [comment]
哦对了，设备是win11

**Comment by suziwen** [comment]
可以用外部的编辑器新建一个扩展名为 md 的空白文件，然后试着用小书匠关联打开,(就是双击该 md 文档)

-------------------

如果上面的方法不行，可以试着先把 数据文件位置

Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
移动到另外一个临时位置，再启动小书匠

**Comment by RainyGrass** [comment]
当我使用第二种方法，它确实能够启动了，但用户数据没有了，于是我又重新移动到原来的位置，小书匠又打不开了，是什么原因呢？

**Comment by suziwen** [comment]
那你试一下，把数据目录下的这个文件夹`storywriter/Default/Local Storage`里的文件清空，再启动小书匠，看能不能启动．（操作前先备份下数据文件夹）

**Comment by RainyGrass** [comment]
清空后确实有效，可以打开，但当我覆盖备份好的用户数据后，就又出现了相同的情况，最终，我只能决定删掉重下

**Comment by suziwen** [comment]
我的意思是再试试　删除掉 数据文件夹 `Windows: %LOCALAPPDATA%/storywriter/ ` 里的 `storywriter/Default/Local Storage` 里的文件，再启动小书匠，看能不能启动？

一般 `storywriter/Default/Local Storage` 这个文件夹保存的是一些配置文件，删除后，重启小书匠，只是重置下配置文件了，文章数据是还在的．

**Comment by RainyGrass** [comment]
哎呀，原来是这样，抱歉，没有理解您的意思，我不知道这样做是重置配置，好吧，幸好我有备份，请容许我再次尝试一下

**Comment by RainyGrass** [comment]
解决了。

**Comment by suziwen** [comment]
这个应该就是最近打开的几篇文章里，可能标题里有些不常用，或者比较特殊的符号引起的，可以自己排查下，不然下次点击这篇文章后，再启动小书匠，可能还需要再走一下上面的流程才能打开．

**Comment by RainyGrass** [comment]
好的

**Comment by RainyGrass** [comment]
也就是说文件和文章标题中不要出现特殊符号一类的对吧？

**Comment by suziwen** [comment]
嗯，如果发现的话，也可以贴出来，这样后继的版本就可以修复这种 bug 了．
