### ISSUE TITLE
win7系统下编辑器无法正常编辑

### ISSUE THREAD

**Issue by zjgtan** [suziwen/markdownxiaoshujiang#176]
win7系统下编辑器无法正常编辑，光标和文字对不上号，应该是乱码了

**Comment by suziwen** [comment]
贴个图看一下是什么效果

**Comment by zjgtan** [comment]
![baiduhi_2016-4-25_23-31-55](https://cloud.githubusercontent.com/assets/4132906/14789192/f3d20270-0b3d-11e6-8dcd-5a3bc2c843cc.png)

**Comment by zjgtan** [comment]
上面的效果应该是编码不正确导致公式也不能正常识别了

**Comment by suziwen** [comment]
我没看懂你这截图的错位是指哪的？

你这个是用 `ace编辑器`，然后自定义了编辑器的字体？现在只有ace编辑器必须是等宽字体，其他内处可以是非等宽的。

**Comment by zjgtan** [comment]
我的情况比较诡异，是输几个字符，光标就跑到后面去了，没有做什么设置

**Comment by suziwen** [comment]
客户端版本是多少？操作系统等一些参数也贴出来看下

**Comment by zjgtan** [comment]
win7 1.9.1

**Comment by suziwen** [comment]
你应该用的是 `ace编辑器`， 可以试着切换成  `codemirror编辑器`，或者 `轻量编辑器`

![image](https://cloud.githubusercontent.com/assets/57370/14805720/4b7edd0e-0b34-11e6-8efb-430536cd67c6.png)

如果一定要用 `ace编辑器` 的话， 可能是你的电脑里没有预设置的等宽字体，可以在 `设置->编辑器`  里添加字体 `monospace`

**Comment by zjgtan** [comment]
还有一个问题，目前网页版的公式majax解析也有问题，
```mathjax!
$$\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.$$
```
显示为一段代码，上面有一个照相机符号

**Comment by suziwen** [comment]
这个是你没有打开设置

系统提供两种设置方式， 一种是内置在文档元数据头的设置

`````
```
grammar_mathjax: true
```
`````

另一种是在系统设置界面上打开的，`设置>语法扩展` , 把 `mathjax公式` 打开，就可以了。

![image](https://cloud.githubusercontent.com/assets/57370/14807540/0b3269dc-0b43-11e6-810f-a2e446d44155.png)

推荐使用第一种元数据的设置方式，这样可以不用每篇文章都预先加载 mathjax库，影响其他不使用mathjax文章的预览速度。

**Comment by zjgtan** [comment]
![baiduhi_2016-4-26_20-46-56](https://cloud.githubusercontent.com/assets/4132906/14818953/6c9b9d38-0bf2-11e6-98b5-a6d20164b039.png)

**Comment by zjgtan** [comment]
这个是web版的问题

**Comment by zjgtan** [comment]
![baiduhi_2016-4-26_21-6-7](https://cloud.githubusercontent.com/assets/4132906/14819012/b778303c-0bf2-11e6-8a89-cf34919f9809.png)

**Comment by suziwen** [comment]
要显示公式的话，要打开相应的语法设置。

**Comment by zjgtan** [comment]
嗯，解决了，多谢啊！
