### ISSUE TITLE
印象笔记同步时报错

### ISSUE THREAD

**Issue by jiftle** [suziwen/markdownxiaoshujiang#177]
加载出现错误{"code":1006,"error":{"errorCode":19,"message":null,"rateLimitDuration":1788}}

**Comment by suziwen** [comment]
[API 调用频率限制](https://dev.yinxiang.com/doc/articles/rate_limits.php)

大约半个小时后就可以再操作同步了 `1788 / 60 = 29.8 分钟`

**Comment by jiftle** [comment]
谢谢，现在可以同步了。



lixugood
 
发件人： 苏滋文
发送时间： 2016-04-26 11:29
收件人： suziwen/markdownxiaoshujiang
抄送： jiftle; Author
主题： Re: [suziwen/markdownxiaoshujiang] 印象笔记同步时报错 (#177)
API 调用频率限制
大约半个小时后就可以再操作同步了 1788 / 60 = 29.8 分钟
