### ISSUE TITLE
保存时出现错误

### ISSUE THREAD

**Issue by NiuYongjie** [suziwen/markdownxiaoshujiang#181]
保存失败: {"status":500,"name":"abort","message":"unknown","reason":"QuotaExceededError"}

这个错误是什么？一直不解，好几次了。重新启动才能缓解。

**Comment by suziwen** [comment]
web版本？客户端版本？操作系统？哪个客户端？或者web版使用的是什么浏览器？

**Comment by NiuYongjie** [comment]
web版
浏览器：chrome
绑定：印象笔记

保存时遇到错误：
```
保存失败:
 {"status":500,"name":"abort","message":"unknown","reason":"QuotaExceededError"}
```

自己搜了搜，没弄明白。我注意了下：从印象笔记中读取文件，时间久一点后保存时就会报这个错误。无法保存，关掉浏览器后再次打开小书匠就会加载很长时间才到编辑界面。（清理浏览器缓存会解决加载时间久的问题，但关闭前的类容就不会保存）

**Comment by NiuYongjie** [comment]
我换了操作系统和客户端后没有再出现问题。
可能和我的浏览器和操作系统有关。
