### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by zhanghaofei** [suziwen/markdownxiaoshujiang#182]
客户端需要绑定印象笔记token，我自己电脑ubuntu系统，公司电脑win10 ，绑定的同一个token。我在公司编辑同步后，在ubuntu上却打开内容还是上次ubuntu中编辑同步时候的内容。不能获取到最新的印象笔记内容(登陆印象笔记内容确实已经刷新了)，网页版能获取最新内容
我怀疑是不是linux版之前打开过得文件再次打开没有重新云端获取

**Comment by q1042697116** [comment]
还想问个问题，为什么网页版登陆就行了，不需要token，客户端却需要

**Comment by suziwen** [comment]
客户端或者浏览器都会缓存打开过的文件，并不会实时的检测服务器是否有最新版本。
可以在第三方的文件面板上右键，`更新本地缓存` 来强制从服务器上覆盖到现在的缓存上。

网页版直接登陆第三方，其实也是一个获取token的过程，只是这个过程得经过小书匠的网站。客户端也可以做成登陆的，只是我看到他们有提供token生成，也就直接省掉了，这样的好处是不需要经过小书匠的认证也能使用印象笔记。比如小书匠的服务如果出现异常，通过登陆拿token的话，这段时间里就没法绑定。

**Comment by q1042697116** [comment]
明白了，多谢。小书匠很棒

**Comment by shuaigeadou** [comment]
我用使用是小书匠 3.0.1windows客户端版本，目录上是否也应该添加强制更新缓存的选项。因为我用印象笔记剪切完的时候，想再用小书匠编辑，但是却看不到新赠的文件。

**Comment by suziwen** [comment]
有强制刷新目录的按钮
@shuaigeadou 
![image](https://cloud.githubusercontent.com/assets/57370/25795336/7b9171de-339a-11e7-83b7-e9211a258fcf.png)

**Comment by shuaigeadou** [comment]
请问是左下角这个位置吗？我这里貌似没有啊
![image](https://cloud.githubusercontent.com/assets/20595228/25795830/ba9ad02c-3409-11e7-88b9-b297b35d25ce.png)

**Comment by suziwen** [comment]
鼠标移动到左侧面版的边界线，手动把左侧面版调宽一点就会显示出来了。
![image](https://cloud.githubusercontent.com/assets/57370/25795932/2a2f16a4-339d-11e7-8290-b3b6e23d99aa.png)

**Comment by shuaigeadou** [comment]
出来了，多谢了

**Comment by tryerrorman** [comment]
我这里win10链接印象笔记，小书匠7.3.2，点击强制刷新，文件也没有更新，需要手动删除上方本地目录里面的文件，重新打开才可以打开新文件。

**Comment by suziwen** [comment]
@tryerrorman 

这个刷新按钮是刷新印象笔记目录树结构，如果想强制更新印象笔记服务器的文章到本地，可以右键点击目录对应的文件，然后会有上下文菜单，选择更新本地缓存就可以了。也可以将小书匠本地的文章进行归档，然后再点击目录树文章时，就会自动强制使用服务器最新版本的文章了。


![image](https://user-images.githubusercontent.com/57370/58173151-2a388d80-7ccd-11e9-8b5f-9dd95e8c549d.png)
