### ISSUE TITLE
vim 模式问题

### ISSUE THREAD

**Issue by zirui** [suziwen/markdownxiaoshujiang#184]
试用了下，发现两个问题
1. ace 编辑器下，插入markdown 表格时，光标和实际输入的字符位置偏移好远
2. codemirror 编辑器，在insert模式下，按esc返回不了vim正常模式

ps. 一直在找mac下好用的markdown编辑器， 用了小书匠感觉还是有不少亮点,希望能做得更完美

**Comment by suziwen** [comment]
1. ace编辑器的话，需要自己到设置里改成等宽的字体。
2. bug

**Comment by suziwen** [comment]
新版  已经修复
