### ISSUE TITLE
软件中无法删除文件

### ISSUE THREAD

**Issue by kevin4fly** [suziwen/markdownxiaoshujiang#189]
重新步骤：
1. 打开最新版本小书匠。
2. 新建一个文件(使用本地文件系统保存文件)。
3. 在新建的文件上面点击右键。

实际结果：
点击右键没有任何反应。

期望结果：
点击右键后，出现弹出菜单，有删除选项。

使用环境：
软件版本：小书匠1.9.1
操作系统： Windows 7 Ultimate

**Comment by kevin4fly** [comment]
你好，请问小书匠这个桌面软件还会更新吗？我看到项目的描述文件中为**Deprecate**。使用过小书匠一段时间，觉得非常的不错，功能丰富，也跨平台。希望作者能够继续维护，谢谢。

**Comment by suziwen** [comment]
你说的右键是指这个区域的右键？
![image](https://cloud.githubusercontent.com/assets/57370/15452046/dbec09e0-1fa5-11e6-9119-edb0464b075d.png)
目前这个地方还没有提供右键功能。

删除文件的话，可以把鼠标移动到

![image](https://cloud.githubusercontent.com/assets/57370/15452053/ffa1b704-1fa5-11e6-97f3-bb6afb01fae9.png)

展开里有个删除的按钮。

不过目前这种方式设计不太好。

#161

**Comment by suziwen** [comment]
还会更新的

**Comment by kevin4fly** [comment]
谢谢你的回复，很高兴听到**小书匠**还会更新的消息。

我也明白你的意思了，找到了可以删除的那个按钮了。

但是还是要说明一下，文档的问题：

在**小书匠编辑器使用手册**中，**本地文件系统存储**这一节：

> ### 删除

> 右击相应的文章可进行删除操作

> ### 重命名

> 右击相应的文章可进行重命名操作

**Comment by suziwen** [comment]
这个指的是把本地文件系统当做第三方绑定的一种方式 ，在第三方目录面板上点击右键才有相关的操作。

![image](https://cloud.githubusercontent.com/assets/57370/15452223/9d25d69e-1fac-11e6-8b07-e30061484c7a.png)


目前客户端对本地的操作有两种，
一种是直接关联打开，另一种就是本地文件目录做为第三方绑定
使用手册里指的是第三方绑定里的操作。

**Comment by kevin4fly** [comment]
嗯，明白你的意思了。

最后问一下，在绑定**本地文件系统**的时候，我能知道绑定的这个文件目录吗？也就是我绑定**本地文件系统**的时候，新建的文件，文件夹储存到了哪里？以及，我可以通过设置来改变它的位置吗？

**Comment by suziwen** [comment]
目前绑定后，没有地方可以看到绑定到哪个目录的信息，暂时得自己记住。
改变绑定位置，可以取消绑定，然后再重新绑定选择新位置就可以了。

**Comment by kevin4fly** [comment]
嗯，明白了，谢谢你的回复。谢谢开发出这么优秀的作品！
