### ISSUE TITLE
在不同主机上使用小书匠，绑定的笔记需要重新设置token

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#191]

**Comment by esdream** [comment]
我的小书匠一般与印象笔记进行绑定，写的markdown笔记直接保存到印象笔记上。但我经常需要切换使用小书匠的主机，每次切换使用后都必须要重新设置token，比较麻烦。有没有解决方法？

**Comment by suziwen** [comment]
客户端的话，可以把申请到的token用在不同的客户机上(自己另外保存token)。不要重新生成token,就可以了。

**Comment by sexypig** [comment]
怎么添加token呢

**Comment by suziwen** [comment]
最新版本 5.0.0 已经发布,参数配置同步，自定义数据中心
