### ISSUE TITLE
WIN7安装启动不了

### ISSUE THREAD

**Issue by qexd** [suziwen/markdownxiaoshujiang#193]
![qq 20160530190145](https://cloud.githubusercontent.com/assets/19648338/15647923/777f7e7e-2699-11e6-9242-a61cd122c942.png)
![qq 20160530190150](https://cloud.githubusercontent.com/assets/19648338/15647926/799c9de0-2699-11e6-9935-28edc6d3347d.png)
如图所示，请看到后帮忙解决，忘了说明，win7,64位，内存16G，N卡，在笔记本上完全OK阿，台式出问题搞不明白啦~~@suziwen @suziwen

**Comment by qexd** [comment]
忘了说明，win7,64位，内存16G，N卡，在笔记本上完全OK阿，台式出问题搞不明白啦

**Comment by qexd** [comment]
@suziwen

**Comment by suziwen** [comment]
单独下载这个软件能启动吗？

http://dl.nwjs.io/v0.12.0/nwjs-v0.12.0-win-x64.zip

解压后执行里面的 nw.exe ,这个能正常执行吗？

**Comment by qexd** [comment]
![qq 20160530235703](https://cloud.githubusercontent.com/assets/19648338/15653892/7377f3b4-26c2-11e6-9702-9ed673e78ed0.png)
![qq 20160530235708](https://cloud.githubusercontent.com/assets/19648338/15653894/73b7171a-26c2-11e6-8c1b-f8f6165300f0.png)
不能，刚做的系统，完全无杂质，win7——64位，该怎么做？

**Comment by suziwen** [comment]
你的win7 是ghost的？感觉是被缩减的版本。能安装 上chrome吗？

**Comment by qexd** [comment]
![qq 20160531092634](https://cloud.githubusercontent.com/assets/19648338/15660657/cac720e6-2711-11e6-8f11-cc1222fedad9.png)
能装上，该怎么办？

**Comment by suziwen** [comment]
跟这种错误类似  https://github.com/nwjs/nw.js/issues/3494 ，但缺失的(出问题的) dll 可能不一样。

直接命令行启动会有什么错误信息。

把执行前的进程 ，执行后的进程贴个看一下。

或者试一下 32位版本的，也一样报错？

**Comment by qexd** [comment]
![qq 20160531102827](https://cloud.githubusercontent.com/assets/19648338/15662106/280577ae-2720-11e6-90a5-34403dc4b8e5.png)
安装了各种指令集还是报错，而且会无限弹窗卡死机。。。然而32位并没有什么问题，这什么鬼？

**Comment by suziwen** [comment]
一般64位的操作系统都会包含32位的dll,用来兼容32位的程序运行。估计你那64位系统里的部份64位dll不完整，而32位dll没修改过，所以就能直接运行32位的客户端了。具体哪个文件引起的就不知道了。暂时先用下32位的客户端了。

**Comment by qexd** [comment]
哦了谢谢，那我去某些安全软件找dll补上。
