### ISSUE TITLE
保存失败: InvalidStateError

### ISSUE THREAD

**Issue by timtsui** [suziwen/markdownxiaoshujiang#194]
Win7 x64 安装 64 位客户端，当前版本: 1.9.1，仅仅绑定本地文件系统，保存时右上角出现提示。

> 保存失败: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

正在写一个软件的说明书，之前仅仅是在编辑文本，没有特别的动作。
文本中有图片，之前已经插入了几十个，都是直接粘贴图片进来的，文件名没有中文。
现在的问题是，编辑到半途（已有几百行），也就是自上次正常保存以来，新添的文本一概无法保存了。
系统重启过，小书编重装过，仍然不行。
我在另一台电脑（Win10 x64）上的小书编，绑定本地文件系统，打开该文档（坚果云同步），则是大量图片附件根本无法保存。
该 bug 导致我的本项工作被迫暂停。

此外这一路上还遇到多次小书编的保存故障，错误类型不同，重启软件就能暂时排除。但这次不行了。
## updates

根据苏同学的提示，关闭小书编后尝试着把`%userprofile%/AppData/Local/小书匠/IndexedDB`移走，重启小书编，重新打开要编辑的文件，就可以正常保存了。文件系统的绑定设置依旧不变。`IndexedDB`文件夹瞬间变小。

**Comment by suziwen** [comment]
文件很多了？这篇文章里的图片多少，一般图片多大的。

看一下这个目录 ，现在这个目录占用多少空间。

`c:/Windows 7/Users/{Administrator}/AppData/Local/小书匠/IndexedDB`

**Comment by timtsui** [comment]
谢谢回复！我的本地文件系统里只有几篇文章（都是产品说明书），这一篇目前有 96 多个不大的截图（全部直接粘贴在小书编内），尺寸区间 [284B, 74.1KB]，部分可能并没有实际出现在文章中（不确定小书编对不再引用的图片附件有没有回收释放机制，估计没有）。
您说的那个索引目录总共 154MB 了。```file__0.indexeddb.leveldb``` 目录下有 80 个文件，其中 75 个文件尺寸 [1,1MB, 3.7MB]。

**Comment by timtsui** [comment]
根据苏同学的提示，关闭小书编后尝试着把```%userprofile/AppData/Local/小书匠/IndexedDB```移走，重启小书编，重新打开要编辑的文件，就可以正常保存了。文件系统的绑定设置依旧不变。```IndexedDB```文件夹瞬间变小。
