### ISSUE TITLE
PPT模式中，扩展样式怎么使用的？

### ISSUE THREAD

**Issue by dalchemist** [suziwen/markdownxiaoshujiang#197]

**Comment by dalchemist** [comment]
PPT功能用的什么软件实现的？

**Comment by dalchemist** [comment]
对片段无效

**Comment by dalchemist** [comment]
``` html
<!-- .element: class="fragment>>== grow==<<" data-fragment-index="1" -->
```
对片段无效

**Comment by suziwen** [comment]
https://github.com/hakimel/reveal.js/

在文件头加这个就可以了
![image](https://cloud.githubusercontent.com/assets/57370/15881294/6b8f348a-2cfa-11e6-8d15-a00204d5b234.png)

或者在 `设置` 里，把段代码样式语法功能打开也一样。

![image](https://cloud.githubusercontent.com/assets/57370/15881310/9b8eb732-2cfa-11e6-826b-c054ce637751.png)


示例文件忘记打开了

**Comment by dalchemist** [comment]
多谢。这么好用的工具，为什么没人推荐呢。

data-fragment-index="1" 这个是不是标识前后顺序的？

**Comment by suziwen** [comment]
``` html

<!-- .element: class="fragment grow" data-fragment-index="1" -->
1. 片段１
<!-- .element: class="fragment grow" data-fragment-index="2" -->
2. 片段２

<!-- .element: class="fragment grow" data-fragment-index="3" -->
3. 片段３

<!-- .element: class="fragment grow" data-fragment-index="4" -->
4. 片段４

<!-- .element: class="fragment grow" data-fragment-index="5 -->
5. 片段５


```

然后用鼠标点击左右控制按钮

![image](https://cloud.githubusercontent.com/assets/57370/15897901/d47910d6-2d5b-11e6-90f0-3fe213df52e3.png)

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/15897929/eefe9a84-2d5b-11e6-932d-c09408ee7772.png)

**Comment by dalchemist** [comment]
我自己研究出来了。多谢！！ 能不能增加PPT的演讲者模式，基本可以代替powerpoint了。 

超好用的工具，推荐中……。  

PS：就是图标丑了点 ：）

**Comment by suziwen** [comment]
有全屏模式，也有服务器客户端模式

![image](https://cloud.githubusercontent.com/assets/57370/15932337/dea0e186-2e20-11e6-9602-b0b932ce09ad.png)


图标自己感觉还可以，不过我不是搞设计的，估计在很长一段时间都会是这个样子了。

**Comment by dalchemist** [comment]
多谢！
一、我说的是这个功能：

> SPEAKER VIEW
There's a speaker view. It includes a timer, preview of the upcoming slide as well as your speaker notes.
Press the S key to try it out.

二、有没有考虑增加ppt 主题和ppt内部链接功能

>THEMES
reveal.js comes with a few themes built in: 
Black (default) - White - League - Sky - Beige - Simple 
Serif - Blood - Night - Moon - Solarized

 ---------  

>INTERGALACTIC INTERCONNECTIONS
You can link between slides internally, like this.

**Comment by suziwen** [comment]
现在ppt功能用的人不多，要做的话估计也会放到比较后面。
刚开始做这个ppt的时候是有考虑这个 speaker view，后来觉得系统其他很多基础功能需要开发，而ppt并不是大部分的需求，就先放着了。

**Comment by dalchemist** [comment]
嗯，可以理解。坐等功能完善……

**Comment by zwfcrazy** [comment]
新版本没有PPT使用示例了吗？语法说明里的PPT语法只有3句，完全不够用啊~

**Comment by suziwen** [comment]
@zwfcrazy 左下角帮助

![image](https://user-images.githubusercontent.com/57370/39739109-bfd9d36c-52c1-11e8-927b-d922ebe90120.png)
