### ISSUE TITLE
忽然出现的bug

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#198]
昨晚在使用的过程中，正在编辑，忽然不能用了，显示，下面接的是背景图。（不知道为啥github传不了图了，找个机会补上）

> abc_123
> _d3
> efg

刷新，等它加载完后，依旧会出现这个情况。无法使用，请尽快解决.

我的情况：
chrome 版本 50.0.2661.102 m
win7 x64 sp1

**Comment by epluguo** [comment]
图片实在传不上来，我可以用邮件或者其他联系方式给你发一下图片，控制台也有一些错误，这里不好贴上来。

我用傲游发现是能打开的，但是我当时编辑的文档格式是没保存到的，而在印象笔记中是生效的，只是小书匠拉取的是旧的。

另外，我那个文档自定义了css（之前没用过），当然自定义css本来是没问题的，但后面我在编辑文档里的代码的时候，就导致了这个问题。

一直刷新都是这样，现在完全使用不了

**Comment by epluguo** [comment]
app.js?v=1.9.2:15          Error: Fancytree assertion failed(…)
VM661 preview.js:153    Uncaught TypeError: Cannot read property 'mermaid' of null

**Comment by suziwen** [comment]
可以发到这 suziwen1#gmail.com

把自定义 css 的内容也发过来.

浏览器强制刷新呢？ `ctrl+r` 或者 `ctrl+f5`或者 `ctrl+刷新按钮`

**Comment by epluguo** [comment]
现在我把chrome的缓存清了一下就可以了，但是我那个笔记的一些数据也变回原来的样子了

**Comment by suziwen** [comment]
在 遨游 里右击一下第三方绑定的对应文件，点一下更新本地缓存

![screenshot_2016-06-11_15-06-44](https://cloud.githubusercontent.com/assets/57370/15983817/21e2341a-2fe6-11e6-991d-9799bc315bc8.png)

**Comment by suziwen** [comment]
每篇文章在本地都会有缓存，并且有历史记录，不行可以找找本地的历史记录里有没有。
![screenshot_2016-06-11_15-10-24](https://cloud.githubusercontent.com/assets/57370/15983838/a4a3ad5c-2fe6-11e6-893b-66cd776a25b0.png)
