### ISSUE TITLE
能否给evernote增加个一键同步？

### ISSUE THREAD

**Issue by xfspace** [suziwen/markdownxiaoshujiang#203]
增加个一键同步同步功能  可以避免忘了刷新本地缓存和evernote修改冲突了。
望增加。谢谢！

**Comment by suziwen** [comment]
有批量保存同步的按钮，批量从 evernote 上抓取的功能还没有。

![image](https://cloud.githubusercontent.com/assets/57370/16300445/9acfc57c-3905-11e6-84b3-6b17c87cd06b.png)

第二个图标的按钮，会计算上次未同步保存的文件，然后批量保存同步 。
