### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#205]
VXDGame_`platform`_`type`_1_`beta`_`build_number`_1_`build_id`.apk

编辑区输入上面的语句，在预览区域下划线会消失掉。如果把``去掉，下划线就回来了

**Comment by epluguo** [comment]
```
VXDGame_`platform`_`type`_1_`beta`_`build_number`_1_`build_id`.apk
```

**Comment by suziwen** [comment]
目前基础的markdown语法遵循的是 commonmark标准。

测试这个[语句](http://johnmacfarlane.net/babelmark2/?text=VXDGame_%60platform%60_%60type%60_1_%60beta%60_%60build_number%60_1_%60build_id%60.apk)

测试结果：
![image](https://cloud.githubusercontent.com/assets/57370/16300363/3a62f254-3905-11e6-818c-9ebb691261d2.png)

小书匠结果：

![image](https://cloud.githubusercontent.com/assets/57370/16300297/cfc7d1da-3904-11e6-8007-b2e7890fcaca.png)
