### ISSUE TITLE
# 建议 sequenceDiagram mermaid

### ISSUE THREAD

**Issue by iamlbccc** [suziwen/markdownxiaoshujiang#206]
``` mermaid!
sequenceDiagram
    Alice->>John: Hello John, how are you?
    activate John
    John-->>Alice: Great!
    deactivate John
```

好像不支持deactivate 和activate  关键字

**Comment by suziwen** [comment]
这个是 v6.0.0版本里的功能。目前系统使用的是 v0.5.8版本。

![image](https://cloud.githubusercontent.com/assets/57370/16362066/c47af0e8-3b69-11e6-8e27-2a83c1b79f13.png)
