### ISSUE TITLE
印象笔记的绑定 会突然失效

### ISSUE THREAD

**Issue by 253133851** [suziwen/markdownxiaoshujiang#207]
不知道什么原因,有的时候重新申请token也没用,但有的时候又是好的
难道是我换了wifi环境的问题?
望回复  多谢,产品真的很喜欢!
![加载错误](http://i4.piimg.com/567571/3ad5f95c3e3b29e7.png)

![](http://i4.piimg.com/567571/20a7a315fc0339a9.png)

**Comment by suziwen** [comment]
#165 

目前我自己测试出来的是网络的问题（通过自己改host来重现）。正常报错的话， error里是有内容的。如果印象的服务器不能正确解析，error就会空。

**Comment by 253133851** [comment]
@suziwen 
多谢回复!!
![](http://i2.piimg.com/567571/00df3ee875b3f7df.png)

有的时候也会报这个错

**Comment by suziwen** [comment]
econnreset 应该是网络被重置。这个错误也是网络问题引起的。最好网络环境不要频繁切换，或者正在保存同步时，不要切换网络。
