### ISSUE TITLE
为什么双击打开本地文件看不见图的bug还没修复?

### ISSUE THREAD

**Issue by supercsq** [suziwen/markdownxiaoshujiang#210]
绑定的本地系统 用的相对路径 其他md软件都能识别 又说这个版本修复?

**Comment by suziwen** [comment]
关联打开的话，文章是会自动找本地图片资源的。
不过有些特殊处理的就是，绝对地址资源位置和相对地址资源位置 。

- 文章里的资源路径是 `a/b/c.jpg` 这种相对地址格式的，就会按你说的这种方式显示 。

- 资源路径是 `/a/b/c.jpg` 这种绝对地址格式的， 需要在 `设置` 里配置下绝对地址的起始路径。

![image](https://cloud.githubusercontent.com/assets/57370/16943965/0afae0b2-4d64-11e6-992d-e884eef6dd44.png)


- 资源路径是 `./a/b/c.jpg` 这种地址格式的，已经被 小书匠 做为内置路径了。
- 其他方式的资源地址暂不支持

再一个需要注意的是，文章如果既是关联打开，同时这片文章又处在 `本地绑定系统里` ,绝对资源地址的计算就会换成绑定的目录，而不是设置里的全局地址了。


#214
