### ISSUE TITLE
发布到博客图片不同步

### ISSUE THREAD

**Issue by luyfuyu** [suziwen/markdownxiaoshujiang#212]
以cnblog为例，发布之后，图片无法显示。同时代码片段格式会有问题。

**Comment by suziwen** [comment]
如果是关联本地打开的文章，里面有关联的本地图片，发布的博文图片是有问题，这个算是个bug。不知道你是不是这个情况.

代码段格式可能跟你博客系统里的css主题有冲突引起的，这个只能自己调整自定义一下css。

**Comment by luyfuyu** [comment]
恩，主要就是发布博文图片丢失。
