### ISSUE TITLE
发布到blog不成功

### ISSUE THREAD

**Issue by harry3633** [suziwen/markdownxiaoshujiang#213]
为啥我发布到blog都不成功，一直显示数据准备中。
链接，用户名密码应该是没问题的，之前有版本发布正常，最近升级了就不行了。
wordpress搭建的blog

**Comment by suziwen** [comment]
只有纯文字的文章也发布不成功？

安装目录下有一个异常日志，看一下有什么相关的日志 
或者打开控制台，看有什么错误信息 

![image](https://cloud.githubusercontent.com/assets/57370/16944541/ad28c302-4d66-11e6-9152-5981693d6c27.png)

打开调试窗口

**Comment by Neo-Lu** [comment]
我发布到博客园也是同样的问题。
我调试窗口，发现找不到js文件。错误如下：
错误1：
![qq 20161101134526](https://cloud.githubusercontent.com/assets/8043218/19880598/aa03a360-a039-11e6-909c-67630e8f4b29.png)
错误2：
![qq 20161101134538](https://cloud.githubusercontent.com/assets/8043218/19880601/b43be568-a039-11e6-8339-2adaa3726013.png)

**Comment by suziwen** [comment]
@Neo-Lu  博客地址要有 `http://` 或者 `https://` 前缀

**Comment by Neo-Lu** [comment]
确实是这个问题，感谢帮助！
