### ISSUE TITLE
归档和删除问题

### ISSUE THREAD

**Issue by youxunlong** [suziwen/markdownxiaoshujiang#215]
归档和删除两者有什么区别？
误点击了“归档”，导致文件找不到了，我需要在哪里才能找回来

**Comment by suziwen** [comment]
点击这个手提箱按钮。就可以看到所有的文件 及回收站 两个标签了，找到被归档的文件，重新放进草稿中就行了。

![image](https://cloud.githubusercontent.com/assets/57370/16943658/5ff817b2-4d62-11e6-8027-448d5a2cec3d.png)


归档就是把文章从文件列表里去掉。
删除就是把文章放到垃圾箱里，并从文件列表里去掉。

目前系统重新设计了文件管理方式。
把文件列表面板想像成一个草稿箱， 然后一个归档箱，再一个回收站。

目前草稿箱和归档箱的区别就是拿第三方绑定的文章处理方式 。放在草稿箱里的文章，点击第三方绑定对应的文章，只是简单的切换 ，并不会真正从第三方绑定服务器拿。而放在归档箱里的文章，当点击第三方绑定对应的文章时，系统会比对该文章与第三方服务器文章的版本，并抓取最新版本重新自动放入草稿箱中。

再一个区别就是草稿箱是放在侧边栏的，可以直观显示，归档箱只能通过按钮进入另一个界面操作。
