### ISSUE TITLE
为什么绑定印象笔记后笔记本排序是凌乱的？

### ISSUE THREAD

**Issue by YeungChiang** [suziwen/markdownxiaoshujiang#219]
希望能够改进一下，因为我的印象笔记中笔记本是按照首字母和数字顺序排列的，但是显示到小书匠当中却没有规律地排列。

**Comment by suziwen** [comment]
目前是按照最近修改的时间排序的。

**Comment by YeungChiang** [comment]
可以让用户自己选择吗？

**Comment by ryys1122** [comment]
可以让用户选择排序方式吗？笔记太多了，用字母或者数字排序找起来比较方便。

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/22094017/ec59dc24-ddcf-11e6-80f2-009f1b7ec6bf.png)
