### ISSUE TITLE
为什么升级以后，不能同时显示编辑界面和预览页面了

### ISSUE THREAD

**Issue by kency2015** [suziwen/markdownxiaoshujiang#220]
升级成1.10版本以后，直接打开以前的笔记，就是编辑页面，预览页面不知道去哪里了，也不知道怎么打开预览页面

**Comment by kency2015** [comment]
升级成1.10版本以后，直接打开以前的笔记，就是编辑页面，预览页面不知道去哪里了，也不知道怎么打开预览页面

**Comment by suziwen** [comment]
![qq 20160729010013](https://cloud.githubusercontent.com/assets/57370/17221772/e633c830-54ba-11e6-9863-32366ec1fa72.png)

这个位置，如果没有出现按钮，调整下窗口大小，再最大化就会出现这个按钮。

**Comment by SuperChrisliu** [comment]
原来这么隐蔽  很尴尬  找了半天。。
