### ISSUE TITLE
有道云笔记PC端和手机端代码高亮显示不同

### ISSUE THREAD

**Issue by youxunlong** [suziwen/markdownxiaoshujiang#221]
下图是PC端的
![image](https://cloud.githubusercontent.com/assets/12827520/17240591/e748f85a-559e-11e6-890d-4471f76d687b.png)
下图是手机端的
![image](https://cloud.githubusercontent.com/assets/12827520/17240613/090b9f42-559f-11e6-973b-c4c884d4197c.png)
**手机端本来应该与PC端显示一样的，即背景为黑色，不清楚是小书匠的问题还是有道云笔记的问题？**
小书匠的高亮模式是下图
![image](https://cloud.githubusercontent.com/assets/12827520/17240663/6764f5fc-559f-11e6-8a52-60a15ea32407.png)

**Comment by suziwen** [comment]
web版已修复。
客户端可以用显示行号的功能临时解决。
或者window 下使用这个文件 
[youdao-base.js.zip](https://github.com/suziwen/markdownxiaoshujiang/files/390955/youdao-base.js.zip) 替换掉安装目录下的  `Story\plugins\plugins\youdao\` 下的 `youdao-base.js`

直接把 `youdao-base.js.zip` 扩展名 `zip` 去掉。
