### ISSUE TITLE
linux客户端无法绑定eveynote

### ISSUE THREAD

**Issue by sexypig** [suziwen/markdownxiaoshujiang#223]
提示绑定成功
然后点击当前绑定信息：
第三方服务: 印象笔记(yinxiang)
使用的用户: Error()

然后是：
加载出现错误{"code":1006,"error":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"119.254.30.32","port":80}}
难道跟系统用代理有关系？？？
求指教谢谢谢谢！！！！

**Comment by suziwen** [comment]
这个提示显示连接超时，检查下网络。
