### ISSUE TITLE
如何搜索印象笔记已有的文章？

### ISSUE THREAD

**Issue by QianChenglong** [suziwen/markdownxiaoshujiang#225]
您好，请问如何搜索呢？比如按tag，title，全文等？（该文档是之前用web版同步过去的）

现在搜索功能好像只能搜到编辑过的啊？

**Comment by suziwen** [comment]
这个暂时不提供直接搜索第三方绑定的内容

**Comment by suziwen** [comment]
最新版本已经提供

http://soft.xiaoshujiang.com/docs/tutorial/store/query/

http://soft.xiaoshujiang.com/blog/evernote/search_support

http://soft.xiaoshujiang.com/blog/evernote/tags_support
