### ISSUE TITLE
绑定github，直接粘贴进编辑器的图片没有保存

### ISSUE THREAD

**Issue by Dollyn** [suziwen/markdownxiaoshujiang#226]

**Comment by suziwen** [comment]
github绑定目前只做基本的文本文件保存，可以考虑本地绑定，然后自己用git命令提交到github上。

**Comment by Dollyn** [comment]
然而本地绑定文件夹，粘贴的时候依然不能自动保存图片文件：
![image](https://cloud.githubusercontent.com/assets/184413/17939703/621a1392-6a5e-11e6-8185-6118aa60fd7e.png)
![image](https://cloud.githubusercontent.com/assets/184413/17939725/7d4c2e2a-6a5e-11e6-866f-fe1cdd282293.png)

**Comment by suziwen** [comment]
点击保存后，就会把相关的图片都保存到 images文件夹里了。以后会再调整每次从剪切版粘贴的图片直接保存到相关位置，而不是现在点击保存后再一次性的全部保存相关附件。
