### ISSUE TITLE
已是最新版仍然提示升级

### ISSUE THREAD

**Issue by VDerGoW** [suziwen/markdownxiaoshujiang#229]
刚下载安装的最新版小书匠，启动后仍然有升级提示，并且版本号与已安装版本相同。

> **升级提示内容**
> 当前版本: 1.10.0
> 服务器最新版本: 1.10.0 升级

安装环境

+ 版本：v1.10.0
+ 系统：Windows 10 专业版64位

**Comment by suziwen** [comment]
嗯，这个版本的提示是有些问题，不过点那个 "知道了" 就不会再提示这个版本的信息了。

**Comment by VDerGoW** [comment]
你们都不关闭issue吗

**Comment by suziwen** [comment]
一般都是下一个大版本时，再统一关闭的。你觉得已经解决了也可以自己关闭的。
