### ISSUE TITLE
bug报告：每次进入后，全屏乱码

### ISSUE THREAD

**Issue by dalchemist** [suziwen/markdownxiaoshujiang#230]
![image 1](https://cloud.githubusercontent.com/assets/19801695/18026327/4fb8b0aa-6c75-11e6-8011-710dbfd8d0b7.png)

**Comment by suziwen** [comment]
最近修改的那篇文章估计有可执行的javascript脚本？
试着本地关联打开一篇新的markdown文章

**Comment by dalchemist** [comment]
没有 1.10版本稳定，这个版本预览框经常假死或者不能点击。



dalchemist@163.com
 
发件人： 苏滋文
发送时间： 2016-12-25 15:10
收件人： suziwen/markdownxiaoshujiang
抄送： dalchemist; Author
主题： Re: [suziwen/markdownxiaoshujiang] bug报告：每次进入后，全屏乱码 (#230)
Closed #230.

**Comment by suziwen** [comment]
当前文章使用了哪些语法？
当前文章使用了哪些第三方绑定？
是否是关联打开的文章？
操作系统？
客户端版本还是 web版本？
我这边没有重现你说的问题，能否发一篇出现问题（预览框假死或者不能点击）时的文章到 suziwen1@gmail.com ？

**Comment by dalchemist** [comment]
当前文章使用了哪些语法？
-- 目录、标题（1-3级）、加粗、图片、引用、列表
当前文章使用了哪些第三方绑定？
-- 我是本地使用，绑定到本地文件系统的。最喜欢直接复制图片的功能……
是否是关联打开的文章？
-- 关联打开文件什么意思？是指草稿箱的关联吗？ 我很少使用草稿箱功能，一般直接打开源文件编辑。（我觉得如果是绑定本地文件系统，草稿功能有点鸡肋，绑定网络服务倒是很好。）
操作系统？
--win7、win10
客户端版本还是 web版本？
--客户端，因为办公环境没有外网，所以都是使用客户端
我这边没有重现你说的问题，能否发一篇出现问题（预览框假死或者不能点击）时的文章到 suziwen1@gmail.com ？
-- 目前我的感觉和文件没有关系，假死后，重启程序可以恢复正常功能。我再试试能不能找出一些规律。

另外：我有一点个人感觉，希望你别介意。软件功能超强大，但总感觉过于“重”，缺少一点灵动和稳定，您是否考虑过这个软件的核心功能是什么？给我的第一感觉不像一个成熟的产品。



dalchemist@163.com
 
发件人： 苏滋文
发送时间： 2016-12-30 14:01
收件人： suziwen/markdownxiaoshujiang
抄送： dalchemist; Author
主题： Re: [suziwen/markdownxiaoshujiang] bug报告：每次进入后，全屏乱码 (#230)
当前文章使用了哪些语法？
当前文章使用了哪些第三方绑定？
是否是关联打开的文章？
操作系统？
客户端版本还是 web版本？
我这边没有重现你说的问题，能否发一篇出现问题（预览框假死或者不能点击）时的文章到 suziwen1@gmail.com ？

**Comment by suziwen** [comment]
关联打开就是没有使用什么本地绑定存储，只是直接用小书匠打开本地操作系统里的 markdown 文件。
草稿还是需要的，仅仅本地绑定是没办法提供历史记录，全文搜索这些功能的。
这个现在有点朝 ide 方向去设计了，写作ide，日记ide或者文档ide，单一的特点不会有太大的竞争力。
