### ISSUE TITLE
Linux版每次从其他界面切换回小书匠都会自动删除光标所在位置的前一个字符

### ISSUE THREAD

**Issue by VDerGoW** [suziwen/markdownxiaoshujiang#231]
Linux版每次从其他界面切换回小书匠都会**自动删除**光标所在位置的前一个字符，如果光标在空行，则会删除当前行。

> 系统：LinuxMint 18.0 Xfce 64bit
> 内核：4.4.0

**Comment by suziwen** [comment]
什么桌面环境，gnome2, gnome3, kde?
小书匠里的编辑器用的是什么,codemirror, ace, 轻量编辑器？

**Comment by VDerGoW** [comment]
桌面环境是Xfce，编辑器用的ace，我在另一台linux电脑上测试了以下，桌面环境是Cinnamon，小书匠使用相同的配置，没有出现这个问题，可能是桌面环境的问题，目前找不到其他Linux电脑测试了。

早晨又试了一下，拉伸窗口大小偶尔也会导致这种情况发生，这时候光标会停止闪烁，点击一下编辑器界面，会自动删除光标前一个符号。

系统首次登录时启动小书匠，切换时会删除光标前一个字符;
注销用户重新登录再启动小书匠，切换时会删除光标前两个字符;
再注销重新登录启动小书匠，切换时会删除光标前一个字符;
......

删除一个或两个字符这种情况循环交替发生

**Comment by suziwen** [comment]
切换到 codemirror  编辑器后，会出现你说的这种情况吗？

**Comment by VDerGoW** [comment]
没出现，只有ace编辑器会出现，其他几个编辑器都没问题。

**Comment by suziwen** [comment]
在小书匠 web版本下(chrome, firefox等)的ace编辑器， 切换标签或者切换程序后也会自动删除？
用了什么输入法。
我这边的xfce桌面环境没法重现你说的问题。

**Comment by VDerGoW** [comment]
抱歉这两天没看邮件，同样的编辑器在其他系统上没问题，用的fcitx pinyin，没法重现的话可能我遇到的问题出在系统环境上，电脑太老了
