### ISSUE TITLE
是否能增加代理

### ISSUE THREAD

**Issue by chinaShawn** [suziwen/markdownxiaoshujiang#234]
在内网需要绑定到github等地方时，没有代理，无法绑定成功，能否在小书匠离线版里添加一个代理的设置。

**Comment by chinaShawn** [comment]
现在很多公司都是搭建的自己的内网，没有代理，无法访问外网，想要增大普及度，这个很重要啊

**Comment by suziwen** [comment]
6.7.0 版本已经提供代理设置功能

http://soft.xiaoshujiang.com/download.html
