### ISSUE TITLE
[bug report] ==** 文本 **==问题

### ISSUE THREAD

**Issue by CastellanLiu** [suziwen/markdownxiaoshujiang#237]
对文本使用 ==\*\*文本\*\*==时，如果后面不加空格直接跟其他文本，将会导致所有文本显示==文本==格式，加空格再加其他文本时正常。请修复

**Comment by suziwen** [comment]
这个暂认定不是bug, 两种语法嵌套使用 markdown也没有统一的标准，就暂时按照原插件作者的功能实现了。
