### ISSUE TITLE
1：导出不居中，而且比较难看。2：预览老是显示一个照相机

### ISSUE THREAD

**Issue by lilerong** [suziwen/markdownxiaoshujiang#239]
您好！小书匠做的很好，但是体验下来感觉有下面两个问题
1：预览区总是显示个照相机的玩意，没那个地方可以去掉
2：导出任何文件，不居中还很宽很大，而且挺难看的。

**Comment by suziwen** [comment]
1. 这个照相机只是在实时预览时有的，导出或者保存到第三方存储时，是不会有这个图标的。这个相机的功能就是把代码片段转换成 png 图片。下一个版本还会提供预览区 代码片段折叠，代码片段下载等功能的。
2. 不居中是指什么？图片 ？ 可以在图片上下各空一行，就会居中了。系统会把该图片当成块图片，而不是行图片。

**Comment by lilerong** [comment]
好的，我明白了，非常感谢您百忙之中回复我，谢谢。



lilerong163@163.com
 
发件人： 苏滋文
发送时间： 2016-09-26 00:03
收件人： suziwen/markdownxiaoshujiang
抄送： lilerong; Author
主题： Re: [suziwen/markdownxiaoshujiang] 1：导出不居中，而且比较难看。2：预览老是显示一个照相机 (#239)
这个照相机只是在实时预览时有的，导出或者保存到第三方存储时，是不会有这个图标的。这个相机的功能就是把代码片段转换成 png 图片。下一个版本还会提供预览区 代码片段折叠，代码片段下载等功能的。
不居中是指什么？图片 ？ 可以在图片上下各空一行，就会居中了。系统会把该图片当成块图片，而不是行图片。
