### ISSUE TITLE
似乎新建md后只能默认模板，希望能自定义模板

### ISSUE THREAD

**Issue by LakeVilladom** [suziwen/markdownxiaoshujiang#240]

**Comment by ShaoJianbo** [comment]
利用CSS自定义模板个时候，会出现无法保存到evernote的情况

**Comment by suziwen** [comment]
`设置》基本`里可以自定义模板的，修改后直接点击确定保存，下次创建新的文章时就会使用新的模板了。

**Comment by suziwen** [comment]
@ShaoJianbo 无法保存到evernote时，有什么错误提示吗？能把自己定义的css模板贴个看下吗？

**Comment by YueCongPKU** [comment]
evernote 7.5.2 无法自定义模板。点击选项(右上角三个点)后，没有“保存模板”选线
