### ISSUE TITLE
最新win10总是开启失败

### ISSUE THREAD

**Issue by Li-albert** [suziwen/markdownxiaoshujiang#241]
升级到win10的周年更新后，每次打开都报错，请问该如何解决

**Comment by dalchemist** [comment]
我的也是win10没发现这个问题。我觉得不是操作系统的问题。

**Comment by suziwen** [comment]
贴个报错的信息看下。我这边的win10能正常打开

**Comment by Li-albert** [comment]
启动之后直接停止工作了
![image](https://cloud.githubusercontent.com/assets/15010914/18943294/3fc4915a-8651-11e6-9743-b98ff20222d8.png)

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v2.1.0

**Comment by dalchemist** [comment]
建议放到百度云盘上，github的下载速度太慢了。



dalchemist@163.com
 
发件人： 苏滋文
发送时间： 2017-04-10 09:41
收件人： suziwen/markdownxiaoshujiang
抄送： dalchemist; Comment
主题： Re: [suziwen/markdownxiaoshujiang] 最新win10总是开启失败 (#241)
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v2.1.0
―
