### ISSUE TITLE
表格里面文本没法居中

### ISSUE THREAD

**Issue by 812865052** [suziwen/markdownxiaoshujiang#243]
table {
  padding: 0;
  border-collapse: collapse;
  border-spacing: 0;
  font-size: 1em;
  font: inherit;
  border: 0;
  margin: 0 auto;
}

tbody {
  margin: 0;
  padding: 0;
  border: 0;
  text-align:center;
  /*vertical-align:bottom;*/
  color:#D81B60;
}

设置自定义的css
table tr {
  border: 0;
  border-top: 1px solid #CCC;
  background-color: white;
  margin: 0;
  padding: 0;
}

table tr:nth-child(2n) {
  background-color: #F8F8F8;
}

table tr th, table tr td {
  font-size: 16px;
  border: 1px solid #CCC;
  margin: 0;
  padding: 5px 10px;
}

table tr th {
  font-weight: bold;
  color: #eee;
  border: 1px solid #009688;
  background-color: #009688;
}

文本还是没法居中
![image](https://cloud.githubusercontent.com/assets/12646048/18698072/bb1787e4-7ff9-11e6-94a6-d3f53e38cde0.png)

**Comment by suziwen** [comment]
```
.table tbody tr td {
text-align: right;
}
```

系统默认的css覆盖了你的 tbody css 定义，所有没有生效。自定义css的话，最好通过查看生成的html结构。

也可以用 markdown 居中的table语法 `:-:`

```
| 1  | 2 | aaa |     |
| --- | :-: | --- | --- |
|     |     | aaa |     |
|     | aaa| aaa |     |
|     |     |     |     |
```
