### ISSUE TITLE
Github绑定无错误信息

### ISSUE THREAD

**Issue by ZephyrJung** [suziwen/markdownxiaoshujiang#244]
无法绑定，右上角弹出红色提示框，但没有信息，不知道原因

**Comment by suziwen** [comment]
确认下那边的网络能否访问github

还有就是token是否正确，
再一个就是 填写的信息是不一致


![image](https://cloud.githubusercontent.com/assets/57370/18816761/70ebba86-8315-11e6-9ef4-99fe979b10b6.png)

**Comment by ZephyrJung** [comment]
这些都没问题的

**Comment by suziwen** [comment]
web版能正常绑定github吗？

**Comment by ZephyrJung** [comment]
额，我应该就是在web版上做的
主要是没有对应错误提示不知到哪儿出了问题。
已经按照说明上的要求做了呢

**Comment by suziwen** [comment]
能把你的 token, 仓库名称， 对应分支发到邮箱 suziwen1@gmail.com 吗。我看一下。

**Comment by ZephyrJung** [comment]
暂时没法发，请稍等一段时间，我下了一下那个客户端，试试后再跟你反馈。
