### ISSUE TITLE
ubuntu 客户端无法输入中文

### ISSUE THREAD

**Issue by wowforestwow** [suziwen/markdownxiaoshujiang#245]
中文输入问题怎么解决
package版本怎么使用？

**Comment by suziwen** [comment]
ubuntu版本，使用的是什么桌面系统,kde,gnome3,gnome2或者其他？输入法是什么。
小书匠客户端版本？使用什么编辑器 ace, codemirror,或者轻量编辑器。这三个都切换下看。
我这边ubuntu运行没发现不能输入中文的情况。
