### ISSUE TITLE
pc客户端绑定有道云笔记 弹出空白窗口 只有我一个人是这样么

### ISSUE THREAD

**Issue by 812865052** [suziwen/markdownxiaoshujiang#246]
![xiaoshujiang](https://cloud.githubusercontent.com/assets/12646048/18820076/e0bea096-83cc-11e6-92bb-c8244d22bab5.gif)

**Comment by suziwen** [comment]
应该是你的网络限制访问有道的网站了。
看看是否360等防火墙是否限制了小书匠访问外网？
