### ISSUE TITLE
PC版小书匠支持mactype渲染么？

### ISSUE THREAD

**Issue by CrazyMelody** [suziwen/markdownxiaoshujiang#247]
浏览器用了mactype加微软雅黑字体，所以看着比较舒服，但是PC版字体看着很虚，看着很不舒服，请问可以调节软件的字体么？我试了设置---基本中的字体，但是好像没用？

**Comment by suziwen** [comment]
#111

**Comment by Mrcxt** [comment]
pc版在哪下载呀

**Comment by suziwen** [comment]
@Mrcxt  http://soft.xiaoshujiang.com
