### ISSUE TITLE
保存失败，服务器错误 code 1009

### ISSUE THREAD

**Issue by CrazyMelody** [suziwen/markdownxiaoshujiang#248]
保存失败: {"code":1009,"error":"服务器错误","orign":{"code":502,"message":"XML-RPC fault: Failed to parse XML-RPC request: Failed to parse date value 0NaNNaNNaNTNaN:NaN:NaN at position 1"}}

经常会碰到这个问题

**Comment by suziwen** [comment]
这个是绑定到哪个存储保存时的提示？

**Comment by CrazyMelody** [comment]
为知笔记,另外我同步到为知的笔记, [TOC]目录的链接有问题,在客户端点没反应,web端点显示无效链接

**Comment by suziwen** [comment]
"code":502," 的错误我这边没重现过。像是到为知服务器的网络不稳定，或者为知的服务器没有及时处理返回 http 502错误。你那文章内容很多？

除了用为知原生的markdown来解析， toc和脚注才可以正常使用。不然为知提供的其他文章都没办法创建文章内部跳转。小书匠目前是把本地的markdown解析成html片段,然后提交保存到为知笔记，提交后为知就把所有非法的 url链接添加 `http://` 前缀，导致跳转失效。
