### ISSUE TITLE
保存失败: 服务器错误（错误码：1009）

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#249]
小书匠1.10.0版本，网络图片不能正常保存。
使用之前版本创建的笔记，保存到为知笔记服务器。在创建的笔记中含有网络图片，书写格式如下：

```
1.![Node与浏览器、W3C组织、CommonJS组织、ECMAScript组织之间关系](http://www.wanwuke.com/wp-content/uploads/2016/01/commonJS.jpg)
```

之前版本能够正常保存。从某一版本后，会产生以下错误。

```
保存失败: {"code":1009,"error":"服务器错误","orign":{"code":502,"message":"XML-RPC fault: Failed to parse XML-RPC request: Failed to parse date value 0NaNNaNNaNTNaN:NaN:NaN at position 1"}}
```

经测试，去除图片后，笔记可以正常保存。

**Comment by suziwen** [comment]
用你的这段在1.10.0上测试了下，能够正常保存。没法重现你说的错误。

```
1.![Node与浏览器、W3C组织、CommonJS组织、ECMAScript组织之间关系](http://www.wanwuke.com/wp-content/uploads/2016/01/commonJS.jpg)
```

保存失败时，试着再保存几次，还是固定会重现？

#248

**Comment by esdream** [comment]
在新创建的md文件中可以正常保存该文件。
我已将出现问题的md笔记文件上传至我的github中。
[https://github.com/esdream/Bug.git](url)
另附保存出现错误时调试窗口打印的错误信息。
![error](https://cloud.githubusercontent.com/assets/14349603/19503347/9565254a-95e5-11e6-959a-0a486cd04808.PNG)

**Comment by esdream** [comment]
@suziwen

**Comment by suziwen** [comment]
用你给的这个文件，我这边还是可以保存到 为知笔记 上。没法重现你说的错误。

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/19594939/1750017a-974d-11e6-9b1c-15c0093f06c8.png)

![image](https://cloud.githubusercontent.com/assets/57370/19594978/50bfea24-974d-11e6-946c-404f5effaa35.png)

**Comment by esdream** [comment]
尝试将该笔记内所有内容复制至另一文件中进行保存，保存成功。
似乎是一个不可在其他文件中内重现的错误。
感谢作者的回答。

**Comment by esdream** [comment]
请问下如何设置Tab键空格个数为4个？目前新版Tab默认为2个空格

**Comment by suziwen** [comment]
这个现在没办法设置，下个版本再提供选项
