### ISSUE TITLE
小书匠web版功能

### ISSUE THREAD

**Issue by 46556489** [suziwen/markdownxiaoshujiang#250]
小书匠web版不能复制剪贴板的图片，只能插入来自文件的图片

**Comment by suziwen** [comment]
可以复制剪贴板图片，无法重现你说的情况。
浏览器版本，操作系统？

**Comment by 46556489** [comment]
操作系统是win7 64位，浏览器是
而且还有两个新问题，win7 64位的客户端，更新到1.10.0后，每次切换文件，会报这个错误
同时，粘贴剪贴板的图片到编辑器，右侧的预览区没有显示该图片（前两天因为这个问题卸载之后又重装过）



YZ_DLUT@163.com
 
发件人： 苏滋文
发送时间： 2016-10-06 13:45
收件人： suziwen/markdownxiaoshujiang
抄送： 46556489; Author
主题： Re: [suziwen/markdownxiaoshujiang] 小书匠web版功能 (#250)
可以复制剪贴板图片，无法重现你说的情况。
浏览器版本，操作系统？

**Comment by suziwen** [comment]
浏览器版本？
报什么错？
好像用邮件发的回复看不到你的截图

**Comment by 46556489** [comment]
firefox的最新版

**Comment by suziwen** [comment]
firefox 暂不支持，目前这个功能只支持chrome

**Comment by suziwen** [comment]
不出意外的话， firefox 应该在50版本后就会实现跟chrome 一样的粘贴行为。
https://bugzilla.mozilla.org/show_bug.cgi?id=906420

先把收集到的 hackfix 资料放在这里了

http://joelb.me/blog/2011/code-snippet-accessing-clipboard-images-with-javascript/

https://meta.discourse.org/t/ability-to-paste-an-image-into-the-compose-form/1582

https://github.com/discourse/discourse/commit/c8c150dfbee938a1182794594bcd7c2584387f41#diff-12b9a3ebd5adbc517b0a8de655b4fc93

https://ruby-china.org/topics/17266

**Comment by suziwen** [comment]
最新版的 firefox 已经可以用了
