### ISSUE TITLE
希望搜索功能加强，我可以直接搜过所有文章里的某个关键字；

### ISSUE THREAD

**Issue by wodish** [suziwen/markdownxiaoshujiang#253]

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/19213186/0e15bf1e-8d2a-11e6-9219-ba03d3011ef1.png)

点小箱子，然后

![image](https://cloud.githubusercontent.com/assets/57370/19213187/25c278be-8d2a-11e6-9117-203b12cccaf1.png)
