### ISSUE TITLE
建议：添加账号，同步设置

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#255]
建议添加账号登录，登录完后自动同步之前的设置。有多台电脑，每次都设置一遍好麻烦，而且有时候重装个浏览器或者使用新的电脑，那些配置又得重新配置。
关键是，有些地方我用的是自定义的css，换了个新的环境，我就捉急了....

**Comment by Yuuuu9658** [comment]
赞同，哪怕是把需要的配置文件绑定到自己的服务器或者自定义网盘也可以

**Comment by wuyaoyao511** [comment]
太赞同了。小书匠是我用的最好用的markdown编辑器了，就是每次设置太麻烦。最好能出个软件安装在电脑上和QQ一样。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经发布，支持参数同步，自定义数据中心
