### ISSUE TITLE
标题里面有<>的问题

### ISSUE THREAD

**Issue by epluguo** [suziwen/markdownxiaoshujiang#256]
如下，注意title那里，有个<>，结果在标题里面，这里面的内容包括<>都不显示了。我把`包起来，标题里面就多了`。
想知道这是哪里的语法？我怎么才能在标题上面显示<>及里面的内容？
---

title: C#基础：委托之Action<T>和Func<T>的用法
tags: 新建,模板,小书匠
grammar_cjkRuby: true
## grammar_html: false

![image](https://cloud.githubusercontent.com/assets/6416516/19638007/6e3d8dc2-9a04-11e6-9105-89c5f92d6799.png)

**Comment by epluguo** [comment]
C#基础：委托之Action<T>和Func<T>的用法

**Comment by epluguo** [comment]
github也对这个尖括号做了处理了。。
![image](https://cloud.githubusercontent.com/assets/6416516/19638092/d3109f50-9a04-11e6-9881-e2d5815fae42.png)

**Comment by epluguo** [comment]
我知道了。。。
尖括号应该是被识别为html了。
能不能提供一种方式，关闭标题的解析？
另外，下面不是有 grammar_html: false 这个选项吗，怎么标题的尖括号还被解析？

**Comment by suziwen** [comment]
元数据里的内容是和正文里的 markdown 分开解析的，所以 grammar_html 对元数据里的内容无效。 直接把 `<T>` 当 html 标签处理了，下个版本修复。

**Comment by suziwen** [comment]
1.11.0 版本已经禁用元数据里的 html 标签
