### ISSUE TITLE
windows版，左边导航操作不便，不能删除引入的本地文件

### ISSUE THREAD

**Issue by KerwinW** [suziwen/markdownxiaoshujiang#257]
操作系统：windows7（64位）
小书匠：1.10.0
之前用小书匠打开过本地 .md 文件，打开历史一直留在小书匠左边导航中，鼠标移上去只有【归档】和【删除】按钮，但仅对小书匠存储文件有效，对本地文件无效，甚至无法将历史从列表中删除，右键鼠标也没有任何可操作项
![qq 20161025111530](https://cloud.githubusercontent.com/assets/17998861/19671854/5e794390-9aa4-11e6-92de-a941d4aa404f.png)

建议：至少增加一个能从历史列表中删除记录的功能

**Comment by ehlxr** [comment]
+1 也发现这个苦恼了

**Comment by suziwen** [comment]
操作系统什么版本？所有关联的文件都不能正确删除？
用其他编辑器新建一个markdown文件，然后用小书匠关联打开，左侧的文件列表里那个新关联的文件也不能删除？

**Comment by KerwinW** [comment]
先说下左边导航历史记录的问题
开始装的是小书匠1.9，存在不能删除本地文件历史记录的bug，所以更新到1.10，还是不能删除，后重启过软件和系统，现在用了几天，没有再出现以上bug，
ps：可能和我绑定过本地文件作为存储有关？我已经取消本地文件存储绑定了，使用小书匠自带的存储

现在出现另一个问题，我每天用小书匠1.10记录工作日报，但是内容写多以后（比如昨天的日报，其实也没多长），就会出现比较严重的编辑延时，卡顿很严重，前天的日报也是，内容变长就渐渐出现这个现象

**Comment by KerwinW** [comment]
先说下左边导航历史记录的问题
开始装的是小书匠1.9，存在不能删除本地文件历史记录的bug，所以更新到1.10，还是不能删除，后重启过软件和系统，现在用了几天，没有再出现以上bug，
ps：可能和我绑定过本地文件作为存储有关？我已经取消本地文件存储绑定了，使用小书匠自带的存储

现在出现另一个问题，我每天用小书匠1.10记录工作日报，但是内容写多以后（比如昨天的日报，其实也没多长），就会出现比较严重的编辑延时，卡顿很严重，前天的日报也是，内容变长就渐渐出现这个现象

**Comment by suziwen** [comment]
现在 1.10 用的什么内置编辑器， ace, codemirror, 轻量 ？

**Comment by KerwinW** [comment]
codemirror

**Comment by suziwen** [comment]
卡顿是预览慢，还是整个小书匠系统其他地方都没法点？文章大概多少字？卡顿时，点击其他文章，再切换这篇变慢的文章，也会卡顿？

**Comment by KerwinW** [comment]
1、卡顿慢是指，比如打字，或者按退格键删除，要一两秒才显示，其他地方能不能点没试过，文章切换会不会卡顿也没试过
2、文章内容不长，35行左右，算上空格550个字左右，包含5个##标题，和若干>注释

ps：刚才又试了一下昨天的日报，没出现打字卡顿的现象（= = 一脸懵逼）
pps：但是我开了预览区域同步滚动，卡了3秒所有，打字没问题，滚动延时，且无法切换其他文章，之后就好了，
ppps：难道要每天下午才出现打字卡（= =），我下午注意一下具体表现。
