### ISSUE TITLE
与sogou五笔不兼容？

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#258]
用的最新版本。
很奇怪，昨天打开小书匠切换到搜狗五笔输入法遇到 nw.exe 不响应，其他输入法就没问题。后来重装了小书匠之后就正常了。但是今天又遇到了不响应的问题。

PS:我在另一台电脑就没遇到过。。。。。。

**Comment by suziwen** [comment]
我这边也没法重现你说的情况

**Comment by leongfeng** [comment]
这问题出现了三回，后来重启了之后到现在再也没遇到过。。。
