### ISSUE TITLE
几点建议，有关编辑区域滚动范围、自定义样式和同步滚动

### ISSUE THREAD

**Issue by KerwinW** [suziwen/markdownxiaoshujiang#259]
操作系统：windows7 （64位）
小书匠：1.10.0

以下意见属个人意见，如有不妥请无视

1、编辑区域内容的底边直接贴近编辑区底部，无多余空白，视觉一直在屏幕底部，建议增加空白可滚动区域（类似sublime），可以把编辑区最后的内容滚动到屏幕中间
![1](https://cloud.githubusercontent.com/assets/17998861/19672151/b7361182-9aa6-11e6-9f0f-e09a3b24b236.png)

2、我想改变文字颜色，只能通过自定义样式，但是添加后会导致整行（整块）都变成指定样式，不能仅对行内部分文字进行操作，除非加上 *\* 文字 *\* 加粗，把样式限定在内，感觉有点麻烦，我刚开始用小书匠，不知道有没有别的解决办法
![2](https://cloud.githubusercontent.com/assets/17998861/19672278/94c18fea-9aa7-11e6-9c03-66bb5f9509c3.png)

**Comment by suziwen** [comment]
1. 后继再改进下
2. 想对部份文字加样式的话，还是用 html 标签比较容易控制些，打开 `grammar_html` , 然后想改变样式的地方用 `<span class="red">红色</span>` ,然后自定义 css 里， `.red{color: red;}`

**Comment by suziwen** [comment]
1.11.0 版本， `设置>编辑器` 里的 scrollPastEnd 选上
