### ISSUE TITLE
请问绑定存储后何时同步？

### ISSUE THREAD

**Issue by xisang233** [suziwen/markdownxiaoshujiang#262]
我现在把小书匠绑定到了自己的github空间，但是并没有看到空间里面有什么文件。
请问在什么时候会同步呢？在另一台设备输入相同的token和空间名之后是否会自动按时下载呢？

谢谢

**Comment by suziwen** [comment]
具体可以看使用手册，里面有详细说明怎么用。
绑定后，还得选择一下，就是右上角要打上勾。

![image](https://cloud.githubusercontent.com/assets/57370/19853293/4c66b872-9f36-11e6-93df-66d157cd6517.png)

不会自动下载，要自己主动去拉取第三方的数据，然后本地缓存。下次再点击时，如果缓存里有文件，就直接拿缓存里的内容，没有的话，才拿第三方服务器的文件。选择了某个绑定，点击保存时，就会同步到第三方服务器里，如果没有选择绑定，就仅仅保存在本地数据库里。
