### ISSUE TITLE
未找到换肤功能

### ISSUE THREAD

**Issue by xiaoyiyibaibai** [suziwen/markdownxiaoshujiang#263]
换肤功能。默认的皮肤太模糊。

**Comment by tony199555** [comment]
开发者都弃疗了 去看看有没有fork的吧

**Comment by suziwen** [comment]
@xiaoyiyibaibai 

编辑区左边的按钮里
![image](https://cloud.githubusercontent.com/assets/57370/20003399/44d694a8-a254-11e6-92e0-0b465dbd1d45.png)

![image](https://cloud.githubusercontent.com/assets/57370/20003421/6018e81a-a254-11e6-9097-fa0301e9d568.png)

现在的系统默认的编辑器打开了`行专注`功能 ， 可以在 `设置-》编辑器->codemirror` 里把 `行专注`选项去掉。

**Comment by suziwen** [comment]
@tony199555 只是开源的版本不再提供维护。 http://soft.xiaoshujiang.com 上的客户端版本，及 在线 web 版本 http://markdown.xiaoshujiang.com 还是有维护的。使用中有问题或者建议，可以在这里提交。
