### ISSUE TITLE
请问：如何自定义主题颜色？

### ISSUE THREAD

**Issue by dalchemist** [suziwen/markdownxiaoshujiang#264]

**Comment by suziwen** [comment]
web 版  和 linux 版 目前只能通过切换主题按钮来修改主题。参考这个 #263 
window版除了可以通过切换按钮换不同主题，还可以到安装目录下自己修改这几个文件， `安装目录/css/` 和 `安装目录/js/ace/theme-*.js`

**Comment by dalchemist** [comment]
请问一下，nwjc.exe是干什么用的？



dalchemist@163.com
 
发件人： 苏滋文
发送时间： 2016-11-06 23:56
收件人： suziwen/markdownxiaoshujiang
抄送： dalchemist; Author
主题： Re: [suziwen/markdownxiaoshujiang] 请问：如何自定义主题颜色？ (#264)
web 版 和 linux 版 目前只能通过切换主题按钮来修改主题。参考这个 #263 
window版除了可以通过切换按钮换不同主题，还可以到安装目录下自己修改这几个文件， 安装目录/css/ 和 安装目录/js/ace/theme-*.js

**Comment by suziwen** [comment]
把 javascript 文件转换成二进制形式，用来保护 javascript 源文件不被查看。对于一般用户没有什么用。
打包的时候偷懒，把一些开发用的工具也跟着打包进去 。
