### ISSUE TITLE
导出html文件的bug

### ISSUE THREAD

**Issue by Shing952** [suziwen/markdownxiaoshujiang#268]
导出html文件是代码块出现问题,如图片:
![qq 20161117000225](https://cloud.githubusercontent.com/assets/23016067/20354526/6e5acdc6-ac59-11e6-80e5-d66df66dd677.png)

**Comment by suziwen** [comment]
估计是代码块里的内容有问题，新建一篇文章，单独只有这个代码块，然后导出 html,也会出这种情况？
有对应代码块的内容没？
发一份到邮件 suziwen1@gmail.com
