### ISSUE TITLE
小书匠与为知笔记连接缓慢

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#272]
小书匠在与为知笔记绑定、获取笔记列表、读取笔记、保存笔记等过程非常缓慢，且极易出错。而使用印象笔记时小书匠与印象笔记的连接十分流畅，体验非常好，这是什么原因导致的？

**Comment by suziwen** [comment]
小书匠客户端都是直接连接为知笔记的，没有数据需要经过小书匠服务器的
这边通过小书匠客户端测试了下，感觉像是为知的服务器问题。有时返回的速度很慢（白天），有时又比较快（晚上比较多这种情况）。

先再观察一段时间了。
