### ISSUE TITLE
新文件保存github时路径名称比较奇怪

### ISSUE THREAD

**Issue by xisang233** [suziwen/markdownxiaoshujiang#274]
![image](https://cloud.githubusercontent.com/assets/18749991/20648337/e72dc504-b4de-11e6-8357-952cc42097e2.png)
windows客户端 这样输报错...
![image](https://cloud.githubusercontent.com/assets/18749991/20648342/fe91de9c-b4de-11e6-9c3a-0b8481a1bccf.png)
需要输成这样...

好别扭

**Comment by suziwen** [comment]
新版 v1.12.0 已经修复
