### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zv1994** [suziwen/markdownxiaoshujiang#275]
首先我很喜欢你们的这个软件 就是不知道你们以后会不会收费 ；
其次希望你们能够出一个os版本的 平时需要用手子码字 ；
还有就是我本人是一个网络小说作者 不知道对付万字以上会不会出现崩溃和卡顿；
最后希望你们越做越好 加油 支持

**Comment by suziwen** [comment]
系统里需要用到小书匠服务器资源的将来会适当收费，数据都是在客户端本地跑的功能，会最大努力不收费。
万字以上的编辑没有问题的。不过一篇文章里添加图片，视频，音频，附件等文件时，不要太多太大，毕竟只是个文字处理软件。

**Comment by sepwolves** [comment]
可是word也是文字处理软件吧。。。
