### ISSUE TITLE
网页版和客户端都都不能正常现实mathjax公式

### ISSUE THREAD

**Issue by pootree** [suziwen/markdownxiaoshujiang#277]
如图，在更换了多个浏览器，以及重装了客户端后均是这种结果。设置当中的mathjax选项已经选中了
![qq 20161130130502](https://cloud.githubusercontent.com/assets/18095906/20740419/cd57d57c-b6fd-11e6-8d51-9a712e371c0f.png)

**Comment by suziwen** [comment]
这样写
`` `!$ \Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.$` ``

~~~~
```mathjax!
$$
\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.
$$
```
~~~~

系统为了更好的区分 mathjax 公式内容，防止单纯的 `$$` 符号会与用户普通文本混淆，所以所有的公式都是放在代码块里操作，并加上一个感叹号 `!` 用来表示执行里面的代码。

**Comment by pootree** [comment]
好的 谢谢。
