### ISSUE TITLE
[BUG] 上边的工具菜单总是消失

### ISSUE THREAD

**Issue by yuruotong** [suziwen/markdownxiaoshujiang#279]
而且从印象笔记同步到小书匠的时候，内容变成了
![image](https://cloud.githubusercontent.com/assets/22231230/20863333/3db20ae8-ba02-11e6-8a83-7fe8c1083415.png)
既没有高亮，语法也变了

**Comment by suziwen** [comment]
保存的文章如果在印象自己的客户端修改后，小书匠这边就只能是尝试将印象笔记的格式再转换成 markdown。转换过程是没办法完整还原成 markdown 格式。

**Comment by suziwen** [comment]
工具菜单消失确认是个bug,感谢反馈。（应该是点击了预览里的跳转引起的）

**Comment by qingyuanxingsi** [comment]
#292 这个编辑锁定容易实现么？？是否可以作为一个选项提供？？

**Comment by suziwen** [comment]
新版 v1.12.0 已经修复
