### ISSUE TITLE
表格处理出错

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#280]
```
| 分   | 小时 | 日   | 月   | 星期 | 命令 |
| ---- | ---- | ---- | ---- | ---- | ---- |
| 0-59 | 0-23 | 1-31 | 1-12 | 0-6fadfadfadsfasdf  | command  |
```
保存到 evernote 之后，生成表格的倒数第三列会非常的长，有很多空格

**Comment by suziwen** [comment]
想要什么效果？

![image](https://cloud.githubusercontent.com/assets/57370/20864728/b4383e68-b9c0-11e6-9209-52bc7a1f556f.png)

**Comment by oska874** [comment]
这个在小书匠上是正常的，但是在印象笔记客户端上，星期一列会非常宽。

**Comment by suziwen** [comment]
印象笔记客户端的效果也这样的

![image](https://cloud.githubusercontent.com/assets/57370/20891880/0a406be6-bb47-11e6-8cba-945fa1706e51.png)

你把你那边异常的效果贴个图片看下。

**Comment by oska874** [comment]
![image](https://cloud.githubusercontent.com/assets/4536559/20909862/08b57526-bb99-11e6-81d1-97d2214b8ba8.png)

**Comment by suziwen** [comment]
自定义css

``` css
.table{
width: initial;
}
```
