### ISSUE TITLE
表格自动刷新与 "自定义Class"功能冲突

### ISSUE THREAD

**Issue by PterX** [suziwen/markdownxiaoshujiang#281]
系统:Linux
书匠:客户端1.11.0版

将语法扩展全部打开，包括自定义Class，就会出现插入的表格不显示问题，重新打开文档也是如此．
但是关闭自定义Class，就可以正常使用．

初步分析是自定义Class与表格冲突．

**Comment by suziwen** [comment]
像是表格里的内容和其他语法(自定义Class)有冲突。语法手册里是把所有语法都打开，也能正常显示示例表格的。

**Comment by PterX** [comment]
语法手册是可以．
你可以复现一下：打开所有选项，新建一个文档，插入表格．这个时候就是无法显示的．表格里面没有任何内容．

**Comment by suziwen** [comment]
新版 v1.12.0 已经修复
