### ISSUE TITLE
一键导入 导出 多篇文档

### ISSUE THREAD

**Issue by lutianfei** [suziwen/markdownxiaoshujiang#282]
我之前是用其他markdown编辑器的，最近使用小书匠发现非常不错。
但是关于一键导入、导出多篇文档的似乎还没有这样的功能（虽然可以多篇同时导出，但需要一个个取选择比较麻烦），不知道您有没有这方面的功能计划呢？

**Comment by suziwen** [comment]
一键导出所有文章？

**Comment by lutianfei** [comment]
对，因为如果文章很多的话，一个个去选择也很麻烦不是

**Comment by suziwen** [comment]
1.13.0 版本开始，提供了对小书匠整个数据库的导入导出功能，导出格式为类似 json的纯文本。
