### ISSUE TITLE
作者关于小书匠的发展方向？是否有可能收费？

### ISSUE THREAD

**Issue by lutianfei** [suziwen/markdownxiaoshujiang#283]
最近体验了一下，马克飞象、Cmd Markdown 和小书匠。感觉各有千秋，
想问下作者关于小书匠有什么野心和长远打算吗？ 要长期把重要笔记交给一个软件，希望有个持续保障。
以后是否会进行收费呢，其实个人是支持收费的，不收费的软件意味着需要忍受各种坑。。。

**Comment by suziwen** [comment]
目前小书匠还只是个个人作品，适合当编辑器来用，系统提供了多种保存到第三方平台的功能，客户端还直接提供了保存本地的功能。重要数据自己需要自己及时保存或者导出。如果想要当作笔记类应用来使用，因为系统还没有提供云同步到小书匠服务器的功能，就需要自己定期备份数据库。

#275
