### ISSUE TITLE
小书匠居然是放在github上的开源项目啊

### ISSUE THREAD

**Issue by sepwolves** [suziwen/markdownxiaoshujiang#284]
不错不错。
我还担心有很多问题不知道怎么反映呢。。
我感觉好像一些第三方语法是不是不太好用。
比如说流程图之类的。
为什么小书匠没有给出一个很详细的说明呢？

**Comment by suziwen** [comment]
开源的代码是比较老的版本。

目前这里主要用做问题反馈的地方。

第三方语法里像流程图，在语法手册里有说明具体使用了哪些库，需要自己到对应的主页上去了解

比如甘特图用的是 [mermaid](http://knsv.github.io/mermaid/),就需要自己到 http://knsv.github.io/mermaid/ 去了解相关的语法了

流程图 https://bramp.github.io/js-sequence-diagrams/



~~~
---
grammar_sequence: true
---

``` sequence
Andrew->China: Says Hello
Note right of China: China thinks\nabout it
China-->Andrew: How are you?
Andrew->>China: I am good thanks!
```
~~~

**Comment by sepwolves** [comment]
原来是这样：小书匠里调用了别人的库，所以具体应该怎么写，还是要看别人的语法？

**Comment by sepwolves** [comment]
![20161208232009](https://cloud.githubusercontent.com/assets/4755874/21015473/1189cebc-bd9d-11e6-9bff-b776ea850f44.png)
请问一下这个grammar的语句是什么意思呢？是一定要这样设定，后面才能用吗？
还有，为什么这个图有的地方是灰色的呢？（今天突然间发现了，很奇怪，以前好像不是这样的。）

**Comment by suziwen** [comment]
流程图，plantuml 等需要到第三方库看语法。

`grammar_mark` 等 grammar 开头的是元数据标识，用来控制打开或者关闭当前文档的语法。想全局控制打开或者关闭语法，可以到 `设置>扩展语法` 里配置。里面有相应的元数据语法标识说明。

这个是行专注效果，可以在 `设置>编辑器>codemirror`下把行专注打开或者关闭。老用户如果是直接升级的话，设置默认是打开的，新用户的话，默认关闭，进入全屏无干扰写作模式时，会打开。
