### ISSUE TITLE
问个简单问题

### ISSUE THREAD

**Issue by 812865052** [suziwen/markdownxiaoshujiang#286]
![300790a2-1c43-4ce8-a535-59c3b5450ac2](https://cloud.githubusercontent.com/assets/12646048/21010364/a5c0f3ba-bd86-11e6-9d80-67b89f041310.png)这种标签是什么，就像这个的标签是blockquote ![image](https://cloud.githubusercontent.com/assets/12646048/21010382/c58d4be4-bd86-11e6-9b86-49ea38da8170.png)

**Comment by suziwen** [comment]
高亮？
```
==换一种方式...==
```

**Comment by 812865052** [comment]
你没理解我的意思，我的意思是 ==换一种方式...== 这个的标签是哪个，针对这个标签，我自己自定义一下他的样式，这样可能更好看一些。就像我对blockquote 这个标签样式进行自定义，那么文章里面的引用样式就都成了我自定义的样式了

**Comment by suziwen** [comment]
生成的 html 

``` html
<span class="mark">换一种方式…</span>
```

**Comment by suziwen** [comment]
web 可以通过审查元素，客户端版可以通过 `关于` 里的打开控制台，来查看生成的 html 结构，这样好自定义修改css, 也可以通过 `导出` html  功能来查看具体导出 html 结构。

**Comment by 812865052** [comment]
哦哦，非常感谢，知道怎么弄了。么么哒，能加个微信么

**Comment by suziwen** [comment]
有疑问还是这边讨论比较方便些，适合问题建议等需求的整理。还没有专门针对小书匠开微信的想法 :smiley:
