### ISSUE TITLE
你好，教育网访问不了小书匠官网啊

### ISSUE THREAD

**Issue by unlackingc** [suziwen/markdownxiaoshujiang#287]
是服务器问题么？还是说你js和css什么的用了google的cdn
好软件！
缺钱我们给你捐啊，千万别不弄了~

**Comment by unlackingc** [comment]
你明显是用了google的cdn
我把dns服务器改成8.8.8.8就快多了
不过下载还是很慢，能不能在git上给个下载链接？

**Comment by suziwen** [comment]
没有做 cdn 处理，都是放在阿里云上面。
