### ISSUE TITLE
数据库中的重名图片的覆盖bug。

### ISSUE THREAD

**Issue by deffyc** [suziwen/markdownxiaoshujiang#290]
如果我添加图片"1.jpg"到文档，链接自然的是"./images/1.jpg"，当再次上传一张内容不同的"1.jpg"时，文档中前面的图片将被覆盖。另外，保存到github中，也会将仓库中images目录中的同名图片覆盖。

**Comment by deffyc** [comment]
图片插入到文章里的链接为：'./images/640.webp%20%2814%29.jpg-Watermark'
图片实际文件名和保存到github的文件名其实是：640.webp (14).jpg

**Comment by suziwen** [comment]
新版 v1.12.0 已经修复
