### ISSUE TITLE
编辑锁定建议

### ISSUE THREAD

**Issue by qingyuanxingsi** [suziwen/markdownxiaoshujiang#292]
非常感谢您提供这么好用的Markdown编辑器。
有一个小建议，仅供参考:
是否可以参考马克飞象的做法，笔记同步到印象笔记之后就不允许用户自己编辑呢？？

**Comment by suziwen** [comment]
新版 v1.12.0 已经提供选项

**Comment by blurm** [comment]
请问下这个选项在设置的哪个地方勾选？

**Comment by suziwen** [comment]
@blurm 绑定界面小齿轮按钮
![image](https://user-images.githubusercontent.com/57370/27588279-475039ba-5b0d-11e7-91f0-c48eba0632ef.png)
