### ISSUE TITLE
关于同步到印象笔记，安卓客户端查看格式有问题

### ISSUE THREAD

**Issue by piaoruiqing** [suziwen/markdownxiaoshujiang#293]
您好！印象笔记安卓客户端查看小书匠创建的笔记时，第一行会被名为“markdownFile.md”的图片覆盖注，望解决，谢谢 
![img_20161219_220403](https://cloud.githubusercontent.com/assets/20742738/21344947/31d81666-c6d9-11e6-9e9a-c0e65b872d5c.png)

**Comment by suziwen** [comment]
新版  v1.12.0  已经修复
