### ISSUE TITLE
关于小书匠v1.11.0 Mac版闪退的问题

### ISSUE THREAD

**Issue by jowishu** [suziwen/markdownxiaoshujiang#295]
我的Mac系统为macOS Sierra10.12.2,使用的小书匠版本为v1.11.0 同步到印象笔记在按保存(cmd+s)的时候,软件总是会闪退.但是保存的内容不会丢失.

**Comment by suziwen** [comment]
有没有什么错误提示，或者通过命令行启动时，后台有什么错误的打印信息？

**Comment by jowishu** [comment]
没有错误提示，只是在按cmd+s保存的时候有时会闪退。我没有通过命令行启动，所以不清楚。



--
发自我的网易邮箱平板适配版



在 2016-12-23 10:39:39，"苏滋文" <notifications@github.com> 写道：


有没有什么错误提示，或者通过命令行启动时，后台有什么错误的打印信息？

**Comment by 3xeye** [comment]
我也是同样的情况，闪退的比较频繁，不知道是不是因为连接了印象笔记。

**Comment by suziwen** [comment]
试一下最新的 2.0.1 版本，是否还有这样的问题
