### ISSUE TITLE
在有道笔记上保存的文章在小书匠编辑器本地无法获取，有道笔记文件夹层级在本地失效

### ISSUE THREAD

**Issue by silencetea** [suziwen/markdownxiaoshujiang#299]
小书匠与有道笔记绑定，在有道笔记网页版上添加笔记，在本地小书匠获取更新时，没有在有道笔记上添加的两篇文章。
有道笔记上建立的文件夹嵌套层级在小书匠本地失效。

**Comment by suziwen** [comment]
有道笔记提供的 api 比较老，没有提供文件夹层级关系数据，都是扁平式的目录，保存时需要自己注意。有道笔记上添加的笔记，保存的目录也需要注意下，确认是在哪个目录下。

**Comment by silencetea** [comment]
谢谢。
关于目录的确认，是在根目录下建立的一个文件夹，笔记放在这个文件夹中，小书匠上可以看到文件夹，但是文件夹里没有笔记。

**Comment by suziwen** [comment]
我刚试了下，没问题的。你在有道添加了笔记，在小书匠这边得刷新目录试下 
![image](https://cloud.githubusercontent.com/assets/57370/21747800/53eed852-d539-11e6-9018-6722b9429476.png)

**Comment by silencetea** [comment]
刷新过了，还是不可以。
我在根目录下一共有两个文件夹，其中一个是只有笔记没有子文件夹，另一个有子文件夹。现在是没有子文件夹的文件夹无法获取更新的笔记。难道是因为根目录下只能放一个文件夹的原因吗？

**Comment by silencetea** [comment]
我知道原因了，因为我在有道上建立的是markdown格式的笔记，小书匠不能识别获取，但是建立普通的笔记，小书匠可以获取到。

**Comment by silencetea** [comment]
但是建立普通的笔记，获取的笔记数据包含html、css等内容，而在小书匠上建立新笔记保存在有道云上，然后在有道云上看到的是一致的，小书匠从有道云上获取数据有问题更新有问题

**Comment by suziwen** [comment]
api 没有返回markdown创建的文章，只能等api 更新提供了。
新版的有道云不再使用标准的 html 格式保存，他家的 api 也没有这些新的 xml 标签说明，暂时无法直接转换从有道云上新创建的文章。

**Comment by silencetea** [comment]
嗯嗯，明白了，谢谢你
