### ISSUE TITLE
Mac version error

### ISSUE THREAD

**Issue by zweite** [suziwen/markdownxiaoshujiang#30]
![2015-03-26 1 53 04](https://cloud.githubusercontent.com/assets/6611745/6841074/7bc2c01e-d3bf-11e4-8e44-80343e52b9f6.png)

**Comment by suziwen** [comment]
这个BUG已经知道了，就是进入全屏写作（阅读），再退出时，就会出现这个BUG。谢谢反馈，下个客户端版本会修复好的。
