### ISSUE TITLE
PDF导出的时候，格式不正确。。

### ISSUE THREAD

**Issue by edocevol** [suziwen/markdownxiaoshujiang#300]
![image](https://cloud.githubusercontent.com/assets/9777120/21748943/514a0088-d5cd-11e6-9bab-cd8be941a36b.png)

**Comment by edocevol** [comment]
代码丢了。。。。

**Comment by suziwen** [comment]
这个是 wkhtmltopdf  转换时没法准确计算位置，上一页显示部份内容，下一页再显示部份截取的内容，只能自己调整代码在文中的位置，或者自定义 css 等。
