### ISSUE TITLE
在设置语法扩展里面有错别字,字全变成宇了

### ISSUE THREAD

**Issue by Seraphli** [suziwen/markdownxiaoshujiang#302]
错别字 文字格式 变成了 文宇格式
以下雷同的有很多

**Comment by suziwen** [comment]
我这边显的就是 `字`, 不是 `宇`
![image](https://cloud.githubusercontent.com/assets/57370/21789444/c0a0beea-d69a-11e6-9824-571a7009f11e.png)

**Comment by Seraphli** [comment]
![](http://i1.piimg.com/567571/bc04022e52ac46c6.png)
![](http://i1.piimg.com/567571/5a5403b727c2a839.png)
Windows 64bit

**Comment by suziwen** [comment]
你这个看着像是字体的问题，你把这些文字， `ctrl+c`,`ctrl+v`到其他可以输入的地方，然后手动输入 `字`,`宇`，看是否一致。

**Comment by Seraphli** [comment]
还真是字体的问题,复制出来是正常的.不知道应该怎么解决.

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/21792053/a8017584-d6ac-11e6-981a-c809cbc148c4.png)

**Comment by Seraphli** [comment]
好了.使用楷体正常了.
