### ISSUE TITLE
如何调整渲染后预览的代码缩进？

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#303]
上个版本渲染后预览的代码缩进为4，新版本升级后变为8了。如何调整？

**Comment by suziwen** [comment]
主要是升级了 markdown 的解析引擎，遵循 commonmark 的标准，用户如果输入 tab , 输出还是 tab, 输入是空格，输出还是空格，不像以前那样会把 tab 转换成 4 个空格来替代。

想要对齐的话，可以做下面的处理。

**自定义css**

``` style
.xiaoshujiang_pre, pre{
    tab-size: 4;
}
```

或者

**编辑器里 tab 自动转换成空格**

在 `设置>编辑器` 里把 codemirror 的 `indentWithTab` 去掉  或者  ace 的 `softTab` 选上

或者 

把预览里的 pre 字体设置成非等宽。
