### ISSUE TITLE
预览窗口浮动后消失，再也找不到预览窗口。

### ISSUE THREAD

**Issue by sweetdark** [suziwen/markdownxiaoshujiang#304]
系统: windows 7 64位
显示器：两台，扩展模式
小书匠版本号：1.120

把预览窗口设置为浮动窗口模式，拖动到显示器边缘，另外一个显示器时，消失不见了。 不知道在哪里可以找回来。
卸载重装，也还是找不到，没有效果。

**Comment by suziwen** [comment]
浮动预览还是在同一个窗体里，只是预览的那个层可以拖动。现在还没办法拆分成两个独立的窗体，实现分屏预览。

恢复方法：

把窗体恢复到普通（就是非最大化），然后调整整个窗体的宽度，再拖动标题栏到适当位置，预览窗体就能看到。

或者 

到 `关于` 页面里， 找到 `数据文件路径` 对应的位置 ，把 `Local Storage` 内的文件删除，再启动小书匠，就会重置所有配置。

**Comment by lucaAce1024** [comment]
thank you ！问题解决了
