### ISSUE TITLE
请问怎么左右预览呢？同时提供一点建议

### ISSUE THREAD

**Issue by hjkl950217** [suziwen/markdownxiaoshujiang#306]
才开始使用这个软件，不知道怎么开启左右预览。
建议：
1.早上面一排的按钮，希望鼠标放上去能有更快的提示，有一些提示没有翻译（虽然能看懂）。
2.现在没有最大化按钮。

**Comment by suziwen** [comment]
预览区边上按钮

![image](https://cloud.githubusercontent.com/assets/57370/21964073/ee9f146c-db0a-11e6-9145-33fa22bda6f6.png)


1. 后继会加上说明，感谢建议
2. 客户端有最大化按钮，web端浏览器就可以直接最大化了
