### ISSUE TITLE
Checkbox功能失效

### ISSUE THREAD

**Issue by Seraphli** [suziwen/markdownxiaoshujiang#308]
设置里勾选了CheckBox
然后可以看到背景中未完成待完成都没有显示出来
另外语法手册的示例中也不能渲染出来
![](http://i1.piimg.com/567571/876473a08ce87723.png)

**Comment by suziwen** [comment]
这个现在改成跟 github 一致的语法，checkbox 必须在列表项里面，也就是类似下面的写法

```
- [ ] aaaa
- [ ] bbbb
- [x] cccc
1. [ ] dddd
2. [x] eeee
```

手册上忘记改过来了,多谢提醒。

**Comment by Seraphli** [comment]
:smile:现在可以了
