### ISSUE TITLE
能否详情描述一下在小书匠在绑定github图床时，token如何配置吗？

### ISSUE THREAD

**Issue by bxh7425014** [suziwen/markdownxiaoshujiang#309]
请输入有效的token,仓库，及对应的分支。
我这边怎么操作都显示跟进token找不到对应的仓库。

**Comment by suziwen** [comment]
类似这样的

![](https://cloud.githubusercontent.com/assets/57370/18816761/70ebba86-8315-11e6-9ef4-99fe979b10b6.png)

**Comment by bxh7425014** [comment]
![image](https://cloud.githubusercontent.com/assets/2756876/22722528/9e5e0d96-edf2-11e6-919d-fe037d2d6d07.png)
绑定的时候，出现了一个错误。但是没有给出出错的提示。

**Comment by suziwen** [comment]
自己先通过 git 添加一个文件到仓库里，
或者在创建仓库时，选中 `Initialize this repository with a README` 这个选项

**Comment by bxh7425014** [comment]
已经OK了。
非常感谢！
