### ISSUE TITLE
为什么没有渲染出公式？

### ISSUE THREAD

**Issue by Geekinus** [suziwen/markdownxiaoshujiang#310]
我输入了：
`!$ \Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,. $`
```mathjax!
$$\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.$$
```
得到了：
$ \Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,. $

    mathjax!    2行
$$\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.$$

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/issues/176#issuecomment-214618108

https://github.com/suziwen/markdownxiaoshujiang/issues/116
