### ISSUE TITLE
如何调整小书匠渲染的效果？

### ISSUE THREAD

**Issue by Geekinus** [suziwen/markdownxiaoshujiang#311]
1. 通过小书匠渲染到WizNote的公式看起来像是用粗钢笔在劣质纸上写的，很不清晰，而且似乎不是适量图格式。
2. 渲染出的代码块是粉红色，但我更希望是CSDN的样式。
3. 渲染出的极限`!$lim_{x→∞}$`中“x→∞”没有出现在lim下方。

**Comment by suziwen** [comment]
1. 系统在保存到第三方存储时，考虑到有些第三方平台并不支持 svg 标签的显示， 都统一把 svg 代码转换成 png 图片，再保存。你说的不清晰感觉是图片被放大的样子，能贴个图看下吗

![image](https://cloud.githubusercontent.com/assets/57370/22644441/87592244-ec9d-11e6-92de-5c2f6dd7a247.png)


2. 代码块的样式可以在 `设置>基本>预览区代码块样式`里调整，也可以自定义 css 来改成自己想要的样式
3. 这样的效果？
![image](https://cloud.githubusercontent.com/assets/57370/22644239/a89c6d9a-ec9c-11e6-844a-03f0c6fbd222.png)

**Comment by Geekinus** [comment]
确实，公式的显示效果不对。

________________________________
发件人: 苏滋文 <notifications@github.com>
发送时间: 2017年2月6日 18:54:05
收件人: suziwen/markdownxiaoshujiang
抄送: Geekinus; Author
主题: Re: [suziwen/markdownxiaoshujiang] 如何调整小书匠渲染的效果？ (#311)


  1.  系统在保存到第三方存储时，考虑到有些第三方平台并不支持 svg 标签的显示， 都统一把 svg 代码转换成 png 图片，再保存。你说的不清晰感觉是图片被放大的样子，能贴个图看下吗

[image]<https://cloud.githubusercontent.com/assets/57370/22644441/87592244-ec9d-11e6-92de-5c2f6dd7a247.png>

  1.  代码块的样式可以在 设置>基本>预览区代码块样式里调整，也可以自定义 css 来改成自己想要的样式
  2.  这样的效果？
[image]<https://cloud.githubusercontent.com/assets/57370/22644239/a89c6d9a-ec9c-11e6-844a-03f0c6fbd222.png>

―

**Comment by suziwen** [comment]
我试了下，想要在下面的话，mathjax 必须是块模式

````
```mathjax!
$$\lim_{x→∞}$$
```
````


![image](https://cloud.githubusercontent.com/assets/57370/22645714/5b731648-eca3-11e6-91f9-03a4430130d8.png)
