### ISSUE TITLE
导入html文件会卡死

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#314]
导入html会卡死，html不大。强制结束之后再重新打开会一直停留在logo界面，尝试用官网的打开也是失败！

**Comment by suziwen** [comment]
本地关联打开一个普通markdown文件，然后删除掉刚才导入的html文件，就可以避免卡在 logo 界面。
web版的话，点一下这个链接

[新建文件](http://markdown.xiaoshujiang.com/#md64=eyJ0aXRsZSI6IjIwMTctMi0xMuacquWRveWQjeaWh+S7tiB4eHh4eHh4eHh4eHgiLCJjb250ZW50IjoiLS0tXG50aXRsZTogMjAxNy0yLTEy5pyq5ZG95ZCN5paH5Lu2IHh4eHh4eHh4eHh4eFxudGFnczog5paw5bu6LOaooeadvyzlsI/kuabljKBcbmdyYW1tYXJfY2prUnVieTogdHJ1ZVxuLS0tXG5cblxu5qyi6L+Oc3Nzc3Nzc3Nzc3Nz5L2/55SoICoqe+Wwj+S5puWMoH0oeGlhb3NodWppYW5nKee8lui+keWZqCoq77yM5oKo5Y+v5Lul6YCa6L+HPT3orr7nva49PemHjOeahOS/ruaUueaooeadv+adpeaUueWPmOaWsOW7uuaWh+eroOeahOWGheWuueOAgiJ9)
