### ISSUE TITLE
插入图片，地址栏无法输入啊

### ISSUE THREAD

**Issue by bfmoka** [suziwen/markdownxiaoshujiang#315]
插入图片，地址栏无法输入啊，谷歌浏览器

**Comment by suziwen** [comment]
“地址栏无法输入” 指的是？

**Comment by bfmoka** [comment]
输入图片的url地址:  光标点不上，有时候又能点上

**Comment by suziwen** [comment]
这边没有出现你描述的问题，
说一下浏览器版本，操作系统，谷歌浏览器试着关闭第三方扩展看是不是还会出现这种情况。
最好能给出一个可以重现的操作顺序。

一般想使用网络地址图片的话， 也可以直接编辑器里输入 `![](网络图片地址)` ，效果是一样的。
