### ISSUE TITLE
链接绑定evetnote失败

### ISSUE THREAD

**Issue by RusanNg** [suziwen/markdownxiaoshujiang#320]
绑定evernote 国际版一直都失败，用ss翻墙也没成功过，一直显示空白。

**Comment by suziwen** [comment]
我这边没有出现你说的情况。
客户端还是 web 版？

**Comment by RusanNg** [comment]
![xiaoshujiang](http://p1.bpimg.com/567571/3a0ac3adf60fb0a7.png)
但是可以收到邮件说绑定成功。

**Comment by suziwen** [comment]
国内的印象笔记能绑定成功吗？还是只是国际的 evernote 不能绑定成功？
你在那个弹窗的界面上右键 ` 审查元素` 下，看看 `console` 有什么错误信息没？
我这边网页版是没有问题的，感觉像是你那装了其他第三方扩展引起的，你试着进入隐身模式，禁用掉所有插件，然后再绑定呢？

**Comment by RusanNg** [comment]
好奇怪，隐身模式可以绑定成功。
![](http://om0vxpskj.bkt.clouddn.com/17-2-27/93658943-file_1488197710405_ad8c.png)

绑定不成功显示说：由于您的浏览器没有开始javascript的支持，本系统将无法使用。

不知道是哪个插件有问题，请赐教。

**Comment by suziwen** [comment]
如果你熟悉 js 的话， 错误提示里应该会显示对应的 js 文件位置，看该文件属于哪个扩展的，就知道哪个插件了。
或者你自己到扩展管理页面，自己一个个临时关掉扩展来测试具体是哪个引起的。

**Comment by RusanNg** [comment]
好的，谢谢～
