### ISSUE TITLE
chrome使用在线版ace编辑器时中文输入有问题

### ISSUE THREAD

**Issue by fefr** [suziwen/markdownxiaoshujiang#321]
使用的输入法是搜狗拼音，输入拼音后选字时会输入一个空格但不见有中文，需要再一次选字后才会输入第一次所选中文，但同时会输入第二次选字的按键。

**Comment by suziwen** [comment]
建议使用内置的 codemirror 编辑器， 
ace编辑器对中文本身支持也不够友好，还必须是等宽字体。
