### ISSUE TITLE
MAC版本中保存印象笔记时，频繁出现闪退情况

### ISSUE THREAD

**Issue by Ox2g** [suziwen/markdownxiaoshujiang#322]
#### 错误信息
file:///var/folders/qw/hwk2s5756z9bjd4qxtkjrx7w0000gn/T/.org.chromium.Chromium.4keY0J/locales/zh/ns.common.json Failed to load resource: net::ERR_FILE_NOT_FOUNDfile:///var/folders/qw/hwk2s5756z9bjd4qxtkjrx7w0000gn/T/.org.chromium.Chromium.4keY0J/locales/zh/ns.common.json Failed to load resource: net::ERR_FILE_NOT_FOUND

#### 系统信息
 16.4.0 Darwin Kernel Version

**Comment by suziwen** [comment]
下载最新的 2.0.1 看下。
