### ISSUE TITLE
win版导入md文件无响应，杀进程后打不开

### ISSUE THREAD

**Issue by star3136** [suziwen/markdownxiaoshujiang#323]
导入md文件，点击确定后大概有一分钟无响应，杀死进程，再次打开客户端，加载引擎后停留在启动界面，多次尝试依然如此。打开网页版，多了一个LoadError: （加载出现错误{"code":1006,"error":{"errorCode":9,"parameter":"authenticationToken"}}），所有的文件都没有加载出来。

**Comment by suziwen** [comment]
客户端的话，关联打开一个本地的 markdown文件
浏览器的话点一下这个 [链接](http://markdown.xiaoshujiang.com/#md64=eyJ0aXRsZSI6IjIwMTctMy0z5pyq5ZG95ZCN5paH5Lu2IHh4eHh4eHh4eHh4eCIsImNvbnRlbnQiOiJcblxuIn0=)

原因的话，感觉是你的 markdown 文件里的内容可能比较特殊，系统解析时有问题。

**Comment by star3136** [comment]
应该的解析的问题。网页版是可以打开的，但是“根目录”下，只有一个LoadError的文件(自己的文件都没有显示)，点击这个文件在右上角显示"加载出现错误{"code":1006,"error":{"errorCode":9,"parameter":"authenticationToken"}}"。

**Comment by star3136** [comment]
导入的文件是这个[https://github.com/CharonChui/AndroidNote/blob/master/AdavancedPart/Android6.0权限系统.md](url)。

**Comment by suziwen** [comment]
authenticationToken, 指的是你绑定的第三方认证过期无效了，需要再绑定一次

**Comment by suziwen** [comment]
我用你的 markdown 文件  导入没什么问题
你`设置`里面默认打开了哪些语法开关？

**Comment by star3136** [comment]
默认的，并没有动这些语法，实际我也只用很少的一部分语法。
客户端依然打不开，请问下配置或者缓存在哪里？我清空下看看，再不行就只能重新安装了。

**Comment by star3136** [comment]
重新绑定后，文件可以同步了。这两个问题一起出现，我还以为是上传的文件引起的网页端文件也加载不出来。

**Comment by suziwen** [comment]
`C:\Users\Administrator\AppData\Local\小书匠`

#307 
#152 

如果缓存里的其他文件还需要的话，最好先备份下 `IndexedDB` 这里面的文件 。

**Comment by star3136** [comment]
感谢，客户端顺利打开了。
