### ISSUE TITLE
数据存储能支持选择多个吗?

### ISSUE THREAD

**Issue by sdbxpjzq** [suziwen/markdownxiaoshujiang#326]
数据存储能支持选择多个吗?

**Comment by suziwen** [comment]
同时保存到多个不同的第三方存储？这种需求应该不会很多，估计不会去实现了

**Comment by zzczx** [comment]
我也想有这各功能。
如果多个第三方存储不方便。能否有一个本地存储+一个第三方存储？
类似相互备份吧。
