### ISSUE TITLE
windows版本64位2.0安装以后一直显示打开文件,无法进入

### ISSUE THREAD

**Issue by lxyer** [suziwen/markdownxiaoshujiang#327]
软件试过重启,试过重新安装,电脑试过重启,都不行.我之前写了那么多的笔记怎么办啊,急死了

**Comment by suziwen** [comment]
只记得在更新文档里加提示，忘记在下载里加个提示了。

你可以回退到 1.12.0 版本，就能找到笔记了。 


新版本升级了底层模块，对保存在小书匠数据库里的旧数据有升级要求的用户，请先下载 `1.13.0` 版本，使用该版本提供的数据库导出功能，导出数据库，再在 `2.0.0` 版本上进行数据库导入, 完成数据升级。升级前建议先备份原有的数据文件（数据文件存储位置可到 `关于` 界面上查看）。如果已经升级到 2.0.0 版本，想找回老数据，可以回退到老版本的小书匠上。

**Comment by suziwen** [comment]
还有一个新版本升级时都会自动重建索引，笔记比较多的话，估计进入页面要等待比较长的时间。

**Comment by lxyer** [comment]
回到老版本之后好了

**Comment by kael-aiur** [comment]
我确认过了，升级2.0的版本必须全新安装，不能覆盖安装，所以先卸载老版本，再全新安装新版本即可启动，猜测是因为覆盖安装的时候，由于某些共同的文件改动导致2.0无法启动，但是配置信息是保存在用户目录的，所以卸载老版本只要没有删除用户配置，安装新版本不会影响之前保存的笔记

**Comment by marsggbo** [comment]
下了2.0后一直显示正在打开文件，然后我就重新下载了1.3，但是安装1.3后数据都没了，这该怎么办？

**Comment by suziwen** [comment]
@marsggbo 
升级脚本是不会删除旧的用户数据和配置信息的，你可以看一下这些是否还在?你自己没有手动删除这些目录，或者安装的第三方清理软件删除这些目录，那数据都是还在的。

``` 
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```
还有一个就是，你是从什么版本升级的， `1.12.0`？

**Comment by marsggbo** [comment]
@suziwen 忘记是从什么版本升级的了，不过现在退回到1.13了，数据不知道怎么搞的又恢复了，但是2.0总是停在“正在打开文件”的界面

**Comment by suziwen** [comment]
升级到 `2.0.1` 呢
2.0.0 版本关联打开 markdown 文件会失败。
`2.0.1` 直接打开失败的话，试着关联打开一个空白的 markdown 文件

**Comment by zhuleilei** [comment]
10篇左右的文档，回退到1.13后导出的json.2.6M，然后升级到2.0.1，导入后重建索引已经一个多小时了，还在重建，这算是正常的速度吗？？

**Comment by suziwen** [comment]
@zhuleilei 
那你试着先把 `数据文件位置`

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```
移动到另外一个位置，再启动小书匠，重新执行导入呢？

**Comment by zzk1977** [comment]
从1.3版本升级到2.01版本，必须首先卸载旧版本，然后重新安装，否则一直会停留在“打开文件的状态“！
