### ISSUE TITLE
汉字输入有问题？

### ISSUE THREAD

**Issue by lawlite19** [suziwen/markdownxiaoshujiang#329]
汉字输入后不立即显示出来
![t ib3o9 0y 7 34fkm6 1n](https://cloud.githubusercontent.com/assets/14356062/23777584/bf308428-0570-11e7-8909-7a24a5ddd033.png)

**Comment by lawlite19** [comment]
输入后什么也没有
![8j bx 6 rj4iw9v3hxe v y](https://cloud.githubusercontent.com/assets/14356062/23777659/26d4b5cc-0571-11e7-81ec-6edf3f5eaf5e.png)
按下空格变成这样
![l7w_j3x8ga hac 196 flqx](https://cloud.githubusercontent.com/assets/14356062/23777688/5694c554-0571-11e7-8210-cf51d4211181.png)
前面多出一个空格，我电脑问题？

**Comment by suziwen** [comment]
换成内置的 `codemirror` 编辑器试试。

![image](https://cloud.githubusercontent.com/assets/57370/23778166/4b7580f0-04fe-11e7-98e1-0274331849ce.png)

**Comment by lawlite19** [comment]
可以了，thanks.

**Comment by bymzy** [comment]
为啥都找不到切换的按钮，，，
