### ISSUE TITLE
下载好慢啊

### ISSUE THREAD

**Issue by marsleoguo** [suziwen/markdownxiaoshujiang#331]

**Comment by suziwen** [comment]
也可以到这下载 

https://github.com/suziwen/markdownxiaoshujiang/releases

**Comment by marsleoguo** [comment]
0B

**Comment by marsleoguo** [comment]
可以直接发我邮箱吗？335038842@qq.com @suziwen

**Comment by suziwen** [comment]
不单独发邮件

可以到 github 的 releases 下载，这个速度应该很快。

https://github.com/suziwen/markdownxiaoshujiang/releases
