### ISSUE TITLE
能和hexo兼容发布博文到GitHub么

### ISSUE THREAD

**Issue by flyuuu** [suziwen/markdownxiaoshujiang#332]
rt,
主要是数学公式完全失效了

**Comment by suziwen** [comment]
小书匠基础语法是遵循  CommonMark 的，扩展语法不能保证全部兼容。
数学公式的符号跟很多普通文档有冲突，而一般的 `$` 并不能很好的隔离开，所以小书匠这边都是把公式放在代码块里，再加上一个感叹号(表示执行里面的代码)来区分的。

hexo 本身也没有支持数学公式，只是通过第三方插件实现。
github 就完全不能识别 mathjax 的代码。 

一般的 hexo 主题，或者插件，都可以通过修改，单独识别块代码里的公式，让它渲染成数学公式的。

**Comment by suziwen** [comment]
在下个版本提供一个兼容选项。#349

**Comment by zhangnew** [comment]
设置中的： `资源绝对路径起始地址` 这一项，有个备注说：”选择了本地绑定功能，则该设置将失效，文章里的绝对地址资源将从绑定的根目录算起。“  但是 Hexo 的文章是在 `/source/_posts/` 里面，而图片放在   `/source/images/` 里面，现在就没法用了，之前用的 1.10 版本是可以用  `资源绝对路径起始地址` 的。

**Comment by flyuuu** [comment]
恩恩，其实如果小书匠和GitHub blog结合，应该会很受欢迎。毕竟小书匠很好用，而blog.github.io的使用者也真不少。。。。

**Comment by suziwen** [comment]
@zhangnew 我先看下，估计加一个绑定的选项，来确定是否覆盖全局的绝对路径。

不过一般的设计本地绑定只是做为本地存储的一种方案，没用过 hexo (或者类似静态博客生成) 的反而觉得不好理解这种选项的作用。:confused:
而且 hexo 里的资源(比如图片引用)，不管 post_asset_folder 怎么配置，在其他一般的 markdown 编辑器里也都不是能很好的解决路径引用问题。还不如直接把图片提交到图床, 使用完整的 url 地址来得简单 :smile:

**Comment by zhangnew** [comment]
@suziwen 没用过 hexo (或者类似静态博客生成) 的不用这个选项就好了。

图床是简单，就怕图床挂了，多说要关了，这就很蛋疼，幸好我用的是 Disqus（打算换了，暂定网易云跟帖）。

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v2.1.0
