### ISSUE TITLE
保存markdown文件到印象笔记时提示:处理文件样式关联失败

### ISSUE THREAD

**Issue by lxyer** [suziwen/markdownxiaoshujiang#335]
![image](https://cloud.githubusercontent.com/assets/17336748/23831025/608a702a-0753-11e7-9b28-9008eb0ae0a1.png)
这个是什么原因呢,是我自己设置模板的问题吗

![image](https://cloud.githubusercontent.com/assets/17336748/23831039/97015a6a-0753-11e7-99f8-93d6d867b79c.png)

**Comment by suziwen** [comment]
自字义 css 了?

**Comment by niuyongjie** [comment]
我之前也遇到过这种问题,你可以新建个,把内容复制进去,就能解决.可能是url造成的

**Comment by echo-ai100** [comment]
应该是新版本的bug,我用新版本无法同步到印象笔记，也无法发布内容到我的博客，老版本就可以。wordpress博客，地址http://bigdataer.net

**Comment by suziwen** [comment]
@bigdataer01 新建一篇文章呢？
我这边一直都能正常保存到印象。
你看一下 `关于` 界面里的 `错误日志文件`，看有什么提示没有？

**Comment by echo-ai100** [comment]
@suziwen 昨天试过了，相同的环境v1.3可以发布及绑定印象笔记，v2.0就不行。而且使用v2.0写作多保存几次电脑会非常卡，目测是内存管理有问题。

**Comment by suziwen** [comment]
@bigdataer01 
能说下你那系统环境吗？
操作系统版本，内存大小，cpu等，保存文章内容是否比较多？使用了哪些语法等，试着保存些简单的文章到印象笔记，也无法同步？


再一个就是，试着把数据文件选移动到其他地方，然后启动小书匠（让它直接默认原有的配置），再重新绑定到印象笔记，这样是否还不能同步？多保存几次还是会变卡？

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```

我这边 win7,win10下 v2版本 都能正常保存到印象笔记，多保存几次也不会出现卡的情况

**Comment by echo-ai100** [comment]
@suziwen win7,8G内存，intel i5处理器。只是一篇不到100字的文章。现在装回v1.3了，一切正常。

**Comment by suziwen** [comment]
@bigdataer01 使用的内置编辑器是什么， codemirror或者  ace?

**Comment by echo-ai100** [comment]
@suziwen 默认的

**Comment by suziwen** [comment]
@bigdataer01 截个图看下，老系统默认跟新系统的默认会不一样。

![image](https://cloud.githubusercontent.com/assets/57370/23980222/6e7c01dc-09cc-11e7-91a3-bb59a77c3406.png)

**Comment by echo-ai100** [comment]
@suziwen 不好意思，老版本已经卸载了。

**Comment by echo-ai100** [comment]
@suziwen 这款工具很棒，已经推荐给好几个人用了。

**Comment by suziwen** [comment]
@bigdataer01 感谢对小书匠的认可和推荐 :smile:

**Comment by zmcui** [comment]
ubuntu 14.04环境，1.2的版本遇到了这个问题， 升级到2.0.1， 问题解决了
