### ISSUE TITLE
离线版无法执行"ctrl + s"保存

### ISSUE THREAD

**Issue by dellzhui** [suziwen/markdownxiaoshujiang#337]
问题描述：可以通过鼠标点击上方按钮保存，但是无法通过通用快捷键ctrl + s保存
环境：windown10 专业版
版本：2.0.1

**Comment by suziwen** [comment]
`ctrl + s` 是不是被其他全局快捷键占用了？

**Comment by dellzhui** [comment]
应该不是全局键被占用，因为ctrl+s基本上是所有编辑器默认保存按键，他们都是正常保存的
