### ISSUE TITLE
双击打开文件没有反应

### ISSUE THREAD

**Issue by lawlite19** [suziwen/markdownxiaoshujiang#338]
- 双击打开markdown文件没有反应
- 打开方式里选择Story-writer.exe打开也是没有反应
- 但是直接运行Story-writer.exe可以

**Comment by suziwen** [comment]
小书匠版本是多少？
`2.0.0` 关联打开是有问题， `2.0.1` 已经修复了

**Comment by lawlite19** [comment]
就是2.0.1

**Comment by suziwen** [comment]
建一个空白的 markdown 文件，然后关联打开呢？还是所有相关的 md 文件都无法关联打开？

**Comment by lawlite19** [comment]
已经尝试，空白的一样，也是没有 反应，win10

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/23864548/e409ccce-07e0-11e7-89db-c1e906835b7d.png)

**Comment by lawlite19** [comment]
好的，明天尝试一下。

**Comment by lawlite19** [comment]
这样是可以打开
附：
![h175jw_p hqe 0w3ue w6](https://cloud.githubusercontent.com/assets/14356062/23884347/1a1618c4-08a7-11e7-95bc-b45185d63f8d.png)

**Comment by lawlite19** [comment]
命令：
- "F:\Program Files\Story\Story-writer.exe" --file=C:\Users\bob\Desktop\English.md

**Comment by suziwen** [comment]
这样看感觉像是安装脚本里注册表操作没有正确执行

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/23888427/d205a6f0-08c2-11e7-89c9-cb10a4f538ae.png)
![image](https://cloud.githubusercontent.com/assets/57370/23888431/d9e427fc-08c2-11e7-95fa-c88fcb30b170.png)
![image](https://cloud.githubusercontent.com/assets/57370/23888438/e26f798a-08c2-11e7-8fef-545bb485b86f.png)


正常安装应该都有这几项的，感觉像是你的其他软件限制修改注册表引起的。

**Comment by lawlite19** [comment]
open下面果然没有，我重装一下

**Comment by lawlite19** [comment]
可以了，谢谢 💯
