### ISSUE TITLE
最新版输入已经混乱？

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#340]
搜狗拼音和搜狗五笔，随便找个字中英文一起显示，删除原先输入的再进行输入，被删除的又会显示，醉了。
![1](https://cloud.githubusercontent.com/assets/11471256/23887801/f0854a9e-08be-11e7-8274-8b83a61637ae.png)
![2](https://cloud.githubusercontent.com/assets/11471256/23887802/f53c1400-08be-11e7-98d9-ce92e67fa908.png)

**Comment by suziwen** [comment]
切换到 codemirror 编辑器

#329

**Comment by ghost** [comment]
虽然说这样好像可以，但是不习惯这个编辑器，我还是用旧版本吧

**Comment by suziwen** [comment]
嗯， ace 编辑器主要对中文不太友好，升级时也就没怎么再测试它，估计以后版本会直接去掉这个选项

**Comment by ghost** [comment]
这个不太清楚，但是 ace编辑器 的界面跟其他的 markdown 软件的编辑器界面是基本一样，而且看起来比较有条理，所以我比较习惯点。而且我相信大多数人用ace比较习惯，不过就看你们能不能培养用户我使用习惯了。

**Comment by harry10086** [comment]
我还以为就我有这个问题呢，卸载重装重启，搞了几次还不行

**Comment by zhangnew** [comment]
我也有这个问题。

@suziwen 另外 codemirror  编辑器的语法识别也有问题，如图：
![image](https://cloud.githubusercontent.com/assets/9146834/24236968/4f413c7e-0fdf-11e7-9704-75d0bbb26769.png)

**Comment by suziwen** [comment]
下一个版本修复 ace 这个问题

**Comment by suziwen** [comment]
@zhangnew 嗯，有注意到，不过感觉不是很影响使用，就没有去修改了。而且把它当成标题处理还能折叠起来。

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v2.1.0

**Comment by zhangnew** [comment]
@suziwen 我上面说的 `---` 语法问题还没解决.

另外，小书匠每次更新的时候，覆盖安装比较好还是导出数据库重新安装比较好？

**Comment by suziwen** [comment]
@zhangnew 我另开了一个问题 #360，楼歪了

**Comment by zhangnew** [comment]
好的，辛苦~
