### ISSUE TITLE
小书匠打不开

### ISSUE THREAD

**Issue by YZSyangzhaoshuo** [suziwen/markdownxiaoshujiang#341]
![image](https://cloud.githubusercontent.com/assets/17767065/23932122/347b211c-0971-11e7-86f8-c53428c2ce78.png)

小书架v2.0.1打不开，在我安装了visual Studio 2017后就打不开了

**Comment by lijihuai** [comment]
我也是一样，不过是从 1.13 进行覆盖安装，然后同上

**Comment by suziwen** [comment]
#327

#323 
#307
#152
