### ISSUE TITLE
waverom已经不能用了吗？

### ISSUE THREAD

**Issue by zzczx** [suziwen/markdownxiaoshujiang#347]
谢谢。语法手册里面找不到了

**Comment by suziwen** [comment]
可以用的。 `设置>语法扩展> WaveDrom Digital timing diagram 语法`。 语法手册忘记更新了。

![image](https://cloud.githubusercontent.com/assets/57370/24090031/c3aed800-0d0a-11e7-8ccd-68768612bd86.png)

![image](https://cloud.githubusercontent.com/assets/57370/24090026/b21aa9a2-0d0a-11e7-8f36-ac67a842185b.png)

**Comment by zzczx** [comment]
我是直接拿waverom网站的代码测试的。
刚刚才发现，是因为小书匠不支持下面的config/head/foot部分导致的。



zzczx@163.com
 
发件人： 苏滋文
发送时间： 2017-03-20 14:16
收件人： suziwen/markdownxiaoshujiang
抄送： zzczx; Author
主题： Re: [suziwen/markdownxiaoshujiang] waverom已经不能用了吗？ (#347)
可以用的。 设置>语法扩展> WaveDrom Digital timing diagram 语法。 语法手册忘记更新了。
