### ISSUE TITLE
导出pdf的问题

### ISSUE THREAD

**Issue by jackychai** [suziwen/markdownxiaoshujiang#348]
1. 导出为pdf的时候，表格单元格不能自动换行，单元格内容较多全部放在一行，导致后面的内容显示不全
2. 导出pdf的时候，[TOC] 显示有问题，如果标题里面含有 <span id=xxx></span> 这样的代码，内容的地方显示是正常的，可是提取为目录的时候，直接显示了这个标签
3.  导出为pdf的时候，文件尾有这样的多余内容，没搞清楚怎么去除，设置里面自定义有个这个，删掉了也没用，难道要付费用户才能去掉吗，没看到有付费啊？
title: 未命名文件
tags: 新建,模板,小书匠
grammar_cjkRuby: true
欢迎使用 {小书匠}(xiaoshujiang)编辑器，您可以通过设置里的修改模板来改变新建文章的内容。

**Comment by suziwen** [comment]
1,2 最好提供个样例数据或者图片说明。
3. 没法重现你说的结尾多出来的内容，你新建一篇文章，导出也这样吗？ 小书匠版本是多少，操作系统？

**Comment by jackychai** [comment]
下面是测试样例：
----------------
<pre>
[TOC]
#### 测试编号<span id='idx100'>100</span>

body|
--|
testteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststestteststesttests|

详见：[idx100](#idx100)
</pre>
---------------------------
截图如下：
![image](https://cloud.githubusercontent.com/assets/26534489/24090551/47df8612-0d7c-11e7-8a20-472c98a1f649.png)

---------------------------
导出pdf截图如下：（1.单元格内容没有自动换行看不全 2. 目录部分不对,3.新建文档，结尾已经没有问题了）
![image](https://cloud.githubusercontent.com/assets/26534489/24090439/203819a4-0d7b-11e7-9293-b3198acd9365.png)

**Comment by jackychai** [comment]
span的用法，是在其他的地方看的，做内联好像很实用，而且我经常用在标题上，[TOC] 提取的目录不能自动去掉很令人伤脑筋

**Comment by suziwen** [comment]
表格的话，可以自己自定义css
比如
```
td{
    word-wrap: break-word;
    word-break: break-all;
}
```
强制让折行.

**Comment by suziwen** [comment]
标题加自己的 html 片段在处理 toc 确实有问题。
你可以先用另一种写法 

```
# 测试编号 <!--{#idx100}-->
```

**Comment by jackychai** [comment]
感谢，可以临时解决这个问题了。
