### ISSUE TITLE
公式写法问题

### ISSUE THREAD

**Issue by jackychai** [suziwen/markdownxiaoshujiang#349]
质能方程写法，一般写法，大多md软件都能识别
通用写法：$E=mc^2$
而这个写法，在小书匠不支持，看了下文档，原来可以这么写
小书匠写法：&#x60;!$E=mc^2$&#x60;
能否也能支持上面通用的写法呢，毕竟有不少存量文档，修改麻烦？

**Comment by suziwen** [comment]
大家都觉得需要上面的那种写法，那就在下个版本提供一个兼容选项。#332

**Comment by suziwen** [comment]
新版本已经提供  https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v2.1.0

**Comment by CarlKing5019** [comment]
建议支持通用写法. 行内公式: $E=mc^2$, 行间公式: $$E=mc^2$$.
这样一则与其他的 markdown 语法兼容, 二则方便输入数学公式, 代码看起来也舒服. 
对于笔记中有大量数学公式的人来说更方便, 对于不需要数学公式的人来说这个语法默认是关闭的, 也不影响.
望采纳.

**Comment by suziwen** [comment]
@CarlKing5019 已经支持了。

![qq 20170427215952](https://cloud.githubusercontent.com/assets/57370/25486823/ef5a7bdc-2b94-11e7-86d1-2a5707f189ad.png)

**Comment by CarlKing5019** [comment]
之前我也是把这项打钩了, 但是尝试写了 `$a^2+b^2=c^2$` 和 `$$a^2+b^2=c^2$$` 均解析错误, 以为不支持这种写法.
刚才我又试了下, 发现只有在角标字符串后加上空格解析才不会出现错误, 如下图所示:
对于 error 的情形, 可以看到解析器把 `2+b` 当成了角标字符串, 这个与 LaTeX 及其他 markdown 编辑器对数学公式的处理是不一样的, 可能是解析器的 bug.

![](https://github.com/CarlKing5019/image-library/raw/master/xiaoshujiang-math-bug.png)

**Comment by suziwen** [comment]
跟 上下标语法冲突了,

我临时做了个 patch 版本，就先放这里吧，你如果是 window 版本的话，可以到安装目录下的 `js` 文件夹里替换掉 `C:\Program Files\Story\js`
[patch-mathjax-for-3.0.0.zip](https://github.com/suziwen/markdownxiaoshujiang/files/964129/patch-mathjax-for-3.0.0.zip)

下个版本再一起发布了。

**Comment by CarlKing5019** [comment]
非常感谢你的及时修复. 我使用的是网页版, 刚试了下现在已经 OK 了.

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.1
