### ISSUE TITLE
有没有关于升级的教程

### ISSUE THREAD

**Issue by wowforestwow** [suziwen/markdownxiaoshujiang#350]
本地数据比较多，可是想升级小书匠版本，请问如何导出数据进行升级？
能不能把所有数据进行打包，不仅文章，还有小书匠的配置文件

**Comment by suziwen** [comment]
可以先看一下这个 #327
最主要的是先备份原有的数据文件到其他地方 

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```

1.x.x 版本数据文件位置 `IndexedDB` 目录里的文件， `Local Storage` 存放的就是配置文件。 

**直接升级到 2.x.x 版本，没有意外，是可以直接使用原有的配置和数据文件的**

，系统会把 `Local Storage` 自动复制到 `/Default/Local Storage`,及 `IndexedDB` 自动复制到 `/Default/IndexedDB` 的 （自己不要手动复制到对应目录）。
