### ISSUE TITLE
如何个性化定制发布内容

### ISSUE THREAD

**Issue by wowforestwow** [suziwen/markdownxiaoshujiang#352]
系统通过识别开头为weblog_的元数据，将其一起发送到博客平台上。比如你不想让文章发表，可以配置元数据weblog_publish: false。想让你的文章添加到小书匠和开发两个分类，可以配置元数据
weblog_categories: [小书匠,开发]。

我一直找不到weblog_publish,weblog_categories等接口设置位置，小书匠可以在哪里进行设置？？？？？？

**Comment by suziwen** [comment]
每篇文章的开头
比如

```
---
title: 2017-3-24未命名文件
tags: 新建,模板,小书匠
grammar_cjkRuby: true
weblog_publish: false
---
```
