### ISSUE TITLE
找不到本地地址 ./images/1490714273853.jpg 对应的资源

### ISSUE THREAD

**Issue by hamster09** [suziwen/markdownxiaoshujiang#355]
小书匠   找不到本地地址 ./images/1490714273853.jpg 对应的资源   这个问题怎么解决

![image](https://cloud.githubusercontent.com/assets/8361639/24512570/7ed893fc-15a1-11e7-96f1-a419418d830b.png)

**Comment by suziwen** [comment]
图片没有正确保存到小书匠数据库里面，重新粘贴一遍。

**Comment by hamster09** [comment]
我保存很多遍了，并且都同步到过印象笔记，现在软件奔溃后就这样了。请问怎么恢复

**Comment by hamster09** [comment]
印象笔记的又不能导出markdown的原格式，真是头疼一波了

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/24513517/02e97e24-1537-11e7-88b8-84f8d96b7f83.png)

**Comment by suziwen** [comment]
或者看一下历史记录，所有图片都变成这样？

**Comment by hamster09** [comment]
全部图片都是这样了

**Comment by suziwen** [comment]
你是具体怎么解决打不开的，删除掉数据文件？
如果 保存到过 evernote ,那就右键，更新本地缓存试试。
![](https://cloud.githubusercontent.com/assets/57370/24513517/02e97e24-1537-11e7-88b8-84f8d96b7f83.png)
