### ISSUE TITLE
粘贴图片导致链接地址异常

### ISSUE THREAD

**Issue by ZQ2014** [suziwen/markdownxiaoshujiang#358]
- 建议增加异常信息一键关闭，批量转换图片时经常会有大量的异常提示，必须逐一关闭才行；
- 批量转换图片时，如网络不好可能转化失败，此时需要逐一勾选失败的图片重新转换，否则会为已经成功的图片重新生成地址；
- 建议图片转换时检查源地址和目标地址是否属于同一个图床，如果是则无需重新生成地址。

**Comment by suziwen** [comment]
新发布的 3.0.0 版本添加了一个批量关闭错误提示功能
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0

至于是否属于同一个图床，这个暂时先不考虑，将来可能会在复选框上提供一个过滤功能，用户根据过滤条件自己决定是否转换。
