### ISSUE TITLE
建议支持 Hexo 图片资源

### ISSUE THREAD

**Issue by zhangnew** [suziwen/markdownxiaoshujiang#361]
建议新增一个本地绑定选项，可以指定资源地址。

https://github.com/suziwen/markdownxiaoshujiang/issues/332#issuecomment-288635760

https://github.com/suziwen/markdownxiaoshujiang/issues/332#issuecomment-288721946

**Comment by hxzhouh** [comment]
可以保存到七牛啊

**Comment by zhangnew** [comment]
@zchlwj 放自己手里安全。

七牛倒闭了怎么办？光缆被挖断怎么办？

多说倒闭，已经让很多人头疼了。

**Comment by zhangnew** [comment]
临时解决办法，创建软链接：
```
mklink /j "D:\hexo\source\_posts\images" "D:\hexo\source\images"
```

**Comment by suziwen** [comment]
新发布的 3.0.0 版本已提供该选项
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0

![image](https://cloud.githubusercontent.com/assets/57370/25509793/137a58fc-2b81-11e7-9647-3217e3174605.png)
