### ISSUE TITLE
windows 文件目录建议；邮箱附件bug

### ISSUE THREAD

**Issue by lanre123** [suziwen/markdownxiaoshujiang#364]
建议：
1.数据文件目录，错误日志目录转为非c盘位置！特别是图片截图多的时候，很占c盘空间，有系统重装丢失的风险。
2.[BUG]邮箱发布文章时以前添加的附件无法管理，造成每次发送邮箱都有以前的文件跟随发送，而找不到如何删除。

**Comment by suziwen** [comment]
第二个问题可以暂时通过重启应用解决下，下个版本修复。

**Comment by lanre123** [comment]
请问后续会会添加非c盘数据目录么？推荐给朋友使用，现在就是有这个顾虑，看着c盘变大，剩的硬盘都不多了

**Comment by suziwen** [comment]
这个是 nw.js  提供的，目前代码层面还没办法直接修改，后续会跟进

不过可以通过启动命令来改变数据目录

```
Story-writer.exe --user-data-dir=e:\xsj
```

这样启动，就会把数据保存到 `e:\xsj` 这个位置了。
如果相直接双击 markdown 文件启动时，也到这个目录，需要自己修改下注册表的值， 
```
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\XiaoShuJiangStoryWriter\shell\open\command
```
由原来的

```
"C:\Program Files\Story\Story-writer.exe" "--file=%1"
```

改成

```
"C:\Program Files\Story\Story-writer.exe" "--user-data-dir=E:\xsj" "--file=%1"
```

但是需要注意的是，每次重新安装时，会覆盖掉该注册表的值。

**Comment by suziwen** [comment]
邮件附件 bug 新发布的 3.0.0 版本已修复
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0

windows 文件目录我重新开了个 issue, 这个先关了 #383
