### ISSUE TITLE
导入印象笔记的markdown都变成附件了

### ISSUE THREAD

**Issue by lxyer** [suziwen/markdownxiaoshujiang#365]
在那里设置呢?现在2.1版本的也找不到黑色背景的皮肤了

**Comment by lxyer** [comment]
还有经常电脑管家清理缓存会把本地图片清除,再打开小书匠之后图片都变成X了

**Comment by suziwen** [comment]
1. 变成附件是指什么？图片按附件的方式显示了？可以到 `设置>预览` 里，把 `是否自动转换非图片扩展名为附件（自动识别jpg,jpeg,png,gif及无扩展名的文件为图片文件，其他的扩展名文件为附件）` 选项去掉试试

2. 修改主题
![image](https://cloud.githubusercontent.com/assets/57370/24987888/f9a2be20-1fc7-11e7-9aee-08e54f817a32.png)

3. 这个就得你自己配置电脑管家不要删除数据目录下的文件了。小书匠数据目录存放位置可以到 `关于` 界面查看。

**Comment by lxyer** [comment]
@suziwen  
![111](https://cloud.githubusercontent.com/assets/17336748/24997377/0503cd3a-2069-11e7-85e1-18a2fadcc705.png)

**Comment by suziwen** [comment]
最近保存到印象笔记的都变成只有一个 markdown 附件？
自定义 css 了？ 或者文章里有哪些比较特殊的语法， html 标签。
这个一般是系统在将 markdown 转换成 evernote 专用的标签时，转换失败引起的，看看错误日志里有什么信息？或者尝试新建一篇内容比较简单的文章，保存到印象笔记呢？
