### ISSUE TITLE
建议导出PDF拥有更多自定义的设置

### ISSUE THREAD

**Issue by verehu** [suziwen/markdownxiaoshujiang#366]
比如不同章节 之间设置不在同一页，希望第2章和第1章能够不在一起。

**Comment by suziwen** [comment]
新发布的 3.0.0 版本提供了 `___` 语法，做为 pdf 打印强制分页功能。
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0

**Comment by huweigoodboy** [comment]
太感谢啦。我觉得这是目前做强大的markdown编辑器。

**Comment by verehu** [comment]
太感谢啦。我觉得这是目前最强大的markdown编辑器。
