### ISSUE TITLE
在mermaid中使用subgraph显示不正常

### ISSUE THREAD

**Issue by AgileC** [suziwen/markdownxiaoshujiang#368]
在mermaid中使用subgraph显示不正常

**Comment by suziwen** [comment]
我这边没问题
![image](https://cloud.githubusercontent.com/assets/57370/25035780/34f2dc38-20b5-11e7-88f5-315a547af152.png)

**Comment by valuefish** [comment]
@suziwen 我这边V5.5.0版本linux客户端和网页subgraph都不显示
![image](https://user-images.githubusercontent.com/22961002/36843840-2e0c7dba-1d8b-11e8-809f-9c1b78d9aeca.png)

**Comment by suziwen** [comment]
@valuefish 我这边能正常使用的。

![image](https://user-images.githubusercontent.com/57370/36848968-c629332e-1d9d-11e8-9f10-46091962795e.png)

**Comment by valuefish** [comment]
@suziwen 除掉grammar_mermaid，还需要什么特殊的配置吗？我换了windows的电脑测试了一下，subgragh还是不可以用。
