### ISSUE TITLE
从网页导入到Mac6.11新版本块代码显示不正常

### ISSUE THREAD

**Issue by wadecoding** [suziwen/markdownxiaoshujiang#369]
![Uploading 块代码.png…](http://i4.buimg.com/567571/dece9387715b9e67.png)
![](http://i2.muimg.com/567571/003f555a488a333a.png)
在选中之后是这样的情况
![](http://i2.muimg.com/567571/55d8a4f8599ffe25.png)

**Comment by suziwen** [comment]
你这个导入，具体是什么操作？没看懂你描述的

**Comment by wadecoding** [comment]
就是绑定印象笔记设置把笔记保存到印象笔记里

**Comment by suziwen** [comment]
能提供下重现的文章片段吗，markdown 格式的。
这个是所有的文章代码段都会显示不正常？
我这边没法重现你说的情况。

**Comment by wadecoding** [comment]
我可能说的不太明白，再补充几句。
在小书匠网页版的编辑器里预览是正常的，但是把笔记保存到印象笔记里格式就乱了。目前就发现块代码的问题比较严重，而且行内代码的字体格式不是等宽字体上图是印象笔记中的效果，下图是编辑器中的效果
[md源码](https://github.com/wadecoding/-/blob/master/README.md)
![印象笔记预览](http://i2.muimg.com/567571/e47b5e36de6abe62.png)
![网页版小书匠预览](http://i1.piimg.com/567571/17a15c3323313826.png)

**Comment by wadecoding** [comment]
之前保存的有多行的块代码格式全都乱了，只有一行的块代码目前还没发现问题

**Comment by suziwen** [comment]
这个是印象客户端自己升级了内置浏览器渲染引擎，引起旧的 html 代码渲染行为不一致的问题。

我测试了下 window 的客户端能够正常显示，所以估计印象不同客户端提供的内置浏览器渲染引擎还不一样。而 mac 下的 web 版（safari, chrome）也是能够正常渲染的,所以怀疑它的 mac 版本客户端是单独出来的。

以前有单独为印象客户端的这种怪异行为单独调整过，后来发现这是一个不可控的因素，印象笔记自己升级了内置浏览器引起的渲染变化，今天为它进行了调整，下次印象客户端再升级一个版本，还是有可能会有一样的问题。

目前小书匠里的显示行号语法 `grammar_codeLinenums: true` 能够比较好的将代码块在 ios 客户端上显示，但同样的，这不能保证以后 印象笔记升级了是否也会在 mac/ios 下同样没问题。目前小书匠保存到 印象的 html 片段都是符合他们官方提供的 enml 要求。而在目前测试显示效果都主要以 web 版本为标准。

**Comment by wadecoding** [comment]
了解了，非常感谢你和你的小书匠
