### ISSUE TITLE
保存失败: 服务器出错

### ISSUE THREAD

**Issue by hloong** [suziwen/markdownxiaoshujiang#37]
{"code":1007,"error":"服务器出错","orign":{"errorCode":11,"parameter":"Error processing document: Invalid a href attribute://xn--ios-3v1ez26a8ual20eotcyw8jla03dq06ajyu"}}

**Comment by suziwen** [comment]
你的超链接里，href改成 `http://`开头的试试，
你这个是保存的evernote上时，提示的错？
evernote对链接有限制，得是http,https开头的

**Comment by hloong** [comment]
我是直接在网页markdown.xiaoshujiang.com来编辑，然后保存到evernote里的，,默认浏览器里的是markdown.xiaoshujiang.com

**Comment by suziwen** [comment]
我是说你文章里的链接或者图片，使用的链接地址里`href`里需要是`http://`或者是`https://`,或者是通过系统添加的图片，地址等，才能上传。

看错误应该是把`//xn--ios-3v1ez26a8ual20eotcyw8jla03dq06ajyu`改成`http://xn--ios-3v1ez26a8ual20eotcyw8jla03dq06ajyu`

你方便把markdown文章发过来吗，我看看一下是哪个格式出了错误，
发到 suziwen1#gmail.com

把#改成@

**Comment by hloong** [comment]
今天把我编辑的文档改了下没保存，然后直接在编辑器里删掉了！好像就没了？浏览器数据库里怎么导入？

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/7117119/51fd7d00-e229-11e4-9bbe-87875e8195f2.png)
在这个位置，
虽然系统对文件做了版本管理，不过目前没有提供任何界面操作历史的文件，想找到前一个版本的文件或者删除的文件，只能自己通过浏览器的开发模式找到对应的记录。

如果你的文件已经保存到evernote上，可以通过绑定操作，并选择对应的第三方存储，重新导入.

![image](https://cloud.githubusercontent.com/assets/57370/7117208/da9d372c-e229-11e4-959d-4e3565637d63.png)
注意绑定后，需要再选择一下，再确定，才算真正选上。
然后主界面就会转换成这种界面

![image](https://cloud.githubusercontent.com/assets/57370/7117249/161de530-e22a-11e4-9197-86f6b8b87515.png)

**Comment by hloong** [comment]
没有数据，我自己重新写了一遍文档
因为你这个网页版绑定了印象笔记无法保存
也是因为你们的本地客户端，效果不好，我从网页复制的原代码放到客户端里，结果面目全非
所以最后我才用markdown.xiaoshujiang.com这个网页来写文档，
ps:文档不方便发你邮箱了，抱歉！目前我只能写完后导出一个md文件保存本地，然后以后用的时候再从本地导入来编辑；似乎我找不到更好的办法了；

**Comment by suziwen** [comment]
好了，web版现在处理了一下链接，如果文章里有非`http://`,`https://`开头的超链接，在保存到evernote上时，系统将自动把html文件里的链接添加`http://`（markdown文件里的内容不变）．替换这个链接的原因是evernote不允许使用非法的链接．
你现在试试应该能保存上你现在的这篇文章了．

**Comment by hloong** [comment]
恩，我今天试了可以了，太感谢了！
