### ISSUE TITLE
保存到印象笔记时TODO-List显示不正常

### ISSUE THREAD

**Issue by Aopodo** [suziwen/markdownxiaoshujiang#370]
todo-list在保存至印象笔记后全都变成了无序列表，还请修复╮(╯▽╰)╭

**Comment by suziwen** [comment]
小书匠版本？

```
1. werwer
2. werwer
3. [ ] sdfsdf
4. sdfsdf
5. sdfsdf
6. [x] sdfsdf
7. [ ] sdfsdf
8. [x] sdfsdf
```

![image](https://cloud.githubusercontent.com/assets/57370/25071062/b56dfebe-2273-11e7-8575-61d69f09f780.png)

**Comment by Aopodo** [comment]
我使用的是2.1.0版本，在windows 64平台下，我按照你的语法说明文件上的todo-list语法来写的
`- [ ] text`
而不是
`[ ] text`
按照你的例子我在小书匠windows编辑器下根本显示不出来，同步到印象笔记也同样显示为原始字符。而我按照说明语法写在编辑器下是正常的，但同步到印象笔记后就不正常了，全都变成了无序列表。

**Comment by suziwen** [comment]
暂时先把 `evernote-base.js.txt` 这个文件替换到 `安装目录/plugins/plugins/evnote` 目录下的 `evernote-base.js`,  下个版本再统一修复发布.
[evernote-base.js.txt](https://github.com/suziwen/markdownxiaoshujiang/files/924699/evernote-base.js.txt)

**Comment by suziwen** [comment]
新发布的 3.0.0 版本已修复
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0
