### ISSUE TITLE
电脑出了一次故障重装后线上写的全部没有了

### ISSUE THREAD

**Issue by yqdch** [suziwen/markdownxiaoshujiang#373]
电脑出了一次故障重装后线上写的全部没有了，能不能推出用户系统做到线上同步呢

**Comment by suziwen** [comment]
目前是不会考虑提供同步用户数据到小书匠服务器功能的，费用和技术上都是很大一个难关，再加上国内的各种环境 :frowning_face:， 想想还是算了。

如果只是把小书匠当成一个编辑器，就无所谓数据问题。
如果想把小书匠当成一个笔记软件，就要自己及时备份数据文件

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```

或者选择一个自己认可的第三方绑定，把数据同时保存到第三方存储上。
