### ISSUE TITLE
保存到有道云笔记后显示问题，待办事项和代码段行号

### ISSUE THREAD

**Issue by vikin** [suziwen/markdownxiaoshujiang#377]
1.保存到有道云笔记之后待办事项前checkbox显示不出来
2.保存到有道云笔记之后代码段中行号没有显示

**Comment by suziwen** [comment]
原本今天发布的 3.0.0 版本已经修复了，可是当我再测试时，**发现有道对 api 进行了重新的设计**，不知道从什么时候开始（应该也就这几天吧），通过 api 新提交的文章，样式会乱。目前有道官方没有对新api相关的说明，所以只能等将来有道重新发布新的 api 文档时，才能再跟进。目前有道绑定功能只能认为已经不能再使用，建议直接用他们官方提供的编辑器，或者选择使用小书匠提供的其他第三存储绑定。
