### ISSUE TITLE
小书匠的各种bug,如果使用印象笔记的话,小书匠基本不能用了

### ISSUE THREAD

**Issue by lxyer** [suziwen/markdownxiaoshujiang#378]
给前后十几个人推荐以后,现在新版本弄的我都不想用了,各种错误:
1:小书匠自带的更新说明保存到印象笔记报错提示
![image](https://cloud.githubusercontent.com/assets/17336748/25309806/807742b0-2809-11e7-8d6e-b4da6a796cf4.png)
2:保存到印象笔记中的markdown都变成了附件形式...................各种方法都试了还是问题依旧
![image](https://cloud.githubusercontent.com/assets/17336748/25309960/40710b12-280c-11e7-94e2-8d6130ba4aed.png)

**Comment by suziwen** [comment]
自定义 css 了？
或者全局自定义 css 了？
`119.254.30.32` 这个 ip 既不是小书匠服务器的，也不是印象笔记或者evernote的

看着像是你的网络环境引起的，网络数据被拦截串改？ :question: 

#365

**Comment by lxyer** [comment]
没有自定义css @suziwen

**Comment by lxyer** [comment]
主要是markdown文件都变成了附件了,我的印象笔记就用看不了了,这个是个挺大的问题

**Comment by suziwen** [comment]
web 版会有问题吗？

或者试一下完全重装最新版的小书匠

1. 备份下原有的数据文件

备份下数据文件

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```

2. 完整卸载小书匠(包括安装目录下的所有文件及数据文件位置下的文件)，最好先卸载干净再安装
3. 下载最新版本的小书匠
4. 保存到印象笔记

这样保存后，还是只有一个附件？

**Comment by lxyer** [comment]
还是不行,在印象笔记里的还是附件,准备换软件了....

**Comment by suziwen** [comment]
嗯，
那没办法，我这边无法重现你说的情况。:broken_heart:
