### ISSUE TITLE
图片上传博客园问题

### ISSUE THREAD

**Issue by FirepadCN** [suziwen/markdownxiaoshujiang#379]
小书匠挺好用的，就是上传博客园时出现文章中图片上传失败的问题。还有就是无法套用博客园自身的代码框体，依然保持的小书匠自身的代码格式。[]~(￣▽￣)~*

**Comment by suziwen** [comment]
小书匠发布到博客上的内容是由 markdown 转换成 html 的片段。不会对不同的博客平台进行太多的调整。

上传图片失败时，有什么错误提示没？

**Comment by FirepadCN** [comment]
他显示的错误是格式错误，尽管我确实上传的gif格式或png等。

**Comment by suziwen** [comment]
找到原因了

**Comment by suziwen** [comment]
新发布的 3.0.0 版本已修复
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.0
