### ISSUE TITLE
代码块字符串如果包含 --- 这种类型的分隔线，预览会出现截断

### ISSUE THREAD

**Issue by outdoxl** [suziwen/markdownxiaoshujiang#381]
代码块字符串如果包含 --- 这种类型的分隔线，预览会出现截断，只显示 --- 后面的内容，而且没有代码块效果。

例如：
```java
package com.example;

public class Main {
  public static void main(String[] args) {
    // write your code here
    System.out.println("Hello");
    System.out.println("---");
    System.out.println("World");
  }
}
```
预览结果：
```
);
System.out.println("World");
}
}
```

其他类型的分隔线（`- - -`, `***`, `* * *`）不会出现这种情况.

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/25479386/3dc7e970-2b0a-11e7-9571-aa4732dc62f8.png)

我这不会。你那边都开了哪些语法？

**Comment by outdoxl** [comment]
确认是我自己问题。
我删除了模板产生的元数据内容，在首行加了 `---` 然后在后面写自己的内容：

![image](https://cloud.githubusercontent.com/assets/5090456/25516707/a4bc4300-2c1e-11e7-8570-2a48ade4fe24.png)

程序应该是判断首行如果有 `---` 则会找到下一个 `---` 闭合元数据，如果后面的内容有 `---` ，就会导致的预览不完整。
