### ISSUE TITLE
升级到v3.0.0之后，无法打开

### ISSUE THREAD

**Issue by liguobing** [suziwen/markdownxiaoshujiang#382]
升级到 v3.0.0 之后，打开直接闪退

**Comment by liguobing** [comment]
对了，是win7 64 位

**Comment by liguobing** [comment]
安装成功之后，打开就一直转啊转，转啊转，得有20多分钟（一共就两篇文章）
转了半天，也没动静，我就关了
再用快捷方式打开，直接显示停止工作，有一个问题详细信息，不知道对你有没有用
问题事件名称:	APPCRASH
  应用程序名:	nw.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	54f7d3de
  故障模块名称:	nw.exe
  故障模块版本:	0.0.0.0
  故障模块时间戳:	54f7d3de
  异常代码:	c0000005
  异常偏移:	000000000228bc20
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	dfce
  其他信息 2:	dfce654e32e56d97d3b088b73a586eb9
  其他信息 3:	1720
  其他信息 4:	1720eb749e7f7dca08885e12f73d0307

**Comment by suziwen** [comment]
从哪个版本升级到 3.0.0 的？
完全卸载，临时先装数据文件目录删除，再安装  3.0.0 ，启动呢？
