### ISSUE TITLE
导出、发送邮件 的建议

### ISSUE THREAD

**Issue by vikin** [suziwen/markdownxiaoshujiang#385]
建议将导出、发送邮件 按钮也放到编辑窗口上方工具条中，比如放在另存为旁边，或者直接就和另存为功能进行合并

**Comment by suziwen** [comment]
目前想设计成主界面和次界面这样一种效果，导出和发送邮件这些都不是特别多的需求，放到主界面反而太占空间。现在都一直想着把主界面的按钮再精简一些。
