### ISSUE TITLE
Mac印象笔记APP中无法正常显示代码块

### ISSUE THREAD

**Issue by Ethan-Yan27** [suziwen/markdownxiaoshujiang#388]
下图就是本人Mac Evernote APP中显示的代码块。

![image](https://cloud.githubusercontent.com/assets/7465441/25581268/7b47dea6-2eb9-11e7-8efa-13809ac3a019.png)

**Comment by suziwen** [comment]
#369 

可以考虑显示行号来解决

![image](https://cloud.githubusercontent.com/assets/57370/25603562/715b2bd8-2ec2-11e7-91f2-f9ec00fd1aca.png)
