### ISSUE TITLE
codemirror编辑器bug 3.0Tab键无效

### ISSUE THREAD

**Issue by miaomiao-dudu** [suziwen/markdownxiaoshujiang#389]

**Comment by suziwen** [comment]
下个版本修复，
可以通过打开 codemirror 的拼写检查 临时解决这个问题
![image](https://cloud.githubusercontent.com/assets/57370/25603631/e78c12ea-2ec2-11e7-8f7d-f77fe8e6232a.png)

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.0.1
