### ISSUE TITLE
mac无法同时打开两个文件.

### ISSUE THREAD

**Issue by mio4kon** [suziwen/markdownxiaoshujiang#39]
而且也没有最近打开的功能.新建一个后点保存不知道保存到哪了

**Comment by suziwen** [comment]
web端保存到浏览器内建的数据库里，客户端保存到系统用户目录下，不过数据格式是一个数据库，用户无法直接打开．

客户端打开时，窗口默认是较小的，你可以通过调整窗口到一定大小后，就能看到左侧的文档区里，里面有最近修改的文章，可能文档区是关闭的，你需要通过左侧中部的按钮，点击后展开．该按钮适合在较宽口的窗口出现．

![](https://cloud.githubusercontent.com/assets/57370/7117249/161de530-e22a-11e4-9197-86f6b8b87515.png)
