### ISSUE TITLE
Linux version 应用名称为 乱码

### ISSUE THREAD

**Issue by xmeng1** [suziwen/markdownxiaoshujiang#390]
3.0 在linux 上, fedora 25, 应用名称是乱码, 切换程序以及 dock上都可以看到乱码, 乱码如下图

![iamge](http://storage9.static.itmages.com/i/17/0501/h_1493670233_5747489_6034df0258.png)

**Comment by suziwen** [comment]
https://github.com/nwjs/nw.js/issues/5895

**Comment by xmeng1** [comment]
Got it! thanks for your reference. ps this app is the best writer app I have used on Linux, thanks

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v4.0.0
