### ISSUE TITLE
为知笔记绑定失败

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#391]
为知笔记更新了同步方式，手贱选择了之后，其不能登录了。
官网说这是新的同步方式，必须将所有客户端升级到最新版本，也就是其服务器地址可能变更了。
所以，麻烦更新下吧。

**Comment by jamy3531** [comment]
同样遇到这个问题，希望更新+1

**Comment by smallsuper** [comment]
强烈请求更新，修补这个漏洞……

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.1.1
