### ISSUE TITLE
建议:Github 绑定可以指定文件夹

### ISSUE THREAD

**Issue by xmeng1** [suziwen/markdownxiaoshujiang#393]
不知道这个功能 使用 API token 是否可行, 但是 StackEdit.io 使用 Oauth2 是可以实现的.

就是在 绑定同步到 Github Repository的时候, 可以指定 **文件夹**, 或者完整路径.  /folder/folder/xxx.md

因为有些静态博客的 post释放到子目录的.

**Comment by suziwen** [comment]
api token 也可以实现的，都是用的同一套 github api，只是觉得没有设计成那样的必要。小书匠绑定 Github 后， 再选择 Github 做为默认存储，以后点击保存，除了第一次新建的文章点击保存时，会弹出窗口要求选择保存位置，以后保存都可以直接自动同步了(注：自动同步需要选择了Github为默认存储，也就是左侧文件管理区要有 github 的文件树面板)。

![image](https://cloud.githubusercontent.com/assets/57370/25660917/f7f92de0-2fd3-11e7-8961-a99f5350803f.png)

或者你也可以使用客户端的本地绑定，然后选择一个文件夹，自己通过 git 同步到相关的第三方 git 托管服务平台(比如github)。

**Comment by xmeng1** [comment]
OK 明白了 可能是我之前github repository 没有其他文件夹, 就直接保存在 根目录了, 如果能第一次选择文件夹 也是可以的. 多谢!
