### ISSUE TITLE
保存的时候能否自动加上.md后缀？

### ISSUE THREAD

**Issue by FGFW** [suziwen/markdownxiaoshujiang#396]
windows 下，后缀比较重要。一个是可以关联上相关的应用程序。二个是用来区别文件类型也很方便。

如果有这个功能会很方便。

**Comment by FGFW** [comment]
编程语言nimrod 已经改名为nim了

**Comment by suziwen** [comment]
1. 新建的文章本地绑定或者保存本地时有自动加上 .md 后缀的，已经关联打开的原文件名是保持不变的，你是怎么操作会没有自动加上的 md?
2. 这个目前是按照 [highlightjs](https://highlightjs.org/download/) 提供的显示，后继应该会在设置里添加一个语言别名自定义功能。

**Comment by FGFW** [comment]
我修改了模板，我不想在文章标题有.md

**Comment by suziwen** [comment]
没太明白
文章模板里也可以不需要出现 `.md` 的，新建的文章，在本地绑定里第一次保存选择保存位置时会自动加上 `.md` 扩展名的

**Comment by FGFW** [comment]
那就先关闭问题吧。我决定先忍一忍。
