### ISSUE TITLE
导出的pdf 问题

### ISSUE THREAD

**Issue by Felix1029** [suziwen/markdownxiaoshujiang#397]
导出的pdf ， 显示的代码字段为蓝色，很不清晰， 怎么可以调代码段的颜色？？    是要改什么样式么

**Comment by suziwen** [comment]
`设置>基本>预览区代码高亮样式`

![image](https://cloud.githubusercontent.com/assets/57370/25928851/0b14f1ca-35c4-11e7-8679-08e806d8a44f.png)
