### ISSUE TITLE
导出PDF，目录文字错误

### ISSUE THREAD

**Issue by hloong** [suziwen/markdownxiaoshujiang#40]
![qq20150428-1 2x](https://cloud.githubusercontent.com/assets/3353954/7364547/6eafa102-edba-11e4-8020-8b57b8cf726d.jpg)
![qq20150428-2 2x](https://cloud.githubusercontent.com/assets/3353954/7364548/6eb7cf9e-edba-11e4-8e42-5f195857e753.jpg)

用的网页版markdown.xiaoshujiang.com 导出到PDF的时候，左边的目录有几个文字错误，如上图所示

**Comment by suziwen** [comment]
web里有个pdf预览，你打开看看那边的目录还是正确的吗，

我这边测试这几个字没什么问题。
![zzzz](https://cloud.githubusercontent.com/assets/57370/7366302/e99e5a16-edc9-11e4-96fb-a03b5c017f4c.jpeg)

**Comment by hloong** [comment]
预览没错，导出就文字错了

**Comment by suziwen** [comment]
![zzxsxx](https://cloud.githubusercontent.com/assets/57370/7366956/9622496a-edce-11e4-8efd-60c3f91b32f1.jpg)
一样的，我这边没错。

**Comment by suziwen** [comment]
我指的pdf预览是这个
![aaa](https://cloud.githubusercontent.com/assets/57370/7367091/97899730-edcf-11e4-8a42-adb6a86d9c2e.png)
如果这里的pdf预览目录没有错误，
那通过这里下载的内容呢
![xxxaaaaaaa](https://cloud.githubusercontent.com/assets/57370/7367107/b14dcb0a-edcf-11e4-85a7-f6476c070754.png)

**Comment by hloong** [comment]
我下载和导出 都是一样的，其实你只需要导出或者直接用你所说的下载就可以知道，难道你的没有文字错误？
我用的chrome和safari都试过
![qq20150429-5 2x](https://cloud.githubusercontent.com/assets/3353954/7383960/45f865cc-ee5b-11e4-8a78-f19a8eae6065.jpg)

**Comment by suziwen** [comment]
我这边下载，导出PDF都没有错误的  :frowning:

不知道 你这边导出html内容会怎么样。

**Comment by hloong** [comment]
那我试试win吧

**Comment by hloong** [comment]
![qq20150429-6 2x](https://cloud.githubusercontent.com/assets/3353954/7384185/328970a8-ee60-11e4-88ca-648a03718834.jpg)

**Comment by suziwen** [comment]
嗯，我这边也出现了，我先看看。:worried:

**Comment by suziwen** [comment]
这个还跟不同的pdf阅读器有关。。。。

**Comment by suziwen** [comment]
1.4.1,
已修复.
