### ISSUE TITLE
sina微博的图床服务是上传到微博的哪个地址？哪个地址是否是公开的？

### ISSUE THREAD

**Issue by fujinggui** [suziwen/markdownxiaoshujiang#401]
sina微博的图床服务是上传到微博的哪个地址？哪个地址是否是公开的？因为可能会有涉及隐私不方便公开的图片，所以想跟作者确认下。谢谢！

**Comment by suziwen** [comment]
用你绑定的微博帐号发送一张公开的图片。图床肯定需要公开的，不然小书匠客户端就没办法直接通过 url 拿到图片了（也就是预览区里的图片就无法正常显示了）。
不想公开的话，就只能选择小书匠提供的默认数据库存储。
