### ISSUE TITLE
链接到印象笔记的文件无法自动换行

### ISSUE THREAD

**Issue by OscarShen** [suziwen/markdownxiaoshujiang#402]
生成到印象笔记的内容太宽了，全屏甚至都不能看完一行。如下所示：
![image](https://cloud.githubusercontent.com/assets/13450440/26046413/6d9b5c4c-3981-11e7-9e45-a5f10399ce39.png)
窗口化之后效果奇差
![image](https://cloud.githubusercontent.com/assets/13450440/26046436/7f466266-3981-11e7-93da-8b9c8da2a3b3.png)
以下是马克飞象生成到印象笔记的截图：
![image](https://cloud.githubusercontent.com/assets/13450440/26046465/9ba9c79a-3981-11e7-9d10-0e015bf6992b.png)
![image](https://cloud.githubusercontent.com/assets/13450440/26046472/a3e5e1f0-3981-11e7-86f9-6aec68b0d31f.png)

**Comment by suziwen** [comment]
需要自己自定义 css,让代码块自动折行

``` css
.xiaoshujiang_pre, pre{
white-space: pre-wrap;
}
```
