### ISSUE TITLE
如何打开预览区域

### ISSUE THREAD

**Issue by absinthedx** [suziwen/markdownxiaoshujiang#404]
如何重新打开预览区域呢？一旦进入全屏再退出来就打不开了

**Comment by suziwen** [comment]
![qq 20160729010013](https://cloud.githubusercontent.com/assets/57370/17221772/e633c830-54ba-11e6-9863-32366ec1fa72.png)

这个位置，如果没有出现按钮，调整下窗口大小，再最大化就会出现这个按钮。
