### ISSUE TITLE
图片上传至七牛云，可以分文件夹吗？

### ISSUE THREAD

**Issue by OumCc** [suziwen/markdownxiaoshujiang#406]
使用七牛云作为图床服务，可以分文件夹存放吗？

**Comment by suziwen** [comment]
现在还分不了
不过可以自己建立一个专门放图片的 空间名称(Bucket Name)

**Comment by OumCc** [comment]
嗯嗯，了解。

希望可以接纳改进，有时文件多了，不好找

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.1.1

3.1.1 版本新提供了自定义文件夹功能
