### ISSUE TITLE
内存占用极高，建议分模块精简

### ISSUE THREAD

**Issue by nickhoo555** [suziwen/markdownxiaoshujiang#407]
> win10 64

内存占用总和高达260M，建议分模块精简，或以绿色软件发布，不同功能可作为插件，单独删除

**Comment by suziwen** [comment]
这个主要是由于底层使用的框架(html, css,js 等 web 技术)决定的，二百多兆目前看来还算是比较正常的使用量，只要不存在内存占有量无限增长，无法正常回收的问题，基本不会再进行上层的优化

目前小书匠里的 codemirror 编辑器拼写检查会占用比较大的内存，如果打开了该功能，可以考虑关闭掉。再一个就是批量导出和数据库导出操作时，也会占用比较大的内存。其他的，就如上面所说的，优化空间很有限。

如果机器内存比较小的话，是不建议使用小书匠的，可以考虑 sublime text 等原生应用开发的客户端。
