### ISSUE TITLE
Ubuntu 14.04.5 LTS 加载插件出现错误: 1006

### ISSUE THREAD

**Issue by zmcui** [suziwen/markdownxiaoshujiang#408]
xiaoshujiang版本是3.0.1, ubuntu环境下, 出现如下错误:
2017-05-18T05:53:09.896Z - error: 加载插件出现错误: 1006
加载出现错误{"code":1006,"error":{"errorCode":9,"parameter":"authenticationToken"}}

请问, 这个代表什么样的问题, 如何debug, 谢谢

**Comment by suziwen** [comment]
绑定的第三方存储认证失效（过期）了，重新绑定

如果进不了小书匠主界面，可以到 `~/.config/小书匠/Default/Local Storage` 这个目录下，把配置文件清空重置

**Comment by zmcui** [comment]
感谢, 是印象笔记的token到期
