### ISSUE TITLE
预览时mathjax公式正确，导出为PDF文件mathjax公式出现错误

### ISSUE THREAD

**Issue by wlcycxy** [suziwen/markdownxiaoshujiang#409]

**Comment by wlcycxy** [comment]
mathjax开启了兼容模式，用兼容模式书写，并且用`___`强制PDF分页。公式代码如下：
`$$动物的生殖\begin{cases}有性生殖\begin{cases}按受精方式分\begin{cases}体内受精\\体外受精\end{cases}\\按胚胎发育分\begin{cases}卵生\\胎生\\卵胎生\\\end{cases}\end{cases}\\无性生殖\end{cases}$$`
预览时公式正确，但导出为PDF时，除了正确的公式，公式下面还出现一下文字：

> \\按胚胎发育分
卵生
胎生
卵胎生
\end{cases}\\无性生殖\end{cases}

不知为什么

**Comment by wlcycxy** [comment]
$$动物的生殖\begin{cases}有性生殖\begin{cases}按受精方式分\begin{cases}体内受精\\体外受精\end{cases}\\按胚胎发育分\begin{cases}卵生\\胎生\\卵胎生\\\end{cases}\end{cases}\\无性生殖\end{cases}$$

**Comment by suziwen** [comment]
web 好了， window 客户端的话，可以自己先下载这个修复文件，解压后自己替换到安装目录下的 `js` 目录对应的文件上
[patch.zip](https://github.com/suziwen/markdownxiaoshujiang/files/1011685/patch.zip)

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.1.1
