### ISSUE TITLE
某些markdown笔记无限加载数据

### ISSUE THREAD

**Issue by emitting** [suziwen/markdownxiaoshujiang#41]
某些情况下，从 github.com 打开 md 文件出现无限`加载数据中`情况，错误信息见下图。
同一份文件从本地可以正常打开。客户端与网页版皆有此问题。
![](https://github.com/emitting/emitting.github.io/blob/master/assets/xiaoshujiang-issues.PNG?raw=true)

**Comment by suziwen** [comment]
1.4.1
已修复，你自己再试一下。

**Comment by emitting** [comment]
验证完毕，原来出问题的几个 md 文件都可以正常打开了。
感谢快速的修复:)
