### ISSUE TITLE
公式解析有点小bug

### ISSUE THREAD

**Issue by hitspring2015** [suziwen/markdownxiaoshujiang#410]
我要输入
![image](https://cloud.githubusercontent.com/assets/22462698/26272726/729692aa-3d52-11e7-8067-668829402609.png)

输入公式代码
`$ \sum_{i=1} ^ {n-1} (n-i)=n-1+n-2+\dotsi+2+1=$`
预览结果
![image](https://cloud.githubusercontent.com/assets/22462698/26272732/acf6b092-3d52-11e7-8398-648ab2758cc5.png)
别的编辑器就ok

**Comment by suziwen** [comment]
建议使用小书匠要求的数学公式写法， 这样可以比较好的隔离公式字符和普通文本
行内用 `` `!$\sum_{i=1} ^ {n-1} (n-i)=n-1+n-2+\dotsi+2+1=$` ``
块公式用 
````
```mathjax!
$$\sum_{i=1} ^ {n-1} (n-i)=n-1+n-2+\dotsi+2+1=$$
```
````
![image](https://cloud.githubusercontent.com/assets/57370/26272953/91ad0902-3cea-11e7-9265-20e54c5bbf64.png)

一定要用通用写法的话(注意需要自己在`设置>语法扩展>mathjax` 里把兼容通用写法打开)，自己需要注意 `$` 符号要紧挨着公式
应该是这样
```
$\sum_{i=1} ^ {n-1} (n-i)=n-1+n-2+\dotsi+2+1=$
```
而不是

```
$ \sum_{i=1} ^ {n-1} (n-i)=n-1+n-2+\dotsi+2+1=$
```

![image](https://cloud.githubusercontent.com/assets/57370/26272956/a672c746-3cea-11e7-8e9f-b499ad3a76dd.png)


mathjax 属于扩展语法，格式识别的细节只会尽量满足，但不会完全一致。再一个原因，本身用 `$` 这个大家经常用的符号来区分公式与非公式的内容就是很不合理。可能在一篇文章里即把 `$` 当成美元符号，又在这篇文章里使用数学公式，这样系统在查找公式块算法上就很容易出错。
