### ISSUE TITLE
怎么没用户同步啊

### ISSUE THREAD

**Issue by novahe** [suziwen/markdownxiaoshujiang#411]
因为要多台电脑编辑，最近在折腾markdown的在线编辑器，渐渐发现小书匠强大无敌，而且还开源 多平台，赶超cmd markdown指日可待，但是为什么没有用户同步啊！，我每在一台电脑上登陆都要去配置印象笔记，图床，这样是是不是很麻烦？而且有你你们自己的用户账号可以增强用户粘性啊。。。不理解

**Comment by suziwen** [comment]
可能方向不同吧
把用户配置数据或者用户数据保存到小书匠服务器上然后实现同步的功能，估计会很长一段时间都不会考虑的。如果你有同步这方面的需求，只能继续使用原先的编辑器了。:disappointed:
