### ISSUE TITLE
图片标题可以做成以前那种图名格式吗？

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#412]
现在的图片标题是在点开图片后，显示在放大图的左上角。但如果将笔记保存到印象笔记中后，就没有图片标题了。之前版本图片标题是作为图片图名显示在图片下方的，保存到其他地方也能显示。
另外想问一下，github下载小书匠的速度极慢，是什么原因？

**Comment by suziwen** [comment]
![image](https://cloud.githubusercontent.com/assets/57370/26404560/03d2a56c-4058-11e7-975c-9afd76f1a865.png)
![image](https://cloud.githubusercontent.com/assets/57370/26404592/22a73ca0-4058-11e7-9dc0-f5266b2682df.png)

我这边好像没有你说的情形，标题能正常在 evernote 上显示。能把你的 markdown, 预览效果和evernote 显示效果截个图看下吗。

2. 一般得翻墙后下载效果会好很多

**Comment by esdream** [comment]
问题解决了。在2.X 版本中会有这个问题，更新至3.0.1后问题解决。
