### ISSUE TITLE
下载的问题

### ISSUE THREAD

**Issue by jackychai** [suziwen/markdownxiaoshujiang#413]
大家都在哪里下载小书匠呢，在github要下载下来，实在是一个不可能完成的任务了。速度奇慢，然后一会儿以后，就显示已经断开，然后又需要重新从头再来，好像不支持断点续传。
早期版本还可以在其他网站下载，这个3.0的版本好像没有找到。能在国内搞个下载点吗，网盘的也行。

**Comment by suziwen** [comment]
这个翻下墙下载应该会好很多

#384
