### ISSUE TITLE
关联有道云笔记，无法读取出md文件

### ISSUE THREAD

**Issue by tuntuntutu** [suziwen/markdownxiaoshujiang#414]
账号关联了有道云笔记，但是只能读取到笔记文件，无法读取到md文件目录，而且也不是树形分级的

**Comment by suziwen** [comment]
目前有道官方没有对新api相关的说明，所以只能等将来有道重新发布新的 api 文档时，才能再跟进。目前有道绑定功能只能认为已经不能再使用，建议直接用他们官方提供的编辑器，或者选择使用小书匠提供的其他第三存储绑定。

#377
