### ISSUE TITLE
小书匠本地md文件可以回退到上一个版本吗？

### ISSUE THREAD

**Issue by esdream** [suziwen/markdownxiaoshujiang#416]
我一般在本地使用小书匠书写md文档，使用印象笔记在线保存md渲染后的文档。我在一次使用印象笔记网页版查看渲染后的文档笔记时，不小心在印象笔记编辑区对笔记进行了修改，虽然立即进行了恢复，但两次操作都由印象笔记自动保存了。当我在小书匠上打开该笔记的md源文件时，变成了渲染后的html代码：
![error](https://cloud.githubusercontent.com/assets/14349603/26544329/ffeab8c8-4493-11e7-9d60-4bb3dd6a2c81.PNG)
这种情况下，还可以将本地的md文件回退至上一个版本吗？或者有什么可以将代码还原成md文件的方法？

**Comment by suziwen** [comment]
有历史记录的
点击编辑区右边的小时钟按钮
![image](https://cloud.githubusercontent.com/assets/57370/26631470/b2fa61ce-45d0-11e7-8633-8cc3904ec4fa.png) 

或者直接把 印象笔记里追加保存的 markdown.md 文件内容直接粘贴过来也可以
