### ISSUE TITLE
关于中文词之间的光标跳转问题

### ISSUE THREAD

**Issue by hotdust** [suziwen/markdownxiaoshujiang#417]
你好，我使用的是MacOS系统。系统有个快捷键就是“option + 左右方向键”。这个快捷键可以进行中文或英文文字间跳转。例如下面的文字
  “这是进行测试的文字”
光标在“是”字前面时，按“option+右键”可以跳到“进”字前面（跳一个字）。再按“option+右键”，光标可以跳到“测”字前面（跳一个词）。
问题：测试了一下，小书匠好像不可以，CSDN的博客MarkDown编辑器可以。不知道能不能做成可以跳转的那种。（Sublime Text 3 好像也不行，请问一下知道是什么原因吗？）

系统配置
MacOS：EI Capitan
Chrome：版本 58.0.3029.110 (64-bit)

**Comment by suziwen** [comment]
这个目前只能在小书匠提供的`轻量编辑器` 里能够实现你说的效果。 codemirror 编辑器现在只能识别到英文单词。
想实现这种功能，需要中文分词的功能， CSDN 的 Markdown 编辑器和小书匠的 `轻量编辑器` 都使用的是浏览器内置的中文分词，所有可以实现你说的效果。 codemirror 编辑器或者  sublime text 3 没有对中文进行分词，所有都是一整句整句的跳。

**Comment by hotdust** [comment]
感谢详细的回答
