### ISSUE TITLE
绑定有道云笔记同步失败，绑定印象笔记同步也失败

### ISSUE THREAD

**Issue by ldcr002** [suziwen/markdownxiaoshujiang#420]
1.绑定有道云笔记，绑定成功后，无法打开有道云笔记的目录，也无法保存到有道云笔记中

2.绑定印象笔记时，新建笔记保存失败，

**Comment by suziwen** [comment]
1. 小书匠现在提供的有道笔记存储不建议再使用， 具体原因看这 #377 #414 , 下个版本会关掉有道笔记第三方存储，直到有道笔记重新发布新版本的 api
2. 最好能给出什么客户端，版本号。还有就是错误提示等信息。
