### ISSUE TITLE
导出的Markdown没有图片

### ISSUE THREAD

**Issue by Seraphli** [suziwen/markdownxiaoshujiang#421]
使用有道保存的文章再导出Markdown的时候只有文章本身没有图片.然后想要使用zip来导出的话却导出不了.一直是进行中.我记得以前导出好像直接是压缩包.

**Comment by suziwen** [comment]
1. 小书匠现在提供的有道笔记存储不建议再使用， 具体原因看这 #377 #414 , 下个版本会关掉有道笔记第三方存储，直到有道笔记重新发布新版本的 api

2. 导出 zip 的话，一直都是压缩包的，你试着新建一篇空白文档，再导出zip 看会不会出现。


![image](https://cloud.githubusercontent.com/assets/57370/26680577/951da9ac-469f-11e7-9dc5-e74ca864a536.png)

**Comment by Seraphli** [comment]
我更新到了3.0.1,然后新建了本地文章,拖进去一张图,然后选择导出zip,然后还是一直是等待的动画,没有包.等了有60秒以上了.

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.1.1

**Comment by Zzcv66** [comment]
小书匠导出的md格式给同事用其它md编辑器打开不显示图片，help。

**Comment by suziwen** [comment]
导出 md 是纯文本，需要使用图床的存储方式，别人才能看到。

或者导出 zip 格式，让你的同事再把 zip 导入。
