### ISSUE TITLE
客户端3.01版本无法下载难道没有人发现吗？？？我都下载2天了还下没动过。

### ISSUE THREAD

**Issue by YeungChiang** [suziwen/markdownxiaoshujiang#422]
有谁有安装包或者网盘地址可以发给我一下吗？真的下载不下来，谢谢大神们了~

**Comment by yjhenan** [comment]
把下载的那个连接，复制到地址栏，https改为http下载就正常多了，你试试

**Comment by sywuks** [comment]
添加下载非常难成功，试了N多遍，即便下载任务添加成功的也只是浏览器自带下载下了1M，FDM下了5M便下不动了。
https改为http，下载任务同样添加不成功，建议添加个网盘源作备用下载。

**Comment by novahe** [comment]
翻墙下的，无压力
