### ISSUE TITLE
开源中国（oschina）的博客不支持发布了吗?

### ISSUE THREAD

**Issue by tanshanli** [suziwen/markdownxiaoshujiang#423]
尝试过了两种URL
第一种：https://my.oschina.net/u/[用户ID]/blog  //这种是oschian上博客的URL 
  提示：该博客无法提供metaweblog接口
第二种：https://my.oschina.net/[用户ID]/blog    //这种是目前小书匠官网的演示URL 
  出现 假死状态

**Comment by suziwen** [comment]
应该是 oschina 新版本的 blog 不再提供  metaweblog api 接口了。详细情况应该到 oschina 上问相关维护人员，关于新的 api 入口地址(xmlrpc 地址)
