### ISSUE TITLE
linux导出pdf，如果文件比较大的时候，就会出现内存蹭蹭往上涨，然后死掉

### ISSUE THREAD

**Issue by chengjin005** [suziwen/markdownxiaoshujiang#426]
linux客户端导出pdf，如果文件比较大的时候，就会出现内存蹭蹭往上涨，然后死掉。
3g内存直接涨到8g。
文件里面的图片有5张，一张大概有5m左右的大小。
windwos无次bug

**Comment by suziwen** [comment]
我在 linux 下没法重现你说的情况，最好再提供一些更详细的信息。
