### ISSUE TITLE
3.1.0什么时候可以下载呀

### ISSUE THREAD

**Issue by welkinbai** [suziwen/markdownxiaoshujiang#428]
如题，我发现你的web版已经到3.1.0了，其中支持码云是我一直期待的功能。
但是跑来下载发现最高才到3.0.1呀。3.0.2和3.1.0呢？

**Comment by suziwen** [comment]
估计周未吧，主要是先放到 web 端上看有没有比较明显的错误

**Comment by welkinbai** [comment]
期待中~ @suziwen

**Comment by psp0001060** [comment]
点击 下载链接 https://github.com/suziwen/markdownxiaoshujiang/releases/download/v3.0.1/Story-writer-win64-setup.exe
下载不了啊，试了好多次都是一样。

**Comment by suziwen** [comment]
@psp0001060 翻墙后会好些。下个版本再考虑放到百度网盘。

**Comment by psp0001060** [comment]
@suziwen 我就是翻墙前后都试了，下载不了。楼主有百度云的下载地址吗

**Comment by psp0001060** [comment]
@suziwen 或者能发到我的邮箱里 psp0001060@163.com 吗

**Comment by suziwen** [comment]
@psp0001060  邮箱就不单独发了，现在还没有上传到百度网盘。
翻墙是能下的，你多切换几个翻墙代理看看，或者你是不是过滤规则忽略了 github 。我这边翻墙很快的， 1分钟就下完了。

**Comment by psp0001060** [comment]
@suziwen  好的，谢谢，我再试试看

**Comment by psp0001060** [comment]
@suziwen 换了个代理，正常下载啦~~

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.1.1
