### ISSUE TITLE
打开evernote中带有图片的笔记后，无法保存到evernote

### ISSUE THREAD

**Issue by icycandy** [suziwen/markdownxiaoshujiang#43]
两个问题
* 打开evernote中带有图片的笔记后，无法保存到evernote
* 在xiaoshujiang中新建带有图片的笔记，在evernote中无法正常显示

**Comment by suziwen** [comment]
编辑器的版本，客户端还是web端，
保存时右上角有什么错误提示吗
无法正常显示是指图片没有显示出来？

**Comment by icycandy** [comment]
用的web端，1.4.2
Firefox 37.0.2
右下角显示“处理中...”，右上角显示“保存成功”
![xiaoshujiang1](https://cloud.githubusercontent.com/assets/724257/7580636/8d076346-f8ab-11e4-8d92-4a5aed3010e4.png)
![xiaoshujiang2](https://cloud.githubusercontent.com/assets/724257/7580639/9231a692-f8ab-11e4-9c94-9c8609706aaf.png)
![evernote](https://cloud.githubusercontent.com/assets/724257/7580640/963fdfba-f8ab-11e4-9449-3071e2572ae3.png)

**Comment by suziwen** [comment]
1.4.3 web版  修复。再试一下。

**Comment by icycandy** [comment]
刚刚测试过多遍，问题2已经解决，问题1似乎依然存在。

复现：
1. 在evernote中新建一个笔记，插入一张图片；或者旧的有图片的笔记也可以。
2. 在小书匠中打开该笔记，增加少量任意字符，然后点击左上角的【保存】按钮
3. 点击【保存】以后，右下角会显示【处理中...】，经过大概二十秒的等待，【处理中...】消失，但是右上角没有出现【保存成功】
4. 返回evernote，点击同步按钮，刚刚在小书匠中的修改并没有同步过来

**Comment by suziwen** [comment]
问题1我再看看

**Comment by suziwen** [comment]
再刷新一下，应该好了。

**Comment by icycandy** [comment]
确实两个问题都解决了，赞！
