### ISSUE TITLE
那个发布功能，远端api是什么规范？

### ISSUE THREAD

**Issue by ilaziness** [suziwen/markdownxiaoshujiang#431]
发布博客，服务器的api什么规范？是有公开统一的规范吗？

**Comment by suziwen** [comment]
https://codex.wordpress.org/XML-RPC_Blogger_API

https://codex.wordpress.org/XML-RPC_WordPress_API

https://codex.wordpress.org/XML-RPC_WordPress_API/Posts

**Comment by ilaziness** [comment]
好，感谢！
