### ISSUE TITLE
插入视频的功能支持什么格式？

### ISSUE THREAD

**Issue by Seraphli** [suziwen/markdownxiaoshujiang#432]
虽然语法文档里面插入了一个ogg格式的视频，但是ogg应该普遍是音频格式吧
然后尝试插入mp4，不行
优酷和腾讯视频的视频也不行
不太明白支持什么格式的，也没有说明

**Comment by suziwen** [comment]
就是 html 标签里的 video, 语法会被替换成这种格式的 `<video src="movie.ogg" controls="controls"></video>`

**Comment by Seraphli** [comment]
我后来只能使用reveal.js直接来做ppt了...好像脚本里直接附带了一个播放器...直接放上mp4的可以放...但是小书匠的试过不行...

**Comment by suziwen** [comment]
这边是有对 reveal.js 进行定制修改，可能有些地方会不一样，再一个就是我用的 reveal.js 版本可能也比较早，可能 reveal.js 后面有再改进更新吧，因为小书匠上面的 reveal.js 用的人很少，就基本没再跟进了。

**Comment by Seraphli** [comment]
嗯
