### ISSUE TITLE
导出的PPT文件是空的

### ISSUE THREAD

**Issue by Seraphli** [suziwen/markdownxiaoshujiang#433]
使用`小书匠ppt使用示例`导出的zip文件中所有的文件都是空的
另外markdown中引用的gif文件会被已png的格式保存在zip中
版本3.1.1
另外示例中关于片段的描述有问题

**Comment by welkinbai** [comment]
遇到同样问题，有没有临时补救办法？

**Comment by Seraphli** [comment]
我记得以前的某些版本这个功能是好着的, 具体是什么版本好的就不知道了

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
