### ISSUE TITLE
使用本地存储时的一个数据丢失现象，疑似BUG，希望主人家测试下。

### ISSUE THREAD

**Issue by madgrass** [suziwen/markdownxiaoshujiang#436]
我的小书匠使用**本地文件系统**，图像服务用**小书匠编辑器存储**，发现有数据丢失的问题。
Windows 10的64位客户端，版本原来是3.0，升级到3.11后问题仍然存在，我家里的单位的电脑都有问题。

**具体问题：**
　　一个比较长的文字，一共写了220行左右，所有功能都正常，但是手动点击保存后，187行之后的内容突然就消失了；什么都不动，再连续点几次保存，每一次都会减几十行，最终到50行左右稳定下来，不会再减少。
　　我把文字复制到记事本，然后新建一个ＭＤ文件，这个问题同样会很有规律地重现，每次减少的内容都一样。

**希望主人家抽空帮忙排查一下问题。**

**Comment by suziwen** [comment]
我这边没法重现你说的情况。

感觉像是你那边绑定的本地文件系统，指定的文件夹被其他程序监控。小书匠一保存，监控程序就会回写的样子。

**Comment by suziwen** [comment]
看一下文件的历史记录，
![image](https://user-images.githubusercontent.com/57370/27482190-034a24b2-57e6-11e7-8a93-7cbfecd82cf8.png) 
![image](https://user-images.githubusercontent.com/57370/27482194-0ca30bf0-57e6-11e7-8aff-44bb55083354.png)
保存成功的话，历史记录应该会有的。

**Comment by madgrass** [comment]
**我重新测试了一下，依然发现这个问题，但是也有些新发现，希望对您有帮助：**

**1.** **重要**：使用默认的文件名 2017-6-23未命名文件时，故障完全消失！！一切正常！！！
**2.** **重要**： 文件名更改后本故障发生率为 100% ！！！大致是这样的，
- 新建文件（*此时是默认2017-6-23未命名文件，保存正常，不会出现丢数据*）
- 点击右上角X下面的文件名更改（我使用了“小明学markdown”这个名字）
- 关闭小书匠
- 通过操作系统，更改文件名（与上面的一致）
- 重新打开，左栏上面条目变成了2条，新的一条多了”.md“ 的后缀。 （**这个时侯出BUG了**）
- paste进去一大段文字，然后不断按保存，每保存一次，文字就会少几十行。
 ***
**3.** 文件夹监控应该可以排除，因为2台不同电脑，不同文件夹都会出现。
**4.** 根据您的提示，查看历史纪录，每一条都保存成功，而且有记录，对比差异显示就是少了最后的几十行，非常有规律。
**5.** 排除是保存回退问题，因为我是一次性复制一大段文字进去（随手百度的新闻），每保存一次就少几十行。
**6.** 文件最终会稳定在4K以内。

**Comment by suziwen** [comment]
我按照你的步骤，也没法重现。
需要进一步的操作细节。

1.  点击新建按钮新建文件后，有先对文件进行修改没（比如去掉元数据头等）？新建文件使用的是系统默认的模板？
2. 右上角 x 下面改完文件名后，有什么后继操作，还是直接关闭小书匠？
3. 通过操作系统改完文件名，是直接双击该文件打开吗？
4. 打开文件后，是在新多出来的那条上进行修改保存？

5. 要是能有个录像，看下具体操作最好了

**Comment by madgrass** [comment]
我专门做了个屏幕录像，请您分析一下：[https://pan.baidu.com/s/1kVJskAF](https://pan.baidu.com/s/1kVJskAF)，提取码： c5r7
***

- 录像中，请重点留意每次保存操作后，文件尾部的变化，从2分20秒后（外部文件改名后），尾巴就开始不断丢失了，而且历史记录中也能看到。
- 外部文件名更改后，原文件名会“阴魂不散”地重新出现，这个算不算是个不太合理的逻辑？
- **我的猜测**：外部文件名更改后，软件把它视为新的文件，但是由于文件名与内置数据库是一致，从而产生了冲突。不过冲突归冲突，也很难解释为什么会出现截尾现象。

**Comment by suziwen** [comment]
按照你的视频操作，我这边还是没法重现。:frowning_face:

## 问题分析

不过我发现你那边绑定的文件夹好像是在 seafile 同步监控下的。感觉是这块引起的，你换到另一个绑定目录再操作下呢？

小书匠在通过双击 md 扩展名文件打开的文档，会自动监控该文件的变化。如果该文件被外部文件修改后，会直接将变化的结果显示到小书匠里。

我估计是这样的操作结果引起的。

1. 双击 md 文件打开，
2. 小书匠上点击保存，这时候小书匠除了保存一个版本到自己的数据库里，还会再把文章内容保存到本地
3. 保存本地时，触发 seafile 文件监控
4. seafile 文件监控到变化后，**根据它自己的算法，又再保存了一次**
5. seafile 自己保存一次后，如果保存的内容跟小书匠当前版本不一样的话，就会触发小书匠使用本地文件系统的文件内容。(因为你是双击 md 文件，小书匠自动监控文件变化)
6. 被截断的那部分，感觉是 seafile 增量同步算法的原因。

-----

## 解决方法

 不想让小书匠监控本地文件的变化，就得在你通过操作系统修改文件名后，通过小书匠左侧的目录树，点击对应的文件名称打开。而不是直接双击打开。如果已经双击打开了，就直接先删除
![image](https://user-images.githubusercontent.com/57370/27505045-7e695d60-58c8-11e7-8104-91d25b1d9b2e.png)，再通过左侧目录树打开。


-----

## 其他

### 元数据
还有个操作细节，就是如果你已经使用元数据的 title, 就不需要通过客户端右上角的标题来修改了，可以直接修改元数据里的 title

![image](https://user-images.githubusercontent.com/57370/27505005-d60703d4-58c7-11e7-83b3-aed46409ef19.png)

**小书匠在处理 title 的优先级**
```
元数据 title > 直接 title
```
如果有 元数据 title 了，你这次修改完了 右上角的 title, 下次修改文章内容，或者通过双击打开，右上角的 title 还是会被元数据的 title 覆盖的。

### 重命名

1. 小书匠每篇文章都会在自己的数据库里有一条记录，同时保存着与本地文件系统的对应信息（比如关联打开或者本地绑定）。如果操作系统外面自己重命名文件（或者删除了文件），小书匠里的对应信息还是存在的，想要让它们替换成新的对应信息的话，可以考虑使用  `另存为`

**Comment by madgrass** [comment]
* Titel 的用法受教了，这些事果然还是作者最清楚^3^。
* seafile那方面，我更换文件夹和退出软件都没有改善，晚上再找台完全没安装过同步软件的电脑测试下。
* 另外有个疑问就是，seafile的监控应该是无差别的，为什么使用默认的文件名就不会出现这个情况呢？

**Comment by suziwen** [comment]
默认的文件名，你还没有使用关联打开，小书匠就不会监控本地文件的变化。你试一下直接用外部操作系统建一个 md 文件， 然后双击用小书匠关联打开，这样操作保存时会被截断吗？

**Comment by madgrass** [comment]
**很不幸的，问题仍然存在。** 我把新的测试录了像，有劳再查看一下。[http://pan.baidu.com/s/1mhB82Go](http://pan.baidu.com/s/1mhB82Go) 密码: 1i5m
***
测试借用了朋友的电脑，没安装同步监控软件，配置也完全不同，唯一的相同点，恐怕只有Win 10 X64。
* 问题的关键点已经确定，就是绑定了本地存储+修改文件名，与Title无关。
* 使用默认的文件名，无论怎么折腾都不会出现问题，包括加同步软件，从外面关联打开。
* 录像分几部分，分隔的时间点是2分15秒左右。
    * 全新安装，不绑定存储，所有数据存在内置数据库（无截尾）
    * 绑定本地文件夹存储，所有文件名保持默认（无截尾）
    * 修改文件名，无论是在软件内右键重命名，还是在外面操作文件夹，均出现保存截尾。
***
另外就是，数据好像并非是完全丢失，而是无法100%保存进新改的文件名，它数据库中，好像还有一份完整的数据。

**Comment by suziwen** [comment]
# 先说一下视频中重命名后，为什么会有两个文件出现

1. 小书匠每篇文章都会在数据库里有一条记录， 你新建时，数据库里创建一条记录 a, 这个时候 a 还没有对应到任何本地文件里
2. 当你切换到本地绑定，并使用另存为，把记录 a 保存到本地后， a 就建立了一条与本地对应的关联关系, 假设为 a(A)
3. 当你在本地绑定面版或者操作系统外重命名了文件A为B后，小书匠里的数据库是不会监控外部文件删除，重命名的。这时候 a 记录的关系还是 a(A). 所以当你在 a 记录上点击保存时， 由于 a(A) 关系的存在，小书匠将重新新建一个 A 文件
4. 当你点击本地绑定面版里的 B文件时， 小书匠数据库里找不到 任何关于 B 文件的映射， 所以就在小书匠系统里新建一个文件 b, 并与 B文件建立绑定关系 b(B)
5.每篇文章的绑定关系可以到`文件管理`  ![image](https://user-images.githubusercontent.com/57370/27516489-9f0167f4-59ed-11e7-848e-fa10b53de597.png) 界面上查看 , 
![image](https://user-images.githubusercontent.com/57370/27516494-b524d16a-59ed-11e7-8822-598bef444d3a.png)

![image](https://user-images.githubusercontent.com/57370/27516498-c2a1ca8c-59ed-11e7-8f6d-35654fc4bcad.png)




这个逻辑可能有些绕，不过感觉是最保险的一种方式。将来可能会在 a(A) 绑定里，当 A 文件不存在时，给个提醒 , A 文件已经删除，是否重新创建。



-------

# 接下来就是那截尾的问题

1. 按照你的视频重命名后，新的文章我这边还是能完整保存 :frowning_face: 


![image](https://user-images.githubusercontent.com/57370/27516448-9e11c6fa-59ec-11e7-80a8-44d6c12b4fc0.png)

2. 看一下你的操作系统版本，还有小书匠关于界面里的 `信息` 相关内容

![image](https://user-images.githubusercontent.com/57370/27516458-e4706228-59ec-11e7-87b4-3b381605522a.png)

3. 再一个就是看下任务管理启动了哪些服务

![image](https://user-images.githubusercontent.com/57370/27516470-24d09996-59ed-11e7-8721-d338daac4447.png)

**Comment by madgrass** [comment]
**请问能否约个时间，让你远程控制我这边的电脑，看一下到底怎么回事？？** 小书匠这个软件用着还挺好的，暂时还不想放弃（虽然不改文件名就能100%避免这个问题，但还是很好奇最后的结果）

我QQ: 150421290，加Q最好，邮箱联系也可以。
***
经过三台机的测试，我基本能很轻易的复现这个问题，现在反而对你的系统环境很惊奇了，不知你是否有其他的朋友或者电脑可以测试一下。**以下是我的电脑的信息**：
`{
    "arch": "x64",
    "cpus": [{
        "model": "Intel(R) Xeon(R) CPU           L5420  @ 2.50GHz",
        "speed": 2500,
        "times": {
            "user": 4426453,
            "nice": 0,
            "sys": 4859468,
            "idle": 97708828,
            "irq": 708781
        }
    }, {
        "model": "Intel(R) Xeon(R) CPU           L5420  @ 2.50GHz",
        "speed": 2500,
        "times": {
            "user": 4770171,
            "nice": 0,
            "sys": 2800093,
            "idle": 99424046,
            "irq": 59921
        }
    }, {
        "model": "Intel(R) Xeon(R) CPU           L5420  @ 2.50GHz",
        "speed": 2500,
        "times": {
            "user": 5919953,
            "nice": 0,
            "sys": 2278343,
            "idle": 98796015,
            "irq": 48171
        }
    }, {
        "model": "Intel(R) Xeon(R) CPU           L5420  @ 2.50GHz",
        "speed": 2500,
        "times": {
            "user": 4216234,
            "nice": 0,
            "sys": 1809031,
            "idle": 100969031,
            "irq": 21859
        }
    }],
    "endianness": "LE",
    "freemem": 3127824384,
    "platform": "win32",
    "release": "10.0.15063",
    "tmpdir": "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp",
    "totalmem": 6441582592,
    "type": "Windows_NT"
}
{
    "apm": {
        "storePlugin": "local",
        "font": ""
    },
    "epm": {
        "editorType": "light",
        "theme": "ace/theme/ambiance",
        "cm_spellChecker": false
    },
    "ppm": {
        "previewLayoutPosition": "east"
    }
}`
![111](https://user-images.githubusercontent.com/29625449/27517465-f0cc5abe-59ff-11e7-9ce0-0be83a4518fb.png)

进程服务的列表太长了，想截图都不好戴.......

**PS：** 在最新的那个屏幕录像中，我发现生成的两个文件、两个记录中，默认文件名那一条是数据完整的，但是我指定文件名那条，就出现尾巴截断的问题。所以我认为小书匠其实是有完整数据的，但不知为何没有写到最后的文件中。

**Comment by suziwen** [comment]
嗯，那就明天晚上 8点左右，我这边再排查下。

**Comment by madgrass** [comment]
因为临时要加班，所以8点应该没办法配合，可以先加个QQ保持联系。
最新发现，请使用**轻量编辑器**再做我之前的那个改文件名测试！！！！
文件写得长一点，要大于4K。
***
![qq 20170626154038](https://user-images.githubusercontent.com/29625449/27529196-29f8596a-5a86-11e7-84d2-6cf2953ef526.png)
***
我是在这个编辑器下面，才会出现截尾的，用默认的编辑器没有问题！

**Comment by suziwen** [comment]
还真是，换成 轻量编辑器 确实出现这种情况。

**Comment by madgrass** [comment]
我可以瞑目了.....还有把卸掉的软件装回去......

**Comment by suziwen** [comment]
感谢支持

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
