### ISSUE TITLE
保存到印象笔记出错

### ISSUE THREAD

**Issue by hitspring2015** [suziwen/markdownxiaoshujiang#437]
![image](https://user-images.githubusercontent.com/22462698/27475931-70d52a10-5839-11e7-8069-d4bdee0aed13.png)
保存到印象笔记的时候出现上面的错误，已经升级到了最新版本。
还有公式编辑器不支持
\begin{equation}
...........
\end{equation}
不知道怎么解决了

**Comment by suziwen** [comment]
应该是 token 过期了，或者 token 的权限被回收了。

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/27482125-bcf60508-57e5-11e7-8677-a04cce7e4ccc.png)
必须要有 `$$` 包裹起来
