### ISSUE TITLE
evernote目录的问题

### ISSUE THREAD

**Issue by icycandy** [suziwen/markdownxiaoshujiang#44]
有两个问题
1. 小书匠不支持evernote的二级目录
2. 左下角【刷新目录】按钮，现在刷新后所有目录都会折叠起来。要是刷新前和刷新后能保持同样的打开状态，体验更好些。

**Comment by suziwen** [comment]
二级目录指的是笔记本组？
官方的 api上好像没有提供这个接口，没办法拿到组的列表，及组跟笔记本的关系。
现在刷新体验是不够友好。:frowning:

**Comment by icycandy** [comment]
噢~ 我隐约记得以前用过一个叫nevernote的，好像就支持笔记本组，还以为API支持呢。
http://nevernote.sourceforge.net/

**Comment by suziwen** [comment]
下载安装了这个软件，确实实现了笔记本组的功能，我再看看，这个功能先记下了。

**Comment by DereckZhang** [comment]
除了笔记本组的支持之外，还建议加入搜索（笔记标题和笔记本）功能，笔记本和笔记一多，一个文件夹一个文件夹打开去找太慢啦

**Comment by DereckZhang** [comment]
我大概看了[Nixnote](http://sourceforge.net/projects/nevernote/)，它作为同步用户所有数据的客户端，向官方申请了非公开的API，功能和频率限制都比公开API多，笔记本组应该也是非公开的API实现的

**Comment by suziwen** [comment]
当时我也觉得奇怪,还以为他的软件可能没用使用官方的api,而是直接模拟web的请求.

**Comment by zhangnew** [comment]
5.6 支持了，可以关了
