### ISSUE TITLE
codemirror和ace编辑器的两个小问题

### ISSUE THREAD

**Issue by blurm** [suziwen/markdownxiaoshujiang#440]
### ace
行间距太小，几乎快重叠了
![xsk21](https://user-images.githubusercontent.com/10203631/27515470-3d5b7c72-59d6-11e7-8a2a-cc4ada0ed6cc.png)

### codemirror
当选择“高亮当前行”之后，光标被挡在了高亮的后面，几乎看不到了
![xsk22](https://user-images.githubusercontent.com/10203631/27515476-597b82f8-59d6-11e7-927c-c0bcbbcdaae7.png)

**Comment by suziwen** [comment]
ace 编辑器好像忘记加行高设置了 :frowning_face: 

codemirror 编辑器你使用哪款主题
![image](https://user-images.githubusercontent.com/57370/27516689-7b48b5f6-5984-11e7-84d0-8adad183366b.png)

我这边高亮当前行是可以看到光标的。
![image](https://user-images.githubusercontent.com/57370/27516696-9f090770-5984-11e7-82c7-d8c22971e53b.png)

**Comment by blurm** [comment]
Bold,Earthsong 都显示不出光标

**Comment by suziwen** [comment]
Bold

![image](https://user-images.githubusercontent.com/57370/27517042-6a2a63d6-598a-11e7-8ead-f2ebef035fa9.png)

Earthsong

![image](https://user-images.githubusercontent.com/57370/27517047-7d734106-598a-11e7-93eb-764e53d1aa12.png)

我这都可以。。

-----

你是指选中状态不会出现光标吧？

![image](https://user-images.githubusercontent.com/57370/27517060-be39db3c-598a-11e7-9155-2e6939302241.png)

选中状态不出现光标是 codemirror 默认这样的。

http://codemirror.net/demo/theme.html

**Comment by blurm** [comment]
不是选中状态，就是在高亮当前行的状态。
有一点没说清，**需要在vim的普通模式下。插入模式是可以找到光标的**
下图是在bold下
Ubuntu 16.04 linux客户端 3.1.1

![xsj31](https://user-images.githubusercontent.com/10203631/27517245-f9ded48c-59fb-11e7-92bd-58bf64214f9e.png)

**Comment by suziwen** [comment]
你这是客户端版本还是 web 版本，

客户端版本试着把 数据文件目录移掉，再启动小书匠，选择 blod 主题呢

![image](https://user-images.githubusercontent.com/57370/27517335-69405a42-5990-11e7-862d-265b7ffd2bf1.png)

比如把 `C:\Users\Administrator.WIN7-1607010007\AppData\Local\小书匠` 暂时改成 `C:\Users\Administrator.WIN7-1607010007\AppData\Local\小书匠aaa`

**Comment by blurm** [comment]
试过了，不行，还是显示不出来

**Comment by suziwen** [comment]
web 版本呢，也不能显示光标？

去掉`高亮当前行` 选项就能正常显示出光标？

这个感觉跟机器或者操作系统关系比较大，主要是我这边没法重现，不好排查。

**Comment by blurm** [comment]
web版本也是如此，Chrome和firefox都是
Ubuntu 16.04
Chrome 59.0.3071.109
Firefox 54.0

**Comment by suziwen** [comment]
我这边没有 ubuntu 16.04 环境，得找个时间安装下才能确认。
不过我在自己的 ubuntu 14.04 上测试是没问题得。

**Comment by blurm** [comment]
那我先去掉高亮好了。

另外codemirror的光标样式可以有用户自己定义么？感觉ace的样式更好一点

**Comment by suziwen** [comment]
window 版本的话，可以通过修改 css 文件实现， 其他版本都打包到一起了，无法修改。
我自己电脑看，好像两个编辑器的光标多基本一样， 没感觉出有什么差别 :frowning_face: 

不知道是显示问题，还是操作系统问题，为什么我的 ace 编辑器没有行重叠的问题。你那编辑器字号，字体都配置成什么的？

**ace** :
![image](https://user-images.githubusercontent.com/57370/27538203-7f720d40-5a3c-11e7-8557-2802187cdab4.png)

**codemirror** :
![image](https://user-images.githubusercontent.com/57370/27538207-8c2004de-5a3c-11e7-8cf4-79d0c7eb1549.png)

**Comment by blurm** [comment]
我用web端不加任何自定义配置也是一样的，行挨行。
看来的确和ubuntu16.04有关系。。？

**Comment by suziwen** [comment]
你那边是不是使用了放大器显示功能?
访问下这个网站什么效果

https://ace.c9.io/build/kitchen-sink.html

**Comment by blurm** [comment]
系统的dpi设置有调整过，浏览器放大到1.5倍了。但是把浏览器放大调回去也是一样的效果
![xsf41](https://user-images.githubusercontent.com/10203631/27538809-5c7951de-5aac-11e7-89c3-976eaf667438.png)

**Comment by suziwen** [comment]
在这个网站上 https://ace.c9.io/build/kitchen-sink.html

把 font size 调成其他的大小 , Mode 和 Document 都选成 Markdown，再输入些中文（比如把小书匠上显示重叠的内容放到这里）

**Comment by blurm** [comment]
一样的重叠效果
![xsf42](https://user-images.githubusercontent.com/10203631/27541180-8c56291e-5ab5-11e7-9ba2-c2cb94ec446c.png)

**Comment by suziwen** [comment]
那可能还是很系统显示设置有关，下个版本再把行高设置添加上去

**Comment by suziwen** [comment]
你是不是在 vim 模式下，高亮当前行不显示光标的？

**Comment by blurm** [comment]
是的，codemirror vim模式

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
