### ISSUE TITLE
mermaid卡死

### ISSUE THREAD

**Issue by welkinbai** [suziwen/markdownxiaoshujiang#441]
windows 64位
ace和codemirror都有这个问题

输入以下文字后，编辑器直接卡死：

```
```mermaid!
sequenceDiagram
    participant 
```
```

网页版就没有这个问题。
版本号：3.1.1

**Comment by suziwen** [comment]
[mermaid.zip](https://github.com/suziwen/markdownxiaoshujiang/files/1101944/mermaid.zip)

把这个压缩包里的文件临时替换到 `安装目录/js/mermaid.full.min.js` 文件上

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
