### ISSUE TITLE
Mac版3.1.1的小书匠编辑器的mermaid导出到印象笔记无图

### ISSUE THREAD

**Issue by gongxiao** [suziwen/markdownxiaoshujiang#443]
小书匠编辑器3.1.1 Mac64版
mermaid（graph TB）
印象笔记

问题：绑定印象笔记后，保存同步后可以看到附件，但看不到图只有文字（gannt图是好的，不知道为什么）

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
