### ISSUE TITLE
儲存到國際版 Evernote 後，程式碼區塊樣式不正確

### ISSUE THREAD

**Issue by imiss** [suziwen/markdownxiaoshujiang#446]
## 測試環境：
- Google chrome 版本 59.0.3071.115 (正式版本) (64 位元) 使用**無痕模式**
- 線上版小書匠編輯器 3.1.1

## BUG；
程式碼區塊在小書匠編輯器中顯示是正常的：
![image](https://user-images.githubusercontent.com/326140/27726539-7089577e-5dad-11e7-8654-6f035ddc76d6.png)

但儲存到 Evernote 後程式碼區塊樣式不正確
![image](https://user-images.githubusercontent.com/326140/27726556-7af16986-5dad-11e7-885e-056ffa71c58f.png)

**Comment by suziwen** [comment]
你那 evernote 客户端版本号是多少。我这边 Evernote_6.5.4.4720 版本下查看是没有问题的。

----------

还有就是小书匠同步到 Evernote(印象) 后，主要还是以他们家的 web 版为结果，如果在 Evernote(印象) 上的 web 版本测试通过，就基本认为是没问题的了。

https://github.com/suziwen/markdownxiaoshujiang/issues/369#issuecomment-294348240

**Comment by imiss** [comment]
> 你那 evernote 客戶端版本號是多少。我這邊 Evernote_6.5.4.4720 版本下查看是沒有問題的。

你說的沒錯，我看有問題的 Evernote 版本是 prerelease 版，
在 Evernote 網頁上看則是正常的，
謝謝你的回覆

![image](https://user-images.githubusercontent.com/326140/27772086-22fb3c1a-5f8e-11e7-84cf-126e28d864af.png)
