### ISSUE TITLE
总是在文档目录下生成debug.log

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#447]
电脑升级到win10后，包括最新版在内的小书匠，不知道为什么总是在markdown目录下自动生成 debug.log 这个日志文件。因为写的文档是上传到git上的，所以经常要删除这个日志。烦请作者知悉。

日志里面的信息是：
> [0705/115250.200:ERROR:registration_protocol_win.cc(55)] CreateFile: The system cannot find the file specified. (0x2)

**Comment by suziwen** [comment]
你这个是本地绑定存储？还是直接关联打开一个本地文件？或者是绑定github存储？保存时自动建一个 debug.log 文件？
我这边没法重现你说的生成　debug.log 文件

而且我的代码里生成的日志文件都是放在数据目录里(关于界面上有提示日志路径)，不会放在第三方存储的位置

我的代码里也没有起名叫 `debug.log` 这个文件名

**Comment by ghost** [comment]
直接关联markdown打开的，没有使用第三方存储，用的本地存储，不是保存的时候创建。
直接通过文件关联打开就会出现这个log文件，我录了一个gif，有图有真相
http://wx1.sinaimg.cn/large/790f0ea7gy1fha6p247b5g21hc0u0kjl.gif

我去我同事的电脑上试了下，他的没有这个问题orz，他也是win10的。

**Comment by ghost** [comment]
刚刚我将软件卸载重装到了d盘，貌似问题就解决了

**Comment by suziwen** [comment]
感觉像是中毒，小书匠 exe 被感染的样子。
解决了就好。
