### ISSUE TITLE
输入文字是反映特别慢

### ISSUE THREAD

**Issue by eesuik** [suziwen/markdownxiaoshujiang#448]
在写文字时从输入法选择文字完毕，到编辑区的拼音变成汉字，时间特别慢，感觉延迟要5秒钟上下。
特别是想删除东西的时候，经常删过头。
完全体验不到流畅的感觉，特别影响思路。

**Comment by suziwen** [comment]
当前使用的内置编辑器是什么？文章语法很复杂？还是内容很多？

切换其他编辑器呢？
![image](https://user-images.githubusercontent.com/57370/27868359-1d25a03e-6162-11e7-93b1-5c3862dbb581.png)

**Comment by eesuik** [comment]
不好意思， 反馈慢了，重启机器后速度起来了。
或许是受到其它程序影响
