### ISSUE TITLE
印象笔记授权

### ISSUE THREAD

**Issue by kehuantiantang** [suziwen/markdownxiaoshujiang#449]
您好我想问一下，mac客户端Version 3.1.1 (3.1.1) 中和印象笔记同步，需要进行印象笔记token授权，这个token是S开头的么？只需要填写“S:=”这个token就行了么？为什么我输入的token提示授权完成，但是他另存为的时候，还是会出现，加载出现错误{"code":1006,"error":{}}

**Comment by suziwen** [comment]
token 是那个　S开头的一串.

感觉像是小书匠客户端不能正确访问到　evernote 的网站，确认下是否有什么防火墙之类的软件限制了小书匠访问外网？

**Comment by kehuantiantang** [comment]
您好，我测试了一下其他的仓库，
- github能够正常的push文本，
- 印象笔记的网页和他的网页文本编辑能够正常打开，
- 重新generate token，继续提示{"code":1006,"error":{}},
- 使用网页版的小书匠能够正常和印象笔记对接读取我的笔记本
- 使用sublime3进行印象笔记的提交，使用相同token，可以提交笔记到印象笔记笔记本中

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/27895307-76b06452-61d7-11e7-900a-9d3133220323.png)


[patch.zip](https://github.com/suziwen/markdownxiaoshujiang/files/1126727/patch.zip)

--------------

或者等下一个客户端版本，到时把落掉的错误提示调整下。

**Comment by kehuantiantang** [comment]
您好，掉落的错误是
```javascript
加载出现错误{"code":1006,"error":"Invalid DataView length undefined"}
```
无论是evernote international 还是印象笔记都是这个错误

**Comment by suziwen** [comment]
在编辑器里输入
```
<iframe src="https://www.evernote.com" nwfaketop></iframe>
```
然后预览窗口里能看到 evernote 页面吗？

或者
```
<iframe src="https://app.yinxiang.com" nwfaketop></iframe>
```

![image](https://user-images.githubusercontent.com/57370/27897291-f76702ba-61e4-11e7-826e-9456d339f02c.png)

**Comment by kehuantiantang** [comment]
嗯，两者都可行，能够显示frame
<img width="1091" alt="2017-07-06 1 49 53" src="https://user-images.githubusercontent.com/5328587/27897406-ba7d307c-6252-11e7-99cf-940f00f1a73e.png">

**Comment by kehuantiantang** [comment]
<img width="1091" alt="2017-07-06 1 49 53" src="https://user-images.githubusercontent.com/5328587/27897406-ba7d307c-6252-11e7-99cf-940f00f1a73e.png">

**Comment by suziwen** [comment]
evernote 提供的js 包是通过 http 请求，而不是 https。看起来像是你的网页有被劫持串改了。

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/27898606-4f739408-61ec-11e7-9d17-d40825fa2a67.png)
[patch1.zip](https://github.com/suziwen/markdownxiaoshujiang/files/1126915/patch1.zip)

**Comment by kehuantiantang** [comment]
确实是网页被劫持了
```javascript
加载出现错误{"code":1006,"error":"read ECONNRESET"}

// 之后重新拉取，继续出现
{"code":1006,"error":"Invalid DataView length undefined"}
```
我使用远程网络相同的token，可以正常拉取，请问有什么比较好的解决方法么？

**Comment by suziwen** [comment]
用那个 patch1.zip 改成 https 请求也不行？

**Comment by kehuantiantang** [comment]
不行的，出现了这个错误
```javascript
加载出现错误{"code":1006,"error":"read ECONNRESET"}

// 之后重新拉取，继续出现
{"code":1006,"error":"Invalid DataView length undefined"}
```

**Comment by suziwen** [comment]
那估计只能用代理了。或者换个其他网络环境。
不过比较奇怪的是 https 直接截断的话，那你 mac 下印象笔记自己的客户端能正常使用？

**Comment by kehuantiantang** [comment]
嗯，是的，正常使用mac印象笔记，evernote-sublime插件，印象笔记正常提交，正常读取

**Comment by suziwen** [comment]
你那网络是直接连接运营商还是公司路由？切换其他网络呢？

要是有网络流量监控软件，看看数据怎么流转的话，就比较好分析为什么 evernote-sublime/evernote app 可以用，而小书匠不可以。

如果没有更多分析数据，暂时没有比较好的解决思路。:frowning_face:

**Comment by kehuantiantang** [comment]
好的，晚上我抓个包来看看
