### ISSUE TITLE
文档列表的图标有什么含义吗

### ISSUE THREAD

**Issue by icycandy** [suziwen/markdownxiaoshujiang#45]
小书匠的默认图标是"记事本"，evernote笔记的图标是"home"。我没绑定github，所以不知道github笔记的图标长什么样子。

如果有含义，是否可以把evernote笔记的图标改成evernote的icon；github笔记的图标用github的icon。

**Comment by suziwen** [comment]
github的图标是github
dropbox的图标是dropbox
印象笔记的图标是大象
evernote的图标是home
当时由于印象笔记和evernote的正方形logo都一样，为了区分，就直接把evernote的图标用home来代替了。
等做好新的图标会更新的。

**Comment by icycandy** [comment]
明白了

**Comment by suziwen** [comment]
web版重新换了一套图标。
