### ISSUE TITLE
Ubuntu 16.04下 无法导入本地markdown文件

### ISSUE THREAD

**Issue by blurm** [suziwen/markdownxiaoshujiang#450]
Ubuntu 16.04
小书匠 3.1.1

打开导入窗口，选择本地文件之后，点击“确定”没有反应。
相同文件在网页版可以顺利导入。

**Comment by blurm** [comment]
另外，本地导入前几天是可以用的，今天突然就不灵了

**Comment by suziwen** [comment]
如果你进行了本地绑定，并且导入的文件与本地绑定同一个路径下，就会有这样的错误。试着导入其他路径下的文件，或者取消本地绑定（这里的取消不是取消选择，是在绑定界面里把本地绑定删除），就能成功使用本地导入。

**Comment by blurm** [comment]
可行！现在可以了。

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v3.2.0
