### ISSUE TITLE
代理设置

### ISSUE THREAD

**Issue by edocevol** [suziwen/markdownxiaoshujiang#452]
能不能加一个代理设置

公司网络环境，图床不能绑定

**Comment by suziwen** [comment]
这个以前有想过，后来鉴于 node 各种依赖包网络请求不一样，nodejs 没有统一的设置代理接口，就暂时放着了。再加上这个功能当时觉得应该要求不高。
#51 #139 #234

**Comment by edocevol** [comment]
公司网络设置了限制，图床设置不了，可以把一点加一下就帮了

**Comment by qingyuanxingsi** [comment]
Evernote同步强烈希望能够加一个**代理设置**，拜谢。

**Comment by Cpresident** [comment]
楼上+1

今早也是，evernote连接不上显示

> 加载文件列表出现错误{"code":1006,"error":"Invalid DataView length undefined"}

但对第三方应用挂了代理就好了

**Comment by suziwen** [comment]
6.7.0 版本已经提供代理设置功能

http://soft.xiaoshujiang.com/download.html
