### ISSUE TITLE
打开小书匠直接死机

### ISSUE THREAD

**Issue by tanwen19932** [suziwen/markdownxiaoshujiang#453]
## 问题描述
不知道怎么回事，正常编辑 ctrl+Q退出后程序未退出，屏幕有一小块小屏显示，然后直接死机，之后打开小书匠则死机
## 环境
MACOS 10.12.5 (16F73)

**Comment by suziwen** [comment]
通过其他编辑器创建一个普通的文件 `aa.md`

然后 
![image](https://user-images.githubusercontent.com/57370/27981964-457e415c-635c-11e7-9539-4a272c030015.png)

-------------------
或者把数据文件目录临时转移下

```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```
