### ISSUE TITLE
codemirror vim 普通模式下 “ctrl+r 撤销修改” 表现为 “插入水平线”

### ISSUE THREAD

**Issue by blurm** [suziwen/markdownxiaoshujiang#454]
小书匠3.2.0和3.1.1都是这样
Ubuntu 16.04

应该保留vim普通模式下的撤销快捷键，现在ace编辑器就是这样的，codemirror应该和其保持一致。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
