### ISSUE TITLE
关于实时预览的渲染速度

### ISSUE THREAD

**Issue by zhouzongyan** [suziwen/markdownxiaoshujiang#456]
作为一个md重度用户，每次编辑时，预览效果都要等一两秒才有更新，尽管就十几个汉字，每次编辑都特别纠结，总感觉像一卡一卡的，功能可以少，但是一定要流畅啊！

**Comment by suziwen** [comment]
这个系统特意设计成这样的。
连续输入，只会在最后一次输入后延迟一秒触发预览。

目前感觉不会太快，也不会太慢，所以暂时不想修改这个值。
