### ISSUE TITLE
[bug] 手动添加链接图标后，后续自动粘贴图标会把手动的都去除掉

### ISSUE THREAD

**Issue by zzczx** [suziwen/markdownxiaoshujiang#457]
因为文章没有保存意外退出，之前的一些图片已经保存到七牛图床上，但是markdown里面没有相应内容。
于是手动添加引用：如 ![][12]     ,  [12]: http://xxxxxxxxxxxxx/bbb.jpg,  [13] ..........一直到[15]编号。
后面再通过截图粘贴方式添加图片时，小书匠会自动把[12].~[15]的编号删除，然后把新粘贴的图片上传到图床，然后从[12]开始编号。。

请教改如何解决。

**Comment by suziwen** [comment]
你把你的 [11], [12], [13] 的链接贴一下，感觉有特殊的符号，引起系统编号错误。如果是自己贴的链接，要注意有些特殊符号可能需要编码。

也可以在工具栏里点击粘贴图片，然后在输入框里输入七牛的地址，确定。这样系统就会进行自动编码。

**Comment by zzczx** [comment]
从9开始的链接。  
[9]: http://oslgbvfr8.bkt.clouddn.com/1499244896064.jpg
  [10]: http://oslgbvfr8.bkt.clouddn.com/1499311455547.jpg
  [11]: http://oslgbvfr8.bkt.clouddn.com/1499311692119.jpg
  [12]: http://oslgbvfr8.bkt.clouddn.com/1499311873382.jpg
  [13]: http://oslgbvfr8.bkt.clouddn.com/1499312193206.jpg
  [14]: http://oslgbvfr8.bkt.clouddn.com/1499312326574.jpg  
  [15]: http://oslgbvfr8.bkt.clouddn.com/%E5%B0%8F%E4%B9%A6%E5%8C%A0/1499672955851.jpg
  [16]: http://oslgbvfr8.bkt.clouddn.com/%E5%B0%8F%E4%B9%A6%E5%8C%A0/1499676604333.jpg
  [17]: http://oslgbvfr8.bkt.clouddn.com/%E5%B0%8F%E4%B9%A6%E5%8C%A0/1499676961828.jpg





zzczx@163.com
 
发件人： 苏滋文
发送时间： 2017-07-10 21:04
收件人： suziwen/markdownxiaoshujiang
抄送： zzczx; Author
主题： Re: [suziwen/markdownxiaoshujiang] [bug] 手动添加链接图标后，后续自动粘贴图标会把手动的都去除掉 (#457)
你把你的 [11], [12], [13] 的链接贴一下，感觉有特殊的符号，引起系统编号错误。如果是自己贴的链接，要注意有些特殊符号可能需要编码。
也可以在工具栏里点击粘贴图片，然后在输入框里输入七牛的地址，确定。这样系统就会进行自动编码。

**Comment by suziwen** [comment]
还是没法重现 :frowning_face:

发一份能够重现的 markdown 文件内容

**Comment by zzczx** [comment]
我使用工具栏的插入图标也是会导致手工填写的链接没掉。



zzczx@163.com
 
发件人： 苏滋文
发送时间： 2017-07-11 20:34
收件人： suziwen/markdownxiaoshujiang
抄送： zzczx; Author
主题： Re: [suziwen/markdownxiaoshujiang] [bug] 手动添加链接图标后，后续自动粘贴图标会把手动的都去除掉 (#457)
还是没法重现 ☹️
发一份能够重现的 markdown 文件内容

**Comment by zzczx** [comment]
有收到我的markdown文件吗？

**Comment by suziwen** [comment]
没有，
你直接把 markdown 文件发到我邮件 suziwen1#gmail.com 或者直接上传貼到这个 issue 下， 不要通过 github 的邮件系统发附件，会收不到附件的。

**Comment by suziwen** [comment]
把文件里的 `![11]` 改成 `![][11]`， `![12]` 改成 `![][12]` 等.

`![11]` 这个是新语法，上次升级 markdown 解析器后有的。但一些快捷键，图片粘贴的处理逻辑没有跟着修改更新引起的。

**Comment by zzczx** [comment]
done。
多谢了。



zzczx@163.com
 
发件人： 苏滋文
发送时间： 2017-07-19 11:22
收件人： suziwen/markdownxiaoshujiang
抄送： zzczx; Author
主题： Re: [suziwen/markdownxiaoshujiang] [bug] 手动添加链接图标后，后续自动粘贴图标会把手动的都去除掉 (#457)
把文件里的 ![11] 改成 ![][11]， ![12] 改成 ![][12] 等.
![11] 这个是新语法，上次升级 markdown 解析器后有的。但一些快捷键，图片粘贴的处理逻辑没有跟着修改更新引起的。
