### ISSUE TITLE
无法保存到印象笔记上

### ISSUE THREAD

**Issue by Maipiao** [suziwen/markdownxiaoshujiang#458]
第一个问题是，已经绑定好印象笔记。并在数据中选中。之后也可以读取到相关目录。但是用小书匠新建一篇markdown，在进行保存的时候，选择印象下面的目录。一直显示保存中………然后过了很久没有反应，'保存中……'消失。也没有保存上。不知道是什么原因，已经换了教室和宿舍两个地方的网络进行测试。电脑是win10，小书匠版本是最新的3.2，64位
第二个问题是：想问一下，用印象笔记新建的普通笔记，在小书匠里面可以打开吗？目前打开普通笔记是没有排版的。不知道是不是不兼容还是打开方式不对。希望可以帮忙解答一下，谢谢！

**Comment by suziwen** [comment]
1. 有没有自定义 css？看一下关于界面里指定的日志文件，有什么信息显示？再一个是不是有其他软件限制了网络？
2. 可以打开，不过小书匠会尝试将印象笔记里的 html 软件成 markdown 格式。
