### ISSUE TITLE
MAC下小书匠无法保存图片

### ISSUE THREAD

**Issue by wxyyxc1992** [suziwen/markdownxiaoshujiang#46]
MAC下小书匠无法保存图片 想问下直接截图然后粘贴进去这部分图片是放在浏览器缓存里吗？这部分一旦把文章在小书匠里面删除就没了。我想另存为或者保存都说Error 文件无法找到。我想知道那个自动的路径 ./images/xxxxx.jpg是指向的哪个文件夹啊。

**Comment by suziwen** [comment]
无法保存图片是指保存到本地吗？
直接截图然后粘贴进去这部分图片是放在浏览器数据库里的，想要拿到图片，可以使用导出功能，导出html文件的话，图片会直接内嵌到html里。导出zip的话，图片就会包含在zip文件里。
如果想保存md文件时同时保存出图片，可以使用绑定本地文件系统，这样md文件保存时，会把相关的附件保存到当前文件相对的路径下。

**Comment by suziwen** [comment]
嗯，现在的版本确实有一个bug。

**Comment by wxyyxc1992** [comment]
非常感谢楼主作答

**Comment by wxyyxc1992** [comment]
建了一个images目录 但是还是报错 是ENOENT的错误，提示找不到images/目录

**Comment by suziwen** [comment]
要保存的文件的同一级目录下创建`images`文件夹
比如你的文件保存到`{...}/aa/bb/cc.md`，那吗创建的images文件夹为`{...}/aa/bb/images`
下个版本会修复这个问题，用户不用自己创建。

**Comment by wxyyxc1992** [comment]
嗷嗷 多谢多谢 不知道下一个版本啥时候发布？

**Comment by wxyyxc1992** [comment]
另外有一个小疑问啊 譬如在MAC下面直接打开某个文件，然后直接保存的话并不能直接保存到这个文件，需要另存为才行。

**Comment by suziwen** [comment]
你应该不是关联打开的，而是直接把文件拖动到编辑区里，然后修改保存？现在拖动文本文件到客户端还只是把它当做导入来处理。所以保存时，不会关联保存本地文件。想要关联的话，直接右键文本文件，选择通过`小书匠`程序来关联打开，这样操作的文件直接保存本地。

**Comment by suziwen** [comment]
1.5.0 修复
http://soft.xiaoshujiang.com
