### ISSUE TITLE
腾讯云怎么也连不上

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#461]
腾讯云oss的服务怎么也验证不通过，可否有个教程，我七牛云可以用？

**Comment by suziwen** [comment]
我这边没有问题的，确认一下你的 “云对象存储” 是 `v4` 版本吗。我新创建的帐号只能使用 v4， 所以没办法开发以前老的 v3 版本。

![image](https://user-images.githubusercontent.com/57370/28253694-0a3748c0-6a6c-11e7-8a29-9a51405cd4b9.png)

**Comment by CharMingF** [comment]
是v4的，老验证不过去，密钥api有个这个说明，是不是这个啊？
使用 云 API请在调用前使用 API 密钥获取签名， 否则将无法调用 API，详见鉴权签名算法。

**Comment by suziwen** [comment]
![screenshot_2017-07-18_19-55-03](https://user-images.githubusercontent.com/57370/28316565-f2c5bc12-6b88-11e7-9be4-973326319b2c.png)
![screenshot_2017-07-18_20-04-34](https://user-images.githubusercontent.com/57370/28316572-f6d57a68-6b88-11e7-8f30-83b03d23f767.png)
![screenshot_2017-07-18_20-08-09](https://user-images.githubusercontent.com/57370/28316576-fb687576-6b88-11e7-80cd-d5056985687a.png)
![screenshot_2017-07-18_20-13-48](https://user-images.githubusercontent.com/57370/28316580-002b36fc-6b89-11e7-9d6b-758475e9d51c.png)

**Comment by CharMingF** [comment]
谢谢，耐心回复。不过还是不行，我还是用其他吧。按照你的操作，保证没有问题。但是还是！

上传资源失败:
绑定认证失败:上传资源失败:
验证用户失败，请确认token是否有效

**Comment by edocevol** [comment]
![image](https://user-images.githubusercontent.com/9777120/31441881-1c86e4c8-aec7-11e7-8595-49c9b2a5ac8e.png)

**Comment by CharMingF** [comment]
看来不是我的问题。

**Comment by suziwen** [comment]
在腾讯云的基础配置里，把跨域打开

![screenshot_2017-11-16_14-18-28](https://user-images.githubusercontent.com/57370/32876858-b5608dba-cad9-11e7-8587-efc55cb9e405.png)
