### ISSUE TITLE
保存到印象笔记的问题

### ISSUE THREAD

**Issue by imndd** [suziwen/markdownxiaoshujiang#462]
在小书匠里编写的文章，同步到印象笔记的时候会自动带上.md附件，怎么不要这个附件

**Comment by suziwen** [comment]
这个暂时没有选项可以去掉。

小书匠系统用这个附件来进行双向同步用的。如果保存到印象笔记里的文章没有修改，并且有这个附件，小书匠再次拉取时会还原这个 md 附件，否则就尝试使用 html 转换成 md 格式的内容。
