### ISSUE TITLE
全局搜索

### ISSUE THREAD

**Issue by kehehee1** [suziwen/markdownxiaoshujiang#464]
有没有全局搜索功能呢，有很多文档，查找资料不是很方便

**Comment by suziwen** [comment]
这个文档包按钮![image](https://user-images.githubusercontent.com/57370/28253772-9e3903ba-6a6c-11e7-8796-61ad4387d7aa.png) , 点击后，
![image](https://user-images.githubusercontent.com/57370/28253785-b318d954-6a6c-11e7-8d4d-0c39e4bf5a1b.png)
