### ISSUE TITLE
代码显示字体如何更改

### ISSUE THREAD

**Issue by wowforestwow** [suziwen/markdownxiaoshujiang#467]
我的小书匠升级版本之后，代码显示的字体发生了变化，请问代码字体如何修改回原来的样子。。。。。。
或者如何调节代码显示字体

**Comment by suziwen** [comment]
最好给出个截图哪个区域的字体，编辑区？预览区？还是导出的  html 字体？等等

设置里可以自定义 css 或者单独设置字体

**Comment by wowforestwow** [comment]
更新版本后的代码字体格式![default](https://user-images.githubusercontent.com/13028764/28371218-f5e56f2c-6cce-11e7-9a54-8b064f128120.png)
原来老版的代码字体格式
![default](https://user-images.githubusercontent.com/13028764/28371296-26333740-6ccf-11e7-9314-65c163b75b09.png)
字体好像变粗了，请问怎么单独设置字体，我想要原来的字体粗细

**Comment by wowforestwow** [comment]
最好能够给我一个参数设定的具体形式样例，我对css不是特别了解

**Comment by suziwen** [comment]
你是从哪个版本升级到哪个版本？
操作系统等也升级了？
你在`设置 > 基本>预览区代码高亮样式` 里选择 `solarized_dark` 样式呢？

![image](https://user-images.githubusercontent.com/57370/28374396-36bc07c8-6c6a-11e7-9569-17b9c2dd5c8b.png)

**Comment by wowforestwow** [comment]
我的操作系统一直是ubuntu 16.04
原来版本记不得太清楚了　　新版本主要是字体大小改变了。。。。

我电脑里，root用户下，还有一个1.10版本，打开字体和原来依旧一样，就是最新版本字体变粗了。。

**Comment by wowforestwow** [comment]
不是样式的问题，是字体大小变化的问题

**Comment by suziwen** [comment]
1.* 版本 全局 body 字体是 1.15em,  新版本我把它改成 18px了。然后代码块是 90%;


你可以自定义 css，来强制修改代码块字体的大小 。

``` css
body code, body .xiaoshujiang_code
{
font-size: 14px;
}
```

**Comment by wowforestwow** [comment]
感谢，就是这个问题

**Comment by wowforestwow** [comment]
再咨询一个小问题，为什么现在c++代码，＃include<xxxx> 没有单独颜色显示，1.x和2.x版本都是红色标记，3.x就没有特殊颜色标记，能不能把这个功能也复原一下下，或者是否有命令可以调节一下。

**Comment by suziwen** [comment]
这个应该是我 highlightjs 升级时，部分 css 文件没替换完整引起的。

你可以在`设置>基本>预览区代码高亮样式` 里选择第一项 `禁用代码高亮样式`。 然后再自定义 css 里添加想要的 css 样式  https://github.com/isagalaev/highlight.js/tree/master/src/styles

样式的效果可以在 https://highlightjs.org/static/demo/ 这里查看到.

------

比如 把 https://github.com/isagalaev/highlight.js/blob/master/src/styles/solarized-light.css 这个文件里的内容粘贴到全局自定义 css 里，就跟选择 solarized-light 效果一样了。

**Comment by sfon** [comment]
麻烦问一下，预览区的字体大小和行高怎么设置？谢谢

**Comment by sfon** [comment]
我想把预览区的普通文字的字体大小调小，不是代码字体的大小

**Comment by sfon** [comment]
不好意思，自己捣鼓了一下问题解决了：
body code, body .xiaoshujiang_code
{
font-size:15px;
line-height:1.5em;
}
body{
font-size:15px;
line-height:2em;
padding:1em;
margin:auto;
}
h1, h2, h3, h4, h5, h6 {
	font-weight: bold;
}

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布

**Comment by howfars** [comment]
请问我的代码块当中的字体为什么是这样
![default](https://user-images.githubusercontent.com/24860642/39858667-d2092f0c-5469-11e8-86f7-e5530005ea0c.png)
如何修改为非衬线字体呢

**Comment by suziwen** [comment]
@howfars 类似这样

``` css
body code, body .xiaoshujiang_code
{
font-family: "Microsoft YaHei";
}
```
