### ISSUE TITLE
chrome web端，可以直接粘贴图片。而win版客户端却不可以。。。。

### ISSUE THREAD

**Issue by alexzeng2014** [suziwen/markdownxiaoshujiang#469]
希望尽快修复，这个功能很重要！

**Comment by suziwen** [comment]
我这边  window 客户端可以。最好给出些详细信息。

**Comment by alexzeng2014** [comment]
例如，你直接对着图片右击复制，然后到web端粘贴，这时图片可以被粘贴进来，不管是七牛还是小书匠的图床。但是在win客户端就不行了。。。

**Comment by suziwen** [comment]
最好能提供一些更详细的配置信息（比如版本，什么内置编辑器，打没打开 vim 等模式），操作系统一些参数等 等 ，我这边没法重现你的情况，就很难着手处理。
