### ISSUE TITLE
[Windows][多語言]Win7 台灣繁體環境下安裝包亂碼

### ISSUE THREAD

**Issue by SunHubert** [suziwen/markdownxiaoshujiang#473]
Win7 **台灣繁體** 環境下安裝包亂碼，雖然不影響使用，但體驗不好。

![20170724101826](https://user-images.githubusercontent.com/30365295/28505929-31765ef0-705a-11e7-93d9-a282df5f400d.png)

![20170724101839](https://user-images.githubusercontent.com/30365295/28505930-33bff0d6-705a-11e7-87b4-32582e59dc93.png)

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
