### ISSUE TITLE
Ctrl+S 快捷键不起作用？

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#476]
@suziwen 本来以为不能保存文档的，后来试了左上角的**保存**按钮是正常的，所以可以确定是快捷键不起作用。

已经退出大多数软件进行排除快捷键冲突

**Comment by ghost** [comment]
小书匠重装过了

**Comment by suziwen** [comment]
#394 

很奇怪，我这边一直没法重现这个情况。

**Comment by ghost** [comment]
我也提供不了更多信息了，因为也只有 ctrl + s不起作用，其它的 ctrl +k/+i/+b 好好的。如果说环境变过的话也就因为win 10前面改成 **开发者** 模式，升级成**预览版**，后来又关掉了，现在系统应该还是预览版的。

**Comment by siqiniao** [comment]
同样遇到这个问题，已经重新安装过，还是不行

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
