### ISSUE TITLE
Could not display "Story-writer"

### ISSUE THREAD

**Issue by zmcui** [suziwen/markdownxiaoshujiang#477]
download Story-writer-linux64.zip on ubuntu 1404 and then extract
when double click Story-writer， prompt as
-------------------------------
Could not display “Story-writer”.
There is no application installed for “shared library” files.
Do you want to search for an application to open this file?

**Comment by suziwen** [comment]
```
cd {story-writer's path}
chmod +x Story-writer
./Story-writer
```

**Comment by zmcui** [comment]
可以在命令行打开
更改权限之后， 也不能双击图标打开么？

**Comment by suziwen** [comment]
我这边的 ubuntu 14.04 双击打开没问题。如果你的命令行能打开，那问题可能跟你的环境配置有关了。

**Comment by zmcui** [comment]
这个问题我补充一下， 下载的release版本解压到本地， 小书匠的文件类型是共享库， nautilus无法识别程序
Story-writer: application/x-sharedlib; charset=binary
参考 https://groups.google.com/forum/#!topic/nwjs-general/2bnKU8dYZrA/discussion 暂时workaround这个问题
 @suziwen下次发布版本能不能把编译的程序类型改成application/x-executable
谢谢
