### ISSUE TITLE
我又遇到发布wordpress错误了

### ISSUE THREAD

**Issue by harry10086** [suziwen/markdownxiaoshujiang#478]
显示：
发送失败：Error: Unknown XML-RPC tag 'TITLE'

本来想找log，但电脑里没搜到这个 story_exceptions.log 
用户名密码网址都没问题，用word是连接正常的

**Comment by suziwen** [comment]
你的 blog  ,metaWebblog 版本是多少？ wordpress 版本是多少或者是什么类型的博客？

**Comment by harry10086** [comment]
我的wordpress是中文4.8版本，我刚刚试用了下WordMark这个软件，同一篇文章，地址账号密码设置也一样，成功发布了。
metaWebblog 版本这个我就不知道了。

**Comment by suziwen** [comment]
我安装了 官方的 docker 版 wordpress 4.8 ， 没有出现类似的错误。 :frowning_face:

**Comment by harry10086** [comment]
我的设置如下，有没有哪里不对：
![image 1501940739](https://user-images.githubusercontent.com/8612989/28995889-7ff5cec2-7a27-11e7-9974-58cc73a49aba.png)
这个网站我用word发布正常，用另一个软件WordMark发布也正常。
之前我卸载了重装过，删除了数据，还是不行。
我把c盘格式化重装了系统，刚刚安装小书匠，还是不能发布，2.*版本的时候我发布文章正常的。
我的网站也没什么特别的设置，想不通

**Comment by suziwen** [comment]
你使用的是哪个服务提供商的 wordpress? 安装了哪些插件？

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
