### ISSUE TITLE
linux64位版本插入当前时间快捷键ctrl+.无效,即使勾选了默认设置

### ISSUE THREAD

**Issue by sfon** [suziwen/markdownxiaoshujiang#479]
linux64位版本插入当前时间快捷键ctrl+.无效,即使勾选了默认设置.
另外插入视频/插入音频/插入链接的快捷键也是无效的.感谢并加油~

**Comment by suziwen** [comment]
我这边 linux64 版本，插入当前时间等快捷键没有出现你说的无效情况。最好能提供一些更详细的配置信息（比如版本，什么内置编辑器，打没打开 vim 等模式）

**Comment by sfon** [comment]
我的系统是CentOS7.2,桌面环境是XFCE,刚刚检查了一下,桌面环境没有快捷键冲突,无论是否选择vim模式,ctrl+.都无效,而且我发现问题在于[设置为默认格式]这个选框设置失效,勾选之后点击确认能成功插入当前时间,但是快捷键用不了,再用鼠标点击进入设置,那个选框是没有被选上的,是我设置的问题?

**Comment by suziwen** [comment]
`设置为默认格式` ,每次打开时间设置界面都会置空。
选中 `设置为默认格式` ，确定后，下次打开时间设置界面时，时间输出格式的下拉选项会选中上次被选中的项。如果不选中 `设置为默认格式`，确定后， 当前下拉选项的时间格式项不会做为默认格式。

-------------------------------------
我这边是 fedora 25 , xfce 环境，没有出现你说的快捷键不生效的问题 :frowning_face:

**Comment by sfon** [comment]
我确认设置是没有问题的,我尝试了其他按键,惊奇地发现ctrl旁边的`[windows]键+.`能插入当前时间,然后键盘上有个[锁定windows]键,锁定之后`ctrl+.`就生效了.怎么说呢,虽然不知道为什么但是问题解决了.
不过插入图片/视频/音频快捷键依然无效,不过我的需求不大.
感谢并加油~
