### ISSUE TITLE
打开新文件后，焦点没有在文件上

### ISSUE THREAD

**Issue by icycandy** [suziwen/markdownxiaoshujiang#48]
五个问题:
* 鼠标点击打开新文件后，还需要鼠标在编辑器中点击一下才能开始写；点击`开启写作模式`之后，也是一样，焦点没有在文件上，需要鼠标再点击一下才能开始写。这个焦点问题，不同的人可能有不同的习惯。像我说的这种方式不一定所有人都喜欢，只是个小建议。
* vim模式，进入`开启写作模式`后，vim进入`插入模式`，此时按esc，会先退出`写作模式`
* vim模式下不支持 `ctrl`-`f`和`ctrl`-`b`前后翻页
* 在列表环境中，按回车时，会出现下一个列表头，比如`* `，此时再按回车，建议清除此列表头。每次都要手动删除，挺麻烦的
* ~~不喜欢写作模式下，背景半透明。期待有像github一样的全屏功能~~ 摸索了半天，发现怎么用单栏了。。。

**Comment by suziwen** [comment]
1. 这个可以改下，其实还有个得改进的地方就是文件切换时，文件焦点的位置都默认重置到开头，好一些的做法是上次文件打开时焦点在第几行，重新打开时还是在第几行。一直想改来着。
2. 3. 嗯，vim模式下有比较多的按键冲突。
4. 这个是ace编辑器默认的行为，我研究下看好不好实现。你说的那种方式在轻量编辑器里是实现的。只是推荐使用ace编辑器，因为轻量编辑器在处理文件内容比较多的时候，会有性能问题。
5. 想实现个设置，可以控制全屏时是否显示背景图片等。

**Comment by suziwen** [comment]
- [x] 鼠标点击打开新文件
- [ ] 目前web端无法实现。全屏后，esc键被浏览器控制了，浏览器由于安全需要，不让代码控制esc。变通的解决方法是使用 `ctrl+[`键，标准的vim里也是可以通过该键退出`insert`模式的，只是操作上可能不太习惯。
- [x] vim模式下不支持 ctrl-f和ctrl-b前后翻页
- [x] web版现在已经实现，不过将来可能还会再改成ace的markdown模式。
- [x] 现在`设置`的`全屏`里可以控制是否显示背景图片等。

**Comment by icycandy** [comment]
测试了一下，还有个小问题。设置全屏宽100%和高100%时，文档底部有内容无法显示完全。

**Comment by suziwen** [comment]
多谢提醒，已修复。

**Comment by icycandy** [comment]
赞！

**Comment by icycandy** [comment]
和问题4类似 

> 在列表环境中，按回车时，会出现下一个列表头，比如*，此时再按回车，建议清除此列表头。每次都要手动删除，挺麻烦的

此时如果按tab，可否让列表增加一级？

**Comment by suziwen** [comment]
列表增加一级?不是很明白.
指的是我按 `tab` 后,那空行就变成 `- ` 这样的?

**Comment by icycandy** [comment]
比如我已经输入了两个一级的item，这个时候按回车，会出现第3个一级item
```
* list 1
* list 2
* 
```
在这个情况下：
* 如果按回车，会删掉第3个item，这个功能目前已经实现了
* 如果按tab，则把一级列表变成第二级列表，即把星号*往后移，这个目前没有实现
```
* list 1
* list 2
    * 
```

**Comment by suziwen** [comment]
最新web版可 以看下效果,不过跟`轻量编辑器`的一些操作在小细节上还是有些不同.

**Comment by icycandy** [comment]
Chrome和IE 11下好了，Firefox下有问题。

**Comment by suziwen** [comment]
好了.

**Comment by icycandy** [comment]
Firefox测试OK
