### ISSUE TITLE
快捷键冲突问题 && 按钮无法点击

### ISSUE THREAD

**Issue by jeferwang** [suziwen/markdownxiaoshujiang#480]
`ctrl+shift+左箭头`在编辑器里是选定文本 , 和隐藏左栏的快捷键冲突

绑定Evernote之后 , Evernote条目的设置按钮不能点击

**Comment by suziwen** [comment]
2. 临时解决方法: 可以重启小书匠，再点击那个设置按钮。

**Comment by jeferwang** [comment]
还有ctrl+左右箭头的快捷键，能否改成自行设置的，在codemirror编辑器有这个问题，改成ace就正常了 @suziwen

**Comment by suziwen** [comment]
自定义快捷键功能是有想做，只是现在代码上还没想好怎么设计切入。再加上这块感觉也不是主要需求，就一直放着没动。

**Comment by epluguo** [comment]
同意，这个我以前也提过，Ctrl + Left arrow，这几个是选择文本，跳过文本的，各个文本编辑器都这样，也使用习惯了，现在和隐藏左栏的快捷键冲突，用不了，这点很不习惯
