### ISSUE TITLE
建议支持跳转至目录或者自定义位置的【锚点】

### ISSUE THREAD

**Issue by focuszane** [suziwen/markdownxiaoshujiang#488]
这对于保存在印象笔记之类的存储中，目录 [toc] 较长的文章来讲，【PS：印象笔记不支持大纲视图】，迅速的双向锚点定位很是方便，就像这张图里的描述：
![default](https://user-images.githubusercontent.com/30841078/29086401-083804e2-7ca5-11e7-94e8-562e3da1f7bd.png)

**Comment by suziwen** [comment]
## 默认的语法里可以这样写
```
## asdfasf<!--{#asd}-->

aaaaaaa
aaaaaaa

aaaaaaa

aaaaaaa

asdfsdf[回到目录](#asd)
```
-----------------------------
## 如果想要用你提供的示例语法的话，可以这样配置扩展语法

语法设置里打开 `html 属性配置(attrs)` 关掉 `html 属性配置(decorate)`, 就可以实现你想要的效果

![image](https://user-images.githubusercontent.com/57370/29597525-bfb11922-8788-11e7-8fa1-252d14879322.png)

## 注意

1. 印象笔记自身对 html 的限制, 导致 html 的锚定跳转失效，小书匠这边也就没办法在印象笔记里实现页面内的跳转。
2. 这个功能目前也只能是在小书匠预览里，或者导出 html, 导出到 github 等上可以实现跳转

**Comment by focuszane** [comment]
哦哦，看来印象笔记的阉割版 html 问题不是一天两天的了，这么多年了还是没改进，哎╮(╯▽╰)╭，也许为知笔记可以做到吧（虽然他 html 内嵌 markdown 的做法很奇怪，也是经常出 BUG），希望将来即将崛起的 Notion 可以解决我的需求吧（初见确实惊艳，可惜才开发了1年，markdown 支持很烂） ，不过还是感谢作者你的解答！
