### ISSUE TITLE
先小书匠编辑，再印象笔记编辑，再用小书匠编辑，印象笔记编辑内容不能同步

### ISSUE THREAD

**Issue by up2wing** [suziwen/markdownxiaoshujiang#49]
绑定了印象笔记，同一篇笔记，先用小书匠编辑，再打开印象笔记进行编辑，再用小书匠编辑，发现印象笔记编辑的内容不能同步。
不知道这是不是一个bug？thx。

**Comment by suziwen** [comment]
web  版本还是客户端版本？当前客户端版本会有这种情况，就是从印象笔记里导入的文件，再保存时会保存不上，临时的解决方案是从印象笔记导入想要的文件后，退出小书匠系统，再启动，文件就能保存。不知道你的情况是不是这个原因，你可以试一下。

**Comment by suziwen** [comment]
1.5.0 修复
http://soft.xiaoshujiang.com
