### ISSUE TITLE
从印象笔记打开：之前保存的 Markdown 格式在编辑区直接变为 HTML 了，排版乱成一团。

### ISSUE THREAD

**Issue by focuszane** [suziwen/markdownxiaoshujiang#490]
系统是：Windows 10 64 位。
版本：Web 版。
问题：
* 现在每次打开之前编辑好的文章（保存为Markdown到印象笔记的那些，并且保证没有在印象笔记再次编辑过），结果自带渲染样式全部内联进去了，排版乱成一团。
* 并且，不管是 Web 端还是 PC 端的Html to Markdown 功能都使用无效。
就像这样：
![1502612968 1](https://user-images.githubusercontent.com/30841078/29248185-9743f0c2-8044-11e7-8879-cf05ecf51f06.jpg)

另外：
* 我也出现【window 处理文件样式关联失败】了。
版本：最新 Windows 32位、64位的 桌面版 都试过了。

如果有办法解决，还望指点一二，谢谢。

**Comment by suziwen** [comment]
应该是你那边修改了文件，小书匠就只能尝试从 html 转换成 markdown, 而不是直接从原有的 markdown.md 文件恢复。

可以在绑定界面，印象笔记里有个保护设置，选中它，强制不允许修改

![image](https://user-images.githubusercontent.com/57370/29596572-6304cac0-8783-11e7-8280-04aed1c94b5e.png)

**Comment by focuszane** [comment]
嗯，确实可以在印象笔记中锁定该笔记（PC、IOS客户端都可以），但是还是希望能够支持双向编辑；或者从Windows端的印象笔记本地程序打开md文件后，能够对接到小书匠客户端或者Web端，然后即时编辑，不然确实比较麻烦（虽然可能是大象的通病），。不过还是感谢作者~~
