### ISSUE TITLE
保存不到为知笔记上

### ISSUE THREAD

**Issue by fsrmqi** [suziwen/markdownxiaoshujiang#491]
保存失败: {"code":1009,"error":"服务器错误","orign":"Method Not Allowed"}

**Comment by fainboy** [comment]
我也一样：

保存失败: {"code":1009,"error":"服务器错误","orign":"Method Not Allowed"}

**Comment by CharMingF** [comment]
早就出问题了

**Comment by suziwen** [comment]
window 版本的话，可以自己先替换下这个文件 `安装目录/plugins/plugins/wizv2/wiz.js`
[wiz.js.zip](https://github.com/suziwen/markdownxiaoshujiang/files/1243937/wiz.js.zip)
#459

**Comment by tsunamilx** [comment]
我是Mac系统，望早点解决 ❤️

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v4.0.0

**Comment by l1nxy** [comment]
我这边保存了，但是看不了。文档打开失败。
