### ISSUE TITLE
预览窗口怎么设置？

### ISSUE THREAD

**Issue by LinTeX9527** [suziwen/markdownxiaoshujiang#492]
需要重新打开3次，才能显示预览窗口。
第一次打开，整个软件只有一个非常小的编辑界面，预览窗口被隐藏了，设置中也没找到主动显示预览窗口的方法。
连续重启3次软件，终于显示左边的导航窗口，编辑窗口，预览窗口。
这个问题昨天发生了一次，今天又发生了一次。我才用了这个软件2天。

**Comment by suziwen** [comment]
在软件的边边有按钮可以打开预览区或者文档管理区的
![](https://cloud.githubusercontent.com/assets/57370/17221772/e633c830-54ba-11e6-9863-32366ec1fa72.png)

一般窗口最大化后，下次再打开，就会保持最大化状态。
