### ISSUE TITLE
小书匠文件保存默认的位置在哪里？

### ISSUE THREAD

**Issue by wowforestwow** [suziwen/markdownxiaoshujiang#493]
RT
我绑定了其他保存位置，可是一直找不到小书匠默认的保存位置，渴望开发者告知我一声

**Comment by suziwen** [comment]
## web 版本

浏览器提供的数据库存储

## 客户端

`关于` 界面里有显示小书匠数据库文件位置

![image](https://user-images.githubusercontent.com/57370/29597138-52d64ad6-8786-11e7-9f6b-2a947575a935.png)

**Comment by wowforestwow** [comment]
嗯嗯，您说的位置我找到了，我想表述的，比如我写了一个1.md文档，我点击左上角保存，请问我在哪里能找到１.md这个文档。我一直找不到这个保存路径在哪里

**Comment by suziwen** [comment]
如果绑定了第三方存储，点击保存(ctrl+s)按钮，会同时保存到第三方存储上，否则的话，只保存到内置的数据库里。如果不想使用第三方绑定，又想保存到外部的文件系统，第一次新建时，可以点另存为，再在弹出的界面左下角，选择本地文件系统。以后再点保存时就会同时保存到你刚指定的本地文件系统位置了。
