### ISSUE TITLE
[bug] 添加截图并上传到图床时，url没有http://

### ISSUE THREAD

**Issue by zzczx** [suziwen/markdownxiaoshujiang#495]
图床采用七牛，没有http://开头， markdown渲染后提示找不到图片。手动添加http:// 则没有问题。

**Comment by CharMingF** [comment]
这个你在图床设置的时候就需要添加完整带HTTP的域名

**Comment by suziwen** [comment]
绑定里有设置
![image](https://user-images.githubusercontent.com/57370/29597044-d1212e70-8785-11e7-9b88-b5299336d3d9.png)
