### ISSUE TITLE
客户端不能绑定印象笔记

### ISSUE THREAD

**Issue by JackSparrow52** [suziwen/markdownxiaoshujiang#497]
点击绑定印象笔记后，点击获取token没有反应。

**Comment by mymartin** [comment]
刚刚在客户端上成功绑定印象笔记，可以试试看。

**Comment by suziwen** [comment]
应该是你那边有什么其他软件，限制小书匠打开浏览器吧。
可以直接到下面的地址自己申请 token

evernote:

https://www.evernote.com/api/DeveloperToken.action

印象笔记:

https://app.yinxiang.com/api/DeveloperToken.action
