### ISSUE TITLE
客户端搜索无法高亮显示不突出

### ISSUE THREAD

**Issue by mymartin** [suziwen/markdownxiaoshujiang#499]
搜索发现，匹配到的文字很难看出来，高亮显示不是很突出。
![qq 20170822145353](https://user-images.githubusercontent.com/6276117/29552421-d384ea12-8749-11e7-8d2e-e4dc958db827.png)

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v4.0.0
