### ISSUE TITLE
添加附件的默认描述能否改为附件文件名字？

### ISSUE THREAD

**Issue by fujinggui** [suziwen/markdownxiaoshujiang#50]
添加附件的默认描述能否改为附件文件名字？ 这样就不需要每添加一个附件手动输入描述，如果附件多的话很麻烦。

**Comment by suziwen** [comment]
web已修复,可以试一下.,效果类似下图.
![a](https://cloud.githubusercontent.com/assets/57370/7983013/d8382c9c-0aee-11e5-9465-3478475e31c2.png)

**Comment by fujinggui** [comment]
我在web上用跟本地一样的，还是需要手动输入描述。是否哪里还需要配置？

**Comment by suziwen** [comment]
强制刷新一下试试,可能缓存的原因,我这边试了下web版,没问题的.
不需要另外配置.

**Comment by suziwen** [comment]
最新版本1.6.0已经实现,可以下载下来体验.
