### ISSUE TITLE
wordpress 4.8.1 发布失败

### ISSUE THREAD

**Issue by wumuzi520** [suziwen/markdownxiaoshujiang#504]
dump抓包发现返回的是下面的字符串

XML-RPC server accepts POST requests only

小书匠发布用的个GET接口哦？

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/issues/478#issuecomment-319659143

提交使用的是 post

我在官方的 4.8 docker 上是没有问题。如果能提供一些更详细的信息就好了，比如 wordpress 是否被二次修改，安装了其他什么插件？

**Comment by wumuzi520** [comment]
你发布的设置是什么样的呢？我tcpdump抓包发现小书匠发出去的是GET包

**Comment by wumuzi520** [comment]
;-. ..r.GET /xmlrpc.php HTTP/1.1
Host: izheteng.top
Connection: keep-alive
Accept: text/html, */*; q=0.01
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Comment by wumuzi520** [comment]
我用MWeb发布时正常的，他使用的是POST

**Comment by suziwen** [comment]
你的 url 地址怎么填的？
![image](https://user-images.githubusercontent.com/57370/29722649-42fbe406-8987-11e7-91f2-8cf32177771f.png)

我估计知道什么原因了，小书匠支持两种地址，`http://localhost:8880/` 和 `http://localhost:8880/xmlrpc.php?rsd`。 然后先尝试 GET 解析 xml 里的  `MetaWeblog`, 找到最后的 apilink `http://localhost:8880/xmlrpc.php`

``` xml
<api name="MetaWeblog" blogID="1" preferred="false" apiLink="http://localhost:8880/xmlrpc.php"/>
```

---------
不是 POST 直接 `http://localhost:8880/xmlrpc.php`

----------

下个版本再把这个地址加上。

**Comment by suziwen** [comment]
临时解决
你可以自己写一个 xml 文件，把这个地址放到一个静态 url 地址上，然后填写这个 url, 让小书匠解析这个 xml ,拿到 aplLink 里的地址，这样应该就能用。

**Comment by prolover** [comment]
好期待这个功能~

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v4.0.0
