### ISSUE TITLE
An invalid XML character (Unicode: 0x8) was found in the element content of the document

### ISSUE THREAD

**Issue by shatle** [suziwen/markdownxiaoshujiang#505]
绑定印象之后 ，编辑 md 文档，保存到印象时，会有字符出错，有遇到过吗

**Comment by shatle** [comment]
其它编辑器，复制过来时，会有相应的不识别编码，去掉之后就好了

**Comment by suziwen** [comment]
什么编码符号引起的？我这边可以修正下，下次遇到类似的就可以直接过滤掉。

**Comment by shatle** [comment]
错误提示据说的啊，不过在小书匠会 以一个小点 的方式显示出来
![image](https://user-images.githubusercontent.com/1129872/30172560-c2df10e4-9427-11e7-9b37-cae40efe8f19.png)
