### ISSUE TITLE
升级到3.2.0之后，在Mac上卡住

### ISSUE THREAD

**Issue by luokaii** [suziwen/markdownxiaoshujiang#506]
当打开小书匠时，暂时没有问题，点击了一篇印象笔记的文章时，顿时cpu升到96%以上，此时无法关闭小书匠，无法再进行操作，但是点开系统的强制退出，上面并未显示应用无响应，不过也只能在这里把应用关闭了。

电脑型号：MacBook pro841
小书匠版本：3.2.0

之前从未出现过这样的状况，电脑其他应用没有发现问题……

**Comment by suziwen** [comment]
用命令行关联打开一个本地的 md 文件
类似的命令

```
open -a Story-writer /home/xxxx/temp.md
```
-----------

或者转移下小书匠内置数据库
```
Mac: ~/Library/Application Support/小书匠/
```
