### ISSUE TITLE
块代码在有道云笔记显示异常的问题

### ISSUE THREAD

**Issue by yurenxiaoxiao** [suziwen/markdownxiaoshujiang#508]
我使用小书匠编辑器，在编辑时保存的块代码，同步至有道云笔记的时候显示异常，会增加很多的横线。

只有块代码会有异常，请教怎么解决这个问题呢。

**Comment by suziwen** [comment]
#377 
新版小书匠已经不支持有道了，不知道你是怎么保存的。
如果是以前版本保存成功，显示正常，最近看文章又有错误，那可能是有道对老数据格式兼容不太友好的原因。
