### ISSUE TITLE
建议增加代理

### ISSUE THREAD

**Issue by sirius60111** [suziwen/markdownxiaoshujiang#51]
编辑器很好用，但存储容易失败。绑定的国际版evernote，打开笔记速度很慢，保存也容易失败。
建议增加代理选项。另外，如果笔记保存失败的话提示不要自动消失。我点保存后就会切换到其他软件，不过因为有好几次保存失败了，现在要一直盯着直到看到保存成功的提示，sigh。。

**Comment by suziwen** [comment]
1. 代理这块目前代码上比较难统一,主要是nodejs没有提供一个全局的代理配置,需要对各个第三方库单独修改,比较棘手,先记下来.
2. 现在的1.6.0版本已经实现错误提示手动关闭功能.

**Comment by chinaShawn** [comment]
强烈需要！！！在线等这个功能啊

**Comment by suziwen** [comment]
6.7.0 版本已经提供代理设置功能

http://soft.xiaoshujiang.com/download.html
