### ISSUE TITLE
印象笔记

### ISSUE THREAD

**Issue by fisherman132** [suziwen/markdownxiaoshujiang#511]
印象笔记中笔记本结构：
一层笔记本
    ----二层笔记本1
    ----二层笔记本2
         ----三层笔记本1
         ----三层笔记本2
到小书匠中：
一层笔记本
    ----二层笔记本1
    ----二层笔记本2
    ----三层笔记本1
    ----三层笔记本2

**Comment by suziwen** [comment]
```
一层笔记本
----二层笔记本1
----二层笔记本2
----三层笔记本1
----三层笔记本2
到小书匠中：
一层笔记本
----二层笔记本1
----二层笔记本2
----三层笔记本1
----三层笔记本2
```
没明白，你是指排序顺序不对？

**Comment by suziwen** [comment]
笔记本组的话， 印象笔记官方没有提供api,不能拿到相关信息。
