### ISSUE TITLE
为什么在刷新后文件列表不全啊？（绑定的是印象笔记）

### ISSUE THREAD

**Issue by XIPEGM** [suziwen/markdownxiaoshujiang#517]
我有一个印象笔记的笔记本里面有400条笔记，但是通过小书匠刷新后，目录下方少了很多笔记，导致想要重新修改笔记，找不到入口。这是个什么情况啊，难道每个笔记本下面的笔记数量有限制么？我用印象笔记的客户端可以实际查看到笔记，就是在小书匠里面看不到。

**Comment by suziwen** [comment]
感谢，还真没注意，我一直都是操作最近的几条，所以没发现这个问题。好像是 api 限制了一次最多取 250 条。我看他们 api 文档上写是可以一次拿到全部，但实际不是这样，估计他们临时又改了，然后文档没跟上。后面再改一下实现多次分页去取笔记列表。

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v4.0.0
