### ISSUE TITLE
能否添加功能。。。

### ISSUE THREAD

**Issue by enterpaper** [suziwen/markdownxiaoshujiang#518]
最近，用小书匠客户端总是无法保存到印象笔记，一个笔记也就8-20M的样子，能否添加一个功能导出到gitbook上，省的保存笔记又出错。

**Comment by suziwen** [comment]
没找到 gitbook 有提供相应的 api.也还没研究过 gitbook 客户端是怎么个工作方式。
不过你应该可以选择绑定到 github 保存，或者本地绑定，然后自己再和 gitbook 对应上。
