### ISSUE TITLE
新建文件默认带tag关键字一和二，我每次都会删除，因为我默认不标记tag。

### ISSUE THREAD

**Issue by fujinggui** [suziwen/markdownxiaoshujiang#52]
关键我是备份到evernote，在本地编辑器已经删除了tag,保存后上传到evernote上的笔记竟然还带tag.请确认下这个bug。

**Comment by suziwen** [comment]
想要删除tag,得先编辑器里删除tag后,再到左边文档列表栏里点击文件对应的信息维护,把界面上的tag也清空一下,再保存到evernote时,就不会更新evernote的tag了.

代码上的设计逻辑是:

编辑器里的tag>文档信息界面里的tag.
如果编辑器里有tag,就会覆盖替换掉文档信息界面里的tag,如果编辑器里把tag删除,但系统只是当做你不想使用元数据里的tag,不代表不想通过文档信息界面里维护tag.

下个版本会添加一个新建文章的设置.可以自己定义新建文章的模板.

**Comment by fujinggui** [comment]
找到了，这样操作确实麻烦。期待模板功能

**Comment by suziwen** [comment]
web版现在已经实现模板功能，可以先体验下。

**Comment by suziwen** [comment]
最新客户端1.6.0已经实现模板功能
