### ISSUE TITLE
win7 x64 已经打开程序的情况下双击md文件闪一下后无反应

### ISSUE THREAD

**Issue by cocowobo** [suziwen/markdownxiaoshujiang#526]
01.安装后，默认程序关闭，
02.进入一个全是md文件的文件夹
03.点击第一个md文件【01.md】，小书匠启动窗口弹出，打开了01.md文件
04.不关闭已打开的窗口，再去点击第二个md文件【02.md】，小书匠已打开的01.md的窗口屏幕边缘暗了一下，也就是闪了一下，之后就没反应了，
05.在已打开的01.md窗口打开左侧侧边栏，展示历史记录列表，也还是只有01.md，
06.重复试验打开其余的其他md文件，效果同上，
-----------------------------------------------------
尝试一：
01.关闭第一个窗口。即程序关闭【完全退出右下角无图标】
02.点击其余的md文件，可以打开，同时历史记录里面正常记录两条打开记录，
03.多次试验，发现只能完全关闭才可以打开新的md文件
尝试二：
01.不关闭已打开窗口，但是将其最小化，
02.尝试打开第二个，无效，只是之前最小化的放大了，
尝试三：
01.打开第一个md文件后，点击左上角菜单点击导入，
02.将其余的某一个md文件导入，导入成功，在历史记录里面找到了，并且可以切换列表里面的md文件。
-----------------------------------------------------------
历史回顾：
md 文件我是接触比较早，但是使用比较少，编辑器也用的少，小书匠我倒是情有独钟，喜欢这风格，
但是从之前个各种版本都是在我的电脑上各种各种的bug，和上面类似都是打不开的问题，还有就是启动慢，左右预览窗口之前的版本不同步，这次的4.0.0功能我们很满意，但是文件打不开的问题直接给我泼了冷书，可以这样说，每次我想熟悉md语法，就去安装小书匠，开始学习，用了1个小时就因为bug，卸载了，然后不学了，包括这次4.0.0，这个版本我觉得很好用，就是我上面的bug让我很难受，有强迫症，
--------------------------------------------------------
推测：
01.首先说下电脑配置，6个T的硬盘，1个112g的固态，16g内存，
02.安装的程序就是android开发的程序，没啥特俗可能导致冲突 的软件，360杀毒，谷歌浏览器，360浏览器，idm。蓝灯。百度云，有道·······
----------------------------------------------------------
其他使用不清楚的：
01.因为不太使用md编辑器，不知道你这数据是干啥，为啥不可以像普通的文本编辑器那样，直接加载本地md，渲染，还有什么归档？干啥的，为什么要出这个功能，我打开一个本地md文件，做出修改，ctrl+s保存，关闭小书匠，就好了，下次打开只是记录之前打开某个文件就行了，怎么小书匠这么复杂？？
02.导入的时候已存在的md文件再次导入，右边提示出错，应该是警示，文件已存在吧，报红弹出错，是什么鬼，也看不出具体什么错，但是我导入新的就可以导入，导入已存在的就会右侧弹红窗，只是提示出错
03.md文件的本地引用gif动图加载失败是不支持还是怎么？
04.缩小后，状态栏没有图标，只是占了个位置？
----------------------------------------------------------

望作者可以认真回复我下，非常感谢！

**Comment by cocowobo** [comment]
后续：
01.安装最古老的版本1.11.0，完全没有问题。。。。。。。
02.怎么打开都没有问题，

**Comment by cocowobo** [comment]
后续：
01.记得当初第一次使用小书匠就是一点几，使用了后很好用，才迷上小书匠的，只是界面有点小瑕疵，后来看见一次升级忘了是哪一次，使用新版本就是各种文件打不开，双击无反应问题，之后就卸载了，偶尔想起下个新版本运行下看解决没有，解决了就使用，没解决就删除，
02.这次的4.0.0我很喜欢，所以不想卸载了，望可以解决这个问题，
03.未发现其他提出同类bug的朋友，难道是我电脑专属bug？

**Comment by cocowobo** [comment]
尝试：双击打不开问题已找出，
----------------------------------------------
01.在同事电脑上打开同样的多个md文件，他的很正常
02.我思考了很久发现。似乎是我的文件的位置是，在外置的移动硬盘上，对了是个4T的移动硬盘，
03.我将文件复制到内置硬盘上，好了，问题解决了，
--------------------------------但是问题出来了------------------
尝试二：
01.我怀疑是移动硬盘中存储目录比较深，于是复制到根目录。
02.双击后成功打开，难道是真的只是目录比较深吗。。我怀疑不仅仅是，
----------------------------------------------
尝试三：
01.在内置硬盘上找了个比较深的路径，放入md文件，打开成功，
02.看来不是因为路径较深。我试着比较两种路径，发现问题所在，并复现出此问题，见下文
+++++++++++++++++问题复现++++++++++++++++++++++
01.出现问题的目录是命名中存在 两个减号，即 E：\01--开发文档\01.md
02.同时测试使用只有一个减号的目录，成功打开，
03.测试其他常见的复杂字符命名的文件夹，成功打开，
04.使用两个和两个以上的减号的目录，则出现上面的 bug，
05.不死心的我在同事电脑上建立了 两个减号的目录，复现出上面的bug。
-----------------------
06.还有个bug反馈。在同事电脑上给一个比较大的md文件，使用鼠标滚轮翻页，快速，特别快速的翻页，他的小书匠顺利而且流畅的翻页了，在我的电脑上快速翻页 则出现出现延迟比较高，我都快速滚动完成了4s，屏幕上才滚动完成。。这个看着解决吧

**Comment by cocowobo** [comment]
补充：
01.打开后滚动卡顿的文件大小81k，我的电脑，刚刚重启，没开什么，性能还可以，同事电脑和我差不多，他就不卡，我就卡。。。
02.测试打开25k的md文件，从头翻到尾部，快速的，会有1s的延迟
03.测试打开41k的md文件，有2s的延迟，这个时间都是我心里估算的。
04.在同事电脑上重复上面的操作。都是很流畅，，，，

**Comment by suziwen** [comment]
非常感谢帮忙找出两个减号目录引起的问题。
1.  内置数据库，归档这些功能一般是给想把小书匠当成知识管理工具来用的用户。如果只是当成编辑器的话，可以忽略这些。小书匠客户端也支持直接双击打个 markdown 文件的。
2. 导入的文件再导入，我这边没有出现你说的错误情况。
3. 支持本地引入 gif 文件的.
![image](https://user-images.githubusercontent.com/57370/30378725-c2b0ba5c-98c6-11e7-8818-3a75e9737d5c.png) 
![image](https://user-images.githubusercontent.com/57370/30378752-d631263e-98c6-11e7-91e5-f4bf48e3a933.png)
4. 缩小窗口后，相关的按钮进行了自适应
![image](https://user-images.githubusercontent.com/57370/30378828-142e1d0c-98c7-11e7-820b-e0d0b9eef539.png)
5. 不能流畅滚动，是不是在小书匠设置里做了其他什么调整。我这边自己平常用也没出现过滚动卡顿。

**Comment by cocowobo** [comment]
14号补充：
------------------滚动延迟-------------------------------
！！！问题已找到
01.原因：切换编辑器：为默认的ace编辑器就很流畅。
02.为什么会出现：当我新电脑第一次安装体验4.0.0的时候，使用了cledit编辑器模式，之后发现了打不开文件的小问题，然后重复卸载，安装，还中途安装过老版本，之后找到文件打不开的原因后，就开始继续体会程序，发觉卡顿。当时原因不明。所以进行过如下尝试。
---------------------------------------------------------------
尝试：01.重装。02.卸载显卡驱动，03.去掉我的双屏，04.重启，05.多个电脑比较

---------------此问题深入测试------------------
01.问题预想：真的是编辑器的问题吗？（什么是编辑器我在知乎看了些资料才知道这几种编辑器是干啥，小白用户可耻呀）
02.问题验证：使用默认的ace编辑器无问题，同一个文件滚动流畅，立马切换到cledit模式,默认回到第一行，前面的50行滚动流畅，但是直接将滚动条拉倒最后一行，向上翻页滚动，立马卡顿！同时我再切换到codemirror模式，重复上面的操作，流畅。
-------------在深入测试------------------
01.问题预想：我加载的特俗才造成以上bug吗？
02.问题验证：100k的小说，改成md文件，打开。使用cledit模式卡顿，纯文本，不需要复杂渲染，也是卡顿。
------------此问题影响范围-----------------------
在历史列表来回切换文件，如果是在此模式下，切换也卡顿，


--------------------------------------结论---------------------------------
卡顿是用的编辑器框架的问题，不知道可以作者解决不，是不是内存的问题。

-------------------------------------小建议-----------------------
在历史界面，可以充分利用右键，直接打开到文件夹。
申请此功能理由：
理由1.：我因为测试发现。来回同一个文件复制多个文件夹下，加入10个文件被打开。都叫01.md，尴尬了，我真的无法区分这10个文件那个是出错的，辨识度。。。。
理由2.：当我需要找一个md 文件的时候我记不得我存放在哪里了，有一天我需要找，不小心打开小书匠，发现之前打开过，干看着历史记录着急呀，，，
------------------------------------
之后我发现在归档管理界面有个修改文件信息，有个绑定信息。可以看到关联的路径，好吧！勉强达到我的要求，但是不好用呀，
还没完。我发现有的草稿文件的绑定信息显示未进行绑定，什么鬼？作者你的设计思路是什么？
我承认，你的设计很高大上，但是我看不懂呀，看不懂没关系。伟大的软件学习成本都是很高的，但是作者你不觉得小书匠的全面功能介绍资料很少吗。。。官方似乎也没有。只有语法资料。。。设计思路，和使用注意事项，新手入门尼？喜欢作者的小书匠，很像自己可以写个简单的入门使用指南，但是我TM还没学会呀。。。

**Comment by harry10086** [comment]
我在win7 64位下基本上不能正常使用.功能非常多,非常强大,但好多功能都不能稳定的使用.
个人感觉4.0很不成熟.

**Comment by cocowobo** [comment]
@harry3633 提出来让他 @suziwen 改正，之前的有bug我就卸载了，这次的有bug我舍不得卸载，因为真的看起来很厉害，等作者修复完成，我就赞助个vip。让作者抽包烟

**Comment by suziwen** [comment]
1. cledit 编辑器不太适合编辑大的文件。
2. 右键功能以后会考虑添加
3. 未绑定是指当前的文件还只是保存在小书匠内置的数据库里，没有和其他第三方系统绑定(比如印象笔记，本地绑定，本地关联).没有绑定的文件，点击保存时，只是保存当前文件到小书匠数据库里，如果绑定了，点击保存会一起保存到第三方系统上的。
4. 目前资料确实很少，不过在一般使用上应该还是够的。用户暂时不需要知道内置的数据文件格式，比如导出的数据库具体字段什么含义。

**Comment by suziwen** [comment]
@harry3633 有 bug 的话可以提的，如果这些 bug 真的让你无法忍受，完全可以删除不用啦，双向选择的。:frowning:
很多功能都是我自己平时在用。都是在确保能正常使用时才会发布出去。遇到一些比较严重的错误，也是会及时修复的。因为功能多，确实有些地方难免测试不到位，只能是希望用户理解了。

**Comment by cocowobo** [comment]
赞一个，一个辛勤工作，努力奉献的作者

**Comment by cocowobo** [comment]
@suziwen 如果这个 奇怪目录打不开的bug解决了。就关闭此吧，
cledit 编辑器不太适合编辑大的文件。可以给出个提示，因为很多新用户第一次学md的时候，可能就看上你的小书匠易用，但小白不知道编辑器的 优缺点，可能会以为是小书匠的bug，还要就是 编辑器的 这个问题是无法修复是吧？
，资料少要不作者给我推荐点，我以后整理下。

**Comment by suziwen** [comment]
嗯，下个版本打算去掉 cledit 编辑器。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
