### ISSUE TITLE
个别语法不识别（本人非专业人士此语法不认识）

### ISSUE THREAD

**Issue by cocowobo** [suziwen/markdownxiaoshujiang#528]
`[![Android Arsenal](https://img.shields.io/badge/Android%20Arsenal-Fragmentation-brightgreen.svg?style=flat)](https://android-arsenal.com/details/1/5937)
[![Build Status](https://travis-ci.org/YoKeyword/Fragmentation.svg?branch=master)](https://travis-ci.org/YoKeyword/Fragmentation)
[![Download](https://api.bintray.com/packages/yokeyword/maven/Fragmentation/images/download.svg) ](https://bintray.com/yokeyword/maven/Fragmentation/_latestVersion)
[![Hex.pm](https://img.shields.io/hexpm/l/plug.svg)](https://www.apache.org/licenses/LICENSE-2.0)`

同一个文件，第一行是上面的内容。紧接着是标题，使`MarkDownPad2`打开后再标题上是渲染出

Android Arsenal Fragmention 隔开 build passing 隔开 Download 1.1.6 隔开 license Apache 2

这是什么不知道，但是人家是排成一行的，
-----------------------------------------------
小书匠渲染结果是如下

附件框 
附件框
 Download 1.1.6
license Apache 2

这个就尴尬了，不懂，来问作者。。。

**Comment by cocowobo** [comment]
疑问2：
代码如下
`![](/gif/logo.png)`
MarkDownPad2 准确的显示了当前目录下的gif目录下的logo图片，
小书匠`找不到本地地址 /gif/logo.png 对应的资源`
疑问3：
代码如下
`<img src="/gif/demo1.gif" width="280px"/>`
MarkDownPad2 准确的显示了当前目录下的gif目录下的动态图片，
小书匠加载失败，显示默认破损错误图。

----------------设想------------（出自不太懂的小白 的设想）
01.md语法不统一吗。之前看过资料，
     `PHP Markdown Extra 介绍 （仅限 PHP Markdown Extra 版本）
上面我们已经完整的学习了 Markdown 官方 Perl 版本的基本使用方法，但是 Markdown 不止Perl一种语言的实现，在任何时候都应该尽可能的先考虑 Markdown 的基本实现，如果基本实现不支持的功能时，再考虑其它的实现，而本站所使用的Markdown为PHP的扩展实现，它在官方版本上，还增加了许多实用的功能，下面对其进行详细的介绍：`
来自于：`https://www.zhihu.com/question/19963642` 第二条回答。
难道作者这个使用是语法不走平常路，
那么就要麻烦作者了，可以推荐点写的好的资料，理清这些语法的演变历史。或者分析，各种博客网站使用的md语法有什么区别？或者是没区别吗

**Comment by suziwen** [comment]
1. 可以在`设置>预览` 把`是否自动转换非图片扩展名为附件（自动识别jpg,jpeg,png,gif及无扩展名的文件为图片文件，其他的扩展名文件为附件）` 选项去掉，就能正确渲染非图片扩展名的图片了
2. 这个路径小书匠是当成绝对路径，在 linux 系统里，这个是从根目录算起的。你可以试试 `./gif/logo.png` 或者 `gif/logo.png`小书匠在资源路径查找算法上有些不一样.全局资源路径可以在 `设置>基本` `资源绝对路径起始地址` 里修改.

**Comment by suziwen** [comment]
这个语法没有错，只是不同编辑器对本地资源的路径查找上不一样。小书匠提供了本地绑定，本地关联打开，印象笔记。如果只是单独的从本地系统里找图片相对资源是无法满足要求的。

如果你是使用本地关联打开一个文件 ，然后用截屏软件保存一个图片到剪切板里，这时到小书匠编辑器粘贴，图片会直接生成 ，然后文章内容是 `![](./image/xxxxx.png)`, 但是你实际是没法在自己文件旁边看到 `image/xxxx.png` 这个文件的。

而如果你是使用本地绑定，就会在该文件的旁边看到一个 `image/xxxx.png` 目录和图片文件.

**Comment by cocowobo** [comment]
@suziwen 非常感谢，你的解释很清晰，语言很直白，一眼看完就懂了，同时还学到了不少知识，谢谢，继续学习中
