### ISSUE TITLE
关于发布功能中文的问题

### ISSUE THREAD

**Issue by fedstryale** [suziwen/markdownxiaoshujiang#53]
发布功能很不错，除了oschina等博客平台，wordpress也支持，不过有个很重要的问题

发布的正文里的中文都被转化为了代码，如`&#x7531;&#x4E8E;&#x5C0F;&#x4E66;&#x5320;&#x6700;&#x65B0;&#x7248;&#x672C;&#x66F4;&#x65B0;&#x652F;&#x6301;&#x76F4;&#x63A5;&#x53D1;&#x5E03;&#x5230;&#x535A;&#x5BA2;&#x5E73;&#x53F0;`
这导致wordpress等不能搜索中文内容，只有标题和英文能被搜索，不知道为什么正文中文需要转化为代码？

**Comment by suziwen** [comment]
嗯,没测试到,是个BUG.下个客户端版本会修复.


下面的是临时解决方案:

如果你用的是window客户端, mac或者使用package版本的,可以自己修改一下.
到安装目录下,找到`js/app.js`,用其他文本编辑器打开,搜索`u=n.load(i)`,把它改成`u=n.load(i,{decodeEntities: false})`,保存退出文本编辑器,再打开小书匠重新发布文章,就能正常处理中文内容了.

mac的路径是`Story-writer.app/Contents/Resources/app.nw`, 解压`app.nw` 里的`js/app.js`进行修改,然后再用压缩软件压缩一下.注意扩展名及压缩后的目录结构.


注: 修改前可以先备份下`js/app.js`文件.我这边修改的是1.5.0版本下的`js/app.js`.

**Comment by suziwen** [comment]
最新1.6.0客户端已经解决
