### ISSUE TITLE
还是WP

### ISSUE THREAD

**Issue by prolover** [suziwen/markdownxiaoshujiang#530]
发送失败：(statusCode:400; statusMessage:Bad Request)服务器返回了不能识别的标签：Unknown XML-RPC tag 'TITLE' <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>400 Bad Request</title> </head><body> <h1>Bad Request</h1> <p>Your browser sent a request that this server could not understand.<br /> </p> </body></html>
上面提示代码.
最新版的wp,没有安装 什么插件。

**Comment by suziwen** [comment]
发布文件的界面截个图看下。

自己搭建的一个 wp? 还是使用哪家 wp 服务商？

**Comment by prolover** [comment]
邮件发给你还能看见?



josuncn@qq.com
 
Sender: 苏滋文
Send Time: 2017-09-16 10:06
Receiver: suziwen/markdownxiaoshujiang
cc: prolover; Author
Subject: Re: [suziwen/markdownxiaoshujiang] 还是WP (#530)
发布文件的界面截个图看下。
自己搭建的一个 wp? 还是使用哪家 wp 服务商？

**Comment by suziwen** [comment]
不要通过 github 中转发带图片或者附件的邮件，看不到附件的。
直接发 suziwen1@gmail.com

**Comment by harry10086** [comment]
和我的问题一样

**Comment by suziwen** [comment]
@harry3633 他的已经解决，不过我没做什么修改，只是他给我个测试账号，然后我发布成功，并截图给他看了下，他自己不知道修改什么，也就发布成功了。。。。可能是提供的 url 地址不对吧，具体得问一下 @prolover ，当时他也没说为什么。

**Comment by prolover** [comment]
@harry3633 我只是加上http和改了一密码，再重新填定用户名和密码。

**Comment by harry10086** [comment]
```
发送失败：(statusCode:301; statusMessage:Moved Permanently)服务器返回了不能识别的标签：Unknown XML-RPC tag 'TITLE' <html>
 <head><title>301 Moved Permanently</title></head>
 <body bgcolor="white">
 <center><h1>301 Moved Permanently</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
```
我的和他提示不一样,用户名密码都没错误,http和https都试了,失败提示一样
wp是我自己搭建的,word可以正常连接发布

**Comment by suziwen** [comment]
@harry3633 你的wp  服务器使用重定向设置了？ 目前还不能直接处理需要重定向的链接地址。

**Comment by harry10086** [comment]
@suziwen 原来如此,谢谢

**Comment by pangao66** [comment]
同问此问题, 我的自建的WordPress, Word可以, 小书匠显示该博客无法提供metaweblog接口  ,我的域名用了阿里云的cdn ,用的CName解析的 ,希望能支持

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
