### ISSUE TITLE
codemirror编辑器的vim模式问题

### ISSUE THREAD

**Issue by everdom** [suziwen/markdownxiaoshujiang#534]
在codemirror编辑器中启用vim模式之后，有些vim快捷键并不能使用，比如：
ctrl+r并不是重做，而是会插入一个分隔符
ctrl+u并不是向上翻半页，而是会插入一个列表
ctrl+f并不是向下翻页，而是显示搜索框
ctrl+b并不是向上翻页，而是会加粗显示
其他键暂未测试，但这几个常用快捷键能否映射成vim快捷键呢？
补充一下：ace编辑器的vim模式没有这些问题

**Comment by suziwen** [comment]
#454

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
