### ISSUE TITLE
打开附件时报错

### ISSUE THREAD

**Issue by sfon** [suziwen/markdownxiaoshujiang#538]
[这是报错的截图](https://ws1.sinaimg.cn/large/006K8RX2gy1fjnir9pqnxj30ag05uwer.jpg)（话说这里怎么直接发图片的？）
是chrome插件的问题？我在我的chrome://extension中没有找到对应的插件啊

**Comment by sfon** [comment]
我想在我的md文件里添加当前目录下的另一篇md文件的链接，正常情况它应该直接打开和显示的，但是它是启用浏览器来打开附件，然后报错了。
能否直接识别附件的文件类型，如果是md文件就直接打开了，不再调用浏览器呢？

**Comment by suziwen** [comment]
要打开 `grammar_attachment:true` 语法，或者 `设置>扩展语法>附件`，点击时才不会报错

**Comment by sfon** [comment]
好的，附件能显示了，是否能考虑一下我的建议呢？

> 能否直接识别**附件/链接**的文件类型，如果是md文件就直接打开了
