### ISSUE TITLE
发布时转换html含图片路径语句的问题

### ISSUE THREAD

**Issue by fedstryale** [suziwen/markdownxiaoshujiang#54]
又发现了一个小问题

由于想将插入图片的路径设置为站点的相对路径，在更换域名时链接不会失效，故采用插入html语句的方式，如
`<p><img src="/wp-content/uploads/jianzhu.jpg" alt="enter description here"></p>`
但无论导出html还是发布功能发布，最终结果都会转换为
`<p><img src="file:///wp-content/uploads/jianzhu.jpg" alt="enter description here"></p>`
会自动加一个`file://`，导致图片链接失效，有办法将其保持原有插入语句吗？

**Comment by suziwen** [comment]
最新1.6.0客户端已经解决
