### ISSUE TITLE
你们用起来卡不卡？

### ISSUE THREAD

**Issue by prolover** [suziwen/markdownxiaoshujiang#542]
我用起来好卡，点一下左键要等十秒左右。
启动更是要花好长时间。

**Comment by suziwen** [comment]
你内置的编辑器是什么 ？ codemirror, ace 或者 cledit?

切换成 codemirror 呢

![image](https://user-images.githubusercontent.com/57370/30574600-a4f29c1c-9cc0-11e7-9472-ff3dcedd0a1f.png)

**Comment by suziwen** [comment]
还有电脑配置， cpu, 内存等，访问 web 版也会卡？

**Comment by prolover** [comment]
win7, i5,4g,其它的软件不卡。

**Comment by suziwen** [comment]
你把`关于` 界面里的`信息` 发个过来看下。

![image](https://user-images.githubusercontent.com/57370/30579204-524431fc-9cdd-11e7-9e5a-dac53a839fa7.png)

**Comment by prolover** [comment]
![4](https://user-images.githubusercontent.com/22161404/30579528-a8edad08-9d4b-11e7-8cfa-82d19755cef4.jpg)

**Comment by prolover** [comment]
现在不卡了。
怎么回事？

**Comment by suziwen** [comment]
新建一篇空白文章，在这篇文章上输入呢，也一样卡？

**Comment by suziwen** [comment]
那感觉还是在哪个地方操作，触发变卡？我这边没有做什么修改。

**Comment by prolover** [comment]
现在不卡了~
无论是新建还是编辑，都不卡了。
