### ISSUE TITLE
4.0 安装报错

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#544]
![tim 20170919203314](https://user-images.githubusercontent.com/11471256/30619100-22125290-9dd0-11e7-8c1f-79474fa63c68.png)

如图， win 10 系统

**Comment by ghost** [comment]
试了一下，以前的版本也是报这个错误。。。。

**Comment by suziwen** [comment]
这个跟你的操作系统关系比较大。64位运行在 32位操作系统上了？
还是操作系统其他什么地方限制
再一个就是下载的安装包是不是被串改了？

**Comment by ghost** [comment]
@suziwen 64位，安装包也是64位，刚开始安装的时候360给报了下毒，后面我关了360。重新下载过包，直接远程到另一台电脑安装成功后再复制包过来，结果还是这样。前后下载过3个包，都是这个结果

**Comment by suziwen** [comment]
这个是 4.0.0,  win 64 位版的 md5 值，你看跟你下载的是不是一样
```
94e5470f4fa5d3789c1f7811f9c2c612  Story-writer-win64-setup.exe
```

**Comment by ghost** [comment]
MD5: 94E5470F4FA5D3789C1F7811F9C2C612
SHA1: 1EC3DE48CC4497F22FA0F2ACC63A07113FC9F4D5
CRC32: EB8DB581

一样的，蛋疼中.....

**Comment by ghost** [comment]
@suziwen 忽然发现我公司和家里电脑换成 win10 之后两边都出问题。公司的小书匠不能用 ctrl + s 保存，家里卸载之后重装不了。（手动滑稽

**Comment by suziwen** [comment]
你看看不能使用 `ctrl+s` 是不是切换到 `ace 编辑器`了， 切回到 `codemirror 编辑器` 应该能解决.

#534 #454

**Comment by ghost** [comment]
嗯，切换 codemirror 确实可以了， thanks
