### ISSUE TITLE
小书匠QQ邮箱，foxmail邮箱无法收到验证信息

### ISSUE THREAD

**Issue by ynchiu** [suziwen/markdownxiaoshujiang#546]
已经查找过垃圾箱里也没有小书匠发的验证邮件。

**Comment by gavin666** [comment]
我最开始注册收到了邮件，但是无法激活，抛异常界面

**Comment by suziwen** [comment]
ynchiu 的已经通过其他邮件注册成功了。先闭关这个 issue 了。
@gavin666  可能验证时间过期了，重新再发送新的验证邮件呢？如果还有问题可以再开一个新的 issue
