### ISSUE TITLE
提一个小问题

### ISSUE THREAD

**Issue by mxxiv** [suziwen/markdownxiaoshujiang#549]
使用 ` ` 对行内关键字标注
像这种写法 `=` 赋值，`==` 等于，`===` 全等于
在双等号的前面还是会出现颜色小方块，会被判断成 ==文字 == 这种语法
在 ` ` 之间是不是不应该再判断语法了

**Comment by suziwen** [comment]
嗯，这个后面再改进下。
如果觉得太多颜色小块，影响写作，可以到 `设置>编辑器>codemirror>开启高亮语法颜色选择器` 选项去掉。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
