### ISSUE TITLE
跟印象笔记的同步总是有问题

### ISSUE THREAD

**Issue by resouer** [suziwen/markdownxiaoshujiang#55]
1. 编写的文章不能及时提交给印象笔记
2. 一台机器上修改不能及时反映到另一台机器上

**Comment by suziwen** [comment]
系统没有提供自动同步到印象的功能。
在选择印象绑定后，手动点保存，或ctrl+s时，才会同步保存到印象上。在使用手册上有印象的操作说明。可以先看看。

**Comment by suziwen** [comment]
也可以看看这篇文章
http://www.cnblogs.com/suziwen/p/4480145.html

**Comment by resouer** [comment]
@suziwen 没有自动同步我是知道的。我也点了ctrl+s

问题在于：
1、A机器保存，B机器看，大多数情况下OK。
2、但是然后在B机器改完，保存，回A机器看，A那边八成还是1所做的改动

**Comment by suziwen** [comment]
目前代码上的设计是这样的

用户在抓取第一份evernote上的文件后，都会在系统上生成一个"缓存"的文件，并把这个缓存的文件跟evernote关联，下次再点击evernote上对应的文章时， **如果系统找到本地浏览器里已经有一份文件了，就不再从evernote上抓取文件，不管evernote是否修改过**  。已经取过一次文件后，想要再从evernote上取得更加新的内容，需要自己手动删除浏览器缓存的文件。现在系统还没做到根据evernote提供的文章修改时间来确认是否需要重新抓取新的文章的功能，因此需要用户自己来操作是否重新加载。

**Comment by resouer** [comment]
@suziwen OK 那我先close了。毕竟只要每次找到做最近一次正确修改的机器的话，内容还是能恢复的。 。。
