### ISSUE TITLE
How do I upgrade to 4.2.0?

### ISSUE THREAD

**Issue by fainboy** [suziwen/markdownxiaoshujiang#553]
A great app, TKS~
I am a registered user, how can i upgrade to the final version?

**Comment by suziwen** [comment]
if you are a VIP
 just restart client app, and it will notice you upgrade.
or  go to `about` page, there is a upgrade button.

![image](https://user-images.githubusercontent.com/57370/30791627-7120b62c-a179-11e7-8d0d-8047b56ddeee.png)

if not a vip, need waiting next client app release.

**Comment by fainboy** [comment]
Oh, yes, I found it when the app was restarted. Thank you
