### ISSUE TITLE
导出PDF水印问题

### ISSUE THREAD

**Issue by G794206250** [suziwen/markdownxiaoshujiang#555]
导出PDF时无论怎么样都不会将水印去掉，网页版也一样

**Comment by suziwen** [comment]
目前非付费用户，想要去掉联网打印 pdf 的水印，只能通过修改它的坐标来实现。就是让水印移出页面范围。比如
![image](https://user-images.githubusercontent.com/57370/30794117-fb1035d0-a18b-11e7-95bd-7bd9f8116b9c.png)

------------------
或者 web 版本使用 chrome 浏览器，然后 `导出/打印`
或者使用客户端的本地 pdf 导出/ 打印
