### ISSUE TITLE
Firefox全屏编辑闪退

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#557]
此网站似乎使用 scroll-linked 定位效果。这可能不适合异步平移；参见 https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 可深入了解，也可加入相关的工具和功能的讨论。

闪退就是直接给我退出了全屏模式，但是还是可以用普通模式。

不过全屏模式还是漂亮呀。

{
    "appCodeName": "Mozilla",
    "appName": "Netscape",
    "appVersion": "5.0 (Windows)",
    "cookieEnabled": true,
    "language": "zh-CN",
    "platform": "Win64",
    "product": "Gecko",
    "productSub": "20100101",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0",
    "vendor": "",
    "vendorSub": ""
}
{
    "apm": {
        "storePlugin": "github",
        "font": ""
    },
    "epm": {
        "editorType": "codemirror",
        "theme": "ace/theme/solarized_light",
        "cm_spellChecker": false
    },
    "ppm": {
        "previewLayoutPosition": "east"
    }
}

**Comment by suziwen** [comment]
我这边 win7 下 firefox 55.03 使用全屏没有出现你说的情况。

**Comment by panhaoyu** [comment]
我自己电脑也没问题可能是图书馆系统问题，我有空再去测一下
