### ISSUE TITLE
每次打开linux客户端，要打开上次保存在evernote上的一篇文章，而不知道什么原因无法打开这篇文章。导致一直停在打开那篇文章，打不开，又无法取消。

### ISSUE THREAD

**Issue by fujinggui** [suziwen/markdownxiaoshujiang#56]
怎么办？linux客户端的配置选项保存在哪个目录？干脆删除配置了。

**Comment by fujinggui** [comment]
找到了，在.config目录下面。哪个文件才是配置？怕把本地文章给清除了。

**Comment by suziwen** [comment]
可能是evernote上的文章在转换成markdown时失败导致。如果启动后一直卡在那有问题的文章，可以先在本地新建一个文件`test.md`，然后通过命令行`./Story-writer /home/xxxx/test.md`来打开一个本地的文章，这样系统就会新建md文件，而有问题的文件就会变成文件列表里的第二个文件。

**Comment by fujinggui** [comment]
是因为之前的那篇文章保存到evernote有问题，保存的时候卡死了。我只好杀死进程，重新打开。结果重新打开的时候也卡死了。新建test.md那样操作可行。不过之前的那篇文章内容丢了，没有保存到evernote。

**Comment by suziwen** [comment]
新建test.md启动后,关闭预览,然后再点击那篇出错的文件还是会卡?
如果不卡的话,自己再单独处理那篇文章.
现在想到的可能原因是该文章里有些特殊的格式,导致系统再转换成html时陷入死循环.如果方便把markdown文件发邮件给我的话,我可以更容易找出出问题的地方.不然现在也没有想到比较好的方法找出出错的地方.
