### ISSUE TITLE
注册不了？收不到验证邮箱的邮件。

### ISSUE THREAD

**Issue by LoyaltyWu** [suziwen/markdownxiaoshujiang#564]
我摁了验证邮箱了，但是并没有收到邮件。重新注册也不行，也说我的邮箱已经注册了。

**Comment by suziwen** [comment]
是不是 qq 邮箱收不到？ 用浏览器登录他家的邮箱能不能看到，还有就是注意下是不是被当成垃圾邮件拦截掉了？

换一个其他品牌的邮箱呢？

**Comment by G794206250** [comment]
QQ邮箱会当作垃圾邮件拦截的，你需要检查一下。我上次也是同样的问题

**Comment by LoyaltyWu** [comment]
不是垃圾邮件的问题。垃圾邮件问问题之前我也检查过了。我在垃圾邮件信箱中都没找到。可能是qq邮箱的问题吧？我迟点试试别的邮箱呀。谢谢你了。
