### ISSUE TITLE
您好，在绑定印象笔记的时候，申请token申请不了？

### ISSUE THREAD

**Issue by WystanW** [suziwen/markdownxiaoshujiang#565]
token界面这么说的：Update: the creation of developer tokens is temporarily disabled.
有没有其他方法绑定印象笔记呢？

**Comment by WystanW** [comment]
而且网页版绑定账户的时候一开始还可以，过了一会账户就不绑定了，然后再申请说绑定失败

**Comment by G794206250** [comment]
我也遇到了同样的问题，现在不能够申请token。你知不知到如何解决？

**Comment by WystanW** [comment]
并不知道，网页版小书匠只能绑定成功不一会，然后就断了，过一会又好然后又断，很是头疼

**Comment by suziwen** [comment]
#532 

可以先参考[这个](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-9-17%20%E5%85%B3%E4%BA%8E%20Evernote(%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0)%20%E5%81%9C%E6%AD%A2%E4%BD%BF%E7%94%A8%20Developer%20Token%2C%E5%B0%8F%E4%B9%A6%E5%8C%A0%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%8D%E8%83%BD%E7%BB%91%E5%AE%9A%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.md)，通过 http://markdown.xiaoshujiang.com 获取 token

@WystanW 你那 web 版用的是什么浏览器，我这边没有出现你说的情况，绑定后，就一直都可以用了。

**Comment by WystanW** [comment]
@suziwen 谢谢，已经搞定

**Comment by linuxu2015** [comment]
客户端现在不能绑定印象，只能使用web端的吗？
可以用了，在web端可以看到印象笔记的token，把那个复制下来，贴到客户端就可以用了。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
