### ISSUE TITLE
小书匠v4.0版本不支持印象笔记图片展示

### ISSUE THREAD

**Issue by venshine** [suziwen/markdownxiaoshujiang#566]
RT,印象笔记图片链接格式显示不支持图片。
如下这种格式：
```![](https://app.yinxiang.com/shard/s65/res/03f42227-a1fc-41d6-9be0-cf4960b2f6ba)```
浏览器可以访问该链接图片，其他markdown客户端也能正常解析该图片，小书匠不显示该图片。

**Comment by suziwen** [comment]
不建议这样使用，因为这样的链接是需要浏览器 cookies 认证访问的，比如导出 html ,别人打开你导出的 html ，就看不到这些需要认证的图片了。
