### ISSUE TITLE
http与https协议数据库不一样

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#567]
以前一直用的默认的http协议，这次自己敲了个https协议进去，发现以前的配置项都没了。。

**Comment by suziwen** [comment]
小书匠网页版数据都是保存到浏览器内置数据库里的，小书匠服务器不提供数据存储服务。浏览器认为 http 和 https 访问的小书匠是两个不同的网站，所以数据是分开保存的。
