### ISSUE TITLE
https协议下码云授权崩了

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#568]
能弹得出来授权的界面，但是点进去之后没反应。

![default](https://user-images.githubusercontent.com/23495987/31077620-bc4d8952-a7b1-11e7-8d16-07645699faa7.png)

点进去之后， 白屏

又测了一下，Firefox浏览器https协议也是没反应。

Chrome与Firefox的http协议正常。

**Comment by suziwen** [comment]
调好了
