### ISSUE TITLE
1.5.1网页版、客户端不能保存图片到印象笔记

### ISSUE THREAD

**Issue by up2wing** [suziwen/markdownxiaoshujiang#57]
如题。
1.5.1版在小书匠编辑器里面ctrl+g添加了图片以后，ctrl+s同步到服务器。但是在印象笔记里面，不能显示图片。请确认。
thx。

**Comment by suziwen** [comment]
测试了下，1.5.1网页版和现在最新的客户端1.5.0版本，ctrl+g添加图片保存后，都能正常保存图片并在evernote上显示图片。只是现在网页的1.5.1和客户端的1.5.0存在一个兼容问题，如果是1.5.1保存的文章，然后1.5.0客户端打开该文章是不能在客户端正常显示图片 的。

能否提供更详细的操作，或者自己单独在 http://markdown.xiaoshujiang.com 上新建一篇简单的文章，然后ctrl+g添加图片，看是否能保存到evernote上。

**Comment by up2wing** [comment]
谢谢回复。
按照你那个方法，可以将图片同步到evernote上。我这样还是不行：
先在evernote上建立一篇文章，然后用小书匠客户端->印象笔记->从服务上导入文件->选择刚才建立的那篇文章，ctrl+g插入图片，ctrl+s保存，此时显示“文件成功保存到本地”（后续是否考虑直接保存到服务器呢？），在客户端预览窗口中可以正常显示图片。然后小书匠客户端->印象笔记->更新到云端，再次选择刚才的那篇文章。在evernote中同步之后，看不到图片。

![1140](https://cloud.githubusercontent.com/assets/2585342/8267376/373d67c6-1791-11e5-8a62-f2e8736eb6db.png)

**Comment by suziwen** [comment]
我这边按照你的操作也一样可以正常在evernote上显示图片。
先确认下你的小书匠版本是否真的是1.5.0
![a3](https://cloud.githubusercontent.com/assets/57370/8267879/1fb68288-17a3-11e5-8e9d-67006d5cb4e7.png)

再一个就是所有操作先单独只在客户端操作完成，或者单独只在网页版完成。

**Comment by up2wing** [comment]
清空了下浏览器缓存，然后网页版可以保存图片了。thx
btw, 网页版咋个更新呢？难道每次都要清空浏览器缓存？我是在几台电脑上编辑。

**Comment by suziwen** [comment]
我这边一直都不需要手动清空浏览器缓存就自动更新的,我这边再处理下让版本升级后强制更新缓存.
