### ISSUE TITLE
恩。。码云那边又炸了

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#572]
“检测失败，没有找到相应的仓库或分支”

**Comment by panhaoyu** [comment]
应该是权限不够，可能是碰到了按键取消了权限，导致没法访问私有仓库。但是我没法重新改权限了，希望增加一个重新请求授权的功能。

**Comment by suziwen** [comment]
可以在绑定界面里取消绑定，然后再重新认证绑定

**Comment by suziwen** [comment]
在绑定界面里，鼠标移到绑定的条目里，会显示取消绑定的按钮。

**Comment by panhaoyu** [comment]
并不行啊。。还是显示这个。。检测失败，没有找到相应的仓库或者分支。
而且并没给我一个选择权限的对话框啊，直接就让我选仓库了。。我把仓库改成了公有之后就可以用了。。但是并不打算开源文章代码。。

![2017-10-18_19h00_07](https://user-images.githubusercontent.com/23495987/31715597-1c89337a-b437-11e7-8ec9-6f35952c344b.png)
![2017-10-18_19h02_26](https://user-images.githubusercontent.com/23495987/31715598-1cc8fe10-b437-11e7-862e-9c0a099e919b.png)
![2017-10-18_19h02_44](https://user-images.githubusercontent.com/23495987/31715600-1d0de82c-b437-11e7-8b0f-7fca050ed882.png)
![2017-10-18_19h02_57](https://user-images.githubusercontent.com/23495987/31715602-1d7d2f84-b437-11e7-8967-64239b1c0dce.png)
![2017-10-18_19h03_05](https://user-images.githubusercontent.com/23495987/31715604-1db7d648-b437-11e7-8abe-9f290f5ae904.png)
