### ISSUE TITLE
latex公式无法渲染

### ISSUE THREAD

**Issue by DavichiHug** [suziwen/markdownxiaoshujiang#578]
latex公式无法渲染
![snipaste_2017-10-16_17-47-21](https://user-images.githubusercontent.com/23614846/31605874-1861c512-b29a-11e7-9adb-bc6303e64fe3.png)

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/31642178-4252f7f0-b2af-11e7-9eec-cf3dbe5578f4.png)

**Comment by DavichiHug** [comment]
还是不行，以下是对比图片，环境是http://markdown.xiaoshujiang.com/
![snipaste_2017-10-17_15-26-05](https://user-images.githubusercontent.com/23614846/31652065-7de9388c-b350-11e7-82ba-45db5a39f5d5.png)
![snipaste_2017-10-17_15-28-56](https://user-images.githubusercontent.com/23614846/31652073-81c99078-b350-11e7-8a69-f902622f90de.png)
![snipaste_2017-10-17_15-29-15](https://user-images.githubusercontent.com/23614846/31652076-83ee30b6-b350-11e7-9d0a-5b470ec08948.png)

**Comment by suziwen** [comment]
如果是想全局控制使用 mathjax 控制，就需要在 `设置>语法扩展>mathjax公式` 选项里选中
![image](https://user-images.githubusercontent.com/57370/31652564-2694c328-b2e5-11e7-991e-1c3b9737e64d.png)

-------------------

如果不想使用全局控制，可以使用元数据标识来打开 mathjax 语法开关，（跟小书匠语法手册一样）

![image](https://user-images.githubusercontent.com/57370/31652692-90fc9ae2-b2e5-11e7-81c0-585b750be17e.png)


----------------

通过元数据标识开关的好处是系统不需要在每篇文章里都对相关的扩展语法进行额外的处理，需要哪些扩展语法，可以动态添加。这也就是为什么`小书匠语法手册` 可以显示公式，但不需要在`设置>语法扩展>mathjax` 里选中的原因。
