### ISSUE TITLE
Firefox ace编辑器如何关掉minimap

### ISSUE THREAD

**Issue by icycandy** [suziwen/markdownxiaoshujiang#58]
![minimap](https://cloud.githubusercontent.com/assets/724257/8302297/efc45d44-19c7-11e5-9e57-bd7c0128411d.png)

Firefox的ace编辑器会一直显示minimap，Chrome不会。

**Comment by suziwen** [comment]
编辑器的minimap在 `设置` 里的 `编辑器`下

![image](https://cloud.githubusercontent.com/assets/57370/8304668/9291b456-19da-11e5-9b0c-bb29cfdf1838.png)

**Comment by icycandy** [comment]
get it :)
