### ISSUE TITLE
web版本无法绑定印象笔记了

### ISSUE THREAD

**Issue by kehaozi** [suziwen/markdownxiaoshujiang#580]
在web版本，突然发现无法保存到印象笔记，再看，绑定失效了，尝试重新绑定，看到印象笔记的设置里面，授权访问，已经可以看到对小书匠授权了，但是在小书匠的web页面里，是没有绑定的，也就无法同步到印象笔记。希望尽快解决

**Comment by suziwen** [comment]
小书匠取消绑定是没有到印象服务器请求删除授权的，只是删除了浏览器里保存的 token,需要用户自己到印象笔记设置里自己取消。

重新绑定一下就可以了。

**Comment by kehaozi** [comment]
您好，chrome尝试重新绑定：页面弹出显示已经授权，但是确定按钮是灰色的。换了别的浏览器IE也不行.希望尽快解决。
![image](https://user-images.githubusercontent.com/18926787/31701787-4f9776aa-b405-11e7-937a-ebf996ace087.png)
