### ISSUE TITLE
web版本无法绑定到印象笔记

### ISSUE THREAD

**Issue by kehaozi** [suziwen/markdownxiaoshujiang#581]
![image](https://user-images.githubusercontent.com/18926787/31701809-729a797c-b405-11e7-933c-721537668466.png)
您好，chrome尝试重新绑定：页面弹出显示已经授权，但是确定按钮是灰色的。换了别的浏览器IE也不行.希望尽快解决。

看到问题已经被close了，所以重开issue。
当前是无法保存文档到印象笔记了。因为这种情况，一直提示未绑定。

**Comment by suziwen** [comment]
你点击下 __重新授权__

**Comment by kehaozi** [comment]
重新授权，效果和上述一样，还是不能绑定。

**Comment by kehaozi** [comment]
点击重新授权后，  重新授权按钮点击后，跳转页面空白，小书匠的确认按钮还是灰色的。

![image](https://user-images.githubusercontent.com/18926787/31705445-fdc044f2-b417-11e7-82de-5cf0ae93caad.png)

**Comment by suziwen** [comment]
好了，再点击重新授权按钮下，就不会了现空白页面了。

**Comment by kehaozi** [comment]
再次点击 重新授权，依然弹出空白页面，清空缓存，关闭浏览器。访问小书匠，还是未绑定状态。

![image](https://user-images.githubusercontent.com/18926787/31711890-241386dc-b42c-11e7-80c2-cb43562767ea.png)

**Comment by suziwen** [comment]
你使用隐身会话，绑定呢？
或者 https://markdown.xiaoshujiang.com 下试试呢。

我这边不管是 http, https 或者其他的都不会再出现 `点击重新授权,就跳转成空白页面` 的情况

**Comment by kehaozi** [comment]
清空浏览器所有历史缓存，关闭浏览器，重新打开浏览器，可以绑定印象笔记了。
及时修复bug 。赞！

**Comment by kehaozi** [comment]
可以close该问题了。确认解决了。
