### ISSUE TITLE
码云私有仓库依然不可用

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#582]
并不行啊。。还是显示这个。。检测失败，没有找到相应的仓库或者分支。
而且并没给我一个选择权限的对话框啊，直接就让我选仓库了。。我把仓库改成了公有之后就可以用了。。但是有些文章并不太适合开源出来，还是希望可以用私有仓库。

1. 解绑
![2017-10-18_19h00_07](https://user-images.githubusercontent.com/23495987/31715759-a2ed3592-b437-11e7-8038-7f103582a2b6.png)
2. 登录
![2017-10-18_19h02_26](https://user-images.githubusercontent.com/23495987/31715760-a32a3f32-b437-11e7-8263-afa0fb3a2b27.png)
3. 并没有弹出权限选择窗口，直接让我选仓库
![2017-10-18_19h02_44](https://user-images.githubusercontent.com/23495987/31715763-a3628cac-b437-11e7-8542-0d59c3822884.png)
4. 输入仓库
![2017-10-18_19h02_57](https://user-images.githubusercontent.com/23495987/31715764-a39c0748-b437-11e7-919c-3a68f4d13deb.png)
5. 报错
![2017-10-18_19h03_05](https://user-images.githubusercontent.com/23495987/31715765-a3dad4e6-b437-11e7-9f87-e5b0182efa7d.png)
全程控制台无相关报错。

**Comment by suziwen** [comment]
你那个私有仓库没有初始化？也就是需要先自己先添加一个文件（或者创建的时候默认添加个 readme.md）

**Comment by panhaoyu** [comment]
有初始化的呀。。切换公有之后就可以用的

**Comment by suziwen** [comment]
你的认证没有弹出这个页面？ 你使用的是什么浏览器，换一个浏览器呢？还是你那码云帐号比较特殊？
![image](https://user-images.githubusercontent.com/57370/31770281-b87ffdee-b49c-11e7-97f5-ac185f96f5c5.png)

**Comment by suziwen** [comment]
我这边用自己的帐号，不管是私有的仓库还是公开的，都能正常绑定使用的。

**Comment by panhaoyu** [comment]
以前是有这个界面的。。

我新建了一个码云账号，是可用的。。

我去找码云客服问问试试吧。。有结果的话我反馈给你。
