### ISSUE TITLE
设置页面切换标签页无法提交数据

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#583]
![default](https://user-images.githubusercontent.com/23495987/31778862-4eb1b7da-b524-11e7-86b2-7c1102fd592c.png)
就这个页面里，比如我修改了《基本》页里的东西，然后不保存，切换到《全屏》标签页，点击《确认》按扭，则无法提交《基本》页面的内容。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
