### ISSUE TITLE
希望可以支持Pelican的元数据格式

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#584]
Pelican是Python的静态博客生成器。

因为平时Python用的多，用Python写插件比较顺手。。

样例：

```
Title: 我的标题
Date: 2017-10-19 23:00
Summary: 文档摘要

这里是文档正文。
```

并希望可以提供更好的文章初始化功能。。或者至少给一点点文档？

我是靠样例里的print函数摸索出来的。。

辛苦大佬了！

**Comment by suziwen** [comment]
这个要再考虑下
感觉这种格式的写法，支持的地方并不多，反倒我觉得是他家应该兼容 github 的格式来写。

小书匠目前提供的元数据格式主要是参考了 github. 

```
---
title: 2017-10-16 工作日志
tags: [工作日志,小书匠]
grammar_cjkRuby: true
---
```
github 可以把元数据识别到表格里
![image](https://user-images.githubusercontent.com/57370/31798388-03cb48ce-b4f9-11e7-84fc-ebe467773218.png)

**Comment by panhaoyu** [comment]
好吧。。你说的对，Python的这个确实有点反人类。。那我给Python的Markdown加个插件好了
