### ISSUE TITLE
能否自定义数据库目录？

### ISSUE THREAD

**Issue by jerry011235** [suziwen/markdownxiaoshujiang#586]
1.能否自定义数据库目录？
数据库文件路径
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
希望可以自定义。

2.能否做个便携版，解压就能用，数据库目录默认在解压后的目录里。

**Comment by suziwen** [comment]
1. #503
2. 这个可以通过写个启动脚本放在安装目录里，然后把安装目录拷贝走，以后想启动时，直接执行脚本就可以了。类似脚本(linux 版本)
my.sh
```
#!/bin/bash
./Story-writer --user-data-dir=./mydata
```
然后 
```
chmod +x my.sh
./my.sh
```

**Comment by jerry011235** [comment]
感谢，我是win，所以 start.cmd
```
@echo off
start "" "%~dp0Story-writer.exe" --user-data-dir=./mydata
```
另发现直接在快捷方式目标后加此参数也能成功。
