### ISSUE TITLE
本地客户端用wavedrom功能直接卡死

### ISSUE THREAD

**Issue by himingway** [suziwen/markdownxiaoshujiang#587]
windows10 64位系统，本地客户端用wavedrom功能直接卡死，CPU占用非常高

**Comment by himingway** [comment]
![default](https://user-images.githubusercontent.com/8113875/32035025-ffcffd3c-ba48-11e7-9172-9c0838faf7f7.png)

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
