### ISSUE TITLE
关于印象笔记取消token

### ISSUE THREAD

**Issue by CoderGFWu** [suziwen/markdownxiaoshujiang#588]
印象笔记取消了token, 该如何操作

**Comment by suziwen** [comment]
#532 

可以先参考[这个](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-9-17%20%E5%85%B3%E4%BA%8E%20Evernote(%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0)%20%E5%81%9C%E6%AD%A2%E4%BD%BF%E7%94%A8%20Developer%20Token%2C%E5%B0%8F%E4%B9%A6%E5%8C%A0%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%8D%E8%83%BD%E7%BB%91%E5%AE%9A%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.md)，通过 http://markdown.xiaoshujiang.com 获取 token
