### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by sunweilibo** [suziwen/markdownxiaoshujiang#590]
图片不显示，总是在对应位置显示 “附件”，从预览区点击附件可以打开图片

**Comment by suziwen** [comment]
`小书匠主按钮>设置>预览>是否自动转换非图片扩展名为附件` ,把 `是否自动转换非图片扩展名为附件` 取消掉就可以了

![image](https://user-images.githubusercontent.com/57370/32261769-d1074a96-be9e-11e7-9d71-2bae8f8cdb4e.png)
