### ISSUE TITLE
小小的bug，数学公式问题

### ISSUE THREAD

**Issue by himingway** [suziwen/markdownxiaoshujiang#591]
数学公式解析不正确：

> $T_∞ = \mathop {\max }\limits_{{\rm{l}} \in L} \{ \frac{{{t_l}}}{{{w_l}}}\}$

![image](https://user-images.githubusercontent.com/8113875/32261071-1e5081ba-bf07-11e7-9b12-55a632a66ef9.png)

正确的应该是：（网页mathjax解析）
![image](https://user-images.githubusercontent.com/8113875/32261093-3cc138ce-bf07-11e7-88da-cebb8c932ace.png)

不影响使用，强迫症哈哈哈~

**Comment by suziwen** [comment]
要使用块级公式

--------

行内公式
```
$T_∞ = \mathop {\max }\limits_{{\rm{l}} \in L} { \frac{{{t_l}}}{{{w_l}}}}$
```
块级公式
```
$$T_∞ = \mathop {\max }\limits_{{\rm{l}} \in L} { \frac{{{t_l}}}{{{w_l}}}}$$
```

![image](https://user-images.githubusercontent.com/57370/32261730-75b715c2-be9e-11e7-95c4-74c555d10fdd.png)

**Comment by himingway** [comment]
好的～
