### ISSUE TITLE
Ubuntu 16.04 导出pdf失败

### ISSUE THREAD

**Issue by BenjaminXiang** [suziwen/markdownxiaoshujiang#592]
客户端在Ubuntu 16.04 下导出pdf 生成文件为0字节 有时会同时出现 xxx.pdf 和 xxx.pdf.crdownload文件但都无法打开

**Comment by suziwen** [comment]
是所有文章的pdf 都导出失败？还是单独这篇？

**Comment by BenjaminXiang** [comment]
尝试其他的也都失败了，重启软件，重启系统都没有奏效。Ubuntu下网页版不受影响。

**Comment by suziwen** [comment]
我这边 fedora 下没问题， ubuntu  16.04 没安装，不过差别应该不大，都是 linux 环境。
以前能正常导出 pdf 吗？现在导出 html 会不会也失败？
客户端是什么版本

**Comment by BenjaminXiang** [comment]
客户端是4.2.1之前一直没问题某一次出了问题 后面就一直失败 估计这个问题不好复现
我先用客户端编辑 需要导出的时候用网页版吧

**Comment by suziwen** [comment]
感觉是设置里哪个地方配置错了
自定义 css? 或者是 pdf 导出的设置做了哪些修改，比如封面，或者水印等
