### ISSUE TITLE
Mac下写博客的时候会异常卡顿哦

### ISSUE THREAD

**Issue by wumuzi520** [suziwen/markdownxiaoshujiang#593]

**Comment by suziwen** [comment]
客户端版本号是多少？
使用小书匠哪个内置编辑器?
![image](https://user-images.githubusercontent.com/57370/32325042-6271a4ac-bf9b-11e7-84f0-7806c236ea36.png)

**Comment by wumuzi520** [comment]
可能和之前的一个issue一样，没有归档导致的吧






祝 身体健康 工作顺利！
——————————————————————
祝森林


原始邮件
发件人:苏滋文notifications@github.com
收件人:suziwen/markdownxiaoshujiangmarkdownxiaoshujiang@noreply.github.com
抄送:wumuzi520wumuzi520@126.com; Authorauthor@noreply.github.com
发送时间:2017年11月2日(周四) 19:59
主题:Re: [suziwen/markdownxiaoshujiang] Mac下写博客的时候会异常卡顿哦 (#593)


客户端版本号是多少？
 使用小书匠哪个内置编辑器?
