### ISSUE TITLE
gitlab.com/码云无法绑定

### ISSUE THREAD

**Issue by flyuuu** [suziwen/markdownxiaoshujiang#594]
如题，是我操作失误，还是确实有bug

**Comment by suziwen** [comment]
码云： #589
gitlab.com: 有报什么错误没？我这边可以绑定的

**Comment by flyuuu** [comment]
码云登录后，就到码云的登录网页去了，登录后没有跳转，没有跳转之类的选项。求一个教程

**Comment by edocevol** [comment]
@suziwen, 代理的问题可以告诉大家使用proxifier软件，就可以了。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
