### ISSUE TITLE
客户端无法绑定印象笔记

### ISSUE THREAD

**Issue by lgdlkq** [suziwen/markdownxiaoshujiang#595]
如题：客户端无法绑定印象笔记，但web端可以绑定使用，web端绑定了客户端却还是同步不过来。
系统：win10 64位专业版

**Comment by suziwen** [comment]
#532 
可以先参考[这个](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-9-17%20%E5%85%B3%E4%BA%8E%20Evernote(%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0)%20%E5%81%9C%E6%AD%A2%E4%BD%BF%E7%94%A8%20Developer%20Token%2C%E5%B0%8F%E4%B9%A6%E5%8C%A0%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%8D%E8%83%BD%E7%BB%91%E5%AE%9A%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.md)，通过 http://markdown.xiaoshujiang.com 获取 token

-------------

小书匠目前各个客户端和 web 是独立的，之间数据，配置不互通。

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
