### ISSUE TITLE
发布到wordpress出错：Unknown XML-RPC tag 'TITLE' 301 Moved Permanently

### ISSUE THREAD

**Issue by crifan** [suziwen/markdownxiaoshujiang#596]
帖子中已写了元数据：
```
weblog_post_type: post
weblog_title: 【整理】正则表达式的示例
weblog_categories: [RegularExpression]
weblog_mt_keywords: [正则表达式,举例,Python]
weblog_wp_slug: summary_regular_expression_examples
weblog_post_status: draft
weblog_mt_allow_comments: open
```

以及填写了必要的信息：
博客地址: `https://www.crifan.com/xmlrpc.php`
用户名: xxx
密码: xxx
点击 发送，去尝试去发布到自己的支持XML-RPC MetaWeblog API的wordpress网站时
出错：
```
发送失败：(statusCode:301; statusMessage:Moved Permanently)
服务器返回了不能识别的标签：Unknown XML-RPC tag 'TITLE' 
<html> <head><title>301 Moved Permanently</title></head> <body bgcolor="white"> <center><h1>301 Moved Permanently</h1></center> <hr><center>nginx</center> </body> </html>
```

如图:
[Unknown XML-RPC tag](http://or65gc2qf.bkt.clouddn.com/17-11-3/20443773.jpg)

换成：
```
weblog_post_type: post
weblog_content.title: 【整理】正则表达式的示例
weblog_content.categories: [RegularExpression]
weblog_content.mt_keywords: [正则表达式,举例,Python]
weblog_content.wp_slug: summary_regular_expression_examples
weblog_content.post_status: draft
weblog_content.mt_allow_comments: open
```
错误依旧。

换成：
```
weblog_post_type: post
weblog_content: {
    "title": "【整理】正则表达式的示例",
    "categories": ["RegularExpression"],
    "mt_keywords": ["正则表达式","举例","Python"],
    "wp_slug": "summary_regular_expression_examples",
    "post_status": "draft",
    "mt_allow_comments": "open"
}
```
错误依旧。
->
所以感觉是：
- 要么是：小书匠内部（用的js库的xmlrpc？MetaWeblog？的库）有bug？
    - 那请作者及时修复
- 要么是：小书匠内部就还是彻底不支持 wordpress的xmlrpc？
    - 那请作者及时添加支持发布帖子到wordpress
        - wordprss官网接口详见：[XML-RPC MetaWeblog API - WordPress 中文文档](http://codex.wordpress.org.cn/XML-RPC_MetaWeblog_API)
- 要么是：此处wordpress的xmrpc的content的结构体的对应的写法，此处自己没有写对？
    - 请给出正确的写法

详细过程，参见我的帖子：
[【未解决】小书匠发布帖子到支持XML-RPC MetaWeblog接口的Wordpress出错：Unknown XML-RPC tag TIT](http://note.youdao.com/noteshare?id=517858e7dbc57bb3cabeb680ab248271)

**Comment by suziwen** [comment]
https://github.com/suziwen/markdownxiaoshujiang/issues/530#issuecomment-330713334

暂时处理不了重定向的问题，下个版本再修复。

**Comment by crifan** [comment]
@suziwen 谢谢。希望可以尽快修复哈。你的软件做的很不错，功能很赞，我打算现在就去买你的会员。😄

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
