### ISSUE TITLE
腾讯云仍然连不上

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#598]
https://github.com/suziwen/markdownxiaoshujiang/issues/461?_pjax=%23js-repo-pjax-container
这是之前你回复的，关闭了。
但是确实连不上，下面也有别人回复，跟我的是一样的，我保证设置的没有任何问题。

**Comment by suziwen** [comment]
能给我一个你连不上腾讯云的 secretid, key, bucketname等账号吗，我测试下。可以发到我邮箱 suziwen1@gmail.com

![image](https://user-images.githubusercontent.com/57370/32430321-be968006-c309-11e7-9c0a-e49ad41bdae8.png)

**Comment by suziwen** [comment]
在腾讯云的基础配置里，把跨域打开

![screenshot_2017-11-16_14-18-28](https://user-images.githubusercontent.com/57370/32876858-b5608dba-cad9-11e7-8587-efc55cb9e405.png)
