### ISSUE TITLE
小书匠缺一个产品经理/交互设计师

### ISSUE THREAD

**Issue by arvinxx** [suziwen/markdownxiaoshujiang#599]
小书匠在功能丰富度层面其实已经远远超过其他任何同类产品，但是在用户体验层面与主流的一些Markdown工具相比还是有一段距离，不知道作者有没有意向找一个产品经理和一交互设计师把小书匠打磨地更加易用一些？
如果有意向，鄙人愿意毛遂自荐一下。
这一篇文章是我关于 Markdown 的部分理解，可作为衡量能力的部分参考。
[基于 Markdown 的文本工作流与写作哲学](http://arvinx.io/2017/markdown-workflow)
如果有意向，可以把联系方式发我邮箱：arvinx@foxmail.com，或者在知乎私信我~
如有打扰，万分抱歉。

**Comment by suziwen** [comment]
感谢你中肯的评价，后面会再慢慢改进用户体验。

主要是现在小书匠还只是很小众，很小众的一款软件，再加上用 markdown 的人本来也不是很多，主要集中在程序员上，用户量上甚至比基他同类 markdown 编辑器 的用户量还少。这样决定了小书匠有相当长一段时间在盈利能力上几乎为零，所以在人员扩充上也暂时还没有什么打算。只能希望以后有机会再一起共事。
