### ISSUE TITLE
导出封面设置问题

### ISSUE THREAD

**Issue by dousp** [suziwen/markdownxiaoshujiang#601]
导出PDF的时候设置了封面背景图片，为什么导出后还是自带的那个呢？我该怎么设置呢
自带的那个好看时好看，但是文字标题什么的不清晰，随机封面太伤眼了。

**Comment by suziwen** [comment]
pdf 加密, 封面，水印这些功能需要会员才能自定义。

非会员的话，只能选择不使用封面功能。
非会员想去除水印只能通过把坐标移出纸张大小的方法来实现。
