### ISSUE TITLE
付费后，在线更新功能是否可用？

### ISSUE THREAD

**Issue by hitjackma** [suziwen/markdownxiaoshujiang#603]
刚开通了会员，测试在浏览器里新建笔记，保存；
而后在客户端数据存储选择一致的“小书匠编辑器存储”，但是没有看到在浏览器里新建的笔记
问题就是：在线更新功能是是否支持浏览器里更新笔记并保存，进一步的，是否可以在一处设置好绑定源（比如印象笔记）而后在浏览器里可以直接同步到绑定的印象笔记上呢
@suziwen ID：@745

**Comment by suziwen** [comment]
可能我那文档描述不准确，引起你的误解。这里的在线更新功能，指的是软件版本的在线更新。会员用户享有更及时的软件功能更新，非会员的话，一般是1到3个月的周期打包更新一个独立客户端版本。

--------

小书匠客户端之间，及客户端与浏览器之间暂不提供数据同步功能。数据都是保存在各自内置的数据库里面，实现离现功能。

-------

你想要的使用场景是 “我点击保存，就直接同步到印象笔记”？

这个功能非会员就可以实现。只要你在绑定界面里(`小书匠主按钮>绑定`),绑定完印象笔记后，**记得选中它，并点击确定按钮**，这样以后新建的文章，保存时，就会自动同步保存到印象笔记里（第一次保存时，会弹出提示，让你选择保存的位置，以后点击保存就直接同步保存了）。以前的文章，可以选择另存为，下次再直接保存，也就可以直接同步保存了。更详细的说明，可以看下内置文档里《小书匠使用手册》里的印象笔记章节。

**Comment by hitjackma** [comment]
希望能实现：在家里客户端绑定好印象笔记之后，在别台电脑上用浏览器登录小书匠，依然绑定着之前设置的印象笔记，这样没有固定PC的使用方便一些。也就是说内容数据不由小书匠同步，而绑定信息同步。

不知道讲清楚没有

**Comment by suziwen** [comment]
#529

**Comment by suziwen** [comment]
最新版本 5.0.0 已经发布,提供了数据中心和配置参数同步功能

**Comment by hitjackma** [comment]
苏总效率可以啊，点赞
