### ISSUE TITLE
文件另存为

### ISSUE THREAD

**Issue by Jumpin2** [suziwen/markdownxiaoshujiang#608]
目前我使用小书匠，evernote，坚果云工作
有几个问题可以优化：

1. 当我使用小书匠的`本地文件系统`绑定我的本地文件夹（比如坚果云同步文件夹），此时想把文件保存到evernote，需要依次选择`另存为` - `选择其他绑定` - `evernote` - `目标文件夹`。
这个过程显得繁琐，希望可以增加快捷键或者简化操作

2. 希望能够在文档库实现文件夹的操作与同步。比如，本地文件系统中可以导入文件夹编辑，也可以保存文件夹。
否则，我在本地编辑了多个文件，想利用小书匠同步到evernote，需要手动保存多个文件夹中的多个文件，有些麻烦。

3. 希望增加不同客户端用户信息的同步功能，比如用户设置

4. 个人觉得 typora 的实时预览功能比两栏预览模式更便于交互，不会打乱写作思路。目前我编辑文件仍然喜欢用 typora，文件管理使用小书匠。如果能实现实时预览就十分完美了。

**Comment by suziwen** [comment]
1. 这个反而觉得过度设计了，一般情况下都是选择一个绑定存储，基本就在这个绑定下操作了。你这种情形感觉是自己想多个地方保存，多些文件安全的保证（比如存储服务器停止运营服务了），但这已经超出小书匠的范围了。
2. 没理解使用场景 :grey_question: 
3. #529 
4. #285

**Comment by suziwen** [comment]
最新版本 5.0.0 已经发布,提供了数据中心和配置参数同步功能
