### ISSUE TITLE
升级新版的时候，原来的文章没有了

### ISSUE THREAD

**Issue by tiankongjintou** [suziwen/markdownxiaoshujiang#609]
右上方的....显示是有的，但是左上方没有。点击右上方的那些文章，提示文件已经被删除
![image](https://user-images.githubusercontent.com/7948351/33105036-37b3722e-cf66-11e7-8632-c6828fd53b2c.png)

**Comment by suziwen** [comment]
从哪个版本升级到哪个版本？

**Comment by tiankongjintou** [comment]
您在啊。哈哈，谢谢，我已经解决了。
需要导出和导入数据。
需要吐槽的地方是：导出只能导一个月的，全部导出，则是空的，还好，我的时间短。
不过话说回来了。
您的这个工具真的很不错。爱上写作。

**Comment by tiankongjintou** [comment]
我决定支持一下你，两年会员已送上。

**Comment by suziwen** [comment]
导出全部还真的有 bug, 不过可以把时间范围扩大，超过一个月也可以导出的。

**Comment by tiankongjintou** [comment]
没事，这都是小问题。我觉得，你可以搞个众筹。
马克飞象功能比你的差远了，还拉磨贵。真心觉得你这是良心之做啊。
所以即便用不到付费功能，还是买了两年会员。
哈哈，关键是价格还很便宜。

**Comment by tiankongjintou** [comment]
顺便问一下，那个脑图你是用啥软件做的。

**Comment by suziwen** [comment]
https://coggle.it/

**Comment by tiankongjintou** [comment]
得翻墙？
现在
咋翻墙？

**Comment by suziwen** [comment]
嗯，好像是登录，注册得翻墙。
