### ISSUE TITLE
关于印象笔记与小书匠的结合使用

### ISSUE THREAD

**Issue by giswangjian** [suziwen/markdownxiaoshujiang#615]
请问：
       能否添加以下两种功能：
           1. 对笔记本排序（比如按照数字大小的顺序）
           2。增加搜索笔记本的功能，笔记本多的情况下，找起来不是太方便

**Comment by suziwen** [comment]
排序的话，可以在这里调整

![](https://cloud.githubusercontent.com/assets/57370/22094017/ec59dc24-ddcf-11e6-80f2-009f1b7ec6bf.png)

搜索功能后面再考虑添加.

**Comment by giswangjian** [comment]
ok
