### ISSUE TITLE
小书匠客户端在win10上无法正常打开

### ISSUE THREAD

**Issue by 6sofer** [suziwen/markdownxiaoshujiang#616]
[屏幕截图](http://note.youdao.com/noteshare?id=fc9b9a57410ecf0f49d299c97d548a9f)
[](https://github.com/6sofer/note/blob/master/images/360%E6%88%AA%E5%9B%BE17930726109128148.png?raw=true)
就一直卡在这个界面，把软件完全卸载，重新安装后，还是卡在这里。重启电脑也不管用，不知道这是为什么？？

**Comment by suziwen** [comment]
试着先把 数据文件位置移到其他地方，再启动。
```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```

**Comment by 6sofer** [comment]
软件可以启动了，但是之前的笔记都没有了，如果我要找回原来的笔记该怎么做？谢谢您了suziwen

**Comment by 6sofer** [comment]
预览的水印效果，按 " ctrl+shift+[ "快捷组合键无法推出。在win10和win7上都是这样，我都试了不行，有没有其他的推出方式？
建议：在主窗口菜单栏 加个控制按钮。因为在水印预览效果下预览图窗的小菜单栏是无法使用的。
[附件图片](http://note.youdao.com/noteshare?id=0444e87a9cca9194c9a37f06aa206388)

**Comment by suziwen** [comment]
想要之前的笔记，就得继续使用原有的数据文件。把移动到其他位置的数据文件重新移回来。
```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```
然后在桌面右键新建一个扩展名为 `md` 的空白文件，直接双击这个空白文件。应该就能启动起来。

**Comment by suziwen** [comment]
水印预览客户端无法退出，目前还是个 bug
#536

**Comment by 6sofer** [comment]
好的，非常感谢

**Comment by suziwen** [comment]
最新版本 5.0.0 已经修复发布
