### ISSUE TITLE
无法按照规则上传文件

### ISSUE THREAD

**Issue by chefish** [suziwen/markdownxiaoshujiang#617]
我的图床绑定了七牛，上面写着可以用  /小书匠/{{filename}}  这种规则配置文件名
，所以我改为了   /小书匠/{{year}}/{{month}}/{{day}}/{{filename}}    希望输出年月日相关信息，但是实际上并没有用

**Comment by suziwen** [comment]
把 `day` 改成 `date`
```
/小书匠/{{year}}/{{month}}/{{day}}/{{filename}}
```
改成 

```
/小书匠/{{year}}/{{month}}/{{date}}/{{filename}}
```

**Comment by chefish** [comment]
非常感谢！
