### ISSUE TITLE
我居然没找到windows客户端如何登录？

### ISSUE THREAD

**Issue by nonpool** [suziwen/markdownxiaoshujiang#618]
是我探索能力太差了么？
另外 对比市面上的笔记软件
小书匠让我眼前一亮
非常适合程序员的笔记软件
自定义图床 自定义发布 自定义保存等等都是非常抢眼的功能
希望小书匠发展壮大 
我真的不希望在各种笔记软件之间切换了~

**Comment by suziwen** [comment]
下次最新客户端(或者直接浏览器访问小书匠),然后 `小书匠主按钮>用户`
