### ISSUE TITLE
同步到印象笔记以后代码格式的问题

### ISSUE THREAD

**Issue by nonpool** [suziwen/markdownxiaoshujiang#619]
行间距和有些空行直接就是没背景色 感觉看上去很奇怪
![](https://www.github.com/bulecode/storyImg/raw/master/%E5%B0%8F%E4%B9%A6%E5%8C%A0/QQ%E6%88%AA%E5%9B%BE20171203221259.jpg)
![](https://www.github.com/bulecode/storyImg/raw/master/%E5%B0%8F%E4%B9%A6%E5%8C%A0/QQ%E6%88%AA%E5%9B%BE20171203221314.jpg)

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/33540122-830a8756-d904-11e7-996b-0b526597fc42.png)

**Comment by nonpool** [comment]
这就奇怪了…… 难道是设置的问题？

**Comment by suziwen** [comment]
小书匠版本？使用的是印象客户端查看还是他们的网页版查看？

**Comment by CoderGrowing** [comment]
同样有这样的问题，小书匠4.0.0，使用印象笔记客户端查看时代码间隔没有背景色，网页版和Android版正常。

另外我想问下小书匠同步到印象的默认字体大小可以更改么？我找了半天只能更改小书匠自身预览区和编辑器文字的大小，同步到印象之后正文字体大小只有10px，代码只有8px。

**Comment by CoderGrowing** [comment]
另外还有两个问题，第一，小书匠当前笔记列表里可以同步显示印象的笔记列表么？如何开启显示？
第二，小书匠保存到印象的笔记默认都有保存了正文内容的附件，强迫症看起来实在是。。别扭，可以关闭这个功能么？
谢谢！

**Comment by nonpool** [comment]
我的小书匠版本是最新的4.2.1 同步以后在印象windows客户端查看的

**Comment by suziwen** [comment]
1. 这个感觉应该是印象笔记官方自己要解决的问题，他们家同样的 html 片段在不同客户端显示效果不一致。目前小书匠只能在符合他们规定的 enml 标签上，保证网页版显示正确。至于客户端，android 等只能尽量调整了，毕竟他们家的客户端没有像网页版那样有调试工具可以用。
2. 可以调整，你自定义 css 的时候，字体不要放到 body 上，放到更近一些的，比如 
```
.preview{
  font-size: 30px;
}
```
3. 绑定完印象笔记后，回到绑定对话框，记得点击`选择`， 再点击`确定`
![image](https://user-images.githubusercontent.com/57370/33792218-f35d7576-dcd4-11e7-8282-21d785ecfa07.png)
4. 这个暂时去不了，附件是为了保证用户下次通过小书匠点击对应的印象笔记时，如果印象笔记没有在其他平台修改过，可以直接使用附件里的 markdow 内容,而不是通过  html 转成 markdown 这样的方式。

**Comment by CoderGrowing** [comment]
感谢！问题已解决
