### ISSUE TITLE
package 版打不开

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#62]
package 版打不开，win7 64bit。试过chrome 43，firefox 39，ie 11，都是加载到最后就听了

**Comment by suziwen** [comment]
package版本得自己下载个 [nwjs](https://github.com/nwjs/nw.js) (0.12.2版本), 然后把package解压后放到nwjs目录下,再点击nwjs.exe启动.

并不是直接点击index.html来打开的.

**Comment by oska874** [comment]
可以打开了，但是一旦点击到其他文档，程序立马死掉
