### ISSUE TITLE
上传博客报错

### ISSUE THREAD

**Issue by flyuuu** [suziwen/markdownxiaoshujiang#620]
发布日志的时候显示：
发送失败： Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by suziwen** [comment]
没遇到过这种错误，可能跟你具体的操作系统设置或者网络环境有关。

**Comment by flyuuu** [comment]
好的，谢谢哦~

**Comment by tiankongjintou** [comment]
估计你是没有啊链接对。

**Comment by flyuuu** [comment]
最后查出来，确实是连接有问题： 没加 http://
