### ISSUE TITLE
win7安装报病毒是什么情况

### ISSUE THREAD

**Issue by lig8** [suziwen/markdownxiaoshujiang#623]
### win7安装报病毒是什么情况，我是从你的百度云盘下载的
![1](https://user-images.githubusercontent.com/26920495/33754394-fdb638d6-dc26-11e7-833a-fc75c5adac1e.png)

**Comment by suziwen** [comment]
这是 win64 4.0.0 版本的 md5sum 值，如果下载下来的值一样，就没有病毒，可能是 360 误报
```
94e5470f4fa5d3789c1f7811f9c2c612  Story-writer-win64-setup.exe
```
