### ISSUE TITLE
你好，生成目录的字体大小可以调节吗

### ISSUE THREAD

**Issue by lig8** [suziwen/markdownxiaoshujiang#624]
你好，生成目录的字体大小可以调节吗，目录字体和正文字体大小不一样，太难看，没找到可以设置目录字体的地方

**Comment by lig8** [comment]
你好，生成目录的字体大小可以调节吗

**Comment by tiankongjintou** [comment]
应该可以吧。我找找看看，看看能不能帮上忙。

**Comment by tiankongjintou** [comment]
目录都是在下面这个tag中
<div class="toc"><ul><ul><ul><li>

你可以在导出的时候，在这里定义
![image](https://user-images.githubusercontent.com/7948351/33762686-61f8b0fa-dc48-11e7-97a0-37464ff84738.png)
也可以在这里，定义预览区的样式，
![image](https://user-images.githubusercontent.com/7948351/33762725-929581d4-dc48-11e7-83ba-3ef5d8f2591d.png)
剩下的就是jquery和css的事情了，用jquery来筛选标签，然后用sytle来定义样式了。
我只是知道怎么弄，但是jquery用的不是很熟练。
等我有这个需要以后，我再看看能不能详细写个教程了。

**Comment by suziwen** [comment]
需要自己自定义 css 来修改预览区的字体
