### ISSUE TITLE
更新5.0.0之后全部数据没了

### ISSUE THREAD

**Issue by pinsily** [suziwen/markdownxiaoshujiang#627]
更新之后，相当于刚开始安装的一样，之前设置的、写的内容都是没的，一片空白，请问这是怎么回事，毕竟是几个月的笔记和一些记录

**Comment by suziwen** [comment]
你是从什么版本更新过来的？

**Comment by pinsily** [comment]
从上一个最新版本，记得上次更新的时候是没有问题的

**Comment by suziwen** [comment]
`4.*.* `版本升级过来的，是不会删除数据目录的文件，除非你删除程序时有第三方安全软件帮你把数据文件清空的可能。

感觉你并不是从 `4.*.*` 版本升级到 `5.0.0` 的。

--------

看下自己的数据目录
数据目录

```
Windows: %LOCALAPPDATA%/storywriter/ 
Mac: ~/Library/Application Support/storywriter/ 
Linux: ~/.config/storywriter 
```

如果版本比较早（`4.0.0` 以前），数据目录
```
Windows: %LOCALAPPDATA%/小书匠/
Mac: ~/Library/Application Support/小书匠/
Linux: ~/.config/小书匠
```

**Comment by giantbranch** [comment]
版本3.x升级的怎么恢复，直接用小书匠的覆盖storywriter目录就行了吗

**Comment by suziwen** [comment]
@giantbranch 
3.x 版本升级的话，直接再装下那个老版本，然后使用小书匠数据导出功能，导出数据库，再安装 5.x 版本，导入，最方便。

不能直接覆盖 storywriter ，里面的目录不一样了。

**Comment by pinsily** [comment]
我是win10，没有删除原版本的，是直接安装5.0版本的，数据目录下文件如下：
![image](https://user-images.githubusercontent.com/19889043/33820224-5162492a-de89-11e7-8ba2-33dd1800f7a9.png)

![image](https://user-images.githubusercontent.com/19889043/33820245-67c9c13e-de89-11e7-969b-3f1b15b3b4e1.png)

**Comment by suziwen** [comment]
@pinsily 有没有这个目录 `%LOCALAPPDATA%/小书匠/`？

**Comment by giantbranch** [comment]
@suziwen 好的，谢谢

**Comment by pinsily** [comment]
@suziwen 有，是要怎么处理吗

**Comment by suziwen** [comment]
先备份下那个目录文件 ，
然后
找个 3.2.x 版本的小书匠，启动看看里面的文章。

**Comment by pinsily** [comment]
好的，谢啦

**Comment by tiankongjintou** [comment]
不要装在原来的文件夹。。。会自动探测原来的文件夹，但是不要装在原来的文件夹，换个就可以了，会自动导入。

**Comment by tiankongjintou** [comment]
或者，你把原来的卸载以后，再安装。
