### ISSUE TITLE
保存到为知笔记无法查看，手机端查看提示为笔记不存在

### ISSUE THREAD

**Issue by l1nxy** [suziwen/markdownxiaoshujiang#629]
保存到为知笔记打不开，显示为笔记加载失败，手机端为安卓。
平台为MacOS。
为知上的笔记显示为带了一个附件。

**Comment by suziwen** [comment]
最好能提供一个重现的文章给我测试

**Comment by l1nxy** [comment]
什么文章都能复现。改已有的文章也会使原文章无法下载查看。

**Comment by suziwen** [comment]
浏览器端，新建一个会话（或者隐身窗口），绑定为知，保存呢？

**Comment by l1nxy** [comment]
一样哎，具体一点是为知的控制台显示的是文件404
小书匠显示显示是对象不存在。

**Comment by suziwen** [comment]
那就奇怪了，我这边没出现你说的情况。

```
ttabc@163.com
ttabc123456
```
这是我用上面的帐号刚测试的文章，正常保存。
https://note.wiz.cn/pages/wiz-flat-doc.html?kb=30d51d47-0c05-41d7-b091-68d9fc5af19f&dc=206a8580-de3e-11e7-8bcb-6de9c60df7bf

**Comment by l1nxy** [comment]
我也用这个号试了一下，真的可以…
但是我自己的号真的不行，我是为知VIP，这个会有什么影响吗。

**Comment by suziwen** [comment]
那这个只能再留意观察了，看是否其他人也会报这种错误，再确认是小书匠还是为知那边的异常。
还是说只有你的账号比较特殊，或者是你的账号有些文章比较特殊，触发了小书匠没有考虑的情况。

**Comment by l1nxy** [comment]
我感觉不是文章的问题啊。什么文章都一样。

**Comment by suziwen** [comment]
你通过为知的 web 版本，用你的账号直接创建文章，上传附件呢？
创建文章时，可以试着用他们的编辑器切换到 html 模式 ,然后把我刚才测试的文章的 html 貼上去，能正常保存吗？

![image](https://user-images.githubusercontent.com/57370/33821041-4539a87e-de8d-11e7-9740-9374637809e4.png)

**Comment by l1nxy** [comment]
html可以正常保存
我在win下测试了，也不能正常查看。

**Comment by l1nxy** [comment]
我去问wiz客服了，看看是什么情况吧

**Comment by suziwen** [comment]
用你的账号，通过为知的 web网页，能正常添加附件吗？

**Comment by l1nxy** [comment]
附件也能正常添加的。

**Comment by suziwen** [comment]
能把你上传附件时， http 请求信息发个过来看看

![image](https://user-images.githubusercontent.com/57370/33834634-871d46d4-debe-11e7-9811-13665c2fe07d.png)

**Comment by l1nxy** [comment]
![image](https://user-images.githubusercontent.com/12152770/33861165-4f65c56e-df17-11e7-8aaa-21a0977e8248.png)

**Comment by suziwen** [comment]
大概知道原因了，
你应该是没有主动打开新版同步方式的用户，然后达到了为知最后强制使用新同步方式的那一批。

**Comment by l1nxy** [comment]
并不觉得啊，小书匠早期版本我就有用啊
![image](https://user-images.githubusercontent.com/12152770/33865450-bf769634-df2c-11e7-9ab0-1633a783d607.png)
这个就是用小书匠写的，也同步成功了，我记得的话应该是用新同步方式同步的。

**Comment by suziwen** [comment]
你用 window wiz客户端 看一下这个选项

![screenshot_2017-12-12_11-16-42](https://user-images.githubusercontent.com/57370/33865859-87bf991e-df2e-11e7-8d8a-cafa930f13d6.png)

**Comment by l1nxy** [comment]
我这个新同步没勾，是不是点上就行了

**Comment by l1nxy** [comment]
解决了，是这个新同步没点上导致的，非常感谢了。
