### ISSUE TITLE
web 版 ppt 预览没法用

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#63]
web 版 ppt 预览没法用，不能翻页。chrome 43

**Comment by suziwen** [comment]
你的markdown内容?

可以参考这个ppt 
[ppt效果](http://markdown.xiaoshujiang.com/#md64=eyJ0aXRsZSI6IuWwj+S5puWMoHBwdOS9v+eUqOekuuS+iyIsImNvbnRlbnQiOiItLS1cbnRpdGxlOiDlsI/kuabljKBwcHTkvb/nlKjnpLrkvotcbnRhZ3M6IOWwj+S5puWMoCwgcHJlc2VudGF0aW9uXG5wcmV2aWV3X3ByZXZpZXdUeXBlOiBwcmVzZW50YXRpb25cbi0tLVxuXG4jIOWwj+S5puWMoHBwdOS9v+eUqOekuuS+i1xuXG4tLS0tXG5cbiMjIOW5u+eBr+eJh1xuXG4xLiAjIyMjIOW5u+eBr+eJh+iDjOaZr1xuMS4gIyMjIyDmsLTlubPlubvnga/niYdcbjIuICMjIyMg5Z6C55u05bm754Gv54mHXG4zLiAjIyMjIOeJh+autVxuXG4tLS0tXG5cbiMjIyDlubvnga/niYfog4zmma9cbmBgYCBodG1sXG48IS0tIC5zbGlkZTogZGF0YS1iYWNrZ3JvdW5kPVwiI2ZmMDAwMFwiIC0tPlxuYGBgXG7mlK/mjIHpopzoibLvvIzlm77niYfvvIzop4bpopHlgZrkuLrog4zmma9cblxuLS0tLVxuXG48IS0tIC5zbGlkZTogZGF0YS1iYWNrZ3JvdW5kPVwiI2ZmMDAwMFwiIC0tPlxuXG4jIyMjICoq6aKc6Imy5bm754Gv54mH6IOM5pmvKipcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtYmFja2dyb3VuZD1cImltZy96ZW4vMy5qcGdcIiAtLT5cblxuIyMjIyAqKuWbvueJh+W5u+eBr+eJh+iDjOaZryoqXG5cbi0tLS1cblxuXG4jIyMg5rC05bmz5bm754Gv54mHXG5cbuivreazle+8mlxuYGBgXG4tLS0tXG5gYGBcbioq5rOo5oSP5YmN5ZCO6YO96ZyA6KaB56m65LiA6KGMKipcblxuXG4tLS0tXG5cbiMjIyDlnoLnm7Tlubvnga/niYdcblxu6K+t5rOV77yaXG5gYGBcbi0tXG5gYGBcbioq5rOo5oSP5YmN5ZCO6YO96ZyA6KaB56m65LiA6KGMKipcblxuLS0tLVxuXG7lnoLnm7Tlubvnga/niYcxXG5cbi0tXG5cbuWeguebtOW5u+eBr+eJh++8klxuXG4tLS0tXG5cbiMjIyDniYfmrrVcblxu6K+t5rOVOlxuYGBgIGh0bWxcbjwhLS0gLmVsZW1lbnQ6IGNsYXNzPVwiZnJhZ21lbnRcIiBkYXRhLWZyYWdtZW50LWluZGV4PVwiMVwiIC0tPlxuYGBgXG7mianlsZXmoLflvI/vvJpcblxuYGBgIGh0bWxcbjwhLS0gLmVsZW1lbnQ6IGNsYXNzPVwiZnJhZ21lbnQ+Pj09IGdyb3c9PTw8XCIgZGF0YS1mcmFnbWVudC1pbmRleD1cIjFcIiAtLT5cbmBgYFxuXG5gZ3Jvd2AsIGBzaHJpbmtgLCBgcm9sbC1pbmAsIGBmYWRlLW91dGAsIGBjdXJyZW50LXZpc2libGVgLCBgaGlnaGxpZ2h0LWN1cnJlbnQtYmx1ZWAsIGBoaWdobGlnaHQtcmVkYCwgYGhpZ2hsaWdodC1ncmVlbmAsIGBoaWdobGlnaHQtYmx1ZWBcblxuLS0tLVxuXG4xLiDniYfmrrXvvJE8IS0tIC5lbGVtZW50OiBjbGFzcz1cImZyYWdtZW50IGdyb3dcIiBkYXRhLWZyYWdtZW50LWluZGV4PVwiMVwiIC0tPlxuMi4g54mH5q6177ySPCEtLSAuZWxlbWVudDogY2xhc3M9XCJmcmFnbWVudCBzaHJpbmtcIiBkYXRhLWZyYWdtZW50LWluZGV4PVwiMlwiIC0tPlxuMy4g54mH5q6177yTPCEtLSAuZWxlbWVudDogY2xhc3M9XCJmcmFnbWVudCByb2xsLWluXCIgZGF0YS1mcmFnbWVudC1pbmRleD1cIjNcIiAtLT5cbjQuIOeJh+aute+8lDwhLS0gLmVsZW1lbnQ6IGNsYXNzPVwiZnJhZ21lbnQgZmFkZS1vdXRcIiBkYXRhLWZyYWdtZW50LWluZGV4PVwiNFwiIC0tPlxuNS4g54mH5q6177yVPCEtLSAuZWxlbWVudDogY2xhc3M9XCJmcmFnbWVudCBjdXJyZW50LXZpc2libGVcIiBkYXRhLWZyYWdtZW50LWluZGV4PVwiNVwiIC0tPlxuNi4g54mH5q6177yWPCEtLSAuZWxlbWVudDogY2xhc3M9XCJmcmFnbWVudCBoaWdobGlnaHQtY3VycmVudC1ibHVlXCIgZGF0YS1mcmFnbWVudC1pbmRleD1cIjZcIiAtLT5cbjcuIOeJh+aute+8lzwhLS0gLmVsZW1lbnQ6IGNsYXNzPVwiZnJhZ21lbnQgaGlnaGxpZ2h0LXJlZFwiIGRhdGEtZnJhZ21lbnQtaW5kZXg9XCI3XCIgLS0+XG44LiDniYfmrrXvvJg8IS0tIC5lbGVtZW50OiBjbGFzcz1cImZyYWdtZW50IGhpZ2hsaWdodC1ncmVlblwiIGRhdGEtZnJhZ21lbnQtaW5kZXg9XCI4XCIgLS0+XG45LiDniYfmrrXvvJk8IS0tIC5lbGVtZW50OiBjbGFzcz1cImZyYWdtZW50IGhpZ2hsaWdodC1ibHVlXCIgZGF0YS1mcmFnbWVudC1pbmRleD1cIjlcIiAtLT5cbjEwLiDniYfmrrXvvJHvvJA8IS0tIC5lbGVtZW50OiBjbGFzcz1cImZyYWdtZW50XCIgZGF0YS1mcmFnbWVudC1pbmRleD1cIjEwXCIgLS0+XG4xMS4g54mH5q6177yR77yRPCEtLSAuZWxlbWVudDogY2xhc3M9XCJmcmFnbWVudFwiIGRhdGEtZnJhZ21lbnQtaW5kZXg9XCIxMVwiIC0tPlxuXG4tLS0tXG5cbiMjIOi9rOWcuuWKqOeUu1xuXG4xLiDliqjnlLvovazlnLpcbjIuIOi9rOWcuumAn+W6plxuMy4g6IOM5pmv5Yqo55S76L2s5Zy6XG5cbi0tLS1cblxuIyMjIOWKqOeUu+i9rOWculxuYGBgaHRtbFxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbj1cInpvb21cIi0tPlxuYGBgXG5cbuaUr+aMgeeahOWKqOeUu1xuYG5vbmVgLCBgZmFkZWAsIGBzbGlkZWAsIGBjb252ZXhgLCBgY29uY2F2ZWAsIGB6b29tYFxuXG4tLS0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLXRyYW5zaXRpb249XCJub25lXCItLT5cblxuIyMjIyDml6DliqjnlLvovazlnLpcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbj1cImZhZGVcIi0tPlxuXG4jIyMjIGZhZGXliqjnlLvovazlnLpcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbj1cInNsaWRlXCIgLS0+XG5cbiMjIyMgc2xpZGXliqjnlLvovazlnLpcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbj1cImNvbnZleFwiLS0+XG5cbiMjIyMgY29udmV45Yqo55S76L2s5Zy6XG5cbi0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLXRyYW5zaXRpb249XCJjb25jYXZlXCItLT5cblxuIyMjIyBjb25jYXZl5Yqo55S76L2s5Zy6XG5cbi0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLXRyYW5zaXRpb249XCJ6b29tXCItLT5cblxuIyMjIyB6b29t5Yqo55S76L2s5Zy6XG5cbi0tLS1cblxuIyMjIOi9rOWcuumAn+W6plxuYGBgIGh0bWxcbjwhLS0gLnNsaWRlOiBkYXRhLXRyYW5zaXRpb24tc3BlZWQ9XCJmYXN0XCItLT5cbmBgYFxu5pSv5oyB55qE5Y+C5pWw5pyJOiBgZGVmYXVsdGAsIGBmYXN0YCwgYHNsb3dgXG5cbi0tLS1cblxuIyMjIyDpu5jorqTovazlnLrpgJ/luqZcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbi1zcGVlZD1cInNsb3dcIi0tPlxuXG4jIyMjIHNsb3fovazlnLrpgJ/luqZcblxuLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtdHJhbnNpdGlvbi1zcGVlZD1cImZhc3RcIi0tPlxuXG4jIyMjIGZhc3TovazlnLrpgJ/luqZcblxuLS0tLVxuXG4jIyMg6IOM5pmv5Yqo55S76L2s5Zy6XG5gYGAgaHRtbFxuPCEtLSAuc2xpZGU6IGRhdGEtYmFja2dyb3VuZC10cmFuc2l0aW9uPVwiem9vbVwiLS0+XG5gYGBcblxu5pSv5oyB55qE5Yqo55S7XG5gbm9uZWAsIGBmYWRlYCwgYHNsaWRlYCwgYGNvbnZleGAsIGBjb25jYXZlYCwgYHpvb21gXG5cbi0tLS1cblxuPCEtLSAuc2xpZGU6IGRhdGEtYmFja2dyb3VuZD1cIiM0ZDdlNjVcIiBkYXRhLWJhY2tncm91bmQtdHJhbnNpdGlvbj1cImNvbnZleFwiLS0+XG5cbiMjIyMgY29udmV46IOM5pmv5Yqo55S76L2s5Zy6XG5cbi0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLWJhY2tncm91bmQ9XCIjNGQ3ZTY1XCIgZGF0YS1iYWNrZ3JvdW5kLXRyYW5zaXRpb249XCJjb25jYXZlXCItLT5cblxuIyMjIyBjb25jYXZl6IOM5pmv5Yqo55S76L2s5Zy6XG5cbi0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLWJhY2tncm91bmQ9XCIjNGQ3ZTY1XCIgZGF0YS1iYWNrZ3JvdW5kLXRyYW5zaXRpb249XCJ6b29tXCItLT5cblxuIyMjIyB6b29t6IOM5pmv5Yqo55S76L2s5Zy6XG5cbi0tXG5cbjwhLS0gLnNsaWRlOiBkYXRhLWJhY2tncm91bmQ9XCIjNGQ3ZTY1XCIgZGF0YS1iYWNrZ3JvdW5kLXRyYW5zaXRpb249XCJzbGlkZVwiLS0+XG5cbiMjIyMgc2xpZGXog4zmma/liqjnlLvovazlnLpcblxuLS0tLVxuXG4jIyMjIOe7hOWQiOaooeW8j+WKqOeUu+i9rOWculxuXG4tLVxuXG48IS0tIC5zbGlkZTogZGF0YS1iYWNrZ3JvdW5kPVwiI2ZmMDAwMFwiIGRhdGEtdHJhbnNpdGlvbj1cInpvb21cIiBkYXRhLXRyYW5zaXRpb24tc3BlZWQ9XCJmYXN0XCItLT5cblxuem9vbSwgZmFzdFxuXG4tLVxuXG48IS0tIC5zbGlkZTogZGF0YS1iYWNrZ3JvdW5kPVwiaW1nL3plbi8zLmpwZ1wiIGRhdGEtYmFja2dyb3VuZC10cmFuc2l0aW9uPVwiY29uY2F2ZVwiIGRhdGEtdHJhbnNpdGlvbj1cInNsaWRlXCIgZGF0YS10cmFuc2l0aW9uLXNwZWVkPVwic2xvd1wiLS0+XG5cbmNvbmNhdmUsIHNsaWRlLCBzbG93XG5cbi0tXG5cblxuPCEtLSAuc2xpZGU6IGRhdGEtYmFja2dyb3VuZD1cIiMwM2M4Y2JcIiBkYXRhLWJhY2tncm91bmQtdHJhbnNpdGlvbj1cImZhZGVcIiBkYXRhLXRyYW5zaXRpb249XCJjb252ZXhcIiBkYXRhLXRyYW5zaXRpb24tc3BlZWQ9XCJkZWZhdWx0XCItLT5cblxuZmFkZSwgY29udmV4LCBkZWZhdWx0XG5cbi0tLS1cblxu6LCi6LCi6KeC6LWPXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuIn0=)

**Comment by oska874** [comment]
找到原因了，要用ppt 预览需要用“----”人工分页。
我以为是自动的呢。看来这个功能我目前使用不到了。
