### ISSUE TITLE
Aliyun的OSS错误

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#637]
验证图片已经传上来了。。却还是无法验证成功。

![default](https://user-images.githubusercontent.com/23495987/33987858-63540b2a-e0fd-11e7-95af-e03a2cdd9263.png)
![default](https://user-images.githubusercontent.com/23495987/33987878-73a72714-e0fd-11e7-8ba5-49ca8a1a819e.png)

**Comment by suziwen** [comment]
是不是防盗链或者跨域设置限制了小书匠无法抓取提交后的验证图片？
你浏览器里 `f12` 看一下网络监听返回的信息。

**Comment by panhaoyu** [comment]
233还真的是，前端果然还得是老司机。

已拦截跨源请求：同源策略禁止读取位于 https://panhaoyu.oss-cn-shanghai.aliyuncs.com/ 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。

但是应该怎么设置呢。。不太懂。。

![default](https://user-images.githubusercontent.com/23495987/34000976-c1ca0804-e129-11e7-82cc-d83225e3e5c3.png)

现在还是绑定不上呀。

**Comment by panhaoyu** [comment]
![default](https://user-images.githubusercontent.com/23495987/34001231-6f58f37c-e12a-11e7-8029-5040377edb03.png)

![default](https://user-images.githubusercontent.com/23495987/34001250-7971b48e-e12a-11e7-892e-298c83af8082.png)

这个也设置了，，还是不行。。原谅一个网页都是后端渲染的菜鸡。。

**Comment by panhaoyu** [comment]
![default](https://user-images.githubusercontent.com/23495987/34001604-63c1d370-e12b-11e7-9521-de2ffd8a7db2.png)

客户端绑定成功

**Comment by suziwen** [comment]
看一下你 f12 网络监听返回的信息

![image](https://user-images.githubusercontent.com/57370/34001663-87e1af00-e12b-11e7-92b3-f801422b4515.png)

**Comment by suziwen** [comment]
客户端默认是关闭跨域设置的， web 端由于浏览器自身安全原因，都是默认打开的。

**Comment by suziwen** [comment]
一般配置这个就够了
![image](https://user-images.githubusercontent.com/57370/34001768-d973e482-e12b-11e7-8a58-d595184c2f63.png)
然后你在阿里云控制台先删除那个验证文件（可能这个文件是以前绑定验证上传成功的）。再通过web 端绑定验证下

**Comment by panhaoyu** [comment]
启动后

![default](https://user-images.githubusercontent.com/23495987/34002176-e1b60f02-e12c-11e7-9154-29c666655c38.png)

绑定失败后

![default](https://user-images.githubusercontent.com/23495987/34002302-2fe8c782-e12d-11e7-911b-1de5047bb199.png)

![default](https://user-images.githubusercontent.com/23495987/34002336-4f4bf7de-e12d-11e7-9b28-0513b831fa6b.png)

删除后再绑定

![default](https://user-images.githubusercontent.com/23495987/34002440-8c491e64-e12d-11e7-99b9-0667fc77a097.png)

此时

![default](https://user-images.githubusercontent.com/23495987/34002468-9de0af7a-e12d-11e7-8780-fcbc5bf5239d.png)

验证文件上传失败

**Comment by panhaoyu** [comment]
![default](https://user-images.githubusercontent.com/23495987/34002539-cd2adfc6-e12d-11e7-9f74-ab5f650494d9.png)

设置成https并没什么用

**Comment by panhaoyu** [comment]
![default](https://user-images.githubusercontent.com/23495987/34002615-0304c1d4-e12e-11e7-90e2-fc05d6e311f6.png)

依然没用

**Comment by suziwen** [comment]
先设置成 `*` 呢

**Comment by suziwen** [comment]
而且你的请求网址怎么会是这个呢
![image](https://user-images.githubusercontent.com/57370/34002876-c65c6010-e12e-11e7-978e-7ef3692c6624.png)
你的入口地址没有加 http:// 或者  https://?

**Comment by panhaoyu** [comment]
可以了！加上https，设置为*就可以了

**Comment by suziwen** [comment]
跨域设置可以再调回http://markdown.xiaoshujiang.com

**Comment by panhaoyu** [comment]
最后的唯一的成功的配置

![default](https://user-images.githubusercontent.com/23495987/34003379-1a41e168-e130-11e7-8ac6-6a3ec228e839.png)

![default](https://user-images.githubusercontent.com/23495987/34003433-31c032cc-e130-11e7-9e54-7fede1a841e1.png)

**Comment by panhaoyu** [comment]
有时间的话尽量简化吧。。至少多加点提示，调回http/md.xsj.com之后没法用http的

**Comment by suziwen** [comment]
同时加http://markdown.xiaoshujiang.com 和https://markdown.xiaoshujiang.com 好像浏览器不允许吧。

**Comment by panhaoyu** [comment]
上一条删了。。accesskey忘了打码。。

**Comment by suziwen** [comment]
accesskey可以在控制台收回，再新申请

**Comment by panhaoyu** [comment]
不懂。。前端的世界太玄幻了

**Comment by suziwen** [comment]
这些都是些安全策略，前后端都需要了解的。后端开放的api,也是要提供跨域设置 😄

**Comment by panhaoyu** [comment]
学无止境呀

**Comment by panhaoyu** [comment]
其实也就是业余敲敲代码。。写得爽自已用的爽就可以了233
