### ISSUE TITLE
行高显示存在问题

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#639]
![default](https://user-images.githubusercontent.com/23495987/34005305-79509bd6-e135-11e7-8f98-196e4bffa2c3.png)

不多说了吧。。

而且导致VIM模式下的光标也小。。明显光标是随行高变化的而不是随字号变化的。。

![default](https://user-images.githubusercontent.com/23495987/34005430-cde8920c-e135-11e7-90ed-2f86145c2af4.png)

这个vim模式实在是有点尴尬。。

还没有那种类似vim-fcitx这种退出编辑模式的功能。。

**Comment by suziwen** [comment]
编辑器里设置里有调整行高的。vim模式是简化版的，没办法达到和原生vim一个功能的

**Comment by suziwen** [comment]
比较好奇你的字体怎么设置的，看下你设置里编辑器相关的配置

**Comment by panhaoyu** [comment]
把默认配置的字体改成华文楷体，然后把字号改成30。别的没有动。

**Comment by tiankongjintou** [comment]
其实你可以自己添加字体。

**Comment by suziwen** [comment]
可以先自己把行高设置成 `2` .先关了，和这个重复了 #560
