### ISSUE TITLE
希望精简一下错误提示

### ISSUE THREAD

**Issue by panhaoyu** [suziwen/markdownxiaoshujiang#642]
![Uploading 图片.png…]()

**Comment by panhaoyu** [comment]
![default](https://user-images.githubusercontent.com/23495987/34075500-97db8280-e303-11e7-84e3-15a8d901f1d7.png)

**Comment by suziwen** [comment]
这个是你的文章里很多图片找不到对应的资源，无法正确加载。感觉这些提示还是有必要的，让用户尽开能多的知道哪些错误。错误提示可以通过左边的批量关闭按钮，把所有错误提示都关掉的。
