### ISSUE TITLE
功能找不到了:设置导入到印象笔记的笔记是否可以编辑(文档锁定功能)

### ISSUE THREAD

**Issue by taoey** [suziwen/markdownxiaoshujiang#649]
一般导入到印象笔记的笔记是不可以在印象笔记中编辑的(文档锁定功能).像这样:
![image](https://user-images.githubusercontent.com/22273652/34198436-5955eccc-e5a5-11e7-8191-4a2b5031a5ad.png)

我的确实可以编辑的.找不到如何设置了...求助

**Comment by suziwen** [comment]
绑定页面下 ,点击对应的小齿轮
![image](https://user-images.githubusercontent.com/57370/34206830-15170b40-e5c3-11e7-98e6-39f4c67b7483.png)

![image](https://user-images.githubusercontent.com/57370/34206851-297f4822-e5c3-11e7-8bbd-92cd0efbf183.png)

**Comment by taoey** [comment]
谢谢,小书匠非常棒!!!会持续关注的
