### ISSUE TITLE
在目录功能下打开已有文件加载速度超慢,或者说打不开

### ISSUE THREAD

**Issue by diwer** [suziwen/markdownxiaoshujiang#657]
如截图,一直打不开文件, 
![123](https://user-images.githubusercontent.com/4810523/34331824-454e4ce2-e965-11e7-9f79-6612b19aff63.png)

另预览七牛图床文件提示图片为null 实际浏览器可以正常打开图片

**Comment by suziwen** [comment]
我这边能正常打开绑定的文件。最好能提供问题重现的方式。

**Comment by diwer** [comment]
反复测试.将这儿说明文件关闭,然后打开下面目录下文件 就会出现这种一直加载的情况
![234](https://user-images.githubusercontent.com/4810523/34344425-c1987776-ea20-11e7-87dd-85cc649496d9.png)

**Comment by diwer** [comment]
说明文件全部关闭才会出现

**Comment by diwer** [comment]
5.3 解决了
