### ISSUE TITLE
用户选项没有了吗？插入图片，图片描述不在图片下方显示

### ISSUE THREAD

**Issue by DavichiHug** [suziwen/markdownxiaoshujiang#658]
![snipaste_2017-12-25_12-25-48](https://user-images.githubusercontent.com/23614846/34332698-e70a3cc2-e96e-11e7-9970-7763761a880b.png)
![snipaste_2017-12-25_12-24-55](https://user-images.githubusercontent.com/23614846/34332699-eae5c05a-e96e-11e7-832d-aedeb97180e8.png)

**Comment by suziwen** [comment]
你这小书匠客户端版本是多少?

**Comment by DavichiHug** [comment]
![image](https://user-images.githubusercontent.com/23614846/34359440-005b5a92-ea93-11e7-898a-aa79290662bb.png)

**Comment by suziwen** [comment]
下载最新版本

https://github.com/suziwen/markdownxiaoshujiang/releases/tag/v5.1.0

**Comment by DavichiHug** [comment]
好的问题解决了，感谢
