### ISSUE TITLE
一段时间不进行操作，再切换文件的话，预览区就会全白，而且不能切换到其他文件

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#66]
一段时间不进行操作，再切换文件的话，预览区就会全白，而且不能切换到其他文件。多次出现。
当时操作的文件时从evernote 打开的。

**Comment by suziwen** [comment]
web 版本?还是客户端版本?
web版的话,说一下浏览器,客户端版本的话,提供下版本号,及操作系统等信息.

**Comment by oska874** [comment]
web .
chrome 43,win 7 64bit.

**Comment by suziwen** [comment]
我这边一直没有出现你说的情况.打开的文件很复杂?试着新建一个简单文件,一段时间不操作,再切换呢?

**Comment by oska874** [comment]
这个出现频率还是挺高的，虽然基本不影响正常使用（很久刷新一下就可以了），但是用着还是有点糟心。

**Comment by suziwen** [comment]
这个主要是我这边一直没有出现你说的情况,你能再提供一些更详细的信息吗,比如变空白时,浏览器控制台显示什么错误信息等.

再有一个是你现在用的浏览器是否安装了比较多的插件?有些插件会改变一些网页html结构,是否可以新建一个没有插件的用户会话下,测试下.
