### ISSUE TITLE
想问一下那种数学符号和希腊字母是不能输入吗

### ISSUE THREAD

**Issue by Foabo** [suziwen/markdownxiaoshujiang#669]
比如数学上的任意和存在，希腊字母的alpha beta等

**Comment by panhaoyu** [comment]
支持mathjax的，你可以查一下这个东西，就是latex的公式。 haoyupan 邮箱：haoyupan@aliyun.com 签名由 网易邮箱大师 定制 在2018年01月07日 23:11，WhyCyrils 写道： 比如数学上的任意和存在，希腊字母的alpha beta等 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by suziwen** [comment]
`设置>语法扩展`， 把 mathjax 选项打开.

![image](https://user-images.githubusercontent.com/57370/34916818-07192e96-f979-11e7-9679-17f89f3bccc6.png)
