### ISSUE TITLE
建议：可以仿照sublime 添加一列缩略显示

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#67]
建议：可以仿照sublime 添加一列缩略显示。
现在编辑区的滚动条太窄不好控制。加一个缩略显示既可以好控制，也方便预览。
之前某个版本是有这个功能的，后来不知怎么的没了。

**Comment by suziwen** [comment]
ace编辑器已经实现　minimap,如果没有打开,可以到`设置`　->　`编辑器` 里打开.

**Comment by oska874** [comment]
这个我试了，但是必须关掉预览区才会出现。不好用。

**Comment by suziwen** [comment]
之前是不关闭预览也可以显示minimap,后来觉得同时打开预览,编辑区,文档列表面板,再打开minimap,显示空间有点小,就改成只有在预览关闭后,minimap才可以显示出来.
