### ISSUE TITLE
建议：能否在左边增加一个文件夹功能

### ISSUE THREAD

**Issue by liuyuzxc** [suziwen/markdownxiaoshujiang#677]
能否在左边文章栏，增加一个文件夹功能，这样写的文章多了，可以都放在一个文件夹下进行归类，方便查找和管理。

**Comment by xmc1204** [comment]
支持，多级子目录，方便管理~

**Comment by suziwen** [comment]
你指的是这种效果?
![image](https://user-images.githubusercontent.com/57370/34916719-8ea6a534-f977-11e7-8b57-5c977d5b2c91.png)
目前使用第三方绑定就可以实现

**Comment by xmc1204** [comment]
@suziwen 

明白怎么实现了，不过这个第三方可以绑定勾选多个么？？

<img src="http://file.oss.open.5vwan.com/tu/1515941202554.jpg" alt="enter description here"
    title="enter description here" name="">

**Comment by suziwen** [comment]
`小书匠主按钮>设置>绑定` 

![image](https://user-images.githubusercontent.com/57370/34917132-3bd4e086-f97d-11e7-934d-c200b4e37c3c.png)

绑定完成后，记得选中，确定，让它成为默认的第三方存储。

就会出现目录树管理功能。

![image](https://user-images.githubusercontent.com/57370/34917142-6d03d964-f97d-11e7-8dcf-9b42828938b4.png)

**Comment by liuyuzxc** [comment]
![default](https://user-images.githubusercontent.com/14965632/34924012-b4ed332a-f9db-11e7-9e65-223b192cd7f6.png)
![default](https://user-images.githubusercontent.com/14965632/34924020-c02f917e-f9db-11e7-848b-a5f5f724b0e2.png)

可是这样也有个问题，我绑定的是印象笔记，，我在印象笔记中有多个层级上百个目录，并且根据目录的名字 印象笔记会自动进行排序，，而小书匠读取出来的目录是乱序的，，能否增加一个目录排序功能呢？（最好跟读取印象笔记出来的排序一样最好啦）

所以综上所述，有两个建议：
1、在小书匠的左侧文章菜单中，增加一个文件夹功能，不用多级文件夹，一级就可以；
2、读取第三方印象笔记目录后，根据目录标题进行排序显示（别的第三方没有试过，这里单只印象笔记）
谢谢~

**Comment by suziwen** [comment]
@liuyuzxc  这个就是可以控制排序的

![image](https://user-images.githubusercontent.com/57370/34932682-c650b046-fa0e-11e7-8936-43d7456af64f.png)

**Comment by suziwen** [comment]
@xmc1204 

只能选择一个作为默认的，这样用户点击保存时，会自动保存到第三方存储，如果想再存储到其他第三方，可以选择`另存为>选择其他绑定`

**Comment by liuyuzxc** [comment]
![default](https://user-images.githubusercontent.com/14965632/34942570-1a06f1a4-fa33-11e7-98eb-0fe9732bfd9e.png)

![default](https://user-images.githubusercontent.com/14965632/34942565-165e94ee-fa33-11e7-9df6-d0055630acbe.png)

![default](https://user-images.githubusercontent.com/14965632/34942563-132aebe2-fa33-11e7-90aa-f396b3c2bab6.png)
![default](https://user-images.githubusercontent.com/14965632/34942557-0f0db666-fa33-11e7-9f1c-10622e0b39ce.png)

我点了这个四个排序功能，但是没有任何效果，，截图如上4张图。
你看我分别点击了这个4个排序功能，但是我印象笔记的菜单没有任何变化，还是乱序。

**Comment by suziwen** [comment]
应该是个 bug 

你可以点击想要的排序后，再点击左边的刷新按钮 
![image](https://user-images.githubusercontent.com/57370/34943157-754527b4-fa35-11e7-86fb-a8f2d487e628.png)

**Comment by weinot** [comment]
文件夹可以固定住吗？不自动隐藏

**Comment by repairearth** [comment]
![image](https://user-images.githubusercontent.com/12729854/37751266-61ce391c-2dcc-11e8-93bb-ecd4457c47a9.png)
固定打开左侧及右侧预览区，在此操作，隐藏较深，找了半天
