### ISSUE TITLE
代码没有颜色，是我设置的问题吗

### ISSUE THREAD

**Issue by yin-shu** [suziwen/markdownxiaoshujiang#682]
![image](https://user-images.githubusercontent.com/29432662/35203682-6711e13a-ff64-11e7-9ea8-2e63dadef9b0.png)

**Comment by yin-shu** [comment]
换了几种样式，都是没有颜色区分

**Comment by suziwen** [comment]
编辑区里的代码块样式？

目前只支持 codemirror  内置编辑器里的 html, css,javascript 语言.

![image](https://user-images.githubusercontent.com/57370/35282836-84e8a4f4-0091-11e8-8ed4-0953ed90634a.png)

**Comment by yin-shu** [comment]
@suziwen 我说的是预览区代码块样式，出来都一个颜色

**Comment by suziwen** [comment]
预览区的话，如果你在 `小书匠主按钮>设置>预览` 里，把代码块的样式禁用的话，是不会显示。

![image](https://user-images.githubusercontent.com/57370/35331135-2c95d852-0141-11e8-9681-f6da1303c69b.png)

还有就是代码块要明确使用了哪种语言， 比如 javascript , 下面的格式才会正常高亮

````
``` javascript
var x = 1;
```
````

如果没有明确使用了哪种语言, 比如下面的格式， 系统只是当成普通的代码块，并不会去高亮里面的代码

````
```
var x = 1;
```
````

![image](https://user-images.githubusercontent.com/57370/35331265-9ffde6c2-0141-11e8-9100-3cbf873dcf8b.png)

**Comment by yin-shu** [comment]
好的，多谢
