### ISSUE TITLE
不能画出 plantuml

### ISSUE THREAD

**Issue by rubyshen** [suziwen/markdownxiaoshujiang#685]
grammar_cjkRuby: true
grammar_flow: true
grammar_sequence: true
grammar_plot: true
grammar_mermaid: true
grammar_plantuml:true

只要加入 grammar_plantuml:true 就会连 sequence 图都画不出来，而且最后一行的grammar_plantuml:true 会是灰色的

**Comment by suziwen** [comment]
元数据对语法要求比较严格，需要在 `grammar_plantuml: true` , 在 `true`和 `:` 之间要有一个空格。
