### ISSUE TITLE
LaTeX公式语法问题

### ISSUE THREAD

**Issue by LRJ-2000** [suziwen/markdownxiaoshujiang#692]
小书匠行内公式语法为  ``!$ $``
但其余编辑器均为 `$ $`
导致和有道云笔记等绑定后无法正常显示公式

**Comment by suziwen** [comment]
`小书匠主按钮>设置>扩展语法>mathjax>兼容通用写法` 选中

![image](https://user-images.githubusercontent.com/57370/35714844-fe4d5676-0809-11e8-8655-1865552c7584.png)
