### ISSUE TITLE
3.0+的版本画的planuml图，同步到印象笔记，后来升级到5.0+，从印象笔记拉下来的plantuml都是png图片了，之前的planuml代码都没了！！！

### ISSUE THREAD

**Issue by kaydxh** [suziwen/markdownxiaoshujiang#697]
3.0+的版本画的planuml图，同步到印象笔记，后来升级到5.0+，从印象笔记拉下来的plantuml都是png图片了，之前的planuml代码都没了！！！

**Comment by suziwen** [comment]
你的文件应该是在印象笔记的客户端里编辑过，小书匠再次拉取时，只能进行 html 转换引起的。你可以自己到印象笔记对应的附件 markdown 里找原文。
