### ISSUE TITLE
linux版本问题

### ISSUE THREAD

**Issue by tiankongjintou** [suziwen/markdownxiaoshujiang#698]
这几天准备Ubuntu，想问下作者，有ubuntu版本的吗。

**Comment by suziwen** [comment]
有 linux 版本的。

**Comment by tiankongjintou** [comment]
是ubuntu的？

**Comment by tiankongjintou** [comment]
原谅我，我也是昨天才开始，之前装了个centos，完全玩不转，所以只要转到ubuntu了，这不，这就是在ubuntu上发的这个。

**Comment by suziwen** [comment]
ubuntu 也可以的。

**Comment by a523** [comment]
我下载了linux版本， 能告诉我怎么在centos 上安装么？

**Comment by tiankongjintou** [comment]
好的，我再尝试装一下。

**Comment by tiankongjintou** [comment]
不知道怎么案安装啊。

**Comment by suziwen** [comment]
给 Story-writer 添加可执行权限， 类似 `chmod a+x Story-writer`, 然后
执行 `./Story-writer`
