### ISSUE TITLE
第三方保存的默认目录

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#704]
我采用的是wiz的第三方，很久之前记得默认保存的目录都是第一个目录，后来提过建议说将目录修改为上一次保存文件的目录，这个很快就被完善了，特别赞。

现在又有新的问题，因为之前没有模板功能，所以自己暂时用多个浏览器使用小书匠，这样不同类型的文档在每次保存的时候，都是自动选择目录。

在开通会员之后有了模板功能了，但是新建不同文档后，现在还是保存为上一次的目录，导致了自己每次都需要重新选择目录，每次都需要操作很久。所以：
能否提供以下两种方案之一（依据难易）：

1. 模板中会附带有目录选项，不同的模板其会默认保存在特定目录下。（由于可能有不同的第三方，这个可能不是好方法。更牛逼的可能就是系统内部判断某模板经常保存的目录之后进行推荐，这个有点难为人了，哈哈）
2. 在现有自动定位到上一次目录下的前提上，在保存选择目录的界面上添加“最近历史目录”的选择，这样可以一键选择最近使用过的目录。（这个可能比较好）

**Comment by suziwen** [comment]
这个是根据你当前在第三方绑定目录里处于哪个目录下，新建的时候，自动定位到这个目录里。

比如下面这个图片

![image](https://user-images.githubusercontent.com/57370/36766233-f36ab8fa-1c6f-11e8-957d-1d040b8a2a65.png)

当前处在 `mmmmm` 目录下，你选择模板新建后，就自动在这个目录下创建文件，点击保存时，也自动定位到这个目录下。

如果你点击了目录树的其他节点，比如 `tftf` ,这时选择模板后创建的文章，就在`tftf` 目录下了。

**Comment by CharMingF** [comment]
尝试了一下，确实如此，谢谢。

不过还是觉得有个最近目录比较好，可能要求比较强求了，因为日常文档使用的目录也就2-4个左右，其他都不经常使用，小书匠目前会将自动定位到文档所在目录下，这样会使得整个目录滚动条变的非常长，必须收缩后使用，再加上第三方目录的读取时间，有时候非常的卡。
![image](https://user-images.githubusercontent.com/7530342/36772011-72c0bc30-1c8e-11e8-8b8b-b048f532ae72.png)
