### ISSUE TITLE
保存到印象笔记后，从印象笔记打开只显示了一个md附件

### ISSUE THREAD

**Issue by KermitLee** [suziwen/markdownxiaoshujiang#710]
保存完之后，并没有显示保存成功，显示的是“处理文件样式关联失败”，然后从印象笔记打开之后显示的就只是一个md的附件

**Comment by suziwen** [comment]
应该是你自定义的 css 里，有些语法不能正确处理引起的。

**Comment by KermitLee** [comment]
但是我并没有自定义css，我用的都是小书匠里已经定义的markdown用法。在桌面端预览的效果都是没问题的，就是保存到印象笔记的时候就变成了一个附件。。。

**Comment by suziwen** [comment]
新建一篇简单的文章，保存也会出错？

**Comment by KermitLee** [comment]
是的，刚刚只是新建了一个简单的文章，还是报 “处理文件样式关联失败” 的错误，在印象笔记打开还是只有一个md文件

**Comment by suziwen** [comment]
在 `关于` 页面里，把里面显示的数据文件位置先临时移到其他位置，然后再启动小书匠，重新绑定印象笔记，保存还会失败？

**Comment by KermitLee** [comment]
我按照你的方法试了一下，还是不行。但是我卸载又重新安装了一次就没有之前的问题了。谢谢你的回答和帮助！
