### ISSUE TITLE
mac版的支持窗口布局修改吗？我想在编辑的同时也可以预览，现在是只能在编辑完之后再打开预览。

### ISSUE THREAD

**Issue by W0lfier** [suziwen/markdownxiaoshujiang#717]

**Comment by suziwen** [comment]
![qq 20160729010013](https://cloud.githubusercontent.com/assets/57370/17221772/e633c830-54ba-11e6-9863-32366ec1fa72.png)

这个位置，如果没有出现按钮，调整下窗口大小，再最大化就会出现这个按钮。
