### ISSUE TITLE
预览区与编辑区不能对齐

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#72]
选择编辑区，然后预览区会跟着对齐，这个没啥问题；
但是选择预览区（勾上中间的两个对号了），编辑区在文档开始还能对齐，但是越往越偏，到最后预览区还有大半页内容，编辑区都已经见底了。
注：图片比较多，十来张小图

**Comment by suziwen** [comment]
嗯,目前同步滚动编辑区还不是很准确.

**Comment by puppylpg** [comment]
是的，看着很不舒服，用着也很不方便，希望赶紧修复一下。支持！！！

**Comment by suziwen** [comment]
最新版本1.7.0已经修复
