### ISSUE TITLE
建议加入印象笔记的笔记本组

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#724]
印象笔记中笔记的层次是这样的：

```
|-- 笔记本组
|   |-- 笔记本
|   |   |-- 笔记
```

小书匠中只保留了笔记本，没有笔记本组，使用起来不是很方便，建议加入笔记本组。

**Comment by suziwen** [comment]
主要是印象笔记官方的 API 没有提供笔记本组的接口。

#44

**Comment by brookchen** [comment]
印象笔记确实没有提供笔记本组的类和api，笔记本组是notebook对象的一个字符串属性，属性名是 `stack`。

## Struct: Notebook

Field | Type | 备注
-- | -- | --
guid | Guid |
name | string |
updateSequenceNum | i32 |
defaultNotebook | bool |
serviceCreated | Timestamp |
serviceUpdated | Timestamp |
publishing | Publishing |
published| bool |
**stack** | **string** | **<---这里是笔记本组名称**
sharedNotebookIds | list<i64> |
sharedNotebooks | list<SharedNotebook> |
businessNotebook | BusinessNotebook |
contact | User |
restrictions | NotebookRestrictions |

**Comment by suziwen** [comment]
原来笔记本组的信息是在这里，一直没注意。。。。。 :sweat_smile:

**Comment by brookchen** [comment]
升级到5.6.0已经支持笔记本组了，非常棒！另外5.6.0的预览流畅度比之前版本好了太多。 @suziwen  很棒啊，要继续加油！
