### ISSUE TITLE
建议： 数据存储中加入<七牛云存储>

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#727]
七牛云存储不仅可以用作图床，也很适合用来保存markdown文件。

>  小书匠是个好软件！
>                ---  我说的

**Comment by suziwen** [comment]
这个可以通过小书匠客户端本地绑定，保存到本地，然后再用其他同步工具同步到七牛云。

----------

感谢对小书匠的支持，不过暂时不考虑单独的把类似七牛这种云存储做为数据存储的方案。

**Comment by brookchen** [comment]
这个确实不算强需求，而且也很容易通过其他方式解决。
