### ISSUE TITLE
七牛云存储的上传服务器域名地址更改了

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#728]
七牛云存储的官方服务器地址域名更改了，小书匠里还没有变过来。 [存储区域](https://developer.qiniu.com/kodo/manual/1671/region-endpoint)

> ## 存储区域
> 最近更新时间：2018-03-15 18:28:40
> 
> 
> 存储区域 | 地域简称 | 上传域名
> -- | -- | --
> 华东 | z0 | 服务器端上传：http(s)://up.qiniup.com客户端上传： http(s)://upload.qiniup.com
> 华北 | z1 | 服务器端上传：http(s)://up-z1.qiniup.com客户端上传：http(s)://upload-z1.qiniup.com
> 华南 | z2 | 服务器端上传：http(s)://up-z2.qiniup.com客户端上传：http(s)://upload-z2.qiniup.com
> 北美 | na0 | 服务器端上传：http(s)://up-na0.qiniup.com客户端上传：http(s)://upload-na0.qiniup.com
> 东南亚 | as0 | 服务器端上传：http(s)://up-as0.qiniu.com客户端上传：http(s)://upload-as0.qiniu.com

>

**Comment by suziwen** [comment]
感谢提醒。
