### ISSUE TITLE
预览文章不能使用esc退出

### ISSUE THREAD

**Issue by puppylpg** [suziwen/markdownxiaoshujiang#73]
客户端在预览文章的时候，不能使用esc退出，只能强行关闭软件。Archlinux-64bits

**Comment by suziwen** [comment]
进入全屏模式(包括编辑全屏和预览全屏)都可以通过屏幕右上角的控制按钮退出(需要注意的是背景图颜色可能跟按钮相似,没注意的话就看不出那个退出全屏的按钮了).后面会考虑客户端esc退出全屏.

**Comment by puppylpg** [comment]
👍

**Comment by suziwen** [comment]
最新版本1.7.0加入了第一次使用提示在哪退出全屏的提示.
