### ISSUE TITLE
希望优化印象笔记文件夹排序及增加搜索功能

### ISSUE THREAD

**Issue by gricn** [suziwen/markdownxiaoshujiang#733]
我的印象笔记已经用图书分类法分类了，即从000到999，然而在小书匠显示的根目录排序还是乱糟糟的，又不能搜索，每次找文件夹特别麻烦。

**Comment by suziwen** [comment]
#615 
[查询](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-12-27%20%E7%AC%AC%E4%B8%89%E6%96%B9%E5%AD%98%E5%82%A8%E6%9F%A5%E8%AF%A2.md)

**Comment by gricn** [comment]
thanks
