### ISSUE TITLE
在印象笔记中显示不正确

### ISSUE THREAD

**Issue by puppylpg** [suziwen/markdownxiaoshujiang#74]
- 凡是使用``<u>...</u>``（下划线）标记的句子，在预览区显示正常，但是同步到了印象笔记里之后，横线都没有了。
- 而且公式显示也不正确——使用mathjax表示分数，分子分母在预览区表现都正常，但是到了印象笔记，分子分母就不见了。

**Comment by suziwen** [comment]
1. 下划线这个确实有问题,下个版本修复,暂时可以用插入语法(grammar_ins: true)或者<ins></ins>标签代替.
2. 公式我这边显示正确的,比如下面这个.不知道你的公式内容是什么,能贴出来我试下吗.

~~~~
```mathjax!
$$\frac{x^22}{e^x-1}$$
` ``
~~~~

**Comment by suziwen** [comment]
最新版本1.7.0 已经修复
