### ISSUE TITLE
Mac版无法退出水印效果

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#741]
按 `Ctrl + Shift + [` 无法退出水印效果，也找不到其他途径返回到正常的预览效果。

**Comment by suziwen** [comment]
我这边小书匠  5.1.0 mac 版本没有问题，可以正常退出水印效果。

－－－－－－－

可以重启小书匠，自动退出水印效果

**Comment by brookchen** [comment]
通过重启恢复了正常。

**Comment by suziwen** [comment]
`5.5.0` 版本的话，不能在编辑区里按这个快捷键，需要在非编辑区（比如工具栏里），通过鼠标点击下工具栏空白区域，然后按`ctrl+shift+f` ,就能退出水印效果了。
