### ISSUE TITLE
付费用户，移动端，打开绑定账号中的文件

### ISSUE THREAD

**Issue by xfdywy** [suziwen/markdownxiaoshujiang#744]
付费用户默认可以同步绑定信息，如果我绑定了github，我在移动端，比如手机上还是没法打开绑定 的github里面的文件，因为只有新建，保存，另存为的选项。没有在桌面端左下角的操作绑定账号的界面。

**Comment by suziwen** [comment]
用手势向右滑动

**Comment by xfdywy** [comment]
不行啊。是要从最左边的边缘往右滑动吗？很难滑动成功啊。。。往往都是退回到上一页去了（好像跟浏览器的快捷手势重合了，感觉这个快捷手势现在大部分手机浏览器都有吧），要么就没反应（可能是没有从最边缘开始滑动）。就偶尔有几次次成功了。也可以用chrome的调试功能把网页切成手机模式来试试，确实挺难用的。
大佬考不考虑改进一下。移动端用的人应该也还有一些，手机，pad上什么的。

**Comment by suziwen** [comment]
不需要从边缘开始滑动，从编辑区的中心向右滑也可以。

就是目前小书匠还没有对移动端做太多的优化，使用体验不是很好，很多新功能的加入，也没有考虑移动动端的兼容。再加上移动端的使用场景还是很有限，不太适合文字的输入，所以还不是比较急着专门开发移动端。等 PC 端的功能差不多了，才会再考虑单独开发。
