### ISSUE TITLE
PPT预览无法使用

### ISSUE THREAD

**Issue by getGitxxx** [suziwen/markdownxiaoshujiang#75]
ppt预览在ff和chrome下均无法使用，firebug，ajax请求返回null，
err：

Firefox 无法建立到 ws://markdown.xiaoshujiang.com/socket.io/?EIO=3&transport=websocket&sid=rFVFyGkq4dV5fv7OAAAJ 服务器的连接

**Comment by suziwen** [comment]
我这边试了下,没有你说的这个情况,我这边运行得挺好的,不知道你那边是怎么操作的.还有就是
用的什么版本,web?,客户端?什么操作系统?是否是防火墙把连接断了?

部署完后,先贴演讲者地址 ,然后 再认别人查看对看者地址 呢?
