### ISSUE TITLE
部分文档不能导出为zip格式

### ISSUE THREAD

**Issue by Watereggs** [suziwen/markdownxiaoshujiang#754]
大佬好，很幸运能找到这款编辑器使用。

最近在编辑文档的时候，一个含图片较多的文档，大小为25M。无论是网页版还是客户端都无法生成zip包，其他的word，pdf，html都可以生成。
中间出现过在历史记录里显示文件冲突，然后我给关掉了冲突分支，不知道有无影响。

望解答，谢谢。

**Comment by suziwen** [comment]
`小书匠主按钮>关于` 里，看一下日志文件有没有什么错误信息.

**Comment by Watereggs** [comment]
日志文件里有错误信息。
2018.4.8号出现的报错信息是:TypeError: Cannot read property '_autoSave' of null,    
2018.4.13出现的报错信息是：error: uncaughtException: Cannot read property 'save' of undefined date和error: uncaughtException: Cannot read property '$el' of null date和error: uncaughtException: Cannot read property 'destroy' of null date和error: uncaughtException: Eek! Coincident points! date

小白看不太懂，是我操作上有需要注意的地方吗？
谢谢。

**Comment by suziwen** [comment]
能把错误的日志文件和导出异常时的文章正文发到邮箱  suziwen1@gmail.com 吗
