### ISSUE TITLE
保存在印象笔记后内容消失

### ISSUE THREAD

**Issue by gricn** [suziwen/markdownxiaoshujiang#755]
在小书匠正常编辑的内容在印象笔记打不开
![9](https://user-images.githubusercontent.com/34237589/38465418-eb48cf3e-3b4d-11e8-9dba-7c046005e903.png)
![10](https://user-images.githubusercontent.com/34237589/38465420-eb7d6870-3b4d-11e8-8565-7aeeaddc3944.png)

**Comment by gricn** [comment]
但是在印象笔记历史版本中又能找到最新版本，导入后却还是空白
![11](https://user-images.githubusercontent.com/34237589/38465450-5b6f4464-3b4e-11e8-93f3-2cc7f62d0bc9.png)

**Comment by suziwen** [comment]
是不是文章里包含表格？

#725

**Comment by gricn** [comment]
是，请问如何解决。

**Comment by suziwen** [comment]
这个感觉应该是印象笔记自己的 bug, 主要原因是表格里如果使用 thead , 也就是表格头，在他们的新版本window 客户端就会异常。印象笔记的 web版本就不会有这个问题。**如果印象笔记不解决这个 bug 的话，老数据里如果表格有 thead 标签，都会变成空白文档**。我查看了他们开发文档里，表格是允许有 thead 标签 [相关链接](https://dev.yinxiang.com/doc/articles/enml.php#permitted)。
![image](https://user-images.githubusercontent.com/57370/38473708-02b9ec1a-3bc7-11e8-97aa-bb85410e8e7d.png)
![image](https://user-images.githubusercontent.com/57370/38473715-273c7850-3bc7-11e8-83e3-3c0f20c0db66.png)


---------------

暂时解决方案

1. 降低印象笔记window 客户端版本, 等他们修复这个问题再升级。
2. 自己在 markdown 文章里使用 table 标签。

**Comment by suziwen** [comment]
失败的文档

```
# 这是一个会在新版本出问题的表格

<table class="table table-striped table-celled">
<thead>
<tr>
<th>a</th>
<th>b</th>
<th>c</th>
</tr>
</thead>
<tbody>
<tr>
<td>d</td>
<td>e</td>
<td>f</td>
</tr>
</tbody>
</table>
```

正确的文档

```
# 这是在印象笔记里正常显示的表格
<table class="table table-striped table-celled">
<tbody>
<tr>
<td>a</td>
<td>b</td>
<td>c</td>
</tr>
</tbody>
</table>
```

**Comment by wubei7231** [comment]
这是印象笔记的锅。建议使用老版本的evernote。

**Comment by gricn** [comment]
最新版本的印象笔记可以用了，修复了这个问题

2018-04-10 22:12 GMT+08:00 wubei7231 <notifications@github.com>:
