### ISSUE TITLE
拍照模式是否可以部分拍照

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#762]
目前拍照是全文进行拍照。有时候想将文档的部分保存为图片，虽然截图可以，但是超过屏幕大小的还需要动用软件，不知可否通过选择编辑器内容中的的部分后，拍照结果的是渲染之后的部分呢？

**Comment by suziwen** [comment]
感觉保存为全文图片后，自己可以找个图片编辑软件切割出想要的部份更容易些。

=========

主要是通过编辑器选中的部份进行渲染导出还是有点麻烦，涉及到图片引用，脚注引用等关联信息处理。就暂时不实现这个功能了。

**Comment by CharMingF** [comment]
ok，利用图片截取软件解决了
