### ISSUE TITLE
建议加入章节管理

### ISSUE THREAD

**Issue by localking3693** [suziwen/markdownxiaoshujiang#764]
当写内容较多和较长的文档时，内容会显得很杂乱，建议加入类似 gitbook 的章节管理的功能，这样写比较长篇的文章时会比较方便管理和查看

**Comment by suziwen** [comment]
比较长的文章，可以自己拆分成不同的文章。
或者直接通过小书匠的大纲视图功能查看

![image](https://user-images.githubusercontent.com/57370/38617913-c7f51d38-3dca-11e8-818b-9a446cdf1c6d.png)
