### ISSUE TITLE
左边编辑区+======变成绿的小点，点击出现取色界面

### ISSUE THREAD

**Issue by qgyhd1234** [suziwen/markdownxiaoshujiang#766]
![image](https://user-images.githubusercontent.com/19366952/38616958-4bc65468-3dc8-11e8-9091-34b8724a3d02.png)

**Comment by suziwen** [comment]
这个可以在 `设置>编辑器>codemirro` 里，把`开启高亮语法颜色选择器` 去掉。

**Comment by qgyhd1234** [comment]
关闭后编辑区正常了，但是预览区有
![image](https://user-images.githubusercontent.com/19366952/38654076-38d3f5ea-3e40-11e8-9f4e-b7fafd3fcf03.png)

**Comment by suziwen** [comment]
这个被当成文字格式标识语法`==+==` 转换了，你可以在`设置>扩展语法>文字格式标识` 里，把它取消。

![image](https://user-images.githubusercontent.com/57370/38677775-d922b594-3e91-11e8-9f51-20bb307e1169.png)
