### ISSUE TITLE
Story writer  5.6.0：向印象笔记同步_表格格式错误

### ISSUE THREAD

**Issue by zzjjszh1** [suziwen/markdownxiaoshujiang#772]
我使用 5.6.0，其中使用了表格，
| 1111 | 1111 |
| ---- | ---- |
| 111  |1111  |

向印象笔记进行同步后，在印象笔记中，表格无法显示。

我来我尝试在metadata部分添加了grammar_table:true，同样无法显示

这个问题在之前的版本中也是同样的现象，请帮忙检查解决

**Comment by suziwen** [comment]
#725
