### ISSUE TITLE
建议增强表格功能

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#773]
目前小书匠是不是不支持单元格纵向合并？

 Atom 的 `markdown-preview-enhanced` 插件可以使用符合 `>` 和 `^` 支持表格的横向与纵向单元格合并。

``` markdown
H1|H2|H3|H4|H5
-|-|-|-|-
1|2|3|4|5
1|>|>|2|5
^|>|3|4|5
^|2|>|4|5
1|2|3|4|5
```
效果如下：

![image](https://user-images.githubusercontent.com/8371441/38724458-eb4e30d6-3f36-11e8-969e-c03e3c46a89e.png)

[markdown-preview-enhanced 插件 table](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=table)

**Comment by brookchen** [comment]
现在可以通过 `^` 和 `<` 合并单元格了，我还有两个问题：

1.  如果想输入一个空白的cell改怎么办，我是通过 `| ... | <p> </p> | ... | ` 来输入的，有些不方便，有没有其他办法？
2.  使用 `^` 纵向合并的单元格，能不能默认垂直居中对齐？

**Comment by suziwen** [comment]
可以使用中文全角空格或者 `&nbsp;`  代替


------------

这个自定义一下 css 样式就可能

```
.table th, .table td{
vertical-align: middle;
}
```
