### ISSUE TITLE
严重bug反馈：加载文件列表出现错误

### ISSUE THREAD

**Issue by gujin03** [suziwen/markdownxiaoshujiang#774]
操作系统：mac os10.13.4
版本：离线版5.6.0
现象：关联了印象笔记成功后当导入一定数据的md文件（如20-30篇左右）在同步到印象笔记的过程中，突然之间软件就会报“加载文件列表出现错误{"code":1006,"error":null}”
此时无论如何操作都无法解决，于是取消与印象笔记的关联尝试重新建立关联关系，我尝试了有几十次之多，依次为：
授权1天-失败
授权1周-失败
授权30天-失败
授权1年-失败
……

软件总是提示“验证用户失败，请确认token是否有效”

我同时有监控印象笔记的授权记录，在授权记录则显示每一次操作又是成功的，于是手动将授权记录全部删除，再次尝试上面的关联动作，在经历N次尝试后，软件突然之间又提示“建立成功”

我再次进入md文件导入，再过一段时间又会重复出现上面的错误，非常让人困扰，希望作者尽快解决。

**Comment by gujin03** [comment]
#[](url)

**Comment by suziwen** [comment]
我这边没法重现你说的情况。

**Comment by nicohmx** [comment]
操作系统：windows
版本：离线版5.6.0
现象：关联了印象笔记，使用一段时间，后来也报错“加载文件列表出现错误{"code":1006,"error":null}”。
操作：我是在印象笔记中，把几篇文章从一个笔记本移动到另外一个笔记本，然后点击同步。切换到小书匠，同步目录的时候出现的报错，后边重启等操作都没法解决。

**Comment by suziwen** [comment]
这个错误感觉是你那边网络连接不到印象服务器引起的。或者其他软件限制了小书匠访问指定网络。

你说的操作步骤，我试着把一个笔记从一个笔记本移到另外一个位置，还是能正确处理的。

**Comment by rubyshen** [comment]
我是新手 一度也出现如下的错误信息
加载文件列表出现错误{"code":1006,"error":"{\"errorCode\":9,\"parameter\":\"authenticationToken\"}"}

我是找到这里来 发现可能跟印象服务器有关 所以我重新绑定了印象服务器 就不再有这个恼人的信息了
