### ISSUE TITLE
待办事项出现bug

### ISSUE THREAD

**Issue by nicohmx** [suziwen/markdownxiaoshujiang#777]
待办事项语法 `-[]`、`-[x]`，没有转换成checkbox形式，在语法手册的示例中，也没有显示checkbox。
------环境--------
windows版本
当前版本: 5.6.0
服务器最新版本: 5.7.4

**Comment by suziwen** [comment]
`-` 和 `[` 中间加个空格，语法手册忘记更新修改了。

```
- [ ] 未完成事项
- [x] 完成事项
- [X] 完成事项
```
![image](https://user-images.githubusercontent.com/57370/38787516-f4768272-4160-11e8-9edd-046e2137dc90.png)

**Comment by nicohmx** [comment]
可以了，谢谢！
