### ISSUE TITLE
电脑死机导致未保存文字丢失

### ISSUE THREAD

**Issue by brookchen** [suziwen/markdownxiaoshujiang#779]
今天写了不少字，没有来得及保存，电脑出现死机，重启后文字都丢了。
建议加入保存正在编辑的文章到本地临时文件的功能，如果出现异常关闭应用，重启应用后可以从临时文件中恢复，类似于Office那样，以免丢失数据。

**Comment by suziwen** [comment]
历史记录里应该还有的

![image](https://user-images.githubusercontent.com/57370/38919803-3d0addd4-4324-11e8-9482-7e81af654a67.png)

**Comment by brookchen** [comment]
可惜昨天没有发现这个功能，又巴巴地写了一遍。
