### ISSUE TITLE
导出到word 不能被wps/liberoffice 打开

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#78]
导出到word 的doc 文件有问题，wps 不能打开，liberoffice 打开是网页乱码，必须用ms office 另存为一下才能被其他word 软件打开，而且另存为的时候word 提示的第一选项竟然是mht。
如果把导出的word 直接重命名成mht 文件，浏览器可以直接打开。你的导出到word 是直接把mht 换成doc 吗？好奇。

**Comment by suziwen** [comment]
嗯,目前是做成导出类似mht的,你把doc扩展名改成txt,用纯文本打开就可以看出是类似html的语法.

目前word还没找到一个比较好的库来生成word的开放标准格式,自己写比较耗时间,就只能暂时用这种方法处理下.
