### ISSUE TITLE
小书匠zip包导入问题。

### ISSUE THREAD

**Issue by Watereggs** [suziwen/markdownxiaoshujiang#781]
1.小书匠导出的zip包无法导入客户端

![1](https://user-images.githubusercontent.com/35022581/38969342-6a5d5e4e-43c2-11e8-9c23-84b09592bdd0.png)

2.zip包能导入网页端，但是会出现部分图片，表格无法加载的情况！而且数量不少。

![2](https://user-images.githubusercontent.com/35022581/38969347-6f4702fc-43c2-11e8-9b49-269a45ff0b6e.png)

**Comment by Watereggs** [comment]
有时候文件打包，体积会明显小于pdf，html，word，大概是word的一半！重新打包偶尔报错，找个机会打包成功之后，zip和word体积一样。

**Comment by suziwen** [comment]
能把导入异常的 zip 文件 发到邮箱 suziwen1@gmail.com 吗。

找不到图片，可能是在导出时，图片就没有导出来。可以自己解压缩看看 zip 文件里是否有对应的图片。

**Comment by Watereggs** [comment]
我有解压查看图片和表格比对过，在压缩包里都有。就是客户端和网页端都加载不出来。
