### ISSUE TITLE
小书匠模板

### ISSUE THREAD

**Issue by ranniyue** [suziwen/markdownxiaoshujiang#783]
问一下 自定义模板，怎么获取文档保存的时间 ？

**Comment by suziwen** [comment]
自定义模板只能拿到文件创建时的时间，如果想拿到文件保存时间，需要通过 nunjucks (grammar_nunjucks: true) 语法来拿到，比如 

```
这篇文档更新于 {{doc.updateDate|date('YYYY年MM月DD日 HH小时mm分钟ss秒SSS毫秒')}}
```

具体如何使用 nunjucks ，可以[参考这里](https://github.com/suziwen/blogxiaoshujiang/blob/master/2016-12-28%20%E5%B0%8F%E4%B9%A6%E5%8C%A0%20nunjucks%20%E6%A8%A1%E6%9D%BF%E6%A0%87%E7%AD%BE%E8%AF%AD%E6%B3%95%E6%89%8B%E5%86%8C.md)
