### ISSUE TITLE
归档之后文件不见了

### ISSUE THREAD

**Issue by Watereggs** [suziwen/markdownxiaoshujiang#784]
hello 大佬
zip包今天在更新之后，试了导入，成功了且不卡顿。
然后我选择了文档归档。
归档之后出现了。
![31aaf7d843a24156e97785257f0a38b](https://user-images.githubusercontent.com/35022581/39104503-99b1d19c-46e3-11e8-8774-7df55ac91f04.png)

我在本地存储找不到我的文档了，重启打开之后也没有......不知道文档哪儿去了。

**Comment by suziwen** [comment]
归档后的文件在这里找，
![image](https://user-images.githubusercontent.com/57370/39105270-87fdd9ba-46e7-11e8-8d77-a0ddcba5a8b4.png)

-----------------------

出现这个错误是不是你的数据库文件太大了，看一下 `关于` 界面下，数据目录下的文件占用空间。

**Comment by Watereggs** [comment]
我检查了数据目录下的文件夹，default有360M，其中300M都是indexedDB，我如果后面不用这个，是要清理掉还是怎么处理比较好呢？

**Comment by Watereggs** [comment]
![ae72703dfbed79d7585171af15c458d](https://user-images.githubusercontent.com/35022581/39105807-7dc6b928-46ea-11e8-895a-91e3c9bb2a56.png)
补个图

**Comment by suziwen** [comment]
这个就是小书匠本地保存使用的数据库，如果你的数据都已经保存到其他第三方平台，就可以自己删除掉了。或者通过 `小书匠主按钮>数据>删除数据库` 来清空本地数据库。

-------------


需要提醒的是**删除本地数据库意味着归档后的所有数据都会被删除** 。但是如果你自己自定义了远程服务器的数据库同步，是不会删除远程服务器的数据库。

![image](https://user-images.githubusercontent.com/57370/39106086-008a0d46-46ec-11e8-8d22-42adaa51b9a5.png)

**Comment by Watereggs** [comment]
好的，谢谢大佬解答。
