### ISSUE TITLE
`ctrl+shift+f`快捷键收起左侧栏再打开，会遮挡编辑栏

### ISSUE THREAD

**Issue by yufenglyu** [suziwen/markdownxiaoshujiang#786]
`ctrl+shift+f`快捷键收起左侧栏后，再用`ctrl+shift+f`打开，会遮挡编辑栏

**Comment by suziwen** [comment]
这个当时设计成用快捷键打开时，是临时打开左侧栏，一段时间不操作会自动收回去。
