### ISSUE TITLE
小书匠的图片批注能否通过css控制呢?

### ISSUE THREAD

**Issue by Watereggs** [suziwen/markdownxiaoshujiang#787]
大佬好：

这是编辑器自动应用的样式。
![3](https://user-images.githubusercontent.com/35022581/39232857-38c7d556-48a1-11e8-9cd4-a04bd364e34d.png)

我想把批注改动到图片的左上方，批注的字体颜色与样式能改动吗？
图片的位置也能进行居左设置吗，我之前是在样式代码里面设置了，没应用成功。

望解答

**Comment by suziwen** [comment]
升级到 `5.7.6` ，然后可以看一下[这个](https://github.com/suziwen/blogxiaoshujiang/blob/master/2018-4-25%20%E8%87%AA%E5%AE%9A%E4%B9%89%20css%20%E6%A0%B7%E5%BC%8F%E8%B0%83%E6%95%B4%E5%9D%97%E7%BA%A7%E5%9B%BE%E7%89%87%E6%A0%87%E9%A2%98%E6%98%BE%E7%A4%BA%E4%BD%8D%E7%BD%AE.md)
