### ISSUE TITLE
修改markdown里面title名字后右上角题目不会自动修改

### ISSUE THREAD

**Issue by wubei7231** [suziwen/markdownxiaoshujiang#788]
如题，新建文档后，修改title
title: 小书匠编辑器使用手册
tags: 小书匠,使用手册
中title名字，右上角文档题目不会自动修改。以前老版本是可以自动修改的。
使用版本：5.7.5
模板新建文档，修改title内容，右上角无法自动修改，保存到印象笔记后，也无法自动修改题目。

**Comment by suziwen** [comment]
这个应该是你的元数据块不符合要求，系统当成普通文本了。可以把你的元数据块代码贴出来看一下。

**Comment by CharMingF** [comment]
title: 文字
文字和冒号之间有个空格。

**Comment by wubei7231** [comment]
嗯，我重新设置了一个模板解决问题。可能是少了个空格。
感谢楼上。
