### ISSUE TITLE
使用```java?linenums 方式 保存到印象笔记代码只显示一行

### ISSUE THREAD

**Issue by valjeta** [suziwen/markdownxiaoshujiang#79]
小书匠 版本 1.6.1
印象笔记版本 5.9.0.8665(276665)Public

其他语言的  `?linenums` 方式同样出现这样的问题

- 印象笔记截图 （只显示一行）
![fdsfdsfd](http://7xldom.com1.z0.glb.clouddn.com/QQ截图20150904152611.png)
- 截图 小书架 (显示正常)
![](http://7xldom.com1.z0.glb.clouddn.com/QQ截图20150904151504.png)

**Comment by suziwen** [comment]
web版本已修复,客户端等下个版本发布修复.

**Comment by suziwen** [comment]
最新版本1.7.0已经修复
