### ISSUE TITLE
预览窗口无法显示图像

### ISSUE THREAD

**Issue by oysz2016** [suziwen/markdownxiaoshujiang#790]
为了让图像居中，在图像的链接上加入了“center”标签，用其他编辑器可以正常显示插入的图像，为什么在小书匠的预览窗口无法显示。

**Comment by suziwen** [comment]
大部份的markdown 语法里 html 标签范围内的内容是不能再使用 markdown 语法的, **小书匠使用的是 markdown-it 解析 ， 遵循 commonmark 标准 ，所以也不会支持在 html 片段里使用 markdown 语法**。如果想在 html 标签里显示图片，需要使用 img 标签。

```
//不会显示图片，而是做为普通文本显示
<center>![](http://xxx.xxx/xx.jpg)</center>
// html 标签里需要使用 img 标签才能显示图片
<center><img src="http://xxx.xxx/xx.jpg"></center>
```
