### ISSUE TITLE
增加新功能：代码底色可以设置为Linux默认颜色---黑底白字

### ISSUE THREAD

**Issue by kehaozi** [suziwen/markdownxiaoshujiang#793]
建议可以设置代码底色（非预览区域，是正式发表区域）为Linux底色（黑底白字），马可飞象的代码样式就是这种颜色，实际工作中，选择这种底色的人很多

**Comment by suziwen** [comment]
![image](https://user-images.githubusercontent.com/57370/39738719-42b62ca2-52bf-11e8-9f48-136a3f95fc49.png)
