### ISSUE TITLE
联网导出PDF英文字符间距不规整

### ISSUE THREAD

**Issue by himingway** [suziwen/markdownxiaoshujiang#794]
![image](https://user-images.githubusercontent.com/8113875/39508634-d05fd4f8-4e15-11e8-8f3e-0b1f73492089.png)
![image](https://user-images.githubusercontent.com/8113875/39508660-e6c17d3c-4e15-11e8-974c-3f6eb99d3425.png)

比如上图的evernote 的 'r' 和 ‘n' 黏在一起了。
markdown 的 'r’ 和 'k'间距比较小

**Comment by suziwen** [comment]
这个跟选择的字体设计有关
