### ISSUE TITLE
小书匠与Gitlab没法绑定

### ISSUE THREAD

**Issue by PistonIntJack** [suziwen/markdownxiaoshujiang#796]
想用小书匠跟gitlab的wiki链接，仓库是wiki的gitlab，用git可以直接连接的，但小书匠没法连，token已经给了所有权限了.
报的错误是“检测失败，没有找到相应的仓库或者分支“；但那个仓库git是可以上传的，分支是master

**Comment by suziwen** [comment]
gitlab api 里对 wiki 支持跟对普通仓库支持不一样，只能自己通过本地绑定，然后 git 提交到 wiki.

https://docs.gitlab.com/ee/api/wikis.html

https://docs.gitlab.com/ee/api/repositories.html
