### ISSUE TITLE
输入```java的时候提示的选项第一个是javascript而不是java

### ISSUE THREAD

**Issue by baizhantang** [suziwen/markdownxiaoshujiang#798]
这个事情很头痛啊，它提示了又没办法取消，每次只能选择第二个 java。感觉很不爽，希望作者重视一下这个问题，体恤一下java开发者，别太偏心JavaScript

**Comment by suziwen** [comment]
好像输入 `j` 时，下拉第一个选项是  `java`, 可以直接回车 ,就选中 `java` 了
