### ISSUE TITLE
从预览文档大纲那点击标题，不能准确滚动到对应的位置。

### ISSUE THREAD

**Issue by jay763190097** [suziwen/markdownxiaoshujiang#799]

**Comment by suziwen** [comment]
最好能详细描述下你的预期效果，或者截图说明。不然可能你理解的准确定位跟我的不一样。

**Comment by jay763190097** [comment]
![_crx_jalbgaejjmdihbhmdepjgcdikbeclnbe_20180519192726](https://user-images.githubusercontent.com/16317178/40268182-b1813b7e-5b9b-11e8-8118-27dda2d83851.gif)

**Comment by jay763190097** [comment]
另外大纲我觉得比较重要，用得多，可以挪到左边

**Comment by suziwen** [comment]
6.0.0  修复
