### ISSUE TITLE
toc以及功能建议

### ISSUE THREAD

**Issue by fedstryale** [suziwen/markdownxiaoshujiang#8]
一直在关注这个project，离线版很给力，不过有两个问题：
1. 看到功能介绍，小书匠好像支持toc目录生成了，不过不知道生成toc有办法是有序列表吗，如1 1.1 1.1.1
2. 小书匠有无考虑加入简单的离线文件管理功能呢（许多在线编辑器都有），就是一个简单的本地文件的列表，现在没有网络的时候无法编辑多个文档，以前编辑过的文档也必须从evernote拉下来才能编辑，没有网络就不能完成了。如果有离线文件管理，就可以完全取代evernote客户端的本地编辑功能了。

**Comment by suziwen** [comment]
toc 编号可以通过自定义css（设置里有）,实现 .toc ul 的样式实现，也可以自己在每个标题前手动编号。系统暂时没办法自动生成编号。

将来会考虑离线文件管理功能的。

**Comment by fedstryale** [comment]
1.toc的确可以加入css改，不过只能在预览里生效，导出html和同步到evernote就不会出现编号了
2.我才发现在线版原来已经改得这么强大了，也加入了离线文件管理，而且离线版那个加入图片后导出zip再导入zip就不能看到图片的bug也改掉了，不知道什么时候离线版更新到现在在线版的版本就相当相当强大了

**Comment by xinshangshangxin** [comment]
ctrl + s 能不能静默保存,只是弹出个小窗就可以了; 因为 比较习惯 动不动就按下 ctrl + s

**Comment by suziwen** [comment]
嗯，会考虑的，离线的新版得等在线版稳定一段时间后，再放出来。

**Comment by suziwen** [comment]
离线版 
http://soft.xiaoshujiang.com/
http://soft.xiaoshujiang.com/version/Story-writer-v1.0.0/Story-writer-win32-setup.exe
http://soft.xiaoshujiang.com/version/Story-writer-v1.0.0/Story-writer-win64-setup.exe
