### ISSUE TITLE
保存为图片可以选择分辨率

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#800]
前段时间更新的功能，编辑图片功能非常强大，间接实现了当时我想要的保存当前页面的功能，但是目前发现编辑之后，特别时裁剪之后保存的图片分辨率有点低，不知道能否提高分辨率，或者自定义呢？

**Comment by suziwen** [comment]
不知道是不是我显示器问题，我这边编辑图片后，没看出图片质量被压缩多少。

你那能提供几张编辑前，以及裁剪后的图片吗，最好是前后效果相差比较大的图片。
