### ISSUE TITLE
ubuntu下预览模式中文字体超细

### ISSUE THREAD

**Issue by suinxinliulang** [suziwen/markdownxiaoshujiang#801]
ubuntu下预览模式中文字体比西文字体细太多
![2018-05-11 21-52-20](https://user-images.githubusercontent.com/37922670/39927785-fe3ec8f0-5565-11e8-953c-4683fe6215fd.png)

**Comment by suziwen** [comment]
可以到`设置>基本`， `设置>编辑器` 里修改自己系统有的字体。
