### ISSUE TITLE
甘特图横坐标不支持axisFormat %m

### ISSUE THREAD

**Issue by apas008** [suziwen/markdownxiaoshujiang#803]
甘特图横坐标不支持axisFormat %m
Parse error on line 3:
... DD/MM/YYaxisFormattitle PostNord Depl
----------------------^
Expecting 'taskData', got 'NL

官方mermaid已经能够支持
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHQgXG5kYXRlRm9ybWF0IEREL01NL1lZXG5heGlzRm9ybWF0ICVtXG50aXRsZSBQb3N0Tm9yZCBEZXBsb3ltZW50IFBsYW5cblxuU2VjdGlvbiBDb21tb25cblRhc2sgMSA6ZG9uZSwxMC8wMy8xNywgMTMvMDMvMTdcblRhc2sgMiA6ZG9uZSwgMDIvMTIvMTYsIDEzLzAzLzE3XG5UYXNrIDMgOmRvbmUsIDAyLzEyLzE2LCAxMy8xMi8xNlxuU2VjdGlvbiBTZWN0aW9uXzFcbkRlc2lnbiA6MDIvMTIvMTYsIDIyLzAyLzE3XG5EZXNpZ24gMiA6Y3JpdCwgMDIvMTIvMTYsIDA2LzAzLzE3XG5EZXNpZ24gMyA6Y3JpdCwgMDIvMTIvMTYsIDE4LzAzLzE3XG5cbk9yZGVyIHdhdmUgMSA6MjAvMDMvMTcsIDE0LzA0LzE3XG5PcmRlciB3YXZlIDIgOmNyaXQsIDI3LzAzLzE3LCAyMS8wNC8xN1xuT3JkZXIgd2F2ZSAzIDpjcml0LCAwMy8wNC8xNywgMjgvMDQvMTdcblxuRGVwbG95bWVudCBXYXZlIDEgOjE3LzA0LzE3LCAyMy8wNi8xN1xuRGVwbG95bWVudCBXYXZlIDIgOjI0LzA0LzE3LCAwOS8wNi8xN1xuRGVwbG95bWVudCBXYXZlIDMgOmNyaXQsMDEvMDUvMTcsIDA3LzA3LzE3XG5cblNlY3Rpb24gU2VjdGlvbl8yXG5EZXNpZ24gOmNyaXQsIDIzLzAyLzE3LCAxNS8wMy8xN1xuT3JkZXIgYW5kIERlbGl2ZXIgOiAyMC8wMy8xNywgMjgvMDQvMTdcbkRlcGxveW1lbnQgOjAxLzA1LzE3LCAxNi8wOC8xNyIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

**Comment by suziwen** [comment]
6.0.0 已支持。
