### ISSUE TITLE
怎么小书匠没法正常使用了！！！

### ISSUE THREAD

**Issue by sixleaves** [suziwen/markdownxiaoshujiang#805]
怎么小书匠没法正常使用了！！！怎么小书匠没法正常使用了！！！怎么小书匠没法正常使用了！！！怎么小书匠没法正常使用了！！！

**Comment by suziwen** [comment]
最好能出些具体项。

**Comment by sixleaves** [comment]
进去只有背景图，啥都没有

**Comment by suziwen** [comment]
把数据目录移到其他地方， 然后再启动呢。

Windows: %LOCALAPPDATA%/storywriter/ 
Mac: ~/Library/Application Support/storywriter/ 
Linux: ~/.config/storywriter

**Comment by sixleaves** [comment]
你确定mac是这个目录吗？我到这个目录下没有发下storywriter

**Comment by suziwen** [comment]
你的小书匠什么版本？

到这里下载个最新的 5.6.0 https://github.com/suziwen/markdownxiaoshujiang/releases

------------

 mac 下默认都是在这个目录的。 `Mac: ~/Library/Application Support/storywriter/`

**Comment by sixleaves** [comment]
我一直都用网页版

**Comment by sixleaves** [comment]
网页版不正常啊

**Comment by suziwen** [comment]
。。。。。

你用的什么浏览器，使用隐身模式打开呢？我这边网页版一直正常。

**Comment by sixleaves** [comment]
chrome，火狐都不行

**Comment by sixleaves** [comment]
![sweetcshttp___soft xia](https://user-images.githubusercontent.com/3601210/40224510-f83d3556-5ab8-11e8-9d35-4ef5bbc8417e.png)

**Comment by sixleaves** [comment]
也是醉了，要用这个地址才行。http://markdown.xiaoshujiang.com/

**Comment by suziwen** [comment]
好了，再加上了。
