### ISSUE TITLE
bug? 标题不能以[]开头

### ISSUE THREAD

**Issue by BianChengNan** [suziwen/markdownxiaoshujiang#808]
我是初次使用小书匠, 9分. 点赞.

有一个小问题, 我想以
**[原] 学习总结**
为标题创建笔记,保存到印象笔记完全不对了,而且在小书匠的渲染效果也不对. []在标题中也会被解析吗?个人感觉标题中不应该做什么解析,当成纯文本处理即可.

**Comment by suziwen** [comment]
元数据里，如果字符串有特殊符号的话，可以用引号包裹下。

```
---
title: "[原] 学习总结"
---
```
