### ISSUE TITLE
拍照截图功能错误

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#809]
昨天可以，今天就不能用了。换了浏览器仍然报错。
![image](https://user-images.githubusercontent.com/7530342/40211123-5dbe4570-5a7b-11e8-9bb3-a877d67ca61f.png)

**Comment by suziwen** [comment]
这个是点击拍照按钮后就报错，还是出现了图片编辑窗口，然后点保存报错？

**Comment by CharMingF** [comment]
点击拍照按钮就直接报错了

**Comment by suziwen** [comment]
是不是自定义了什么  css 样式，或者文章内容比较特殊？

用隐身模式打开窗口，然后拍照截图呢？

**Comment by CharMingF** [comment]
隐身窗口是可以的，后来我测试了其他文档，部分文档是可以的。而且好像和css无关，因为我把自定义的css清除了，好像还是不可以。
奇怪的是前天之前都是可以的。

**Comment by CharMingF** [comment]
经过反复测试，发现了问题所在，如果文档里有图片，就无法拍照了。
![image](https://user-images.githubusercontent.com/7530342/40264392-383dbb98-5b55-11e8-95e2-48b2c64b19ff.png)
如上图红框中的内容，去掉就可以拍照截图了。

**Comment by suziwen** [comment]
估计是图片被限制跨域访问了。

**Comment by CharMingF** [comment]
我用的是腾讯云 有解决办法么

**Comment by suziwen** [comment]
到腾讯控制台设置一下。

![image](https://user-images.githubusercontent.com/57370/40286260-2be737be-5cd8-11e8-8787-5923045c24a5.png)


![image](https://user-images.githubusercontent.com/57370/40286231-df585928-5cd7-11e8-9e64-a9f982276c9c.png)

**Comment by CharMingF** [comment]
腾讯云的跨域之前就设置过了，之前我无法链接，这是你给我的回复，#598 #461。
所以我之前都是设置好的，我又检查了一遍，发现还是不行。
我现在肯定的是这个功能本身出错了，因为我之前都是正常使用的。
另外，我清楚缓存后，使用小书匠自带的 “语法使用手册” ，去拍照，同样的错误。
所以我猜测所有外链都是有问题的，我尝试了自带的sm.ms及微博等，都失败了。

**Comment by CharMingF** [comment]
![image](https://user-images.githubusercontent.com/7530342/40347056-73678a18-5dd1-11e8-873a-e2e3b8d714d5.png)
![image](https://user-images.githubusercontent.com/7530342/40347116-a10a6436-5dd1-11e8-95ef-39861bd87fd3.png)

登陆之后会有错误，不知道是否和这个有关系

**Comment by suziwen** [comment]
前面的 data.xiaoshujiang.com 404 (Object Not Found) 不必管它，后面的 `Access-Control-Allow-Origin` 就说明跨域问题。
![image](https://user-images.githubusercontent.com/57370/40362490-3e96fcaa-5dff-11e8-938e-332c50c15c3f.png)

-----------------

我自己测试了下 `sm.ms` ，我这里可以拍照截图.......

![image](https://user-images.githubusercontent.com/57370/40362612-9ceb5ecc-5dff-11e8-8be8-4d8d396f52e0.png)

------------

真没办法的话，只能等下一个版本修复，修改成对跨域抓取失败的图片，再尝试从小书匠服务器中转拿一下。

**Comment by CharMingF** [comment]
谢谢作者耐心回复了，我想了下，之前可以使用应该是之前没有插图，所以没有注意。我暂时先想其他方法吧。

下面提供更多的信息供参考吧：
预览图片后的右上角的编辑 和 图片的地址的下方的编辑  都是可以调用编辑图片插件的，就是整个拍照截图不能调用插件。

**Comment by CharMingF** [comment]
![snipaste_2018-05-23_11-10-23](https://user-images.githubusercontent.com/7530342/40478486-c2427124-5f7b-11e8-9fa4-3954670e1e12.png)

**Comment by suziwen** [comment]
6.0.0 修复
