### ISSUE TITLE
重启应用后无法找到本地文件的根目录

### ISSUE THREAD

**Issue by 5290589** [suziwen/markdownxiaoshujiang#81]
`Error: ENOENT: no such file or directory, open 'D:\Program Files (x86)\Story\undefined\1...`

客户端:`1.6.1`
每次重新打开应用后，之前保存的本地文件根目录都失效，必须重新解绑再绑定。

**Comment by suziwen** [comment]
我这边一直没法重现，能给个详细些的重现操作步骤吗？

**Comment by 5290589** [comment]
就是进入应用，绑定本地系统后，这时能打开保存本地系统的文件。再关闭应用，打开应用，这时就无法找到之前绑定的路径了，保存文件时会提示找不到路径

**Comment by 5290589** [comment]
![image](https://cloud.githubusercontent.com/assets/14369930/10562760/70ddb4f2-759e-11e5-8caf-ebdf0d15db08.png)
![image](https://cloud.githubusercontent.com/assets/14369930/10562762/83ff8f92-759e-11e5-9f40-f27840d4750a.png)
![image](https://cloud.githubusercontent.com/assets/14369930/10562764/88727260-759e-11e5-88eb-9a00f0d6e695.png)
![image](https://cloud.githubusercontent.com/assets/14369930/10562765/97974284-759e-11e5-937c-1137099de19b.png)
![image](https://cloud.githubusercontent.com/assets/14369930/10562766/a00ab23e-759e-11e5-8049-0f63745ed4ca.png)
重新打开后：
左下角目录浏览无法查看，保存文件失败：

![image](https://cloud.githubusercontent.com/assets/14369930/10562784/54f1e9d8-759f-11e5-91ab-b5ca42c7f76b.png)



忘了插着第二个显示器了，所以把桌面截上了。

**Comment by suziwen** [comment]
客户端1.7.1已经更新解决,可以到 http://soft.xiaoshujiang.com 下载
