### ISSUE TITLE
手机不能显示绑定列表

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#812]
再去开发一个手机APP可能没有必要，现在网页版适配的感觉完全可以日常编辑使用，但是，不能显示印象笔记等的文件列表，也就不能选择编辑原来的文件，要是能在这方面改善，就完美了。

**Comment by suziwen** [comment]
在编辑区用手势向右滑动

**Comment by CharMingF** [comment]
@Jianzs  一般情况下，直接从边界划，会激活浏览器的返回功能，所以要从慢慢的点着边界，向右摔，哈哈
