### ISSUE TITLE
更新后codemirro编辑器的任务列表bug

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#815]
![image](https://user-images.githubusercontent.com/7530342/40576834-671426de-612f-11e8-9d2f-2eb8024ea259.png)
如图所示，在codemirror编辑器模式下，任务列表未完成之前是框框，如果完成则其会为对号框框，这个版本更新之后，完成会显示为深色框框。而且框框是长方形的，之前应该是正方形。

**Comment by suziwen** [comment]
暂时可以先通过关掉`设置>编辑器>codemirror > 自动预览checkbox`里的选项解决。

**Comment by CharMingF** [comment]
效率很高，已经好了 👍
