### ISSUE TITLE
无法正常保存到印象笔记 处理文件样式关联失败

### ISSUE THREAD

**Issue by Ayatujisang** [suziwen/markdownxiaoshujiang#820]
处理文件样式关联失败
保存失败: {"code":1007,"error":"服务器出错","orign":{"errorCode":2,"parameter":"Note.guid"}}

在公司保存就可以 回家保存就不行了 麻烦看看 只能保存一个md文件
这个问题相信不是我一个人碰到吧~

**Comment by suziwen** [comment]
处理文件样式失败，就是你可能自定义了 css 样式，这些样式规则有些不合法，导致不能正确转换成印象笔记支持的样式。

到`设置>预览>预览区自定义样式` 里把样式清空，再新建一篇简单的文章保存下呢？

**Comment by Ayatujisang** [comment]
不行 试过了 我没有自定义CSS样式 里面也看了确实是空的 不能正常保存 是因为使用了不同设备的原因,么? 我起初是在公司保存的 一切操作都正常 但是现在在家里使用私人电脑就无法保存 还有一个小问题 每一篇文章都要手动同步本地缓存 感觉很麻烦 有方法一次性同步的么?

**Comment by suziwen** [comment]
那感觉跟你的操作系统，或者外部软件限制引起的。
主要是我这边没法重现你说的，我遇到的印象保存失败所能定位到的问题就是自定义 css 错误引起的。其他原因还没有发现。

----------

目前只能自己手动更新缓存，或者把文档及时归档，然后用户下次点击印象笔记目录下的文件 ，就会自动更新为最新版本。

再一个就是使用小书匠提供的自定义数据中心（或者临时数据中心），小书匠就会自动同步数据库里的数据。
