### ISSUE TITLE
Win10 桌面版 预览

### ISSUE THREAD

**Issue by ScnuWang** [suziwen/markdownxiaoshujiang#823]
Win10 x 64桌面版 打开预览之后，右边的工具栏点击没反应，不知道是怎么回事?求解

**Comment by suziwen** [comment]
能给个截图看看具体哪个位置吗？ 小书匠 web 版本能正常点击吗？

**Comment by ScnuWang** [comment]
web版本流畅无比，刚刚准备起截图的时候打开桌面版，结果昨天的那个问题没有了，不知道怎么回事。那我还是继续用桌面版。
不过很喜欢你们的作品，界面UI也很酷炫，谢谢！
