### ISSUE TITLE
网页版打开后只剩下三篇使用说明，其余的都不见了？？

### ISSUE THREAD

**Issue by mjwonderful** [suziwen/markdownxiaoshujiang#825]
您好！
       今天打开网页版本后，先是一个使用提示，然后发现之前写的都不见了，只剩下三篇使用说明。另外，之前有绑定印象笔记账号，现在也提示未绑定。想咨询下是什么原因以及有没有办法恢复。用户名是mjdata@126.com；唯一编号：@1851。
       之前有清过一次浏览器缓存，不知道是否对此有影响。
       很好用的产品，希望能得到您的回复，谢谢。

**Comment by suziwen** [comment]
小书匠不提供任何数据存储服务的，所有数据都存在用户本地，包括 web 版本，如果浏览器清空所有缓存(数据库数据)，那小书匠的数据以及第三方绑定信息也会被清空的。基本上不可能再恢复过来，除非浏览器自己提供该功能。

----------------

小书匠账户系统是给会员用户使用的，但即使是会员用户，小书匠也不提供数据存储服务的，只提供数据临时中转，及自定义数据中心功能。

所以如果你清空了缓存，我这边没法办法帮你操作的。

建议自己平时完稿的文章及时保存到其他第三方存储，或者使用小书匠的自定义数据中心功能，自己搭建数据服务器，这样能保证数据安全。

**Comment by mjwonderful** [comment]
恩，谢谢解惑。
