### ISSUE TITLE
表格中的列指定宽度的问题

### ISSUE THREAD

**Issue by localking3693** [suziwen/markdownxiaoshujiang#827]
用小书匠编辑器做表格的时候，经常会遇到列的宽度不合理的问题，有的列太宽，有的列太窄，能不能增加一种语法或者其它的什么方式，在定义列的时候指定该列的宽度。

推荐一种方式：比如 React 中表格宽度的做法，把整个显示区域的宽度等分为 24 份，可以指定每一列分别占多少比例。

**Comment by suziwen** [comment]
一般的 markdown 语法是无法实现的。参考了很多其他 markdown 扩展语法，也都没有比较满意的。可以自己通过自定义 css 来调整表格指定列的宽度。

-------------

或者使用小书匠提供的表格组件功能。配合[小书匠表格组件可视化编辑器](https://github.com/suziwen/blogxiaoshujiang/blob/master/2018-3-30%20%E8%A1%A8%E6%A0%BC%E7%BB%84%E4%BB%B6%E7%BC%96%E8%BE%91%E5%99%A8%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)，可以自己调整表格宽度，合并单元格，表格嵌套等.
