### ISSUE TITLE
不知道有没有有使用Jupyter.导出的html无法正确导入小书匠

### ISSUE THREAD

**Issue by WuShaogui** [suziwen/markdownxiaoshujiang#828]
从Jupyter导出来的html在浏览器上显示非常完美,导入小书匠出现以下问题:

![default](https://user-images.githubusercontent.com/24794718/40952580-5f9d1696-68ae-11e8-95ec-da19514c4079.png)

这是不允许导入的html有script吗?

**Comment by suziwen** [comment]
是的，小书匠正文不允许自己嵌入脚本的。
