### ISSUE TITLE
为知笔记服务器失效

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#831]
最近为知可能更新了服务器（其官网通知维护），维护后，就无法绑定管理。麻烦更新下服务器地址吧。谢谢

**Comment by chen729223605** [comment]
我也是同样的情况 @suziwen  能不能解决？ 一直出现加载错误
加载出现错误{"code":1009,"error":"服务器错误","orign":{"code":502,"message":"Not Found"}}

**Comment by CharMingF** [comment]
@chen729223605  作者肯定能解决的，只不过最近可能没有时间，等等吧。之前就是这样的，需要修复服务器地址。

**Comment by chen729223605** [comment]
作者给力啊  解决了
