### ISSUE TITLE
发博客是双标题???

### ISSUE THREAD

**Issue by WuShaogui** [suziwen/markdownxiaoshujiang#833]
发到博客中的文章,去浏览器查看是双标题,如发到博客园的文章是这样的:
![default](https://user-images.githubusercontent.com/24794718/41028476-1ab5f3b4-69ac-11e8-8ad7-e148f4ed6ddb.png)

可不可以发布时不要把标题发布上去啊????

**Comment by ghost** [comment]
我也遇到这问题了，在发布到cnblogs上的时候。

**Comment by suziwen** [comment]
`设置>预览` 里，把`是否自动渲染元数据里的标题(title)` 选项去掉。
