### ISSUE TITLE
mac端截图放如文档中图片不显示

### ISSUE THREAD

**Issue by gaoyp27** [suziwen/markdownxiaoshujiang#838]
所有图片在编辑界面和预览界面都是显示![enter description here](./images/1528642621896.png)这种，不显示图片。使用的是本地土图床。

**Comment by suziwen** [comment]
无法重现你说的错误。最好能详细描述出错的情形，还有就是把出现错误的样例文章，图片提供一下。

**Comment by gaoyp27** [comment]
![14345d1a-160b-4a3c-aff5-208ee2bcec36](https://user-images.githubusercontent.com/10111085/41500103-971c92fe-71be-11e8-9180-17d870fef5f3.png)

下载文章里都是这样的显示状态，在插入图片，缓存图片能看到这些图片！

**Comment by suziwen** [comment]
你这已经是被当成代码块语法来处理了，把前面的空格去掉。

![image](https://user-images.githubusercontent.com/57370/41503914-2904b608-7212-11e8-94a1-1990dad46d37.png)

**Comment by gaoyp27** [comment]
确实是这个原因，非常感谢您的解答！
