### ISSUE TITLE
小书匠书写的文档用印象笔记打开后格式消失

### ISSUE THREAD

**Issue by gricn** [suziwen/markdownxiaoshujiang#841]
小书匠V5.60  印象笔记最新版
如图
![14](https://user-images.githubusercontent.com/34237589/41275660-33898674-6e54-11e8-877a-cc7379e2ca99.png)
但原本在小书匠编辑的时候内容缩进还是有的，请问这是小书匠的问题还是印象笔记的问题？
期末在即，还望即使告知

**Comment by suziwen** [comment]
没明白你描述的问题。是想说通过小书匠编辑器保存后，在印象笔记客户端里什么内容都没有了，只有一个 markdown 附件？
