### ISSUE TITLE
为知笔记绑定之后同步报错

### ISSUE THREAD

**Issue by xiyueliuyun** [suziwen/markdownxiaoshujiang#844]
为知笔记V2绑定之后同步报错
错误信息：
加载出现错误{"code":1009,"error":"服务器错误","orign":{"code":502,"message":"Not Found"}}

**Comment by roseion** [comment]
![snipaste_2018-06-13_17-07-43](https://user-images.githubusercontent.com/38565188/41341460-58321094-6f2c-11e8-9c22-2de3cd03364e.png)

 我也遇见了同样的问题，两种绑定方式均不可，重新绑定也不行。

**Comment by suziwen** [comment]
#831
