### ISSUE TITLE
dropbox读取时出错

### ISSUE THREAD

**Issue by CharMingF** [suziwen/markdownxiaoshujiang#845]
![image](https://user-images.githubusercontent.com/7530342/41386055-0c223752-6fb2-11e8-938b-65db13d2d257.png)
dropbox在授权成功后，读取报错，但是奇怪的是可以正常读取内容，但是总会有错误，有时候无法读取出来。

**Comment by suziwen** [comment]
没法重现你说的情况。所有文章都会报这个错误？在 dropbox 创建一篇简单的 md 文件 ，然后通过小书匠读取呢？
