### ISSUE TITLE
请问能出一个编辑器内的检索功能吗

### ISSUE THREAD

**Issue by Watereggs** [suziwen/markdownxiaoshujiang#846]
希望有个文章内的搜索功能，可以快速跳到搜索的关键字地方。后期修改大篇幅的文字的时候会很高效。要是能有检索替换就更好啦。

**Comment by suziwen** [comment]
在编辑区里按 `ctrl+f` ，出现查找对话框，连续按两次出现查找替换对话框。

**Comment by xmeng1** [comment]
或者点击 查询窗口的 + 号,悬浮有提示
