### ISSUE TITLE
请问小书匠是要连接后台服务器的吗？

### ISSUE THREAD

**Issue by luoshu-open** [suziwen/markdownxiaoshujiang#849]
请问这个软件是要连接后台服务器，还是一直通过客户端就可以完成所有的功能，比如像印象笔记的保存，这个是客户端独立完成还是有后台配合啊，其实我在想万一哪天小书匠的服务器出问题了，我还能保存进去不哈哈

**Comment by suziwen** [comment]
客户端除了联网 pdf 打印功能需要连接到小书匠服务器，其他功能（印象笔记，为知等操作）都是在本地执行的。

**Comment by luoshu-open** [comment]
@suziwen 谢谢，无论我是否能用上小书匠的付费功能，我都购买了。因为像这样纯粹的软件真的不多了，感觉作者
