### ISSUE TITLE
metaweblog支持加强。

### ISSUE THREAD

**Issue by PterX** [suziwen/markdownxiaoshujiang#85]
对于您开发的这个工具，真的是很是喜欢，也是非常支持。但是，发布功能目前还不太好用。

大概看了下您的源码，是分析blog页面的RSD标签。对于csdn没有这个标签的就无法支持。
我用privoxy模拟了一个。然后看到报了一个无效的Tag META。应该是csdn api页面多了一个meta标签导致的，这个可能需要在xmlrpc做一下兼容。

总结：
1、可能需要开放自由填写api地址的功能。
2、需要xmlrpc容错处理。
3、对于多平台，还是希望能做到平台帐号管理。

**Comment by suziwen** [comment]
* csdn我记得好像是不开放api的，也就是不支持metaweblog的。
* xmlrpc容错处理会改进的。
* 账号管理是指什么的？

**Comment by PterX** [comment]
× 我看到的消息说是去年csdn又开放了，并且metaweblog api页面可以访问。
× 帐号管理，比如同时使用多个博客平台，就有多个帐号，希望能在发布的时候下拉选则就行，不用每次都单独填写。

**Comment by suziwen** [comment]
csdn 的metaweblog api有相关的链接地址吗,我一直没找到.
