### ISSUE TITLE
带编号的公式导出html后行宽过大

### ISSUE THREAD

**Issue by heatfx** [suziwen/markdownxiaoshujiang#86]
Mathjax 输入公式有一个可以输入带编号的公式的功能，真的是非常吸引人的一个特点。不过在另存到笔记本（有道笔记本，印象笔记本都试过）或者导出为html文件时，公式所在行似乎变成固定行宽，而且行宽很大，总要拖动底部的水平滚动条才能看到编号。在小书匠的编辑器自带的预览显示没有这个问题，导出pdf也没有这个问题。

比如在编辑器里面：
![equation](https://cloud.githubusercontent.com/assets/4026213/10422539/6b34edea-70ee-11e5-9695-9ea63621d54d.png)

导出后显示如下，是超长的一行，需要缩小页面才能完全显示：
![toolong](https://cloud.githubusercontent.com/assets/4026213/10422592/f7bff732-70ee-11e5-8a93-747af6d6a315.png)

**Comment by DereckZhang** [comment]
同问题，带编号的公式在Evernote中显示太小
![image](https://cloud.githubusercontent.com/assets/7668825/10578134/d0bc0c48-76a2-11e5-8599-a49bb55af3a0.png)

**Comment by suziwen** [comment]
客户端1.7.1已经更新解决,可以到 http://soft.xiaoshujiang.com 下载
