### ISSUE TITLE
会员哪里能下载最新版啊？

### ISSUE THREAD

**Issue by fainboy** [suziwen/markdownxiaoshujiang#860]
经常能看到更新提示，让去官网下载，但官网（包括 GitHub 的 releases 里）都找不到最新版，比如这个 6.1.0。
以前软件还能自动升级，怎么现在总是要到官网下载，却找不到，真是闹心！
哪里可以下载啊？
（终于忍不住来吐槽了）

**Comment by suziwen** [comment]
先下载 `6.0.3` , 然后启动会提示更新到 `6.1.0`

有些版本升级涉及到底层代码的修改，没法实现在线更新，就会发布一个新的客户端版本。这时，所有想要升级到下一个版本的用户，都需要先下载  http://soft.xiaoshujiang.com 客户端版本。

**Comment by fainboy** [comment]
我的是 6.0.2，有提示更新到 6.1.0，但我在官网和 github 里根本找不到哪里有 6.1.0 下载，这是问题关键哦。

**Comment by suziwen** [comment]
就是到官网里下载 `6.0.3`,然后启动小书匠，会提示你自动升级到 `6.1.0`

**Comment by fainboy** [comment]
哦哦，明白了，不过这个升级方式实在繁琐，直接提供 6.1.0 下载不更好吗？
为了 6.0.2 -> 6.1.0，我还得先下 6.0.3。

**Comment by suziwen** [comment]
1. 一般是有底层文件的修改，或者严重的错误，或者定期重要版本的更新，才会发布新的客户端版本
2. 没直接发布 `6.1.0` 客户端版本，还有商业化的考虑。
3. 直接在线更新发布流程大概需要半小时就能搞定。如果是打包成客户端发布让下载，目前最快要整理半天的时间。

**Comment by fainboy** [comment]
嗯，理解。辛苦了~
提个小建议，在更新里可以增加更多的提示，比如：需要先更新至 6.0.3，系统会自动升级至 6.1.0。
这样可能会更友好一些。
