### ISSUE TITLE
换了台电脑为啥之前绑定的印象笔记账户就没了？

### ISSUE THREAD

**Issue by carlosxu312** [suziwen/markdownxiaoshujiang#861]
我换了台电脑，之前绑定的账户全没了，这是咋回事

**Comment by suziwen** [comment]
小书匠是一个纯客户端产品，所有数据都是保存在用户自己电脑上的，包括浏览器 web 版本，数据也是保存在用户自己当前的电脑上的。如果换电脑，用户数据，用户配置肯定没有同步的。

------------

小书匠还提供了会员服务，提供用户配置同步，用户自定义数据中心等。但即使是会员用户，也需要自己打开配置同步功能，小书匠默认是关闭配置同步的。

![image](https://user-images.githubusercontent.com/57370/41976811-7f17849e-7a50-11e8-846b-5b83b194b208.png)

**Comment by carlosxu312** [comment]
明白了，谢谢

**Comment by carlosxu312** [comment]
再问一下，如果我的电脑清除了cookie，那保存的东西还会存在吧

**Comment by suziwen** [comment]
目前数据只存储在 localStorage 和 IndexedDB 里， cookie 没有保存数据。
