### ISSUE TITLE
打不开软件了

### ISSUE THREAD

**Issue by MingGH** [suziwen/markdownxiaoshujiang#866]
![image](https://user-images.githubusercontent.com/32670399/42044112-bec22e8e-7b2a-11e8-9a84-494f7a1e484b.png)
卡在这个界面了，系统是win10,刚刚下载下来还没用1小时，关闭程序后重新启动就卡住了

**Comment by suziwen** [comment]
把数据目录移走，重新启动


数据库文件路径

```
Windows: %LOCALAPPDATA%/storywriter/
Mac: ~/Library/Application Support/storywriter/
Linux: ~/.config/storywriter
```

**Comment by MingGH** [comment]
说起来，你可能不信，它竟然**没有**,还是说我找错位置了...
![qq 20180702082632](https://user-images.githubusercontent.com/32670399/42140435-ff261af4-7dd1-11e8-8aa2-90322a8cf7cb.png)

**Comment by suziwen** [comment]
你下载的小书匠估计不是最新的 `6.0.3` 版本

https://github.com/suziwen/markdownxiaoshujiang/releases

**Comment by MingGH** [comment]
他有提示过我更新，确实不是最新版，我试试最新版
