### ISSUE TITLE
验证用户失败，请确认token是否有效[object Object]

### ISSUE THREAD

**Issue by XiaoTianWork** [suziwen/markdownxiaoshujiang#867]
绑定印象笔记提示，无法进行绑定

**Comment by XiaoTianWork** [comment]
@suziwen

**Comment by suziwen** [comment]
我这边可以正常绑定。

感觉是你那边网络限制，或者第三方程序限制了。

**Comment by XiaoTianWork** [comment]
偶发性出现的，也很迷

**Comment by mykgzy** [comment]
验证用户失败，请确认token是否有效[object Object],同样出现这个问题了。重装等无效。是不是有些地方需要清缓存文件什么的。 web版小书匠绑定没问题

**Comment by suziwen** [comment]
@mykgzy 

可以试着把小书匠的数据目录先移走, 再启动小书匠,重新绑定,看能不能成功.

`数据目录` 位置可以在 `关于` 界面上找到.

**Comment by mykgzy** [comment]
@suziwen 我把数据目录的东西全部删除后然后重装，再绑定还是报错。
我看stroy.log文件的日志为：
2020-09-02T10:51:50.060Z - error:  code=1006, error=服务器出错....{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},

**Comment by suziwen** [comment]
@mykgzy 
无法验证的签名，像是你的网络环境有问题.  可以试着切换一个网络,再绑定看看.

**Comment by mykgzy** [comment]
我用手机当热点试了下，确认是公司网络问题，估计把端口屏蔽了，即使绑定后也同步不了笔记。
