### ISSUE TITLE
使用gmail邮箱注册异常

### ISSUE THREAD

**Issue by Ya-RZ** [suziwen/markdownxiaoshujiang#873]
无法受到验证邮件，看来是被屏了。gmail地址没问题。
已用163邮箱注册，秒收。

希望官方能够加上相应提示或者手动发送验证邮件。

**Comment by sprders** [comment]
gmial邮箱地址没问题

**Comment by suziwen** [comment]
我这边 gmail 能正常收到，看看是不是被放到垃圾箱里，或者你自己自定义规则过滤掉了。

**Comment by Ya-RZ** [comment]
@suziwen 还真是在垃圾箱里，多谢
