### ISSUE TITLE
印象笔记绑定问题，想问一下是软件bug，还是印象授权有问题

### ISSUE THREAD

**Issue by ranniyue** [suziwen/markdownxiaoshujiang#874]
![image](https://user-images.githubusercontent.com/15190244/42410045-4eb049f8-8216-11e8-9a5c-3f16df2b1b5a.png)

**Comment by suziwen** [comment]
我这边可以正常绑定。

感觉是你那边网络限制，或者第三方程序限制了。

**Comment by ranniyue** [comment]
有时候可以，有时候出错
