### ISSUE TITLE
行内代码有无其他显示方案 

### ISSUE THREAD

**Issue by HowardMaCloud** [suziwen/markdownxiaoshujiang#876]
如题，最近刚刚上手这个软件，与马克飞象也对比过，个人认为小书匠的定制化更高，但是在使用中发现几个问题：
    1、我希望行内代码的显示较为亮一点，不是飘黄的那种高亮，而是类似于区别于其他文字的，比如马克飞象的那种红色，因为更容易识别一点，默认的样式在阅读的时候不太方便，特别是底色域的笔记本，不知道是不是已经有设置了，而我未找到，我看到块代码有显示样式，但是行代码貌似都一样。
    2、我使用的浏览器是Chrome，在编辑无须列表，使用“-”时，第一个编辑完，敲击回车会自动生成第二个列表，但是输入的光标是在第二个列表的下一行，导致每次都需要切换到该行，不知道这个是设置问题还是软件自身的考虑？
    3、我习惯用鼠标来切换光标位置，在使用时发现很多时候鼠标点击后没有用，光标一直在标题栏那里的第一个位子，只能用方向键切换，不知道这个是设置问题吗？
    期待您的回复，谢谢！

**Comment by suziwen** [comment]
1. 可以自定义 css 样式 #711
2. 3. 没出现你描述的情形，可能跟你的浏览器安装的扩展或者其他什么输入法有关。
