### ISSUE TITLE
如何绑定github账号

### ISSUE THREAD

**Issue by PraflyGod** [suziwen/markdownxiaoshujiang#877]
如题。我绑定的时候，总是出错，但是看不到出错的提示。

**Comment by PraflyGod** [comment]
提示： 检测失败，使用的token没有找到相应的仓库。
仓库那里填写的格式是什么？

**Comment by suziwen** [comment]
最好提供下重现时，你提交的数据格式

**Comment by PraflyGod** [comment]
![image](https://user-images.githubusercontent.com/13954697/43206526-8839b682-9058-11e8-8f30-3833b22a579d.png)

**Comment by suziwen** [comment]
仓库名称写 blog 就可以了

**Comment by PraflyGod** [comment]
![image](https://user-images.githubusercontent.com/13954697/43356373-45bacea8-92a2-11e8-848e-34253bbfccf6.png)

**Comment by PraflyGod** [comment]
还是不成功

**Comment by PraflyGod** [comment]
原来是仓库没有初始化。
