### ISSUE TITLE
是否可以添加一个  使：编辑区和预览区左右互换 的功能

### ISSUE THREAD

**Issue by valjeta** [suziwen/markdownxiaoshujiang#88]
**效果如下图：** 
![](http://7xldom.com1.z0.glb.clouddn.com/QQ截图20151018024748.png)

**Comment by suziwen** [comment]
预览区边上按钮

![image](https://cloud.githubusercontent.com/assets/57370/21964073/ee9f146c-db0a-11e6-9145-33fa22bda6f6.png)
