### ISSUE TITLE
Evernote中字体的问题

### ISSUE THREAD

**Issue by fengjianyun** [suziwen/markdownxiaoshujiang#881]
你好，我今天才接触小书匠，试验了一下，非常好用。

不过有个小问题，我是把笔记同步到Evernote中。但是在Evernote中看时，代码的背景、颜色都保留下来了，但是字体用的是我Evernote的默认字体。而我Evernote因为还有其他来源的笔记，所以没有用等宽字体，造成小书匠生成的笔记的代码也不是等宽字体。

有没有什么办法能解决这个问题呢？谢谢！

**Comment by suziwen** [comment]
自定义css样式

**Comment by fengjianyun** [comment]
@suziwen  谢谢，问题解决了。
