### ISSUE TITLE
多行代码在evernote中显示为单行代码

### ISSUE THREAD

**Issue by desperadoshi** [suziwen/markdownxiaoshujiang#89]
问题如题。

---

在小书匠中写好markdown内容，同步到evernote中。

小书匠中代码如下图

![code](https://cloud.githubusercontent.com/assets/9106886/10571761/b39755e2-7674-11e5-9bfa-61f6a1412cb7.PNG)

Evernote中显示如下图

![evernote](https://cloud.githubusercontent.com/assets/9106886/10571769/c206704a-7674-11e5-93fc-e40522d05304.PNG)

**Comment by suziwen** [comment]
小书匠用的是哪个版本(客户端或者web版)？evernote是用web查看还是evernote自己的客户端？最新版本（1.7.0）测试是没有问题的。

**Comment by desperadoshi** [comment]
+ 谢谢您的迅速回复
+ 我使用的Evernote客户端版本是5.9.1.8942
+ 我使用的小书匠客户端版本是1.6.1
+ 所以为了正常使用，我需要使用1.7.0版本的小书匠？

**Comment by suziwen** [comment]
#79 

客户端升级到1.7.0就可以了

**Comment by desperadoshi** [comment]
的确升级到1.7.0就正常了
