### ISSUE TITLE
预览中的信息复制到outlook样式全没有了

### ISSUE THREAD

**Issue by zbqBaoqing** [suziwen/markdownxiaoshujiang#893]
最近刚开始用小书匠，不可否认，小书匠是很不错的，但我发现从预览中复制到outlook后，样式全没有了~
小书匠用的6.0.3 outlook 16.15~
很无奈啊~

**Comment by zbqBaoqing** [comment]
![1](https://user-images.githubusercontent.com/3815057/43673334-a5b1f5d8-97f3-11e8-907d-f0155f8d4ec5.png)
![2](https://user-images.githubusercontent.com/3815057/43673337-af295872-97f3-11e8-82fa-65daa827f717.png)

**Comment by suziwen** [comment]
这个感觉跟 outlook 关系比较大，可以试着导出内联样式的 html, 再从 html 复制到 outlook.

或者直接使用小书匠的发送邮件功能。
