### ISSUE TITLE
Mac版本升级6.2.0之后无法绑定evernote，提示文件列表获取错误

### ISSUE THREAD

**Issue by jctn** [suziwen/markdownxiaoshujiang#896]
![image](https://user-images.githubusercontent.com/6377240/43874474-a4c58530-9bbe-11e8-94c6-c9cecaeaef07.png)

**Comment by fengjianyun** [comment]
我用6.0.3版，也出现这个问题。昨天还好着，今天就出问题了。

**Comment by oska874** [comment]
绑定不了evernote了，绑定印象笔记正常
win7平台，网页版。

**Comment by suziwen** [comment]
#899

**Comment by suziwen** [comment]
已修复，下载 6.2.1 版本
