### ISSUE TITLE
无法使用evernote

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#897]
绑定不了evernote了，弹出网页，但是不跳转到evernote 的授权网页。
绑定印象笔记正常
win7平台，网页版。

**Comment by heart5** [comment]
因为evernote官方拒绝非https的服务了。希望网站方尽快解决。拜托。谢谢。

> 亲爱的客户,我们最近发现与你的 Evernote 帐户绑定的一个应用程序一直未使用 HTTPS 安全传输你的数据。为保护你的帐户，我们已从你的帐户中撤销这些应用程序并阻止它们使用我们的服务。我们已通知应用程序作者，一旦他们更新其应用程序使用 HTTPS，我们将予以恢复。届时，你能够将该应用程序重新绑定至你的帐户。

**Comment by oska874** [comment]
印象笔记也无法绑定了@suziwen

**Comment by suziwen** [comment]
#899

**Comment by suziwen** [comment]
已修复，下载 6.2.1 版本
