### ISSUE TITLE
元数据tags如果多个标签都包含特殊符号，只能添加第一个

### ISSUE THREAD

**Issue by vindevil** [suziwen/markdownxiaoshujiang#898]
比如：
tags: "#OtherTags|XiaoShuJiang", "@学习|时间项目知识管理"
同步到Evernote后，笔记只有第一个标签#OtherTags|XiaoShuJiang

并且这种情况下，会导致元数据中title等也不渲染，在预览中看不到title

**Comment by suziwen** [comment]
元数据如果有特殊符号，需要严格遵循yaml语法

**Comment by suziwen** [comment]
正确的写法
```
tags: ["#OtherTags|XiaoShuJiang", "@学习|时间项目知识管理"]
```
