### ISSUE TITLE
桌面客户端同步和加载Evernote(国际版)出现错误, code 1006, Invalid DataView length undefined

### ISSUE THREAD

**Issue by vindevil** [suziwen/markdownxiaoshujiang#899]
突然就同步不了笔记，也加载不了evernote笔记列表，出现如下错误：
![2018-08-10_044659](https://user-images.githubusercontent.com/11132484/43937360-bda36186-9c8f-11e8-8d10-5d18fa6bd3da.png)

卸载并重装windows客户端，并重新授权，也没能解决。用chrome在线版没有问题，可以正常同步和加载。

**Comment by protea-ban** [comment]
我也是这个问题，用的是Windows版的

**Comment by vindevil** [comment]
现在我用chrome的小书匠，也不能同步了，不知道为什么。提示授权token无效，重新尝试授权evernote，结果授权页面一直空白。而点击“印象笔记”出现了授权页面。

路由器翻墙，youtube等都正常，应该不是翻墙的问题。

查看evernote应用授权列表，发现没有小书匠了。

用sublime text 3可以获取笔记和编辑同步。

**Comment by vindevil** [comment]
而且今天我的Evernote windows客户端旧版本（6.6.4）无法同步，退出账户后，无法重新登陆。安装最新版6.13后才能正常登陆和同步。猜测是不是Evernote官方后台做了什么调整，限制了一些旧客户端和接口的登陆。

**Comment by vindevil** [comment]
原来是 evernote 发现旧版本 windows 客户端以及部分旧接口有未加密的问题，所以拒绝 6.4-6.7 windows 客户端登陆，以及使用旧版接口的第三方编辑器登陆。看来小书匠要更新接口了。
https://discussion.evernote.com/topic/115348-evernote-for-windows-update-required/

这里（https://www.v2ex.com/t/478453） 有人提到马克飞象作者经过调整后解决了问题。

**Comment by suziwen** [comment]
抱歉，目前不在工作电脑边，无法及时更新，预计9月份再提供修正的下载客户端。

个人感觉 Evernote 这样做得有点急，起码先通知开发者，给开发者一个缓冲的时间，直接禁用掉有点武断。

**Comment by oska874** [comment]
@suziwen 能否提供导出md和文档中插入的图片的方法，方便我们导出内容，在其他地方编辑

**Comment by fengjianyun** [comment]
我接到evernote的邮件，大意是要用HTTPS来连了，不用HTTPS连的全给禁了，然后又说也会通知开发者。

**Comment by suziwen** [comment]
导出zip 就会包含图片

**Comment by OumCc** [comment]
@suziwen 现在是要等更新才可以解决这个问题？

**Comment by suziwen** [comment]
已修复，下载 6.2.1 版本
