### ISSUE TITLE
evernote的token失效，官方提示是因为没用使用https所以取消了

### ISSUE THREAD

**Issue by heart5** [suziwen/markdownxiaoshujiang#900]
evernote好霸道，检测到不支持https直接把我通过“小书匠”生成的开发API的token给禁止了。个人急用，希望能够尽快解决。谢谢了。

摘抄官方邮件部分内容如下：
> 亲爱的客户, 我们最近发现与你的Evernote 帐户绑定的一个应用程序一直未使用 HTTPS 安全传输你的数据。为保护你的帐户，我们已从你的帐户中撤销这些应用程序并阻止它们使用我们的服务。我们已通知应用程序作者，一旦他们更新其应用程序使用 HTTPS，我们将予以恢复。届时，你能够将该应用程序重新绑定至你的帐户。

**Comment by suziwen** [comment]
#899

**Comment by suziwen** [comment]
已修复，下载 6.2.1 版本
