### ISSUE TITLE
为什么过一会github授权就不可以使用了

### ISSUE THREAD

**Issue by PraflyGod** [suziwen/markdownxiaoshujiang#901]
刚开始绑定到github的时候，是好的。但是保存一两次之后，就会失败了。
![image](https://user-images.githubusercontent.com/13954697/43990949-54db1818-9d95-11e8-89d0-737904e4cf15.png)

**Comment by PraflyGod** [comment]
是不是保存太频繁，然后出错。我第二天保存，又正常了。

**Comment by suziwen** [comment]
提示409冲突，应该是保存太频繁。
