### ISSUE TITLE
mac下 6.0.3无法绑定印象笔记，弹框都不出来

### ISSUE THREAD

**Issue by OumCc** [suziwen/markdownxiaoshujiang#902]
![image](https://user-images.githubusercontent.com/10840542/43992910-33c314dc-9db8-11e8-9639-8e2a4cfa753c.png)

如上图

在mac下，点击绑定，加载不出

**Comment by kingstorms** [comment]
windows下也一样，同问

**Comment by suziwen** [comment]
#899

**Comment by mornone** [comment]
windows下面印象笔记也无法弹出授权框了

**Comment by ttimasdf** [comment]
哪个平台都不行。Linux +1

**Comment by suziwen** [comment]
已修复，下载 6.2.1 版本
