### ISSUE TITLE
为什么我不能登录了呢？然后找回密码，注册都不可以哎

### ISSUE THREAD

**Issue by liango2** [suziwen/markdownxiaoshujiang#903]
为什么我chrome浏览器不能登录了呢？然后找回密码，注册都不可以哎？求帮我看看，换了个Microsoft Edge也一样不行

![image](https://user-images.githubusercontent.com/5696817/43998910-86e70080-9e33-11e8-93e1-9ffeac409502.png)

**Comment by suziwen** [comment]
邮箱不存在。确认你注册的邮箱是否正确。
