### ISSUE TITLE
关于安装包大小的问题

### ISSUE THREAD

**Issue by xiebruce** [suziwen/markdownxiaoshujiang#906]
我说的是Mac版的（都是当前最新版）：
有道云笔记：9.3M
evernote：60.1M
为知笔记：74.8M
小书匠：109.8M

不知是什么原因导致体积相差如此之大呢？当然这不属于bug哈，不好意思好像只能在issue里提问，而我又有点好奇，哈哈

**Comment by suziwen** [comment]
可能是小书匠功能比较强大，比较多吧，😅😅。

**Comment by xiebruce** [comment]
@suziwen 呃。。。可能是吧，哈哈！有个问题：
绑定为知笔记v2版的时候，如果我密码输入错了，为知那边报错信息你直接抛出来了哦，应该直接抛出returnMessage就好啦！好吧，其实这个不是功能性的错误，改不改都无所谓了
<img width="299" alt="qq20180814-103307 2x" src="https://user-images.githubusercontent.com/13575500/44068657-c3e76030-9fad-11e8-92d4-81b99f3143de.png">

**Comment by suziwen** [comment]
这个软件面向程序员的比较多，一些错误信息感觉越多越好，比较好排查问题。
