### ISSUE TITLE
无法读取有道云笔记的内容

### ISSUE THREAD

**Issue by JunHong1995** [suziwen/markdownxiaoshujiang#909]
我看了下有道云的API，上面有查看笔记的API了，请问什么时候可以跟进？

**Comment by suziwen** [comment]
这是他们家很久以前的 API , 自从他们家升级了新的底层后，一直没有跟进自家的 api ,导致部份 api 已经完全无法使用。所以我这边也没办法进行有道云笔记内容的读取。
