### ISSUE TITLE
无法绑定github

### ISSUE THREAD

**Issue by oneweek20169902** [suziwen/markdownxiaoshujiang#911]
![image](https://user-images.githubusercontent.com/19389964/44257954-370cea00-a240-11e8-86ea-fc37a081c697.png)
如图
没有提示成功，看图中是报错了，但是没有错误信息

**Comment by Byzero512** [comment]
使用最新版本就好了

**Comment by suziwen** [comment]
仓库名称  `blogs` 就可以了，不用整个链接地址
