### ISSUE TITLE
不能从有道云笔记抓取文件

### ISSUE THREAD

**Issue by CapZhang** [suziwen/markdownxiaoshujiang#913]
![image](https://user-images.githubusercontent.com/19522615/44378136-87cb5e00-a532-11e8-9abd-19a5b3c800ed.png)

说是能支持存取，但是实际上只能存，即使开了VIP，也是只能存，有道云

**Comment by suziwen** [comment]
这个说明比较老，当时是支持的，后来有道自己升级版本，有道又没升级自己的接口，就无法支持了。小书匠会员区别没有哪个地方说是支持的
