### ISSUE TITLE
预览区自定义样式Bug

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#92]
为实现首行缩进的功能，我在`设置`-`预览区自定义样式`中添加了：
```
p
  {
  text-indent:2em;
  }
```
虽然右侧预览区显示正常，但是同步到Evernote后，行内公式前会多出两个空格：
![image](https://cloud.githubusercontent.com/assets/7668825/10632501/70be2e5e-7817-11e5-9873-20e243e08dd8.png)

**Comment by suziwen** [comment]
这个是因为latex要将svg转换成图片,然后全局的css影响到了这个图片公式
可以这样设置

```
p{
  text-indent:2em;
  }
p .mathjax>.MathJax_SVG{
text-indent:0;
}
```

想要配置出一份自己想要的css,可以通过右侧预览区"查看html"按钮查看生成的html,如果是同步到第三方的话,可以先自己用"导出"功能,导出inlinestyle+svg=>jpg的html,然后看看生成的html内容,再配置出自己想要的css.

**Comment by DereckZhang** [comment]
非常感谢，我对CSS只懂皮毛。。。

**Comment by DereckZhang** [comment]
@suziwen 使用您给出的自定义CSS：
```
p{
  text-indent:2em;
  }
p .mathjax>.MathJax_SVG{
text-indent:0;
}
```
之后，虽然公式正常了，但是其他一些地方，比如列表还是会发生错位：
![qq 20151021223503](https://cloud.githubusercontent.com/assets/7668825/10639708/346b3ac8-7844-11e5-8799-bbbbd5d9cdeb.png)
研究了一下，您采用的方法似乎是通过<span>标签定义，但是无序列表没有<span>标签，似乎不能使用同样的办法解决，奇怪的是，以前使用马克飞象时，自定义渲染CSS里直接写：
```
p{
  text-indent:2em;
  }
```
就可以仅调整文字的位置，而不影响列表。

**Comment by DereckZhang** [comment]
@suziwen 使用
```
p{
  text-indent:2em;
  }
```
来解决首行缩进的问题，还会导致另一个问题：一张图片（包括转换成图片的公式、流程图等）或一个视频单独为一段时会出现2em的错位，这个问题在小书匠预览时就会出现。
要想比较清楚地看到这种情况，可以在单独一段（前后均有空行，前无文字）插入一张较大的图片/视频（宽度超过显示界面宽度）：

![qq 20151021232003](https://cloud.githubusercontent.com/assets/7668825/10641327/66936276-784b-11e5-8ae7-3cafbfc24f44.png)

个人猜测可能的原因是CSS缩小图片时，缩小为100%的宽度，而没有考虑到首行缩进的问题。
在马克飞象中，类似的情况下，程序内预览并没有问题，但是同步到Evernote时也存在同样的问题。
事实上，对单独成段的图片或视频，我们并不需要缩进，如何智能的判断是一个问题。
目前对此我也找到了一个解决方案，单独成段的图片或视频，只要强制居中`->XXX<-`就可以解决这个问题。

**Comment by suziwen** [comment]
因为生成的html结构不同,
小书匠在ol, li里会生成 p标签来包裹内容.

可以试试这样的css

```
.preview>p{
  text-indent:2em;
  }
p .mathjax>.MathJax_SVG{
text-indent:0;
}
```

图片的话,由于 img标签是当成行内标签的, 所有单独一段的图片标签最终会生成 `<p><img></p>` ,这样的结构形式,因为你设置了p 为缩进,所以也会影响img标签.

img标签想不受影响的话,可以配合居中语法`grammar_center`,或者对齐语法`grammar_align`

使用居中语法的话, 生成的标签就是 `<center><img></center>`
对齐语法的话,生成的标签就是`<div class="story_align_{left\center\right}"><img></div>`,这样的形式.这两个就都不会影响图片缩进了
