### ISSUE TITLE
为什么封面标题不出来了？

### ISSUE THREAD

**Issue by prolover** [suziwen/markdownxiaoshujiang#927]
![face](https://user-images.githubusercontent.com/22161404/45069023-09a7b380-b0fd-11e8-9be5-7656826392c8.jpg)
![face2](https://user-images.githubusercontent.com/22161404/45069024-0a404a00-b0fd-11e8-9175-d09b64a7b416.jpg)

为什么会这样？

**Comment by suziwen** [comment]
字体颜色改成黑色就可以了 `#000`
