### ISSUE TITLE
增加公式输出格式为SVG的选项

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#93]
希望像马克飞象那样有公式输出为PNG或SVG的选择。SVG无损缩放清晰度好，但有些情况如低版本的Android和Gmail不支持：

![qq 20151021172817](https://cloud.githubusercontent.com/assets/7668825/10632826/3f1dab34-7819-11e5-8dfe-a806449b914e.png)

PS：说实在的，Evernote同步这块，马克飞象很优秀，很多地方值得借鉴，但是价格确实坑爹。。。

**Comment by suziwen** [comment]
这个以前很早就有实现的,后来自己否掉了.

evernote / 印象笔记 不允许有 svg 等标签,所以需要一种更 hack 的方式来实现,但这种hack方式存在一定的数据不安全.

实现的原理就是在 `html` 标签 `span` 上加 `background` ,并且 url 地址是这种base64形式的 `data:image/svg+xml;base64`.

不想使用这种方式,主要考虑的是:

1. 这种做法现在只是一种比较hack的方式,不保证将来 evernote/ 印象笔记 官方为了安全原因,禁用掉,到时数据就会不完整

2. 为了实现  svg 显示公示, 前提还需要该篇文章必须被锁定,以后只能通过特定的编辑器才能重新编辑.
如果你让文章变成非锁定(也就是非readonly)时,再保存成svg,你就会发现这些公式都看不见.

3. 小书匠设计的初衷是文章可以脱离小书匠系统再次使用,不想绑架用户的数据.

**Comment by DereckZhang** [comment]
我之前使用的是马克飞象，现在改用小书匠了，对比一下发现它确实是用这样hack的方式来实现的，看来还是保持png的方式比较好。我对马克飞象最大的担心就是就算我现在付费了，以后万一网站倒了，数据被锁住了，我找谁说理去
