### ISSUE TITLE
使用自动目录的文档无法从印象笔记正确导入

### ISSUE THREAD

**Issue by zhangdoa** [suziwen/markdownxiaoshujiang#933]
如题，所有带有[toc]或[toc!]的文档都无法加载文档末尾的md附件，文档会被打开为HTML解析结果。

**Comment by suziwen** [comment]
我这边正常，没有你说的情况。应该是你通过印象笔记客户端修改了小书匠导出的文件，这种情况下再导入到小书匠时就不会去识别 md 附件了。

--------------

可以在小书匠绑定界面的设置里，把保护文档打开，这样通过小书匠导出的文件在印象笔记客户端就会变成不可修改

![image](https://user-images.githubusercontent.com/57370/45253523-5d372d00-b39b-11e8-9b20-c35cdc1e9230.png)


![image](https://user-images.githubusercontent.com/57370/45253517-455fa900-b39b-11e8-956b-f031ded1fff8.png)

**Comment by zhangdoa** [comment]
打开保护文档后，手动将md文件里的数据重新粘贴了一次，现在已经解决了，谢谢。
