### ISSUE TITLE
evernote同步失败

### ISSUE THREAD

**Issue by yunshuibohen** [suziwen/markdownxiaoshujiang#935]
![image](https://user-images.githubusercontent.com/42466915/45275455-7fda5a80-b4ef-11e8-93c3-94b0e8450d10.png)
看到有更新，同步到evernote仍然失败，请问之前evernote https的bug是否已经修复？

**Comment by suziwen** [comment]
更新到小书匠最新客户端 6.2.1, 然后再重新绑定一下。

**Comment by yunshuibohen** [comment]
感谢，已经OK……

发自我的 iPhone
