### ISSUE TITLE
请问一下小书匠中的标签能否同步到印象笔记的标签中？

### ISSUE THREAD

**Issue by EdwinZhangyc** [suziwen/markdownxiaoshujiang#936]
![image](https://user-images.githubusercontent.com/32889416/45282989-339f1280-b50f-11e8-9bb3-512be71f4d6a.png)
![image](https://user-images.githubusercontent.com/32889416/45283020-46194c00-b50f-11e8-83b1-5e4e50fc071c.png)

**Comment by suziwen** [comment]
可以的。只要元数据格式正确，预览里会有相应的标签，就会同步到印象笔记里的。

![image](https://user-images.githubusercontent.com/57370/45284176-6a2a5c80-b512-11e8-98d3-a35ee3d2575a.png)


![image](https://user-images.githubusercontent.com/57370/45284217-7d3d2c80-b512-11e8-82cd-3d1e5f19eb4a.png)

**Comment by EdwinZhangyc** [comment]
谢谢您，已经解决，需要上边排版时与每个: 之间都留有一个空格。
---
title: 未命名文件 
date: <% print((new Date()).getFullYear().toString()+ '-'+ ((new Date()).getMonth() + 1).toString() + '-'+ (new Date()).getDate().toString()); %>
tags: 
auther: Edwin
grammar_mindmap: true
---
