### ISSUE TITLE
文档的存储位置在哪儿？

### ISSUE THREAD

**Issue by oneweek20169902** [suziwen/markdownxiaoshujiang#939]

**Comment by suziwen** [comment]
web版本存储在本地浏览器自己的数据库里
客户端版本存储位置可以到 `小书匠主按钮>关于` 里查看。

不过文档是存储在数据库里，没办法直接打开。最好自己写完的文档选择导出或者绑定一个第三方存储。

**Comment by oneweek20169902** [comment]
默认路径是什么？

**Comment by oneweek20169902** [comment]
我从html转md文件导致了界面卡死，所以无法查看默认位置

**Comment by suziwen** [comment]
``` 
Windows: %LOCALAPPDATA%/storywriter/ 
Mac: ~/Library/Application Support/storywriter/ 
Linux: ~/.config/storywriter 
```

**Comment by coocoky** [comment]
能不能自定义文档存储位置?

**Comment by suziwen** [comment]
添加启动参数，参考[这里](http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir)
