### ISSUE TITLE
导出为pdf时能指定中文字体吗

### ISSUE THREAD

**Issue by malongshuai** [suziwen/markdownxiaoshujiang#941]
我自定义了default.css里的字体，但是导出为pdf的时候，只有代码部分的字体生效，中文字体没反应。

**Comment by suziwen** [comment]
参考[这里](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-9-24%20%E5%B0%8F%E4%B9%A6%E5%8C%A0%20pdf%20%E5%AF%BC%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%20css%20%E6%95%99%E7%A8%8B.md#pdf-%E6%AD%A3%E6%96%87%E4%BF%AE%E6%94%B9%E5%AD%97%E4%BD%93)

**Comment by malongshuai** [comment]
@suziwen 非常感谢
