### ISSUE TITLE
打开小书匠后，有时会出现未打开预览的情况

### ISSUE THREAD

**Issue by Captain-Alan** [suziwen/markdownxiaoshujiang#944]
当前版本: 6.3.0(6.2.1)
服务器最新版本: 6.3.0

打开小书匠后，有时会出现：
1. 未打开 右侧预览 & 左侧文件目录 的情况
2. 之后，点击open 虽可打开右侧预览 & 左侧文件目录，但，只要鼠标从预览移出，右侧的预览会自动关闭

**Comment by suziwen** [comment]
点击侧边框中间的长方形按钮，就会固定住了。

![image](https://user-images.githubusercontent.com/57370/45752716-ffcb9780-bc48-11e8-9824-d52e0a223db5.png)

**Comment by Captain-Alan** [comment]
嗯，谢谢回复。

是的，在点击侧边框中间的长方形按钮，是固定了，可就是点击此处固定后，有时会出现BUG：只要鼠标从预览移出，右侧的预览会自动关闭

**Comment by Captain-Alan** [comment]
现在暂未再出现这种情况了
