### ISSUE TITLE
为什么github图床出现保存附件失败

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#945]
![sd](https://www.github.com/liao20081228/notebook/raw/master/图片/OSI参考模型和TCP_IP参考模型.md/test.PNG)

**Comment by suziwen** [comment]
我这边能正常使用，没法重现。

**Comment by liao20081228** [comment]
> 我这边能正常使用，没法重现。

我的意思是这样的：我文章和图片都放在github中，然后新建一个文章，保存在github中，然后拉入插入一张本地图片，此时图片可以正确上传到github，但是在我保存文章到github的时候就会出错

**Comment by liao20081228** [comment]
> 我这边能正常使用，没法重现。错误如下：

保存附件失败: https://www.github.com/用户名/目录/文件.jpg, [object ProgressEvent]

**Comment by suziwen** [comment]
按照你的步骤，我还是能正常保存到 github上。

**Comment by liao20081228** [comment]
> 按照你的步骤，我还是能正常保存到 github上。

是的，可以保存但是就是会出错误提示。我感觉是将我上传的图片作为附件进行上传了。
功能正常使用，只是会出现错误提示。。您在使用时没有错误提示吗？难道我使用方法不对吗？我的git图床实际就只是一个用于数据存储的git仓库下的一个目录

**Comment by suziwen** [comment]
嗯，没有错误提示的。

使用方法是对的，可能其他什么因素造成的。

**Comment by suziwen** [comment]
如果使用 github 的绑定存储， 也可以不用指定图床， 新添加的图片系统会自动保存到当前文章所在目录下的  images 文件夹内。

当然通过指定一个 github 图床也可以。 

我这边测试都是可以使用，也没有报错提示。只能再观察一下，看有其他什么没有想到的因素了。
