### ISSUE TITLE
引用中设置文本高亮颜色，文本缺失

### ISSUE THREAD

**Issue by crazyBeer** [suziwen/markdownxiaoshujiang#950]
引用文本中有`code`，并为高亮设置自定义颜色时，引用文本会有丢失。

使用软件：windows x64 6.2.1
相关代码：
//展示：我是引用内容
> 我是==引用内`容`==

//展示：我是容 #800028
> 我是==引用内`容` #800028==

**Comment by suziwen** [comment]
6.7.0 版本已经修复

http://soft.xiaoshujiang.com/download.html
