### ISSUE TITLE
保存到 Evernote ,[TOC] 没有缩进

### ISSUE THREAD

**Issue by Captain-Alan** [suziwen/markdownxiaoshujiang#951]
1. Evernote TOC

![Evernote TOC](https://i.loli.net/2018/09/26/5bab258e2b5d5.jpg)

2. 小书匠 TOC

![小书匠 TOC](https://i.loli.net/2018/09/26/5bab25a3d6831.jpg)

**Comment by suziwen** [comment]
我这边用最新的小书匠保存后查看 evernote  web 版本正常。

**Comment by Captain-Alan** [comment]
下面是与 马克飞象 的截图对比，希望能尽快解决这个问题，发布到Evernote后，[TOC] 没有了`<ul>`、`<li>`，都被替换成`<div>`：

1. 马克飞象

![IMG-马克飞象.png](https://i.loli.net/2018/09/28/5bae2dd0c20d8.png)
<BR/><BR/><BR/><BR/>
![IMG-马克飞象2.png](https://i.loli.net/2018/09/28/5bae2dd0d376d.png)
<BR/><BR/><BR/><BR/><BR/><BR/>

2. 小书匠

![IMG-小书匠.png](https://i.loli.net/2018/09/28/5bae2dd0e0ea4.png)
<BR/><BR/><BR/><BR/>
![IMG-小书匠2.png](https://i.loli.net/2018/09/28/5bae2dd1ae7bc.png)
<BR/><BR/><BR/><BR/><BR/><BR/>

3. 发布到Evernote的截图

![IMG-发布到Evernote的马克飞象TOC.png](https://i.loli.net/2018/09/28/5bae2dd0ad976.png)
<BR/><BR/><BR/><BR/>
![IMG-发布到Evernote的小书匠TOC.png](https://i.loli.net/2018/09/28/5bae2dd0b2812.png)
<BR/><BR/><BR/><BR/><BR/><BR/>

**Comment by suziwen** [comment]
我这边正常，没法重现你说的情况

![image](https://user-images.githubusercontent.com/57370/46213586-811eda80-c36b-11e8-9c72-6d3a0401c2f8.png)


![image](https://user-images.githubusercontent.com/57370/46213658-c0e5c200-c36b-11e8-8b81-71a51c023d23.png)

**Comment by Captain-Alan** [comment]
你那用的是旧版本的Evernote网页版，在Evenote旧版本上，我这边也正常：
![IMG-old-evernote.png](https://i.loli.net/2018/09/29/5baed713d491b.png)
<BR/><BR/><BR/><BR/>
但，新版Evenote网页版，却与Evenote客户端一样：
![IMG-new-evenote.png](https://i.loli.net/2018/09/29/5baed713b0284.png)
<BR/><BR/><BR/><BR/>
Evernote客户端程序：
![IMG-evernote-client.png](https://i.loli.net/2018/09/29/5baed713dfe94.png)
<BR/><BR/><BR/><BR/>

**Comment by suziwen** [comment]
可以先自定义 css 样式

``` css
.toc ul{
list-style: unset;
list-style-type: none; 
}
```

**Comment by Captain-Alan** [comment]
OK
