### ISSUE TITLE
现阶段小书匠支持Latex公式吗？

### ISSUE THREAD

**Issue by HowardMaCloud** [suziwen/markdownxiaoshujiang#955]
如题，看到语法选项里有这个示例，但是自己使用的时候发现这个好像是无法使用的，在使用手册里关于公式一项，貌似左右两边是一样的，也未转换成数学公式的样子。

**Comment by suziwen** [comment]
支持 Latex 公式的，估计你的元数据没有写正确,导致元数据的语法开关失效。

--------

也可以全局打开，直接在 `小书匠主按钮>设置>语法扩展` 里把 mathjax 数学公式选项打开。

![image](https://user-images.githubusercontent.com/57370/46242015-6a24ca80-c3f5-11e8-9252-4781eba91631.png)

**Comment by HowardMaCloud** [comment]
谢谢，我在单个文本里打开这个开关没有作用（试过直接把这个语法复制，发现无效；也重新查看语法手册里关于公式的讲解，发现也失效了）
刚刚在全局打开了这个开关，问题解决，语法手册里的公式也显示正常
再次感谢您的帮助！
