### ISSUE TITLE
能否在添加第三方存储后增加自动同步功能

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#956]
能够在添加第三方存储后增加自动同步功能？现在虽然可以保存到第三方，但是每次修改后都需要手动保存，感觉很不方便呢？

**Comment by suziwen** [comment]
这个选择为默认第三方存储后，按保存按钮(或者快捷键 `ctrl+s`)，就会自动保存同步到对应的第三方存储上。

暂不考虑系统自动检测用户每次修改文章就自动同步的功能。一个是很多第三方平台有单位时间 api 调用次数限制，再一个每次修改都自动同步，有历史记录功能的第三方存储也会产生太多记录。
