### ISSUE TITLE
块代码内文字格式渲染错误

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#96]
当`设置`-`语法扩展`-`段代码显示行号`属性打开时，块代码内文字格式会渲染错误向右偏移2em，如下图所示：
![image](https://cloud.githubusercontent.com/assets/7668825/10687092/fa8db808-799c-11e5-8bde-82fbd7ba42fd.png)

**Comment by suziwen** [comment]
客户端1.7.1已经更新解决,可以到 http://soft.xiaoshujiang.com 下载
