### ISSUE TITLE
在表格中使用html空格标签无法正确设置行宽

### ISSUE THREAD

**Issue by liao20081228** [suziwen/markdownxiaoshujiang#960]
由于第三列内容过长的原因，我不希望markdown对第一列和第二列，换行显示，在其它编辑其中，可以采取新增一行，并在对应的单元格中用足够的数量的`&emsp;`来控制宽度。而在xiaoshujiang 无法正确使用。  比如在github中：

```
|短选项|长选项|描述|
|:--|:--|:--|
|-b, -m||为了兼容性，忽略这些选项|
|-B|--always-make|无条件重建所有目标，即使目标是最新的|
|-C dir|--directory=dir|切换到dir目录，读取并执行makefile文件。默认当前目录。使用多个-C命令行选项时，后一个指定的目录是前一个指定的目录的子目录。|
|-d||打印大量调试信息。调试信息指出正在考虑重新创建哪些文件，正在比较哪些文件时间以及结果如何，哪些文件真的需要重编译，哪些隐式规则会被考虑并应用|
||--debug[=FLAGS]|打印各种调试信息。如果FLAGS被省略，则与-d相同。FLAGS为b适用于基本调试，v适用于更详细的基本调试，i适用于显示隐式规则，j适用于调用命令的详细信息，m适用于调试时重新生成文件。n禁用所有以前的调试标志。|
|-e|--environment-overrides|系统环境变量将覆盖 makefile 中定义的同名变量|
|**-f FILE**| --file=file, --makefile=FILE|读取FILE作为一个makefile。默认读取GNUmakefile、makefile、Makefile
|-h|打印帮助消息。
|**-i**|--ignore-errors|执行某个命令时如果发生错误则忽略并继续往下执行，不指定该选项则停止
|**-I dir**|--include-dir=dir|指定makefile中引入的其它makefile文件的搜索目录，使用多个-I 选项时，make 将按照顺序依次在 dir目录下搜索
|**-j [N]**|--jobs[=jobs] |同时允许N个任务；无参数表明允许无限个任务。如果多个-j选项，则最后一个有效
|**-k**|--keep-going|当某些目标无法创建时尽可能多的继续。
|-l [N]|--load-average[=load]|不开始新的作业除非系统负载低于N。省略N则删除之前ed负载限制
|-L|--check-symlink-times|在符号链接和目标之间使用最新的mtime。
|**-n**|--just-print, --dry-run, --recon|仅显示要执行的命令，但不执行命令。
|-o FILE|--old-file=file, --assume-old=file| 强制将FILE认作非常老，不要重新 make 它。
|-O[type]|--output-sync[=type]|当与-j并行运行多个作业时，确保每个作业的输出都被收集在一起，而不是散布在其他作业的输出中。如果type被省略或是target，则将每个目标的输出组在一起。如果type是line，每个命令的输出将被组在一起。如果type是recurse，则整个递归make的输出被组在一起。如果type是none，则禁用输出同步。
|-p|--print-data-base|打印读取makefile所产生的数据库（规则和变量值）
|-q|--question|不运行任何命令；退出状态为0则目标已全部更新。
|-r|--no-builtin-rules|禁用内置隐含规则。  同时清除后缀规则的默认后缀列表。
|-R|--no-builtin-variables|禁用内置变量设置。
|**-s**|--silent, --quiet|执行时不打印执行的命令。
|-S|--no-keep-going, --stop|关闭 -k。除非在递归make中-k可能通过MAKEFLAGS从顶层make继承，或者在环境中的MAKEFLAGS中设置-k，否则该选项是不需要的。
|-t|--touch |使用touch将目标的时间标记为最新，而不是重新创建它们。
||--trace|打印每个目标的处置信息（为什么要重建目标以及运行哪些命令来重建目标）。
|-v| --version|打印 make 的版本号并退出。
|-w|--print-directory |在其它处理前后打印工作目录。
||--no-print-directory|即使 -w 隐式开启，也要关闭 -w。
|-W FILE|--what-if=file, --new-file=file,<br> --assume-new=file|将 FILE 认作无限新。
||--warn-undefined-variables|当引用未定义的变量打印警告信息。
|&emsp;&emsp;&emsp;&emsp;|&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;||

```

显示如下：

|短选项|长选项|描述|
|:--|:--|:--|
|-b, -m||为了兼容性，忽略这些选项|
|-B|--always-make|无条件重建所有目标，即使目标是最新的|
|-C dir|--directory=dir|切换到dir目录，读取并执行makefile文件。默认当前目录。使用多个-C命令行选项时，后一个指定的目录是前一个指定的目录的子目录。|
|-d||打印大量调试信息。调试信息指出正在考虑重新创建哪些文件，正在比较哪些文件时间以及结果如何，哪些文件真的需要重编译，哪些隐式规则会被考虑并应用|
||--debug[=FLAGS]|打印各种调试信息。如果FLAGS被省略，则与-d相同。FLAGS为b适用于基本调试，v适用于更详细的基本调试，i适用于显示隐式规则，j适用于调用命令的详细信息，m适用于调试时重新生成文件。n禁用所有以前的调试标志。|
|-e|--environment-overrides|系统环境变量将覆盖 makefile 中定义的同名变量|
|**-f FILE**| --file=file, --makefile=FILE|读取FILE作为一个makefile。默认读取GNUmakefile、makefile、Makefile
|-h|打印帮助消息。
|**-i**|--ignore-errors|执行某个命令时如果发生错误则忽略并继续往下执行，不指定该选项则停止
|**-I dir**|--include-dir=dir|指定makefile中引入的其它makefile文件的搜索目录，使用多个-I 选项时，make 将按照顺序依次在 dir目录下搜索
|**-j [N]**|--jobs[=jobs] |同时允许N个任务；无参数表明允许无限个任务。如果多个-j选项，则最后一个有效
|**-k**|--keep-going|当某些目标无法创建时尽可能多的继续。
|-l [N]|--load-average[=load]|不开始新的作业除非系统负载低于N。省略N则删除之前ed负载限制
|-L|--check-symlink-times|在符号链接和目标之间使用最新的mtime。
|**-n**|--just-print, --dry-run, --recon|仅显示要执行的命令，但不执行命令。
|-o FILE|--old-file=file, --assume-old=file| 强制将FILE认作非常老，不要重新 make 它。
|-O[type]|--output-sync[=type]|当与-j并行运行多个作业时，确保每个作业的输出都被收集在一起，而不是散布在其他作业的输出中。如果type被省略或是target，则将每个目标的输出组在一起。如果type是line，每个命令的输出将被组在一起。如果type是recurse，则整个递归make的输出被组在一起。如果type是none，则禁用输出同步。
|-p|--print-data-base|打印读取makefile所产生的数据库（规则和变量值）
|-q|--question|不运行任何命令；退出状态为0则目标已全部更新。
|-r|--no-builtin-rules|禁用内置隐含规则。  同时清除后缀规则的默认后缀列表。
|-R|--no-builtin-variables|禁用内置变量设置。
|**-s**|--silent, --quiet|执行时不打印执行的命令。
|-S|--no-keep-going, --stop|关闭 -k。除非在递归make中-k可能通过MAKEFLAGS从顶层make继承，或者在环境中的MAKEFLAGS中设置-k，否则该选项是不需要的。
|-t|--touch |使用touch将目标的时间标记为最新，而不是重新创建它们。
||--trace|打印每个目标的处置信息（为什么要重建目标以及运行哪些命令来重建目标）。
|-v| --version|打印 make 的版本号并退出。
|-w|--print-directory |在其它处理前后打印工作目录。
||--no-print-directory|即使 -w 隐式开启，也要关闭 -w。
|-W FILE|--what-if=file, --new-file=file,<br> --assume-new=file|将 FILE 认作无限新。
||--warn-undefined-variables|当引用未定义的变量打印警告信息。
|&emsp;&emsp;&emsp;&emsp;|&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;||

**Comment by suziwen** [comment]
可以自定义 css 样式

``` css
.table{
word-break: initial;
}
```

**Comment by liao20081228** [comment]
虽然这个方式可以，但是还是希望能修复这个bug

> 可以自定义 css 样式
> 
> ```css
> .table{
> word-break: initial;
> }
> ```
