### ISSUE TITLE
win10上6.2.1版本64位保存到印象笔记一直显示处理文件关联格式失败

### ISSUE THREAD

**Issue by LiamCodesX** [suziwen/markdownxiaoshujiang#966]
自从8月份出现这个情况后，更新也无法解决，只有网页版的可以保存成功

**Comment by suziwen** [comment]
可以试下 32 位版本。#934

目前我这边 64 位的无法重现，可以正常保存到印象笔记。

**Comment by LiamCodesX** [comment]
换了32位的版本后还是出现一样的问题

**Comment by LiamCodesX** [comment]
已经解决，原因在于我自定义了预览区的CSS样式，删除后一切正常
