### ISSUE TITLE
mac不能全屏

### ISSUE THREAD

**Issue by sunweilibo** [suziwen/markdownxiaoshujiang#967]
为什么不设计成全屏，可以划屏呢

**Comment by suziwen** [comment]
我记得是可以全屏的，通过全屏编辑按钮，或全屏预览按钮进入全屏模式。

你说的全屏是什么概念？

**Comment by sunweilibo** [comment]
编辑可以实时预览的时候

**Comment by suziwen** [comment]
6.7.0 版本已经提供

http://soft.xiaoshujiang.com/download.html
