### ISSUE TITLE
形如**[text]**格式渲染错误

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#97]
形如`**[text]**`格式渲染错误，会忽略加粗，除非前后再加空格才能渲染正确，如下所示：
1.正常
![image](https://cloud.githubusercontent.com/assets/7668825/10696686/e2e0f988-79db-11e5-8a37-1e69fe736032.png)
2.没有渲染加粗
![image](https://cloud.githubusercontent.com/assets/7668825/10696766/5cc700b2-79dc-11e5-8b7f-22e03c0932c0.png)
3.添加空格后渲染正常，但在轻量编辑器中显示不正常
![image](https://cloud.githubusercontent.com/assets/7668825/10696815/ad619406-79dc-11e5-8317-a94940e28b5c.png)

**Comment by suziwen** [comment]
系统基础的语法使用的是 commonmark, 出现这种情况的原因好像是为了解决 `*` 逻辑容易出现混乱的原因,具体可以看 commonmark 的这段要求 [right-flanking delimiter run ](http://spec.commonmark.org/0.18/#right-flanking-delimiter-run) (英文不好,我也就没详细看)

这是关于这个的讨论
jgm/CommonMark#317

兼容性可以到这里来测试

[测试粗体等](http://johnmacfarlane.net/babelmark2/?text=**%E8%AF%B4%E6%98%8E**%E6%AD%A4%E9%A2%98%0A%0A**%5B%E8%AF%B4%E6%98%8E%5D**%E6%AD%A4%E9%A2%98%0A%0A**%5B%E8%AF%B4%E6%98%8E%5D**+%E6%AD%A4%E9%A2%98)
