### ISSUE TITLE
关于附件

### ISSUE THREAD

**Issue by BianChengNan** [suziwen/markdownxiaoshujiang#977]
有一个关于附件的问题困扰我很久了，看了帮助文档，在网上搜了很多资料都没解决！
我想添加一个txt或者json或者其它非图片格式的文件作为附件，每次打开的时候都提示下面的错误。
不知道是我添加的方式不对？还是哪里操作有问题？希望有知道的朋友帮忙解答下，谢谢啦！大赞小书匠。

![default](https://user-images.githubusercontent.com/5259514/47952010-c0140180-dfa3-11e8-886e-b2e4349c19f3.png)

![default](https://user-images.githubusercontent.com/5259514/47951987-79260c00-dfa3-11e8-9d13-54af50b21cfb.png)

![default](https://user-images.githubusercontent.com/5259514/47951975-60b5f180-dfa3-11e8-89ef-5afcd730f8dc.png)

**Comment by suziwen** [comment]
元数据里添加 `grammar_attachment: true`

![image](https://user-images.githubusercontent.com/57370/47952463-c9549c80-dfaa-11e8-87ad-76f388a1761e.png)

------

其实如果你在`小书匠主按钮>设置>预览`里 ,把自动识别图片扩展名打开的话，使用图片语法一样可以显示成附件形式.
![image](https://user-images.githubusercontent.com/57370/47952480-f1440000-dfaa-11e8-89ae-50c048de2a1b.png)

![image](https://user-images.githubusercontent.com/57370/47952492-2f412400-dfab-11e8-940a-271562ae7983.png)
