### ISSUE TITLE
公式中的中文导出后空白

### ISSUE THREAD

**Issue by DereckZhang** [suziwen/markdownxiaoshujiang#98]
公式中含有中文时，预览正常，但导出为inlineStylesheet:true+svg转图片（或pdf、word、同步到Evernote）时，无法正常转换，中文所在位置显示空白：
![image](https://cloud.githubusercontent.com/assets/7668825/10704255/24684970-7a08-11e5-9248-47ee35255083.png)

PS：公式中的中文，预览时还不错，转出来却变得很丑，感觉调用的字体不太对。

**Comment by suziwen** [comment]
web版没问题，客户端出错了

**Comment by DereckZhang** [comment]
我这边测试在Web版也有问题，例如下列公式：

```latex
$$
\left\{ \begin{matrix}
\begin{array}{r}
\textrm{古：}\\
\textrm{今中：}\\
\textrm{将来：}\\
\vphantom{\begin{array}{c}
1\\
2
\end{array} }\textrm{外：}
 \end{array} & \begin{array}{l}
\textrm{历史水平}\\
\textrm{经济周期}\\
\textrm{价格预期}\\
\left\{ \begin{array}{l}
\textrm{汇率}\\
\textrm{国际利率水平}
\end{array} \right. \textrm{（二率）}
\end{array}
\end{matrix} \right. 
$$
```
在Web版，其他设置均为默认，除了打开了mathjax，导出设置如下：
![image](https://cloud.githubusercontent.com/assets/7668825/10709318/8baea05a-7a5a-11e5-8dbb-652ad3de2faf.png)
中文显示为空格

**Comment by suziwen** [comment]
web版和客户端版字体样式确实没带上.
web版中文不会变空白,客户端版会消失.

**Comment by suziwen** [comment]
好了,web版(1.7.1)强制刷新一下,就能看到结果了.
顺便把代码内文字格式和带编号的公式图片也修了下.

**Comment by suziwen** [comment]
你那边web中文还会是空白?

**Comment by DereckZhang** [comment]
好了！已经修复了

**Comment by DereckZhang** [comment]
客户端会更新吗？

**Comment by suziwen** [comment]
会,不过得等下个大版本吧,不是特别急的错误不会频繁更新客户端版本的.

**Comment by suziwen** [comment]
客户端1.7.1已经更新解决,可以到 http://soft.xiaoshujiang.com 下载
