### ISSUE TITLE
BUG-界面经常混乱

### ISSUE THREAD

**Issue by yzymarvin** [suziwen/markdownxiaoshujiang#99]
![image](https://cloud.githubusercontent.com/assets/12823291/10714904/e4004360-7b3d-11e5-97d6-9cbbae7e12a4.png)
界面经常混乱，如图所示，下方出现不明预览窗口，上方的工具栏消失。重启以后恢复。出现概率相当高。
版本1.70  
win10

非常喜欢你们的客户端  祝越来越好

**Comment by suziwen** [comment]
#65

**Comment by suziwen** [comment]
能大概说下重现步骤吗，我这边客户端没法重现。

比如是点击了导出功能，然后再点机其他某个位置就出现这种情形？

**Comment by yzymarvin** [comment]
重启之后，出现的次数比较少了，但是偶尔还是会出现
我初步发现在使用windows的分屏功能是比较容易出现，比如将小书匠放在屏幕的左侧，右边浏览网页或者看视频，经常性地来回操作就比较容易紊乱。
[系统是win10],
