### ISSUE TITLE
标记高亮无法选择颜色？？？

### ISSUE THREAD

**Issue by WuShaogui** [suziwen/markdownxiaoshujiang#992]
本人系统是linuxmint19,以前小书匠是可以选颜色的，从前几个版本开始，高亮就是绿色，没发选，情况如下：
![image](https://user-images.githubusercontent.com/24794718/48480637-10158280-e846-11e8-912d-4e2ed668009f.png)

**Comment by suziwen** [comment]
看使用的内置编辑器是否是 codemirror, 还有就是在 `设置>编辑器>codemirror>颜色选择器` 功能是否选中。

**Comment by WuShaogui** [comment]
> 看使用的内置编辑器是否是 codemirror, 还有就是在 `设置>编辑器>codemirror>颜色选择器` 功能是否选中。

编辑器问题，我使用ace编辑器，无法选择颜色
