### ISSUE TITLE
绑定github不成功

### ISSUE THREAD

**Issue by kingcourage** [suziwen/markdownxiaoshujiang#999]
用软件绑定不成功，报错，但是没有报错信息，用浏览器打开也这样，打开F12发现有下面的信息，什么原因呀
![image](https://user-images.githubusercontent.com/21072475/48992558-4cfd4580-f173-11e8-8fa9-098608bc6164.png)

**Comment by pkptzx** [comment]
多试几次吧.有可能是网络的问题.
我正常...

**Comment by pkptzx** [comment]
偶尔还会遇到无法保存到GitHub上.但网页/本地git 都正常.多试几次或重新开软件就好了.

**Comment by kingcourage** [comment]
> 多试几次吧.有可能是网络的问题.
> 我正常...

用github我还是一直不成功，我绑到gitlab上成功了

**Comment by suziwen** [comment]
我这边正常，无法重现。
